In [16]:
#RUN QUESTO (1)

import os 
os.environ["CUDA_VISIBLE_DEVICES"]="0"

In [17]:
#RUN QUESTO (2)

# check GPU

import torch
print(torch.cuda.is_available())

True

In [18]:
#RUN QUESTO (3)

# Libraries

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import random
import pickle
from sklearn.decomposition import PCA
#from scipy.sparse import coo_matrix
from torch_geometric.data import HeteroData
from torch_geometric.utils import from_scipy_sparse_matrix
import torch_geometric.transforms as T
from torch_geometric.transforms import AddMetaPaths
from torch_geometric.nn import Linear, to_hetero
from torch_geometric.nn.conv import GATv2Conv
from sklearn.metrics import f1_score, roc_auc_score

fname_base = 'DyHANE/'
base = '2019-2021/' #'2019-2022/'
new = '2022/'

BASE MODEL

In [21]:
# load node features

AX = torch.load(fname_base+base+'features/AX_tensor.pt') 
AY = torch.load(fname_base+base+'features/AY_tensor.pt')
PX = torch.load(fname_base+base+'features/PX_tensor.pt')
IX = torch.load(fname_base+base+'features/IX_tensor.pt')

In [22]:
print(AX.shape)
print(PX.shape)
print(IX.shape)

torch.Size([13116, 389])
torch.Size([8641, 779])
torch.Size([1612, 489])

In [23]:
#Optional: same dimnsion for all node types

from sklearn.decomposition import PCA

dim=128 #32 #64

pca_author=PCA(n_components=dim).fit(AX)
pca_paper=PCA(n_components=dim).fit(PX)
pca_institution=PCA(n_components=dim).fit(IX)

In [24]:
# Load edges

AP = pd.read_csv(fname_base+base+'AP_map.csv')[['author', 'paper']] #new
#AP_coo = coo_matrix(AP.values.T)
AP_tensor = torch.tensor(AP.values.T)

PA = pd.read_csv(fname_base+base+'AP_map.csv')[['paper', 'author']]
#PA_coo = coo_matrix(PA.values.T)
PA_tensor = torch.tensor(PA.values.T)

PP = pd.read_csv(fname_base+base+'PP_map.csv')[['citing', 'cited']]
#PP_coo = coo_matrix(PP.values.T)
PP_tensor = torch.tensor(PP.values.T)

PP_rev = pd.read_csv(fname_base+base+'PP_map.csv')[['cited', 'citing']]
#PP_rev_coo = coo_matrix(PP_rev.values.T)
PP_rev_tensor = torch.tensor(PP_rev.values.T)

AI = pd.read_csv(fname_base+base+'AI_map.csv')
#AI_coo = coo_matrix(AI.values.T)
AI_tensor = torch.tensor(AI.values.T)

IA = AI[['institution_id', 'author_id']]
#IA_coo = coo_matrix(IA.values.T)
IA_tensor = torch.tensor(IA.values.T)

In [25]:
# Build HeteroData

data = HeteroData()

data['author'].x = torch.tensor(pca_author.transform(AX)).float()# qui
data['author'].y = AY
data['paper'].x = torch.tensor(pca_paper.transform(PX)).float()
data['institution'].x = torch.tensor(pca_institution.transform(IX)).float()

data['author', 'writes', 'paper'].edge_index = AP_tensor
data['paper', 'is_written_by', 'author'].edge_index = PA_tensor
data['paper', 'cites', 'paper'].edge_index = PP_tensor
data['paper', 'is_cited_by', 'paper'].edge_index = PP_rev_tensor
data['author', 'is_affiliated_with', 'institution'].edge_index = AI_tensor
data['institution', 'has_affiliated', 'author'].edge_index = IA_tensor

#data['paper', 'cites', 'paper'].edge_attr = ... # [num_edges_cites, num_features_cites]

#reversed edges explicitly added since ---data = T.ToUndirected()(data)--- is not working for edges between nodes of same type

print(data.node_types)
print(data.num_nodes)
print(data.edge_types)
print(data.num_edges)

#data = data.pin_memory()
#data = data#.to('cuda:0', non_blocking=True)

['author', 'paper', 'institution']
23369
[('author', 'writes', 'paper'), ('paper', 'is_written_by', 'author'), ('paper', 'cites', 'paper'), ('paper', 'is_cited_by', 'paper'), ('author', 'is_affiliated_with', 'institution'), ('institution', 'has_affiliated', 'author')]
40628

In [26]:
#Add metapaths

metapaths = [[('author', 'paper'), ('paper', 'author')], #APA
             [('author', 'paper'), ('paper', 'is_cited_by', 'paper'), ('paper', 'author')], #APPA
             [('author', 'institution'), ('institution', 'author')]] #AIA
data = AddMetaPaths(metapaths, weighted=True)(data)

In [27]:
data

HeteroData(
  metapath_dict={
    (author, metapath_0, author)=[2],
    (author, metapath_1, author)=[3],
    (author, metapath_2, author)=[2],
  },
  author={
    x=[13116, 128],
    y=[13116],
  },
  paper={ x=[8641, 128] },
  institution={ x=[1612, 128] },
  (author, writes, paper)={ edge_index=[2, 16020] },
  (paper, is_written_by, author)={ edge_index=[2, 16020] },
  (paper, cites, paper)={ edge_index=[2, 113] },
  (paper, is_cited_by, paper)={ edge_index=[2, 113] },
  (author, is_affiliated_with, institution)={ edge_index=[2, 4181] },
  (institution, has_affiliated, author)={ edge_index=[2, 4181] },
  (author, metapath_0, author)={
    edge_index=[2, 57736],
    edge_weight=[57736],
  },
  (author, metapath_1, author)={
    edge_index=[2, 302],
    edge_weight=[302],
  },
  (author, metapath_2, author)={
    edge_index=[2, 18507],
    edge_weight=[18507],
  }
)

In [12]:
print(data.has_isolated_nodes())
print(data.has_self_loops())
print(data.is_undirected())

#data.edge_types
#data['author', 'writes', 'paper'].edge_index
#print(torch.max(data['author', 'writes', 'paper'].edge_index))

#data.x_dict
#data.edge_index_dict
#data.metapath_dict

True
True
False

In [28]:
# Train - Val - Test split: random

import torch_geometric.transforms as T

#transform = T.compose([T.NormalizeFeatures(), T.RandomNodeSplit()])
transform = T.RandomNodeSplit()
data = transform(data)

In [12]:
print('Autori effettivi training:', data['author'].train_mask.count_nonzero())
print('Autori effettivi testing:', data['author'].test_mask.count_nonzero()) #testo su 1000 (500 val)

Autori effettivi training: tensor(11616)
Autori effettivi testing: tensor(1000)

In [19]:
#RUN QUESTO (4)

# Methods for statistics computation

from statistics import stdev

def process_metric(df, col):
    data = df[col]
    media = data.mean()
    st_dev = stdev(data.tolist())
    return media, st_dev

#df = pd.DataFrame(columns=['F1_micro', 'F1_macro', 'F1_weighted', 'ROC-AUC'])
def processing_results(df):
    res = pd.DataFrame(columns=df.columns) #columns=['F1_micro', 'F1_macro', 'F1_weighted', 'ROC-AUC']
    
    #Compute mean and standard deviation
    for col in df.columns:
        lista = df[col].tolist()
        media, st_dev = process_metric(df, col)
        stringa = "{:0.4f}".format(media)+u"\u00B1"+"{:0.4f}".format(st_dev)
        lista.append(stringa)
        res[col] = lista

    return res

In [20]:
#RUN QUESTO (5)

# GNN

class GAT(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels, dropout=0):
        super().__init__()
        self.conv1 = GATv2Conv((-1, -1), hidden_channels, add_self_loops=False, dropout=dropout)
        self.lin1 = Linear(-1, hidden_channels)
        self.conv2 = GATv2Conv((-1, -1), out_channels, add_self_loops=False, dropout=dropout)
        self.lin2 = Linear(-1, out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index) + self.lin1(x.relu()) #self.lin1(x) 
        x = x.relu()
        x = self.conv2(x, edge_index) + self.lin2(x.relu()) #self.lin2(x)
        return x

In [6]:
# Model training    

def train_node_classifier(model, data, optimizer, criterion, n_epochs=200): 

    for epoch in range(1, n_epochs + 1):
        model.train()
        optimizer.zero_grad()
        out = model(data.x_dict, data.edge_index_dict)#['author'] #davide
        mask = data['author'].train_mask
        #loss = F.cross_entropy(out[mask], data['author'].y[mask])
        #loss = criterion(out[graph.train_mask], graph.y[graph.train_mask])
        loss = criterion(out['author'][mask], data['author'].y[mask]) #davide
        #loss = criterion(out[mask], data['author'].y[mask])
        loss.backward()
        optimizer.step()

        #pred = (out.x_dict, out.edge_index_dict).argmax(dim=-1)
        pred = out['author'].argmax(dim=1) ## Use the class with highest probability. #con davide
        #pred = out.argmax(dim=1)
        f1_micro, f1_macro, f1_weigh, auc = eval_node_classifier(model, data) #, auc

        if epoch % 20 == 0:
            print(f'Epoch: {epoch:03d}, Train Loss: {loss:.3f}, Val f1_micro: {f1_micro:.3f}')

    return model


def eval_node_classifier(model, data):

    model.eval()
    with torch.no_grad():
        #pred = model(data['author']).argmax(dim=1)
        #pred = model(data.x_dict, data.edge_index_dict).argmax(dim=-1) 
        pred = model(data.x_dict, data.edge_index_dict)['author'].argmax(dim=-1)
        pred_prob = torch.nn.functional.softmax(model(data.x_dict, data.edge_index_dict)['author'], -1)
        #print(pred_prob[0].sum())
        #pred_prob = model(data.x_dict, data.edge_index_dict)['author'] #prova per auc
        mask = data['author'].val_mask
        #acc = (pred[mask] == data['author'].y[mask]).sum() / mask.sum()
        correct = (pred[mask] == data['author'].y[mask]).sum()
        #acc = int(correct) / int(mask.sum())
        f1_micro = f1_score(data['author'].y.cpu(), pred.cpu(), average='micro')
        f1_macro = f1_score(data['author'].y.cpu(), pred.cpu(), average='macro')
        f1_weigh = f1_score(data['author'].y.cpu(), pred.cpu(), average='weighted')
        #servono predicted probabilities, 8 classes
        auc = roc_auc_score(data['author'].y.cpu(), pred_prob.cpu().detach().numpy(), average='macro', multi_class='ovo')
        return f1_micro, f1_macro, f1_weigh, auc
  
  
num_run = 5
l_micro = []
l_macro = []
l_weigh = []
l_auc = []
for run in range(num_run):
    print('##### RUN '+str((run+1))+' #####')

    model = None
    model = GAT(hidden_channels=64, out_channels=8, dropout=0.4) #num_classes
    model = to_hetero(model, data.metadata(), aggr='sum')

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    data, model = data.to(device), model.to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=0.005, weight_decay=0.001) #lr=0.005
    weights = torch.tensor([1.5, 1.5, 1, 1, 1, 1, 1.5, 1]).float().to(device)
    criterion = nn.CrossEntropyLoss(weights) #F.cross_entropy()

    model = train_node_classifier(model, data, optimizer, criterion, n_epochs=500) #500

    torch.save(model.state_dict(), fname_base+base+'base_model.pth')

    f1_micro, f1_macro, f1_weigh, auc = eval_node_classifier(model, data) #, auc
    #print(f'Test Eval: {test_ev:.3f}')
    print(f'f1-micro: {f1_micro:.3f}, f1-macro: {f1_macro:.3f}, f1-weighted: {f1_weigh:.3f}, roc-auc: {auc:.3f}')

    l_micro.append(f1_micro)
    l_macro.append(f1_macro)
    l_weigh.append(f1_weigh)
    l_auc.append(auc)

df = pd.DataFrame(columns=['F1_micro', 'F1_macro', 'F1_weighted', 'ROC-AUC'])
df['F1_micro'] = l_micro
df['F1_macro'] = l_macro
df['F1_weighted'] = l_weigh
df['ROC-AUC'] = l_auc
df_ok = processing_results(df)
df_ok.to_excel(fname_base+base+'results_base_model.xlsx', index=False)

##### RUN 1 #####

NameError: name 'data' is not defined

In [21]:
#RUN QUESTO (6)

# Model loading

def load_model(hidden_channels,out_channels,dropout,data,weigths_filename):
    model = GAT(hidden_channels, out_channels,dropout)
    model = to_hetero(model, data.metadata(), aggr='sum')

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    data, model = data.to(device), model.to(device)

    with torch.no_grad():
        model.eval()
        model(data.x_dict, data.edge_index_dict)
        model.train()
    model.load_state_dict(torch.load(weigths_filename))
    return model

In [32]:
# Alternative to training: load saved model  

def eval_node_classifier(model, data):

    model.eval()
    with torch.no_grad(): 
        pred = model(data.x_dict, data.edge_index_dict)['author'].argmax(dim=-1)
        pred_prob = torch.nn.functional.softmax(model(data.x_dict, data.edge_index_dict)['author'], -1)
        mask = data['author'].val_mask
        correct = (pred[mask] == data['author'].y[mask]).sum()
        f1_micro = f1_score(data['author'].y.cpu(), pred.cpu(), average='micro')
        f1_macro = f1_score(data['author'].y.cpu(), pred.cpu(), average='macro')
        f1_weigh = f1_score(data['author'].y.cpu(), pred.cpu(), average='weighted')
        #servono predicted probabilities, 8 classes
        auc = roc_auc_score(data['author'].y.cpu(), pred_prob.cpu().detach().numpy(), average='macro', multi_class='ovo')
        return f1_micro, f1_macro, f1_weigh, auc
  
model = GAT(hidden_channels=64, out_channels=8, dropout=0.4) #num_classes
model = to_hetero(model, data.metadata(), aggr='sum')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
data, model = data.to(device), model.to(device)

##LOAD SAVED MODEL
model = load_model(64,8,0.4,data,fname_base+base+'model.pth')

f1_micro, f1_macro, f1_weigh, auc = eval_node_classifier(model, data) #, auc
#print(f'Test Eval: {test_ev:.3f}')
print(f'f1-micro: {f1_micro:.3f}, f1-macro: {f1_macro:.3f}, f1-weighted: {f1_weigh:.3f}, , roc-auc: {auc:.3f}')

f1-micro: 0.644, f1-macro: 0.639, f1-weighted: 0.645, , roc-auc: 0.927

In [15]:
results = pd.read_excel(fname_base+base+'results_base_model.xlsx') 
print(results)

        F1_micro       F1_macro    F1_weighted        ROC-AUC
0       0.703644       0.701783       0.703872        0.94686
1       0.700442       0.696709       0.700083       0.945297
2       0.704483       0.701229       0.704601       0.946149
3       0.697088       0.693574       0.696932       0.944393
4       0.708676       0.705864        0.70914       0.947448
5  0.7029±0.0044  0.6998±0.0048  0.7029±0.0046  0.9460±0.0012

In [20]:
# Explainer

from torch_geometric.explain import Explainer, CaptumExplainer
explainer = Explainer(
    model=model,
    algorithm=CaptumExplainer('IntegratedGradients'), #InputXGradient
    explanation_type='phenomenon', #model's beahviour (model) vs individual predictions (phenomenon)
    node_mask_type='attributes', #attributes #'CaptumExplainer' only supports 'node_mask_type' None or 'attributes' (got 'object')
    edge_mask_type=None,
    model_config=dict(
        mode='multiclass_classification',
        task_level='node', 
        return_type='probs', #log_probs, raw
                                                                                                                                                 
    ),
)

#indices = torch.arange(13116)
#indices = torch.from_numpy(np.expand_dims(torch.arange(13116), axis=0))
with torch.no_grad():
    explanation = explainer(data.x_dict, data.edge_index_dict,target=data.y_dict["author"], index=torch.arange(13116)) #index=torch.arange(13116) #target=data.y if explanation_type=='phenomenon' else None
# print(f'Generated explanations in {explanation.available_explanations}')

# path = fname_base+'feature_importance.png'
# explanation.visualize_feature_importance(path, top_k=10)
# print(f"Feature importance plot has been saved to '{path}'")

# path = fname_base+'subgraph.pdf'
# explanation.visualize_graph(path)
# print(f"Subgraph visualization plot has been saved to '{path}'")

/root/.pyenv/versions/3.10.1/envs/DyHANE_cuda/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [24]:
# B initialization

B = {}  
B_size = 768
topk = 64
n_types = ['author', 'paper', 'institution']
percs = [0] * len(n_types) 

#type importance, dato dalla media dei topk per ogni tipo
for i, nt in enumerate(n_types):
    values,indices=torch.topk(explanation.node_mask_dict[nt].sum(-1),k=topk)
    percs[i] = values.mean().item()

scaling_factor = B_size / sum(percs)
rates = [round(val * scaling_factor) for val in percs]

# top nodes for each type
for i, nt in enumerate(n_types):
    values,indices=torch.topk(explanation.node_mask_dict[nt].sum(-1),k=rates[i])
    B[nt+'s'] = indices.cpu().numpy().tolist()

with open(fname_base+base+'B_'+str(B_size)+'.pkl', 'wb') as fp:
    pickle.dump(B, fp)
    print('dictionary saved successfully to file')

print(B)

dictionary saved successfully to file
{'authors': [171, 65, 27, 1, 18, 9, 7468, 2, 1739, 205, 5243, 499, 5080, 340, 10168, 10059, 17, 12, 1095, 2821, 1464, 479, 454, 86, 93, 1377, 525, 303, 173, 7951, 2819, 189, 5043, 5466, 3218, 3310, 13006, 3087, 3264, 6733, 11211, 107, 109, 3252, 8586, 11884, 559, 3574, 5018, 11939, 7108, 1235, 2424, 10025, 396, 4738, 10710, 8294, 478, 11176, 661, 3370, 9221, 3120, 5995, 9779, 2848, 3369, 3517, 11848, 10908, 2658, 4469, 6817, 1998, 63, 66, 155, 11801, 502, 4331, 5919, 1159, 6544, 11382, 6331, 2885, 11410, 9873, 5877, 9719, 8293, 2255, 1576, 11320, 2441], 'papers': [6746, 5297, 3773, 5939, 6179, 4223, 5969, 2376, 4862, 5337, 2968, 5452, 5890, 4227, 2342, 5921, 6098, 5184, 4639, 131, 6378, 4971, 4939, 2692, 8042, 4715, 5089, 4564, 8457, 6100, 4199, 4940, 5125, 5565, 3077, 7964, 5102, 8066, 36, 5485, 5001, 3139, 4823, 6319, 30, 5360, 5729, 1821, 6377, 6110, 4019, 1975, 8132, 3420, 6125, 7649, 2205, 3768, 417, 578, 8181, 267, 1105, 1310, 3581, 5595, 3948, 7075, 7740, 3970, 5217, 79, 8333, 2570, 2757, 4269, 3240, 982, 4369, 6178, 7946, 3280, 6645, 5186, 8515, 723, 2724, 2209, 1471, 6656, 6428, 6089, 5352, 810, 3254, 2505, 5683, 4471, 8566, 6397, 3364, 464, 8567, 6368, 778, 1317, 5641, 6477, 8584, 6735, 7589, 5066, 5048, 3988, 8054, 8353, 2531, 6204, 1194, 3402, 3317, 3395, 3641, 8040, 5533, 6686, 2887, 686, 2514, 7476, 5584, 7167, 1280, 4948, 6575, 4383, 827, 6877, 7551, 623, 3357, 586, 2942, 6203, 6007, 3121, 5915, 4855, 5758, 5534, 3898, 6287, 7012, 5646, 5361, 2516, 6620, 3544, 7531, 5047, 621, 5655, 4968, 730, 2909, 1979, 6055, 5639, 327, 3115, 5225, 6949, 6271, 5924, 4422, 6227, 6693, 6860, 29, 6980, 167, 5189, 7745, 1003, 2648, 2970, 7366, 3404, 6751, 5457, 367, 5008, 5722, 8627, 8139, 6103, 2653, 4761, 6747, 53, 3477, 3828, 4539, 2152, 6854, 2642, 31, 6972, 5363, 5366, 6771, 6396, 3895, 7008, 940, 7123, 2729, 3972, 8084, 4316, 2281, 2771, 5856, 7382, 5620, 1592, 6550, 2206, 6065, 3508, 6862, 2709, 3523, 3572, 6986, 32, 2223, 706, 8005, 8592, 2512, 5052, 6383, 6882, 2343, 679, 3279, 4902, 1455, 6275, 3177, 759, 3855, 7183, 1385, 5757, 1579, 7961, 8075, 3361, 8402, 5766, 2517, 3413, 6921, 884, 1189, 917, 2362, 1024, 1072, 337, 4362, 6192, 7344, 6454, 109, 5608, 7340, 8009, 5392, 3251, 843, 7024, 7234, 1685, 7645, 753, 7557, 5405, 7519, 2241, 6591, 4394, 2608, 97, 3090, 5386, 5409, 399, 5334, 2975, 4361, 6819, 1108, 7125, 3706, 7911, 3900, 2606, 4774, 6418, 3199, 374, 1568, 6473, 8101, 5953, 3427, 6156, 1721, 63, 270, 2561, 6634, 1855, 241, 2521, 1602, 1424, 1172, 4395, 1336, 4028, 2271, 141, 7926, 4173, 3714, 1011, 4004, 758, 1734, 6134, 3245, 4040, 7771, 3126, 6196, 514, 1490, 3016, 2603, 4347, 1079, 2574, 164, 830, 8596, 3334, 136, 1065, 7335, 4421, 6475, 1791, 239, 7888, 6930, 6008, 4304, 303, 3178, 3456, 4931, 4805, 1365, 1551, 1265, 8199, 906, 8114, 3293, 5231, 5691, 4594, 4813, 6057, 6385, 5749, 3083, 4961, 3027, 8268, 2590, 5413, 1664, 3048, 7772, 2440, 14, 748, 5481, 1037, 2337, 6824, 7236, 572, 6908, 678, 7059, 2550, 661, 4077, 7887, 8410, 2238, 176, 6961, 5664, 3922, 3584, 4424, 7103, 6235, 191, 8233, 6529, 890, 5479, 6467, 2242, 7193, 4893, 5820, 188, 4309, 2351, 6578, 1616, 3274, 6601, 3665, 4288, 806, 8172, 577, 5954, 6175, 6374, 4069, 1696, 6764, 7567, 4477, 3153, 116, 3654, 1775, 6910, 8120, 2556, 6046, 1078, 4009, 6568, 5958, 6137, 800, 3123, 782, 6488, 2467, 5672, 388, 6445, 3871, 996, 1807, 1349, 3480, 354, 1160, 2579, 5310, 5606, 6248, 6577, 751, 7001, 7022, 8364, 6295, 1837, 6554, 3766, 2934, 3779, 4819, 5384, 148, 5319, 7209, 4142, 2, 4742, 3208, 5721, 696, 5651, 2946, 6509, 633, 1660, 7860, 3041, 7677, 3481, 3409, 8289, 5741, 2635, 6356, 6853, 1798, 3205, 4147, 7396, 3854, 6049, 252, 8197, 5630, 5385, 9, 5438, 5907, 3621, 4428, 3023, 5622, 2614, 2984, 5790, 1465, 4735, 7939, 4873, 6312, 7445, 4588, 2377, 3064, 8303, 6970, 8308, 1983, 3051, 3646, 8055, 7052, 5540, 573, 5778, 946, 7757, 7242, 5003, 7748, 5338, 4247, 2797, 8324, 142, 8220, 284, 4830, 912, 3234, 6936, 3135, 7208, 1726, 6988, 4240, 6426, 2822, 8193, 539, 2643, 7056], 'institutions': [310, 102, 90, 330, 5, 1341, 1520, 415, 356, 560, 419, 1205, 479, 1021, 108, 264, 1250, 1276, 468, 1198, 77, 181, 944, 261, 114, 981, 460, 87, 35, 126, 821, 162, 1413, 409, 1444, 1278, 1367, 1345, 349, 710, 1154, 1178, 861, 1566, 561, 322, 822, 607, 249, 741, 153, 455, 1601, 1208, 449, 1450, 977, 487, 615, 467, 317, 1109, 739, 1002, 65, 1091, 154, 699, 60, 336, 103, 832, 406, 84, 1496, 784, 1537, 1382, 589, 1467, 669]}

INCREMENT

In [14]:
# I generation
# for each eij, I = I U {i, j} if category == 0 
# else I = I U {i, j} U N_i U N_j U N_mp_i if type(i) == 'A'

df_events = pd.read_csv(fname_base+new+'events_edges_cat.csv')
df_events.head(5)

  openalex_id_i openalex_id_j   id_i  id_j r_type  category
0   A5011101896   W1439977626  13116  8641     AP         1
1   A5077030086   W1439977626  13117  8641     AP         1
2   A5055416007   W2146875259     93  8642     AP         1
3   A5080395937   W2146875259  13118  8642     AP         1
4   A5037058917   W2146875259  13119  8642     AP         1

In [15]:
#mapped edges

#AP
AP_old = pd.read_csv(fname_base+base+'AP_map.csv')
AP_new = df_events[df_events['r_type'] == 'AP']
AP_new = AP_new[['id_i', 'id_j']]

#AI
AI_old = pd.read_csv(fname_base+base+'AI_map.csv')
AI_new = df_events[df_events['r_type'] == 'AI']
AI_new = AI_new[['id_i', 'id_j']]

#PP
PP_old = pd.read_csv(fname_base+base+'PP_map.csv')
PP_new = df_events[df_events['r_type'] == 'PP']
PP_new = PP_new[['id_i', 'id_j']]

#AA all
AA = pd.read_csv(fname_base+new+'AA_all_map.csv')

In [16]:
#serve il remapping degli edges. Per i nuovi ok, sono id_i e id_j di df_events.
#I vecchi li abbiamo già

def one_hop_neighborhood(category, id, ntype, AP_new, AP_old, AI_new, AI_old, PP_new, PP_old, AA): #all mapped
    nei_A = []
    nei_I = []
    nei_P = []

    if category == 1:
        if ntype == 'A':
            AP_old_sub = AP_old[AP_old['author'] == id]
            AP_new_sub = AP_new[AP_new['id_i'] == id]
            nei_P = list(set(AP_old_sub['paper'].tolist() + AP_new_sub['id_j'].tolist()))
            AI_old_sub = AI_old[AI_old['author_id'] == id]
            AI_new_sub = AI_new[AI_new['id_i'] == id]
            nei_I = list(set(AI_old_sub['institution_id'].tolist() + AI_new_sub['id_j'].tolist()))
            AA_sub = AA[AA['source'] == id]
            nei_A = AA_sub['target'].drop_duplicates().tolist()

        elif ntype == 'I':
            AI_old_sub = AI_old[AI_old['institution_id'] == id]
            AI_new_sub = AI_new[AI_new['id_j'] == id]
            nei_A = list(set(AI_old_sub['author_id'].tolist() + AI_new_sub['id_i'].tolist()))


        else: #ntype == 'P
            AP_old_sub = AP_old[AP_old['paper'] == id]
            AP_new_sub = AP_new[AP_new['id_j'] == id]
            nei_A = list(set(AP_old_sub['author'].tolist() + AP_new_sub['id_i'].tolist()))
            PP_old_sub = PP_old[PP_old['citing'] == id]
            PP_new_sub = PP_new[PP_new['id_i'] == id]
            nei_P = list(set(PP_old_sub['cited'].tolist() + PP_new_sub['id_j'].tolist()))
        
    return nei_A, nei_I, nei_P

In [17]:
df_events['nei_A'],  df_events['nei_I'], df_events['nei_P'] = zip(*df_events.apply(lambda row: one_hop_neighborhood(row['category'], row['id_i'], row['r_type'][0], AP_new, AP_old, AI_new, AI_old, PP_new, PP_old, AA), axis=1))
df_events['nej_A'],  df_events['nej_I'], df_events['nej_P'] = zip(*df_events.apply(lambda row: one_hop_neighborhood(row['category'], row['id_j'], row['r_type'][1], AP_new, AP_old, AI_new, AI_old, PP_new, PP_old, AA), axis=1))
#df_events.head(5)


df_A = df_events[(df_events['r_type'] == 'AP') | (df_events['r_type'] == 'AI')]
A = df_A['id_i'].drop_duplicates().tolist()
A_nei_tmp = df_events['nei_A'].drop_duplicates().tolist() #list of lists
A_nei_tmp = [l for l in A_nei_tmp if l!=[]]
A_nei = [a for l in A_nei_tmp for a in l]
A_nej_tmp = df_events['nej_A'].drop_duplicates().tolist() #list of lists
A_nej_tmp = [l for l in A_nej_tmp if l!=[]]
A_nej = [a for l in A_nej_tmp for a in l]

A_all = list(set(A + A_nei + A_nej))

print(A_all[:10])


df_I = df_events[df_events['r_type'] == 'AI']
I = df_I['id_j'].drop_duplicates().tolist()
I_nei_tmp = df_events['nei_I'].drop_duplicates().tolist() #list of lists
I_nei_tmp = [l for l in I_nei_tmp if l!=[]]
I_nei = [i for l in I_nei_tmp for i in l]
I_nej_tmp = df_events['nej_I'].drop_duplicates().tolist() #list of lists
I_nej_tmp = [l for l in I_nej_tmp if l!=[]]
I_nej = [i for l in I_nej_tmp for i in l]

I_all = list(set(I + I_nei + I_nej))
print(I_all[:10])

#split AP and PP
df_P_fromAP = df_events[df_events['r_type'] == 'AP']
P_from_AP = df_P_fromAP['id_j'].drop_duplicates().tolist()
df_P_fromPP = df_events[df_events['r_type'] == 'PP']
P_from_PP = df_P_fromPP['id_i'].drop_duplicates().tolist() + df_P_fromPP['id_j'].drop_duplicates().tolist() 

#P = df_P['id_j'].drop_duplicates().tolist() if df_events['r_type'] == 'AP' else list(set(df_P['id_i'].drop_duplicates().tolist()+df_P['id_j'].drop_duplicates().tolist()))
P_nei_tmp = df_events['nei_P'].drop_duplicates().tolist() #list of lists
P_nei_tmp = [l for l in P_nei_tmp if l!=[]]
P_nei = [p for l in P_nei_tmp for p in l]
P_nej_tmp = df_events['nej_P'].drop_duplicates().tolist() #list of lists
P_nej_tmp = [l for l in P_nej_tmp if l!=[]]
P_nej = [p for l in P_nej_tmp for p in l]

P_all = list(set(P_from_AP + P_from_PP + P_nei + P_nej))
print(P_all[:10])

I = {}
I['authors'] = A_all
I['institutions'] = I_all
I['papers'] = P_all


with open(fname_base+new+'I.pkl', 'wb') as fp:
        pickle.dump(I, fp)
        print('dictionary saved successfully to file')

print(I)

[0, 3257, 7, 13, 15, 16, 21, 22, 23, 24]
[0, 3, 6, 12, 15, 17, 24, 27, 33, 34]
[4, 34, 35, 37, 41, 8244, 84, 91, 117, 122]
dictionary saved successfully to file

In [18]:
print('Num authors in I:', len(I['authors']))
print('Num institutions in I:', len(I['institutions']))
print('Num papers in I:', len(I['papers']))

Num authors in I: 3409
Num institutions in I: 525
Num papers in I: 1817

In [6]:
##TEST DI PROVA

def indices_to_keep(I, B, ntype):
    if B == {}: #OnlineGNN
        return I[ntype]
    else: #continualGNN
        return list(set(I[ntype]+B[ntype]))
    
def build_testing_online_and_unchanged(AX,I,B):
    #prendiamo online
    indices_online = torch.load(fname_base+'testing_online.pt')
    mask_online = torch.zeros(AX.shape[0], dtype=torch.bool)
    mask_online[indices_online] = 1
    mask_online_opp = ~mask_online
    tx = torch.masked_select(torch.arange(AX.shape[0]), mask_online)
    p#rint('online shape',tx.shape)

    #Gli indici True di A sono quelli che si possono prendere, tra cui selezionare i random.
    #Quindi vanno messi a true gli indici non presenti in A e in B e non presenti in online.
    mask = torch.zeros(AX.shape[0], dtype=torch.bool)
    indices_no = indices_to_keep(I, B, 'authors')
    indices_si = [a for a in range(AX.shape[0]) if a not in indices_no] 
    mask[indices_si] = 1
    mask = torch.logical_and(mask, mask_online_opp)

    #prendiamo random 189 indici tra quelli true di A. 
    num_samples = indices_online.shape[0] #189
    true_indices = torch.masked_select(torch.arange(AX.shape[0]), mask) #tutti indici true 
    sampled_indices = true_indices[torch.randperm(true_indices.shape[0])[:num_samples]] #prendo num_samples valori a caso (sono gli indici che rimarrano True qui)
    mask_test = torch.zeros(AX.shape[0], dtype=torch.bool)
    mask_test[sampled_indices] = 1
    testing = torch.masked_select(torch.arange(AX.shape[0]), mask_test)
    #print('unchanged shape', testing.shape)

    mask_test = torch.logical_or(mask_test, mask_online) #metto a True indici che posso prendere & indici test online
    testing = torch.masked_select(torch.arange(AX.shape[0]), mask_test)
    #print('final shape', testing.shape)
    torch.save(testing, fname_base+'testing_online_and_unchanged.pt')


I = pickle.load(open(fname_base+new+'I.pkl', 'rb'))
B = pickle.load(open(fname_base+base+'B_256.pkl', 'rb'))
print('#########')
indices_online = torch.load(fname_base+'testing_online.pt')
print(indices_online.shape) #189 
AX = torch.load(fname_base+new+'features/AX_tensor_2019-2022.pt')  
build_testing_online_and_unchanged(AX, I, B)
print('#########')
indices_online_unchanged = torch.load(fname_base+'testing_online_and_unchanged.pt')
print(indices_online_unchanged.shape) #189*2

#########
torch.Size([189])
online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
#########
torch.Size([378])

In [22]:
#RUN QUESTO (7)

#Generate new heterodata 

def indices_to_keep(I, B, ntype):
    if B == {}: #OnlineGNN
        return I[ntype]
    else: #continualGNN
        return list(set(I[ntype]+B[ntype]))

def generate_mapped_edges(df_events_ok, r_type, I, B):
    df_r = df_events_ok[df_events_ok['r_type'] == r_type]
    df_r = df_events_ok[['id_i', 'id_j']]
    if r_type == 'AP':
        df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
    elif r_type == 'AI':
        df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
    else: #r_type == 'PP':
        df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)
    return subset_mapped_edges(df_r, r_type, I, B)

def subset_mapped_edges(df_edg, r_type, I, B): #df_edg is AP_map or AI_map or PP_map
    col_i = df_edg.columns[0]
    col_j = df_edg.columns[1]
    i_type = r_type[0]
    j_type = r_type[1]
    diz = {'A': 'authors', 'P': 'papers', 'I': 'institutions'}
    if B == {}: #onlineGNN
        df_edg_sub = df_edg[(df_edg[col_i].isin(I[diz[i_type]])) & (df_edg[col_j].isin(I[diz[j_type]]))]
    else: #streamingGNN
        df_edg_sub = df_edg[((df_edg[col_i].isin(I[diz[i_type]])) | (df_edg[col_i].isin(B[diz[i_type]]))) & ((df_edg[col_j].isin(I[diz[j_type]])) | (df_edg[col_j].isin(B[diz[j_type]])))]
    return df_edg_sub


def build_testing_online_and_unchanged(AX,I,B):
    #prendiamo online
    indices_online = torch.load(fname_base+'testing_online.pt')
    mask_online = torch.zeros(AX.shape[0], dtype=torch.bool)
    mask_online[indices_online] = 1
    mask_online_opp = ~mask_online
    tx = torch.masked_select(torch.arange(AX.shape[0]), mask_online)
    #print('online shape',tx.shape)

    #Gli indici True di A sono quelli che si possono prendere, tra cui selezionare i random.
    #Quindi vanno messi a true gli indici non presenti in A e in B e non presenti in online.
    mask = torch.zeros(AX.shape[0], dtype=torch.bool)
    indices_no = indices_to_keep(I, B, 'authors')
    indices_si = [a for a in range(AX.shape[0]) if a not in indices_no] 
    mask[indices_si] = 1
    mask = torch.logical_and(mask, mask_online_opp)

    #prendiamo random 189 indici tra quelli true di A. 
    num_samples = indices_online.shape[0] #189
    true_indices = torch.masked_select(torch.arange(AX.shape[0]), mask) #tutti indici true 
    sampled_indices = true_indices[torch.randperm(true_indices.shape[0])[:num_samples]] #prendo num_samples valori a caso (sono gli indici che rimarrano True qui)
    mask_test = torch.zeros(AX.shape[0], dtype=torch.bool)
    mask_test[sampled_indices] = 1
    testing = torch.masked_select(torch.arange(AX.shape[0]), mask_test)
    #print('unchanged shape', testing.shape)

    mask_test = torch.logical_or(mask_test, mask_online) #metto a True indici che posso prendere & indici test online
    testing = torch.masked_select(torch.arange(AX.shape[0]), mask_test)
    #print('final shape', testing.shape)
    torch.save(testing, fname_base+'testing_online_and_unchanged.pt')
    


def generate_new_heterodata(I, B, df_events, scenario):
    for r_type in df_events['r_type'].drop_duplicates().tolist():
        df_ev = generate_mapped_edges(df_events, r_type, I, B)
        df_edg = pd.read_csv(fname_base+base+r_type+'_map.csv')
        df_base = subset_mapped_edges(df_edg, r_type, I, B)
        df_train = pd.concat([df_ev, df_base], axis=0).drop_duplicates()
        df_train.to_csv(fname_base+new+'Training/'+r_type+'_map.csv', index=False)

    #loading X and Y tensors
    AX = torch.load(fname_base+new+'features/AX_tensor_2019-2022.pt') 
    AY = torch.load(fname_base+new+'features/AY_tensor_2019-2022.pt')
    PX = torch.load(fname_base+new+'features/PX_tensor_2019-2022.pt')
    IX = torch.load(fname_base+new+'features/IX_tensor_2019-2022.pt')

    #PCA
    dim=128
    pca_author=PCA(n_components=dim).fit(AX)
    pca_paper=PCA(n_components=dim).fit(PX)
    pca_institution=PCA(n_components=dim).fit(IX)

    #create edge list
    AP = pd.read_csv(fname_base+new+'Training/AP_map.csv')[['author', 'paper']] 
    AP_tensor = torch.tensor(AP.values.T)
    PA = pd.read_csv(fname_base+new+'Training/AP_map.csv')[['paper', 'author']]
    PA_tensor = torch.tensor(PA.values.T)
    PP = pd.read_csv(fname_base+new+'Training/PP_map.csv')[['citing', 'cited']]
    PP_tensor = torch.tensor(PP.values.T)
    PP_rev = pd.read_csv(fname_base+new+'Training/PP_map.csv')[['cited', 'citing']]
    PP_rev_tensor = torch.tensor(PP_rev.values.T)
    AI = pd.read_csv(fname_base+new+'Training/AI_map.csv')
    AI_tensor = torch.tensor(AI.values.T)
    IA = AI[['institution_id', 'author_id']]
    IA_tensor = torch.tensor(IA.values.T)

    new_data = HeteroData()

    filter_nan=lambda x:x[:,torch.logical_not(x.isnan().long().sum(axis=0).bool())]

    new_data['author'].x = torch.tensor(pca_author.transform(AX)).float()# qui
    new_data['author'].y = AY.long()
    new_data['paper'].x = torch.tensor(pca_paper.transform(PX)).float()
    new_data['institution'].x = torch.tensor(pca_institution.transform(IX)).float()
    new_data['author', 'writes', 'paper'].edge_index = AP_tensor.long()
    new_data['paper', 'is_written_by', 'author'].edge_index = PA_tensor.long()
    new_data['paper', 'cites', 'paper'].edge_index = PP_tensor.long()
    new_data['paper', 'is_cited_by', 'paper'].edge_index = PP_rev_tensor.long()
    new_data['author', 'is_affiliated_with', 'institution'].edge_index = filter_nan(AI_tensor).long()
    new_data['institution', 'has_affiliated', 'author'].edge_index = filter_nan(IA_tensor).long()

    #add meta-paths
    metapaths = [[('author', 'paper'), ('paper', 'author')], #APA
            [('author', 'paper'), ('paper', 'is_cited_by', 'paper'), ('paper', 'author')], #APPA
            [('author', 'institution'), ('institution', 'author')]] #AIA
    new_data = AddMetaPaths(metapaths, weighted=True)(new_data)

    # transform: train-test split --> non lo facciamo perché abbiamo test set fissato
    #transform = T.RandomNodeSplit()
    #new_data = transform(new_data)


    mask_A = torch.zeros(AX.shape[0], dtype=torch.bool)
    indices_A = indices_to_keep(I, B, 'authors')
    mask_A[indices_A] = 1
    #caso random split:
    #new_data['author'].train_mask = torch.logical_and(new_data['author'].train_mask, mask_A) #T.IndexToMask(indices_A)
    #new_data['author'].val_mask = torch.logical_and(new_data['author'].val_mask, mask_A)
    #new_data['author'].test_mask = torch.logical_and(new_data['author'].test_mask, mask_A)
    
    #per avere stesso test altri modelli
    #prendi test set
    if scenario == 'C':
        indices_test = torch.load(fname_base+'testing_online.pt') #testing_online_and_unchanged.pt
    else:
        build_testing_online_and_unchanged(AX,I,B)
        indices_test = torch.load(fname_base+'testing_online_and_unchanged.pt')
    mask_test = torch.zeros(AX.shape[0], dtype=torch.bool)
    mask_test[indices_test] = 1
    mask_test_opp = ~mask_test

    new_data['author'].test_mask = torch.logical_and(mask_A, mask_test) #metto a True indici che posso prendere & indici test online
    new_data['author'].train_mask = torch.logical_and(mask_A, mask_test_opp) #metto a True indici che posso prendere & not indici test online
    new_data['author'].val_mask = torch.logical_and(mask_A, mask_test_opp) #metto a True indici che posso prendere & not indici test online
    #prendiamo random 500 indici tra quelli true di train e li spostiamo nel validation
    true_indices_val = torch.masked_select(torch.arange(AX.shape[0]), new_data['author'].val_mask) #tutti indici true di val
    sampled_indices = true_indices_val[torch.randperm(true_indices_val.shape[0])[:500]] #prendo 500 valori a caso (sono gli indici che rimarrano True qui e diventeranno False in train_mask)
    mask_val = torch.zeros(AX.shape[0], dtype=torch.bool)
    mask_val[sampled_indices] = 1
    new_data['author'].val_mask = torch.logical_and(new_data['author'].val_mask, mask_val)
    #quegli stessi 500 valori vanno messi a false per il train
    mask_train = ~mask_val
    new_data['author'].train_mask = torch.logical_and(new_data['author'].train_mask, mask_train)

    mask_I = torch.zeros(IX.shape[0], dtype=torch.bool)
    indices_I = indices_to_keep(I, B, 'institutions')
    mask_I[indices_I] = 1
    new_data['institution'].train_mask = mask_I
    
    mask_P = torch.zeros(PX.shape[0], dtype=torch.bool)
    indices_P = indices_to_keep(I, B, 'papers')
    mask_P[indices_P] = 1
    new_data['paper'].train_mask = mask_P
    
    return new_data

In [26]:
#INCREMENTAL STEP

I = pickle.load(open(fname_base+new+'I.pkl', 'rb'))
B = pickle.load(open(fname_base+base+'B_256.pkl', 'rb'))
#B = {}
df_events = pd.read_csv(fname_base+new+'events_edges.csv') #openalex_id_i, openalex_id_j, id_i, id_j, r_type
scenario = 'C' #'C+U'
new_data = generate_new_heterodata(I, B, df_events, scenario)

#print(new_data['author'].test_mask.count_nonzero()) #qua testo non su 1000 ma su 242 

num_run = 5
l_micro = []
l_macro = []
l_weigh = []
l_auc = []
for run in range(num_run):
    print('##### RUN '+str((run+1))+' #####')

    model = None
    model = GAT(hidden_channels=64, out_channels=8, dropout=0.4) #num_classes
    model = to_hetero(model, new_data.metadata(), aggr='sum')

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    new_data, model = new_data.to(device), model.to(device)

    model = load_model(64,8,0.6, new_data,fname_base+base+'model.pth')

    optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=0.001) #0.01, 005, 001, 0001 fa cacare
    weights = torch.tensor([2, 2, 1, 1.5, 1.5, 1, 2, 1]).float().to(device)
    criterion = nn.CrossEntropyLoss(weights) 

    model = train_node_classifier(model, new_data, optimizer, criterion, n_epochs=500) #500

    torch.save(model.state_dict(), fname_base+new+'model_dyhane_B256_old_new.pth')

    f1_micro, f1_macro, f1_weigh, auc = eval_node_classifier(model, new_data) 
    #print(f'Test Eval: {test_ev:.3f}')
    print(f'f1-micro: {f1_micro:.3f}, f1-macro: {f1_macro:.3f}, f1-weighted: {f1_weigh:.3f}, , roc-auc: {auc:.3f}')

    l_micro.append(f1_micro)
    l_macro.append(f1_macro)
    l_weigh.append(f1_weigh)
    l_auc.append(auc)

df = pd.DataFrame(columns=['F1_micro', 'F1_macro', 'F1_weighted', 'ROC-AUC'])
df['F1_micro'] = l_micro
df['F1_macro'] = l_macro
df['F1_weighted'] = l_weigh
df['ROC-AUC'] = l_auc
df_ok = processing_results(df)
df_ok.to_excel(fname_base+new+'results_dyhane_B256_old_new.xlsx', index=False)

/tmp/ipykernel_843305/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_843305/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_843305/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

##### RUN 1 #####

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

Da qui in poi: UTILS

In [47]:
#Grid search

from itertools import product

# Example usage:
# Assuming you have a model called 'model' and hyperparameters defined as a dictionary
# hyperparameters = {'param1': [value1, value2, ...], 'param2': [value1, value2, ...], ...}

def train_node_classifier(model, data, optimizer, criterion, n_epochs=200): 

    for epoch in range(1, n_epochs + 1):
        model.train()
        optimizer.zero_grad()
        out = model(data.x_dict, data.edge_index_dict)
        mask = data['author'].train_mask
        loss = criterion(out['author'][mask], data['author'].y[mask]) 
        loss.backward()
        optimizer.step()
        pred = out['author'].argmax(dim=1) ## Use the class with highest probability
        f1_micro, f1_macro, f1_weigh, auc = eval_node_classifier(model, data) 
        '''if epoch % 20 == 0:
            print(f'Epoch: {epoch:03d}, Train Loss: {loss:.3f}, Val f1_micro: {f1_micro:.3f}')'''
    return model


def eval_node_classifier(model, data):

    model.eval()
    with torch.no_grad(): 
        pred = model(data.x_dict, data.edge_index_dict)['author'].argmax(dim=-1)
        pred_prob = torch.nn.functional.softmax(model(data.x_dict, data.edge_index_dict)['author'], -1)
        mask = data['author'].val_mask
        correct = (pred[mask] == data['author'].y[mask]).sum()
        f1_micro = f1_score(data['author'].y.cpu(), pred.cpu(), average='micro')
        f1_macro = f1_score(data['author'].y.cpu(), pred.cpu(), average='macro')
        f1_weigh = f1_score(data['author'].y.cpu(), pred.cpu(), average='weighted')
        #servono predicted probabilities, 8 classes
        auc = roc_auc_score(data['author'].y.cpu(), pred_prob.cpu().detach().numpy(), average='macro', multi_class='ovo')
        return f1_micro, f1_macro, f1_weigh, auc
    

def grid_search(hyperparameters):
    best_score = float('-inf')
    best_params = None
    
    # Generate all combinations of hyperparameters
    param_combinations = product(*hyperparameters.values())
    
    for params in param_combinations:
        print('########## Hyperparameters combination ##########')
        print(params)
        print('##########')
        I = pickle.load(open(fname_base+new+'I.pkl', 'rb'))
        B = pickle.load(open(fname_base+base+'B_'+str(params[0])+'.pkl', 'rb')) #params[0] --> 'B_size'
        df_events = pd.read_csv(fname_base+new+'events_edges.csv') #openalex_id_i, openalex_id_j, id_i, id_j, r_type
        scenario = 'C+U' #'C'
        new_data = generate_new_heterodata(I, B, df_events, scenario)

        num_run = 5
        l_micro = []
        l_macro = []
        l_weigh = []
        l_auc = []
        for run in range(num_run):
            print('##### RUN '+str((run+1))+' #####')

            model = None
            model = GAT(hidden_channels=64, out_channels=8, dropout=params[1]) #params[1] --> 'dropout'
            model = to_hetero(model, new_data.metadata(), aggr='sum')

            device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
            new_data, model = new_data.to(device), model.to(device)

            model = load_model(64,8,params[1], new_data,fname_base+base+'base_model.pth') #params[1] --> 'dropout'

            optimizer = torch.optim.Adam(model.parameters(), lr=params[2], weight_decay=params[3]) #params[2] --> lr, params[3] --> L2
            weights = torch.tensor([2, 2, 1, 1.5, 1.5, 1, 2, 1]).float().to(device)
            criterion = nn.CrossEntropyLoss(weights) 

            model = train_node_classifier(model, new_data, optimizer, criterion, n_epochs=500) 

            torch.save(model.state_dict(), fname_base+new+'model_dyhane_B'+str(params[0])+'_run'+str(run+1)+'_old_new.pth') #params[0] --> 'B_size'

            f1_micro, f1_macro, f1_weigh, auc = eval_node_classifier(model, new_data) 
            print(f'f1-micro: {f1_micro:.3f}, f1-macro: {f1_macro:.3f}, f1-weighted: {f1_weigh:.3f}, , roc-auc: {auc:.3f}')

            l_micro.append(f1_micro)
            l_macro.append(f1_macro)
            l_weigh.append(f1_weigh)
            l_auc.append(auc)

        df = pd.DataFrame(columns=['F1_micro', 'F1_macro', 'F1_weighted', 'ROC-AUC'])
        df['F1_micro'] = l_micro
        df['F1_macro'] = l_macro
        df['F1_weighted'] = l_weigh
        df['ROC-AUC'] = l_auc
        df_ok = processing_results(df)
        #df_ok.to_excel(fname_base+new+'results_dyhane_B'+str(params[0])+'_old_new.xlsx', index=False) #params[0] --> 'B_size'

        #score = df_ok['F1_micro'].mean() #F1 micro
        score = float(df_ok['F1_micro'].iloc[-1].split('±')[0])

        if score > best_score:
            best_score = score
            best_params = params

        
    
    return best_params, best_score



hyperparameters = {
    'B_size':[768, 2048, 256], #512 tutti e 80, 1024 ne mancano 7
    'dropout':[0.3, 0.4, 0.5, 0.6, 0.7],
    'lr': [0.001, 0.005, 0.01, 0.05],
    'L2': [0.0001, 0.0005, 0.001, 0.005]
}

best_params, best_score = grid_search(hyperparameters)
print('##########')
print("Best hyperparameters:", best_params)
print("Best validation score:", best_score)
print('##########')

########## Hyperparameters combination ##########
(512, 0.3, 0.001, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.095, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.816, Val f1_micro: 0.223
Epoch: 060, Train Loss: 1.656, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.540, Val f1_micro: 0.241
Epoch: 100, Train Loss: 1.441, Val f1_micro: 0.250
Epoch: 120, Train Loss: 1.365, Val f1_micro: 0.256
Epoch: 140, Train Loss: 1.296, Val f1_micro: 0.259
Epoch: 160, Train Loss: 1.234, Val f1_micro: 0.263
Epoch: 180, Train Loss: 1.186, Val f1_micro: 0.272
Epoch: 200, Train Loss: 1.145, Val f1_micro: 0.272
Epoch: 220, Train Loss: 1.095, Val f1_micro: 0.279
Epoch: 240, Train Loss: 1.047, Val f1_micro: 0.279
Epoch: 260, Train Loss: 1.028, Val f1_micro: 0.282
Epoch: 280, Train Loss: 0.971, Val f1_micro: 0.289
Epoch: 300, Train Loss: 0.958, Val f1_micro: 0.288
Epoch: 320, Train Loss: 0.918, Val f1_micro: 0.291
Epoch: 340, Train Loss: 0.897, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.867, Val f1_micro: 0.293
Epoch: 380, Train Loss: 0.827, Val f1_micro: 0.295
Epoch: 400, Train Loss: 0.811, Val f1_micro: 0.295
Epoch: 420, Train Loss: 0.790, Val f1_micro: 0.296
Epoch: 440, Train Loss: 0.775, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.751, Val f1_micro: 0.299
Epoch: 480, Train Loss: 0.726, Val f1_micro: 0.299
Epoch: 500, Train Loss: 0.700, Val f1_micro: 0.301
f1-micro: 0.301, f1-macro: 0.292, f1-weighted: 0.297, , roc-auc: 0.688
##### RUN 2 #####
Epoch: 020, Train Loss: 2.083, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.817, Val f1_micro: 0.219
Epoch: 060, Train Loss: 1.664, Val f1_micro: 0.238
Epoch: 080, Train Loss: 1.537, Val f1_micro: 0.240
Epoch: 100, Train Loss: 1.459, Val f1_micro: 0.249
Epoch: 120, Train Loss: 1.370, Val f1_micro: 0.256
Epoch: 140, Train Loss: 1.302, Val f1_micro: 0.265
Epoch: 160, Train Loss: 1.248, Val f1_micro: 0.268
Epoch: 180, Train Loss: 1.174, Val f1_micro: 0.271
Epoch: 200, Train Loss: 1.140, Val f1_micro: 0.277
Epoch: 220, Train Loss: 1.108, Val f1_micro: 0.278
Epoch: 240, Train Loss: 1.053, Val f1_micro: 0.282
Epoch: 260, Train Loss: 1.023, Val f1_micro: 0.285
Epoch: 280, Train Loss: 0.975, Val f1_micro: 0.287
Epoch: 300, Train Loss: 0.964, Val f1_micro: 0.290
Epoch: 320, Train Loss: 0.918, Val f1_micro: 0.291
Epoch: 340, Train Loss: 0.898, Val f1_micro: 0.292
Epoch: 360, Train Loss: 0.854, Val f1_micro: 0.294
Epoch: 380, Train Loss: 0.834, Val f1_micro: 0.293
Epoch: 400, Train Loss: 0.823, Val f1_micro: 0.297
Epoch: 420, Train Loss: 0.781, Val f1_micro: 0.297
Epoch: 440, Train Loss: 0.767, Val f1_micro: 0.296
Epoch: 460, Train Loss: 0.741, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.718, Val f1_micro: 0.299
Epoch: 500, Train Loss: 0.697, Val f1_micro: 0.302
f1-micro: 0.302, f1-macro: 0.294, f1-weighted: 0.299, , roc-auc: 0.688
##### RUN 3 #####
Epoch: 020, Train Loss: 2.088, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.829, Val f1_micro: 0.222
Epoch: 060, Train Loss: 1.658, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.544, Val f1_micro: 0.242
Epoch: 100, Train Loss: 1.439, Val f1_micro: 0.250
Epoch: 120, Train Loss: 1.364, Val f1_micro: 0.256
Epoch: 140, Train Loss: 1.313, Val f1_micro: 0.261
Epoch: 160, Train Loss: 1.232, Val f1_micro: 0.266
Epoch: 180, Train Loss: 1.160, Val f1_micro: 0.271
Epoch: 200, Train Loss: 1.134, Val f1_micro: 0.274
Epoch: 220, Train Loss: 1.083, Val f1_micro: 0.277
Epoch: 240, Train Loss: 1.041, Val f1_micro: 0.283
Epoch: 260, Train Loss: 1.022, Val f1_micro: 0.284
Epoch: 280, Train Loss: 0.983, Val f1_micro: 0.284
Epoch: 300, Train Loss: 0.938, Val f1_micro: 0.289
Epoch: 320, Train Loss: 0.912, Val f1_micro: 0.289
Epoch: 340, Train Loss: 0.878, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.850, Val f1_micro: 0.293
Epoch: 380, Train Loss: 0.842, Val f1_micro: 0.292
Epoch: 400, Train Loss: 0.813, Val f1_micro: 0.296
Epoch: 420, Train Loss: 0.795, Val f1_micro: 0.294
Epoch: 440, Train Loss: 0.761, Val f1_micro: 0.296
Epoch: 460, Train Loss: 0.749, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.739, Val f1_micro: 0.300
Epoch: 500, Train Loss: 0.715, Val f1_micro: 0.298
f1-micro: 0.298, f1-macro: 0.290, f1-weighted: 0.294, , roc-auc: 0.688
##### RUN 4 #####
Epoch: 020, Train Loss: 2.088, Val f1_micro: 0.190
Epoch: 040, Train Loss: 1.818, Val f1_micro: 0.224
Epoch: 060, Train Loss: 1.657, Val f1_micro: 0.233
Epoch: 080, Train Loss: 1.538, Val f1_micro: 0.243
Epoch: 100, Train Loss: 1.449, Val f1_micro: 0.248
Epoch: 120, Train Loss: 1.360, Val f1_micro: 0.253
Epoch: 140, Train Loss: 1.290, Val f1_micro: 0.259
Epoch: 160, Train Loss: 1.251, Val f1_micro: 0.264
Epoch: 180, Train Loss: 1.196, Val f1_micro: 0.269
Epoch: 200, Train Loss: 1.136, Val f1_micro: 0.275
Epoch: 220, Train Loss: 1.071, Val f1_micro: 0.278
Epoch: 240, Train Loss: 1.059, Val f1_micro: 0.281
Epoch: 260, Train Loss: 1.018, Val f1_micro: 0.283
Epoch: 280, Train Loss: 0.976, Val f1_micro: 0.284
Epoch: 300, Train Loss: 0.959, Val f1_micro: 0.289
Epoch: 320, Train Loss: 0.914, Val f1_micro: 0.291
Epoch: 340, Train Loss: 0.886, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.866, Val f1_micro: 0.291
Epoch: 380, Train Loss: 0.839, Val f1_micro: 0.295
Epoch: 400, Train Loss: 0.807, Val f1_micro: 0.296
Epoch: 420, Train Loss: 0.778, Val f1_micro: 0.296
Epoch: 440, Train Loss: 0.760, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.740, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.734, Val f1_micro: 0.297
Epoch: 500, Train Loss: 0.689, Val f1_micro: 0.299
f1-micro: 0.299, f1-macro: 0.290, f1-weighted: 0.295, , roc-auc: 0.688
##### RUN 5 #####
Epoch: 020, Train Loss: 2.095, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.811, Val f1_micro: 0.220
Epoch: 060, Train Loss: 1.667, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.545, Val f1_micro: 0.239
Epoch: 100, Train Loss: 1.444, Val f1_micro: 0.249
Epoch: 120, Train Loss: 1.390, Val f1_micro: 0.254
Epoch: 140, Train Loss: 1.308, Val f1_micro: 0.257
Epoch: 160, Train Loss: 1.238, Val f1_micro: 0.265
Epoch: 180, Train Loss: 1.193, Val f1_micro: 0.272
Epoch: 200, Train Loss: 1.130, Val f1_micro: 0.275
Epoch: 220, Train Loss: 1.077, Val f1_micro: 0.279
Epoch: 240, Train Loss: 1.046, Val f1_micro: 0.279
Epoch: 260, Train Loss: 1.020, Val f1_micro: 0.282
Epoch: 280, Train Loss: 0.982, Val f1_micro: 0.285
Epoch: 300, Train Loss: 0.942, Val f1_micro: 0.288
Epoch: 320, Train Loss: 0.910, Val f1_micro: 0.292
Epoch: 340, Train Loss: 0.892, Val f1_micro: 0.291
Epoch: 360, Train Loss: 0.856, Val f1_micro: 0.294
Epoch: 380, Train Loss: 0.830, Val f1_micro: 0.292
Epoch: 400, Train Loss: 0.811, Val f1_micro: 0.294
Epoch: 420, Train Loss: 0.795, Val f1_micro: 0.294
Epoch: 440, Train Loss: 0.774, Val f1_micro: 0.296
Epoch: 460, Train Loss: 0.741, Val f1_micro: 0.300
Epoch: 480, Train Loss: 0.725, Val f1_micro: 0.299
Epoch: 500, Train Loss: 0.708, Val f1_micro: 0.302
f1-micro: 0.302, f1-macro: 0.293, f1-weighted: 0.298, , roc-auc: 0.688
########## Hyperparameters combination ##########
(512, 0.3, 0.001, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.096, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.819, Val f1_micro: 0.218
Epoch: 060, Train Loss: 1.670, Val f1_micro: 0.230
Epoch: 080, Train Loss: 1.573, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.464, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.395, Val f1_micro: 0.251
Epoch: 140, Train Loss: 1.328, Val f1_micro: 0.256
Epoch: 160, Train Loss: 1.266, Val f1_micro: 0.260
Epoch: 180, Train Loss: 1.215, Val f1_micro: 0.264
Epoch: 200, Train Loss: 1.184, Val f1_micro: 0.268
Epoch: 220, Train Loss: 1.153, Val f1_micro: 0.272
Epoch: 240, Train Loss: 1.101, Val f1_micro: 0.271
Epoch: 260, Train Loss: 1.062, Val f1_micro: 0.275
Epoch: 280, Train Loss: 1.045, Val f1_micro: 0.276
Epoch: 300, Train Loss: 1.016, Val f1_micro: 0.277
Epoch: 320, Train Loss: 1.002, Val f1_micro: 0.279
Epoch: 340, Train Loss: 0.964, Val f1_micro: 0.281
Epoch: 360, Train Loss: 0.942, Val f1_micro: 0.282
Epoch: 380, Train Loss: 0.911, Val f1_micro: 0.284
Epoch: 400, Train Loss: 0.911, Val f1_micro: 0.286
Epoch: 420, Train Loss: 0.897, Val f1_micro: 0.287
Epoch: 440, Train Loss: 0.879, Val f1_micro: 0.286
Epoch: 460, Train Loss: 0.872, Val f1_micro: 0.288
Epoch: 480, Train Loss: 0.818, Val f1_micro: 0.289
Epoch: 500, Train Loss: 0.807, Val f1_micro: 0.290
f1-micro: 0.290, f1-macro: 0.280, f1-weighted: 0.284, , roc-auc: 0.678
##### RUN 2 #####
Epoch: 020, Train Loss: 2.109, Val f1_micro: 0.187
Epoch: 040, Train Loss: 1.835, Val f1_micro: 0.217
Epoch: 060, Train Loss: 1.670, Val f1_micro: 0.230
Epoch: 080, Train Loss: 1.553, Val f1_micro: 0.237
Epoch: 100, Train Loss: 1.468, Val f1_micro: 0.245
Epoch: 120, Train Loss: 1.388, Val f1_micro: 0.249
Epoch: 140, Train Loss: 1.336, Val f1_micro: 0.256
Epoch: 160, Train Loss: 1.278, Val f1_micro: 0.260
Epoch: 180, Train Loss: 1.233, Val f1_micro: 0.264
Epoch: 200, Train Loss: 1.195, Val f1_micro: 0.267
Epoch: 220, Train Loss: 1.164, Val f1_micro: 0.270
Epoch: 240, Train Loss: 1.111, Val f1_micro: 0.271
Epoch: 260, Train Loss: 1.082, Val f1_micro: 0.273
Epoch: 280, Train Loss: 1.064, Val f1_micro: 0.275
Epoch: 300, Train Loss: 1.019, Val f1_micro: 0.279
Epoch: 320, Train Loss: 1.002, Val f1_micro: 0.278
Epoch: 340, Train Loss: 0.975, Val f1_micro: 0.281
Epoch: 360, Train Loss: 0.955, Val f1_micro: 0.283
Epoch: 380, Train Loss: 0.939, Val f1_micro: 0.283
Epoch: 400, Train Loss: 0.916, Val f1_micro: 0.284
Epoch: 420, Train Loss: 0.899, Val f1_micro: 0.285
Epoch: 440, Train Loss: 0.874, Val f1_micro: 0.289
Epoch: 460, Train Loss: 0.849, Val f1_micro: 0.287
Epoch: 480, Train Loss: 0.836, Val f1_micro: 0.288
Epoch: 500, Train Loss: 0.815, Val f1_micro: 0.288
f1-micro: 0.288, f1-macro: 0.279, f1-weighted: 0.282, , roc-auc: 0.678
##### RUN 3 #####
Epoch: 020, Train Loss: 2.092, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.834, Val f1_micro: 0.219
Epoch: 060, Train Loss: 1.666, Val f1_micro: 0.231
Epoch: 080, Train Loss: 1.566, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.461, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.379, Val f1_micro: 0.250
Epoch: 140, Train Loss: 1.314, Val f1_micro: 0.257
Epoch: 160, Train Loss: 1.257, Val f1_micro: 0.259
Epoch: 180, Train Loss: 1.232, Val f1_micro: 0.263
Epoch: 200, Train Loss: 1.204, Val f1_micro: 0.265
Epoch: 220, Train Loss: 1.143, Val f1_micro: 0.271
Epoch: 240, Train Loss: 1.104, Val f1_micro: 0.274
Epoch: 260, Train Loss: 1.059, Val f1_micro: 0.275
Epoch: 280, Train Loss: 1.073, Val f1_micro: 0.278
Epoch: 300, Train Loss: 1.005, Val f1_micro: 0.277
Epoch: 320, Train Loss: 0.985, Val f1_micro: 0.279
Epoch: 340, Train Loss: 0.981, Val f1_micro: 0.281
Epoch: 360, Train Loss: 0.949, Val f1_micro: 0.281
Epoch: 380, Train Loss: 0.918, Val f1_micro: 0.282
Epoch: 400, Train Loss: 0.908, Val f1_micro: 0.285
Epoch: 420, Train Loss: 0.895, Val f1_micro: 0.288
Epoch: 440, Train Loss: 0.872, Val f1_micro: 0.287
Epoch: 460, Train Loss: 0.851, Val f1_micro: 0.288
Epoch: 480, Train Loss: 0.843, Val f1_micro: 0.288
Epoch: 500, Train Loss: 0.820, Val f1_micro: 0.291
f1-micro: 0.291, f1-macro: 0.281, f1-weighted: 0.285, , roc-auc: 0.679
##### RUN 4 #####
Epoch: 020, Train Loss: 2.124, Val f1_micro: 0.190
Epoch: 040, Train Loss: 1.836, Val f1_micro: 0.218
Epoch: 060, Train Loss: 1.659, Val f1_micro: 0.229
Epoch: 080, Train Loss: 1.561, Val f1_micro: 0.237
Epoch: 100, Train Loss: 1.472, Val f1_micro: 0.244
Epoch: 120, Train Loss: 1.387, Val f1_micro: 0.253
Epoch: 140, Train Loss: 1.333, Val f1_micro: 0.255
Epoch: 160, Train Loss: 1.277, Val f1_micro: 0.261
Epoch: 180, Train Loss: 1.222, Val f1_micro: 0.265
Epoch: 200, Train Loss: 1.173, Val f1_micro: 0.268
Epoch: 220, Train Loss: 1.149, Val f1_micro: 0.270
Epoch: 240, Train Loss: 1.111, Val f1_micro: 0.270
Epoch: 260, Train Loss: 1.071, Val f1_micro: 0.273
Epoch: 280, Train Loss: 1.039, Val f1_micro: 0.275
Epoch: 300, Train Loss: 1.028, Val f1_micro: 0.278
Epoch: 320, Train Loss: 0.981, Val f1_micro: 0.280
Epoch: 340, Train Loss: 0.963, Val f1_micro: 0.281
Epoch: 360, Train Loss: 0.942, Val f1_micro: 0.282
Epoch: 380, Train Loss: 0.923, Val f1_micro: 0.284
Epoch: 400, Train Loss: 0.912, Val f1_micro: 0.286
Epoch: 420, Train Loss: 0.889, Val f1_micro: 0.287
Epoch: 440, Train Loss: 0.875, Val f1_micro: 0.289
Epoch: 460, Train Loss: 0.854, Val f1_micro: 0.291
Epoch: 480, Train Loss: 0.855, Val f1_micro: 0.292
Epoch: 500, Train Loss: 0.833, Val f1_micro: 0.293
f1-micro: 0.293, f1-macro: 0.283, f1-weighted: 0.287, , roc-auc: 0.679
##### RUN 5 #####
Epoch: 020, Train Loss: 2.098, Val f1_micro: 0.188
Epoch: 040, Train Loss: 1.824, Val f1_micro: 0.219
Epoch: 060, Train Loss: 1.670, Val f1_micro: 0.233
Epoch: 080, Train Loss: 1.560, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.457, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.396, Val f1_micro: 0.251
Epoch: 140, Train Loss: 1.323, Val f1_micro: 0.253
Epoch: 160, Train Loss: 1.282, Val f1_micro: 0.259
Epoch: 180, Train Loss: 1.230, Val f1_micro: 0.267
Epoch: 200, Train Loss: 1.189, Val f1_micro: 0.270
Epoch: 220, Train Loss: 1.148, Val f1_micro: 0.271
Epoch: 240, Train Loss: 1.115, Val f1_micro: 0.271
Epoch: 260, Train Loss: 1.084, Val f1_micro: 0.275
Epoch: 280, Train Loss: 1.035, Val f1_micro: 0.273
Epoch: 300, Train Loss: 1.014, Val f1_micro: 0.278
Epoch: 320, Train Loss: 0.991, Val f1_micro: 0.279
Epoch: 340, Train Loss: 0.961, Val f1_micro: 0.279
Epoch: 360, Train Loss: 0.942, Val f1_micro: 0.281
Epoch: 380, Train Loss: 0.930, Val f1_micro: 0.285
Epoch: 400, Train Loss: 0.915, Val f1_micro: 0.285
Epoch: 420, Train Loss: 0.885, Val f1_micro: 0.287
Epoch: 440, Train Loss: 0.867, Val f1_micro: 0.285
Epoch: 460, Train Loss: 0.844, Val f1_micro: 0.288
Epoch: 480, Train Loss: 0.839, Val f1_micro: 0.290
Epoch: 500, Train Loss: 0.821, Val f1_micro: 0.289
f1-micro: 0.289, f1-macro: 0.279, f1-weighted: 0.283, , roc-auc: 0.678
########## Hyperparameters combination ##########
(512, 0.3, 0.001, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.081, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.812, Val f1_micro: 0.218
Epoch: 060, Train Loss: 1.663, Val f1_micro: 0.230
Epoch: 080, Train Loss: 1.561, Val f1_micro: 0.239
Epoch: 100, Train Loss: 1.474, Val f1_micro: 0.244
Epoch: 120, Train Loss: 1.389, Val f1_micro: 0.248
Epoch: 140, Train Loss: 1.346, Val f1_micro: 0.257
Epoch: 160, Train Loss: 1.306, Val f1_micro: 0.257
Epoch: 180, Train Loss: 1.258, Val f1_micro: 0.262
Epoch: 200, Train Loss: 1.223, Val f1_micro: 0.264
Epoch: 220, Train Loss: 1.182, Val f1_micro: 0.266
Epoch: 240, Train Loss: 1.145, Val f1_micro: 0.267
Epoch: 260, Train Loss: 1.139, Val f1_micro: 0.271
Epoch: 280, Train Loss: 1.119, Val f1_micro: 0.269
Epoch: 300, Train Loss: 1.088, Val f1_micro: 0.273
Epoch: 320, Train Loss: 1.079, Val f1_micro: 0.273
Epoch: 340, Train Loss: 1.064, Val f1_micro: 0.275
Epoch: 360, Train Loss: 1.036, Val f1_micro: 0.277
Epoch: 380, Train Loss: 1.022, Val f1_micro: 0.276
Epoch: 400, Train Loss: 1.007, Val f1_micro: 0.278
Epoch: 420, Train Loss: 0.987, Val f1_micro: 0.280
Epoch: 440, Train Loss: 0.961, Val f1_micro: 0.279
Epoch: 460, Train Loss: 0.957, Val f1_micro: 0.278
Epoch: 480, Train Loss: 0.940, Val f1_micro: 0.279
Epoch: 500, Train Loss: 0.937, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.270, f1-weighted: 0.272, , roc-auc: 0.676
##### RUN 2 #####
Epoch: 020, Train Loss: 2.091, Val f1_micro: 0.188
Epoch: 040, Train Loss: 1.820, Val f1_micro: 0.220
Epoch: 060, Train Loss: 1.663, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.572, Val f1_micro: 0.238
Epoch: 100, Train Loss: 1.472, Val f1_micro: 0.245
Epoch: 120, Train Loss: 1.403, Val f1_micro: 0.252
Epoch: 140, Train Loss: 1.359, Val f1_micro: 0.256
Epoch: 160, Train Loss: 1.312, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.261, Val f1_micro: 0.261
Epoch: 200, Train Loss: 1.224, Val f1_micro: 0.265
Epoch: 220, Train Loss: 1.192, Val f1_micro: 0.267
Epoch: 240, Train Loss: 1.172, Val f1_micro: 0.269
Epoch: 260, Train Loss: 1.131, Val f1_micro: 0.271
Epoch: 280, Train Loss: 1.111, Val f1_micro: 0.271
Epoch: 300, Train Loss: 1.096, Val f1_micro: 0.272
Epoch: 320, Train Loss: 1.072, Val f1_micro: 0.273
Epoch: 340, Train Loss: 1.048, Val f1_micro: 0.276
Epoch: 360, Train Loss: 1.042, Val f1_micro: 0.276
Epoch: 380, Train Loss: 1.014, Val f1_micro: 0.279
Epoch: 400, Train Loss: 1.020, Val f1_micro: 0.278
Epoch: 420, Train Loss: 1.000, Val f1_micro: 0.277
Epoch: 440, Train Loss: 0.980, Val f1_micro: 0.279
Epoch: 460, Train Loss: 0.968, Val f1_micro: 0.277
Epoch: 480, Train Loss: 0.962, Val f1_micro: 0.280
Epoch: 500, Train Loss: 0.941, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.270, f1-weighted: 0.272, , roc-auc: 0.676
##### RUN 3 #####
Epoch: 020, Train Loss: 2.088, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.824, Val f1_micro: 0.219
Epoch: 060, Train Loss: 1.663, Val f1_micro: 0.230
Epoch: 080, Train Loss: 1.564, Val f1_micro: 0.235
Epoch: 100, Train Loss: 1.477, Val f1_micro: 0.244
Epoch: 120, Train Loss: 1.413, Val f1_micro: 0.249
Epoch: 140, Train Loss: 1.361, Val f1_micro: 0.256
Epoch: 160, Train Loss: 1.301, Val f1_micro: 0.257
Epoch: 180, Train Loss: 1.266, Val f1_micro: 0.261
Epoch: 200, Train Loss: 1.242, Val f1_micro: 0.263
Epoch: 220, Train Loss: 1.193, Val f1_micro: 0.266
Epoch: 240, Train Loss: 1.175, Val f1_micro: 0.265
Epoch: 260, Train Loss: 1.127, Val f1_micro: 0.269
Epoch: 280, Train Loss: 1.124, Val f1_micro: 0.269
Epoch: 300, Train Loss: 1.116, Val f1_micro: 0.272
Epoch: 320, Train Loss: 1.069, Val f1_micro: 0.274
Epoch: 340, Train Loss: 1.068, Val f1_micro: 0.274
Epoch: 360, Train Loss: 1.010, Val f1_micro: 0.274
Epoch: 380, Train Loss: 1.024, Val f1_micro: 0.277
Epoch: 400, Train Loss: 0.992, Val f1_micro: 0.279
Epoch: 420, Train Loss: 0.994, Val f1_micro: 0.280
Epoch: 440, Train Loss: 0.973, Val f1_micro: 0.280
Epoch: 460, Train Loss: 0.962, Val f1_micro: 0.282
Epoch: 480, Train Loss: 0.964, Val f1_micro: 0.280
Epoch: 500, Train Loss: 0.934, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.270, f1-weighted: 0.273, , roc-auc: 0.676
##### RUN 4 #####
Epoch: 020, Train Loss: 2.100, Val f1_micro: 0.188
Epoch: 040, Train Loss: 1.822, Val f1_micro: 0.219
Epoch: 060, Train Loss: 1.664, Val f1_micro: 0.233
Epoch: 080, Train Loss: 1.564, Val f1_micro: 0.237
Epoch: 100, Train Loss: 1.465, Val f1_micro: 0.247
Epoch: 120, Train Loss: 1.411, Val f1_micro: 0.252
Epoch: 140, Train Loss: 1.350, Val f1_micro: 0.255
Epoch: 160, Train Loss: 1.309, Val f1_micro: 0.261
Epoch: 180, Train Loss: 1.264, Val f1_micro: 0.261
Epoch: 200, Train Loss: 1.230, Val f1_micro: 0.262
Epoch: 220, Train Loss: 1.210, Val f1_micro: 0.267
Epoch: 240, Train Loss: 1.178, Val f1_micro: 0.267
Epoch: 260, Train Loss: 1.132, Val f1_micro: 0.271
Epoch: 280, Train Loss: 1.111, Val f1_micro: 0.272
Epoch: 300, Train Loss: 1.085, Val f1_micro: 0.274
Epoch: 320, Train Loss: 1.071, Val f1_micro: 0.274
Epoch: 340, Train Loss: 1.065, Val f1_micro: 0.274
Epoch: 360, Train Loss: 1.047, Val f1_micro: 0.275
Epoch: 380, Train Loss: 1.022, Val f1_micro: 0.276
Epoch: 400, Train Loss: 1.004, Val f1_micro: 0.276
Epoch: 420, Train Loss: 0.990, Val f1_micro: 0.278
Epoch: 440, Train Loss: 0.991, Val f1_micro: 0.280
Epoch: 460, Train Loss: 0.955, Val f1_micro: 0.278
Epoch: 480, Train Loss: 0.953, Val f1_micro: 0.282
Epoch: 500, Train Loss: 0.939, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.270, f1-weighted: 0.272, , roc-auc: 0.675
##### RUN 5 #####
Epoch: 020, Train Loss: 2.094, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.823, Val f1_micro: 0.220
Epoch: 060, Train Loss: 1.666, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.552, Val f1_micro: 0.238
Epoch: 100, Train Loss: 1.471, Val f1_micro: 0.243
Epoch: 120, Train Loss: 1.411, Val f1_micro: 0.251
Epoch: 140, Train Loss: 1.359, Val f1_micro: 0.257
Epoch: 160, Train Loss: 1.314, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.255, Val f1_micro: 0.261
Epoch: 200, Train Loss: 1.231, Val f1_micro: 0.262
Epoch: 220, Train Loss: 1.200, Val f1_micro: 0.266
Epoch: 240, Train Loss: 1.148, Val f1_micro: 0.268
Epoch: 260, Train Loss: 1.140, Val f1_micro: 0.269
Epoch: 280, Train Loss: 1.111, Val f1_micro: 0.272
Epoch: 300, Train Loss: 1.093, Val f1_micro: 0.272
Epoch: 320, Train Loss: 1.062, Val f1_micro: 0.272
Epoch: 340, Train Loss: 1.036, Val f1_micro: 0.273
Epoch: 360, Train Loss: 1.036, Val f1_micro: 0.274
Epoch: 380, Train Loss: 1.030, Val f1_micro: 0.276
Epoch: 400, Train Loss: 1.001, Val f1_micro: 0.275
Epoch: 420, Train Loss: 0.997, Val f1_micro: 0.277
Epoch: 440, Train Loss: 0.964, Val f1_micro: 0.279
Epoch: 460, Train Loss: 0.974, Val f1_micro: 0.281
Epoch: 480, Train Loss: 0.948, Val f1_micro: 0.279
Epoch: 500, Train Loss: 0.947, Val f1_micro: 0.282
f1-micro: 0.282, f1-macro: 0.271, f1-weighted: 0.273, , roc-auc: 0.676
########## Hyperparameters combination ##########
(512, 0.3, 0.001, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.122, Val f1_micro: 0.188
Epoch: 040, Train Loss: 1.866, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.744, Val f1_micro: 0.223
Epoch: 080, Train Loss: 1.658, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.626, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.573, Val f1_micro: 0.232
Epoch: 140, Train Loss: 1.549, Val f1_micro: 0.233
Epoch: 160, Train Loss: 1.517, Val f1_micro: 0.237
Epoch: 180, Train Loss: 1.525, Val f1_micro: 0.236
Epoch: 200, Train Loss: 1.504, Val f1_micro: 0.239
Epoch: 220, Train Loss: 1.501, Val f1_micro: 0.238
Epoch: 240, Train Loss: 1.492, Val f1_micro: 0.237
Epoch: 260, Train Loss: 1.493, Val f1_micro: 0.237
Epoch: 280, Train Loss: 1.494, Val f1_micro: 0.235
Epoch: 300, Train Loss: 1.492, Val f1_micro: 0.238
Epoch: 320, Train Loss: 1.487, Val f1_micro: 0.238
Epoch: 340, Train Loss: 1.496, Val f1_micro: 0.237
Epoch: 360, Train Loss: 1.488, Val f1_micro: 0.237
Epoch: 380, Train Loss: 1.487, Val f1_micro: 0.237
Epoch: 400, Train Loss: 1.487, Val f1_micro: 0.236
Epoch: 420, Train Loss: 1.495, Val f1_micro: 0.235
Epoch: 440, Train Loss: 1.488, Val f1_micro: 0.235
Epoch: 460, Train Loss: 1.500, Val f1_micro: 0.238
Epoch: 480, Train Loss: 1.492, Val f1_micro: 0.234
Epoch: 500, Train Loss: 1.505, Val f1_micro: 0.233
f1-micro: 0.233, f1-macro: 0.206, f1-weighted: 0.206, , roc-auc: 0.655
##### RUN 2 #####
Epoch: 020, Train Loss: 2.116, Val f1_micro: 0.187
Epoch: 040, Train Loss: 1.870, Val f1_micro: 0.217
Epoch: 060, Train Loss: 1.747, Val f1_micro: 0.223
Epoch: 080, Train Loss: 1.673, Val f1_micro: 0.224
Epoch: 100, Train Loss: 1.603, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.577, Val f1_micro: 0.234
Epoch: 140, Train Loss: 1.540, Val f1_micro: 0.236
Epoch: 160, Train Loss: 1.530, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.512, Val f1_micro: 0.235
Epoch: 200, Train Loss: 1.505, Val f1_micro: 0.238
Epoch: 220, Train Loss: 1.488, Val f1_micro: 0.239
Epoch: 240, Train Loss: 1.494, Val f1_micro: 0.236
Epoch: 260, Train Loss: 1.481, Val f1_micro: 0.241
Epoch: 280, Train Loss: 1.491, Val f1_micro: 0.238
Epoch: 300, Train Loss: 1.483, Val f1_micro: 0.238
Epoch: 320, Train Loss: 1.485, Val f1_micro: 0.237
Epoch: 340, Train Loss: 1.482, Val f1_micro: 0.236
Epoch: 360, Train Loss: 1.486, Val f1_micro: 0.237
Epoch: 380, Train Loss: 1.486, Val f1_micro: 0.235
Epoch: 400, Train Loss: 1.487, Val f1_micro: 0.236
Epoch: 420, Train Loss: 1.496, Val f1_micro: 0.233
Epoch: 440, Train Loss: 1.485, Val f1_micro: 0.234
Epoch: 460, Train Loss: 1.497, Val f1_micro: 0.230
Epoch: 480, Train Loss: 1.503, Val f1_micro: 0.233
Epoch: 500, Train Loss: 1.492, Val f1_micro: 0.231
f1-micro: 0.231, f1-macro: 0.204, f1-weighted: 0.204, , roc-auc: 0.655
##### RUN 3 #####
Epoch: 020, Train Loss: 2.121, Val f1_micro: 0.188
Epoch: 040, Train Loss: 1.862, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.740, Val f1_micro: 0.223
Epoch: 080, Train Loss: 1.662, Val f1_micro: 0.225
Epoch: 100, Train Loss: 1.603, Val f1_micro: 0.229
Epoch: 120, Train Loss: 1.569, Val f1_micro: 0.231
Epoch: 140, Train Loss: 1.555, Val f1_micro: 0.235
Epoch: 160, Train Loss: 1.536, Val f1_micro: 0.239
Epoch: 180, Train Loss: 1.513, Val f1_micro: 0.237
Epoch: 200, Train Loss: 1.501, Val f1_micro: 0.237
Epoch: 220, Train Loss: 1.504, Val f1_micro: 0.236
Epoch: 240, Train Loss: 1.508, Val f1_micro: 0.237
Epoch: 260, Train Loss: 1.481, Val f1_micro: 0.239
Epoch: 280, Train Loss: 1.494, Val f1_micro: 0.237
Epoch: 300, Train Loss: 1.482, Val f1_micro: 0.237
Epoch: 320, Train Loss: 1.497, Val f1_micro: 0.236
Epoch: 340, Train Loss: 1.495, Val f1_micro: 0.235
Epoch: 360, Train Loss: 1.494, Val f1_micro: 0.238
Epoch: 380, Train Loss: 1.485, Val f1_micro: 0.237
Epoch: 400, Train Loss: 1.489, Val f1_micro: 0.234
Epoch: 420, Train Loss: 1.489, Val f1_micro: 0.235
Epoch: 440, Train Loss: 1.500, Val f1_micro: 0.234
Epoch: 460, Train Loss: 1.499, Val f1_micro: 0.232
Epoch: 480, Train Loss: 1.499, Val f1_micro: 0.235
Epoch: 500, Train Loss: 1.495, Val f1_micro: 0.231
f1-micro: 0.231, f1-macro: 0.203, f1-weighted: 0.203, , roc-auc: 0.655
##### RUN 4 #####
Epoch: 020, Train Loss: 2.124, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.865, Val f1_micro: 0.214
Epoch: 060, Train Loss: 1.747, Val f1_micro: 0.222
Epoch: 080, Train Loss: 1.680, Val f1_micro: 0.224
Epoch: 100, Train Loss: 1.613, Val f1_micro: 0.229
Epoch: 120, Train Loss: 1.579, Val f1_micro: 0.235
Epoch: 140, Train Loss: 1.544, Val f1_micro: 0.234
Epoch: 160, Train Loss: 1.528, Val f1_micro: 0.237
Epoch: 180, Train Loss: 1.512, Val f1_micro: 0.237
Epoch: 200, Train Loss: 1.498, Val f1_micro: 0.238
Epoch: 220, Train Loss: 1.500, Val f1_micro: 0.238
Epoch: 240, Train Loss: 1.497, Val f1_micro: 0.237
Epoch: 260, Train Loss: 1.499, Val f1_micro: 0.237
Epoch: 280, Train Loss: 1.501, Val f1_micro: 0.236
Epoch: 300, Train Loss: 1.489, Val f1_micro: 0.238
Epoch: 320, Train Loss: 1.486, Val f1_micro: 0.237
Epoch: 340, Train Loss: 1.491, Val f1_micro: 0.237
Epoch: 360, Train Loss: 1.493, Val f1_micro: 0.237
Epoch: 380, Train Loss: 1.485, Val f1_micro: 0.235
Epoch: 400, Train Loss: 1.495, Val f1_micro: 0.234
Epoch: 420, Train Loss: 1.498, Val f1_micro: 0.231
Epoch: 440, Train Loss: 1.487, Val f1_micro: 0.233
Epoch: 460, Train Loss: 1.502, Val f1_micro: 0.234
Epoch: 480, Train Loss: 1.500, Val f1_micro: 0.233
Epoch: 500, Train Loss: 1.506, Val f1_micro: 0.232
f1-micro: 0.232, f1-macro: 0.205, f1-weighted: 0.204, , roc-auc: 0.656
##### RUN 5 #####
Epoch: 020, Train Loss: 2.124, Val f1_micro: 0.183
Epoch: 040, Train Loss: 1.878, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.748, Val f1_micro: 0.224
Epoch: 080, Train Loss: 1.659, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.601, Val f1_micro: 0.230
Epoch: 120, Train Loss: 1.573, Val f1_micro: 0.236
Epoch: 140, Train Loss: 1.553, Val f1_micro: 0.236
Epoch: 160, Train Loss: 1.540, Val f1_micro: 0.237
Epoch: 180, Train Loss: 1.528, Val f1_micro: 0.237
Epoch: 200, Train Loss: 1.514, Val f1_micro: 0.239
Epoch: 220, Train Loss: 1.502, Val f1_micro: 0.239
Epoch: 240, Train Loss: 1.506, Val f1_micro: 0.240
Epoch: 260, Train Loss: 1.495, Val f1_micro: 0.238
Epoch: 280, Train Loss: 1.491, Val f1_micro: 0.238
Epoch: 300, Train Loss: 1.490, Val f1_micro: 0.238
Epoch: 320, Train Loss: 1.495, Val f1_micro: 0.239
Epoch: 340, Train Loss: 1.485, Val f1_micro: 0.236
Epoch: 360, Train Loss: 1.488, Val f1_micro: 0.235
Epoch: 380, Train Loss: 1.492, Val f1_micro: 0.239
Epoch: 400, Train Loss: 1.497, Val f1_micro: 0.235
Epoch: 420, Train Loss: 1.489, Val f1_micro: 0.238
Epoch: 440, Train Loss: 1.496, Val f1_micro: 0.233
Epoch: 460, Train Loss: 1.496, Val f1_micro: 0.234
Epoch: 480, Train Loss: 1.482, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.499, Val f1_micro: 0.233
f1-micro: 0.233, f1-macro: 0.205, f1-weighted: 0.205, , roc-auc: 0.655
########## Hyperparameters combination ##########
(512, 0.3, 0.005, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.583, Val f1_micro: 0.237
Epoch: 040, Train Loss: 1.266, Val f1_micro: 0.257
Epoch: 060, Train Loss: 1.099, Val f1_micro: 0.268
Epoch: 080, Train Loss: 0.952, Val f1_micro: 0.281
Epoch: 100, Train Loss: 0.854, Val f1_micro: 0.282
Epoch: 120, Train Loss: 0.774, Val f1_micro: 0.288
Epoch: 140, Train Loss: 0.701, Val f1_micro: 0.295
Epoch: 160, Train Loss: 0.633, Val f1_micro: 0.299
Epoch: 180, Train Loss: 0.579, Val f1_micro: 0.304
Epoch: 200, Train Loss: 0.541, Val f1_micro: 0.303
Epoch: 220, Train Loss: 0.479, Val f1_micro: 0.308
Epoch: 240, Train Loss: 0.447, Val f1_micro: 0.311
Epoch: 260, Train Loss: 0.414, Val f1_micro: 0.311
Epoch: 280, Train Loss: 0.389, Val f1_micro: 0.315
Epoch: 300, Train Loss: 0.357, Val f1_micro: 0.315
Epoch: 320, Train Loss: 0.323, Val f1_micro: 0.314
Epoch: 340, Train Loss: 0.313, Val f1_micro: 0.317
Epoch: 360, Train Loss: 0.278, Val f1_micro: 0.316
Epoch: 380, Train Loss: 0.282, Val f1_micro: 0.316
Epoch: 400, Train Loss: 0.267, Val f1_micro: 0.314
Epoch: 420, Train Loss: 0.261, Val f1_micro: 0.316
Epoch: 440, Train Loss: 0.245, Val f1_micro: 0.316
Epoch: 460, Train Loss: 0.234, Val f1_micro: 0.316
Epoch: 480, Train Loss: 0.215, Val f1_micro: 0.315
Epoch: 500, Train Loss: 0.224, Val f1_micro: 0.318
f1-micro: 0.318, f1-macro: 0.311, f1-weighted: 0.318, , roc-auc: 0.686
##### RUN 2 #####
Epoch: 020, Train Loss: 1.585, Val f1_micro: 0.236
Epoch: 040, Train Loss: 1.272, Val f1_micro: 0.258
Epoch: 060, Train Loss: 1.095, Val f1_micro: 0.271
Epoch: 080, Train Loss: 0.954, Val f1_micro: 0.280
Epoch: 100, Train Loss: 0.850, Val f1_micro: 0.287
Epoch: 120, Train Loss: 0.755, Val f1_micro: 0.290
Epoch: 140, Train Loss: 0.696, Val f1_micro: 0.296
Epoch: 160, Train Loss: 0.628, Val f1_micro: 0.299
Epoch: 180, Train Loss: 0.571, Val f1_micro: 0.302
Epoch: 200, Train Loss: 0.533, Val f1_micro: 0.304
Epoch: 220, Train Loss: 0.473, Val f1_micro: 0.306
Epoch: 240, Train Loss: 0.439, Val f1_micro: 0.309
Epoch: 260, Train Loss: 0.421, Val f1_micro: 0.310
Epoch: 280, Train Loss: 0.390, Val f1_micro: 0.313
Epoch: 300, Train Loss: 0.356, Val f1_micro: 0.316
Epoch: 320, Train Loss: 0.325, Val f1_micro: 0.316
Epoch: 340, Train Loss: 0.332, Val f1_micro: 0.316
Epoch: 360, Train Loss: 0.308, Val f1_micro: 0.317
Epoch: 380, Train Loss: 0.294, Val f1_micro: 0.318
Epoch: 400, Train Loss: 0.271, Val f1_micro: 0.320
Epoch: 420, Train Loss: 0.252, Val f1_micro: 0.319
Epoch: 440, Train Loss: 0.256, Val f1_micro: 0.318
Epoch: 460, Train Loss: 0.237, Val f1_micro: 0.321
Epoch: 480, Train Loss: 0.230, Val f1_micro: 0.320
Epoch: 500, Train Loss: 0.215, Val f1_micro: 0.321
f1-micro: 0.321, f1-macro: 0.314, f1-weighted: 0.321, , roc-auc: 0.687
##### RUN 3 #####
Epoch: 020, Train Loss: 1.589, Val f1_micro: 0.236
Epoch: 040, Train Loss: 1.285, Val f1_micro: 0.254
Epoch: 060, Train Loss: 1.078, Val f1_micro: 0.271
Epoch: 080, Train Loss: 0.962, Val f1_micro: 0.279
Epoch: 100, Train Loss: 0.837, Val f1_micro: 0.287
Epoch: 120, Train Loss: 0.764, Val f1_micro: 0.287
Epoch: 140, Train Loss: 0.685, Val f1_micro: 0.291
Epoch: 160, Train Loss: 0.635, Val f1_micro: 0.299
Epoch: 180, Train Loss: 0.574, Val f1_micro: 0.301
Epoch: 200, Train Loss: 0.526, Val f1_micro: 0.305
Epoch: 220, Train Loss: 0.480, Val f1_micro: 0.309
Epoch: 240, Train Loss: 0.447, Val f1_micro: 0.308
Epoch: 260, Train Loss: 0.411, Val f1_micro: 0.311
Epoch: 280, Train Loss: 0.370, Val f1_micro: 0.314
Epoch: 300, Train Loss: 0.344, Val f1_micro: 0.315
Epoch: 320, Train Loss: 0.338, Val f1_micro: 0.316
Epoch: 340, Train Loss: 0.311, Val f1_micro: 0.317
Epoch: 360, Train Loss: 0.296, Val f1_micro: 0.318
Epoch: 380, Train Loss: 0.274, Val f1_micro: 0.316
Epoch: 400, Train Loss: 0.273, Val f1_micro: 0.319
Epoch: 420, Train Loss: 0.269, Val f1_micro: 0.316
Epoch: 440, Train Loss: 0.250, Val f1_micro: 0.320
Epoch: 460, Train Loss: 0.244, Val f1_micro: 0.319
Epoch: 480, Train Loss: 0.225, Val f1_micro: 0.319
Epoch: 500, Train Loss: 0.211, Val f1_micro: 0.319
f1-micro: 0.319, f1-macro: 0.312, f1-weighted: 0.318, , roc-auc: 0.686
##### RUN 4 #####
Epoch: 020, Train Loss: 1.582, Val f1_micro: 0.238
Epoch: 040, Train Loss: 1.272, Val f1_micro: 0.259
Epoch: 060, Train Loss: 1.107, Val f1_micro: 0.273
Epoch: 080, Train Loss: 0.954, Val f1_micro: 0.277
Epoch: 100, Train Loss: 0.847, Val f1_micro: 0.287
Epoch: 120, Train Loss: 0.761, Val f1_micro: 0.288
Epoch: 140, Train Loss: 0.704, Val f1_micro: 0.293
Epoch: 160, Train Loss: 0.628, Val f1_micro: 0.298
Epoch: 180, Train Loss: 0.570, Val f1_micro: 0.299
Epoch: 200, Train Loss: 0.525, Val f1_micro: 0.306
Epoch: 220, Train Loss: 0.473, Val f1_micro: 0.306
Epoch: 240, Train Loss: 0.447, Val f1_micro: 0.310
Epoch: 260, Train Loss: 0.419, Val f1_micro: 0.312
Epoch: 280, Train Loss: 0.403, Val f1_micro: 0.314
Epoch: 300, Train Loss: 0.353, Val f1_micro: 0.313
Epoch: 320, Train Loss: 0.337, Val f1_micro: 0.315
Epoch: 340, Train Loss: 0.333, Val f1_micro: 0.314
Epoch: 360, Train Loss: 0.298, Val f1_micro: 0.316
Epoch: 380, Train Loss: 0.272, Val f1_micro: 0.314
Epoch: 400, Train Loss: 0.266, Val f1_micro: 0.318
Epoch: 420, Train Loss: 0.262, Val f1_micro: 0.315
Epoch: 440, Train Loss: 0.244, Val f1_micro: 0.318
Epoch: 460, Train Loss: 0.242, Val f1_micro: 0.317
Epoch: 480, Train Loss: 0.215, Val f1_micro: 0.317
Epoch: 500, Train Loss: 0.226, Val f1_micro: 0.318
f1-micro: 0.318, f1-macro: 0.311, f1-weighted: 0.317, , roc-auc: 0.687
##### RUN 5 #####
Epoch: 020, Train Loss: 1.574, Val f1_micro: 0.236
Epoch: 040, Train Loss: 1.260, Val f1_micro: 0.258
Epoch: 060, Train Loss: 1.077, Val f1_micro: 0.269
Epoch: 080, Train Loss: 0.943, Val f1_micro: 0.280
Epoch: 100, Train Loss: 0.856, Val f1_micro: 0.288
Epoch: 120, Train Loss: 0.754, Val f1_micro: 0.290
Epoch: 140, Train Loss: 0.683, Val f1_micro: 0.293
Epoch: 160, Train Loss: 0.625, Val f1_micro: 0.300
Epoch: 180, Train Loss: 0.563, Val f1_micro: 0.300
Epoch: 200, Train Loss: 0.515, Val f1_micro: 0.303
Epoch: 220, Train Loss: 0.466, Val f1_micro: 0.308
Epoch: 240, Train Loss: 0.429, Val f1_micro: 0.308
Epoch: 260, Train Loss: 0.396, Val f1_micro: 0.311
Epoch: 280, Train Loss: 0.377, Val f1_micro: 0.314
Epoch: 300, Train Loss: 0.351, Val f1_micro: 0.314
Epoch: 320, Train Loss: 0.335, Val f1_micro: 0.316
Epoch: 340, Train Loss: 0.303, Val f1_micro: 0.316
Epoch: 360, Train Loss: 0.291, Val f1_micro: 0.314
Epoch: 380, Train Loss: 0.279, Val f1_micro: 0.315
Epoch: 400, Train Loss: 0.264, Val f1_micro: 0.316
Epoch: 420, Train Loss: 0.272, Val f1_micro: 0.315
Epoch: 440, Train Loss: 0.243, Val f1_micro: 0.315
Epoch: 460, Train Loss: 0.212, Val f1_micro: 0.318
Epoch: 480, Train Loss: 0.210, Val f1_micro: 0.319
Epoch: 500, Train Loss: 0.224, Val f1_micro: 0.317
f1-micro: 0.317, f1-macro: 0.310, f1-weighted: 0.317, , roc-auc: 0.684
########## Hyperparameters combination ##########
(512, 0.3, 0.005, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.592, Val f1_micro: 0.242
Epoch: 040, Train Loss: 1.303, Val f1_micro: 0.259
Epoch: 060, Train Loss: 1.131, Val f1_micro: 0.271
Epoch: 080, Train Loss: 1.021, Val f1_micro: 0.280
Epoch: 100, Train Loss: 0.961, Val f1_micro: 0.287
Epoch: 120, Train Loss: 0.881, Val f1_micro: 0.286
Epoch: 140, Train Loss: 0.839, Val f1_micro: 0.292
Epoch: 160, Train Loss: 0.784, Val f1_micro: 0.296
Epoch: 180, Train Loss: 0.744, Val f1_micro: 0.295
Epoch: 200, Train Loss: 0.692, Val f1_micro: 0.300
Epoch: 220, Train Loss: 0.682, Val f1_micro: 0.300
Epoch: 240, Train Loss: 0.650, Val f1_micro: 0.302
Epoch: 260, Train Loss: 0.633, Val f1_micro: 0.304
Epoch: 280, Train Loss: 0.607, Val f1_micro: 0.305
Epoch: 300, Train Loss: 0.601, Val f1_micro: 0.309
Epoch: 320, Train Loss: 0.572, Val f1_micro: 0.310
Epoch: 340, Train Loss: 0.562, Val f1_micro: 0.311
Epoch: 360, Train Loss: 0.547, Val f1_micro: 0.311
Epoch: 380, Train Loss: 0.543, Val f1_micro: 0.314
Epoch: 400, Train Loss: 0.519, Val f1_micro: 0.314
Epoch: 420, Train Loss: 0.520, Val f1_micro: 0.316
Epoch: 440, Train Loss: 0.499, Val f1_micro: 0.315
Epoch: 460, Train Loss: 0.488, Val f1_micro: 0.312
Epoch: 480, Train Loss: 0.492, Val f1_micro: 0.316
Epoch: 500, Train Loss: 0.469, Val f1_micro: 0.316
f1-micro: 0.316, f1-macro: 0.309, f1-weighted: 0.315, , roc-auc: 0.680
##### RUN 2 #####
Epoch: 020, Train Loss: 1.592, Val f1_micro: 0.241
Epoch: 040, Train Loss: 1.292, Val f1_micro: 0.261
Epoch: 060, Train Loss: 1.137, Val f1_micro: 0.272
Epoch: 080, Train Loss: 1.021, Val f1_micro: 0.280
Epoch: 100, Train Loss: 0.939, Val f1_micro: 0.287
Epoch: 120, Train Loss: 0.883, Val f1_micro: 0.290
Epoch: 140, Train Loss: 0.832, Val f1_micro: 0.293
Epoch: 160, Train Loss: 0.775, Val f1_micro: 0.294
Epoch: 180, Train Loss: 0.754, Val f1_micro: 0.297
Epoch: 200, Train Loss: 0.696, Val f1_micro: 0.299
Epoch: 220, Train Loss: 0.672, Val f1_micro: 0.302
Epoch: 240, Train Loss: 0.651, Val f1_micro: 0.303
Epoch: 260, Train Loss: 0.627, Val f1_micro: 0.305
Epoch: 280, Train Loss: 0.599, Val f1_micro: 0.307
Epoch: 300, Train Loss: 0.587, Val f1_micro: 0.309
Epoch: 320, Train Loss: 0.558, Val f1_micro: 0.312
Epoch: 340, Train Loss: 0.550, Val f1_micro: 0.310
Epoch: 360, Train Loss: 0.539, Val f1_micro: 0.317
Epoch: 380, Train Loss: 0.521, Val f1_micro: 0.314
Epoch: 400, Train Loss: 0.517, Val f1_micro: 0.313
Epoch: 420, Train Loss: 0.509, Val f1_micro: 0.315
Epoch: 440, Train Loss: 0.486, Val f1_micro: 0.315
Epoch: 460, Train Loss: 0.488, Val f1_micro: 0.315
Epoch: 480, Train Loss: 0.482, Val f1_micro: 0.315
Epoch: 500, Train Loss: 0.464, Val f1_micro: 0.315
f1-micro: 0.315, f1-macro: 0.308, f1-weighted: 0.313, , roc-auc: 0.680
##### RUN 3 #####
Epoch: 020, Train Loss: 1.581, Val f1_micro: 0.241
Epoch: 040, Train Loss: 1.293, Val f1_micro: 0.259
Epoch: 060, Train Loss: 1.137, Val f1_micro: 0.272
Epoch: 080, Train Loss: 1.029, Val f1_micro: 0.281
Epoch: 100, Train Loss: 0.957, Val f1_micro: 0.286
Epoch: 120, Train Loss: 0.885, Val f1_micro: 0.288
Epoch: 140, Train Loss: 0.830, Val f1_micro: 0.292
Epoch: 160, Train Loss: 0.791, Val f1_micro: 0.291
Epoch: 180, Train Loss: 0.748, Val f1_micro: 0.293
Epoch: 200, Train Loss: 0.706, Val f1_micro: 0.299
Epoch: 220, Train Loss: 0.682, Val f1_micro: 0.301
Epoch: 240, Train Loss: 0.657, Val f1_micro: 0.305
Epoch: 260, Train Loss: 0.628, Val f1_micro: 0.305
Epoch: 280, Train Loss: 0.604, Val f1_micro: 0.307
Epoch: 300, Train Loss: 0.606, Val f1_micro: 0.310
Epoch: 320, Train Loss: 0.570, Val f1_micro: 0.311
Epoch: 340, Train Loss: 0.559, Val f1_micro: 0.314
Epoch: 360, Train Loss: 0.548, Val f1_micro: 0.314
Epoch: 380, Train Loss: 0.535, Val f1_micro: 0.315
Epoch: 400, Train Loss: 0.536, Val f1_micro: 0.313
Epoch: 420, Train Loss: 0.506, Val f1_micro: 0.313
Epoch: 440, Train Loss: 0.498, Val f1_micro: 0.313
Epoch: 460, Train Loss: 0.494, Val f1_micro: 0.317
Epoch: 480, Train Loss: 0.491, Val f1_micro: 0.319
Epoch: 500, Train Loss: 0.476, Val f1_micro: 0.321
f1-micro: 0.321, f1-macro: 0.312, f1-weighted: 0.318, , roc-auc: 0.683
##### RUN 4 #####
Epoch: 020, Train Loss: 1.590, Val f1_micro: 0.237
Epoch: 040, Train Loss: 1.318, Val f1_micro: 0.259
Epoch: 060, Train Loss: 1.145, Val f1_micro: 0.270
Epoch: 080, Train Loss: 1.010, Val f1_micro: 0.283
Epoch: 100, Train Loss: 0.947, Val f1_micro: 0.285
Epoch: 120, Train Loss: 0.881, Val f1_micro: 0.289
Epoch: 140, Train Loss: 0.819, Val f1_micro: 0.290
Epoch: 160, Train Loss: 0.801, Val f1_micro: 0.289
Epoch: 180, Train Loss: 0.744, Val f1_micro: 0.295
Epoch: 200, Train Loss: 0.716, Val f1_micro: 0.297
Epoch: 220, Train Loss: 0.690, Val f1_micro: 0.300
Epoch: 240, Train Loss: 0.661, Val f1_micro: 0.302
Epoch: 260, Train Loss: 0.643, Val f1_micro: 0.302
Epoch: 280, Train Loss: 0.612, Val f1_micro: 0.305
Epoch: 300, Train Loss: 0.602, Val f1_micro: 0.307
Epoch: 320, Train Loss: 0.587, Val f1_micro: 0.306
Epoch: 340, Train Loss: 0.554, Val f1_micro: 0.311
Epoch: 360, Train Loss: 0.548, Val f1_micro: 0.310
Epoch: 380, Train Loss: 0.541, Val f1_micro: 0.310
Epoch: 400, Train Loss: 0.523, Val f1_micro: 0.313
Epoch: 420, Train Loss: 0.514, Val f1_micro: 0.312
Epoch: 440, Train Loss: 0.507, Val f1_micro: 0.312
Epoch: 460, Train Loss: 0.483, Val f1_micro: 0.316
Epoch: 480, Train Loss: 0.478, Val f1_micro: 0.311
Epoch: 500, Train Loss: 0.461, Val f1_micro: 0.316
f1-micro: 0.316, f1-macro: 0.308, f1-weighted: 0.313, , roc-auc: 0.680
##### RUN 5 #####
Epoch: 020, Train Loss: 1.598, Val f1_micro: 0.235
Epoch: 040, Train Loss: 1.300, Val f1_micro: 0.261
Epoch: 060, Train Loss: 1.148, Val f1_micro: 0.274
Epoch: 080, Train Loss: 1.041, Val f1_micro: 0.281
Epoch: 100, Train Loss: 0.956, Val f1_micro: 0.289
Epoch: 120, Train Loss: 0.894, Val f1_micro: 0.292
Epoch: 140, Train Loss: 0.816, Val f1_micro: 0.292
Epoch: 160, Train Loss: 0.782, Val f1_micro: 0.294
Epoch: 180, Train Loss: 0.733, Val f1_micro: 0.298
Epoch: 200, Train Loss: 0.705, Val f1_micro: 0.295
Epoch: 220, Train Loss: 0.678, Val f1_micro: 0.303
Epoch: 240, Train Loss: 0.653, Val f1_micro: 0.305
Epoch: 260, Train Loss: 0.644, Val f1_micro: 0.307
Epoch: 280, Train Loss: 0.625, Val f1_micro: 0.306
Epoch: 300, Train Loss: 0.600, Val f1_micro: 0.309
Epoch: 320, Train Loss: 0.585, Val f1_micro: 0.311
Epoch: 340, Train Loss: 0.542, Val f1_micro: 0.312
Epoch: 360, Train Loss: 0.559, Val f1_micro: 0.316
Epoch: 380, Train Loss: 0.532, Val f1_micro: 0.312
Epoch: 400, Train Loss: 0.540, Val f1_micro: 0.314
Epoch: 420, Train Loss: 0.503, Val f1_micro: 0.313
Epoch: 440, Train Loss: 0.489, Val f1_micro: 0.314
Epoch: 460, Train Loss: 0.498, Val f1_micro: 0.315
Epoch: 480, Train Loss: 0.469, Val f1_micro: 0.317
Epoch: 500, Train Loss: 0.474, Val f1_micro: 0.318
f1-micro: 0.318, f1-macro: 0.310, f1-weighted: 0.315, , roc-auc: 0.681
########## Hyperparameters combination ##########
(512, 0.3, 0.005, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.588, Val f1_micro: 0.232
Epoch: 040, Train Loss: 1.321, Val f1_micro: 0.247
Epoch: 060, Train Loss: 1.191, Val f1_micro: 0.262
Epoch: 080, Train Loss: 1.113, Val f1_micro: 0.270
Epoch: 100, Train Loss: 1.045, Val f1_micro: 0.270
Epoch: 120, Train Loss: 0.987, Val f1_micro: 0.279
Epoch: 140, Train Loss: 0.953, Val f1_micro: 0.281
Epoch: 160, Train Loss: 0.925, Val f1_micro: 0.282
Epoch: 180, Train Loss: 0.901, Val f1_micro: 0.285
Epoch: 200, Train Loss: 0.856, Val f1_micro: 0.285
Epoch: 220, Train Loss: 0.834, Val f1_micro: 0.285
Epoch: 240, Train Loss: 0.826, Val f1_micro: 0.291
Epoch: 260, Train Loss: 0.801, Val f1_micro: 0.291
Epoch: 280, Train Loss: 0.780, Val f1_micro: 0.293
Epoch: 300, Train Loss: 0.789, Val f1_micro: 0.294
Epoch: 320, Train Loss: 0.755, Val f1_micro: 0.298
Epoch: 340, Train Loss: 0.757, Val f1_micro: 0.296
Epoch: 360, Train Loss: 0.757, Val f1_micro: 0.297
Epoch: 380, Train Loss: 0.735, Val f1_micro: 0.298
Epoch: 400, Train Loss: 0.724, Val f1_micro: 0.301
Epoch: 420, Train Loss: 0.704, Val f1_micro: 0.299
Epoch: 440, Train Loss: 0.730, Val f1_micro: 0.300
Epoch: 460, Train Loss: 0.711, Val f1_micro: 0.299
Epoch: 480, Train Loss: 0.713, Val f1_micro: 0.305
Epoch: 500, Train Loss: 0.675, Val f1_micro: 0.300
f1-micro: 0.300, f1-macro: 0.291, f1-weighted: 0.296, , roc-auc: 0.680
##### RUN 2 #####
Epoch: 020, Train Loss: 1.589, Val f1_micro: 0.233
Epoch: 040, Train Loss: 1.325, Val f1_micro: 0.252
Epoch: 060, Train Loss: 1.177, Val f1_micro: 0.265
Epoch: 080, Train Loss: 1.105, Val f1_micro: 0.272
Epoch: 100, Train Loss: 1.030, Val f1_micro: 0.272
Epoch: 120, Train Loss: 1.000, Val f1_micro: 0.282
Epoch: 140, Train Loss: 0.955, Val f1_micro: 0.281
Epoch: 160, Train Loss: 0.918, Val f1_micro: 0.285
Epoch: 180, Train Loss: 0.886, Val f1_micro: 0.288
Epoch: 200, Train Loss: 0.864, Val f1_micro: 0.289
Epoch: 220, Train Loss: 0.844, Val f1_micro: 0.290
Epoch: 240, Train Loss: 0.822, Val f1_micro: 0.294
Epoch: 260, Train Loss: 0.799, Val f1_micro: 0.292
Epoch: 280, Train Loss: 0.778, Val f1_micro: 0.297
Epoch: 300, Train Loss: 0.761, Val f1_micro: 0.298
Epoch: 320, Train Loss: 0.754, Val f1_micro: 0.294
Epoch: 340, Train Loss: 0.756, Val f1_micro: 0.297
Epoch: 360, Train Loss: 0.735, Val f1_micro: 0.299
Epoch: 380, Train Loss: 0.727, Val f1_micro: 0.297
Epoch: 400, Train Loss: 0.740, Val f1_micro: 0.299
Epoch: 420, Train Loss: 0.705, Val f1_micro: 0.302
Epoch: 440, Train Loss: 0.701, Val f1_micro: 0.299
Epoch: 460, Train Loss: 0.703, Val f1_micro: 0.302
Epoch: 480, Train Loss: 0.723, Val f1_micro: 0.303
Epoch: 500, Train Loss: 0.686, Val f1_micro: 0.304
f1-micro: 0.304, f1-macro: 0.295, f1-weighted: 0.300, , roc-auc: 0.680
##### RUN 3 #####
Epoch: 020, Train Loss: 1.584, Val f1_micro: 0.235
Epoch: 040, Train Loss: 1.320, Val f1_micro: 0.249
Epoch: 060, Train Loss: 1.187, Val f1_micro: 0.267
Epoch: 080, Train Loss: 1.083, Val f1_micro: 0.265
Epoch: 100, Train Loss: 1.031, Val f1_micro: 0.273
Epoch: 120, Train Loss: 0.986, Val f1_micro: 0.278
Epoch: 140, Train Loss: 0.960, Val f1_micro: 0.281
Epoch: 160, Train Loss: 0.921, Val f1_micro: 0.283
Epoch: 180, Train Loss: 0.871, Val f1_micro: 0.284
Epoch: 200, Train Loss: 0.859, Val f1_micro: 0.289
Epoch: 220, Train Loss: 0.830, Val f1_micro: 0.286
Epoch: 240, Train Loss: 0.827, Val f1_micro: 0.291
Epoch: 260, Train Loss: 0.808, Val f1_micro: 0.293
Epoch: 280, Train Loss: 0.784, Val f1_micro: 0.290
Epoch: 300, Train Loss: 0.774, Val f1_micro: 0.294
Epoch: 320, Train Loss: 0.769, Val f1_micro: 0.295
Epoch: 340, Train Loss: 0.757, Val f1_micro: 0.296
Epoch: 360, Train Loss: 0.742, Val f1_micro: 0.295
Epoch: 380, Train Loss: 0.745, Val f1_micro: 0.296
Epoch: 400, Train Loss: 0.729, Val f1_micro: 0.298
Epoch: 420, Train Loss: 0.707, Val f1_micro: 0.299
Epoch: 440, Train Loss: 0.708, Val f1_micro: 0.303
Epoch: 460, Train Loss: 0.697, Val f1_micro: 0.302
Epoch: 480, Train Loss: 0.683, Val f1_micro: 0.301
Epoch: 500, Train Loss: 0.686, Val f1_micro: 0.302
f1-micro: 0.302, f1-macro: 0.293, f1-weighted: 0.299, , roc-auc: 0.678
##### RUN 4 #####
Epoch: 020, Train Loss: 1.589, Val f1_micro: 0.235
Epoch: 040, Train Loss: 1.305, Val f1_micro: 0.252
Epoch: 060, Train Loss: 1.186, Val f1_micro: 0.272
Epoch: 080, Train Loss: 1.099, Val f1_micro: 0.270
Epoch: 100, Train Loss: 1.045, Val f1_micro: 0.278
Epoch: 120, Train Loss: 0.985, Val f1_micro: 0.276
Epoch: 140, Train Loss: 0.952, Val f1_micro: 0.280
Epoch: 160, Train Loss: 0.907, Val f1_micro: 0.281
Epoch: 180, Train Loss: 0.881, Val f1_micro: 0.285
Epoch: 200, Train Loss: 0.878, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.841, Val f1_micro: 0.290
Epoch: 240, Train Loss: 0.812, Val f1_micro: 0.293
Epoch: 260, Train Loss: 0.814, Val f1_micro: 0.294
Epoch: 280, Train Loss: 0.793, Val f1_micro: 0.293
Epoch: 300, Train Loss: 0.761, Val f1_micro: 0.294
Epoch: 320, Train Loss: 0.766, Val f1_micro: 0.294
Epoch: 340, Train Loss: 0.753, Val f1_micro: 0.297
Epoch: 360, Train Loss: 0.743, Val f1_micro: 0.298
Epoch: 380, Train Loss: 0.718, Val f1_micro: 0.299
Epoch: 400, Train Loss: 0.721, Val f1_micro: 0.301
Epoch: 420, Train Loss: 0.714, Val f1_micro: 0.299
Epoch: 440, Train Loss: 0.718, Val f1_micro: 0.302
Epoch: 460, Train Loss: 0.698, Val f1_micro: 0.301
Epoch: 480, Train Loss: 0.683, Val f1_micro: 0.305
Epoch: 500, Train Loss: 0.695, Val f1_micro: 0.303
f1-micro: 0.303, f1-macro: 0.293, f1-weighted: 0.298, , roc-auc: 0.681
##### RUN 5 #####
Epoch: 020, Train Loss: 1.582, Val f1_micro: 0.230
Epoch: 040, Train Loss: 1.314, Val f1_micro: 0.247
Epoch: 060, Train Loss: 1.198, Val f1_micro: 0.264
Epoch: 080, Train Loss: 1.098, Val f1_micro: 0.269
Epoch: 100, Train Loss: 1.040, Val f1_micro: 0.276
Epoch: 120, Train Loss: 1.005, Val f1_micro: 0.277
Epoch: 140, Train Loss: 0.966, Val f1_micro: 0.280
Epoch: 160, Train Loss: 0.922, Val f1_micro: 0.281
Epoch: 180, Train Loss: 0.887, Val f1_micro: 0.281
Epoch: 200, Train Loss: 0.853, Val f1_micro: 0.284
Epoch: 220, Train Loss: 0.830, Val f1_micro: 0.287
Epoch: 240, Train Loss: 0.819, Val f1_micro: 0.290
Epoch: 260, Train Loss: 0.796, Val f1_micro: 0.293
Epoch: 280, Train Loss: 0.779, Val f1_micro: 0.292
Epoch: 300, Train Loss: 0.791, Val f1_micro: 0.295
Epoch: 320, Train Loss: 0.769, Val f1_micro: 0.295
Epoch: 340, Train Loss: 0.751, Val f1_micro: 0.295
Epoch: 360, Train Loss: 0.728, Val f1_micro: 0.295
Epoch: 380, Train Loss: 0.728, Val f1_micro: 0.295
Epoch: 400, Train Loss: 0.712, Val f1_micro: 0.298
Epoch: 420, Train Loss: 0.712, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.714, Val f1_micro: 0.300
Epoch: 460, Train Loss: 0.704, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.705, Val f1_micro: 0.302
Epoch: 500, Train Loss: 0.698, Val f1_micro: 0.292
f1-micro: 0.292, f1-macro: 0.284, f1-weighted: 0.289, , roc-auc: 0.677
########## Hyperparameters combination ##########
(512, 0.3, 0.005, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.640, Val f1_micro: 0.227
Epoch: 040, Train Loss: 1.496, Val f1_micro: 0.233
Epoch: 060, Train Loss: 1.484, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.487, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.487, Val f1_micro: 0.237
Epoch: 120, Train Loss: 1.500, Val f1_micro: 0.235
Epoch: 140, Train Loss: 1.505, Val f1_micro: 0.230
Epoch: 160, Train Loss: 1.503, Val f1_micro: 0.232
Epoch: 180, Train Loss: 1.513, Val f1_micro: 0.233
Epoch: 200, Train Loss: 1.516, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.510, Val f1_micro: 0.232
Epoch: 240, Train Loss: 1.520, Val f1_micro: 0.233
Epoch: 260, Train Loss: 1.516, Val f1_micro: 0.228
Epoch: 280, Train Loss: 1.505, Val f1_micro: 0.228
Epoch: 300, Train Loss: 1.515, Val f1_micro: 0.227
Epoch: 320, Train Loss: 1.509, Val f1_micro: 0.231
Epoch: 340, Train Loss: 1.509, Val f1_micro: 0.228
Epoch: 360, Train Loss: 1.516, Val f1_micro: 0.228
Epoch: 380, Train Loss: 1.501, Val f1_micro: 0.230
Epoch: 400, Train Loss: 1.503, Val f1_micro: 0.227
Epoch: 420, Train Loss: 1.495, Val f1_micro: 0.226
Epoch: 440, Train Loss: 1.506, Val f1_micro: 0.221
Epoch: 460, Train Loss: 1.492, Val f1_micro: 0.232
Epoch: 480, Train Loss: 1.504, Val f1_micro: 0.226
Epoch: 500, Train Loss: 1.504, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.199, f1-weighted: 0.198, , roc-auc: 0.645
##### RUN 2 #####
Epoch: 020, Train Loss: 1.639, Val f1_micro: 0.232
Epoch: 040, Train Loss: 1.511, Val f1_micro: 0.232
Epoch: 060, Train Loss: 1.482, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.487, Val f1_micro: 0.240
Epoch: 100, Train Loss: 1.489, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.485, Val f1_micro: 0.232
Epoch: 140, Train Loss: 1.502, Val f1_micro: 0.233
Epoch: 160, Train Loss: 1.506, Val f1_micro: 0.232
Epoch: 180, Train Loss: 1.522, Val f1_micro: 0.233
Epoch: 200, Train Loss: 1.510, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.513, Val f1_micro: 0.228
Epoch: 240, Train Loss: 1.516, Val f1_micro: 0.230
Epoch: 260, Train Loss: 1.515, Val f1_micro: 0.230
Epoch: 280, Train Loss: 1.505, Val f1_micro: 0.226
Epoch: 300, Train Loss: 1.514, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.503, Val f1_micro: 0.228
Epoch: 340, Train Loss: 1.506, Val f1_micro: 0.229
Epoch: 360, Train Loss: 1.506, Val f1_micro: 0.234
Epoch: 380, Train Loss: 1.499, Val f1_micro: 0.232
Epoch: 400, Train Loss: 1.513, Val f1_micro: 0.229
Epoch: 420, Train Loss: 1.484, Val f1_micro: 0.227
Epoch: 440, Train Loss: 1.500, Val f1_micro: 0.231
Epoch: 460, Train Loss: 1.495, Val f1_micro: 0.234
Epoch: 480, Train Loss: 1.497, Val f1_micro: 0.237
Epoch: 500, Train Loss: 1.488, Val f1_micro: 0.233
f1-micro: 0.233, f1-macro: 0.200, f1-weighted: 0.199, , roc-auc: 0.645
##### RUN 3 #####
Epoch: 020, Train Loss: 1.659, Val f1_micro: 0.232
Epoch: 040, Train Loss: 1.505, Val f1_micro: 0.232
Epoch: 060, Train Loss: 1.482, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.489, Val f1_micro: 0.240
Epoch: 100, Train Loss: 1.493, Val f1_micro: 0.237
Epoch: 120, Train Loss: 1.506, Val f1_micro: 0.228
Epoch: 140, Train Loss: 1.519, Val f1_micro: 0.229
Epoch: 160, Train Loss: 1.489, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.515, Val f1_micro: 0.229
Epoch: 200, Train Loss: 1.519, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.512, Val f1_micro: 0.223
Epoch: 240, Train Loss: 1.508, Val f1_micro: 0.223
Epoch: 260, Train Loss: 1.513, Val f1_micro: 0.230
Epoch: 280, Train Loss: 1.522, Val f1_micro: 0.226
Epoch: 300, Train Loss: 1.493, Val f1_micro: 0.229
Epoch: 320, Train Loss: 1.520, Val f1_micro: 0.225
Epoch: 340, Train Loss: 1.506, Val f1_micro: 0.224
Epoch: 360, Train Loss: 1.503, Val f1_micro: 0.229
Epoch: 380, Train Loss: 1.508, Val f1_micro: 0.228
Epoch: 400, Train Loss: 1.514, Val f1_micro: 0.230
Epoch: 420, Train Loss: 1.502, Val f1_micro: 0.232
Epoch: 440, Train Loss: 1.497, Val f1_micro: 0.229
Epoch: 460, Train Loss: 1.496, Val f1_micro: 0.227
Epoch: 480, Train Loss: 1.492, Val f1_micro: 0.230
Epoch: 500, Train Loss: 1.502, Val f1_micro: 0.225
f1-micro: 0.225, f1-macro: 0.194, f1-weighted: 0.192, , roc-auc: 0.647
##### RUN 4 #####
Epoch: 020, Train Loss: 1.646, Val f1_micro: 0.232
Epoch: 040, Train Loss: 1.520, Val f1_micro: 0.234
Epoch: 060, Train Loss: 1.484, Val f1_micro: 0.234
Epoch: 080, Train Loss: 1.480, Val f1_micro: 0.237
Epoch: 100, Train Loss: 1.495, Val f1_micro: 0.227
Epoch: 120, Train Loss: 1.502, Val f1_micro: 0.233
Epoch: 140, Train Loss: 1.504, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.509, Val f1_micro: 0.232
Epoch: 180, Train Loss: 1.518, Val f1_micro: 0.224
Epoch: 200, Train Loss: 1.511, Val f1_micro: 0.228
Epoch: 220, Train Loss: 1.511, Val f1_micro: 0.229
Epoch: 240, Train Loss: 1.500, Val f1_micro: 0.229
Epoch: 260, Train Loss: 1.516, Val f1_micro: 0.227
Epoch: 280, Train Loss: 1.517, Val f1_micro: 0.231
Epoch: 300, Train Loss: 1.512, Val f1_micro: 0.228
Epoch: 320, Train Loss: 1.500, Val f1_micro: 0.227
Epoch: 340, Train Loss: 1.498, Val f1_micro: 0.228
Epoch: 360, Train Loss: 1.505, Val f1_micro: 0.225
Epoch: 380, Train Loss: 1.499, Val f1_micro: 0.224
Epoch: 400, Train Loss: 1.495, Val f1_micro: 0.230
Epoch: 420, Train Loss: 1.503, Val f1_micro: 0.229
Epoch: 440, Train Loss: 1.497, Val f1_micro: 0.233
Epoch: 460, Train Loss: 1.500, Val f1_micro: 0.228
Epoch: 480, Train Loss: 1.493, Val f1_micro: 0.229
Epoch: 500, Train Loss: 1.491, Val f1_micro: 0.229
f1-micro: 0.229, f1-macro: 0.199, f1-weighted: 0.198, , roc-auc: 0.644
##### RUN 5 #####
Epoch: 020, Train Loss: 1.655, Val f1_micro: 0.225
Epoch: 040, Train Loss: 1.507, Val f1_micro: 0.230
Epoch: 060, Train Loss: 1.484, Val f1_micro: 0.235
Epoch: 080, Train Loss: 1.485, Val f1_micro: 0.235
Epoch: 100, Train Loss: 1.491, Val f1_micro: 0.236
Epoch: 120, Train Loss: 1.500, Val f1_micro: 0.235
Epoch: 140, Train Loss: 1.504, Val f1_micro: 0.233
Epoch: 160, Train Loss: 1.510, Val f1_micro: 0.228
Epoch: 180, Train Loss: 1.507, Val f1_micro: 0.228
Epoch: 200, Train Loss: 1.516, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.509, Val f1_micro: 0.229
Epoch: 240, Train Loss: 1.515, Val f1_micro: 0.232
Epoch: 260, Train Loss: 1.522, Val f1_micro: 0.230
Epoch: 280, Train Loss: 1.498, Val f1_micro: 0.233
Epoch: 300, Train Loss: 1.509, Val f1_micro: 0.233
Epoch: 320, Train Loss: 1.516, Val f1_micro: 0.223
Epoch: 340, Train Loss: 1.511, Val f1_micro: 0.226
Epoch: 360, Train Loss: 1.490, Val f1_micro: 0.230
Epoch: 380, Train Loss: 1.499, Val f1_micro: 0.234
Epoch: 400, Train Loss: 1.496, Val f1_micro: 0.234
Epoch: 420, Train Loss: 1.494, Val f1_micro: 0.226
Epoch: 440, Train Loss: 1.506, Val f1_micro: 0.233
Epoch: 460, Train Loss: 1.501, Val f1_micro: 0.230
Epoch: 480, Train Loss: 1.495, Val f1_micro: 0.221
Epoch: 500, Train Loss: 1.495, Val f1_micro: 0.233
f1-micro: 0.233, f1-macro: 0.202, f1-weighted: 0.202, , roc-auc: 0.645
########## Hyperparameters combination ##########
(512, 0.3, 0.01, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.510, Val f1_micro: 0.230
Epoch: 040, Train Loss: 1.180, Val f1_micro: 0.268
Epoch: 060, Train Loss: 0.983, Val f1_micro: 0.284
Epoch: 080, Train Loss: 0.835, Val f1_micro: 0.293
Epoch: 100, Train Loss: 0.723, Val f1_micro: 0.299
Epoch: 120, Train Loss: 0.642, Val f1_micro: 0.305
Epoch: 140, Train Loss: 0.563, Val f1_micro: 0.308
Epoch: 160, Train Loss: 0.502, Val f1_micro: 0.312
Epoch: 180, Train Loss: 0.429, Val f1_micro: 0.317
Epoch: 200, Train Loss: 0.392, Val f1_micro: 0.316
Epoch: 220, Train Loss: 0.360, Val f1_micro: 0.322
Epoch: 240, Train Loss: 0.338, Val f1_micro: 0.322
Epoch: 260, Train Loss: 0.303, Val f1_micro: 0.322
Epoch: 280, Train Loss: 0.298, Val f1_micro: 0.326
Epoch: 300, Train Loss: 0.278, Val f1_micro: 0.322
Epoch: 320, Train Loss: 0.237, Val f1_micro: 0.323
Epoch: 340, Train Loss: 0.228, Val f1_micro: 0.324
Epoch: 360, Train Loss: 0.231, Val f1_micro: 0.322
Epoch: 380, Train Loss: 0.222, Val f1_micro: 0.324
Epoch: 400, Train Loss: 0.211, Val f1_micro: 0.325
Epoch: 420, Train Loss: 0.196, Val f1_micro: 0.326
Epoch: 440, Train Loss: 0.185, Val f1_micro: 0.324
Epoch: 460, Train Loss: 0.196, Val f1_micro: 0.322
Epoch: 480, Train Loss: 0.174, Val f1_micro: 0.323
Epoch: 500, Train Loss: 0.173, Val f1_micro: 0.324
f1-micro: 0.324, f1-macro: 0.318, f1-weighted: 0.323, , roc-auc: 0.692
##### RUN 2 #####
Epoch: 020, Train Loss: 1.495, Val f1_micro: 0.221
Epoch: 040, Train Loss: 1.158, Val f1_micro: 0.266
Epoch: 060, Train Loss: 0.957, Val f1_micro: 0.285
Epoch: 080, Train Loss: 0.842, Val f1_micro: 0.289
Epoch: 100, Train Loss: 0.723, Val f1_micro: 0.299
Epoch: 120, Train Loss: 0.632, Val f1_micro: 0.307
Epoch: 140, Train Loss: 0.552, Val f1_micro: 0.310
Epoch: 160, Train Loss: 0.484, Val f1_micro: 0.314
Epoch: 180, Train Loss: 0.435, Val f1_micro: 0.318
Epoch: 200, Train Loss: 0.387, Val f1_micro: 0.318
Epoch: 220, Train Loss: 0.347, Val f1_micro: 0.320
Epoch: 240, Train Loss: 0.326, Val f1_micro: 0.321
Epoch: 260, Train Loss: 0.305, Val f1_micro: 0.321
Epoch: 280, Train Loss: 0.278, Val f1_micro: 0.325
Epoch: 300, Train Loss: 0.253, Val f1_micro: 0.324
Epoch: 320, Train Loss: 0.244, Val f1_micro: 0.324
Epoch: 340, Train Loss: 0.233, Val f1_micro: 0.324
Epoch: 360, Train Loss: 0.227, Val f1_micro: 0.326
Epoch: 380, Train Loss: 0.232, Val f1_micro: 0.320
Epoch: 400, Train Loss: 0.217, Val f1_micro: 0.322
Epoch: 420, Train Loss: 0.191, Val f1_micro: 0.327
Epoch: 440, Train Loss: 0.200, Val f1_micro: 0.327
Epoch: 460, Train Loss: 0.199, Val f1_micro: 0.325
Epoch: 480, Train Loss: 0.181, Val f1_micro: 0.325
Epoch: 500, Train Loss: 0.172, Val f1_micro: 0.327
f1-micro: 0.327, f1-macro: 0.320, f1-weighted: 0.326, , roc-auc: 0.693
##### RUN 3 #####
Epoch: 020, Train Loss: 1.511, Val f1_micro: 0.230
Epoch: 040, Train Loss: 1.163, Val f1_micro: 0.268
Epoch: 060, Train Loss: 0.960, Val f1_micro: 0.282
Epoch: 080, Train Loss: 0.833, Val f1_micro: 0.287
Epoch: 100, Train Loss: 0.713, Val f1_micro: 0.299
Epoch: 120, Train Loss: 0.627, Val f1_micro: 0.301
Epoch: 140, Train Loss: 0.558, Val f1_micro: 0.309
Epoch: 160, Train Loss: 0.472, Val f1_micro: 0.310
Epoch: 180, Train Loss: 0.429, Val f1_micro: 0.313
Epoch: 200, Train Loss: 0.397, Val f1_micro: 0.316
Epoch: 220, Train Loss: 0.368, Val f1_micro: 0.318
Epoch: 240, Train Loss: 0.325, Val f1_micro: 0.321
Epoch: 260, Train Loss: 0.305, Val f1_micro: 0.321
Epoch: 280, Train Loss: 0.280, Val f1_micro: 0.322
Epoch: 300, Train Loss: 0.262, Val f1_micro: 0.323
Epoch: 320, Train Loss: 0.241, Val f1_micro: 0.326
Epoch: 340, Train Loss: 0.232, Val f1_micro: 0.324
Epoch: 360, Train Loss: 0.213, Val f1_micro: 0.322
Epoch: 380, Train Loss: 0.203, Val f1_micro: 0.324
Epoch: 400, Train Loss: 0.204, Val f1_micro: 0.323
Epoch: 420, Train Loss: 0.197, Val f1_micro: 0.322
Epoch: 440, Train Loss: 0.197, Val f1_micro: 0.321
Epoch: 460, Train Loss: 0.172, Val f1_micro: 0.325
Epoch: 480, Train Loss: 0.173, Val f1_micro: 0.325
Epoch: 500, Train Loss: 0.168, Val f1_micro: 0.323
f1-micro: 0.323, f1-macro: 0.317, f1-weighted: 0.323, , roc-auc: 0.694
##### RUN 4 #####
Epoch: 020, Train Loss: 1.505, Val f1_micro: 0.228
Epoch: 040, Train Loss: 1.167, Val f1_micro: 0.269
Epoch: 060, Train Loss: 0.977, Val f1_micro: 0.282
Epoch: 080, Train Loss: 0.848, Val f1_micro: 0.288
Epoch: 100, Train Loss: 0.732, Val f1_micro: 0.299
Epoch: 120, Train Loss: 0.626, Val f1_micro: 0.306
Epoch: 140, Train Loss: 0.570, Val f1_micro: 0.307
Epoch: 160, Train Loss: 0.499, Val f1_micro: 0.311
Epoch: 180, Train Loss: 0.450, Val f1_micro: 0.316
Epoch: 200, Train Loss: 0.384, Val f1_micro: 0.318
Epoch: 220, Train Loss: 0.346, Val f1_micro: 0.321
Epoch: 240, Train Loss: 0.329, Val f1_micro: 0.321
Epoch: 260, Train Loss: 0.304, Val f1_micro: 0.323
Epoch: 280, Train Loss: 0.289, Val f1_micro: 0.322
Epoch: 300, Train Loss: 0.271, Val f1_micro: 0.326
Epoch: 320, Train Loss: 0.270, Val f1_micro: 0.323
Epoch: 340, Train Loss: 0.228, Val f1_micro: 0.327
Epoch: 360, Train Loss: 0.217, Val f1_micro: 0.325
Epoch: 380, Train Loss: 0.233, Val f1_micro: 0.325
Epoch: 400, Train Loss: 0.202, Val f1_micro: 0.328
Epoch: 420, Train Loss: 0.201, Val f1_micro: 0.325
Epoch: 440, Train Loss: 0.187, Val f1_micro: 0.324
Epoch: 460, Train Loss: 0.180, Val f1_micro: 0.324
Epoch: 480, Train Loss: 0.179, Val f1_micro: 0.323
Epoch: 500, Train Loss: 0.184, Val f1_micro: 0.325
f1-micro: 0.325, f1-macro: 0.319, f1-weighted: 0.324, , roc-auc: 0.694
##### RUN 5 #####
Epoch: 020, Train Loss: 1.484, Val f1_micro: 0.231
Epoch: 040, Train Loss: 1.153, Val f1_micro: 0.272
Epoch: 060, Train Loss: 0.957, Val f1_micro: 0.279
Epoch: 080, Train Loss: 0.836, Val f1_micro: 0.290
Epoch: 100, Train Loss: 0.714, Val f1_micro: 0.300
Epoch: 120, Train Loss: 0.627, Val f1_micro: 0.305
Epoch: 140, Train Loss: 0.551, Val f1_micro: 0.307
Epoch: 160, Train Loss: 0.474, Val f1_micro: 0.314
Epoch: 180, Train Loss: 0.410, Val f1_micro: 0.319
Epoch: 200, Train Loss: 0.378, Val f1_micro: 0.318
Epoch: 220, Train Loss: 0.351, Val f1_micro: 0.321
Epoch: 240, Train Loss: 0.315, Val f1_micro: 0.322
Epoch: 260, Train Loss: 0.295, Val f1_micro: 0.322
Epoch: 280, Train Loss: 0.274, Val f1_micro: 0.327
Epoch: 300, Train Loss: 0.262, Val f1_micro: 0.326
Epoch: 320, Train Loss: 0.259, Val f1_micro: 0.324
Epoch: 340, Train Loss: 0.242, Val f1_micro: 0.327
Epoch: 360, Train Loss: 0.233, Val f1_micro: 0.326
Epoch: 380, Train Loss: 0.216, Val f1_micro: 0.326
Epoch: 400, Train Loss: 0.211, Val f1_micro: 0.327
Epoch: 420, Train Loss: 0.199, Val f1_micro: 0.324
Epoch: 440, Train Loss: 0.184, Val f1_micro: 0.325
Epoch: 460, Train Loss: 0.179, Val f1_micro: 0.326
Epoch: 480, Train Loss: 0.167, Val f1_micro: 0.327
Epoch: 500, Train Loss: 0.186, Val f1_micro: 0.324
f1-micro: 0.324, f1-macro: 0.318, f1-weighted: 0.324, , roc-auc: 0.692
########## Hyperparameters combination ##########
(512, 0.3, 0.01, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.487, Val f1_micro: 0.230
Epoch: 040, Train Loss: 1.197, Val f1_micro: 0.267
Epoch: 060, Train Loss: 1.057, Val f1_micro: 0.275
Epoch: 080, Train Loss: 0.943, Val f1_micro: 0.277
Epoch: 100, Train Loss: 0.858, Val f1_micro: 0.288
Epoch: 120, Train Loss: 0.793, Val f1_micro: 0.289
Epoch: 140, Train Loss: 0.756, Val f1_micro: 0.293
Epoch: 160, Train Loss: 0.700, Val f1_micro: 0.294
Epoch: 180, Train Loss: 0.668, Val f1_micro: 0.300
Epoch: 200, Train Loss: 0.651, Val f1_micro: 0.299
Epoch: 220, Train Loss: 0.595, Val f1_micro: 0.301
Epoch: 240, Train Loss: 0.584, Val f1_micro: 0.302
Epoch: 260, Train Loss: 0.550, Val f1_micro: 0.306
Epoch: 280, Train Loss: 0.539, Val f1_micro: 0.308
Epoch: 300, Train Loss: 0.542, Val f1_micro: 0.307
Epoch: 320, Train Loss: 0.519, Val f1_micro: 0.313
Epoch: 340, Train Loss: 0.491, Val f1_micro: 0.310
Epoch: 360, Train Loss: 0.489, Val f1_micro: 0.313
Epoch: 380, Train Loss: 0.478, Val f1_micro: 0.308
Epoch: 400, Train Loss: 0.454, Val f1_micro: 0.310
Epoch: 420, Train Loss: 0.452, Val f1_micro: 0.314
Epoch: 440, Train Loss: 0.454, Val f1_micro: 0.311
Epoch: 460, Train Loss: 0.454, Val f1_micro: 0.313
Epoch: 480, Train Loss: 0.416, Val f1_micro: 0.314
Epoch: 500, Train Loss: 0.440, Val f1_micro: 0.313
f1-micro: 0.313, f1-macro: 0.307, f1-weighted: 0.312, , roc-auc: 0.685
##### RUN 2 #####
Epoch: 020, Train Loss: 1.496, Val f1_micro: 0.231
Epoch: 040, Train Loss: 1.189, Val f1_micro: 0.264
Epoch: 060, Train Loss: 1.034, Val f1_micro: 0.275
Epoch: 080, Train Loss: 0.957, Val f1_micro: 0.282
Epoch: 100, Train Loss: 0.866, Val f1_micro: 0.288
Epoch: 120, Train Loss: 0.791, Val f1_micro: 0.290
Epoch: 140, Train Loss: 0.745, Val f1_micro: 0.295
Epoch: 160, Train Loss: 0.708, Val f1_micro: 0.296
Epoch: 180, Train Loss: 0.665, Val f1_micro: 0.297
Epoch: 200, Train Loss: 0.638, Val f1_micro: 0.299
Epoch: 220, Train Loss: 0.607, Val f1_micro: 0.302
Epoch: 240, Train Loss: 0.604, Val f1_micro: 0.304
Epoch: 260, Train Loss: 0.554, Val f1_micro: 0.305
Epoch: 280, Train Loss: 0.556, Val f1_micro: 0.309
Epoch: 300, Train Loss: 0.539, Val f1_micro: 0.306
Epoch: 320, Train Loss: 0.516, Val f1_micro: 0.307
Epoch: 340, Train Loss: 0.490, Val f1_micro: 0.312
Epoch: 360, Train Loss: 0.473, Val f1_micro: 0.311
Epoch: 380, Train Loss: 0.477, Val f1_micro: 0.309
Epoch: 400, Train Loss: 0.466, Val f1_micro: 0.308
Epoch: 420, Train Loss: 0.453, Val f1_micro: 0.314
Epoch: 440, Train Loss: 0.438, Val f1_micro: 0.313
Epoch: 460, Train Loss: 0.429, Val f1_micro: 0.314
Epoch: 480, Train Loss: 0.439, Val f1_micro: 0.313
Epoch: 500, Train Loss: 0.438, Val f1_micro: 0.312
f1-micro: 0.312, f1-macro: 0.304, f1-weighted: 0.310, , roc-auc: 0.682
##### RUN 3 #####
Epoch: 020, Train Loss: 1.485, Val f1_micro: 0.227
Epoch: 040, Train Loss: 1.165, Val f1_micro: 0.266
Epoch: 060, Train Loss: 1.029, Val f1_micro: 0.275
Epoch: 080, Train Loss: 0.943, Val f1_micro: 0.280
Epoch: 100, Train Loss: 0.864, Val f1_micro: 0.286
Epoch: 120, Train Loss: 0.800, Val f1_micro: 0.286
Epoch: 140, Train Loss: 0.748, Val f1_micro: 0.294
Epoch: 160, Train Loss: 0.703, Val f1_micro: 0.297
Epoch: 180, Train Loss: 0.677, Val f1_micro: 0.299
Epoch: 200, Train Loss: 0.634, Val f1_micro: 0.303
Epoch: 220, Train Loss: 0.619, Val f1_micro: 0.304
Epoch: 240, Train Loss: 0.592, Val f1_micro: 0.309
Epoch: 260, Train Loss: 0.565, Val f1_micro: 0.307
Epoch: 280, Train Loss: 0.532, Val f1_micro: 0.307
Epoch: 300, Train Loss: 0.525, Val f1_micro: 0.308
Epoch: 320, Train Loss: 0.523, Val f1_micro: 0.309
Epoch: 340, Train Loss: 0.508, Val f1_micro: 0.310
Epoch: 360, Train Loss: 0.493, Val f1_micro: 0.312
Epoch: 380, Train Loss: 0.472, Val f1_micro: 0.313
Epoch: 400, Train Loss: 0.462, Val f1_micro: 0.315
Epoch: 420, Train Loss: 0.448, Val f1_micro: 0.313
Epoch: 440, Train Loss: 0.434, Val f1_micro: 0.316
Epoch: 460, Train Loss: 0.436, Val f1_micro: 0.311
Epoch: 480, Train Loss: 0.437, Val f1_micro: 0.314
Epoch: 500, Train Loss: 0.410, Val f1_micro: 0.313
f1-micro: 0.313, f1-macro: 0.309, f1-weighted: 0.314, , roc-auc: 0.684
##### RUN 4 #####
Epoch: 020, Train Loss: 1.501, Val f1_micro: 0.228
Epoch: 040, Train Loss: 1.192, Val f1_micro: 0.266
Epoch: 060, Train Loss: 1.057, Val f1_micro: 0.276
Epoch: 080, Train Loss: 0.940, Val f1_micro: 0.278
Epoch: 100, Train Loss: 0.857, Val f1_micro: 0.286
Epoch: 120, Train Loss: 0.788, Val f1_micro: 0.287
Epoch: 140, Train Loss: 0.752, Val f1_micro: 0.291
Epoch: 160, Train Loss: 0.698, Val f1_micro: 0.295
Epoch: 180, Train Loss: 0.662, Val f1_micro: 0.299
Epoch: 200, Train Loss: 0.633, Val f1_micro: 0.301
Epoch: 220, Train Loss: 0.604, Val f1_micro: 0.304
Epoch: 240, Train Loss: 0.593, Val f1_micro: 0.307
Epoch: 260, Train Loss: 0.580, Val f1_micro: 0.304
Epoch: 280, Train Loss: 0.538, Val f1_micro: 0.308
Epoch: 300, Train Loss: 0.546, Val f1_micro: 0.305
Epoch: 320, Train Loss: 0.505, Val f1_micro: 0.308
Epoch: 340, Train Loss: 0.512, Val f1_micro: 0.304
Epoch: 360, Train Loss: 0.496, Val f1_micro: 0.312
Epoch: 380, Train Loss: 0.480, Val f1_micro: 0.313
Epoch: 400, Train Loss: 0.470, Val f1_micro: 0.313
Epoch: 420, Train Loss: 0.457, Val f1_micro: 0.312
Epoch: 440, Train Loss: 0.451, Val f1_micro: 0.310
Epoch: 460, Train Loss: 0.447, Val f1_micro: 0.314
Epoch: 480, Train Loss: 0.439, Val f1_micro: 0.315
Epoch: 500, Train Loss: 0.434, Val f1_micro: 0.314
f1-micro: 0.314, f1-macro: 0.307, f1-weighted: 0.313, , roc-auc: 0.682
##### RUN 5 #####
Epoch: 020, Train Loss: 1.481, Val f1_micro: 0.230
Epoch: 040, Train Loss: 1.168, Val f1_micro: 0.263
Epoch: 060, Train Loss: 1.020, Val f1_micro: 0.278
Epoch: 080, Train Loss: 0.931, Val f1_micro: 0.281
Epoch: 100, Train Loss: 0.860, Val f1_micro: 0.288
Epoch: 120, Train Loss: 0.797, Val f1_micro: 0.293
Epoch: 140, Train Loss: 0.746, Val f1_micro: 0.290
Epoch: 160, Train Loss: 0.694, Val f1_micro: 0.301
Epoch: 180, Train Loss: 0.668, Val f1_micro: 0.300
Epoch: 200, Train Loss: 0.633, Val f1_micro: 0.306
Epoch: 220, Train Loss: 0.610, Val f1_micro: 0.305
Epoch: 240, Train Loss: 0.575, Val f1_micro: 0.306
Epoch: 260, Train Loss: 0.566, Val f1_micro: 0.310
Epoch: 280, Train Loss: 0.539, Val f1_micro: 0.311
Epoch: 300, Train Loss: 0.511, Val f1_micro: 0.315
Epoch: 320, Train Loss: 0.509, Val f1_micro: 0.315
Epoch: 340, Train Loss: 0.488, Val f1_micro: 0.313
Epoch: 360, Train Loss: 0.473, Val f1_micro: 0.315
Epoch: 380, Train Loss: 0.472, Val f1_micro: 0.319
Epoch: 400, Train Loss: 0.460, Val f1_micro: 0.315
Epoch: 420, Train Loss: 0.454, Val f1_micro: 0.315
Epoch: 440, Train Loss: 0.436, Val f1_micro: 0.316
Epoch: 460, Train Loss: 0.442, Val f1_micro: 0.315
Epoch: 480, Train Loss: 0.431, Val f1_micro: 0.315
Epoch: 500, Train Loss: 0.437, Val f1_micro: 0.316
f1-micro: 0.316, f1-macro: 0.310, f1-weighted: 0.316, , roc-auc: 0.685
########## Hyperparameters combination ##########
(512, 0.3, 0.01, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.541, Val f1_micro: 0.235
Epoch: 040, Train Loss: 1.267, Val f1_micro: 0.265
Epoch: 060, Train Loss: 1.136, Val f1_micro: 0.273
Epoch: 080, Train Loss: 1.047, Val f1_micro: 0.278
Epoch: 100, Train Loss: 0.994, Val f1_micro: 0.279
Epoch: 120, Train Loss: 0.955, Val f1_micro: 0.280
Epoch: 140, Train Loss: 0.885, Val f1_micro: 0.283
Epoch: 160, Train Loss: 0.868, Val f1_micro: 0.287
Epoch: 180, Train Loss: 0.834, Val f1_micro: 0.288
Epoch: 200, Train Loss: 0.803, Val f1_micro: 0.291
Epoch: 220, Train Loss: 0.790, Val f1_micro: 0.290
Epoch: 240, Train Loss: 0.766, Val f1_micro: 0.290
Epoch: 260, Train Loss: 0.748, Val f1_micro: 0.293
Epoch: 280, Train Loss: 0.737, Val f1_micro: 0.293
Epoch: 300, Train Loss: 0.729, Val f1_micro: 0.296
Epoch: 320, Train Loss: 0.718, Val f1_micro: 0.299
Epoch: 340, Train Loss: 0.707, Val f1_micro: 0.288
Epoch: 360, Train Loss: 0.690, Val f1_micro: 0.298
Epoch: 380, Train Loss: 0.692, Val f1_micro: 0.299
Epoch: 400, Train Loss: 0.689, Val f1_micro: 0.298
Epoch: 420, Train Loss: 0.682, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.685, Val f1_micro: 0.295
Epoch: 460, Train Loss: 0.671, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.674, Val f1_micro: 0.297
Epoch: 500, Train Loss: 0.654, Val f1_micro: 0.298
f1-micro: 0.298, f1-macro: 0.290, f1-weighted: 0.293, , roc-auc: 0.674
##### RUN 2 #####
Epoch: 020, Train Loss: 1.522, Val f1_micro: 0.234
Epoch: 040, Train Loss: 1.256, Val f1_micro: 0.267
Epoch: 060, Train Loss: 1.124, Val f1_micro: 0.272
Epoch: 080, Train Loss: 1.056, Val f1_micro: 0.275
Epoch: 100, Train Loss: 0.992, Val f1_micro: 0.282
Epoch: 120, Train Loss: 0.951, Val f1_micro: 0.283
Epoch: 140, Train Loss: 0.907, Val f1_micro: 0.285
Epoch: 160, Train Loss: 0.861, Val f1_micro: 0.283
Epoch: 180, Train Loss: 0.832, Val f1_micro: 0.289
Epoch: 200, Train Loss: 0.827, Val f1_micro: 0.289
Epoch: 220, Train Loss: 0.784, Val f1_micro: 0.291
Epoch: 240, Train Loss: 0.775, Val f1_micro: 0.291
Epoch: 260, Train Loss: 0.771, Val f1_micro: 0.291
Epoch: 280, Train Loss: 0.748, Val f1_micro: 0.295
Epoch: 300, Train Loss: 0.721, Val f1_micro: 0.295
Epoch: 320, Train Loss: 0.733, Val f1_micro: 0.296
Epoch: 340, Train Loss: 0.693, Val f1_micro: 0.295
Epoch: 360, Train Loss: 0.700, Val f1_micro: 0.299
Epoch: 380, Train Loss: 0.685, Val f1_micro: 0.295
Epoch: 400, Train Loss: 0.706, Val f1_micro: 0.295
Epoch: 420, Train Loss: 0.674, Val f1_micro: 0.297
Epoch: 440, Train Loss: 0.669, Val f1_micro: 0.297
Epoch: 460, Train Loss: 0.671, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.661, Val f1_micro: 0.297
Epoch: 500, Train Loss: 0.661, Val f1_micro: 0.298
f1-micro: 0.298, f1-macro: 0.291, f1-weighted: 0.295, , roc-auc: 0.673
##### RUN 3 #####
Epoch: 020, Train Loss: 1.513, Val f1_micro: 0.236
Epoch: 040, Train Loss: 1.271, Val f1_micro: 0.262
Epoch: 060, Train Loss: 1.131, Val f1_micro: 0.268
Epoch: 080, Train Loss: 1.056, Val f1_micro: 0.275
Epoch: 100, Train Loss: 0.984, Val f1_micro: 0.276
Epoch: 120, Train Loss: 0.938, Val f1_micro: 0.279
Epoch: 140, Train Loss: 0.883, Val f1_micro: 0.285
Epoch: 160, Train Loss: 0.861, Val f1_micro: 0.286
Epoch: 180, Train Loss: 0.819, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.812, Val f1_micro: 0.289
Epoch: 220, Train Loss: 0.773, Val f1_micro: 0.289
Epoch: 240, Train Loss: 0.766, Val f1_micro: 0.293
Epoch: 260, Train Loss: 0.750, Val f1_micro: 0.298
Epoch: 280, Train Loss: 0.741, Val f1_micro: 0.293
Epoch: 300, Train Loss: 0.741, Val f1_micro: 0.297
Epoch: 320, Train Loss: 0.728, Val f1_micro: 0.298
Epoch: 340, Train Loss: 0.711, Val f1_micro: 0.300
Epoch: 360, Train Loss: 0.696, Val f1_micro: 0.300
Epoch: 380, Train Loss: 0.683, Val f1_micro: 0.299
Epoch: 400, Train Loss: 0.664, Val f1_micro: 0.299
Epoch: 420, Train Loss: 0.679, Val f1_micro: 0.301
Epoch: 440, Train Loss: 0.677, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.660, Val f1_micro: 0.299
Epoch: 480, Train Loss: 0.655, Val f1_micro: 0.302
Epoch: 500, Train Loss: 0.676, Val f1_micro: 0.302
f1-micro: 0.302, f1-macro: 0.295, f1-weighted: 0.299, , roc-auc: 0.674
##### RUN 4 #####
Epoch: 020, Train Loss: 1.518, Val f1_micro: 0.236
Epoch: 040, Train Loss: 1.252, Val f1_micro: 0.267
Epoch: 060, Train Loss: 1.153, Val f1_micro: 0.268
Epoch: 080, Train Loss: 1.051, Val f1_micro: 0.275
Epoch: 100, Train Loss: 0.984, Val f1_micro: 0.280
Epoch: 120, Train Loss: 0.924, Val f1_micro: 0.280
Epoch: 140, Train Loss: 0.898, Val f1_micro: 0.284
Epoch: 160, Train Loss: 0.877, Val f1_micro: 0.289
Epoch: 180, Train Loss: 0.825, Val f1_micro: 0.288
Epoch: 200, Train Loss: 0.800, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.776, Val f1_micro: 0.291
Epoch: 240, Train Loss: 0.776, Val f1_micro: 0.295
Epoch: 260, Train Loss: 0.750, Val f1_micro: 0.290
Epoch: 280, Train Loss: 0.754, Val f1_micro: 0.294
Epoch: 300, Train Loss: 0.731, Val f1_micro: 0.295
Epoch: 320, Train Loss: 0.730, Val f1_micro: 0.297
Epoch: 340, Train Loss: 0.718, Val f1_micro: 0.295
Epoch: 360, Train Loss: 0.703, Val f1_micro: 0.295
Epoch: 380, Train Loss: 0.707, Val f1_micro: 0.298
Epoch: 400, Train Loss: 0.698, Val f1_micro: 0.300
Epoch: 420, Train Loss: 0.679, Val f1_micro: 0.300
Epoch: 440, Train Loss: 0.676, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.680, Val f1_micro: 0.294
Epoch: 480, Train Loss: 0.663, Val f1_micro: 0.295
Epoch: 500, Train Loss: 0.681, Val f1_micro: 0.300
f1-micro: 0.300, f1-macro: 0.293, f1-weighted: 0.297, , roc-auc: 0.673
##### RUN 5 #####
Epoch: 020, Train Loss: 1.543, Val f1_micro: 0.229
Epoch: 040, Train Loss: 1.260, Val f1_micro: 0.267
Epoch: 060, Train Loss: 1.150, Val f1_micro: 0.272
Epoch: 080, Train Loss: 1.052, Val f1_micro: 0.276
Epoch: 100, Train Loss: 0.995, Val f1_micro: 0.277
Epoch: 120, Train Loss: 0.948, Val f1_micro: 0.281
Epoch: 140, Train Loss: 0.888, Val f1_micro: 0.280
Epoch: 160, Train Loss: 0.870, Val f1_micro: 0.285
Epoch: 180, Train Loss: 0.836, Val f1_micro: 0.285
Epoch: 200, Train Loss: 0.816, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.804, Val f1_micro: 0.289
Epoch: 240, Train Loss: 0.771, Val f1_micro: 0.291
Epoch: 260, Train Loss: 0.770, Val f1_micro: 0.293
Epoch: 280, Train Loss: 0.755, Val f1_micro: 0.292
Epoch: 300, Train Loss: 0.735, Val f1_micro: 0.289
Epoch: 320, Train Loss: 0.741, Val f1_micro: 0.298
Epoch: 340, Train Loss: 0.722, Val f1_micro: 0.295
Epoch: 360, Train Loss: 0.717, Val f1_micro: 0.298
Epoch: 380, Train Loss: 0.706, Val f1_micro: 0.297
Epoch: 400, Train Loss: 0.686, Val f1_micro: 0.300
Epoch: 420, Train Loss: 0.691, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.681, Val f1_micro: 0.297
Epoch: 460, Train Loss: 0.665, Val f1_micro: 0.295
Epoch: 480, Train Loss: 0.669, Val f1_micro: 0.297
Epoch: 500, Train Loss: 0.665, Val f1_micro: 0.299
f1-micro: 0.299, f1-macro: 0.292, f1-weighted: 0.296, , roc-auc: 0.672
########## Hyperparameters combination ##########
(512, 0.3, 0.01, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.663, Val f1_micro: 0.222
Epoch: 040, Train Loss: 1.546, Val f1_micro: 0.240
Epoch: 060, Train Loss: 1.517, Val f1_micro: 0.242
Epoch: 080, Train Loss: 1.526, Val f1_micro: 0.239
Epoch: 100, Train Loss: 1.532, Val f1_micro: 0.237
Epoch: 120, Train Loss: 1.525, Val f1_micro: 0.234
Epoch: 140, Train Loss: 1.530, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.528, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.530, Val f1_micro: 0.233
Epoch: 200, Train Loss: 1.523, Val f1_micro: 0.234
Epoch: 220, Train Loss: 1.527, Val f1_micro: 0.230
Epoch: 240, Train Loss: 1.529, Val f1_micro: 0.228
Epoch: 260, Train Loss: 1.518, Val f1_micro: 0.231
Epoch: 280, Train Loss: 1.506, Val f1_micro: 0.231
Epoch: 300, Train Loss: 1.506, Val f1_micro: 0.228
Epoch: 320, Train Loss: 1.520, Val f1_micro: 0.228
Epoch: 340, Train Loss: 1.513, Val f1_micro: 0.235
Epoch: 360, Train Loss: 1.520, Val f1_micro: 0.237
Epoch: 380, Train Loss: 1.513, Val f1_micro: 0.234
Epoch: 400, Train Loss: 1.520, Val f1_micro: 0.233
Epoch: 420, Train Loss: 1.509, Val f1_micro: 0.235
Epoch: 440, Train Loss: 1.499, Val f1_micro: 0.237
Epoch: 460, Train Loss: 1.501, Val f1_micro: 0.239
Epoch: 480, Train Loss: 1.501, Val f1_micro: 0.238
Epoch: 500, Train Loss: 1.493, Val f1_micro: 0.240
f1-micro: 0.240, f1-macro: 0.203, f1-weighted: 0.204, , roc-auc: 0.648
##### RUN 2 #####
Epoch: 020, Train Loss: 1.646, Val f1_micro: 0.226
Epoch: 040, Train Loss: 1.533, Val f1_micro: 0.246
Epoch: 060, Train Loss: 1.516, Val f1_micro: 0.238
Epoch: 080, Train Loss: 1.515, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.525, Val f1_micro: 0.238
Epoch: 120, Train Loss: 1.525, Val f1_micro: 0.230
Epoch: 140, Train Loss: 1.530, Val f1_micro: 0.235
Epoch: 160, Train Loss: 1.532, Val f1_micro: 0.233
Epoch: 180, Train Loss: 1.527, Val f1_micro: 0.236
Epoch: 200, Train Loss: 1.522, Val f1_micro: 0.237
Epoch: 220, Train Loss: 1.519, Val f1_micro: 0.228
Epoch: 240, Train Loss: 1.520, Val f1_micro: 0.232
Epoch: 260, Train Loss: 1.517, Val f1_micro: 0.236
Epoch: 280, Train Loss: 1.513, Val f1_micro: 0.236
Epoch: 300, Train Loss: 1.519, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.494, Val f1_micro: 0.235
Epoch: 340, Train Loss: 1.505, Val f1_micro: 0.236
Epoch: 360, Train Loss: 1.504, Val f1_micro: 0.233
Epoch: 380, Train Loss: 1.494, Val f1_micro: 0.232
Epoch: 400, Train Loss: 1.511, Val f1_micro: 0.234
Epoch: 420, Train Loss: 1.515, Val f1_micro: 0.233
Epoch: 440, Train Loss: 1.490, Val f1_micro: 0.238
Epoch: 460, Train Loss: 1.498, Val f1_micro: 0.236
Epoch: 480, Train Loss: 1.507, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.506, Val f1_micro: 0.232
f1-micro: 0.232, f1-macro: 0.199, f1-weighted: 0.200, , roc-auc: 0.647
##### RUN 3 #####
Epoch: 020, Train Loss: 1.641, Val f1_micro: 0.227
Epoch: 040, Train Loss: 1.536, Val f1_micro: 0.242
Epoch: 060, Train Loss: 1.516, Val f1_micro: 0.237
Epoch: 080, Train Loss: 1.523, Val f1_micro: 0.233
Epoch: 100, Train Loss: 1.516, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.525, Val f1_micro: 0.234
Epoch: 140, Train Loss: 1.527, Val f1_micro: 0.234
Epoch: 160, Train Loss: 1.543, Val f1_micro: 0.229
Epoch: 180, Train Loss: 1.529, Val f1_micro: 0.235
Epoch: 200, Train Loss: 1.538, Val f1_micro: 0.233
Epoch: 220, Train Loss: 1.529, Val f1_micro: 0.229
Epoch: 240, Train Loss: 1.527, Val f1_micro: 0.234
Epoch: 260, Train Loss: 1.515, Val f1_micro: 0.232
Epoch: 280, Train Loss: 1.514, Val f1_micro: 0.232
Epoch: 300, Train Loss: 1.498, Val f1_micro: 0.237
Epoch: 320, Train Loss: 1.511, Val f1_micro: 0.235
Epoch: 340, Train Loss: 1.511, Val f1_micro: 0.238
Epoch: 360, Train Loss: 1.514, Val f1_micro: 0.232
Epoch: 380, Train Loss: 1.509, Val f1_micro: 0.232
Epoch: 400, Train Loss: 1.507, Val f1_micro: 0.230
Epoch: 420, Train Loss: 1.495, Val f1_micro: 0.237
Epoch: 440, Train Loss: 1.507, Val f1_micro: 0.234
Epoch: 460, Train Loss: 1.491, Val f1_micro: 0.238
Epoch: 480, Train Loss: 1.500, Val f1_micro: 0.233
Epoch: 500, Train Loss: 1.497, Val f1_micro: 0.247
f1-micro: 0.247, f1-macro: 0.212, f1-weighted: 0.215, , roc-auc: 0.649
##### RUN 4 #####
Epoch: 020, Train Loss: 1.617, Val f1_micro: 0.229
Epoch: 040, Train Loss: 1.535, Val f1_micro: 0.241
Epoch: 060, Train Loss: 1.524, Val f1_micro: 0.237
Epoch: 080, Train Loss: 1.514, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.524, Val f1_micro: 0.238
Epoch: 120, Train Loss: 1.519, Val f1_micro: 0.237
Epoch: 140, Train Loss: 1.528, Val f1_micro: 0.234
Epoch: 160, Train Loss: 1.529, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.528, Val f1_micro: 0.234
Epoch: 200, Train Loss: 1.520, Val f1_micro: 0.236
Epoch: 220, Train Loss: 1.533, Val f1_micro: 0.237
Epoch: 240, Train Loss: 1.522, Val f1_micro: 0.232
Epoch: 260, Train Loss: 1.515, Val f1_micro: 0.228
Epoch: 280, Train Loss: 1.520, Val f1_micro: 0.234
Epoch: 300, Train Loss: 1.510, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.503, Val f1_micro: 0.228
Epoch: 340, Train Loss: 1.506, Val f1_micro: 0.235
Epoch: 360, Train Loss: 1.502, Val f1_micro: 0.240
Epoch: 380, Train Loss: 1.504, Val f1_micro: 0.236
Epoch: 400, Train Loss: 1.510, Val f1_micro: 0.233
Epoch: 420, Train Loss: 1.506, Val f1_micro: 0.236
Epoch: 440, Train Loss: 1.497, Val f1_micro: 0.234
Epoch: 460, Train Loss: 1.495, Val f1_micro: 0.233
Epoch: 480, Train Loss: 1.507, Val f1_micro: 0.233
Epoch: 500, Train Loss: 1.497, Val f1_micro: 0.235
f1-micro: 0.235, f1-macro: 0.200, f1-weighted: 0.200, , roc-auc: 0.648
##### RUN 5 #####
Epoch: 020, Train Loss: 1.630, Val f1_micro: 0.219
Epoch: 040, Train Loss: 1.541, Val f1_micro: 0.239
Epoch: 060, Train Loss: 1.521, Val f1_micro: 0.241
Epoch: 080, Train Loss: 1.522, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.532, Val f1_micro: 0.234
Epoch: 120, Train Loss: 1.536, Val f1_micro: 0.235
Epoch: 140, Train Loss: 1.516, Val f1_micro: 0.237
Epoch: 160, Train Loss: 1.528, Val f1_micro: 0.234
Epoch: 180, Train Loss: 1.524, Val f1_micro: 0.234
Epoch: 200, Train Loss: 1.535, Val f1_micro: 0.228
Epoch: 220, Train Loss: 1.526, Val f1_micro: 0.234
Epoch: 240, Train Loss: 1.512, Val f1_micro: 0.234
Epoch: 260, Train Loss: 1.536, Val f1_micro: 0.231
Epoch: 280, Train Loss: 1.518, Val f1_micro: 0.227
Epoch: 300, Train Loss: 1.501, Val f1_micro: 0.225
Epoch: 320, Train Loss: 1.517, Val f1_micro: 0.230
Epoch: 340, Train Loss: 1.509, Val f1_micro: 0.236
Epoch: 360, Train Loss: 1.507, Val f1_micro: 0.238
Epoch: 380, Train Loss: 1.509, Val f1_micro: 0.235
Epoch: 400, Train Loss: 1.503, Val f1_micro: 0.236
Epoch: 420, Train Loss: 1.507, Val f1_micro: 0.236
Epoch: 440, Train Loss: 1.521, Val f1_micro: 0.237
Epoch: 460, Train Loss: 1.509, Val f1_micro: 0.239
Epoch: 480, Train Loss: 1.492, Val f1_micro: 0.237
Epoch: 500, Train Loss: 1.500, Val f1_micro: 0.233
f1-micro: 0.233, f1-macro: 0.196, f1-weighted: 0.195, , roc-auc: 0.649
########## Hyperparameters combination ##########
(512, 0.3, 0.05, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.987, Val f1_micro: 0.106
Epoch: 040, Train Loss: 1.723, Val f1_micro: 0.149
Epoch: 060, Train Loss: 1.538, Val f1_micro: 0.166
Epoch: 080, Train Loss: 1.398, Val f1_micro: 0.203
Epoch: 100, Train Loss: 1.221, Val f1_micro: 0.230
Epoch: 120, Train Loss: 1.069, Val f1_micro: 0.244
Epoch: 140, Train Loss: 0.950, Val f1_micro: 0.250
Epoch: 160, Train Loss: 0.850, Val f1_micro: 0.265
Epoch: 180, Train Loss: 0.781, Val f1_micro: 0.275
Epoch: 200, Train Loss: 0.693, Val f1_micro: 0.276
Epoch: 220, Train Loss: 0.634, Val f1_micro: 0.278
Epoch: 240, Train Loss: 0.644, Val f1_micro: 0.287
Epoch: 260, Train Loss: 0.573, Val f1_micro: 0.290
Epoch: 280, Train Loss: 0.524, Val f1_micro: 0.292
Epoch: 300, Train Loss: 0.520, Val f1_micro: 0.295
Epoch: 320, Train Loss: 0.487, Val f1_micro: 0.297
Epoch: 340, Train Loss: 0.471, Val f1_micro: 0.297
Epoch: 360, Train Loss: 0.437, Val f1_micro: 0.298
Epoch: 380, Train Loss: 0.435, Val f1_micro: 0.298
Epoch: 400, Train Loss: 0.433, Val f1_micro: 0.302
Epoch: 420, Train Loss: 0.385, Val f1_micro: 0.301
Epoch: 440, Train Loss: 0.400, Val f1_micro: 0.303
Epoch: 460, Train Loss: 0.360, Val f1_micro: 0.302
Epoch: 480, Train Loss: 0.364, Val f1_micro: 0.305
Epoch: 500, Train Loss: 0.360, Val f1_micro: 0.303
f1-micro: 0.303, f1-macro: 0.296, f1-weighted: 0.303, , roc-auc: 0.667
##### RUN 2 #####
Epoch: 020, Train Loss: 1.956, Val f1_micro: 0.114
Epoch: 040, Train Loss: 1.716, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.524, Val f1_micro: 0.196
Epoch: 080, Train Loss: 1.383, Val f1_micro: 0.206
Epoch: 100, Train Loss: 1.252, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.076, Val f1_micro: 0.243
Epoch: 140, Train Loss: 0.969, Val f1_micro: 0.255
Epoch: 160, Train Loss: 0.841, Val f1_micro: 0.267
Epoch: 180, Train Loss: 0.770, Val f1_micro: 0.272
Epoch: 200, Train Loss: 0.721, Val f1_micro: 0.284
Epoch: 220, Train Loss: 0.646, Val f1_micro: 0.285
Epoch: 240, Train Loss: 0.603, Val f1_micro: 0.289
Epoch: 260, Train Loss: 0.555, Val f1_micro: 0.294
Epoch: 280, Train Loss: 0.532, Val f1_micro: 0.294
Epoch: 300, Train Loss: 0.505, Val f1_micro: 0.293
Epoch: 320, Train Loss: 0.473, Val f1_micro: 0.300
Epoch: 340, Train Loss: 0.438, Val f1_micro: 0.298
Epoch: 360, Train Loss: 0.432, Val f1_micro: 0.307
Epoch: 380, Train Loss: 0.408, Val f1_micro: 0.301
Epoch: 400, Train Loss: 0.406, Val f1_micro: 0.299
Epoch: 420, Train Loss: 0.363, Val f1_micro: 0.299
Epoch: 440, Train Loss: 0.369, Val f1_micro: 0.304
Epoch: 460, Train Loss: 0.379, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.358, Val f1_micro: 0.305
Epoch: 500, Train Loss: 0.340, Val f1_micro: 0.310
f1-micro: 0.310, f1-macro: 0.306, f1-weighted: 0.311, , roc-auc: 0.670
##### RUN 3 #####
Epoch: 020, Train Loss: 1.964, Val f1_micro: 0.153
Epoch: 040, Train Loss: 1.771, Val f1_micro: 0.190
Epoch: 060, Train Loss: 1.601, Val f1_micro: 0.164
Epoch: 080, Train Loss: 1.457, Val f1_micro: 0.191
Epoch: 100, Train Loss: 1.336, Val f1_micro: 0.213
Epoch: 120, Train Loss: 1.234, Val f1_micro: 0.229
Epoch: 140, Train Loss: 1.109, Val f1_micro: 0.238
Epoch: 160, Train Loss: 0.972, Val f1_micro: 0.252
Epoch: 180, Train Loss: 0.921, Val f1_micro: 0.262
Epoch: 200, Train Loss: 0.834, Val f1_micro: 0.273
Epoch: 220, Train Loss: 0.788, Val f1_micro: 0.273
Epoch: 240, Train Loss: 0.704, Val f1_micro: 0.278
Epoch: 260, Train Loss: 0.679, Val f1_micro: 0.282
Epoch: 280, Train Loss: 0.654, Val f1_micro: 0.284
Epoch: 300, Train Loss: 0.616, Val f1_micro: 0.285
Epoch: 320, Train Loss: 0.548, Val f1_micro: 0.285
Epoch: 340, Train Loss: 0.547, Val f1_micro: 0.291
Epoch: 360, Train Loss: 0.503, Val f1_micro: 0.292
Epoch: 380, Train Loss: 0.481, Val f1_micro: 0.292
Epoch: 400, Train Loss: 0.474, Val f1_micro: 0.290
Epoch: 420, Train Loss: 0.422, Val f1_micro: 0.293
Epoch: 440, Train Loss: 0.450, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.414, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.391, Val f1_micro: 0.298
Epoch: 500, Train Loss: 0.377, Val f1_micro: 0.299
f1-micro: 0.299, f1-macro: 0.296, f1-weighted: 0.301, , roc-auc: 0.660
##### RUN 4 #####
Epoch: 020, Train Loss: 1.976, Val f1_micro: 0.106
Epoch: 040, Train Loss: 1.805, Val f1_micro: 0.180
Epoch: 060, Train Loss: 1.605, Val f1_micro: 0.159
Epoch: 080, Train Loss: 1.394, Val f1_micro: 0.198
Epoch: 100, Train Loss: 1.201, Val f1_micro: 0.225
Epoch: 120, Train Loss: 1.063, Val f1_micro: 0.243
Epoch: 140, Train Loss: 0.947, Val f1_micro: 0.254
Epoch: 160, Train Loss: 0.856, Val f1_micro: 0.265
Epoch: 180, Train Loss: 0.762, Val f1_micro: 0.275
Epoch: 200, Train Loss: 0.709, Val f1_micro: 0.278
Epoch: 220, Train Loss: 0.663, Val f1_micro: 0.287
Epoch: 240, Train Loss: 0.577, Val f1_micro: 0.287
Epoch: 260, Train Loss: 0.544, Val f1_micro: 0.295
Epoch: 280, Train Loss: 0.517, Val f1_micro: 0.299
Epoch: 300, Train Loss: 0.507, Val f1_micro: 0.301
Epoch: 320, Train Loss: 0.438, Val f1_micro: 0.303
Epoch: 340, Train Loss: 0.424, Val f1_micro: 0.303
Epoch: 360, Train Loss: 0.435, Val f1_micro: 0.303
Epoch: 380, Train Loss: 0.411, Val f1_micro: 0.309
Epoch: 400, Train Loss: 0.401, Val f1_micro: 0.311
Epoch: 420, Train Loss: 0.412, Val f1_micro: 0.308
Epoch: 440, Train Loss: 0.350, Val f1_micro: 0.307
Epoch: 460, Train Loss: 0.342, Val f1_micro: 0.302
Epoch: 480, Train Loss: 0.321, Val f1_micro: 0.304
Epoch: 500, Train Loss: 0.333, Val f1_micro: 0.312
f1-micro: 0.312, f1-macro: 0.307, f1-weighted: 0.312, , roc-auc: 0.671
##### RUN 5 #####
Epoch: 020, Train Loss: 2.002, Val f1_micro: 0.154
Epoch: 040, Train Loss: 1.744, Val f1_micro: 0.184
Epoch: 060, Train Loss: 1.571, Val f1_micro: 0.190
Epoch: 080, Train Loss: 1.430, Val f1_micro: 0.209
Epoch: 100, Train Loss: 1.296, Val f1_micro: 0.221
Epoch: 120, Train Loss: 1.190, Val f1_micro: 0.231
Epoch: 140, Train Loss: 1.082, Val f1_micro: 0.244
Epoch: 160, Train Loss: 0.980, Val f1_micro: 0.257
Epoch: 180, Train Loss: 0.884, Val f1_micro: 0.265
Epoch: 200, Train Loss: 0.794, Val f1_micro: 0.274
Epoch: 220, Train Loss: 0.699, Val f1_micro: 0.283
Epoch: 240, Train Loss: 0.687, Val f1_micro: 0.284
Epoch: 260, Train Loss: 0.602, Val f1_micro: 0.285
Epoch: 280, Train Loss: 0.591, Val f1_micro: 0.293
Epoch: 300, Train Loss: 0.537, Val f1_micro: 0.293
Epoch: 320, Train Loss: 0.533, Val f1_micro: 0.294
Epoch: 340, Train Loss: 0.477, Val f1_micro: 0.295
Epoch: 360, Train Loss: 0.461, Val f1_micro: 0.296
Epoch: 380, Train Loss: 0.422, Val f1_micro: 0.297
Epoch: 400, Train Loss: 0.436, Val f1_micro: 0.300
Epoch: 420, Train Loss: 0.376, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.393, Val f1_micro: 0.301
Epoch: 460, Train Loss: 0.361, Val f1_micro: 0.304
Epoch: 480, Train Loss: 0.330, Val f1_micro: 0.303
Epoch: 500, Train Loss: 0.337, Val f1_micro: 0.303
f1-micro: 0.303, f1-macro: 0.298, f1-weighted: 0.305, , roc-auc: 0.668
########## Hyperparameters combination ##########
(512, 0.3, 0.05, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.000, Val f1_micro: 0.106
Epoch: 040, Train Loss: 1.901, Val f1_micro: 0.174
Epoch: 060, Train Loss: 1.758, Val f1_micro: 0.165
Epoch: 080, Train Loss: 1.649, Val f1_micro: 0.170
Epoch: 100, Train Loss: 1.496, Val f1_micro: 0.217
Epoch: 120, Train Loss: 1.369, Val f1_micro: 0.222
Epoch: 140, Train Loss: 1.275, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.219, Val f1_micro: 0.254
Epoch: 180, Train Loss: 1.151, Val f1_micro: 0.252
Epoch: 200, Train Loss: 1.059, Val f1_micro: 0.259
Epoch: 220, Train Loss: 1.041, Val f1_micro: 0.258
Epoch: 240, Train Loss: 0.987, Val f1_micro: 0.264
Epoch: 260, Train Loss: 0.931, Val f1_micro: 0.267
Epoch: 280, Train Loss: 0.945, Val f1_micro: 0.264
Epoch: 300, Train Loss: 0.833, Val f1_micro: 0.284
Epoch: 320, Train Loss: 0.828, Val f1_micro: 0.282
Epoch: 340, Train Loss: 0.792, Val f1_micro: 0.286
Epoch: 360, Train Loss: 0.821, Val f1_micro: 0.276
Epoch: 380, Train Loss: 0.801, Val f1_micro: 0.284
Epoch: 400, Train Loss: 0.738, Val f1_micro: 0.284
Epoch: 420, Train Loss: 0.719, Val f1_micro: 0.287
Epoch: 440, Train Loss: 0.730, Val f1_micro: 0.290
Epoch: 460, Train Loss: 0.722, Val f1_micro: 0.281
Epoch: 480, Train Loss: 0.698, Val f1_micro: 0.299
Epoch: 500, Train Loss: 0.731, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.277, f1-weighted: 0.281, , roc-auc: 0.664
##### RUN 2 #####
Epoch: 020, Train Loss: 2.023, Val f1_micro: 0.104
Epoch: 040, Train Loss: 1.887, Val f1_micro: 0.126
Epoch: 060, Train Loss: 1.755, Val f1_micro: 0.144
Epoch: 080, Train Loss: 1.677, Val f1_micro: 0.155
Epoch: 100, Train Loss: 1.571, Val f1_micro: 0.169
Epoch: 120, Train Loss: 1.484, Val f1_micro: 0.180
Epoch: 140, Train Loss: 1.393, Val f1_micro: 0.206
Epoch: 160, Train Loss: 1.290, Val f1_micro: 0.225
Epoch: 180, Train Loss: 1.197, Val f1_micro: 0.240
Epoch: 200, Train Loss: 1.122, Val f1_micro: 0.249
Epoch: 220, Train Loss: 1.041, Val f1_micro: 0.262
Epoch: 240, Train Loss: 1.003, Val f1_micro: 0.258
Epoch: 260, Train Loss: 0.951, Val f1_micro: 0.267
Epoch: 280, Train Loss: 0.900, Val f1_micro: 0.274
Epoch: 300, Train Loss: 0.892, Val f1_micro: 0.268
Epoch: 320, Train Loss: 0.857, Val f1_micro: 0.276
Epoch: 340, Train Loss: 0.804, Val f1_micro: 0.273
Epoch: 360, Train Loss: 0.789, Val f1_micro: 0.276
Epoch: 380, Train Loss: 0.765, Val f1_micro: 0.284
Epoch: 400, Train Loss: 0.732, Val f1_micro: 0.288
Epoch: 420, Train Loss: 0.733, Val f1_micro: 0.292
Epoch: 440, Train Loss: 0.704, Val f1_micro: 0.293
Epoch: 460, Train Loss: 0.676, Val f1_micro: 0.282
Epoch: 480, Train Loss: 0.711, Val f1_micro: 0.285
Epoch: 500, Train Loss: 0.685, Val f1_micro: 0.289
f1-micro: 0.289, f1-macro: 0.284, f1-weighted: 0.287, , roc-auc: 0.662
##### RUN 3 #####
Epoch: 020, Train Loss: 2.020, Val f1_micro: 0.144
Epoch: 040, Train Loss: 1.891, Val f1_micro: 0.173
Epoch: 060, Train Loss: 1.763, Val f1_micro: 0.146
Epoch: 080, Train Loss: 1.636, Val f1_micro: 0.160
Epoch: 100, Train Loss: 1.470, Val f1_micro: 0.195
Epoch: 120, Train Loss: 1.384, Val f1_micro: 0.217
Epoch: 140, Train Loss: 1.289, Val f1_micro: 0.233
Epoch: 160, Train Loss: 1.171, Val f1_micro: 0.245
Epoch: 180, Train Loss: 1.130, Val f1_micro: 0.239
Epoch: 200, Train Loss: 1.057, Val f1_micro: 0.256
Epoch: 220, Train Loss: 1.010, Val f1_micro: 0.257
Epoch: 240, Train Loss: 0.969, Val f1_micro: 0.260
Epoch: 260, Train Loss: 0.936, Val f1_micro: 0.265
Epoch: 280, Train Loss: 0.879, Val f1_micro: 0.267
Epoch: 300, Train Loss: 0.859, Val f1_micro: 0.274
Epoch: 320, Train Loss: 0.816, Val f1_micro: 0.281
Epoch: 340, Train Loss: 0.788, Val f1_micro: 0.268
Epoch: 360, Train Loss: 0.753, Val f1_micro: 0.277
Epoch: 380, Train Loss: 0.726, Val f1_micro: 0.290
Epoch: 400, Train Loss: 0.762, Val f1_micro: 0.292
Epoch: 420, Train Loss: 0.712, Val f1_micro: 0.291
Epoch: 440, Train Loss: 0.686, Val f1_micro: 0.293
Epoch: 460, Train Loss: 0.748, Val f1_micro: 0.290
Epoch: 480, Train Loss: 0.667, Val f1_micro: 0.287
Epoch: 500, Train Loss: 0.644, Val f1_micro: 0.293
f1-micro: 0.293, f1-macro: 0.289, f1-weighted: 0.293, , roc-auc: 0.667
##### RUN 4 #####
Epoch: 020, Train Loss: 2.013, Val f1_micro: 0.109
Epoch: 040, Train Loss: 1.873, Val f1_micro: 0.176
Epoch: 060, Train Loss: 1.718, Val f1_micro: 0.174
Epoch: 080, Train Loss: 1.588, Val f1_micro: 0.186
Epoch: 100, Train Loss: 1.436, Val f1_micro: 0.204
Epoch: 120, Train Loss: 1.340, Val f1_micro: 0.224
Epoch: 140, Train Loss: 1.238, Val f1_micro: 0.233
Epoch: 160, Train Loss: 1.153, Val f1_micro: 0.245
Epoch: 180, Train Loss: 1.136, Val f1_micro: 0.230
Epoch: 200, Train Loss: 0.986, Val f1_micro: 0.255
Epoch: 220, Train Loss: 0.957, Val f1_micro: 0.252
Epoch: 240, Train Loss: 0.908, Val f1_micro: 0.270
Epoch: 260, Train Loss: 0.899, Val f1_micro: 0.269
Epoch: 280, Train Loss: 0.818, Val f1_micro: 0.272
Epoch: 300, Train Loss: 0.816, Val f1_micro: 0.263
Epoch: 320, Train Loss: 0.794, Val f1_micro: 0.277
Epoch: 340, Train Loss: 0.781, Val f1_micro: 0.282
Epoch: 360, Train Loss: 0.748, Val f1_micro: 0.282
Epoch: 380, Train Loss: 0.729, Val f1_micro: 0.285
Epoch: 400, Train Loss: 0.736, Val f1_micro: 0.283
Epoch: 420, Train Loss: 0.696, Val f1_micro: 0.285
Epoch: 440, Train Loss: 0.720, Val f1_micro: 0.285
Epoch: 460, Train Loss: 0.651, Val f1_micro: 0.291
Epoch: 480, Train Loss: 0.636, Val f1_micro: 0.290
Epoch: 500, Train Loss: 0.684, Val f1_micro: 0.295
f1-micro: 0.295, f1-macro: 0.289, f1-weighted: 0.294, , roc-auc: 0.666
##### RUN 5 #####
Epoch: 020, Train Loss: 2.010, Val f1_micro: 0.104
Epoch: 040, Train Loss: 1.843, Val f1_micro: 0.179
Epoch: 060, Train Loss: 1.678, Val f1_micro: 0.151
Epoch: 080, Train Loss: 1.539, Val f1_micro: 0.195
Epoch: 100, Train Loss: 1.395, Val f1_micro: 0.213
Epoch: 120, Train Loss: 1.284, Val f1_micro: 0.223
Epoch: 140, Train Loss: 1.276, Val f1_micro: 0.219
Epoch: 160, Train Loss: 1.161, Val f1_micro: 0.241
Epoch: 180, Train Loss: 1.078, Val f1_micro: 0.251
Epoch: 200, Train Loss: 1.013, Val f1_micro: 0.254
Epoch: 220, Train Loss: 1.051, Val f1_micro: 0.257
Epoch: 240, Train Loss: 0.948, Val f1_micro: 0.266
Epoch: 260, Train Loss: 0.957, Val f1_micro: 0.267
Epoch: 280, Train Loss: 0.891, Val f1_micro: 0.265
Epoch: 300, Train Loss: 0.887, Val f1_micro: 0.272
Epoch: 320, Train Loss: 0.791, Val f1_micro: 0.277
Epoch: 340, Train Loss: 0.758, Val f1_micro: 0.277
Epoch: 360, Train Loss: 0.815, Val f1_micro: 0.265
Epoch: 380, Train Loss: 0.712, Val f1_micro: 0.289
Epoch: 400, Train Loss: 0.709, Val f1_micro: 0.283
Epoch: 420, Train Loss: 0.760, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.711, Val f1_micro: 0.284
Epoch: 460, Train Loss: 0.692, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.632, Val f1_micro: 0.288
Epoch: 500, Train Loss: 0.664, Val f1_micro: 0.294
f1-micro: 0.294, f1-macro: 0.289, f1-weighted: 0.293, , roc-auc: 0.666
########## Hyperparameters combination ##########
(512, 0.3, 0.05, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.016, Val f1_micro: 0.106
Epoch: 040, Train Loss: 1.914, Val f1_micro: 0.173
Epoch: 060, Train Loss: 1.822, Val f1_micro: 0.136
Epoch: 080, Train Loss: 1.689, Val f1_micro: 0.159
Epoch: 100, Train Loss: 1.606, Val f1_micro: 0.202
Epoch: 120, Train Loss: 1.521, Val f1_micro: 0.214
Epoch: 140, Train Loss: 1.455, Val f1_micro: 0.222
Epoch: 160, Train Loss: 1.353, Val f1_micro: 0.226
Epoch: 180, Train Loss: 1.306, Val f1_micro: 0.235
Epoch: 200, Train Loss: 1.232, Val f1_micro: 0.234
Epoch: 220, Train Loss: 1.218, Val f1_micro: 0.243
Epoch: 240, Train Loss: 1.153, Val f1_micro: 0.248
Epoch: 260, Train Loss: 1.174, Val f1_micro: 0.243
Epoch: 280, Train Loss: 1.135, Val f1_micro: 0.251
Epoch: 300, Train Loss: 1.058, Val f1_micro: 0.247
Epoch: 320, Train Loss: 1.064, Val f1_micro: 0.251
Epoch: 340, Train Loss: 1.135, Val f1_micro: 0.260
Epoch: 360, Train Loss: 1.027, Val f1_micro: 0.259
Epoch: 380, Train Loss: 0.986, Val f1_micro: 0.269
Epoch: 400, Train Loss: 1.010, Val f1_micro: 0.258
Epoch: 420, Train Loss: 1.002, Val f1_micro: 0.258
Epoch: 440, Train Loss: 0.952, Val f1_micro: 0.272
Epoch: 460, Train Loss: 0.958, Val f1_micro: 0.278
Epoch: 480, Train Loss: 0.912, Val f1_micro: 0.280
Epoch: 500, Train Loss: 0.907, Val f1_micro: 0.282
f1-micro: 0.282, f1-macro: 0.270, f1-weighted: 0.274, , roc-auc: 0.659
##### RUN 2 #####
Epoch: 020, Train Loss: 2.015, Val f1_micro: 0.108
Epoch: 040, Train Loss: 1.897, Val f1_micro: 0.175
Epoch: 060, Train Loss: 1.752, Val f1_micro: 0.145
Epoch: 080, Train Loss: 1.641, Val f1_micro: 0.170
Epoch: 100, Train Loss: 1.468, Val f1_micro: 0.210
Epoch: 120, Train Loss: 1.392, Val f1_micro: 0.201
Epoch: 140, Train Loss: 1.326, Val f1_micro: 0.225
Epoch: 160, Train Loss: 1.279, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.222, Val f1_micro: 0.229
Epoch: 200, Train Loss: 1.175, Val f1_micro: 0.241
Epoch: 220, Train Loss: 1.179, Val f1_micro: 0.245
Epoch: 240, Train Loss: 1.145, Val f1_micro: 0.242
Epoch: 260, Train Loss: 1.073, Val f1_micro: 0.259
Epoch: 280, Train Loss: 1.057, Val f1_micro: 0.267
Epoch: 300, Train Loss: 1.026, Val f1_micro: 0.270
Epoch: 320, Train Loss: 1.006, Val f1_micro: 0.264
Epoch: 340, Train Loss: 1.058, Val f1_micro: 0.251
Epoch: 360, Train Loss: 0.989, Val f1_micro: 0.269
Epoch: 380, Train Loss: 0.961, Val f1_micro: 0.278
Epoch: 400, Train Loss: 0.975, Val f1_micro: 0.258
Epoch: 420, Train Loss: 1.019, Val f1_micro: 0.245
Epoch: 440, Train Loss: 0.964, Val f1_micro: 0.260
Epoch: 460, Train Loss: 0.966, Val f1_micro: 0.267
Epoch: 480, Train Loss: 0.940, Val f1_micro: 0.271
Epoch: 500, Train Loss: 0.899, Val f1_micro: 0.278
f1-micro: 0.278, f1-macro: 0.267, f1-weighted: 0.272, , roc-auc: 0.655
##### RUN 3 #####
Epoch: 020, Train Loss: 2.010, Val f1_micro: 0.113
Epoch: 040, Train Loss: 1.861, Val f1_micro: 0.193
Epoch: 060, Train Loss: 1.742, Val f1_micro: 0.180
Epoch: 080, Train Loss: 1.644, Val f1_micro: 0.200
Epoch: 100, Train Loss: 1.560, Val f1_micro: 0.203
Epoch: 120, Train Loss: 1.442, Val f1_micro: 0.197
Epoch: 140, Train Loss: 1.412, Val f1_micro: 0.221
Epoch: 160, Train Loss: 1.395, Val f1_micro: 0.215
Epoch: 180, Train Loss: 1.280, Val f1_micro: 0.225
Epoch: 200, Train Loss: 1.216, Val f1_micro: 0.243
Epoch: 220, Train Loss: 1.220, Val f1_micro: 0.248
Epoch: 240, Train Loss: 1.181, Val f1_micro: 0.244
Epoch: 260, Train Loss: 1.184, Val f1_micro: 0.251
Epoch: 280, Train Loss: 1.076, Val f1_micro: 0.258
Epoch: 300, Train Loss: 1.042, Val f1_micro: 0.266
Epoch: 320, Train Loss: 1.050, Val f1_micro: 0.259
Epoch: 340, Train Loss: 1.029, Val f1_micro: 0.262
Epoch: 360, Train Loss: 0.991, Val f1_micro: 0.264
Epoch: 380, Train Loss: 0.952, Val f1_micro: 0.277
Epoch: 400, Train Loss: 0.987, Val f1_micro: 0.275
Epoch: 420, Train Loss: 0.956, Val f1_micro: 0.267
Epoch: 440, Train Loss: 0.966, Val f1_micro: 0.279
Epoch: 460, Train Loss: 0.939, Val f1_micro: 0.267
Epoch: 480, Train Loss: 0.923, Val f1_micro: 0.279
Epoch: 500, Train Loss: 0.906, Val f1_micro: 0.275
f1-micro: 0.275, f1-macro: 0.265, f1-weighted: 0.268, , roc-auc: 0.653
##### RUN 4 #####
Epoch: 020, Train Loss: 2.016, Val f1_micro: 0.107
Epoch: 040, Train Loss: 1.889, Val f1_micro: 0.175
Epoch: 060, Train Loss: 1.738, Val f1_micro: 0.157
Epoch: 080, Train Loss: 1.599, Val f1_micro: 0.190
Epoch: 100, Train Loss: 1.559, Val f1_micro: 0.195
Epoch: 120, Train Loss: 1.440, Val f1_micro: 0.211
Epoch: 140, Train Loss: 1.374, Val f1_micro: 0.219
Epoch: 160, Train Loss: 1.330, Val f1_micro: 0.227
Epoch: 180, Train Loss: 1.263, Val f1_micro: 0.235
Epoch: 200, Train Loss: 1.236, Val f1_micro: 0.236
Epoch: 220, Train Loss: 1.217, Val f1_micro: 0.246
Epoch: 240, Train Loss: 1.168, Val f1_micro: 0.251
Epoch: 260, Train Loss: 1.145, Val f1_micro: 0.253
Epoch: 280, Train Loss: 1.136, Val f1_micro: 0.247
Epoch: 300, Train Loss: 1.094, Val f1_micro: 0.267
Epoch: 320, Train Loss: 1.062, Val f1_micro: 0.256
Epoch: 340, Train Loss: 1.073, Val f1_micro: 0.266
Epoch: 360, Train Loss: 1.013, Val f1_micro: 0.258
Epoch: 380, Train Loss: 0.984, Val f1_micro: 0.265
Epoch: 400, Train Loss: 0.989, Val f1_micro: 0.274
Epoch: 420, Train Loss: 0.994, Val f1_micro: 0.279
Epoch: 440, Train Loss: 0.976, Val f1_micro: 0.272
Epoch: 460, Train Loss: 0.928, Val f1_micro: 0.274
Epoch: 480, Train Loss: 1.080, Val f1_micro: 0.241
Epoch: 500, Train Loss: 0.953, Val f1_micro: 0.276
f1-micro: 0.276, f1-macro: 0.262, f1-weighted: 0.266, , roc-auc: 0.658
##### RUN 5 #####
Epoch: 020, Train Loss: 2.005, Val f1_micro: 0.107
Epoch: 040, Train Loss: 1.868, Val f1_micro: 0.178
Epoch: 060, Train Loss: 1.751, Val f1_micro: 0.164
Epoch: 080, Train Loss: 1.615, Val f1_micro: 0.204
Epoch: 100, Train Loss: 1.538, Val f1_micro: 0.213
Epoch: 120, Train Loss: 1.455, Val f1_micro: 0.220
Epoch: 140, Train Loss: 1.377, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.306, Val f1_micro: 0.234
Epoch: 180, Train Loss: 1.274, Val f1_micro: 0.220
Epoch: 200, Train Loss: 1.244, Val f1_micro: 0.239
Epoch: 220, Train Loss: 1.249, Val f1_micro: 0.237
Epoch: 240, Train Loss: 1.194, Val f1_micro: 0.241
Epoch: 260, Train Loss: 1.128, Val f1_micro: 0.250
Epoch: 280, Train Loss: 1.131, Val f1_micro: 0.249
Epoch: 300, Train Loss: 1.107, Val f1_micro: 0.266
Epoch: 320, Train Loss: 1.072, Val f1_micro: 0.255
Epoch: 340, Train Loss: 1.077, Val f1_micro: 0.253
Epoch: 360, Train Loss: 1.035, Val f1_micro: 0.250
Epoch: 380, Train Loss: 1.024, Val f1_micro: 0.261
Epoch: 400, Train Loss: 0.980, Val f1_micro: 0.275
Epoch: 420, Train Loss: 0.955, Val f1_micro: 0.270
Epoch: 440, Train Loss: 1.006, Val f1_micro: 0.247
Epoch: 460, Train Loss: 0.948, Val f1_micro: 0.276
Epoch: 480, Train Loss: 0.952, Val f1_micro: 0.279
Epoch: 500, Train Loss: 0.928, Val f1_micro: 0.275
f1-micro: 0.275, f1-macro: 0.261, f1-weighted: 0.263, , roc-auc: 0.658
########## Hyperparameters combination ##########
(512, 0.3, 0.05, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.060, Val f1_micro: 0.141
Epoch: 040, Train Loss: 1.995, Val f1_micro: 0.170
Epoch: 060, Train Loss: 1.921, Val f1_micro: 0.189
Epoch: 080, Train Loss: 1.880, Val f1_micro: 0.171
Epoch: 100, Train Loss: 1.856, Val f1_micro: 0.183
Epoch: 120, Train Loss: 1.787, Val f1_micro: 0.189
Epoch: 140, Train Loss: 1.779, Val f1_micro: 0.199
Epoch: 160, Train Loss: 1.745, Val f1_micro: 0.200
Epoch: 180, Train Loss: 1.759, Val f1_micro: 0.208
Epoch: 200, Train Loss: 1.717, Val f1_micro: 0.211
Epoch: 220, Train Loss: 1.703, Val f1_micro: 0.200
Epoch: 240, Train Loss: 1.710, Val f1_micro: 0.181
Epoch: 260, Train Loss: 1.699, Val f1_micro: 0.227
Epoch: 280, Train Loss: 1.680, Val f1_micro: 0.208
Epoch: 300, Train Loss: 1.689, Val f1_micro: 0.195
Epoch: 320, Train Loss: 1.704, Val f1_micro: 0.214
Epoch: 340, Train Loss: 1.674, Val f1_micro: 0.222
Epoch: 360, Train Loss: 1.675, Val f1_micro: 0.214
Epoch: 380, Train Loss: 1.662, Val f1_micro: 0.212
Epoch: 400, Train Loss: 1.662, Val f1_micro: 0.218
Epoch: 420, Train Loss: 1.685, Val f1_micro: 0.209
Epoch: 440, Train Loss: 1.708, Val f1_micro: 0.211
Epoch: 460, Train Loss: 1.663, Val f1_micro: 0.221
Epoch: 480, Train Loss: 1.654, Val f1_micro: 0.215
Epoch: 500, Train Loss: 1.664, Val f1_micro: 0.228
f1-micro: 0.228, f1-macro: 0.178, f1-weighted: 0.179, , roc-auc: 0.629
##### RUN 2 #####
Epoch: 020, Train Loss: 2.062, Val f1_micro: 0.097
Epoch: 040, Train Loss: 2.009, Val f1_micro: 0.163
Epoch: 060, Train Loss: 1.946, Val f1_micro: 0.196
Epoch: 080, Train Loss: 1.882, Val f1_micro: 0.197
Epoch: 100, Train Loss: 1.833, Val f1_micro: 0.187
Epoch: 120, Train Loss: 1.770, Val f1_micro: 0.201
Epoch: 140, Train Loss: 1.739, Val f1_micro: 0.195
Epoch: 160, Train Loss: 1.740, Val f1_micro: 0.210
Epoch: 180, Train Loss: 1.733, Val f1_micro: 0.209
Epoch: 200, Train Loss: 1.717, Val f1_micro: 0.203
Epoch: 220, Train Loss: 1.700, Val f1_micro: 0.199
Epoch: 240, Train Loss: 1.705, Val f1_micro: 0.211
Epoch: 260, Train Loss: 1.688, Val f1_micro: 0.214
Epoch: 280, Train Loss: 1.695, Val f1_micro: 0.214
Epoch: 300, Train Loss: 1.697, Val f1_micro: 0.213
Epoch: 320, Train Loss: 1.669, Val f1_micro: 0.220
Epoch: 340, Train Loss: 1.678, Val f1_micro: 0.219
Epoch: 360, Train Loss: 1.667, Val f1_micro: 0.213
Epoch: 380, Train Loss: 1.686, Val f1_micro: 0.215
Epoch: 400, Train Loss: 1.652, Val f1_micro: 0.221
Epoch: 420, Train Loss: 1.659, Val f1_micro: 0.210
Epoch: 440, Train Loss: 1.671, Val f1_micro: 0.216
Epoch: 460, Train Loss: 1.649, Val f1_micro: 0.204
Epoch: 480, Train Loss: 1.654, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.632, Val f1_micro: 0.216
f1-micro: 0.216, f1-macro: 0.174, f1-weighted: 0.177, , roc-auc: 0.632
##### RUN 3 #####
Epoch: 020, Train Loss: 2.049, Val f1_micro: 0.100
Epoch: 040, Train Loss: 1.983, Val f1_micro: 0.119
Epoch: 060, Train Loss: 1.952, Val f1_micro: 0.179
Epoch: 080, Train Loss: 1.875, Val f1_micro: 0.188
Epoch: 100, Train Loss: 1.820, Val f1_micro: 0.199
Epoch: 120, Train Loss: 1.772, Val f1_micro: 0.191
Epoch: 140, Train Loss: 1.746, Val f1_micro: 0.208
Epoch: 160, Train Loss: 1.747, Val f1_micro: 0.200
Epoch: 180, Train Loss: 1.720, Val f1_micro: 0.207
Epoch: 200, Train Loss: 1.719, Val f1_micro: 0.203
Epoch: 220, Train Loss: 1.726, Val f1_micro: 0.206
Epoch: 240, Train Loss: 1.756, Val f1_micro: 0.208
Epoch: 260, Train Loss: 1.709, Val f1_micro: 0.195
Epoch: 280, Train Loss: 1.685, Val f1_micro: 0.220
Epoch: 300, Train Loss: 1.696, Val f1_micro: 0.209
Epoch: 320, Train Loss: 1.672, Val f1_micro: 0.217
Epoch: 340, Train Loss: 1.689, Val f1_micro: 0.225
Epoch: 360, Train Loss: 1.676, Val f1_micro: 0.215
Epoch: 380, Train Loss: 1.661, Val f1_micro: 0.216
Epoch: 400, Train Loss: 1.686, Val f1_micro: 0.207
Epoch: 420, Train Loss: 1.695, Val f1_micro: 0.215
Epoch: 440, Train Loss: 1.679, Val f1_micro: 0.221
Epoch: 460, Train Loss: 1.657, Val f1_micro: 0.221
Epoch: 480, Train Loss: 1.691, Val f1_micro: 0.199
Epoch: 500, Train Loss: 1.680, Val f1_micro: 0.215
f1-micro: 0.215, f1-macro: 0.171, f1-weighted: 0.172, , roc-auc: 0.623
##### RUN 4 #####
Epoch: 020, Train Loss: 2.050, Val f1_micro: 0.099
Epoch: 040, Train Loss: 2.006, Val f1_micro: 0.175
Epoch: 060, Train Loss: 1.948, Val f1_micro: 0.188
Epoch: 080, Train Loss: 1.862, Val f1_micro: 0.174
Epoch: 100, Train Loss: 1.825, Val f1_micro: 0.186
Epoch: 120, Train Loss: 1.788, Val f1_micro: 0.185
Epoch: 140, Train Loss: 1.752, Val f1_micro: 0.198
Epoch: 160, Train Loss: 1.739, Val f1_micro: 0.201
Epoch: 180, Train Loss: 1.726, Val f1_micro: 0.193
Epoch: 200, Train Loss: 1.745, Val f1_micro: 0.215
Epoch: 220, Train Loss: 1.708, Val f1_micro: 0.217
Epoch: 240, Train Loss: 1.701, Val f1_micro: 0.210
Epoch: 260, Train Loss: 1.690, Val f1_micro: 0.202
Epoch: 280, Train Loss: 1.700, Val f1_micro: 0.222
Epoch: 300, Train Loss: 1.700, Val f1_micro: 0.206
Epoch: 320, Train Loss: 1.674, Val f1_micro: 0.218
Epoch: 340, Train Loss: 1.661, Val f1_micro: 0.206
Epoch: 360, Train Loss: 1.667, Val f1_micro: 0.207
Epoch: 380, Train Loss: 1.674, Val f1_micro: 0.208
Epoch: 400, Train Loss: 1.661, Val f1_micro: 0.219
Epoch: 420, Train Loss: 1.687, Val f1_micro: 0.203
Epoch: 440, Train Loss: 1.667, Val f1_micro: 0.212
Epoch: 460, Train Loss: 1.663, Val f1_micro: 0.215
Epoch: 480, Train Loss: 1.660, Val f1_micro: 0.212
Epoch: 500, Train Loss: 1.715, Val f1_micro: 0.200
f1-micro: 0.200, f1-macro: 0.147, f1-weighted: 0.149, , roc-auc: 0.617
##### RUN 5 #####
Epoch: 020, Train Loss: 2.055, Val f1_micro: 0.146
Epoch: 040, Train Loss: 2.008, Val f1_micro: 0.166
Epoch: 060, Train Loss: 1.945, Val f1_micro: 0.182
Epoch: 080, Train Loss: 1.886, Val f1_micro: 0.183
Epoch: 100, Train Loss: 1.816, Val f1_micro: 0.188
Epoch: 120, Train Loss: 1.804, Val f1_micro: 0.202
Epoch: 140, Train Loss: 1.765, Val f1_micro: 0.193
Epoch: 160, Train Loss: 1.737, Val f1_micro: 0.203
Epoch: 180, Train Loss: 1.718, Val f1_micro: 0.213
Epoch: 200, Train Loss: 1.698, Val f1_micro: 0.208
Epoch: 220, Train Loss: 1.709, Val f1_micro: 0.202
Epoch: 240, Train Loss: 1.713, Val f1_micro: 0.215
Epoch: 260, Train Loss: 1.695, Val f1_micro: 0.217
Epoch: 280, Train Loss: 1.688, Val f1_micro: 0.217
Epoch: 300, Train Loss: 1.670, Val f1_micro: 0.232
Epoch: 320, Train Loss: 1.678, Val f1_micro: 0.234
Epoch: 340, Train Loss: 1.706, Val f1_micro: 0.215
Epoch: 360, Train Loss: 1.662, Val f1_micro: 0.210
Epoch: 380, Train Loss: 1.670, Val f1_micro: 0.228
Epoch: 400, Train Loss: 1.689, Val f1_micro: 0.220
Epoch: 420, Train Loss: 1.670, Val f1_micro: 0.214
Epoch: 440, Train Loss: 1.670, Val f1_micro: 0.222
Epoch: 460, Train Loss: 1.690, Val f1_micro: 0.220
Epoch: 480, Train Loss: 1.704, Val f1_micro: 0.222
Epoch: 500, Train Loss: 1.660, Val f1_micro: 0.217
f1-micro: 0.217, f1-macro: 0.170, f1-weighted: 0.170, , roc-auc: 0.627
########## Hyperparameters combination ##########
(512, 0.4, 0.001, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.171, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.919, Val f1_micro: 0.216
Epoch: 060, Train Loss: 1.745, Val f1_micro: 0.228
Epoch: 080, Train Loss: 1.627, Val f1_micro: 0.229
Epoch: 100, Train Loss: 1.547, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.450, Val f1_micro: 0.246
Epoch: 140, Train Loss: 1.394, Val f1_micro: 0.249
Epoch: 160, Train Loss: 1.327, Val f1_micro: 0.249
Epoch: 180, Train Loss: 1.281, Val f1_micro: 0.259
Epoch: 200, Train Loss: 1.242, Val f1_micro: 0.259
Epoch: 220, Train Loss: 1.206, Val f1_micro: 0.260
Epoch: 240, Train Loss: 1.172, Val f1_micro: 0.265
Epoch: 260, Train Loss: 1.116, Val f1_micro: 0.269
Epoch: 280, Train Loss: 1.092, Val f1_micro: 0.268
Epoch: 300, Train Loss: 1.066, Val f1_micro: 0.276
Epoch: 320, Train Loss: 1.034, Val f1_micro: 0.274
Epoch: 340, Train Loss: 1.030, Val f1_micro: 0.277
Epoch: 360, Train Loss: 0.998, Val f1_micro: 0.279
Epoch: 380, Train Loss: 0.957, Val f1_micro: 0.280
Epoch: 400, Train Loss: 0.917, Val f1_micro: 0.284
Epoch: 420, Train Loss: 0.912, Val f1_micro: 0.285
Epoch: 440, Train Loss: 0.887, Val f1_micro: 0.287
Epoch: 460, Train Loss: 0.876, Val f1_micro: 0.287
Epoch: 480, Train Loss: 0.856, Val f1_micro: 0.288
Epoch: 500, Train Loss: 0.844, Val f1_micro: 0.290
f1-micro: 0.290, f1-macro: 0.283, f1-weighted: 0.286, , roc-auc: 0.682
##### RUN 2 #####
Epoch: 020, Train Loss: 2.184, Val f1_micro: 0.186
Epoch: 040, Train Loss: 1.901, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.738, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.625, Val f1_micro: 0.229
Epoch: 100, Train Loss: 1.541, Val f1_micro: 0.239
Epoch: 120, Train Loss: 1.463, Val f1_micro: 0.242
Epoch: 140, Train Loss: 1.386, Val f1_micro: 0.248
Epoch: 160, Train Loss: 1.347, Val f1_micro: 0.252
Epoch: 180, Train Loss: 1.299, Val f1_micro: 0.260
Epoch: 200, Train Loss: 1.238, Val f1_micro: 0.261
Epoch: 220, Train Loss: 1.199, Val f1_micro: 0.262
Epoch: 240, Train Loss: 1.163, Val f1_micro: 0.264
Epoch: 260, Train Loss: 1.144, Val f1_micro: 0.269
Epoch: 280, Train Loss: 1.100, Val f1_micro: 0.276
Epoch: 300, Train Loss: 1.063, Val f1_micro: 0.274
Epoch: 320, Train Loss: 1.020, Val f1_micro: 0.277
Epoch: 340, Train Loss: 1.024, Val f1_micro: 0.279
Epoch: 360, Train Loss: 0.988, Val f1_micro: 0.279
Epoch: 380, Train Loss: 0.961, Val f1_micro: 0.281
Epoch: 400, Train Loss: 0.928, Val f1_micro: 0.284
Epoch: 420, Train Loss: 0.921, Val f1_micro: 0.285
Epoch: 440, Train Loss: 0.909, Val f1_micro: 0.285
Epoch: 460, Train Loss: 0.855, Val f1_micro: 0.287
Epoch: 480, Train Loss: 0.866, Val f1_micro: 0.290
Epoch: 500, Train Loss: 0.853, Val f1_micro: 0.290
f1-micro: 0.290, f1-macro: 0.283, f1-weighted: 0.286, , roc-auc: 0.682
##### RUN 3 #####
Epoch: 020, Train Loss: 2.171, Val f1_micro: 0.190
Epoch: 040, Train Loss: 1.887, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.732, Val f1_micro: 0.224
Epoch: 080, Train Loss: 1.635, Val f1_micro: 0.229
Epoch: 100, Train Loss: 1.540, Val f1_micro: 0.240
Epoch: 120, Train Loss: 1.462, Val f1_micro: 0.246
Epoch: 140, Train Loss: 1.391, Val f1_micro: 0.248
Epoch: 160, Train Loss: 1.323, Val f1_micro: 0.253
Epoch: 180, Train Loss: 1.294, Val f1_micro: 0.259
Epoch: 200, Train Loss: 1.248, Val f1_micro: 0.263
Epoch: 220, Train Loss: 1.202, Val f1_micro: 0.267
Epoch: 240, Train Loss: 1.170, Val f1_micro: 0.266
Epoch: 260, Train Loss: 1.146, Val f1_micro: 0.268
Epoch: 280, Train Loss: 1.094, Val f1_micro: 0.271
Epoch: 300, Train Loss: 1.055, Val f1_micro: 0.273
Epoch: 320, Train Loss: 1.033, Val f1_micro: 0.274
Epoch: 340, Train Loss: 1.006, Val f1_micro: 0.277
Epoch: 360, Train Loss: 0.975, Val f1_micro: 0.280
Epoch: 380, Train Loss: 0.942, Val f1_micro: 0.283
Epoch: 400, Train Loss: 0.934, Val f1_micro: 0.285
Epoch: 420, Train Loss: 0.904, Val f1_micro: 0.285
Epoch: 440, Train Loss: 0.895, Val f1_micro: 0.284
Epoch: 460, Train Loss: 0.877, Val f1_micro: 0.286
Epoch: 480, Train Loss: 0.849, Val f1_micro: 0.288
Epoch: 500, Train Loss: 0.822, Val f1_micro: 0.290
f1-micro: 0.290, f1-macro: 0.283, f1-weighted: 0.286, , roc-auc: 0.681
##### RUN 4 #####
Epoch: 020, Train Loss: 2.167, Val f1_micro: 0.190
Epoch: 040, Train Loss: 1.902, Val f1_micro: 0.218
Epoch: 060, Train Loss: 1.736, Val f1_micro: 0.222
Epoch: 080, Train Loss: 1.626, Val f1_micro: 0.229
Epoch: 100, Train Loss: 1.530, Val f1_micro: 0.240
Epoch: 120, Train Loss: 1.461, Val f1_micro: 0.247
Epoch: 140, Train Loss: 1.412, Val f1_micro: 0.251
Epoch: 160, Train Loss: 1.338, Val f1_micro: 0.255
Epoch: 180, Train Loss: 1.287, Val f1_micro: 0.257
Epoch: 200, Train Loss: 1.233, Val f1_micro: 0.261
Epoch: 220, Train Loss: 1.176, Val f1_micro: 0.267
Epoch: 240, Train Loss: 1.153, Val f1_micro: 0.263
Epoch: 260, Train Loss: 1.105, Val f1_micro: 0.267
Epoch: 280, Train Loss: 1.112, Val f1_micro: 0.268
Epoch: 300, Train Loss: 1.066, Val f1_micro: 0.274
Epoch: 320, Train Loss: 1.034, Val f1_micro: 0.278
Epoch: 340, Train Loss: 1.003, Val f1_micro: 0.278
Epoch: 360, Train Loss: 0.984, Val f1_micro: 0.278
Epoch: 380, Train Loss: 0.947, Val f1_micro: 0.282
Epoch: 400, Train Loss: 0.949, Val f1_micro: 0.282
Epoch: 420, Train Loss: 0.911, Val f1_micro: 0.285
Epoch: 440, Train Loss: 0.896, Val f1_micro: 0.285
Epoch: 460, Train Loss: 0.852, Val f1_micro: 0.289
Epoch: 480, Train Loss: 0.834, Val f1_micro: 0.288
Epoch: 500, Train Loss: 0.830, Val f1_micro: 0.289
f1-micro: 0.289, f1-macro: 0.282, f1-weighted: 0.285, , roc-auc: 0.682
##### RUN 5 #####
Epoch: 020, Train Loss: 2.175, Val f1_micro: 0.186
Epoch: 040, Train Loss: 1.892, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.728, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.631, Val f1_micro: 0.232
Epoch: 100, Train Loss: 1.537, Val f1_micro: 0.238
Epoch: 120, Train Loss: 1.455, Val f1_micro: 0.244
Epoch: 140, Train Loss: 1.397, Val f1_micro: 0.248
Epoch: 160, Train Loss: 1.344, Val f1_micro: 0.251
Epoch: 180, Train Loss: 1.277, Val f1_micro: 0.256
Epoch: 200, Train Loss: 1.256, Val f1_micro: 0.258
Epoch: 220, Train Loss: 1.216, Val f1_micro: 0.262
Epoch: 240, Train Loss: 1.190, Val f1_micro: 0.266
Epoch: 260, Train Loss: 1.120, Val f1_micro: 0.268
Epoch: 280, Train Loss: 1.096, Val f1_micro: 0.269
Epoch: 300, Train Loss: 1.050, Val f1_micro: 0.275
Epoch: 320, Train Loss: 1.023, Val f1_micro: 0.278
Epoch: 340, Train Loss: 1.018, Val f1_micro: 0.277
Epoch: 360, Train Loss: 0.972, Val f1_micro: 0.277
Epoch: 380, Train Loss: 0.960, Val f1_micro: 0.284
Epoch: 400, Train Loss: 0.935, Val f1_micro: 0.282
Epoch: 420, Train Loss: 0.916, Val f1_micro: 0.285
Epoch: 440, Train Loss: 0.886, Val f1_micro: 0.287
Epoch: 460, Train Loss: 0.868, Val f1_micro: 0.289
Epoch: 480, Train Loss: 0.844, Val f1_micro: 0.291
Epoch: 500, Train Loss: 0.818, Val f1_micro: 0.288
f1-micro: 0.288, f1-macro: 0.281, f1-weighted: 0.284, , roc-auc: 0.682
########## Hyperparameters combination ##########
(512, 0.4, 0.001, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.176, Val f1_micro: 0.188
Epoch: 040, Train Loss: 1.888, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.737, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.638, Val f1_micro: 0.227
Epoch: 100, Train Loss: 1.548, Val f1_micro: 0.235
Epoch: 120, Train Loss: 1.477, Val f1_micro: 0.239
Epoch: 140, Train Loss: 1.412, Val f1_micro: 0.246
Epoch: 160, Train Loss: 1.374, Val f1_micro: 0.244
Epoch: 180, Train Loss: 1.329, Val f1_micro: 0.255
Epoch: 200, Train Loss: 1.284, Val f1_micro: 0.253
Epoch: 220, Train Loss: 1.239, Val f1_micro: 0.260
Epoch: 240, Train Loss: 1.223, Val f1_micro: 0.264
Epoch: 260, Train Loss: 1.167, Val f1_micro: 0.267
Epoch: 280, Train Loss: 1.148, Val f1_micro: 0.269
Epoch: 300, Train Loss: 1.137, Val f1_micro: 0.269
Epoch: 320, Train Loss: 1.126, Val f1_micro: 0.272
Epoch: 340, Train Loss: 1.106, Val f1_micro: 0.270
Epoch: 360, Train Loss: 1.054, Val f1_micro: 0.272
Epoch: 380, Train Loss: 1.046, Val f1_micro: 0.273
Epoch: 400, Train Loss: 1.020, Val f1_micro: 0.276
Epoch: 420, Train Loss: 0.997, Val f1_micro: 0.279
Epoch: 440, Train Loss: 0.978, Val f1_micro: 0.279
Epoch: 460, Train Loss: 0.979, Val f1_micro: 0.279
Epoch: 480, Train Loss: 0.948, Val f1_micro: 0.280
Epoch: 500, Train Loss: 0.921, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.271, f1-weighted: 0.274, , roc-auc: 0.670
##### RUN 2 #####
Epoch: 020, Train Loss: 2.138, Val f1_micro: 0.186
Epoch: 040, Train Loss: 1.903, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.739, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.625, Val f1_micro: 0.225
Epoch: 100, Train Loss: 1.548, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.472, Val f1_micro: 0.234
Epoch: 140, Train Loss: 1.411, Val f1_micro: 0.242
Epoch: 160, Train Loss: 1.374, Val f1_micro: 0.245
Epoch: 180, Train Loss: 1.323, Val f1_micro: 0.254
Epoch: 200, Train Loss: 1.269, Val f1_micro: 0.255
Epoch: 220, Train Loss: 1.251, Val f1_micro: 0.257
Epoch: 240, Train Loss: 1.220, Val f1_micro: 0.264
Epoch: 260, Train Loss: 1.160, Val f1_micro: 0.266
Epoch: 280, Train Loss: 1.171, Val f1_micro: 0.266
Epoch: 300, Train Loss: 1.123, Val f1_micro: 0.267
Epoch: 320, Train Loss: 1.109, Val f1_micro: 0.271
Epoch: 340, Train Loss: 1.071, Val f1_micro: 0.273
Epoch: 360, Train Loss: 1.055, Val f1_micro: 0.272
Epoch: 380, Train Loss: 1.045, Val f1_micro: 0.274
Epoch: 400, Train Loss: 1.026, Val f1_micro: 0.273
Epoch: 420, Train Loss: 0.989, Val f1_micro: 0.274
Epoch: 440, Train Loss: 0.977, Val f1_micro: 0.276
Epoch: 460, Train Loss: 0.981, Val f1_micro: 0.276
Epoch: 480, Train Loss: 0.960, Val f1_micro: 0.277
Epoch: 500, Train Loss: 0.933, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.272, f1-weighted: 0.274, , roc-auc: 0.670
##### RUN 3 #####
Epoch: 020, Train Loss: 2.172, Val f1_micro: 0.186
Epoch: 040, Train Loss: 1.883, Val f1_micro: 0.210
Epoch: 060, Train Loss: 1.746, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.626, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.538, Val f1_micro: 0.234
Epoch: 120, Train Loss: 1.482, Val f1_micro: 0.237
Epoch: 140, Train Loss: 1.396, Val f1_micro: 0.244
Epoch: 160, Train Loss: 1.361, Val f1_micro: 0.247
Epoch: 180, Train Loss: 1.339, Val f1_micro: 0.250
Epoch: 200, Train Loss: 1.280, Val f1_micro: 0.256
Epoch: 220, Train Loss: 1.265, Val f1_micro: 0.257
Epoch: 240, Train Loss: 1.207, Val f1_micro: 0.262
Epoch: 260, Train Loss: 1.186, Val f1_micro: 0.263
Epoch: 280, Train Loss: 1.150, Val f1_micro: 0.265
Epoch: 300, Train Loss: 1.129, Val f1_micro: 0.268
Epoch: 320, Train Loss: 1.117, Val f1_micro: 0.269
Epoch: 340, Train Loss: 1.094, Val f1_micro: 0.272
Epoch: 360, Train Loss: 1.049, Val f1_micro: 0.273
Epoch: 380, Train Loss: 1.037, Val f1_micro: 0.273
Epoch: 400, Train Loss: 1.049, Val f1_micro: 0.274
Epoch: 420, Train Loss: 1.008, Val f1_micro: 0.276
Epoch: 440, Train Loss: 0.995, Val f1_micro: 0.276
Epoch: 460, Train Loss: 0.974, Val f1_micro: 0.279
Epoch: 480, Train Loss: 0.950, Val f1_micro: 0.280
Epoch: 500, Train Loss: 0.947, Val f1_micro: 0.280
f1-micro: 0.280, f1-macro: 0.271, f1-weighted: 0.274, , roc-auc: 0.669
##### RUN 4 #####
Epoch: 020, Train Loss: 2.153, Val f1_micro: 0.180
Epoch: 040, Train Loss: 1.897, Val f1_micro: 0.203
Epoch: 060, Train Loss: 1.750, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.636, Val f1_micro: 0.226
Epoch: 100, Train Loss: 1.547, Val f1_micro: 0.231
Epoch: 120, Train Loss: 1.480, Val f1_micro: 0.237
Epoch: 140, Train Loss: 1.415, Val f1_micro: 0.241
Epoch: 160, Train Loss: 1.367, Val f1_micro: 0.248
Epoch: 180, Train Loss: 1.313, Val f1_micro: 0.251
Epoch: 200, Train Loss: 1.282, Val f1_micro: 0.257
Epoch: 220, Train Loss: 1.253, Val f1_micro: 0.261
Epoch: 240, Train Loss: 1.212, Val f1_micro: 0.259
Epoch: 260, Train Loss: 1.190, Val f1_micro: 0.264
Epoch: 280, Train Loss: 1.164, Val f1_micro: 0.267
Epoch: 300, Train Loss: 1.126, Val f1_micro: 0.267
Epoch: 320, Train Loss: 1.095, Val f1_micro: 0.271
Epoch: 340, Train Loss: 1.079, Val f1_micro: 0.272
Epoch: 360, Train Loss: 1.068, Val f1_micro: 0.274
Epoch: 380, Train Loss: 1.048, Val f1_micro: 0.274
Epoch: 400, Train Loss: 1.016, Val f1_micro: 0.277
Epoch: 420, Train Loss: 1.000, Val f1_micro: 0.279
Epoch: 440, Train Loss: 0.991, Val f1_micro: 0.278
Epoch: 460, Train Loss: 0.972, Val f1_micro: 0.279
Epoch: 480, Train Loss: 0.936, Val f1_micro: 0.281
Epoch: 500, Train Loss: 0.938, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.271, f1-weighted: 0.274, , roc-auc: 0.669
##### RUN 5 #####
Epoch: 020, Train Loss: 2.153, Val f1_micro: 0.184
Epoch: 040, Train Loss: 1.896, Val f1_micro: 0.210
Epoch: 060, Train Loss: 1.739, Val f1_micro: 0.215
Epoch: 080, Train Loss: 1.641, Val f1_micro: 0.226
Epoch: 100, Train Loss: 1.545, Val f1_micro: 0.231
Epoch: 120, Train Loss: 1.461, Val f1_micro: 0.237
Epoch: 140, Train Loss: 1.423, Val f1_micro: 0.242
Epoch: 160, Train Loss: 1.372, Val f1_micro: 0.247
Epoch: 180, Train Loss: 1.335, Val f1_micro: 0.249
Epoch: 200, Train Loss: 1.284, Val f1_micro: 0.256
Epoch: 220, Train Loss: 1.244, Val f1_micro: 0.262
Epoch: 240, Train Loss: 1.228, Val f1_micro: 0.260
Epoch: 260, Train Loss: 1.164, Val f1_micro: 0.264
Epoch: 280, Train Loss: 1.162, Val f1_micro: 0.266
Epoch: 300, Train Loss: 1.147, Val f1_micro: 0.268
Epoch: 320, Train Loss: 1.112, Val f1_micro: 0.270
Epoch: 340, Train Loss: 1.072, Val f1_micro: 0.270
Epoch: 360, Train Loss: 1.079, Val f1_micro: 0.269
Epoch: 380, Train Loss: 1.042, Val f1_micro: 0.270
Epoch: 400, Train Loss: 1.005, Val f1_micro: 0.274
Epoch: 420, Train Loss: 1.007, Val f1_micro: 0.273
Epoch: 440, Train Loss: 1.002, Val f1_micro: 0.276
Epoch: 460, Train Loss: 0.991, Val f1_micro: 0.276
Epoch: 480, Train Loss: 0.952, Val f1_micro: 0.278
Epoch: 500, Train Loss: 0.937, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.272, f1-weighted: 0.275, , roc-auc: 0.669
########## Hyperparameters combination ##########
(512, 0.4, 0.001, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.160, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.891, Val f1_micro: 0.222
Epoch: 060, Train Loss: 1.755, Val f1_micro: 0.234
Epoch: 080, Train Loss: 1.629, Val f1_micro: 0.240
Epoch: 100, Train Loss: 1.562, Val f1_micro: 0.243
Epoch: 120, Train Loss: 1.484, Val f1_micro: 0.250
Epoch: 140, Train Loss: 1.448, Val f1_micro: 0.255
Epoch: 160, Train Loss: 1.368, Val f1_micro: 0.257
Epoch: 180, Train Loss: 1.338, Val f1_micro: 0.258
Epoch: 200, Train Loss: 1.302, Val f1_micro: 0.261
Epoch: 220, Train Loss: 1.285, Val f1_micro: 0.261
Epoch: 240, Train Loss: 1.243, Val f1_micro: 0.261
Epoch: 260, Train Loss: 1.228, Val f1_micro: 0.266
Epoch: 280, Train Loss: 1.211, Val f1_micro: 0.265
Epoch: 300, Train Loss: 1.194, Val f1_micro: 0.268
Epoch: 320, Train Loss: 1.171, Val f1_micro: 0.272
Epoch: 340, Train Loss: 1.139, Val f1_micro: 0.268
Epoch: 360, Train Loss: 1.143, Val f1_micro: 0.270
Epoch: 380, Train Loss: 1.124, Val f1_micro: 0.271
Epoch: 400, Train Loss: 1.109, Val f1_micro: 0.272
Epoch: 420, Train Loss: 1.101, Val f1_micro: 0.273
Epoch: 440, Train Loss: 1.071, Val f1_micro: 0.273
Epoch: 460, Train Loss: 1.085, Val f1_micro: 0.275
Epoch: 480, Train Loss: 1.061, Val f1_micro: 0.277
Epoch: 500, Train Loss: 1.038, Val f1_micro: 0.275
f1-micro: 0.275, f1-macro: 0.263, f1-weighted: 0.266, , roc-auc: 0.673
##### RUN 2 #####
Epoch: 020, Train Loss: 2.158, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.894, Val f1_micro: 0.219
Epoch: 060, Train Loss: 1.756, Val f1_micro: 0.235
Epoch: 080, Train Loss: 1.636, Val f1_micro: 0.240
Epoch: 100, Train Loss: 1.548, Val f1_micro: 0.247
Epoch: 120, Train Loss: 1.492, Val f1_micro: 0.251
Epoch: 140, Train Loss: 1.433, Val f1_micro: 0.253
Epoch: 160, Train Loss: 1.379, Val f1_micro: 0.257
Epoch: 180, Train Loss: 1.336, Val f1_micro: 0.257
Epoch: 200, Train Loss: 1.313, Val f1_micro: 0.261
Epoch: 220, Train Loss: 1.280, Val f1_micro: 0.260
Epoch: 240, Train Loss: 1.250, Val f1_micro: 0.262
Epoch: 260, Train Loss: 1.242, Val f1_micro: 0.266
Epoch: 280, Train Loss: 1.220, Val f1_micro: 0.267
Epoch: 300, Train Loss: 1.200, Val f1_micro: 0.270
Epoch: 320, Train Loss: 1.176, Val f1_micro: 0.268
Epoch: 340, Train Loss: 1.155, Val f1_micro: 0.272
Epoch: 360, Train Loss: 1.128, Val f1_micro: 0.270
Epoch: 380, Train Loss: 1.142, Val f1_micro: 0.271
Epoch: 400, Train Loss: 1.107, Val f1_micro: 0.274
Epoch: 420, Train Loss: 1.098, Val f1_micro: 0.274
Epoch: 440, Train Loss: 1.070, Val f1_micro: 0.275
Epoch: 460, Train Loss: 1.070, Val f1_micro: 0.274
Epoch: 480, Train Loss: 1.057, Val f1_micro: 0.274
Epoch: 500, Train Loss: 1.047, Val f1_micro: 0.273
f1-micro: 0.273, f1-macro: 0.262, f1-weighted: 0.264, , roc-auc: 0.673
##### RUN 3 #####
Epoch: 020, Train Loss: 2.186, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.899, Val f1_micro: 0.219
Epoch: 060, Train Loss: 1.738, Val f1_micro: 0.233
Epoch: 080, Train Loss: 1.634, Val f1_micro: 0.239
Epoch: 100, Train Loss: 1.549, Val f1_micro: 0.247
Epoch: 120, Train Loss: 1.490, Val f1_micro: 0.251
Epoch: 140, Train Loss: 1.429, Val f1_micro: 0.254
Epoch: 160, Train Loss: 1.392, Val f1_micro: 0.257
Epoch: 180, Train Loss: 1.346, Val f1_micro: 0.258
Epoch: 200, Train Loss: 1.318, Val f1_micro: 0.264
Epoch: 220, Train Loss: 1.281, Val f1_micro: 0.263
Epoch: 240, Train Loss: 1.258, Val f1_micro: 0.264
Epoch: 260, Train Loss: 1.231, Val f1_micro: 0.267
Epoch: 280, Train Loss: 1.214, Val f1_micro: 0.268
Epoch: 300, Train Loss: 1.194, Val f1_micro: 0.268
Epoch: 320, Train Loss: 1.166, Val f1_micro: 0.270
Epoch: 340, Train Loss: 1.138, Val f1_micro: 0.269
Epoch: 360, Train Loss: 1.120, Val f1_micro: 0.270
Epoch: 380, Train Loss: 1.125, Val f1_micro: 0.271
Epoch: 400, Train Loss: 1.092, Val f1_micro: 0.273
Epoch: 420, Train Loss: 1.098, Val f1_micro: 0.273
Epoch: 440, Train Loss: 1.079, Val f1_micro: 0.276
Epoch: 460, Train Loss: 1.067, Val f1_micro: 0.276
Epoch: 480, Train Loss: 1.068, Val f1_micro: 0.275
Epoch: 500, Train Loss: 1.045, Val f1_micro: 0.278
f1-micro: 0.278, f1-macro: 0.265, f1-weighted: 0.268, , roc-auc: 0.674
##### RUN 4 #####
Epoch: 020, Train Loss: 2.163, Val f1_micro: 0.190
Epoch: 040, Train Loss: 1.894, Val f1_micro: 0.222
Epoch: 060, Train Loss: 1.738, Val f1_micro: 0.233
Epoch: 080, Train Loss: 1.628, Val f1_micro: 0.239
Epoch: 100, Train Loss: 1.553, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.475, Val f1_micro: 0.250
Epoch: 140, Train Loss: 1.423, Val f1_micro: 0.253
Epoch: 160, Train Loss: 1.375, Val f1_micro: 0.257
Epoch: 180, Train Loss: 1.347, Val f1_micro: 0.259
Epoch: 200, Train Loss: 1.317, Val f1_micro: 0.261
Epoch: 220, Train Loss: 1.284, Val f1_micro: 0.261
Epoch: 240, Train Loss: 1.251, Val f1_micro: 0.265
Epoch: 260, Train Loss: 1.231, Val f1_micro: 0.263
Epoch: 280, Train Loss: 1.207, Val f1_micro: 0.264
Epoch: 300, Train Loss: 1.192, Val f1_micro: 0.267
Epoch: 320, Train Loss: 1.155, Val f1_micro: 0.270
Epoch: 340, Train Loss: 1.132, Val f1_micro: 0.268
Epoch: 360, Train Loss: 1.132, Val f1_micro: 0.268
Epoch: 380, Train Loss: 1.120, Val f1_micro: 0.269
Epoch: 400, Train Loss: 1.111, Val f1_micro: 0.272
Epoch: 420, Train Loss: 1.084, Val f1_micro: 0.273
Epoch: 440, Train Loss: 1.081, Val f1_micro: 0.274
Epoch: 460, Train Loss: 1.063, Val f1_micro: 0.274
Epoch: 480, Train Loss: 1.052, Val f1_micro: 0.275
Epoch: 500, Train Loss: 1.048, Val f1_micro: 0.276
f1-micro: 0.276, f1-macro: 0.263, f1-weighted: 0.265, , roc-auc: 0.673
##### RUN 5 #####
Epoch: 020, Train Loss: 2.181, Val f1_micro: 0.194
Epoch: 040, Train Loss: 1.884, Val f1_micro: 0.219
Epoch: 060, Train Loss: 1.747, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.630, Val f1_micro: 0.237
Epoch: 100, Train Loss: 1.557, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.496, Val f1_micro: 0.250
Epoch: 140, Train Loss: 1.422, Val f1_micro: 0.253
Epoch: 160, Train Loss: 1.389, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.350, Val f1_micro: 0.258
Epoch: 200, Train Loss: 1.317, Val f1_micro: 0.260
Epoch: 220, Train Loss: 1.273, Val f1_micro: 0.263
Epoch: 240, Train Loss: 1.260, Val f1_micro: 0.264
Epoch: 260, Train Loss: 1.235, Val f1_micro: 0.266
Epoch: 280, Train Loss: 1.221, Val f1_micro: 0.269
Epoch: 300, Train Loss: 1.186, Val f1_micro: 0.268
Epoch: 320, Train Loss: 1.155, Val f1_micro: 0.269
Epoch: 340, Train Loss: 1.147, Val f1_micro: 0.270
Epoch: 360, Train Loss: 1.139, Val f1_micro: 0.271
Epoch: 380, Train Loss: 1.130, Val f1_micro: 0.271
Epoch: 400, Train Loss: 1.099, Val f1_micro: 0.272
Epoch: 420, Train Loss: 1.093, Val f1_micro: 0.274
Epoch: 440, Train Loss: 1.072, Val f1_micro: 0.277
Epoch: 460, Train Loss: 1.064, Val f1_micro: 0.276
Epoch: 480, Train Loss: 1.041, Val f1_micro: 0.276
Epoch: 500, Train Loss: 1.032, Val f1_micro: 0.277
f1-micro: 0.277, f1-macro: 0.264, f1-weighted: 0.267, , roc-auc: 0.674
########## Hyperparameters combination ##########
(512, 0.4, 0.001, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.187, Val f1_micro: 0.186
Epoch: 040, Train Loss: 1.920, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.792, Val f1_micro: 0.222
Epoch: 080, Train Loss: 1.704, Val f1_micro: 0.221
Epoch: 100, Train Loss: 1.652, Val f1_micro: 0.225
Epoch: 120, Train Loss: 1.610, Val f1_micro: 0.231
Epoch: 140, Train Loss: 1.601, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.583, Val f1_micro: 0.232
Epoch: 180, Train Loss: 1.562, Val f1_micro: 0.236
Epoch: 200, Train Loss: 1.543, Val f1_micro: 0.237
Epoch: 220, Train Loss: 1.533, Val f1_micro: 0.235
Epoch: 240, Train Loss: 1.526, Val f1_micro: 0.233
Epoch: 260, Train Loss: 1.533, Val f1_micro: 0.235
Epoch: 280, Train Loss: 1.526, Val f1_micro: 0.234
Epoch: 300, Train Loss: 1.516, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.514, Val f1_micro: 0.233
Epoch: 340, Train Loss: 1.528, Val f1_micro: 0.233
Epoch: 360, Train Loss: 1.521, Val f1_micro: 0.235
Epoch: 380, Train Loss: 1.534, Val f1_micro: 0.233
Epoch: 400, Train Loss: 1.525, Val f1_micro: 0.233
Epoch: 420, Train Loss: 1.538, Val f1_micro: 0.237
Epoch: 440, Train Loss: 1.533, Val f1_micro: 0.232
Epoch: 460, Train Loss: 1.520, Val f1_micro: 0.234
Epoch: 480, Train Loss: 1.533, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.532, Val f1_micro: 0.234
f1-micro: 0.234, f1-macro: 0.205, f1-weighted: 0.207, , roc-auc: 0.654
##### RUN 2 #####
Epoch: 020, Train Loss: 2.177, Val f1_micro: 0.188
Epoch: 040, Train Loss: 1.923, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.788, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.716, Val f1_micro: 0.222
Epoch: 100, Train Loss: 1.652, Val f1_micro: 0.229
Epoch: 120, Train Loss: 1.616, Val f1_micro: 0.232
Epoch: 140, Train Loss: 1.590, Val f1_micro: 0.232
Epoch: 160, Train Loss: 1.577, Val f1_micro: 0.237
Epoch: 180, Train Loss: 1.543, Val f1_micro: 0.236
Epoch: 200, Train Loss: 1.557, Val f1_micro: 0.238
Epoch: 220, Train Loss: 1.533, Val f1_micro: 0.235
Epoch: 240, Train Loss: 1.531, Val f1_micro: 0.233
Epoch: 260, Train Loss: 1.532, Val f1_micro: 0.234
Epoch: 280, Train Loss: 1.540, Val f1_micro: 0.239
Epoch: 300, Train Loss: 1.517, Val f1_micro: 0.234
Epoch: 320, Train Loss: 1.524, Val f1_micro: 0.237
Epoch: 340, Train Loss: 1.533, Val f1_micro: 0.232
Epoch: 360, Train Loss: 1.524, Val f1_micro: 0.233
Epoch: 380, Train Loss: 1.528, Val f1_micro: 0.231
Epoch: 400, Train Loss: 1.525, Val f1_micro: 0.235
Epoch: 420, Train Loss: 1.526, Val f1_micro: 0.235
Epoch: 440, Train Loss: 1.526, Val f1_micro: 0.234
Epoch: 460, Train Loss: 1.528, Val f1_micro: 0.231
Epoch: 480, Train Loss: 1.538, Val f1_micro: 0.237
Epoch: 500, Train Loss: 1.548, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.201, f1-weighted: 0.203, , roc-auc: 0.654
##### RUN 3 #####
Epoch: 020, Train Loss: 2.195, Val f1_micro: 0.187
Epoch: 040, Train Loss: 1.914, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.783, Val f1_micro: 0.222
Epoch: 080, Train Loss: 1.704, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.664, Val f1_micro: 0.223
Epoch: 120, Train Loss: 1.619, Val f1_micro: 0.228
Epoch: 140, Train Loss: 1.590, Val f1_micro: 0.232
Epoch: 160, Train Loss: 1.571, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.553, Val f1_micro: 0.233
Epoch: 200, Train Loss: 1.550, Val f1_micro: 0.234
Epoch: 220, Train Loss: 1.537, Val f1_micro: 0.235
Epoch: 240, Train Loss: 1.537, Val f1_micro: 0.239
Epoch: 260, Train Loss: 1.535, Val f1_micro: 0.238
Epoch: 280, Train Loss: 1.540, Val f1_micro: 0.240
Epoch: 300, Train Loss: 1.543, Val f1_micro: 0.237
Epoch: 320, Train Loss: 1.528, Val f1_micro: 0.234
Epoch: 340, Train Loss: 1.532, Val f1_micro: 0.235
Epoch: 360, Train Loss: 1.528, Val f1_micro: 0.234
Epoch: 380, Train Loss: 1.533, Val f1_micro: 0.232
Epoch: 400, Train Loss: 1.528, Val f1_micro: 0.233
Epoch: 420, Train Loss: 1.534, Val f1_micro: 0.234
Epoch: 440, Train Loss: 1.534, Val f1_micro: 0.231
Epoch: 460, Train Loss: 1.536, Val f1_micro: 0.234
Epoch: 480, Train Loss: 1.524, Val f1_micro: 0.233
Epoch: 500, Train Loss: 1.539, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.202, f1-weighted: 0.204, , roc-auc: 0.654
##### RUN 4 #####
Epoch: 020, Train Loss: 2.165, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.913, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.780, Val f1_micro: 0.221
Epoch: 080, Train Loss: 1.707, Val f1_micro: 0.219
Epoch: 100, Train Loss: 1.650, Val f1_micro: 0.227
Epoch: 120, Train Loss: 1.614, Val f1_micro: 0.228
Epoch: 140, Train Loss: 1.602, Val f1_micro: 0.234
Epoch: 160, Train Loss: 1.561, Val f1_micro: 0.234
Epoch: 180, Train Loss: 1.563, Val f1_micro: 0.237
Epoch: 200, Train Loss: 1.553, Val f1_micro: 0.241
Epoch: 220, Train Loss: 1.535, Val f1_micro: 0.236
Epoch: 240, Train Loss: 1.533, Val f1_micro: 0.239
Epoch: 260, Train Loss: 1.530, Val f1_micro: 0.234
Epoch: 280, Train Loss: 1.531, Val f1_micro: 0.235
Epoch: 300, Train Loss: 1.528, Val f1_micro: 0.236
Epoch: 320, Train Loss: 1.532, Val f1_micro: 0.233
Epoch: 340, Train Loss: 1.530, Val f1_micro: 0.236
Epoch: 360, Train Loss: 1.520, Val f1_micro: 0.232
Epoch: 380, Train Loss: 1.517, Val f1_micro: 0.232
Epoch: 400, Train Loss: 1.525, Val f1_micro: 0.234
Epoch: 420, Train Loss: 1.530, Val f1_micro: 0.231
Epoch: 440, Train Loss: 1.532, Val f1_micro: 0.233
Epoch: 460, Train Loss: 1.523, Val f1_micro: 0.234
Epoch: 480, Train Loss: 1.542, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.552, Val f1_micro: 0.226
f1-micro: 0.226, f1-macro: 0.198, f1-weighted: 0.199, , roc-auc: 0.654
##### RUN 5 #####
Epoch: 020, Train Loss: 2.193, Val f1_micro: 0.184
Epoch: 040, Train Loss: 1.915, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.781, Val f1_micro: 0.218
Epoch: 080, Train Loss: 1.724, Val f1_micro: 0.224
Epoch: 100, Train Loss: 1.655, Val f1_micro: 0.227
Epoch: 120, Train Loss: 1.615, Val f1_micro: 0.224
Epoch: 140, Train Loss: 1.596, Val f1_micro: 0.233
Epoch: 160, Train Loss: 1.566, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.557, Val f1_micro: 0.233
Epoch: 200, Train Loss: 1.551, Val f1_micro: 0.237
Epoch: 220, Train Loss: 1.544, Val f1_micro: 0.234
Epoch: 240, Train Loss: 1.528, Val f1_micro: 0.234
Epoch: 260, Train Loss: 1.529, Val f1_micro: 0.235
Epoch: 280, Train Loss: 1.521, Val f1_micro: 0.235
Epoch: 300, Train Loss: 1.518, Val f1_micro: 0.234
Epoch: 320, Train Loss: 1.530, Val f1_micro: 0.236
Epoch: 340, Train Loss: 1.521, Val f1_micro: 0.235
Epoch: 360, Train Loss: 1.532, Val f1_micro: 0.232
Epoch: 380, Train Loss: 1.526, Val f1_micro: 0.230
Epoch: 400, Train Loss: 1.525, Val f1_micro: 0.233
Epoch: 420, Train Loss: 1.524, Val f1_micro: 0.235
Epoch: 440, Train Loss: 1.531, Val f1_micro: 0.234
Epoch: 460, Train Loss: 1.530, Val f1_micro: 0.234
Epoch: 480, Train Loss: 1.544, Val f1_micro: 0.238
Epoch: 500, Train Loss: 1.536, Val f1_micro: 0.231
f1-micro: 0.231, f1-macro: 0.201, f1-weighted: 0.203, , roc-auc: 0.654
########## Hyperparameters combination ##########
(512, 0.4, 0.005, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.648, Val f1_micro: 0.225
Epoch: 040, Train Loss: 1.371, Val f1_micro: 0.251
Epoch: 060, Train Loss: 1.204, Val f1_micro: 0.269
Epoch: 080, Train Loss: 1.061, Val f1_micro: 0.278
Epoch: 100, Train Loss: 0.963, Val f1_micro: 0.282
Epoch: 120, Train Loss: 0.874, Val f1_micro: 0.287
Epoch: 140, Train Loss: 0.804, Val f1_micro: 0.290
Epoch: 160, Train Loss: 0.751, Val f1_micro: 0.297
Epoch: 180, Train Loss: 0.690, Val f1_micro: 0.298
Epoch: 200, Train Loss: 0.642, Val f1_micro: 0.300
Epoch: 220, Train Loss: 0.610, Val f1_micro: 0.303
Epoch: 240, Train Loss: 0.567, Val f1_micro: 0.307
Epoch: 260, Train Loss: 0.528, Val f1_micro: 0.307
Epoch: 280, Train Loss: 0.489, Val f1_micro: 0.311
Epoch: 300, Train Loss: 0.435, Val f1_micro: 0.318
Epoch: 320, Train Loss: 0.434, Val f1_micro: 0.313
Epoch: 340, Train Loss: 0.391, Val f1_micro: 0.316
Epoch: 360, Train Loss: 0.377, Val f1_micro: 0.318
Epoch: 380, Train Loss: 0.370, Val f1_micro: 0.319
Epoch: 400, Train Loss: 0.356, Val f1_micro: 0.320
Epoch: 420, Train Loss: 0.303, Val f1_micro: 0.318
Epoch: 440, Train Loss: 0.321, Val f1_micro: 0.321
Epoch: 460, Train Loss: 0.293, Val f1_micro: 0.322
Epoch: 480, Train Loss: 0.280, Val f1_micro: 0.321
Epoch: 500, Train Loss: 0.259, Val f1_micro: 0.321
f1-micro: 0.321, f1-macro: 0.313, f1-weighted: 0.321, , roc-auc: 0.689
##### RUN 2 #####
Epoch: 020, Train Loss: 1.662, Val f1_micro: 0.224
Epoch: 040, Train Loss: 1.362, Val f1_micro: 0.251
Epoch: 060, Train Loss: 1.206, Val f1_micro: 0.271
Epoch: 080, Train Loss: 1.067, Val f1_micro: 0.273
Epoch: 100, Train Loss: 0.963, Val f1_micro: 0.281
Epoch: 120, Train Loss: 0.885, Val f1_micro: 0.287
Epoch: 140, Train Loss: 0.807, Val f1_micro: 0.292
Epoch: 160, Train Loss: 0.747, Val f1_micro: 0.295
Epoch: 180, Train Loss: 0.690, Val f1_micro: 0.300
Epoch: 200, Train Loss: 0.629, Val f1_micro: 0.304
Epoch: 220, Train Loss: 0.584, Val f1_micro: 0.306
Epoch: 240, Train Loss: 0.559, Val f1_micro: 0.308
Epoch: 260, Train Loss: 0.505, Val f1_micro: 0.309
Epoch: 280, Train Loss: 0.479, Val f1_micro: 0.310
Epoch: 300, Train Loss: 0.441, Val f1_micro: 0.313
Epoch: 320, Train Loss: 0.423, Val f1_micro: 0.316
Epoch: 340, Train Loss: 0.394, Val f1_micro: 0.319
Epoch: 360, Train Loss: 0.394, Val f1_micro: 0.317
Epoch: 380, Train Loss: 0.346, Val f1_micro: 0.317
Epoch: 400, Train Loss: 0.325, Val f1_micro: 0.315
Epoch: 420, Train Loss: 0.334, Val f1_micro: 0.320
Epoch: 440, Train Loss: 0.301, Val f1_micro: 0.320
Epoch: 460, Train Loss: 0.300, Val f1_micro: 0.324
Epoch: 480, Train Loss: 0.289, Val f1_micro: 0.321
Epoch: 500, Train Loss: 0.275, Val f1_micro: 0.322
f1-micro: 0.322, f1-macro: 0.313, f1-weighted: 0.321, , roc-auc: 0.690
##### RUN 3 #####
Epoch: 020, Train Loss: 1.635, Val f1_micro: 0.225
Epoch: 040, Train Loss: 1.360, Val f1_micro: 0.248
Epoch: 060, Train Loss: 1.207, Val f1_micro: 0.265
Epoch: 080, Train Loss: 1.064, Val f1_micro: 0.276
Epoch: 100, Train Loss: 0.963, Val f1_micro: 0.283
Epoch: 120, Train Loss: 0.890, Val f1_micro: 0.287
Epoch: 140, Train Loss: 0.811, Val f1_micro: 0.294
Epoch: 160, Train Loss: 0.739, Val f1_micro: 0.294
Epoch: 180, Train Loss: 0.693, Val f1_micro: 0.294
Epoch: 200, Train Loss: 0.640, Val f1_micro: 0.301
Epoch: 220, Train Loss: 0.610, Val f1_micro: 0.303
Epoch: 240, Train Loss: 0.552, Val f1_micro: 0.307
Epoch: 260, Train Loss: 0.512, Val f1_micro: 0.309
Epoch: 280, Train Loss: 0.487, Val f1_micro: 0.312
Epoch: 300, Train Loss: 0.448, Val f1_micro: 0.313
Epoch: 320, Train Loss: 0.412, Val f1_micro: 0.314
Epoch: 340, Train Loss: 0.401, Val f1_micro: 0.315
Epoch: 360, Train Loss: 0.391, Val f1_micro: 0.313
Epoch: 380, Train Loss: 0.362, Val f1_micro: 0.319
Epoch: 400, Train Loss: 0.320, Val f1_micro: 0.317
Epoch: 420, Train Loss: 0.321, Val f1_micro: 0.319
Epoch: 440, Train Loss: 0.336, Val f1_micro: 0.322
Epoch: 460, Train Loss: 0.288, Val f1_micro: 0.317
Epoch: 480, Train Loss: 0.273, Val f1_micro: 0.318
Epoch: 500, Train Loss: 0.286, Val f1_micro: 0.319
f1-micro: 0.319, f1-macro: 0.312, f1-weighted: 0.319, , roc-auc: 0.688
##### RUN 4 #####
Epoch: 020, Train Loss: 1.640, Val f1_micro: 0.228
Epoch: 040, Train Loss: 1.385, Val f1_micro: 0.252
Epoch: 060, Train Loss: 1.196, Val f1_micro: 0.264
Epoch: 080, Train Loss: 1.063, Val f1_micro: 0.276
Epoch: 100, Train Loss: 0.964, Val f1_micro: 0.278
Epoch: 120, Train Loss: 0.886, Val f1_micro: 0.286
Epoch: 140, Train Loss: 0.814, Val f1_micro: 0.291
Epoch: 160, Train Loss: 0.746, Val f1_micro: 0.295
Epoch: 180, Train Loss: 0.678, Val f1_micro: 0.298
Epoch: 200, Train Loss: 0.633, Val f1_micro: 0.299
Epoch: 220, Train Loss: 0.593, Val f1_micro: 0.303
Epoch: 240, Train Loss: 0.553, Val f1_micro: 0.305
Epoch: 260, Train Loss: 0.516, Val f1_micro: 0.307
Epoch: 280, Train Loss: 0.456, Val f1_micro: 0.309
Epoch: 300, Train Loss: 0.445, Val f1_micro: 0.311
Epoch: 320, Train Loss: 0.428, Val f1_micro: 0.312
Epoch: 340, Train Loss: 0.406, Val f1_micro: 0.315
Epoch: 360, Train Loss: 0.396, Val f1_micro: 0.317
Epoch: 380, Train Loss: 0.369, Val f1_micro: 0.315
Epoch: 400, Train Loss: 0.325, Val f1_micro: 0.319
Epoch: 420, Train Loss: 0.324, Val f1_micro: 0.318
Epoch: 440, Train Loss: 0.329, Val f1_micro: 0.320
Epoch: 460, Train Loss: 0.295, Val f1_micro: 0.321
Epoch: 480, Train Loss: 0.284, Val f1_micro: 0.323
Epoch: 500, Train Loss: 0.278, Val f1_micro: 0.319
f1-micro: 0.319, f1-macro: 0.312, f1-weighted: 0.320, , roc-auc: 0.689
##### RUN 5 #####
Epoch: 020, Train Loss: 1.659, Val f1_micro: 0.223
Epoch: 040, Train Loss: 1.353, Val f1_micro: 0.245
Epoch: 060, Train Loss: 1.178, Val f1_micro: 0.268
Epoch: 080, Train Loss: 1.070, Val f1_micro: 0.270
Epoch: 100, Train Loss: 0.955, Val f1_micro: 0.281
Epoch: 120, Train Loss: 0.853, Val f1_micro: 0.284
Epoch: 140, Train Loss: 0.798, Val f1_micro: 0.291
Epoch: 160, Train Loss: 0.751, Val f1_micro: 0.295
Epoch: 180, Train Loss: 0.689, Val f1_micro: 0.298
Epoch: 200, Train Loss: 0.640, Val f1_micro: 0.303
Epoch: 220, Train Loss: 0.594, Val f1_micro: 0.303
Epoch: 240, Train Loss: 0.545, Val f1_micro: 0.304
Epoch: 260, Train Loss: 0.508, Val f1_micro: 0.306
Epoch: 280, Train Loss: 0.464, Val f1_micro: 0.311
Epoch: 300, Train Loss: 0.449, Val f1_micro: 0.315
Epoch: 320, Train Loss: 0.417, Val f1_micro: 0.316
Epoch: 340, Train Loss: 0.392, Val f1_micro: 0.317
Epoch: 360, Train Loss: 0.398, Val f1_micro: 0.316
Epoch: 380, Train Loss: 0.373, Val f1_micro: 0.318
Epoch: 400, Train Loss: 0.358, Val f1_micro: 0.318
Epoch: 420, Train Loss: 0.331, Val f1_micro: 0.321
Epoch: 440, Train Loss: 0.312, Val f1_micro: 0.324
Epoch: 460, Train Loss: 0.292, Val f1_micro: 0.323
Epoch: 480, Train Loss: 0.275, Val f1_micro: 0.323
Epoch: 500, Train Loss: 0.273, Val f1_micro: 0.322
f1-micro: 0.322, f1-macro: 0.315, f1-weighted: 0.323, , roc-auc: 0.689
########## Hyperparameters combination ##########
(512, 0.4, 0.005, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.687, Val f1_micro: 0.225
Epoch: 040, Train Loss: 1.391, Val f1_micro: 0.249
Epoch: 060, Train Loss: 1.245, Val f1_micro: 0.265
Epoch: 080, Train Loss: 1.135, Val f1_micro: 0.270
Epoch: 100, Train Loss: 1.061, Val f1_micro: 0.273
Epoch: 120, Train Loss: 0.984, Val f1_micro: 0.273
Epoch: 140, Train Loss: 0.936, Val f1_micro: 0.280
Epoch: 160, Train Loss: 0.888, Val f1_micro: 0.288
Epoch: 180, Train Loss: 0.839, Val f1_micro: 0.287
Epoch: 200, Train Loss: 0.812, Val f1_micro: 0.289
Epoch: 220, Train Loss: 0.799, Val f1_micro: 0.289
Epoch: 240, Train Loss: 0.747, Val f1_micro: 0.293
Epoch: 260, Train Loss: 0.733, Val f1_micro: 0.294
Epoch: 280, Train Loss: 0.706, Val f1_micro: 0.299
Epoch: 300, Train Loss: 0.695, Val f1_micro: 0.300
Epoch: 320, Train Loss: 0.657, Val f1_micro: 0.301
Epoch: 340, Train Loss: 0.640, Val f1_micro: 0.300
Epoch: 360, Train Loss: 0.664, Val f1_micro: 0.300
Epoch: 380, Train Loss: 0.614, Val f1_micro: 0.308
Epoch: 400, Train Loss: 0.605, Val f1_micro: 0.302
Epoch: 420, Train Loss: 0.594, Val f1_micro: 0.302
Epoch: 440, Train Loss: 0.575, Val f1_micro: 0.306
Epoch: 460, Train Loss: 0.565, Val f1_micro: 0.305
Epoch: 480, Train Loss: 0.564, Val f1_micro: 0.309
Epoch: 500, Train Loss: 0.544, Val f1_micro: 0.309
f1-micro: 0.309, f1-macro: 0.304, f1-weighted: 0.310, , roc-auc: 0.677
##### RUN 2 #####
Epoch: 020, Train Loss: 1.666, Val f1_micro: 0.222
Epoch: 040, Train Loss: 1.377, Val f1_micro: 0.252
Epoch: 060, Train Loss: 1.226, Val f1_micro: 0.259
Epoch: 080, Train Loss: 1.133, Val f1_micro: 0.268
Epoch: 100, Train Loss: 1.056, Val f1_micro: 0.272
Epoch: 120, Train Loss: 1.002, Val f1_micro: 0.279
Epoch: 140, Train Loss: 0.930, Val f1_micro: 0.282
Epoch: 160, Train Loss: 0.909, Val f1_micro: 0.287
Epoch: 180, Train Loss: 0.846, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.815, Val f1_micro: 0.286
Epoch: 220, Train Loss: 0.793, Val f1_micro: 0.291
Epoch: 240, Train Loss: 0.760, Val f1_micro: 0.290
Epoch: 260, Train Loss: 0.725, Val f1_micro: 0.292
Epoch: 280, Train Loss: 0.697, Val f1_micro: 0.298
Epoch: 300, Train Loss: 0.703, Val f1_micro: 0.298
Epoch: 320, Train Loss: 0.684, Val f1_micro: 0.303
Epoch: 340, Train Loss: 0.643, Val f1_micro: 0.301
Epoch: 360, Train Loss: 0.637, Val f1_micro: 0.302
Epoch: 380, Train Loss: 0.631, Val f1_micro: 0.302
Epoch: 400, Train Loss: 0.601, Val f1_micro: 0.302
Epoch: 420, Train Loss: 0.589, Val f1_micro: 0.305
Epoch: 440, Train Loss: 0.602, Val f1_micro: 0.303
Epoch: 460, Train Loss: 0.566, Val f1_micro: 0.305
Epoch: 480, Train Loss: 0.580, Val f1_micro: 0.307
Epoch: 500, Train Loss: 0.538, Val f1_micro: 0.305
f1-micro: 0.305, f1-macro: 0.298, f1-weighted: 0.304, , roc-auc: 0.677
##### RUN 3 #####
Epoch: 020, Train Loss: 1.660, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.406, Val f1_micro: 0.248
Epoch: 060, Train Loss: 1.259, Val f1_micro: 0.263
Epoch: 080, Train Loss: 1.142, Val f1_micro: 0.267
Epoch: 100, Train Loss: 1.052, Val f1_micro: 0.271
Epoch: 120, Train Loss: 0.992, Val f1_micro: 0.278
Epoch: 140, Train Loss: 0.945, Val f1_micro: 0.281
Epoch: 160, Train Loss: 0.883, Val f1_micro: 0.283
Epoch: 180, Train Loss: 0.854, Val f1_micro: 0.285
Epoch: 200, Train Loss: 0.795, Val f1_micro: 0.289
Epoch: 220, Train Loss: 0.781, Val f1_micro: 0.292
Epoch: 240, Train Loss: 0.760, Val f1_micro: 0.289
Epoch: 260, Train Loss: 0.728, Val f1_micro: 0.296
Epoch: 280, Train Loss: 0.723, Val f1_micro: 0.299
Epoch: 300, Train Loss: 0.690, Val f1_micro: 0.300
Epoch: 320, Train Loss: 0.670, Val f1_micro: 0.302
Epoch: 340, Train Loss: 0.660, Val f1_micro: 0.301
Epoch: 360, Train Loss: 0.638, Val f1_micro: 0.302
Epoch: 380, Train Loss: 0.624, Val f1_micro: 0.304
Epoch: 400, Train Loss: 0.607, Val f1_micro: 0.303
Epoch: 420, Train Loss: 0.595, Val f1_micro: 0.308
Epoch: 440, Train Loss: 0.570, Val f1_micro: 0.307
Epoch: 460, Train Loss: 0.574, Val f1_micro: 0.306
Epoch: 480, Train Loss: 0.571, Val f1_micro: 0.307
Epoch: 500, Train Loss: 0.549, Val f1_micro: 0.308
f1-micro: 0.308, f1-macro: 0.302, f1-weighted: 0.308, , roc-auc: 0.679
##### RUN 4 #####
Epoch: 020, Train Loss: 1.678, Val f1_micro: 0.226
Epoch: 040, Train Loss: 1.399, Val f1_micro: 0.247
Epoch: 060, Train Loss: 1.256, Val f1_micro: 0.263
Epoch: 080, Train Loss: 1.141, Val f1_micro: 0.274
Epoch: 100, Train Loss: 1.061, Val f1_micro: 0.272
Epoch: 120, Train Loss: 0.992, Val f1_micro: 0.277
Epoch: 140, Train Loss: 0.914, Val f1_micro: 0.279
Epoch: 160, Train Loss: 0.883, Val f1_micro: 0.283
Epoch: 180, Train Loss: 0.840, Val f1_micro: 0.284
Epoch: 200, Train Loss: 0.813, Val f1_micro: 0.289
Epoch: 220, Train Loss: 0.784, Val f1_micro: 0.289
Epoch: 240, Train Loss: 0.745, Val f1_micro: 0.295
Epoch: 260, Train Loss: 0.730, Val f1_micro: 0.291
Epoch: 280, Train Loss: 0.701, Val f1_micro: 0.299
Epoch: 300, Train Loss: 0.679, Val f1_micro: 0.296
Epoch: 320, Train Loss: 0.659, Val f1_micro: 0.301
Epoch: 340, Train Loss: 0.646, Val f1_micro: 0.301
Epoch: 360, Train Loss: 0.644, Val f1_micro: 0.302
Epoch: 380, Train Loss: 0.604, Val f1_micro: 0.301
Epoch: 400, Train Loss: 0.597, Val f1_micro: 0.304
Epoch: 420, Train Loss: 0.605, Val f1_micro: 0.301
Epoch: 440, Train Loss: 0.572, Val f1_micro: 0.304
Epoch: 460, Train Loss: 0.566, Val f1_micro: 0.306
Epoch: 480, Train Loss: 0.562, Val f1_micro: 0.306
Epoch: 500, Train Loss: 0.552, Val f1_micro: 0.308
f1-micro: 0.308, f1-macro: 0.303, f1-weighted: 0.309, , roc-auc: 0.678
##### RUN 5 #####
Epoch: 020, Train Loss: 1.675, Val f1_micro: 0.224
Epoch: 040, Train Loss: 1.385, Val f1_micro: 0.247
Epoch: 060, Train Loss: 1.244, Val f1_micro: 0.263
Epoch: 080, Train Loss: 1.116, Val f1_micro: 0.270
Epoch: 100, Train Loss: 1.054, Val f1_micro: 0.274
Epoch: 120, Train Loss: 0.986, Val f1_micro: 0.271
Epoch: 140, Train Loss: 0.930, Val f1_micro: 0.282
Epoch: 160, Train Loss: 0.873, Val f1_micro: 0.287
Epoch: 180, Train Loss: 0.851, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.810, Val f1_micro: 0.286
Epoch: 220, Train Loss: 0.780, Val f1_micro: 0.293
Epoch: 240, Train Loss: 0.762, Val f1_micro: 0.289
Epoch: 260, Train Loss: 0.752, Val f1_micro: 0.295
Epoch: 280, Train Loss: 0.701, Val f1_micro: 0.295
Epoch: 300, Train Loss: 0.686, Val f1_micro: 0.298
Epoch: 320, Train Loss: 0.668, Val f1_micro: 0.299
Epoch: 340, Train Loss: 0.644, Val f1_micro: 0.302
Epoch: 360, Train Loss: 0.632, Val f1_micro: 0.303
Epoch: 380, Train Loss: 0.639, Val f1_micro: 0.301
Epoch: 400, Train Loss: 0.618, Val f1_micro: 0.304
Epoch: 420, Train Loss: 0.584, Val f1_micro: 0.307
Epoch: 440, Train Loss: 0.578, Val f1_micro: 0.304
Epoch: 460, Train Loss: 0.561, Val f1_micro: 0.309
Epoch: 480, Train Loss: 0.559, Val f1_micro: 0.306
Epoch: 500, Train Loss: 0.563, Val f1_micro: 0.306
f1-micro: 0.306, f1-macro: 0.300, f1-weighted: 0.306, , roc-auc: 0.678
########## Hyperparameters combination ##########
(512, 0.4, 0.005, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.680, Val f1_micro: 0.236
Epoch: 040, Train Loss: 1.408, Val f1_micro: 0.250
Epoch: 060, Train Loss: 1.286, Val f1_micro: 0.259
Epoch: 080, Train Loss: 1.212, Val f1_micro: 0.271
Epoch: 100, Train Loss: 1.148, Val f1_micro: 0.271
Epoch: 120, Train Loss: 1.095, Val f1_micro: 0.279
Epoch: 140, Train Loss: 1.057, Val f1_micro: 0.283
Epoch: 160, Train Loss: 1.015, Val f1_micro: 0.285
Epoch: 180, Train Loss: 1.002, Val f1_micro: 0.289
Epoch: 200, Train Loss: 0.969, Val f1_micro: 0.294
Epoch: 220, Train Loss: 0.947, Val f1_micro: 0.290
Epoch: 240, Train Loss: 0.919, Val f1_micro: 0.289
Epoch: 260, Train Loss: 0.898, Val f1_micro: 0.292
Epoch: 280, Train Loss: 0.872, Val f1_micro: 0.294
Epoch: 300, Train Loss: 0.882, Val f1_micro: 0.293
Epoch: 320, Train Loss: 0.857, Val f1_micro: 0.297
Epoch: 340, Train Loss: 0.861, Val f1_micro: 0.296
Epoch: 360, Train Loss: 0.826, Val f1_micro: 0.295
Epoch: 380, Train Loss: 0.824, Val f1_micro: 0.294
Epoch: 400, Train Loss: 0.814, Val f1_micro: 0.297
Epoch: 420, Train Loss: 0.822, Val f1_micro: 0.296
Epoch: 440, Train Loss: 0.807, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.813, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.793, Val f1_micro: 0.299
Epoch: 500, Train Loss: 0.790, Val f1_micro: 0.301
f1-micro: 0.301, f1-macro: 0.291, f1-weighted: 0.297, , roc-auc: 0.676
##### RUN 2 #####
Epoch: 020, Train Loss: 1.665, Val f1_micro: 0.242
Epoch: 040, Train Loss: 1.423, Val f1_micro: 0.255
Epoch: 060, Train Loss: 1.278, Val f1_micro: 0.263
Epoch: 080, Train Loss: 1.198, Val f1_micro: 0.271
Epoch: 100, Train Loss: 1.150, Val f1_micro: 0.273
Epoch: 120, Train Loss: 1.105, Val f1_micro: 0.272
Epoch: 140, Train Loss: 1.046, Val f1_micro: 0.281
Epoch: 160, Train Loss: 1.008, Val f1_micro: 0.285
Epoch: 180, Train Loss: 0.992, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.975, Val f1_micro: 0.287
Epoch: 220, Train Loss: 0.938, Val f1_micro: 0.287
Epoch: 240, Train Loss: 0.918, Val f1_micro: 0.292
Epoch: 260, Train Loss: 0.897, Val f1_micro: 0.288
Epoch: 280, Train Loss: 0.890, Val f1_micro: 0.294
Epoch: 300, Train Loss: 0.850, Val f1_micro: 0.295
Epoch: 320, Train Loss: 0.867, Val f1_micro: 0.293
Epoch: 340, Train Loss: 0.852, Val f1_micro: 0.296
Epoch: 360, Train Loss: 0.811, Val f1_micro: 0.296
Epoch: 380, Train Loss: 0.828, Val f1_micro: 0.304
Epoch: 400, Train Loss: 0.814, Val f1_micro: 0.298
Epoch: 420, Train Loss: 0.814, Val f1_micro: 0.299
Epoch: 440, Train Loss: 0.781, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.798, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.791, Val f1_micro: 0.298
Epoch: 500, Train Loss: 0.781, Val f1_micro: 0.301
f1-micro: 0.301, f1-macro: 0.291, f1-weighted: 0.296, , roc-auc: 0.677
##### RUN 3 #####
Epoch: 020, Train Loss: 1.666, Val f1_micro: 0.238
Epoch: 040, Train Loss: 1.419, Val f1_micro: 0.256
Epoch: 060, Train Loss: 1.289, Val f1_micro: 0.267
Epoch: 080, Train Loss: 1.192, Val f1_micro: 0.270
Epoch: 100, Train Loss: 1.140, Val f1_micro: 0.273
Epoch: 120, Train Loss: 1.095, Val f1_micro: 0.275
Epoch: 140, Train Loss: 1.046, Val f1_micro: 0.279
Epoch: 160, Train Loss: 1.014, Val f1_micro: 0.284
Epoch: 180, Train Loss: 0.993, Val f1_micro: 0.287
Epoch: 200, Train Loss: 0.949, Val f1_micro: 0.285
Epoch: 220, Train Loss: 0.949, Val f1_micro: 0.288
Epoch: 240, Train Loss: 0.899, Val f1_micro: 0.294
Epoch: 260, Train Loss: 0.898, Val f1_micro: 0.292
Epoch: 280, Train Loss: 0.896, Val f1_micro: 0.296
Epoch: 300, Train Loss: 0.873, Val f1_micro: 0.292
Epoch: 320, Train Loss: 0.860, Val f1_micro: 0.296
Epoch: 340, Train Loss: 0.846, Val f1_micro: 0.297
Epoch: 360, Train Loss: 0.846, Val f1_micro: 0.295
Epoch: 380, Train Loss: 0.830, Val f1_micro: 0.303
Epoch: 400, Train Loss: 0.825, Val f1_micro: 0.301
Epoch: 420, Train Loss: 0.817, Val f1_micro: 0.297
Epoch: 440, Train Loss: 0.798, Val f1_micro: 0.297
Epoch: 460, Train Loss: 0.807, Val f1_micro: 0.301
Epoch: 480, Train Loss: 0.793, Val f1_micro: 0.300
Epoch: 500, Train Loss: 0.775, Val f1_micro: 0.299
f1-micro: 0.299, f1-macro: 0.290, f1-weighted: 0.295, , roc-auc: 0.676
##### RUN 4 #####
Epoch: 020, Train Loss: 1.684, Val f1_micro: 0.236
Epoch: 040, Train Loss: 1.406, Val f1_micro: 0.248
Epoch: 060, Train Loss: 1.279, Val f1_micro: 0.257
Epoch: 080, Train Loss: 1.220, Val f1_micro: 0.263
Epoch: 100, Train Loss: 1.151, Val f1_micro: 0.274
Epoch: 120, Train Loss: 1.102, Val f1_micro: 0.275
Epoch: 140, Train Loss: 1.059, Val f1_micro: 0.279
Epoch: 160, Train Loss: 1.025, Val f1_micro: 0.276
Epoch: 180, Train Loss: 0.993, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.964, Val f1_micro: 0.287
Epoch: 220, Train Loss: 0.956, Val f1_micro: 0.290
Epoch: 240, Train Loss: 0.913, Val f1_micro: 0.290
Epoch: 260, Train Loss: 0.900, Val f1_micro: 0.295
Epoch: 280, Train Loss: 0.895, Val f1_micro: 0.293
Epoch: 300, Train Loss: 0.865, Val f1_micro: 0.293
Epoch: 320, Train Loss: 0.862, Val f1_micro: 0.294
Epoch: 340, Train Loss: 0.851, Val f1_micro: 0.296
Epoch: 360, Train Loss: 0.840, Val f1_micro: 0.297
Epoch: 380, Train Loss: 0.838, Val f1_micro: 0.296
Epoch: 400, Train Loss: 0.811, Val f1_micro: 0.300
Epoch: 420, Train Loss: 0.820, Val f1_micro: 0.299
Epoch: 440, Train Loss: 0.816, Val f1_micro: 0.304
Epoch: 460, Train Loss: 0.817, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.789, Val f1_micro: 0.301
Epoch: 500, Train Loss: 0.790, Val f1_micro: 0.302
f1-micro: 0.302, f1-macro: 0.292, f1-weighted: 0.297, , roc-auc: 0.676
##### RUN 5 #####
Epoch: 020, Train Loss: 1.685, Val f1_micro: 0.243
Epoch: 040, Train Loss: 1.416, Val f1_micro: 0.253
Epoch: 060, Train Loss: 1.297, Val f1_micro: 0.264
Epoch: 080, Train Loss: 1.207, Val f1_micro: 0.271
Epoch: 100, Train Loss: 1.148, Val f1_micro: 0.276
Epoch: 120, Train Loss: 1.090, Val f1_micro: 0.282
Epoch: 140, Train Loss: 1.042, Val f1_micro: 0.282
Epoch: 160, Train Loss: 1.050, Val f1_micro: 0.285
Epoch: 180, Train Loss: 0.996, Val f1_micro: 0.289
Epoch: 200, Train Loss: 0.964, Val f1_micro: 0.286
Epoch: 220, Train Loss: 0.942, Val f1_micro: 0.288
Epoch: 240, Train Loss: 0.921, Val f1_micro: 0.294
Epoch: 260, Train Loss: 0.904, Val f1_micro: 0.293
Epoch: 280, Train Loss: 0.901, Val f1_micro: 0.296
Epoch: 300, Train Loss: 0.869, Val f1_micro: 0.295
Epoch: 320, Train Loss: 0.868, Val f1_micro: 0.296
Epoch: 340, Train Loss: 0.857, Val f1_micro: 0.297
Epoch: 360, Train Loss: 0.829, Val f1_micro: 0.300
Epoch: 380, Train Loss: 0.826, Val f1_micro: 0.297
Epoch: 400, Train Loss: 0.816, Val f1_micro: 0.299
Epoch: 420, Train Loss: 0.806, Val f1_micro: 0.300
Epoch: 440, Train Loss: 0.800, Val f1_micro: 0.300
Epoch: 460, Train Loss: 0.813, Val f1_micro: 0.300
Epoch: 480, Train Loss: 0.807, Val f1_micro: 0.302
Epoch: 500, Train Loss: 0.797, Val f1_micro: 0.303
f1-micro: 0.303, f1-macro: 0.293, f1-weighted: 0.298, , roc-auc: 0.675
########## Hyperparameters combination ##########
(512, 0.4, 0.005, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.727, Val f1_micro: 0.224
Epoch: 040, Train Loss: 1.578, Val f1_micro: 0.233
Epoch: 060, Train Loss: 1.551, Val f1_micro: 0.226
Epoch: 080, Train Loss: 1.524, Val f1_micro: 0.220
Epoch: 100, Train Loss: 1.543, Val f1_micro: 0.230
Epoch: 120, Train Loss: 1.563, Val f1_micro: 0.227
Epoch: 140, Train Loss: 1.567, Val f1_micro: 0.220
Epoch: 160, Train Loss: 1.573, Val f1_micro: 0.226
Epoch: 180, Train Loss: 1.579, Val f1_micro: 0.221
Epoch: 200, Train Loss: 1.586, Val f1_micro: 0.224
Epoch: 220, Train Loss: 1.590, Val f1_micro: 0.220
Epoch: 240, Train Loss: 1.570, Val f1_micro: 0.220
Epoch: 260, Train Loss: 1.585, Val f1_micro: 0.220
Epoch: 280, Train Loss: 1.585, Val f1_micro: 0.225
Epoch: 300, Train Loss: 1.587, Val f1_micro: 0.227
Epoch: 320, Train Loss: 1.592, Val f1_micro: 0.222
Epoch: 340, Train Loss: 1.587, Val f1_micro: 0.224
Epoch: 360, Train Loss: 1.584, Val f1_micro: 0.221
Epoch: 380, Train Loss: 1.587, Val f1_micro: 0.220
Epoch: 400, Train Loss: 1.584, Val f1_micro: 0.222
Epoch: 420, Train Loss: 1.572, Val f1_micro: 0.223
Epoch: 440, Train Loss: 1.571, Val f1_micro: 0.224
Epoch: 460, Train Loss: 1.582, Val f1_micro: 0.222
Epoch: 480, Train Loss: 1.571, Val f1_micro: 0.223
Epoch: 500, Train Loss: 1.572, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.199, f1-weighted: 0.200, , roc-auc: 0.644
##### RUN 2 #####
Epoch: 020, Train Loss: 1.730, Val f1_micro: 0.222
Epoch: 040, Train Loss: 1.581, Val f1_micro: 0.228
Epoch: 060, Train Loss: 1.547, Val f1_micro: 0.233
Epoch: 080, Train Loss: 1.554, Val f1_micro: 0.230
Epoch: 100, Train Loss: 1.548, Val f1_micro: 0.226
Epoch: 120, Train Loss: 1.565, Val f1_micro: 0.223
Epoch: 140, Train Loss: 1.566, Val f1_micro: 0.223
Epoch: 160, Train Loss: 1.569, Val f1_micro: 0.221
Epoch: 180, Train Loss: 1.578, Val f1_micro: 0.226
Epoch: 200, Train Loss: 1.581, Val f1_micro: 0.222
Epoch: 220, Train Loss: 1.590, Val f1_micro: 0.227
Epoch: 240, Train Loss: 1.588, Val f1_micro: 0.227
Epoch: 260, Train Loss: 1.590, Val f1_micro: 0.224
Epoch: 280, Train Loss: 1.576, Val f1_micro: 0.224
Epoch: 300, Train Loss: 1.578, Val f1_micro: 0.224
Epoch: 320, Train Loss: 1.576, Val f1_micro: 0.222
Epoch: 340, Train Loss: 1.587, Val f1_micro: 0.222
Epoch: 360, Train Loss: 1.575, Val f1_micro: 0.225
Epoch: 380, Train Loss: 1.579, Val f1_micro: 0.226
Epoch: 400, Train Loss: 1.571, Val f1_micro: 0.221
Epoch: 420, Train Loss: 1.584, Val f1_micro: 0.224
Epoch: 440, Train Loss: 1.577, Val f1_micro: 0.223
Epoch: 460, Train Loss: 1.565, Val f1_micro: 0.229
Epoch: 480, Train Loss: 1.574, Val f1_micro: 0.221
Epoch: 500, Train Loss: 1.576, Val f1_micro: 0.226
f1-micro: 0.226, f1-macro: 0.199, f1-weighted: 0.198, , roc-auc: 0.642
##### RUN 3 #####
Epoch: 020, Train Loss: 1.736, Val f1_micro: 0.219
Epoch: 040, Train Loss: 1.587, Val f1_micro: 0.221
Epoch: 060, Train Loss: 1.550, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.545, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.562, Val f1_micro: 0.225
Epoch: 120, Train Loss: 1.566, Val f1_micro: 0.223
Epoch: 140, Train Loss: 1.569, Val f1_micro: 0.222
Epoch: 160, Train Loss: 1.593, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.591, Val f1_micro: 0.224
Epoch: 200, Train Loss: 1.565, Val f1_micro: 0.226
Epoch: 220, Train Loss: 1.589, Val f1_micro: 0.224
Epoch: 240, Train Loss: 1.582, Val f1_micro: 0.224
Epoch: 260, Train Loss: 1.590, Val f1_micro: 0.222
Epoch: 280, Train Loss: 1.590, Val f1_micro: 0.220
Epoch: 300, Train Loss: 1.599, Val f1_micro: 0.224
Epoch: 320, Train Loss: 1.579, Val f1_micro: 0.228
Epoch: 340, Train Loss: 1.592, Val f1_micro: 0.216
Epoch: 360, Train Loss: 1.591, Val f1_micro: 0.224
Epoch: 380, Train Loss: 1.589, Val f1_micro: 0.228
Epoch: 400, Train Loss: 1.580, Val f1_micro: 0.221
Epoch: 420, Train Loss: 1.588, Val f1_micro: 0.227
Epoch: 440, Train Loss: 1.577, Val f1_micro: 0.227
Epoch: 460, Train Loss: 1.577, Val f1_micro: 0.232
Epoch: 480, Train Loss: 1.576, Val f1_micro: 0.223
Epoch: 500, Train Loss: 1.573, Val f1_micro: 0.228
f1-micro: 0.228, f1-macro: 0.198, f1-weighted: 0.199, , roc-auc: 0.642
##### RUN 4 #####
Epoch: 020, Train Loss: 1.738, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.571, Val f1_micro: 0.222
Epoch: 060, Train Loss: 1.544, Val f1_micro: 0.228
Epoch: 080, Train Loss: 1.543, Val f1_micro: 0.226
Epoch: 100, Train Loss: 1.551, Val f1_micro: 0.224
Epoch: 120, Train Loss: 1.567, Val f1_micro: 0.225
Epoch: 140, Train Loss: 1.558, Val f1_micro: 0.227
Epoch: 160, Train Loss: 1.572, Val f1_micro: 0.227
Epoch: 180, Train Loss: 1.578, Val f1_micro: 0.219
Epoch: 200, Train Loss: 1.586, Val f1_micro: 0.226
Epoch: 220, Train Loss: 1.574, Val f1_micro: 0.222
Epoch: 240, Train Loss: 1.588, Val f1_micro: 0.222
Epoch: 260, Train Loss: 1.584, Val f1_micro: 0.222
Epoch: 280, Train Loss: 1.584, Val f1_micro: 0.224
Epoch: 300, Train Loss: 1.584, Val f1_micro: 0.224
Epoch: 320, Train Loss: 1.581, Val f1_micro: 0.225
Epoch: 340, Train Loss: 1.582, Val f1_micro: 0.221
Epoch: 360, Train Loss: 1.576, Val f1_micro: 0.223
Epoch: 380, Train Loss: 1.583, Val f1_micro: 0.225
Epoch: 400, Train Loss: 1.580, Val f1_micro: 0.225
Epoch: 420, Train Loss: 1.583, Val f1_micro: 0.225
Epoch: 440, Train Loss: 1.579, Val f1_micro: 0.226
Epoch: 460, Train Loss: 1.572, Val f1_micro: 0.225
Epoch: 480, Train Loss: 1.568, Val f1_micro: 0.222
Epoch: 500, Train Loss: 1.581, Val f1_micro: 0.221
f1-micro: 0.221, f1-macro: 0.194, f1-weighted: 0.193, , roc-auc: 0.641
##### RUN 5 #####
Epoch: 020, Train Loss: 1.735, Val f1_micro: 0.213
Epoch: 040, Train Loss: 1.580, Val f1_micro: 0.228
Epoch: 060, Train Loss: 1.550, Val f1_micro: 0.223
Epoch: 080, Train Loss: 1.545, Val f1_micro: 0.220
Epoch: 100, Train Loss: 1.550, Val f1_micro: 0.224
Epoch: 120, Train Loss: 1.558, Val f1_micro: 0.230
Epoch: 140, Train Loss: 1.555, Val f1_micro: 0.223
Epoch: 160, Train Loss: 1.567, Val f1_micro: 0.224
Epoch: 180, Train Loss: 1.573, Val f1_micro: 0.221
Epoch: 200, Train Loss: 1.585, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.585, Val f1_micro: 0.220
Epoch: 240, Train Loss: 1.586, Val f1_micro: 0.220
Epoch: 260, Train Loss: 1.595, Val f1_micro: 0.223
Epoch: 280, Train Loss: 1.586, Val f1_micro: 0.222
Epoch: 300, Train Loss: 1.585, Val f1_micro: 0.224
Epoch: 320, Train Loss: 1.583, Val f1_micro: 0.219
Epoch: 340, Train Loss: 1.582, Val f1_micro: 0.226
Epoch: 360, Train Loss: 1.586, Val f1_micro: 0.228
Epoch: 380, Train Loss: 1.587, Val f1_micro: 0.227
Epoch: 400, Train Loss: 1.585, Val f1_micro: 0.225
Epoch: 420, Train Loss: 1.582, Val f1_micro: 0.224
Epoch: 440, Train Loss: 1.589, Val f1_micro: 0.230
Epoch: 460, Train Loss: 1.576, Val f1_micro: 0.226
Epoch: 480, Train Loss: 1.583, Val f1_micro: 0.219
Epoch: 500, Train Loss: 1.581, Val f1_micro: 0.220
f1-micro: 0.220, f1-macro: 0.191, f1-weighted: 0.191, , roc-auc: 0.643
########## Hyperparameters combination ##########
(512, 0.4, 0.01, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.571, Val f1_micro: 0.227
Epoch: 040, Train Loss: 1.279, Val f1_micro: 0.268
Epoch: 060, Train Loss: 1.095, Val f1_micro: 0.276
Epoch: 080, Train Loss: 0.971, Val f1_micro: 0.283
Epoch: 100, Train Loss: 0.856, Val f1_micro: 0.288
Epoch: 120, Train Loss: 0.758, Val f1_micro: 0.296
Epoch: 140, Train Loss: 0.661, Val f1_micro: 0.301
Epoch: 160, Train Loss: 0.616, Val f1_micro: 0.304
Epoch: 180, Train Loss: 0.543, Val f1_micro: 0.307
Epoch: 200, Train Loss: 0.484, Val f1_micro: 0.314
Epoch: 220, Train Loss: 0.455, Val f1_micro: 0.312
Epoch: 240, Train Loss: 0.403, Val f1_micro: 0.313
Epoch: 260, Train Loss: 0.378, Val f1_micro: 0.316
Epoch: 280, Train Loss: 0.343, Val f1_micro: 0.315
Epoch: 300, Train Loss: 0.331, Val f1_micro: 0.316
Epoch: 320, Train Loss: 0.316, Val f1_micro: 0.318
Epoch: 340, Train Loss: 0.297, Val f1_micro: 0.316
Epoch: 360, Train Loss: 0.282, Val f1_micro: 0.318
Epoch: 380, Train Loss: 0.272, Val f1_micro: 0.319
Epoch: 400, Train Loss: 0.251, Val f1_micro: 0.316
Epoch: 420, Train Loss: 0.243, Val f1_micro: 0.318
Epoch: 440, Train Loss: 0.250, Val f1_micro: 0.317
Epoch: 460, Train Loss: 0.225, Val f1_micro: 0.318
Epoch: 480, Train Loss: 0.217, Val f1_micro: 0.317
Epoch: 500, Train Loss: 0.207, Val f1_micro: 0.314
f1-micro: 0.314, f1-macro: 0.307, f1-weighted: 0.314, , roc-auc: 0.685
##### RUN 2 #####
Epoch: 020, Train Loss: 1.593, Val f1_micro: 0.227
Epoch: 040, Train Loss: 1.263, Val f1_micro: 0.267
Epoch: 060, Train Loss: 1.084, Val f1_micro: 0.276
Epoch: 080, Train Loss: 0.952, Val f1_micro: 0.281
Epoch: 100, Train Loss: 0.844, Val f1_micro: 0.293
Epoch: 120, Train Loss: 0.738, Val f1_micro: 0.298
Epoch: 140, Train Loss: 0.637, Val f1_micro: 0.300
Epoch: 160, Train Loss: 0.606, Val f1_micro: 0.307
Epoch: 180, Train Loss: 0.540, Val f1_micro: 0.312
Epoch: 200, Train Loss: 0.476, Val f1_micro: 0.310
Epoch: 220, Train Loss: 0.433, Val f1_micro: 0.316
Epoch: 240, Train Loss: 0.407, Val f1_micro: 0.315
Epoch: 260, Train Loss: 0.375, Val f1_micro: 0.319
Epoch: 280, Train Loss: 0.341, Val f1_micro: 0.317
Epoch: 300, Train Loss: 0.335, Val f1_micro: 0.316
Epoch: 320, Train Loss: 0.294, Val f1_micro: 0.317
Epoch: 340, Train Loss: 0.297, Val f1_micro: 0.316
Epoch: 360, Train Loss: 0.296, Val f1_micro: 0.318
Epoch: 380, Train Loss: 0.258, Val f1_micro: 0.317
Epoch: 400, Train Loss: 0.252, Val f1_micro: 0.318
Epoch: 420, Train Loss: 0.249, Val f1_micro: 0.317
Epoch: 440, Train Loss: 0.239, Val f1_micro: 0.316
Epoch: 460, Train Loss: 0.230, Val f1_micro: 0.314
Epoch: 480, Train Loss: 0.233, Val f1_micro: 0.319
Epoch: 500, Train Loss: 0.224, Val f1_micro: 0.316
f1-micro: 0.316, f1-macro: 0.308, f1-weighted: 0.315, , roc-auc: 0.682
##### RUN 3 #####
Epoch: 020, Train Loss: 1.590, Val f1_micro: 0.222
Epoch: 040, Train Loss: 1.296, Val f1_micro: 0.263
Epoch: 060, Train Loss: 1.093, Val f1_micro: 0.275
Epoch: 080, Train Loss: 0.949, Val f1_micro: 0.286
Epoch: 100, Train Loss: 0.833, Val f1_micro: 0.290
Epoch: 120, Train Loss: 0.748, Val f1_micro: 0.296
Epoch: 140, Train Loss: 0.650, Val f1_micro: 0.301
Epoch: 160, Train Loss: 0.603, Val f1_micro: 0.308
Epoch: 180, Train Loss: 0.520, Val f1_micro: 0.307
Epoch: 200, Train Loss: 0.461, Val f1_micro: 0.313
Epoch: 220, Train Loss: 0.455, Val f1_micro: 0.316
Epoch: 240, Train Loss: 0.423, Val f1_micro: 0.315
Epoch: 260, Train Loss: 0.379, Val f1_micro: 0.316
Epoch: 280, Train Loss: 0.359, Val f1_micro: 0.316
Epoch: 300, Train Loss: 0.331, Val f1_micro: 0.317
Epoch: 320, Train Loss: 0.311, Val f1_micro: 0.317
Epoch: 340, Train Loss: 0.303, Val f1_micro: 0.322
Epoch: 360, Train Loss: 0.290, Val f1_micro: 0.319
Epoch: 380, Train Loss: 0.273, Val f1_micro: 0.321
Epoch: 400, Train Loss: 0.253, Val f1_micro: 0.318
Epoch: 420, Train Loss: 0.243, Val f1_micro: 0.322
Epoch: 440, Train Loss: 0.241, Val f1_micro: 0.318
Epoch: 460, Train Loss: 0.224, Val f1_micro: 0.319
Epoch: 480, Train Loss: 0.215, Val f1_micro: 0.321
Epoch: 500, Train Loss: 0.220, Val f1_micro: 0.322
f1-micro: 0.322, f1-macro: 0.315, f1-weighted: 0.322, , roc-auc: 0.686
##### RUN 4 #####
Epoch: 020, Train Loss: 1.595, Val f1_micro: 0.231
Epoch: 040, Train Loss: 1.282, Val f1_micro: 0.260
Epoch: 060, Train Loss: 1.095, Val f1_micro: 0.277
Epoch: 080, Train Loss: 0.951, Val f1_micro: 0.283
Epoch: 100, Train Loss: 0.842, Val f1_micro: 0.292
Epoch: 120, Train Loss: 0.747, Val f1_micro: 0.294
Epoch: 140, Train Loss: 0.682, Val f1_micro: 0.298
Epoch: 160, Train Loss: 0.607, Val f1_micro: 0.309
Epoch: 180, Train Loss: 0.539, Val f1_micro: 0.314
Epoch: 200, Train Loss: 0.509, Val f1_micro: 0.313
Epoch: 220, Train Loss: 0.450, Val f1_micro: 0.313
Epoch: 240, Train Loss: 0.419, Val f1_micro: 0.315
Epoch: 260, Train Loss: 0.388, Val f1_micro: 0.317
Epoch: 280, Train Loss: 0.363, Val f1_micro: 0.314
Epoch: 300, Train Loss: 0.328, Val f1_micro: 0.317
Epoch: 320, Train Loss: 0.321, Val f1_micro: 0.315
Epoch: 340, Train Loss: 0.318, Val f1_micro: 0.315
Epoch: 360, Train Loss: 0.291, Val f1_micro: 0.319
Epoch: 380, Train Loss: 0.280, Val f1_micro: 0.315
Epoch: 400, Train Loss: 0.270, Val f1_micro: 0.314
Epoch: 420, Train Loss: 0.243, Val f1_micro: 0.316
Epoch: 440, Train Loss: 0.241, Val f1_micro: 0.317
Epoch: 460, Train Loss: 0.237, Val f1_micro: 0.319
Epoch: 480, Train Loss: 0.245, Val f1_micro: 0.314
Epoch: 500, Train Loss: 0.224, Val f1_micro: 0.317
f1-micro: 0.317, f1-macro: 0.310, f1-weighted: 0.316, , roc-auc: 0.683
##### RUN 5 #####
Epoch: 020, Train Loss: 1.603, Val f1_micro: 0.230
Epoch: 040, Train Loss: 1.289, Val f1_micro: 0.261
Epoch: 060, Train Loss: 1.105, Val f1_micro: 0.276
Epoch: 080, Train Loss: 0.969, Val f1_micro: 0.281
Epoch: 100, Train Loss: 0.841, Val f1_micro: 0.284
Epoch: 120, Train Loss: 0.738, Val f1_micro: 0.294
Epoch: 140, Train Loss: 0.676, Val f1_micro: 0.299
Epoch: 160, Train Loss: 0.594, Val f1_micro: 0.305
Epoch: 180, Train Loss: 0.533, Val f1_micro: 0.308
Epoch: 200, Train Loss: 0.489, Val f1_micro: 0.309
Epoch: 220, Train Loss: 0.460, Val f1_micro: 0.310
Epoch: 240, Train Loss: 0.425, Val f1_micro: 0.313
Epoch: 260, Train Loss: 0.362, Val f1_micro: 0.317
Epoch: 280, Train Loss: 0.368, Val f1_micro: 0.318
Epoch: 300, Train Loss: 0.347, Val f1_micro: 0.317
Epoch: 320, Train Loss: 0.322, Val f1_micro: 0.319
Epoch: 340, Train Loss: 0.290, Val f1_micro: 0.318
Epoch: 360, Train Loss: 0.288, Val f1_micro: 0.318
Epoch: 380, Train Loss: 0.274, Val f1_micro: 0.316
Epoch: 400, Train Loss: 0.262, Val f1_micro: 0.319
Epoch: 420, Train Loss: 0.239, Val f1_micro: 0.321
Epoch: 440, Train Loss: 0.245, Val f1_micro: 0.322
Epoch: 460, Train Loss: 0.236, Val f1_micro: 0.320
Epoch: 480, Train Loss: 0.221, Val f1_micro: 0.320
Epoch: 500, Train Loss: 0.217, Val f1_micro: 0.319
f1-micro: 0.319, f1-macro: 0.312, f1-weighted: 0.319, , roc-auc: 0.685
########## Hyperparameters combination ##########
(512, 0.4, 0.01, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.602, Val f1_micro: 0.227
Epoch: 040, Train Loss: 1.302, Val f1_micro: 0.263
Epoch: 060, Train Loss: 1.170, Val f1_micro: 0.269
Epoch: 080, Train Loss: 1.029, Val f1_micro: 0.278
Epoch: 100, Train Loss: 0.953, Val f1_micro: 0.281
Epoch: 120, Train Loss: 0.897, Val f1_micro: 0.286
Epoch: 140, Train Loss: 0.848, Val f1_micro: 0.287
Epoch: 160, Train Loss: 0.803, Val f1_micro: 0.291
Epoch: 180, Train Loss: 0.752, Val f1_micro: 0.293
Epoch: 200, Train Loss: 0.726, Val f1_micro: 0.295
Epoch: 220, Train Loss: 0.698, Val f1_micro: 0.296
Epoch: 240, Train Loss: 0.672, Val f1_micro: 0.298
Epoch: 260, Train Loss: 0.652, Val f1_micro: 0.301
Epoch: 280, Train Loss: 0.626, Val f1_micro: 0.308
Epoch: 300, Train Loss: 0.609, Val f1_micro: 0.309
Epoch: 320, Train Loss: 0.586, Val f1_micro: 0.305
Epoch: 340, Train Loss: 0.595, Val f1_micro: 0.305
Epoch: 360, Train Loss: 0.581, Val f1_micro: 0.306
Epoch: 380, Train Loss: 0.542, Val f1_micro: 0.308
Epoch: 400, Train Loss: 0.540, Val f1_micro: 0.308
Epoch: 420, Train Loss: 0.519, Val f1_micro: 0.313
Epoch: 440, Train Loss: 0.510, Val f1_micro: 0.308
Epoch: 460, Train Loss: 0.511, Val f1_micro: 0.312
Epoch: 480, Train Loss: 0.520, Val f1_micro: 0.311
Epoch: 500, Train Loss: 0.494, Val f1_micro: 0.315
f1-micro: 0.315, f1-macro: 0.309, f1-weighted: 0.314, , roc-auc: 0.673
##### RUN 2 #####
Epoch: 020, Train Loss: 1.577, Val f1_micro: 0.220
Epoch: 040, Train Loss: 1.290, Val f1_micro: 0.260
Epoch: 060, Train Loss: 1.134, Val f1_micro: 0.262
Epoch: 080, Train Loss: 1.037, Val f1_micro: 0.272
Epoch: 100, Train Loss: 0.951, Val f1_micro: 0.278
Epoch: 120, Train Loss: 0.910, Val f1_micro: 0.281
Epoch: 140, Train Loss: 0.849, Val f1_micro: 0.288
Epoch: 160, Train Loss: 0.802, Val f1_micro: 0.291
Epoch: 180, Train Loss: 0.762, Val f1_micro: 0.290
Epoch: 200, Train Loss: 0.719, Val f1_micro: 0.294
Epoch: 220, Train Loss: 0.698, Val f1_micro: 0.297
Epoch: 240, Train Loss: 0.663, Val f1_micro: 0.301
Epoch: 260, Train Loss: 0.657, Val f1_micro: 0.300
Epoch: 280, Train Loss: 0.638, Val f1_micro: 0.309
Epoch: 300, Train Loss: 0.586, Val f1_micro: 0.306
Epoch: 320, Train Loss: 0.572, Val f1_micro: 0.306
Epoch: 340, Train Loss: 0.554, Val f1_micro: 0.309
Epoch: 360, Train Loss: 0.551, Val f1_micro: 0.307
Epoch: 380, Train Loss: 0.538, Val f1_micro: 0.309
Epoch: 400, Train Loss: 0.530, Val f1_micro: 0.311
Epoch: 420, Train Loss: 0.527, Val f1_micro: 0.311
Epoch: 440, Train Loss: 0.506, Val f1_micro: 0.314
Epoch: 460, Train Loss: 0.495, Val f1_micro: 0.312
Epoch: 480, Train Loss: 0.498, Val f1_micro: 0.317
Epoch: 500, Train Loss: 0.494, Val f1_micro: 0.313
f1-micro: 0.313, f1-macro: 0.306, f1-weighted: 0.312, , roc-auc: 0.675
##### RUN 3 #####
Epoch: 020, Train Loss: 1.624, Val f1_micro: 0.231
Epoch: 040, Train Loss: 1.313, Val f1_micro: 0.258
Epoch: 060, Train Loss: 1.167, Val f1_micro: 0.269
Epoch: 080, Train Loss: 1.053, Val f1_micro: 0.274
Epoch: 100, Train Loss: 0.982, Val f1_micro: 0.279
Epoch: 120, Train Loss: 0.913, Val f1_micro: 0.282
Epoch: 140, Train Loss: 0.871, Val f1_micro: 0.285
Epoch: 160, Train Loss: 0.830, Val f1_micro: 0.288
Epoch: 180, Train Loss: 0.776, Val f1_micro: 0.292
Epoch: 200, Train Loss: 0.743, Val f1_micro: 0.294
Epoch: 220, Train Loss: 0.702, Val f1_micro: 0.299
Epoch: 240, Train Loss: 0.692, Val f1_micro: 0.302
Epoch: 260, Train Loss: 0.666, Val f1_micro: 0.303
Epoch: 280, Train Loss: 0.633, Val f1_micro: 0.304
Epoch: 300, Train Loss: 0.608, Val f1_micro: 0.306
Epoch: 320, Train Loss: 0.608, Val f1_micro: 0.308
Epoch: 340, Train Loss: 0.586, Val f1_micro: 0.308
Epoch: 360, Train Loss: 0.554, Val f1_micro: 0.307
Epoch: 380, Train Loss: 0.545, Val f1_micro: 0.309
Epoch: 400, Train Loss: 0.553, Val f1_micro: 0.309
Epoch: 420, Train Loss: 0.517, Val f1_micro: 0.312
Epoch: 440, Train Loss: 0.535, Val f1_micro: 0.311
Epoch: 460, Train Loss: 0.507, Val f1_micro: 0.308
Epoch: 480, Train Loss: 0.503, Val f1_micro: 0.314
Epoch: 500, Train Loss: 0.495, Val f1_micro: 0.314
f1-micro: 0.314, f1-macro: 0.309, f1-weighted: 0.315, , roc-auc: 0.674
##### RUN 4 #####
Epoch: 020, Train Loss: 1.609, Val f1_micro: 0.223
Epoch: 040, Train Loss: 1.329, Val f1_micro: 0.261
Epoch: 060, Train Loss: 1.141, Val f1_micro: 0.269
Epoch: 080, Train Loss: 1.047, Val f1_micro: 0.273
Epoch: 100, Train Loss: 0.974, Val f1_micro: 0.276
Epoch: 120, Train Loss: 0.912, Val f1_micro: 0.286
Epoch: 140, Train Loss: 0.851, Val f1_micro: 0.289
Epoch: 160, Train Loss: 0.822, Val f1_micro: 0.291
Epoch: 180, Train Loss: 0.745, Val f1_micro: 0.293
Epoch: 200, Train Loss: 0.739, Val f1_micro: 0.293
Epoch: 220, Train Loss: 0.707, Val f1_micro: 0.292
Epoch: 240, Train Loss: 0.669, Val f1_micro: 0.297
Epoch: 260, Train Loss: 0.625, Val f1_micro: 0.297
Epoch: 280, Train Loss: 0.624, Val f1_micro: 0.303
Epoch: 300, Train Loss: 0.600, Val f1_micro: 0.301
Epoch: 320, Train Loss: 0.610, Val f1_micro: 0.307
Epoch: 340, Train Loss: 0.572, Val f1_micro: 0.309
Epoch: 360, Train Loss: 0.537, Val f1_micro: 0.312
Epoch: 380, Train Loss: 0.524, Val f1_micro: 0.311
Epoch: 400, Train Loss: 0.506, Val f1_micro: 0.310
Epoch: 420, Train Loss: 0.530, Val f1_micro: 0.309
Epoch: 440, Train Loss: 0.513, Val f1_micro: 0.305
Epoch: 460, Train Loss: 0.508, Val f1_micro: 0.314
Epoch: 480, Train Loss: 0.521, Val f1_micro: 0.314
Epoch: 500, Train Loss: 0.498, Val f1_micro: 0.309
f1-micro: 0.309, f1-macro: 0.302, f1-weighted: 0.309, , roc-auc: 0.676
##### RUN 5 #####
Epoch: 020, Train Loss: 1.616, Val f1_micro: 0.229
Epoch: 040, Train Loss: 1.310, Val f1_micro: 0.255
Epoch: 060, Train Loss: 1.151, Val f1_micro: 0.270
Epoch: 080, Train Loss: 1.047, Val f1_micro: 0.273
Epoch: 100, Train Loss: 0.972, Val f1_micro: 0.280
Epoch: 120, Train Loss: 0.898, Val f1_micro: 0.284
Epoch: 140, Train Loss: 0.857, Val f1_micro: 0.289
Epoch: 160, Train Loss: 0.805, Val f1_micro: 0.291
Epoch: 180, Train Loss: 0.783, Val f1_micro: 0.290
Epoch: 200, Train Loss: 0.731, Val f1_micro: 0.297
Epoch: 220, Train Loss: 0.692, Val f1_micro: 0.297
Epoch: 240, Train Loss: 0.666, Val f1_micro: 0.302
Epoch: 260, Train Loss: 0.659, Val f1_micro: 0.301
Epoch: 280, Train Loss: 0.627, Val f1_micro: 0.304
Epoch: 300, Train Loss: 0.610, Val f1_micro: 0.305
Epoch: 320, Train Loss: 0.588, Val f1_micro: 0.305
Epoch: 340, Train Loss: 0.563, Val f1_micro: 0.308
Epoch: 360, Train Loss: 0.560, Val f1_micro: 0.308
Epoch: 380, Train Loss: 0.559, Val f1_micro: 0.309
Epoch: 400, Train Loss: 0.540, Val f1_micro: 0.308
Epoch: 420, Train Loss: 0.514, Val f1_micro: 0.310
Epoch: 440, Train Loss: 0.510, Val f1_micro: 0.311
Epoch: 460, Train Loss: 0.509, Val f1_micro: 0.313
Epoch: 480, Train Loss: 0.505, Val f1_micro: 0.313
Epoch: 500, Train Loss: 0.491, Val f1_micro: 0.315
f1-micro: 0.315, f1-macro: 0.309, f1-weighted: 0.315, , roc-auc: 0.675
########## Hyperparameters combination ##########
(512, 0.4, 0.01, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.626, Val f1_micro: 0.223
Epoch: 040, Train Loss: 1.348, Val f1_micro: 0.255
Epoch: 060, Train Loss: 1.229, Val f1_micro: 0.268
Epoch: 080, Train Loss: 1.145, Val f1_micro: 0.269
Epoch: 100, Train Loss: 1.073, Val f1_micro: 0.276
Epoch: 120, Train Loss: 1.032, Val f1_micro: 0.279
Epoch: 140, Train Loss: 0.976, Val f1_micro: 0.281
Epoch: 160, Train Loss: 0.943, Val f1_micro: 0.283
Epoch: 180, Train Loss: 0.937, Val f1_micro: 0.290
Epoch: 200, Train Loss: 0.917, Val f1_micro: 0.285
Epoch: 220, Train Loss: 0.873, Val f1_micro: 0.287
Epoch: 240, Train Loss: 0.862, Val f1_micro: 0.289
Epoch: 260, Train Loss: 0.852, Val f1_micro: 0.292
Epoch: 280, Train Loss: 0.814, Val f1_micro: 0.292
Epoch: 300, Train Loss: 0.831, Val f1_micro: 0.294
Epoch: 320, Train Loss: 0.813, Val f1_micro: 0.298
Epoch: 340, Train Loss: 0.798, Val f1_micro: 0.297
Epoch: 360, Train Loss: 0.769, Val f1_micro: 0.294
Epoch: 380, Train Loss: 0.771, Val f1_micro: 0.297
Epoch: 400, Train Loss: 0.785, Val f1_micro: 0.299
Epoch: 420, Train Loss: 0.779, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.762, Val f1_micro: 0.300
Epoch: 460, Train Loss: 0.752, Val f1_micro: 0.304
Epoch: 480, Train Loss: 0.747, Val f1_micro: 0.305
Epoch: 500, Train Loss: 0.761, Val f1_micro: 0.295
f1-micro: 0.295, f1-macro: 0.287, f1-weighted: 0.292, , roc-auc: 0.673
##### RUN 2 #####
Epoch: 020, Train Loss: 1.592, Val f1_micro: 0.224
Epoch: 040, Train Loss: 1.345, Val f1_micro: 0.259
Epoch: 060, Train Loss: 1.214, Val f1_micro: 0.268
Epoch: 080, Train Loss: 1.118, Val f1_micro: 0.270
Epoch: 100, Train Loss: 1.076, Val f1_micro: 0.274
Epoch: 120, Train Loss: 1.043, Val f1_micro: 0.278
Epoch: 140, Train Loss: 0.992, Val f1_micro: 0.280
Epoch: 160, Train Loss: 0.949, Val f1_micro: 0.286
Epoch: 180, Train Loss: 0.904, Val f1_micro: 0.285
Epoch: 200, Train Loss: 0.909, Val f1_micro: 0.286
Epoch: 220, Train Loss: 0.869, Val f1_micro: 0.287
Epoch: 240, Train Loss: 0.857, Val f1_micro: 0.288
Epoch: 260, Train Loss: 0.835, Val f1_micro: 0.290
Epoch: 280, Train Loss: 0.838, Val f1_micro: 0.294
Epoch: 300, Train Loss: 0.809, Val f1_micro: 0.293
Epoch: 320, Train Loss: 0.794, Val f1_micro: 0.295
Epoch: 340, Train Loss: 0.802, Val f1_micro: 0.289
Epoch: 360, Train Loss: 0.794, Val f1_micro: 0.292
Epoch: 380, Train Loss: 0.773, Val f1_micro: 0.301
Epoch: 400, Train Loss: 0.765, Val f1_micro: 0.298
Epoch: 420, Train Loss: 0.746, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.769, Val f1_micro: 0.299
Epoch: 460, Train Loss: 0.750, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.727, Val f1_micro: 0.301
Epoch: 500, Train Loss: 0.757, Val f1_micro: 0.300
f1-micro: 0.300, f1-macro: 0.291, f1-weighted: 0.297, , roc-auc: 0.673
##### RUN 3 #####
Epoch: 020, Train Loss: 1.617, Val f1_micro: 0.223
Epoch: 040, Train Loss: 1.332, Val f1_micro: 0.256
Epoch: 060, Train Loss: 1.222, Val f1_micro: 0.268
Epoch: 080, Train Loss: 1.143, Val f1_micro: 0.273
Epoch: 100, Train Loss: 1.066, Val f1_micro: 0.278
Epoch: 120, Train Loss: 1.031, Val f1_micro: 0.277
Epoch: 140, Train Loss: 0.986, Val f1_micro: 0.282
Epoch: 160, Train Loss: 0.941, Val f1_micro: 0.284
Epoch: 180, Train Loss: 0.938, Val f1_micro: 0.290
Epoch: 200, Train Loss: 0.921, Val f1_micro: 0.288
Epoch: 220, Train Loss: 0.900, Val f1_micro: 0.289
Epoch: 240, Train Loss: 0.874, Val f1_micro: 0.291
Epoch: 260, Train Loss: 0.852, Val f1_micro: 0.286
Epoch: 280, Train Loss: 0.831, Val f1_micro: 0.294
Epoch: 300, Train Loss: 0.813, Val f1_micro: 0.294
Epoch: 320, Train Loss: 0.811, Val f1_micro: 0.293
Epoch: 340, Train Loss: 0.792, Val f1_micro: 0.292
Epoch: 360, Train Loss: 0.778, Val f1_micro: 0.295
Epoch: 380, Train Loss: 0.762, Val f1_micro: 0.297
Epoch: 400, Train Loss: 0.789, Val f1_micro: 0.299
Epoch: 420, Train Loss: 0.759, Val f1_micro: 0.300
Epoch: 440, Train Loss: 0.757, Val f1_micro: 0.296
Epoch: 460, Train Loss: 0.756, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.755, Val f1_micro: 0.298
Epoch: 500, Train Loss: 0.757, Val f1_micro: 0.300
f1-micro: 0.300, f1-macro: 0.290, f1-weighted: 0.296, , roc-auc: 0.675
##### RUN 4 #####
Epoch: 020, Train Loss: 1.607, Val f1_micro: 0.225
Epoch: 040, Train Loss: 1.343, Val f1_micro: 0.261
Epoch: 060, Train Loss: 1.246, Val f1_micro: 0.267
Epoch: 080, Train Loss: 1.117, Val f1_micro: 0.272
Epoch: 100, Train Loss: 1.078, Val f1_micro: 0.272
Epoch: 120, Train Loss: 1.039, Val f1_micro: 0.280
Epoch: 140, Train Loss: 0.982, Val f1_micro: 0.278
Epoch: 160, Train Loss: 0.957, Val f1_micro: 0.284
Epoch: 180, Train Loss: 0.944, Val f1_micro: 0.284
Epoch: 200, Train Loss: 0.898, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.891, Val f1_micro: 0.289
Epoch: 240, Train Loss: 0.861, Val f1_micro: 0.288
Epoch: 260, Train Loss: 0.836, Val f1_micro: 0.295
Epoch: 280, Train Loss: 0.824, Val f1_micro: 0.295
Epoch: 300, Train Loss: 0.816, Val f1_micro: 0.294
Epoch: 320, Train Loss: 0.791, Val f1_micro: 0.300
Epoch: 340, Train Loss: 0.802, Val f1_micro: 0.297
Epoch: 360, Train Loss: 0.794, Val f1_micro: 0.296
Epoch: 380, Train Loss: 0.773, Val f1_micro: 0.300
Epoch: 400, Train Loss: 0.776, Val f1_micro: 0.302
Epoch: 420, Train Loss: 0.772, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.746, Val f1_micro: 0.303
Epoch: 460, Train Loss: 0.753, Val f1_micro: 0.295
Epoch: 480, Train Loss: 0.736, Val f1_micro: 0.303
Epoch: 500, Train Loss: 0.757, Val f1_micro: 0.307
f1-micro: 0.307, f1-macro: 0.297, f1-weighted: 0.303, , roc-auc: 0.676
##### RUN 5 #####
Epoch: 020, Train Loss: 1.619, Val f1_micro: 0.221
Epoch: 040, Train Loss: 1.333, Val f1_micro: 0.259
Epoch: 060, Train Loss: 1.214, Val f1_micro: 0.267
Epoch: 080, Train Loss: 1.149, Val f1_micro: 0.273
Epoch: 100, Train Loss: 1.086, Val f1_micro: 0.278
Epoch: 120, Train Loss: 1.037, Val f1_micro: 0.279
Epoch: 140, Train Loss: 0.988, Val f1_micro: 0.278
Epoch: 160, Train Loss: 0.943, Val f1_micro: 0.289
Epoch: 180, Train Loss: 0.941, Val f1_micro: 0.290
Epoch: 200, Train Loss: 0.910, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.873, Val f1_micro: 0.287
Epoch: 240, Train Loss: 0.853, Val f1_micro: 0.292
Epoch: 260, Train Loss: 0.825, Val f1_micro: 0.293
Epoch: 280, Train Loss: 0.821, Val f1_micro: 0.294
Epoch: 300, Train Loss: 0.804, Val f1_micro: 0.291
Epoch: 320, Train Loss: 0.804, Val f1_micro: 0.290
Epoch: 340, Train Loss: 0.804, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.785, Val f1_micro: 0.299
Epoch: 380, Train Loss: 0.766, Val f1_micro: 0.295
Epoch: 400, Train Loss: 0.760, Val f1_micro: 0.295
Epoch: 420, Train Loss: 0.753, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.755, Val f1_micro: 0.294
Epoch: 460, Train Loss: 0.748, Val f1_micro: 0.299
Epoch: 480, Train Loss: 0.744, Val f1_micro: 0.301
Epoch: 500, Train Loss: 0.736, Val f1_micro: 0.301
f1-micro: 0.301, f1-macro: 0.293, f1-weighted: 0.299, , roc-auc: 0.674
########## Hyperparameters combination ##########
(512, 0.4, 0.01, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.702, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.573, Val f1_micro: 0.231
Epoch: 060, Train Loss: 1.570, Val f1_micro: 0.235
Epoch: 080, Train Loss: 1.573, Val f1_micro: 0.233
Epoch: 100, Train Loss: 1.571, Val f1_micro: 0.230
Epoch: 120, Train Loss: 1.594, Val f1_micro: 0.226
Epoch: 140, Train Loss: 1.575, Val f1_micro: 0.230
Epoch: 160, Train Loss: 1.585, Val f1_micro: 0.230
Epoch: 180, Train Loss: 1.593, Val f1_micro: 0.225
Epoch: 200, Train Loss: 1.587, Val f1_micro: 0.224
Epoch: 220, Train Loss: 1.583, Val f1_micro: 0.229
Epoch: 240, Train Loss: 1.593, Val f1_micro: 0.229
Epoch: 260, Train Loss: 1.585, Val f1_micro: 0.223
Epoch: 280, Train Loss: 1.597, Val f1_micro: 0.229
Epoch: 300, Train Loss: 1.581, Val f1_micro: 0.225
Epoch: 320, Train Loss: 1.590, Val f1_micro: 0.230
Epoch: 340, Train Loss: 1.583, Val f1_micro: 0.232
Epoch: 360, Train Loss: 1.579, Val f1_micro: 0.224
Epoch: 380, Train Loss: 1.581, Val f1_micro: 0.228
Epoch: 400, Train Loss: 1.584, Val f1_micro: 0.230
Epoch: 420, Train Loss: 1.596, Val f1_micro: 0.230
Epoch: 440, Train Loss: 1.593, Val f1_micro: 0.233
Epoch: 460, Train Loss: 1.571, Val f1_micro: 0.230
Epoch: 480, Train Loss: 1.573, Val f1_micro: 0.229
Epoch: 500, Train Loss: 1.567, Val f1_micro: 0.225
f1-micro: 0.225, f1-macro: 0.192, f1-weighted: 0.193, , roc-auc: 0.643
##### RUN 2 #####
Epoch: 020, Train Loss: 1.692, Val f1_micro: 0.217
Epoch: 040, Train Loss: 1.586, Val f1_micro: 0.240
Epoch: 060, Train Loss: 1.572, Val f1_micro: 0.230
Epoch: 080, Train Loss: 1.573, Val f1_micro: 0.230
Epoch: 100, Train Loss: 1.577, Val f1_micro: 0.230
Epoch: 120, Train Loss: 1.583, Val f1_micro: 0.223
Epoch: 140, Train Loss: 1.588, Val f1_micro: 0.226
Epoch: 160, Train Loss: 1.598, Val f1_micro: 0.229
Epoch: 180, Train Loss: 1.589, Val f1_micro: 0.230
Epoch: 200, Train Loss: 1.589, Val f1_micro: 0.232
Epoch: 220, Train Loss: 1.592, Val f1_micro: 0.225
Epoch: 240, Train Loss: 1.578, Val f1_micro: 0.225
Epoch: 260, Train Loss: 1.591, Val f1_micro: 0.223
Epoch: 280, Train Loss: 1.589, Val f1_micro: 0.224
Epoch: 300, Train Loss: 1.582, Val f1_micro: 0.224
Epoch: 320, Train Loss: 1.589, Val f1_micro: 0.226
Epoch: 340, Train Loss: 1.587, Val f1_micro: 0.228
Epoch: 360, Train Loss: 1.578, Val f1_micro: 0.225
Epoch: 380, Train Loss: 1.577, Val f1_micro: 0.231
Epoch: 400, Train Loss: 1.579, Val f1_micro: 0.234
Epoch: 420, Train Loss: 1.563, Val f1_micro: 0.228
Epoch: 440, Train Loss: 1.574, Val f1_micro: 0.225
Epoch: 460, Train Loss: 1.557, Val f1_micro: 0.228
Epoch: 480, Train Loss: 1.576, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.575, Val f1_micro: 0.227
f1-micro: 0.227, f1-macro: 0.199, f1-weighted: 0.199, , roc-auc: 0.644
##### RUN 3 #####
Epoch: 020, Train Loss: 1.694, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.583, Val f1_micro: 0.229
Epoch: 060, Train Loss: 1.570, Val f1_micro: 0.229
Epoch: 080, Train Loss: 1.575, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.581, Val f1_micro: 0.227
Epoch: 120, Train Loss: 1.592, Val f1_micro: 0.229
Epoch: 140, Train Loss: 1.597, Val f1_micro: 0.226
Epoch: 160, Train Loss: 1.575, Val f1_micro: 0.226
Epoch: 180, Train Loss: 1.590, Val f1_micro: 0.229
Epoch: 200, Train Loss: 1.589, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.586, Val f1_micro: 0.226
Epoch: 240, Train Loss: 1.583, Val f1_micro: 0.224
Epoch: 260, Train Loss: 1.593, Val f1_micro: 0.228
Epoch: 280, Train Loss: 1.592, Val f1_micro: 0.227
Epoch: 300, Train Loss: 1.582, Val f1_micro: 0.225
Epoch: 320, Train Loss: 1.585, Val f1_micro: 0.229
Epoch: 340, Train Loss: 1.577, Val f1_micro: 0.230
Epoch: 360, Train Loss: 1.578, Val f1_micro: 0.217
Epoch: 380, Train Loss: 1.567, Val f1_micro: 0.227
Epoch: 400, Train Loss: 1.577, Val f1_micro: 0.233
Epoch: 420, Train Loss: 1.576, Val f1_micro: 0.230
Epoch: 440, Train Loss: 1.568, Val f1_micro: 0.227
Epoch: 460, Train Loss: 1.562, Val f1_micro: 0.226
Epoch: 480, Train Loss: 1.577, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.559, Val f1_micro: 0.232
f1-micro: 0.232, f1-macro: 0.196, f1-weighted: 0.194, , roc-auc: 0.644
##### RUN 4 #####
Epoch: 020, Train Loss: 1.701, Val f1_micro: 0.218
Epoch: 040, Train Loss: 1.591, Val f1_micro: 0.236
Epoch: 060, Train Loss: 1.566, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.570, Val f1_micro: 0.228
Epoch: 100, Train Loss: 1.572, Val f1_micro: 0.230
Epoch: 120, Train Loss: 1.592, Val f1_micro: 0.227
Epoch: 140, Train Loss: 1.589, Val f1_micro: 0.226
Epoch: 160, Train Loss: 1.589, Val f1_micro: 0.227
Epoch: 180, Train Loss: 1.584, Val f1_micro: 0.227
Epoch: 200, Train Loss: 1.586, Val f1_micro: 0.224
Epoch: 220, Train Loss: 1.585, Val f1_micro: 0.225
Epoch: 240, Train Loss: 1.586, Val f1_micro: 0.228
Epoch: 260, Train Loss: 1.580, Val f1_micro: 0.225
Epoch: 280, Train Loss: 1.582, Val f1_micro: 0.229
Epoch: 300, Train Loss: 1.585, Val f1_micro: 0.221
Epoch: 320, Train Loss: 1.579, Val f1_micro: 0.225
Epoch: 340, Train Loss: 1.569, Val f1_micro: 0.226
Epoch: 360, Train Loss: 1.576, Val f1_micro: 0.225
Epoch: 380, Train Loss: 1.575, Val f1_micro: 0.235
Epoch: 400, Train Loss: 1.565, Val f1_micro: 0.233
Epoch: 420, Train Loss: 1.589, Val f1_micro: 0.227
Epoch: 440, Train Loss: 1.572, Val f1_micro: 0.228
Epoch: 460, Train Loss: 1.567, Val f1_micro: 0.228
Epoch: 480, Train Loss: 1.580, Val f1_micro: 0.222
Epoch: 500, Train Loss: 1.574, Val f1_micro: 0.223
f1-micro: 0.223, f1-macro: 0.190, f1-weighted: 0.189, , roc-auc: 0.643
##### RUN 5 #####
Epoch: 020, Train Loss: 1.680, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.588, Val f1_micro: 0.235
Epoch: 060, Train Loss: 1.567, Val f1_micro: 0.230
Epoch: 080, Train Loss: 1.582, Val f1_micro: 0.228
Epoch: 100, Train Loss: 1.588, Val f1_micro: 0.236
Epoch: 120, Train Loss: 1.571, Val f1_micro: 0.221
Epoch: 140, Train Loss: 1.587, Val f1_micro: 0.226
Epoch: 160, Train Loss: 1.595, Val f1_micro: 0.233
Epoch: 180, Train Loss: 1.587, Val f1_micro: 0.226
Epoch: 200, Train Loss: 1.592, Val f1_micro: 0.228
Epoch: 220, Train Loss: 1.594, Val f1_micro: 0.227
Epoch: 240, Train Loss: 1.585, Val f1_micro: 0.231
Epoch: 260, Train Loss: 1.589, Val f1_micro: 0.229
Epoch: 280, Train Loss: 1.584, Val f1_micro: 0.227
Epoch: 300, Train Loss: 1.582, Val f1_micro: 0.226
Epoch: 320, Train Loss: 1.576, Val f1_micro: 0.223
Epoch: 340, Train Loss: 1.589, Val f1_micro: 0.229
Epoch: 360, Train Loss: 1.577, Val f1_micro: 0.233
Epoch: 380, Train Loss: 1.584, Val f1_micro: 0.229
Epoch: 400, Train Loss: 1.574, Val f1_micro: 0.234
Epoch: 420, Train Loss: 1.568, Val f1_micro: 0.222
Epoch: 440, Train Loss: 1.573, Val f1_micro: 0.235
Epoch: 460, Train Loss: 1.579, Val f1_micro: 0.229
Epoch: 480, Train Loss: 1.583, Val f1_micro: 0.227
Epoch: 500, Train Loss: 1.561, Val f1_micro: 0.220
f1-micro: 0.220, f1-macro: 0.189, f1-weighted: 0.189, , roc-auc: 0.644
########## Hyperparameters combination ##########
(512, 0.4, 0.05, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.012, Val f1_micro: 0.143
Epoch: 040, Train Loss: 1.895, Val f1_micro: 0.175
Epoch: 060, Train Loss: 1.775, Val f1_micro: 0.141
Epoch: 080, Train Loss: 1.631, Val f1_micro: 0.154
Epoch: 100, Train Loss: 1.526, Val f1_micro: 0.177
Epoch: 120, Train Loss: 1.394, Val f1_micro: 0.200
Epoch: 140, Train Loss: 1.293, Val f1_micro: 0.227
Epoch: 160, Train Loss: 1.186, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.104, Val f1_micro: 0.244
Epoch: 200, Train Loss: 1.048, Val f1_micro: 0.244
Epoch: 220, Train Loss: 0.964, Val f1_micro: 0.255
Epoch: 240, Train Loss: 0.894, Val f1_micro: 0.260
Epoch: 260, Train Loss: 0.851, Val f1_micro: 0.264
Epoch: 280, Train Loss: 0.808, Val f1_micro: 0.268
Epoch: 300, Train Loss: 0.715, Val f1_micro: 0.273
Epoch: 320, Train Loss: 0.700, Val f1_micro: 0.273
Epoch: 340, Train Loss: 0.666, Val f1_micro: 0.282
Epoch: 360, Train Loss: 0.637, Val f1_micro: 0.282
Epoch: 380, Train Loss: 0.589, Val f1_micro: 0.288
Epoch: 400, Train Loss: 0.608, Val f1_micro: 0.285
Epoch: 420, Train Loss: 0.544, Val f1_micro: 0.291
Epoch: 440, Train Loss: 0.526, Val f1_micro: 0.293
Epoch: 460, Train Loss: 0.475, Val f1_micro: 0.293
Epoch: 480, Train Loss: 0.470, Val f1_micro: 0.296
Epoch: 500, Train Loss: 0.463, Val f1_micro: 0.301
f1-micro: 0.301, f1-macro: 0.294, f1-weighted: 0.302, , roc-auc: 0.659
##### RUN 2 #####
Epoch: 020, Train Loss: 2.004, Val f1_micro: 0.107
Epoch: 040, Train Loss: 1.906, Val f1_micro: 0.174
Epoch: 060, Train Loss: 1.767, Val f1_micro: 0.139
Epoch: 080, Train Loss: 1.686, Val f1_micro: 0.149
Epoch: 100, Train Loss: 1.631, Val f1_micro: 0.187
Epoch: 120, Train Loss: 1.503, Val f1_micro: 0.208
Epoch: 140, Train Loss: 1.402, Val f1_micro: 0.212
Epoch: 160, Train Loss: 1.282, Val f1_micro: 0.222
Epoch: 180, Train Loss: 1.161, Val f1_micro: 0.247
Epoch: 200, Train Loss: 1.055, Val f1_micro: 0.247
Epoch: 220, Train Loss: 0.974, Val f1_micro: 0.263
Epoch: 240, Train Loss: 0.899, Val f1_micro: 0.262
Epoch: 260, Train Loss: 0.844, Val f1_micro: 0.272
Epoch: 280, Train Loss: 0.753, Val f1_micro: 0.278
Epoch: 300, Train Loss: 0.695, Val f1_micro: 0.283
Epoch: 320, Train Loss: 0.678, Val f1_micro: 0.283
Epoch: 340, Train Loss: 0.668, Val f1_micro: 0.279
Epoch: 360, Train Loss: 0.621, Val f1_micro: 0.285
Epoch: 380, Train Loss: 0.568, Val f1_micro: 0.290
Epoch: 400, Train Loss: 0.506, Val f1_micro: 0.296
Epoch: 420, Train Loss: 0.502, Val f1_micro: 0.295
Epoch: 440, Train Loss: 0.479, Val f1_micro: 0.299
Epoch: 460, Train Loss: 0.500, Val f1_micro: 0.293
Epoch: 480, Train Loss: 0.491, Val f1_micro: 0.298
Epoch: 500, Train Loss: 0.448, Val f1_micro: 0.293
f1-micro: 0.293, f1-macro: 0.290, f1-weighted: 0.296, , roc-auc: 0.666
##### RUN 3 #####
Epoch: 020, Train Loss: 1.975, Val f1_micro: 0.109
Epoch: 040, Train Loss: 1.844, Val f1_micro: 0.195
Epoch: 060, Train Loss: 1.722, Val f1_micro: 0.174
Epoch: 080, Train Loss: 1.570, Val f1_micro: 0.184
Epoch: 100, Train Loss: 1.410, Val f1_micro: 0.195
Epoch: 120, Train Loss: 1.322, Val f1_micro: 0.212
Epoch: 140, Train Loss: 1.218, Val f1_micro: 0.228
Epoch: 160, Train Loss: 1.109, Val f1_micro: 0.238
Epoch: 180, Train Loss: 1.016, Val f1_micro: 0.250
Epoch: 200, Train Loss: 0.960, Val f1_micro: 0.261
Epoch: 220, Train Loss: 0.884, Val f1_micro: 0.264
Epoch: 240, Train Loss: 0.852, Val f1_micro: 0.267
Epoch: 260, Train Loss: 0.772, Val f1_micro: 0.273
Epoch: 280, Train Loss: 0.693, Val f1_micro: 0.273
Epoch: 300, Train Loss: 0.670, Val f1_micro: 0.282
Epoch: 320, Train Loss: 0.646, Val f1_micro: 0.286
Epoch: 340, Train Loss: 0.630, Val f1_micro: 0.287
Epoch: 360, Train Loss: 0.574, Val f1_micro: 0.290
Epoch: 380, Train Loss: 0.548, Val f1_micro: 0.290
Epoch: 400, Train Loss: 0.536, Val f1_micro: 0.292
Epoch: 420, Train Loss: 0.537, Val f1_micro: 0.289
Epoch: 440, Train Loss: 0.476, Val f1_micro: 0.294
Epoch: 460, Train Loss: 0.502, Val f1_micro: 0.299
Epoch: 480, Train Loss: 0.479, Val f1_micro: 0.302
Epoch: 500, Train Loss: 0.448, Val f1_micro: 0.299
f1-micro: 0.299, f1-macro: 0.293, f1-weighted: 0.299, , roc-auc: 0.663
##### RUN 4 #####
Epoch: 020, Train Loss: 2.025, Val f1_micro: 0.104
Epoch: 040, Train Loss: 1.928, Val f1_micro: 0.174
Epoch: 060, Train Loss: 1.802, Val f1_micro: 0.173
Epoch: 080, Train Loss: 1.636, Val f1_micro: 0.184
Epoch: 100, Train Loss: 1.539, Val f1_micro: 0.208
Epoch: 120, Train Loss: 1.411, Val f1_micro: 0.214
Epoch: 140, Train Loss: 1.311, Val f1_micro: 0.222
Epoch: 160, Train Loss: 1.222, Val f1_micro: 0.223
Epoch: 180, Train Loss: 1.109, Val f1_micro: 0.235
Epoch: 200, Train Loss: 1.065, Val f1_micro: 0.249
Epoch: 220, Train Loss: 0.956, Val f1_micro: 0.253
Epoch: 240, Train Loss: 0.903, Val f1_micro: 0.253
Epoch: 260, Train Loss: 0.828, Val f1_micro: 0.268
Epoch: 280, Train Loss: 0.789, Val f1_micro: 0.276
Epoch: 300, Train Loss: 0.738, Val f1_micro: 0.273
Epoch: 320, Train Loss: 0.695, Val f1_micro: 0.278
Epoch: 340, Train Loss: 0.667, Val f1_micro: 0.274
Epoch: 360, Train Loss: 0.614, Val f1_micro: 0.285
Epoch: 380, Train Loss: 0.638, Val f1_micro: 0.287
Epoch: 400, Train Loss: 0.568, Val f1_micro: 0.285
Epoch: 420, Train Loss: 0.526, Val f1_micro: 0.285
Epoch: 440, Train Loss: 0.510, Val f1_micro: 0.294
Epoch: 460, Train Loss: 0.519, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.475, Val f1_micro: 0.295
Epoch: 500, Train Loss: 0.501, Val f1_micro: 0.293
f1-micro: 0.293, f1-macro: 0.288, f1-weighted: 0.296, , roc-auc: 0.661
##### RUN 5 #####
Epoch: 020, Train Loss: 2.000, Val f1_micro: 0.103
Epoch: 040, Train Loss: 1.851, Val f1_micro: 0.182
Epoch: 060, Train Loss: 1.700, Val f1_micro: 0.150
Epoch: 080, Train Loss: 1.554, Val f1_micro: 0.195
Epoch: 100, Train Loss: 1.439, Val f1_micro: 0.211
Epoch: 120, Train Loss: 1.312, Val f1_micro: 0.226
Epoch: 140, Train Loss: 1.207, Val f1_micro: 0.239
Epoch: 160, Train Loss: 1.088, Val f1_micro: 0.241
Epoch: 180, Train Loss: 0.983, Val f1_micro: 0.253
Epoch: 200, Train Loss: 0.955, Val f1_micro: 0.252
Epoch: 220, Train Loss: 0.866, Val f1_micro: 0.256
Epoch: 240, Train Loss: 0.834, Val f1_micro: 0.269
Epoch: 260, Train Loss: 0.764, Val f1_micro: 0.276
Epoch: 280, Train Loss: 0.714, Val f1_micro: 0.277
Epoch: 300, Train Loss: 0.664, Val f1_micro: 0.275
Epoch: 320, Train Loss: 0.663, Val f1_micro: 0.288
Epoch: 340, Train Loss: 0.613, Val f1_micro: 0.287
Epoch: 360, Train Loss: 0.606, Val f1_micro: 0.279
Epoch: 380, Train Loss: 0.567, Val f1_micro: 0.284
Epoch: 400, Train Loss: 0.522, Val f1_micro: 0.285
Epoch: 420, Train Loss: 0.516, Val f1_micro: 0.285
Epoch: 440, Train Loss: 0.513, Val f1_micro: 0.292
Epoch: 460, Train Loss: 0.470, Val f1_micro: 0.293
Epoch: 480, Train Loss: 0.449, Val f1_micro: 0.295
Epoch: 500, Train Loss: 0.442, Val f1_micro: 0.296
f1-micro: 0.296, f1-macro: 0.290, f1-weighted: 0.296, , roc-auc: 0.652
########## Hyperparameters combination ##########
(512, 0.4, 0.05, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.015, Val f1_micro: 0.108
Epoch: 040, Train Loss: 1.872, Val f1_micro: 0.138
Epoch: 060, Train Loss: 1.762, Val f1_micro: 0.147
Epoch: 080, Train Loss: 1.659, Val f1_micro: 0.184
Epoch: 100, Train Loss: 1.544, Val f1_micro: 0.206
Epoch: 120, Train Loss: 1.454, Val f1_micro: 0.213
Epoch: 140, Train Loss: 1.377, Val f1_micro: 0.221
Epoch: 160, Train Loss: 1.298, Val f1_micro: 0.223
Epoch: 180, Train Loss: 1.239, Val f1_micro: 0.245
Epoch: 200, Train Loss: 1.180, Val f1_micro: 0.252
Epoch: 220, Train Loss: 1.154, Val f1_micro: 0.251
Epoch: 240, Train Loss: 1.116, Val f1_micro: 0.242
Epoch: 260, Train Loss: 1.066, Val f1_micro: 0.259
Epoch: 280, Train Loss: 1.006, Val f1_micro: 0.265
Epoch: 300, Train Loss: 0.967, Val f1_micro: 0.255
Epoch: 320, Train Loss: 0.953, Val f1_micro: 0.267
Epoch: 340, Train Loss: 0.937, Val f1_micro: 0.267
Epoch: 360, Train Loss: 0.915, Val f1_micro: 0.271
Epoch: 380, Train Loss: 0.925, Val f1_micro: 0.264
Epoch: 400, Train Loss: 0.881, Val f1_micro: 0.275
Epoch: 420, Train Loss: 0.918, Val f1_micro: 0.261
Epoch: 440, Train Loss: 0.880, Val f1_micro: 0.269
Epoch: 460, Train Loss: 0.836, Val f1_micro: 0.276
Epoch: 480, Train Loss: 0.876, Val f1_micro: 0.261
Epoch: 500, Train Loss: 0.795, Val f1_micro: 0.276
f1-micro: 0.276, f1-macro: 0.266, f1-weighted: 0.271, , roc-auc: 0.657
##### RUN 2 #####
Epoch: 020, Train Loss: 2.040, Val f1_micro: 0.146
Epoch: 040, Train Loss: 1.904, Val f1_micro: 0.130
Epoch: 060, Train Loss: 1.813, Val f1_micro: 0.143
Epoch: 080, Train Loss: 1.721, Val f1_micro: 0.159
Epoch: 100, Train Loss: 1.646, Val f1_micro: 0.169
Epoch: 120, Train Loss: 1.568, Val f1_micro: 0.188
Epoch: 140, Train Loss: 1.505, Val f1_micro: 0.212
Epoch: 160, Train Loss: 1.436, Val f1_micro: 0.227
Epoch: 180, Train Loss: 1.336, Val f1_micro: 0.235
Epoch: 200, Train Loss: 1.241, Val f1_micro: 0.236
Epoch: 220, Train Loss: 1.216, Val f1_micro: 0.240
Epoch: 240, Train Loss: 1.169, Val f1_micro: 0.251
Epoch: 260, Train Loss: 1.118, Val f1_micro: 0.252
Epoch: 280, Train Loss: 1.056, Val f1_micro: 0.256
Epoch: 300, Train Loss: 1.018, Val f1_micro: 0.245
Epoch: 320, Train Loss: 1.000, Val f1_micro: 0.262
Epoch: 340, Train Loss: 0.959, Val f1_micro: 0.268
Epoch: 360, Train Loss: 0.917, Val f1_micro: 0.271
Epoch: 380, Train Loss: 0.900, Val f1_micro: 0.271
Epoch: 400, Train Loss: 0.901, Val f1_micro: 0.263
Epoch: 420, Train Loss: 0.828, Val f1_micro: 0.267
Epoch: 440, Train Loss: 0.828, Val f1_micro: 0.280
Epoch: 460, Train Loss: 0.825, Val f1_micro: 0.274
Epoch: 480, Train Loss: 0.805, Val f1_micro: 0.281
Epoch: 500, Train Loss: 0.794, Val f1_micro: 0.288
f1-micro: 0.288, f1-macro: 0.280, f1-weighted: 0.286, , roc-auc: 0.659
##### RUN 3 #####
Epoch: 020, Train Loss: 2.027, Val f1_micro: 0.102
Epoch: 040, Train Loss: 1.920, Val f1_micro: 0.179
Epoch: 060, Train Loss: 1.791, Val f1_micro: 0.157
Epoch: 080, Train Loss: 1.682, Val f1_micro: 0.171
Epoch: 100, Train Loss: 1.593, Val f1_micro: 0.201
Epoch: 120, Train Loss: 1.511, Val f1_micro: 0.216
Epoch: 140, Train Loss: 1.420, Val f1_micro: 0.224
Epoch: 160, Train Loss: 1.334, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.288, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.201, Val f1_micro: 0.247
Epoch: 220, Train Loss: 1.142, Val f1_micro: 0.237
Epoch: 240, Train Loss: 1.109, Val f1_micro: 0.250
Epoch: 260, Train Loss: 1.067, Val f1_micro: 0.260
Epoch: 280, Train Loss: 1.049, Val f1_micro: 0.257
Epoch: 300, Train Loss: 0.986, Val f1_micro: 0.269
Epoch: 320, Train Loss: 0.948, Val f1_micro: 0.268
Epoch: 340, Train Loss: 0.966, Val f1_micro: 0.266
Epoch: 360, Train Loss: 0.896, Val f1_micro: 0.267
Epoch: 380, Train Loss: 0.916, Val f1_micro: 0.275
Epoch: 400, Train Loss: 0.889, Val f1_micro: 0.275
Epoch: 420, Train Loss: 0.854, Val f1_micro: 0.277
Epoch: 440, Train Loss: 0.850, Val f1_micro: 0.287
Epoch: 460, Train Loss: 0.861, Val f1_micro: 0.280
Epoch: 480, Train Loss: 0.834, Val f1_micro: 0.270
Epoch: 500, Train Loss: 0.884, Val f1_micro: 0.269
f1-micro: 0.269, f1-macro: 0.261, f1-weighted: 0.263, , roc-auc: 0.659
##### RUN 4 #####
Epoch: 020, Train Loss: 2.027, Val f1_micro: 0.103
Epoch: 040, Train Loss: 1.926, Val f1_micro: 0.173
Epoch: 060, Train Loss: 1.829, Val f1_micro: 0.138
Epoch: 080, Train Loss: 1.706, Val f1_micro: 0.152
Epoch: 100, Train Loss: 1.613, Val f1_micro: 0.206
Epoch: 120, Train Loss: 1.513, Val f1_micro: 0.211
Epoch: 140, Train Loss: 1.411, Val f1_micro: 0.214
Epoch: 160, Train Loss: 1.393, Val f1_micro: 0.222
Epoch: 180, Train Loss: 1.272, Val f1_micro: 0.227
Epoch: 200, Train Loss: 1.225, Val f1_micro: 0.239
Epoch: 220, Train Loss: 1.147, Val f1_micro: 0.250
Epoch: 240, Train Loss: 1.133, Val f1_micro: 0.249
Epoch: 260, Train Loss: 1.061, Val f1_micro: 0.256
Epoch: 280, Train Loss: 1.040, Val f1_micro: 0.256
Epoch: 300, Train Loss: 0.995, Val f1_micro: 0.262
Epoch: 320, Train Loss: 0.972, Val f1_micro: 0.272
Epoch: 340, Train Loss: 0.928, Val f1_micro: 0.273
Epoch: 360, Train Loss: 0.888, Val f1_micro: 0.263
Epoch: 380, Train Loss: 0.839, Val f1_micro: 0.281
Epoch: 400, Train Loss: 0.886, Val f1_micro: 0.256
Epoch: 420, Train Loss: 0.833, Val f1_micro: 0.277
Epoch: 440, Train Loss: 0.773, Val f1_micro: 0.287
Epoch: 460, Train Loss: 0.812, Val f1_micro: 0.263
Epoch: 480, Train Loss: 0.767, Val f1_micro: 0.288
Epoch: 500, Train Loss: 0.765, Val f1_micro: 0.292
f1-micro: 0.292, f1-macro: 0.283, f1-weighted: 0.288, , roc-auc: 0.658
##### RUN 5 #####
Epoch: 020, Train Loss: 2.038, Val f1_micro: 0.097
Epoch: 040, Train Loss: 1.902, Val f1_micro: 0.177
Epoch: 060, Train Loss: 1.799, Val f1_micro: 0.142
Epoch: 080, Train Loss: 1.712, Val f1_micro: 0.170
Epoch: 100, Train Loss: 1.607, Val f1_micro: 0.205
Epoch: 120, Train Loss: 1.506, Val f1_micro: 0.218
Epoch: 140, Train Loss: 1.426, Val f1_micro: 0.221
Epoch: 160, Train Loss: 1.350, Val f1_micro: 0.226
Epoch: 180, Train Loss: 1.244, Val f1_micro: 0.229
Epoch: 200, Train Loss: 1.207, Val f1_micro: 0.247
Epoch: 220, Train Loss: 1.176, Val f1_micro: 0.230
Epoch: 240, Train Loss: 1.070, Val f1_micro: 0.259
Epoch: 260, Train Loss: 1.029, Val f1_micro: 0.261
Epoch: 280, Train Loss: 0.999, Val f1_micro: 0.263
Epoch: 300, Train Loss: 0.936, Val f1_micro: 0.270
Epoch: 320, Train Loss: 0.909, Val f1_micro: 0.275
Epoch: 340, Train Loss: 0.912, Val f1_micro: 0.264
Epoch: 360, Train Loss: 0.885, Val f1_micro: 0.270
Epoch: 380, Train Loss: 0.912, Val f1_micro: 0.268
Epoch: 400, Train Loss: 0.807, Val f1_micro: 0.287
Epoch: 420, Train Loss: 0.817, Val f1_micro: 0.285
Epoch: 440, Train Loss: 0.783, Val f1_micro: 0.268
Epoch: 460, Train Loss: 0.810, Val f1_micro: 0.277
Epoch: 480, Train Loss: 0.750, Val f1_micro: 0.282
Epoch: 500, Train Loss: 0.749, Val f1_micro: 0.285
f1-micro: 0.285, f1-macro: 0.276, f1-weighted: 0.281, , roc-auc: 0.659
########## Hyperparameters combination ##########
(512, 0.4, 0.05, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.041, Val f1_micro: 0.105
Epoch: 040, Train Loss: 1.950, Val f1_micro: 0.175
Epoch: 060, Train Loss: 1.867, Val f1_micro: 0.180
Epoch: 080, Train Loss: 1.792, Val f1_micro: 0.177
Epoch: 100, Train Loss: 1.715, Val f1_micro: 0.188
Epoch: 120, Train Loss: 1.667, Val f1_micro: 0.187
Epoch: 140, Train Loss: 1.594, Val f1_micro: 0.200
Epoch: 160, Train Loss: 1.540, Val f1_micro: 0.197
Epoch: 180, Train Loss: 1.503, Val f1_micro: 0.202
Epoch: 200, Train Loss: 1.459, Val f1_micro: 0.206
Epoch: 220, Train Loss: 1.394, Val f1_micro: 0.218
Epoch: 240, Train Loss: 1.384, Val f1_micro: 0.211
Epoch: 260, Train Loss: 1.386, Val f1_micro: 0.222
Epoch: 280, Train Loss: 1.304, Val f1_micro: 0.235
Epoch: 300, Train Loss: 1.306, Val f1_micro: 0.229
Epoch: 320, Train Loss: 1.268, Val f1_micro: 0.236
Epoch: 340, Train Loss: 1.283, Val f1_micro: 0.230
Epoch: 360, Train Loss: 1.194, Val f1_micro: 0.249
Epoch: 380, Train Loss: 1.204, Val f1_micro: 0.245
Epoch: 400, Train Loss: 1.166, Val f1_micro: 0.253
Epoch: 420, Train Loss: 1.180, Val f1_micro: 0.235
Epoch: 440, Train Loss: 1.186, Val f1_micro: 0.250
Epoch: 460, Train Loss: 1.167, Val f1_micro: 0.254
Epoch: 480, Train Loss: 1.112, Val f1_micro: 0.258
Epoch: 500, Train Loss: 1.102, Val f1_micro: 0.263
f1-micro: 0.263, f1-macro: 0.249, f1-weighted: 0.250, , roc-auc: 0.651
##### RUN 2 #####
Epoch: 020, Train Loss: 2.027, Val f1_micro: 0.103
Epoch: 040, Train Loss: 1.943, Val f1_micro: 0.174
Epoch: 060, Train Loss: 1.879, Val f1_micro: 0.140
Epoch: 080, Train Loss: 1.784, Val f1_micro: 0.157
Epoch: 100, Train Loss: 1.698, Val f1_micro: 0.205
Epoch: 120, Train Loss: 1.588, Val f1_micro: 0.210
Epoch: 140, Train Loss: 1.541, Val f1_micro: 0.216
Epoch: 160, Train Loss: 1.508, Val f1_micro: 0.200
Epoch: 180, Train Loss: 1.386, Val f1_micro: 0.227
Epoch: 200, Train Loss: 1.377, Val f1_micro: 0.223
Epoch: 220, Train Loss: 1.335, Val f1_micro: 0.233
Epoch: 240, Train Loss: 1.301, Val f1_micro: 0.248
Epoch: 260, Train Loss: 1.263, Val f1_micro: 0.245
Epoch: 280, Train Loss: 1.249, Val f1_micro: 0.255
Epoch: 300, Train Loss: 1.217, Val f1_micro: 0.244
Epoch: 320, Train Loss: 1.195, Val f1_micro: 0.249
Epoch: 340, Train Loss: 1.146, Val f1_micro: 0.257
Epoch: 360, Train Loss: 1.139, Val f1_micro: 0.263
Epoch: 380, Train Loss: 1.107, Val f1_micro: 0.264
Epoch: 400, Train Loss: 1.151, Val f1_micro: 0.247
Epoch: 420, Train Loss: 1.067, Val f1_micro: 0.264
Epoch: 440, Train Loss: 1.099, Val f1_micro: 0.262
Epoch: 460, Train Loss: 1.082, Val f1_micro: 0.235
Epoch: 480, Train Loss: 1.064, Val f1_micro: 0.273
Epoch: 500, Train Loss: 1.039, Val f1_micro: 0.271
f1-micro: 0.271, f1-macro: 0.261, f1-weighted: 0.265, , roc-auc: 0.665
##### RUN 3 #####
Epoch: 020, Train Loss: 2.043, Val f1_micro: 0.102
Epoch: 040, Train Loss: 1.979, Val f1_micro: 0.171
Epoch: 060, Train Loss: 1.907, Val f1_micro: 0.131
Epoch: 080, Train Loss: 1.838, Val f1_micro: 0.133
Epoch: 100, Train Loss: 1.758, Val f1_micro: 0.185
Epoch: 120, Train Loss: 1.646, Val f1_micro: 0.194
Epoch: 140, Train Loss: 1.558, Val f1_micro: 0.211
Epoch: 160, Train Loss: 1.544, Val f1_micro: 0.218
Epoch: 180, Train Loss: 1.442, Val f1_micro: 0.220
Epoch: 200, Train Loss: 1.389, Val f1_micro: 0.232
Epoch: 220, Train Loss: 1.379, Val f1_micro: 0.232
Epoch: 240, Train Loss: 1.323, Val f1_micro: 0.248
Epoch: 260, Train Loss: 1.339, Val f1_micro: 0.239
Epoch: 280, Train Loss: 1.298, Val f1_micro: 0.251
Epoch: 300, Train Loss: 1.252, Val f1_micro: 0.255
Epoch: 320, Train Loss: 1.277, Val f1_micro: 0.245
Epoch: 340, Train Loss: 1.263, Val f1_micro: 0.244
Epoch: 360, Train Loss: 1.217, Val f1_micro: 0.241
Epoch: 380, Train Loss: 1.203, Val f1_micro: 0.258
Epoch: 400, Train Loss: 1.137, Val f1_micro: 0.255
Epoch: 420, Train Loss: 1.165, Val f1_micro: 0.248
Epoch: 440, Train Loss: 1.144, Val f1_micro: 0.259
Epoch: 460, Train Loss: 1.134, Val f1_micro: 0.255
Epoch: 480, Train Loss: 1.070, Val f1_micro: 0.263
Epoch: 500, Train Loss: 1.092, Val f1_micro: 0.260
f1-micro: 0.260, f1-macro: 0.243, f1-weighted: 0.245, , roc-auc: 0.656
##### RUN 4 #####
Epoch: 020, Train Loss: 2.035, Val f1_micro: 0.104
Epoch: 040, Train Loss: 1.952, Val f1_micro: 0.175
Epoch: 060, Train Loss: 1.853, Val f1_micro: 0.134
Epoch: 080, Train Loss: 1.770, Val f1_micro: 0.169
Epoch: 100, Train Loss: 1.666, Val f1_micro: 0.206
Epoch: 120, Train Loss: 1.593, Val f1_micro: 0.199
Epoch: 140, Train Loss: 1.498, Val f1_micro: 0.217
Epoch: 160, Train Loss: 1.464, Val f1_micro: 0.225
Epoch: 180, Train Loss: 1.401, Val f1_micro: 0.224
Epoch: 200, Train Loss: 1.372, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.326, Val f1_micro: 0.243
Epoch: 240, Train Loss: 1.315, Val f1_micro: 0.241
Epoch: 260, Train Loss: 1.267, Val f1_micro: 0.237
Epoch: 280, Train Loss: 1.217, Val f1_micro: 0.240
Epoch: 300, Train Loss: 1.196, Val f1_micro: 0.249
Epoch: 320, Train Loss: 1.168, Val f1_micro: 0.247
Epoch: 340, Train Loss: 1.182, Val f1_micro: 0.249
Epoch: 360, Train Loss: 1.153, Val f1_micro: 0.248
Epoch: 380, Train Loss: 1.194, Val f1_micro: 0.249
Epoch: 400, Train Loss: 1.137, Val f1_micro: 0.233
Epoch: 420, Train Loss: 1.120, Val f1_micro: 0.266
Epoch: 440, Train Loss: 1.104, Val f1_micro: 0.258
Epoch: 460, Train Loss: 1.109, Val f1_micro: 0.243
Epoch: 480, Train Loss: 1.092, Val f1_micro: 0.260
Epoch: 500, Train Loss: 1.082, Val f1_micro: 0.264
f1-micro: 0.264, f1-macro: 0.250, f1-weighted: 0.252, , roc-auc: 0.652
##### RUN 5 #####
Epoch: 020, Train Loss: 2.023, Val f1_micro: 0.105
Epoch: 040, Train Loss: 1.951, Val f1_micro: 0.174
Epoch: 060, Train Loss: 1.894, Val f1_micro: 0.131
Epoch: 080, Train Loss: 1.821, Val f1_micro: 0.142
Epoch: 100, Train Loss: 1.721, Val f1_micro: 0.198
Epoch: 120, Train Loss: 1.636, Val f1_micro: 0.203
Epoch: 140, Train Loss: 1.537, Val f1_micro: 0.210
Epoch: 160, Train Loss: 1.506, Val f1_micro: 0.215
Epoch: 180, Train Loss: 1.442, Val f1_micro: 0.216
Epoch: 200, Train Loss: 1.447, Val f1_micro: 0.223
Epoch: 220, Train Loss: 1.389, Val f1_micro: 0.236
Epoch: 240, Train Loss: 1.376, Val f1_micro: 0.246
Epoch: 260, Train Loss: 1.308, Val f1_micro: 0.229
Epoch: 280, Train Loss: 1.312, Val f1_micro: 0.233
Epoch: 300, Train Loss: 1.278, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.243, Val f1_micro: 0.240
Epoch: 340, Train Loss: 1.244, Val f1_micro: 0.230
Epoch: 360, Train Loss: 1.207, Val f1_micro: 0.250
Epoch: 380, Train Loss: 1.181, Val f1_micro: 0.239
Epoch: 400, Train Loss: 1.214, Val f1_micro: 0.239
Epoch: 420, Train Loss: 1.209, Val f1_micro: 0.248
Epoch: 440, Train Loss: 1.154, Val f1_micro: 0.242
Epoch: 460, Train Loss: 1.137, Val f1_micro: 0.243
Epoch: 480, Train Loss: 1.139, Val f1_micro: 0.255
Epoch: 500, Train Loss: 1.091, Val f1_micro: 0.264
f1-micro: 0.264, f1-macro: 0.251, f1-weighted: 0.254, , roc-auc: 0.651
########## Hyperparameters combination ##########
(512, 0.4, 0.05, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.058, Val f1_micro: 0.099
Epoch: 040, Train Loss: 2.012, Val f1_micro: 0.119
Epoch: 060, Train Loss: 1.960, Val f1_micro: 0.174
Epoch: 080, Train Loss: 1.892, Val f1_micro: 0.168
Epoch: 100, Train Loss: 1.835, Val f1_micro: 0.202
Epoch: 120, Train Loss: 1.816, Val f1_micro: 0.181
Epoch: 140, Train Loss: 1.787, Val f1_micro: 0.203
Epoch: 160, Train Loss: 1.782, Val f1_micro: 0.213
Epoch: 180, Train Loss: 1.763, Val f1_micro: 0.212
Epoch: 200, Train Loss: 1.772, Val f1_micro: 0.215
Epoch: 220, Train Loss: 1.766, Val f1_micro: 0.209
Epoch: 240, Train Loss: 1.752, Val f1_micro: 0.209
Epoch: 260, Train Loss: 1.754, Val f1_micro: 0.203
Epoch: 280, Train Loss: 1.734, Val f1_micro: 0.212
Epoch: 300, Train Loss: 1.739, Val f1_micro: 0.189
Epoch: 320, Train Loss: 1.758, Val f1_micro: 0.196
Epoch: 340, Train Loss: 1.747, Val f1_micro: 0.202
Epoch: 360, Train Loss: 1.744, Val f1_micro: 0.217
Epoch: 380, Train Loss: 1.737, Val f1_micro: 0.208
Epoch: 400, Train Loss: 1.723, Val f1_micro: 0.202
Epoch: 420, Train Loss: 1.774, Val f1_micro: 0.206
Epoch: 440, Train Loss: 1.737, Val f1_micro: 0.213
Epoch: 460, Train Loss: 1.724, Val f1_micro: 0.218
Epoch: 480, Train Loss: 1.748, Val f1_micro: 0.214
Epoch: 500, Train Loss: 1.733, Val f1_micro: 0.215
f1-micro: 0.215, f1-macro: 0.169, f1-weighted: 0.169, , roc-auc: 0.619
##### RUN 2 #####
Epoch: 020, Train Loss: 2.054, Val f1_micro: 0.098
Epoch: 040, Train Loss: 2.020, Val f1_micro: 0.162
Epoch: 060, Train Loss: 1.970, Val f1_micro: 0.173
Epoch: 080, Train Loss: 1.903, Val f1_micro: 0.177
Epoch: 100, Train Loss: 1.868, Val f1_micro: 0.190
Epoch: 120, Train Loss: 1.826, Val f1_micro: 0.189
Epoch: 140, Train Loss: 1.796, Val f1_micro: 0.187
Epoch: 160, Train Loss: 1.785, Val f1_micro: 0.214
Epoch: 180, Train Loss: 1.768, Val f1_micro: 0.205
Epoch: 200, Train Loss: 1.770, Val f1_micro: 0.204
Epoch: 220, Train Loss: 1.771, Val f1_micro: 0.204
Epoch: 240, Train Loss: 1.765, Val f1_micro: 0.203
Epoch: 260, Train Loss: 1.765, Val f1_micro: 0.215
Epoch: 280, Train Loss: 1.765, Val f1_micro: 0.212
Epoch: 300, Train Loss: 1.725, Val f1_micro: 0.217
Epoch: 320, Train Loss: 1.744, Val f1_micro: 0.217
Epoch: 340, Train Loss: 1.746, Val f1_micro: 0.196
Epoch: 360, Train Loss: 1.743, Val f1_micro: 0.195
Epoch: 380, Train Loss: 1.749, Val f1_micro: 0.182
Epoch: 400, Train Loss: 1.755, Val f1_micro: 0.210
Epoch: 420, Train Loss: 1.728, Val f1_micro: 0.201
Epoch: 440, Train Loss: 1.727, Val f1_micro: 0.200
Epoch: 460, Train Loss: 1.753, Val f1_micro: 0.193
Epoch: 480, Train Loss: 1.743, Val f1_micro: 0.213
Epoch: 500, Train Loss: 1.723, Val f1_micro: 0.213
f1-micro: 0.213, f1-macro: 0.177, f1-weighted: 0.179, , roc-auc: 0.622
##### RUN 3 #####
Epoch: 020, Train Loss: 2.063, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.029, Val f1_micro: 0.165
Epoch: 060, Train Loss: 1.967, Val f1_micro: 0.171
Epoch: 080, Train Loss: 1.933, Val f1_micro: 0.173
Epoch: 100, Train Loss: 1.861, Val f1_micro: 0.185
Epoch: 120, Train Loss: 1.816, Val f1_micro: 0.189
Epoch: 140, Train Loss: 1.825, Val f1_micro: 0.192
Epoch: 160, Train Loss: 1.789, Val f1_micro: 0.198
Epoch: 180, Train Loss: 1.766, Val f1_micro: 0.204
Epoch: 200, Train Loss: 1.763, Val f1_micro: 0.210
Epoch: 220, Train Loss: 1.782, Val f1_micro: 0.211
Epoch: 240, Train Loss: 1.764, Val f1_micro: 0.203
Epoch: 260, Train Loss: 1.765, Val f1_micro: 0.212
Epoch: 280, Train Loss: 1.757, Val f1_micro: 0.196
Epoch: 300, Train Loss: 1.751, Val f1_micro: 0.209
Epoch: 320, Train Loss: 1.724, Val f1_micro: 0.213
Epoch: 340, Train Loss: 1.735, Val f1_micro: 0.216
Epoch: 360, Train Loss: 1.771, Val f1_micro: 0.202
Epoch: 380, Train Loss: 1.735, Val f1_micro: 0.186
Epoch: 400, Train Loss: 1.743, Val f1_micro: 0.204
Epoch: 420, Train Loss: 1.718, Val f1_micro: 0.210
Epoch: 440, Train Loss: 1.726, Val f1_micro: 0.211
Epoch: 460, Train Loss: 1.736, Val f1_micro: 0.218
Epoch: 480, Train Loss: 1.720, Val f1_micro: 0.198
Epoch: 500, Train Loss: 1.716, Val f1_micro: 0.192
f1-micro: 0.192, f1-macro: 0.151, f1-weighted: 0.148, , roc-auc: 0.624
##### RUN 4 #####
Epoch: 020, Train Loss: 2.051, Val f1_micro: 0.145
Epoch: 040, Train Loss: 2.019, Val f1_micro: 0.118
Epoch: 060, Train Loss: 1.992, Val f1_micro: 0.167
Epoch: 080, Train Loss: 1.905, Val f1_micro: 0.173
Epoch: 100, Train Loss: 1.866, Val f1_micro: 0.190
Epoch: 120, Train Loss: 1.854, Val f1_micro: 0.192
Epoch: 140, Train Loss: 1.836, Val f1_micro: 0.195
Epoch: 160, Train Loss: 1.805, Val f1_micro: 0.208
Epoch: 180, Train Loss: 1.800, Val f1_micro: 0.205
Epoch: 200, Train Loss: 1.788, Val f1_micro: 0.201
Epoch: 220, Train Loss: 1.769, Val f1_micro: 0.207
Epoch: 240, Train Loss: 1.759, Val f1_micro: 0.188
Epoch: 260, Train Loss: 1.757, Val f1_micro: 0.208
Epoch: 280, Train Loss: 1.774, Val f1_micro: 0.195
Epoch: 300, Train Loss: 1.749, Val f1_micro: 0.208
Epoch: 320, Train Loss: 1.740, Val f1_micro: 0.209
Epoch: 340, Train Loss: 1.719, Val f1_micro: 0.202
Epoch: 360, Train Loss: 1.734, Val f1_micro: 0.217
Epoch: 380, Train Loss: 1.727, Val f1_micro: 0.218
Epoch: 400, Train Loss: 1.731, Val f1_micro: 0.184
Epoch: 420, Train Loss: 1.733, Val f1_micro: 0.219
Epoch: 440, Train Loss: 1.728, Val f1_micro: 0.203
Epoch: 460, Train Loss: 1.752, Val f1_micro: 0.215
Epoch: 480, Train Loss: 1.733, Val f1_micro: 0.195
Epoch: 500, Train Loss: 1.714, Val f1_micro: 0.209
f1-micro: 0.209, f1-macro: 0.160, f1-weighted: 0.158, , roc-auc: 0.620
##### RUN 5 #####
Epoch: 020, Train Loss: 2.059, Val f1_micro: 0.097
Epoch: 040, Train Loss: 2.033, Val f1_micro: 0.158
Epoch: 060, Train Loss: 1.983, Val f1_micro: 0.144
Epoch: 080, Train Loss: 1.915, Val f1_micro: 0.183
Epoch: 100, Train Loss: 1.865, Val f1_micro: 0.186
Epoch: 120, Train Loss: 1.823, Val f1_micro: 0.202
Epoch: 140, Train Loss: 1.805, Val f1_micro: 0.199
Epoch: 160, Train Loss: 1.800, Val f1_micro: 0.190
Epoch: 180, Train Loss: 1.783, Val f1_micro: 0.205
Epoch: 200, Train Loss: 1.786, Val f1_micro: 0.209
Epoch: 220, Train Loss: 1.773, Val f1_micro: 0.198
Epoch: 240, Train Loss: 1.749, Val f1_micro: 0.194
Epoch: 260, Train Loss: 1.777, Val f1_micro: 0.211
Epoch: 280, Train Loss: 1.758, Val f1_micro: 0.210
Epoch: 300, Train Loss: 1.742, Val f1_micro: 0.215
Epoch: 320, Train Loss: 1.767, Val f1_micro: 0.190
Epoch: 340, Train Loss: 1.734, Val f1_micro: 0.220
Epoch: 360, Train Loss: 1.726, Val f1_micro: 0.189
Epoch: 380, Train Loss: 1.741, Val f1_micro: 0.219
Epoch: 400, Train Loss: 1.731, Val f1_micro: 0.212
Epoch: 420, Train Loss: 1.762, Val f1_micro: 0.227
Epoch: 440, Train Loss: 1.722, Val f1_micro: 0.220
Epoch: 460, Train Loss: 1.750, Val f1_micro: 0.192
Epoch: 480, Train Loss: 1.730, Val f1_micro: 0.216
Epoch: 500, Train Loss: 1.728, Val f1_micro: 0.214
f1-micro: 0.214, f1-macro: 0.176, f1-weighted: 0.178, , roc-auc: 0.622
########## Hyperparameters combination ##########
(512, 0.5, 0.001, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.255, Val f1_micro: 0.190
Epoch: 040, Train Loss: 1.975, Val f1_micro: 0.214
Epoch: 060, Train Loss: 1.799, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.711, Val f1_micro: 0.226
Epoch: 100, Train Loss: 1.622, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.571, Val f1_micro: 0.238
Epoch: 140, Train Loss: 1.499, Val f1_micro: 0.243
Epoch: 160, Train Loss: 1.435, Val f1_micro: 0.247
Epoch: 180, Train Loss: 1.409, Val f1_micro: 0.252
Epoch: 200, Train Loss: 1.348, Val f1_micro: 0.255
Epoch: 220, Train Loss: 1.313, Val f1_micro: 0.254
Epoch: 240, Train Loss: 1.280, Val f1_micro: 0.258
Epoch: 260, Train Loss: 1.239, Val f1_micro: 0.264
Epoch: 280, Train Loss: 1.216, Val f1_micro: 0.263
Epoch: 300, Train Loss: 1.180, Val f1_micro: 0.264
Epoch: 320, Train Loss: 1.159, Val f1_micro: 0.272
Epoch: 340, Train Loss: 1.124, Val f1_micro: 0.269
Epoch: 360, Train Loss: 1.118, Val f1_micro: 0.272
Epoch: 380, Train Loss: 1.083, Val f1_micro: 0.271
Epoch: 400, Train Loss: 1.052, Val f1_micro: 0.273
Epoch: 420, Train Loss: 1.045, Val f1_micro: 0.275
Epoch: 440, Train Loss: 1.002, Val f1_micro: 0.276
Epoch: 460, Train Loss: 1.000, Val f1_micro: 0.275
Epoch: 480, Train Loss: 0.986, Val f1_micro: 0.278
Epoch: 500, Train Loss: 0.965, Val f1_micro: 0.279
f1-micro: 0.279, f1-macro: 0.271, f1-weighted: 0.274, , roc-auc: 0.675
##### RUN 2 #####
Epoch: 020, Train Loss: 2.260, Val f1_micro: 0.196
Epoch: 040, Train Loss: 1.972, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.823, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.703, Val f1_micro: 0.226
Epoch: 100, Train Loss: 1.633, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.559, Val f1_micro: 0.236
Epoch: 140, Train Loss: 1.499, Val f1_micro: 0.242
Epoch: 160, Train Loss: 1.449, Val f1_micro: 0.250
Epoch: 180, Train Loss: 1.397, Val f1_micro: 0.252
Epoch: 200, Train Loss: 1.349, Val f1_micro: 0.255
Epoch: 220, Train Loss: 1.305, Val f1_micro: 0.259
Epoch: 240, Train Loss: 1.274, Val f1_micro: 0.259
Epoch: 260, Train Loss: 1.238, Val f1_micro: 0.261
Epoch: 280, Train Loss: 1.199, Val f1_micro: 0.263
Epoch: 300, Train Loss: 1.183, Val f1_micro: 0.264
Epoch: 320, Train Loss: 1.164, Val f1_micro: 0.267
Epoch: 340, Train Loss: 1.129, Val f1_micro: 0.272
Epoch: 360, Train Loss: 1.109, Val f1_micro: 0.270
Epoch: 380, Train Loss: 1.095, Val f1_micro: 0.272
Epoch: 400, Train Loss: 1.057, Val f1_micro: 0.273
Epoch: 420, Train Loss: 1.071, Val f1_micro: 0.274
Epoch: 440, Train Loss: 1.001, Val f1_micro: 0.276
Epoch: 460, Train Loss: 1.010, Val f1_micro: 0.278
Epoch: 480, Train Loss: 0.967, Val f1_micro: 0.277
Epoch: 500, Train Loss: 0.959, Val f1_micro: 0.280
f1-micro: 0.280, f1-macro: 0.272, f1-weighted: 0.274, , roc-auc: 0.675
##### RUN 3 #####
Epoch: 020, Train Loss: 2.269, Val f1_micro: 0.194
Epoch: 040, Train Loss: 1.968, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.815, Val f1_micro: 0.222
Epoch: 080, Train Loss: 1.735, Val f1_micro: 0.227
Epoch: 100, Train Loss: 1.641, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.568, Val f1_micro: 0.239
Epoch: 140, Train Loss: 1.491, Val f1_micro: 0.247
Epoch: 160, Train Loss: 1.457, Val f1_micro: 0.247
Epoch: 180, Train Loss: 1.398, Val f1_micro: 0.253
Epoch: 200, Train Loss: 1.354, Val f1_micro: 0.255
Epoch: 220, Train Loss: 1.319, Val f1_micro: 0.258
Epoch: 240, Train Loss: 1.285, Val f1_micro: 0.259
Epoch: 260, Train Loss: 1.246, Val f1_micro: 0.262
Epoch: 280, Train Loss: 1.212, Val f1_micro: 0.266
Epoch: 300, Train Loss: 1.195, Val f1_micro: 0.270
Epoch: 320, Train Loss: 1.163, Val f1_micro: 0.267
Epoch: 340, Train Loss: 1.122, Val f1_micro: 0.270
Epoch: 360, Train Loss: 1.093, Val f1_micro: 0.273
Epoch: 380, Train Loss: 1.086, Val f1_micro: 0.271
Epoch: 400, Train Loss: 1.052, Val f1_micro: 0.277
Epoch: 420, Train Loss: 1.023, Val f1_micro: 0.276
Epoch: 440, Train Loss: 1.034, Val f1_micro: 0.277
Epoch: 460, Train Loss: 0.995, Val f1_micro: 0.276
Epoch: 480, Train Loss: 0.983, Val f1_micro: 0.279
Epoch: 500, Train Loss: 0.975, Val f1_micro: 0.282
f1-micro: 0.282, f1-macro: 0.272, f1-weighted: 0.275, , roc-auc: 0.675
##### RUN 4 #####
Epoch: 020, Train Loss: 2.253, Val f1_micro: 0.196
Epoch: 040, Train Loss: 1.964, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.835, Val f1_micro: 0.218
Epoch: 080, Train Loss: 1.711, Val f1_micro: 0.224
Epoch: 100, Train Loss: 1.627, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.559, Val f1_micro: 0.240
Epoch: 140, Train Loss: 1.476, Val f1_micro: 0.242
Epoch: 160, Train Loss: 1.437, Val f1_micro: 0.251
Epoch: 180, Train Loss: 1.398, Val f1_micro: 0.252
Epoch: 200, Train Loss: 1.346, Val f1_micro: 0.253
Epoch: 220, Train Loss: 1.315, Val f1_micro: 0.258
Epoch: 240, Train Loss: 1.287, Val f1_micro: 0.258
Epoch: 260, Train Loss: 1.226, Val f1_micro: 0.264
Epoch: 280, Train Loss: 1.215, Val f1_micro: 0.263
Epoch: 300, Train Loss: 1.183, Val f1_micro: 0.268
Epoch: 320, Train Loss: 1.152, Val f1_micro: 0.268
Epoch: 340, Train Loss: 1.127, Val f1_micro: 0.266
Epoch: 360, Train Loss: 1.114, Val f1_micro: 0.270
Epoch: 380, Train Loss: 1.088, Val f1_micro: 0.274
Epoch: 400, Train Loss: 1.061, Val f1_micro: 0.273
Epoch: 420, Train Loss: 1.017, Val f1_micro: 0.274
Epoch: 440, Train Loss: 1.020, Val f1_micro: 0.275
Epoch: 460, Train Loss: 1.006, Val f1_micro: 0.278
Epoch: 480, Train Loss: 0.986, Val f1_micro: 0.278
Epoch: 500, Train Loss: 0.960, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.272, f1-weighted: 0.275, , roc-auc: 0.675
##### RUN 5 #####
Epoch: 020, Train Loss: 2.229, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.964, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.821, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.702, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.618, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.567, Val f1_micro: 0.241
Epoch: 140, Train Loss: 1.499, Val f1_micro: 0.242
Epoch: 160, Train Loss: 1.437, Val f1_micro: 0.250
Epoch: 180, Train Loss: 1.380, Val f1_micro: 0.252
Epoch: 200, Train Loss: 1.347, Val f1_micro: 0.252
Epoch: 220, Train Loss: 1.317, Val f1_micro: 0.259
Epoch: 240, Train Loss: 1.286, Val f1_micro: 0.261
Epoch: 260, Train Loss: 1.232, Val f1_micro: 0.262
Epoch: 280, Train Loss: 1.210, Val f1_micro: 0.267
Epoch: 300, Train Loss: 1.192, Val f1_micro: 0.266
Epoch: 320, Train Loss: 1.146, Val f1_micro: 0.268
Epoch: 340, Train Loss: 1.143, Val f1_micro: 0.270
Epoch: 360, Train Loss: 1.117, Val f1_micro: 0.271
Epoch: 380, Train Loss: 1.078, Val f1_micro: 0.273
Epoch: 400, Train Loss: 1.066, Val f1_micro: 0.274
Epoch: 420, Train Loss: 1.031, Val f1_micro: 0.274
Epoch: 440, Train Loss: 1.032, Val f1_micro: 0.276
Epoch: 460, Train Loss: 1.011, Val f1_micro: 0.275
Epoch: 480, Train Loss: 0.982, Val f1_micro: 0.277
Epoch: 500, Train Loss: 0.960, Val f1_micro: 0.279
f1-micro: 0.279, f1-macro: 0.271, f1-weighted: 0.274, , roc-auc: 0.675
########## Hyperparameters combination ##########
(512, 0.5, 0.001, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.224, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.972, Val f1_micro: 0.208
Epoch: 060, Train Loss: 1.809, Val f1_micro: 0.217
Epoch: 080, Train Loss: 1.723, Val f1_micro: 0.228
Epoch: 100, Train Loss: 1.612, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.552, Val f1_micro: 0.239
Epoch: 140, Train Loss: 1.532, Val f1_micro: 0.243
Epoch: 160, Train Loss: 1.470, Val f1_micro: 0.250
Epoch: 180, Train Loss: 1.413, Val f1_micro: 0.254
Epoch: 200, Train Loss: 1.370, Val f1_micro: 0.251
Epoch: 220, Train Loss: 1.349, Val f1_micro: 0.254
Epoch: 240, Train Loss: 1.336, Val f1_micro: 0.256
Epoch: 260, Train Loss: 1.294, Val f1_micro: 0.258
Epoch: 280, Train Loss: 1.281, Val f1_micro: 0.260
Epoch: 300, Train Loss: 1.231, Val f1_micro: 0.264
Epoch: 320, Train Loss: 1.228, Val f1_micro: 0.263
Epoch: 340, Train Loss: 1.211, Val f1_micro: 0.265
Epoch: 360, Train Loss: 1.181, Val f1_micro: 0.268
Epoch: 380, Train Loss: 1.156, Val f1_micro: 0.270
Epoch: 400, Train Loss: 1.163, Val f1_micro: 0.270
Epoch: 420, Train Loss: 1.120, Val f1_micro: 0.271
Epoch: 440, Train Loss: 1.111, Val f1_micro: 0.272
Epoch: 460, Train Loss: 1.080, Val f1_micro: 0.269
Epoch: 480, Train Loss: 1.064, Val f1_micro: 0.272
Epoch: 500, Train Loss: 1.036, Val f1_micro: 0.274
f1-micro: 0.274, f1-macro: 0.262, f1-weighted: 0.266, , roc-auc: 0.673
##### RUN 2 #####
Epoch: 020, Train Loss: 2.239, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.947, Val f1_micro: 0.208
Epoch: 060, Train Loss: 1.807, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.701, Val f1_micro: 0.221
Epoch: 100, Train Loss: 1.623, Val f1_micro: 0.230
Epoch: 120, Train Loss: 1.580, Val f1_micro: 0.236
Epoch: 140, Train Loss: 1.497, Val f1_micro: 0.244
Epoch: 160, Train Loss: 1.457, Val f1_micro: 0.248
Epoch: 180, Train Loss: 1.420, Val f1_micro: 0.250
Epoch: 200, Train Loss: 1.378, Val f1_micro: 0.255
Epoch: 220, Train Loss: 1.358, Val f1_micro: 0.255
Epoch: 240, Train Loss: 1.312, Val f1_micro: 0.258
Epoch: 260, Train Loss: 1.306, Val f1_micro: 0.259
Epoch: 280, Train Loss: 1.258, Val f1_micro: 0.262
Epoch: 300, Train Loss: 1.227, Val f1_micro: 0.263
Epoch: 320, Train Loss: 1.214, Val f1_micro: 0.263
Epoch: 340, Train Loss: 1.185, Val f1_micro: 0.265
Epoch: 360, Train Loss: 1.177, Val f1_micro: 0.264
Epoch: 380, Train Loss: 1.130, Val f1_micro: 0.267
Epoch: 400, Train Loss: 1.137, Val f1_micro: 0.270
Epoch: 420, Train Loss: 1.128, Val f1_micro: 0.271
Epoch: 440, Train Loss: 1.109, Val f1_micro: 0.270
Epoch: 460, Train Loss: 1.066, Val f1_micro: 0.272
Epoch: 480, Train Loss: 1.092, Val f1_micro: 0.274
Epoch: 500, Train Loss: 1.045, Val f1_micro: 0.270
f1-micro: 0.270, f1-macro: 0.260, f1-weighted: 0.262, , roc-auc: 0.673
##### RUN 3 #####
Epoch: 020, Train Loss: 2.232, Val f1_micro: 0.198
Epoch: 040, Train Loss: 1.954, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.815, Val f1_micro: 0.222
Epoch: 080, Train Loss: 1.704, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.618, Val f1_micro: 0.229
Epoch: 120, Train Loss: 1.543, Val f1_micro: 0.239
Epoch: 140, Train Loss: 1.499, Val f1_micro: 0.243
Epoch: 160, Train Loss: 1.462, Val f1_micro: 0.250
Epoch: 180, Train Loss: 1.431, Val f1_micro: 0.251
Epoch: 200, Train Loss: 1.374, Val f1_micro: 0.252
Epoch: 220, Train Loss: 1.343, Val f1_micro: 0.255
Epoch: 240, Train Loss: 1.324, Val f1_micro: 0.256
Epoch: 260, Train Loss: 1.293, Val f1_micro: 0.256
Epoch: 280, Train Loss: 1.266, Val f1_micro: 0.262
Epoch: 300, Train Loss: 1.239, Val f1_micro: 0.261
Epoch: 320, Train Loss: 1.219, Val f1_micro: 0.264
Epoch: 340, Train Loss: 1.197, Val f1_micro: 0.266
Epoch: 360, Train Loss: 1.157, Val f1_micro: 0.270
Epoch: 380, Train Loss: 1.146, Val f1_micro: 0.267
Epoch: 400, Train Loss: 1.143, Val f1_micro: 0.268
Epoch: 420, Train Loss: 1.105, Val f1_micro: 0.270
Epoch: 440, Train Loss: 1.092, Val f1_micro: 0.271
Epoch: 460, Train Loss: 1.087, Val f1_micro: 0.271
Epoch: 480, Train Loss: 1.067, Val f1_micro: 0.273
Epoch: 500, Train Loss: 1.072, Val f1_micro: 0.275
f1-micro: 0.275, f1-macro: 0.264, f1-weighted: 0.266, , roc-auc: 0.673
##### RUN 4 #####
Epoch: 020, Train Loss: 2.230, Val f1_micro: 0.194
Epoch: 040, Train Loss: 1.978, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.811, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.705, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.631, Val f1_micro: 0.230
Epoch: 120, Train Loss: 1.560, Val f1_micro: 0.239
Epoch: 140, Train Loss: 1.486, Val f1_micro: 0.246
Epoch: 160, Train Loss: 1.445, Val f1_micro: 0.252
Epoch: 180, Train Loss: 1.417, Val f1_micro: 0.249
Epoch: 200, Train Loss: 1.393, Val f1_micro: 0.253
Epoch: 220, Train Loss: 1.334, Val f1_micro: 0.255
Epoch: 240, Train Loss: 1.305, Val f1_micro: 0.260
Epoch: 260, Train Loss: 1.295, Val f1_micro: 0.259
Epoch: 280, Train Loss: 1.268, Val f1_micro: 0.259
Epoch: 300, Train Loss: 1.241, Val f1_micro: 0.261
Epoch: 320, Train Loss: 1.210, Val f1_micro: 0.263
Epoch: 340, Train Loss: 1.210, Val f1_micro: 0.266
Epoch: 360, Train Loss: 1.187, Val f1_micro: 0.268
Epoch: 380, Train Loss: 1.151, Val f1_micro: 0.270
Epoch: 400, Train Loss: 1.135, Val f1_micro: 0.273
Epoch: 420, Train Loss: 1.117, Val f1_micro: 0.272
Epoch: 440, Train Loss: 1.120, Val f1_micro: 0.273
Epoch: 460, Train Loss: 1.079, Val f1_micro: 0.273
Epoch: 480, Train Loss: 1.088, Val f1_micro: 0.274
Epoch: 500, Train Loss: 1.055, Val f1_micro: 0.275
f1-micro: 0.275, f1-macro: 0.265, f1-weighted: 0.267, , roc-auc: 0.673
##### RUN 5 #####
Epoch: 020, Train Loss: 2.216, Val f1_micro: 0.196
Epoch: 040, Train Loss: 1.974, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.811, Val f1_micro: 0.217
Epoch: 080, Train Loss: 1.707, Val f1_micro: 0.224
Epoch: 100, Train Loss: 1.644, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.576, Val f1_micro: 0.239
Epoch: 140, Train Loss: 1.499, Val f1_micro: 0.243
Epoch: 160, Train Loss: 1.452, Val f1_micro: 0.248
Epoch: 180, Train Loss: 1.423, Val f1_micro: 0.248
Epoch: 200, Train Loss: 1.386, Val f1_micro: 0.252
Epoch: 220, Train Loss: 1.334, Val f1_micro: 0.255
Epoch: 240, Train Loss: 1.332, Val f1_micro: 0.258
Epoch: 260, Train Loss: 1.287, Val f1_micro: 0.260
Epoch: 280, Train Loss: 1.272, Val f1_micro: 0.260
Epoch: 300, Train Loss: 1.228, Val f1_micro: 0.263
Epoch: 320, Train Loss: 1.206, Val f1_micro: 0.263
Epoch: 340, Train Loss: 1.203, Val f1_micro: 0.263
Epoch: 360, Train Loss: 1.192, Val f1_micro: 0.267
Epoch: 380, Train Loss: 1.160, Val f1_micro: 0.266
Epoch: 400, Train Loss: 1.130, Val f1_micro: 0.269
Epoch: 420, Train Loss: 1.115, Val f1_micro: 0.272
Epoch: 440, Train Loss: 1.098, Val f1_micro: 0.271
Epoch: 460, Train Loss: 1.085, Val f1_micro: 0.275
Epoch: 480, Train Loss: 1.088, Val f1_micro: 0.277
Epoch: 500, Train Loss: 1.064, Val f1_micro: 0.277
f1-micro: 0.277, f1-macro: 0.265, f1-weighted: 0.269, , roc-auc: 0.673
########## Hyperparameters combination ##########
(512, 0.5, 0.001, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.241, Val f1_micro: 0.190
Epoch: 040, Train Loss: 1.962, Val f1_micro: 0.207
Epoch: 060, Train Loss: 1.831, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.730, Val f1_micro: 0.217
Epoch: 100, Train Loss: 1.639, Val f1_micro: 0.230
Epoch: 120, Train Loss: 1.574, Val f1_micro: 0.230
Epoch: 140, Train Loss: 1.536, Val f1_micro: 0.234
Epoch: 160, Train Loss: 1.481, Val f1_micro: 0.237
Epoch: 180, Train Loss: 1.449, Val f1_micro: 0.239
Epoch: 200, Train Loss: 1.416, Val f1_micro: 0.245
Epoch: 220, Train Loss: 1.395, Val f1_micro: 0.251
Epoch: 240, Train Loss: 1.375, Val f1_micro: 0.250
Epoch: 260, Train Loss: 1.348, Val f1_micro: 0.250
Epoch: 280, Train Loss: 1.315, Val f1_micro: 0.254
Epoch: 300, Train Loss: 1.294, Val f1_micro: 0.253
Epoch: 320, Train Loss: 1.267, Val f1_micro: 0.257
Epoch: 340, Train Loss: 1.265, Val f1_micro: 0.254
Epoch: 360, Train Loss: 1.237, Val f1_micro: 0.259
Epoch: 380, Train Loss: 1.212, Val f1_micro: 0.256
Epoch: 400, Train Loss: 1.204, Val f1_micro: 0.263
Epoch: 420, Train Loss: 1.180, Val f1_micro: 0.259
Epoch: 440, Train Loss: 1.184, Val f1_micro: 0.262
Epoch: 460, Train Loss: 1.175, Val f1_micro: 0.265
Epoch: 480, Train Loss: 1.153, Val f1_micro: 0.268
Epoch: 500, Train Loss: 1.159, Val f1_micro: 0.264
f1-micro: 0.264, f1-macro: 0.251, f1-weighted: 0.253, , roc-auc: 0.670
##### RUN 2 #####
Epoch: 020, Train Loss: 2.219, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.976, Val f1_micro: 0.210
Epoch: 060, Train Loss: 1.825, Val f1_micro: 0.216
Epoch: 080, Train Loss: 1.720, Val f1_micro: 0.221
Epoch: 100, Train Loss: 1.671, Val f1_micro: 0.223
Epoch: 120, Train Loss: 1.594, Val f1_micro: 0.232
Epoch: 140, Train Loss: 1.522, Val f1_micro: 0.232
Epoch: 160, Train Loss: 1.491, Val f1_micro: 0.241
Epoch: 180, Train Loss: 1.456, Val f1_micro: 0.239
Epoch: 200, Train Loss: 1.411, Val f1_micro: 0.245
Epoch: 220, Train Loss: 1.385, Val f1_micro: 0.247
Epoch: 240, Train Loss: 1.345, Val f1_micro: 0.247
Epoch: 260, Train Loss: 1.348, Val f1_micro: 0.252
Epoch: 280, Train Loss: 1.318, Val f1_micro: 0.253
Epoch: 300, Train Loss: 1.298, Val f1_micro: 0.251
Epoch: 320, Train Loss: 1.267, Val f1_micro: 0.256
Epoch: 340, Train Loss: 1.250, Val f1_micro: 0.256
Epoch: 360, Train Loss: 1.241, Val f1_micro: 0.256
Epoch: 380, Train Loss: 1.236, Val f1_micro: 0.257
Epoch: 400, Train Loss: 1.214, Val f1_micro: 0.260
Epoch: 420, Train Loss: 1.200, Val f1_micro: 0.259
Epoch: 440, Train Loss: 1.172, Val f1_micro: 0.263
Epoch: 460, Train Loss: 1.178, Val f1_micro: 0.262
Epoch: 480, Train Loss: 1.172, Val f1_micro: 0.262
Epoch: 500, Train Loss: 1.149, Val f1_micro: 0.264
f1-micro: 0.264, f1-macro: 0.251, f1-weighted: 0.254, , roc-auc: 0.668
##### RUN 3 #####
Epoch: 020, Train Loss: 2.257, Val f1_micro: 0.190
Epoch: 040, Train Loss: 1.977, Val f1_micro: 0.210
Epoch: 060, Train Loss: 1.816, Val f1_micro: 0.218
Epoch: 080, Train Loss: 1.703, Val f1_micro: 0.219
Epoch: 100, Train Loss: 1.633, Val f1_micro: 0.221
Epoch: 120, Train Loss: 1.584, Val f1_micro: 0.231
Epoch: 140, Train Loss: 1.524, Val f1_micro: 0.233
Epoch: 160, Train Loss: 1.496, Val f1_micro: 0.238
Epoch: 180, Train Loss: 1.453, Val f1_micro: 0.241
Epoch: 200, Train Loss: 1.401, Val f1_micro: 0.244
Epoch: 220, Train Loss: 1.380, Val f1_micro: 0.248
Epoch: 240, Train Loss: 1.372, Val f1_micro: 0.250
Epoch: 260, Train Loss: 1.332, Val f1_micro: 0.250
Epoch: 280, Train Loss: 1.338, Val f1_micro: 0.249
Epoch: 300, Train Loss: 1.294, Val f1_micro: 0.255
Epoch: 320, Train Loss: 1.268, Val f1_micro: 0.251
Epoch: 340, Train Loss: 1.261, Val f1_micro: 0.257
Epoch: 360, Train Loss: 1.236, Val f1_micro: 0.258
Epoch: 380, Train Loss: 1.218, Val f1_micro: 0.260
Epoch: 400, Train Loss: 1.217, Val f1_micro: 0.257
Epoch: 420, Train Loss: 1.199, Val f1_micro: 0.259
Epoch: 440, Train Loss: 1.195, Val f1_micro: 0.260
Epoch: 460, Train Loss: 1.175, Val f1_micro: 0.263
Epoch: 480, Train Loss: 1.174, Val f1_micro: 0.264
Epoch: 500, Train Loss: 1.164, Val f1_micro: 0.266
f1-micro: 0.266, f1-macro: 0.254, f1-weighted: 0.256, , roc-auc: 0.668
##### RUN 4 #####
Epoch: 020, Train Loss: 2.265, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.973, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.831, Val f1_micro: 0.216
Epoch: 080, Train Loss: 1.722, Val f1_micro: 0.219
Epoch: 100, Train Loss: 1.638, Val f1_micro: 0.226
Epoch: 120, Train Loss: 1.584, Val f1_micro: 0.229
Epoch: 140, Train Loss: 1.528, Val f1_micro: 0.236
Epoch: 160, Train Loss: 1.501, Val f1_micro: 0.238
Epoch: 180, Train Loss: 1.448, Val f1_micro: 0.238
Epoch: 200, Train Loss: 1.426, Val f1_micro: 0.245
Epoch: 220, Train Loss: 1.408, Val f1_micro: 0.246
Epoch: 240, Train Loss: 1.357, Val f1_micro: 0.243
Epoch: 260, Train Loss: 1.332, Val f1_micro: 0.249
Epoch: 280, Train Loss: 1.322, Val f1_micro: 0.251
Epoch: 300, Train Loss: 1.298, Val f1_micro: 0.253
Epoch: 320, Train Loss: 1.288, Val f1_micro: 0.256
Epoch: 340, Train Loss: 1.260, Val f1_micro: 0.253
Epoch: 360, Train Loss: 1.246, Val f1_micro: 0.258
Epoch: 380, Train Loss: 1.239, Val f1_micro: 0.256
Epoch: 400, Train Loss: 1.212, Val f1_micro: 0.257
Epoch: 420, Train Loss: 1.215, Val f1_micro: 0.257
Epoch: 440, Train Loss: 1.184, Val f1_micro: 0.263
Epoch: 460, Train Loss: 1.177, Val f1_micro: 0.262
Epoch: 480, Train Loss: 1.166, Val f1_micro: 0.266
Epoch: 500, Train Loss: 1.157, Val f1_micro: 0.266
f1-micro: 0.266, f1-macro: 0.253, f1-weighted: 0.255, , roc-auc: 0.668
##### RUN 5 #####
Epoch: 020, Train Loss: 2.257, Val f1_micro: 0.190
Epoch: 040, Train Loss: 1.992, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.816, Val f1_micro: 0.218
Epoch: 080, Train Loss: 1.725, Val f1_micro: 0.221
Epoch: 100, Train Loss: 1.666, Val f1_micro: 0.225
Epoch: 120, Train Loss: 1.579, Val f1_micro: 0.230
Epoch: 140, Train Loss: 1.539, Val f1_micro: 0.235
Epoch: 160, Train Loss: 1.494, Val f1_micro: 0.235
Epoch: 180, Train Loss: 1.430, Val f1_micro: 0.241
Epoch: 200, Train Loss: 1.417, Val f1_micro: 0.243
Epoch: 220, Train Loss: 1.370, Val f1_micro: 0.249
Epoch: 240, Train Loss: 1.364, Val f1_micro: 0.251
Epoch: 260, Train Loss: 1.337, Val f1_micro: 0.251
Epoch: 280, Train Loss: 1.326, Val f1_micro: 0.255
Epoch: 300, Train Loss: 1.301, Val f1_micro: 0.253
Epoch: 320, Train Loss: 1.273, Val f1_micro: 0.257
Epoch: 340, Train Loss: 1.281, Val f1_micro: 0.257
Epoch: 360, Train Loss: 1.240, Val f1_micro: 0.260
Epoch: 380, Train Loss: 1.230, Val f1_micro: 0.257
Epoch: 400, Train Loss: 1.226, Val f1_micro: 0.259
Epoch: 420, Train Loss: 1.195, Val f1_micro: 0.262
Epoch: 440, Train Loss: 1.188, Val f1_micro: 0.261
Epoch: 460, Train Loss: 1.178, Val f1_micro: 0.261
Epoch: 480, Train Loss: 1.164, Val f1_micro: 0.262
Epoch: 500, Train Loss: 1.131, Val f1_micro: 0.266
f1-micro: 0.266, f1-macro: 0.254, f1-weighted: 0.256, , roc-auc: 0.669
########## Hyperparameters combination ##########
(512, 0.5, 0.001, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.252, Val f1_micro: 0.185
Epoch: 040, Train Loss: 1.991, Val f1_micro: 0.200
Epoch: 060, Train Loss: 1.865, Val f1_micro: 0.209
Epoch: 080, Train Loss: 1.769, Val f1_micro: 0.209
Epoch: 100, Train Loss: 1.716, Val f1_micro: 0.216
Epoch: 120, Train Loss: 1.679, Val f1_micro: 0.214
Epoch: 140, Train Loss: 1.637, Val f1_micro: 0.220
Epoch: 160, Train Loss: 1.631, Val f1_micro: 0.221
Epoch: 180, Train Loss: 1.613, Val f1_micro: 0.220
Epoch: 200, Train Loss: 1.588, Val f1_micro: 0.220
Epoch: 220, Train Loss: 1.593, Val f1_micro: 0.225
Epoch: 240, Train Loss: 1.599, Val f1_micro: 0.227
Epoch: 260, Train Loss: 1.592, Val f1_micro: 0.227
Epoch: 280, Train Loss: 1.582, Val f1_micro: 0.224
Epoch: 300, Train Loss: 1.582, Val f1_micro: 0.227
Epoch: 320, Train Loss: 1.578, Val f1_micro: 0.224
Epoch: 340, Train Loss: 1.575, Val f1_micro: 0.223
Epoch: 360, Train Loss: 1.579, Val f1_micro: 0.223
Epoch: 380, Train Loss: 1.572, Val f1_micro: 0.225
Epoch: 400, Train Loss: 1.563, Val f1_micro: 0.226
Epoch: 420, Train Loss: 1.576, Val f1_micro: 0.225
Epoch: 440, Train Loss: 1.587, Val f1_micro: 0.228
Epoch: 460, Train Loss: 1.592, Val f1_micro: 0.222
Epoch: 480, Train Loss: 1.590, Val f1_micro: 0.224
Epoch: 500, Train Loss: 1.582, Val f1_micro: 0.221
f1-micro: 0.221, f1-macro: 0.192, f1-weighted: 0.192, , roc-auc: 0.653
##### RUN 2 #####
Epoch: 020, Train Loss: 2.241, Val f1_micro: 0.188
Epoch: 040, Train Loss: 1.966, Val f1_micro: 0.205
Epoch: 060, Train Loss: 1.865, Val f1_micro: 0.204
Epoch: 080, Train Loss: 1.765, Val f1_micro: 0.213
Epoch: 100, Train Loss: 1.720, Val f1_micro: 0.216
Epoch: 120, Train Loss: 1.653, Val f1_micro: 0.214
Epoch: 140, Train Loss: 1.644, Val f1_micro: 0.224
Epoch: 160, Train Loss: 1.627, Val f1_micro: 0.224
Epoch: 180, Train Loss: 1.601, Val f1_micro: 0.227
Epoch: 200, Train Loss: 1.601, Val f1_micro: 0.222
Epoch: 220, Train Loss: 1.598, Val f1_micro: 0.225
Epoch: 240, Train Loss: 1.586, Val f1_micro: 0.230
Epoch: 260, Train Loss: 1.577, Val f1_micro: 0.222
Epoch: 280, Train Loss: 1.577, Val f1_micro: 0.225
Epoch: 300, Train Loss: 1.577, Val f1_micro: 0.226
Epoch: 320, Train Loss: 1.580, Val f1_micro: 0.229
Epoch: 340, Train Loss: 1.580, Val f1_micro: 0.225
Epoch: 360, Train Loss: 1.577, Val f1_micro: 0.222
Epoch: 380, Train Loss: 1.583, Val f1_micro: 0.224
Epoch: 400, Train Loss: 1.591, Val f1_micro: 0.220
Epoch: 420, Train Loss: 1.575, Val f1_micro: 0.220
Epoch: 440, Train Loss: 1.575, Val f1_micro: 0.223
Epoch: 460, Train Loss: 1.569, Val f1_micro: 0.224
Epoch: 480, Train Loss: 1.587, Val f1_micro: 0.225
Epoch: 500, Train Loss: 1.582, Val f1_micro: 0.222
f1-micro: 0.222, f1-macro: 0.193, f1-weighted: 0.194, , roc-auc: 0.653
##### RUN 3 #####
Epoch: 020, Train Loss: 2.281, Val f1_micro: 0.195
Epoch: 040, Train Loss: 1.977, Val f1_micro: 0.202
Epoch: 060, Train Loss: 1.837, Val f1_micro: 0.209
Epoch: 080, Train Loss: 1.766, Val f1_micro: 0.206
Epoch: 100, Train Loss: 1.713, Val f1_micro: 0.213
Epoch: 120, Train Loss: 1.668, Val f1_micro: 0.217
Epoch: 140, Train Loss: 1.632, Val f1_micro: 0.220
Epoch: 160, Train Loss: 1.640, Val f1_micro: 0.220
Epoch: 180, Train Loss: 1.609, Val f1_micro: 0.224
Epoch: 200, Train Loss: 1.604, Val f1_micro: 0.225
Epoch: 220, Train Loss: 1.593, Val f1_micro: 0.228
Epoch: 240, Train Loss: 1.584, Val f1_micro: 0.223
Epoch: 260, Train Loss: 1.577, Val f1_micro: 0.227
Epoch: 280, Train Loss: 1.571, Val f1_micro: 0.226
Epoch: 300, Train Loss: 1.588, Val f1_micro: 0.228
Epoch: 320, Train Loss: 1.573, Val f1_micro: 0.226
Epoch: 340, Train Loss: 1.574, Val f1_micro: 0.228
Epoch: 360, Train Loss: 1.574, Val f1_micro: 0.224
Epoch: 380, Train Loss: 1.577, Val f1_micro: 0.227
Epoch: 400, Train Loss: 1.586, Val f1_micro: 0.227
Epoch: 420, Train Loss: 1.586, Val f1_micro: 0.226
Epoch: 440, Train Loss: 1.587, Val f1_micro: 0.228
Epoch: 460, Train Loss: 1.589, Val f1_micro: 0.225
Epoch: 480, Train Loss: 1.592, Val f1_micro: 0.224
Epoch: 500, Train Loss: 1.601, Val f1_micro: 0.223
f1-micro: 0.223, f1-macro: 0.193, f1-weighted: 0.193, , roc-auc: 0.653
##### RUN 4 #####
Epoch: 020, Train Loss: 2.234, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.973, Val f1_micro: 0.204
Epoch: 060, Train Loss: 1.836, Val f1_micro: 0.206
Epoch: 080, Train Loss: 1.761, Val f1_micro: 0.207
Epoch: 100, Train Loss: 1.715, Val f1_micro: 0.214
Epoch: 120, Train Loss: 1.672, Val f1_micro: 0.220
Epoch: 140, Train Loss: 1.647, Val f1_micro: 0.220
Epoch: 160, Train Loss: 1.624, Val f1_micro: 0.222
Epoch: 180, Train Loss: 1.610, Val f1_micro: 0.226
Epoch: 200, Train Loss: 1.601, Val f1_micro: 0.223
Epoch: 220, Train Loss: 1.589, Val f1_micro: 0.227
Epoch: 240, Train Loss: 1.586, Val f1_micro: 0.225
Epoch: 260, Train Loss: 1.604, Val f1_micro: 0.225
Epoch: 280, Train Loss: 1.571, Val f1_micro: 0.222
Epoch: 300, Train Loss: 1.582, Val f1_micro: 0.226
Epoch: 320, Train Loss: 1.572, Val f1_micro: 0.228
Epoch: 340, Train Loss: 1.577, Val f1_micro: 0.224
Epoch: 360, Train Loss: 1.565, Val f1_micro: 0.224
Epoch: 380, Train Loss: 1.573, Val f1_micro: 0.222
Epoch: 400, Train Loss: 1.577, Val f1_micro: 0.225
Epoch: 420, Train Loss: 1.573, Val f1_micro: 0.226
Epoch: 440, Train Loss: 1.571, Val f1_micro: 0.223
Epoch: 460, Train Loss: 1.579, Val f1_micro: 0.223
Epoch: 480, Train Loss: 1.580, Val f1_micro: 0.223
Epoch: 500, Train Loss: 1.582, Val f1_micro: 0.226
f1-micro: 0.226, f1-macro: 0.195, f1-weighted: 0.196, , roc-auc: 0.653
##### RUN 5 #####
Epoch: 020, Train Loss: 2.283, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.976, Val f1_micro: 0.203
Epoch: 060, Train Loss: 1.845, Val f1_micro: 0.208
Epoch: 080, Train Loss: 1.770, Val f1_micro: 0.208
Epoch: 100, Train Loss: 1.709, Val f1_micro: 0.214
Epoch: 120, Train Loss: 1.697, Val f1_micro: 0.220
Epoch: 140, Train Loss: 1.662, Val f1_micro: 0.219
Epoch: 160, Train Loss: 1.642, Val f1_micro: 0.218
Epoch: 180, Train Loss: 1.621, Val f1_micro: 0.223
Epoch: 200, Train Loss: 1.598, Val f1_micro: 0.224
Epoch: 220, Train Loss: 1.596, Val f1_micro: 0.226
Epoch: 240, Train Loss: 1.582, Val f1_micro: 0.227
Epoch: 260, Train Loss: 1.570, Val f1_micro: 0.228
Epoch: 280, Train Loss: 1.565, Val f1_micro: 0.227
Epoch: 300, Train Loss: 1.572, Val f1_micro: 0.225
Epoch: 320, Train Loss: 1.573, Val f1_micro: 0.224
Epoch: 340, Train Loss: 1.580, Val f1_micro: 0.222
Epoch: 360, Train Loss: 1.590, Val f1_micro: 0.227
Epoch: 380, Train Loss: 1.575, Val f1_micro: 0.224
Epoch: 400, Train Loss: 1.593, Val f1_micro: 0.226
Epoch: 420, Train Loss: 1.585, Val f1_micro: 0.225
Epoch: 440, Train Loss: 1.565, Val f1_micro: 0.227
Epoch: 460, Train Loss: 1.581, Val f1_micro: 0.222
Epoch: 480, Train Loss: 1.580, Val f1_micro: 0.222
Epoch: 500, Train Loss: 1.579, Val f1_micro: 0.227
f1-micro: 0.227, f1-macro: 0.196, f1-weighted: 0.197, , roc-auc: 0.654
########## Hyperparameters combination ##########
(512, 0.5, 0.005, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.777, Val f1_micro: 0.214
Epoch: 040, Train Loss: 1.466, Val f1_micro: 0.242
Epoch: 060, Train Loss: 1.335, Val f1_micro: 0.256
Epoch: 080, Train Loss: 1.197, Val f1_micro: 0.266
Epoch: 100, Train Loss: 1.093, Val f1_micro: 0.268
Epoch: 120, Train Loss: 1.025, Val f1_micro: 0.277
Epoch: 140, Train Loss: 0.956, Val f1_micro: 0.287
Epoch: 160, Train Loss: 0.892, Val f1_micro: 0.286
Epoch: 180, Train Loss: 0.825, Val f1_micro: 0.292
Epoch: 200, Train Loss: 0.773, Val f1_micro: 0.293
Epoch: 220, Train Loss: 0.742, Val f1_micro: 0.297
Epoch: 240, Train Loss: 0.681, Val f1_micro: 0.294
Epoch: 260, Train Loss: 0.632, Val f1_micro: 0.303
Epoch: 280, Train Loss: 0.611, Val f1_micro: 0.302
Epoch: 300, Train Loss: 0.555, Val f1_micro: 0.305
Epoch: 320, Train Loss: 0.538, Val f1_micro: 0.307
Epoch: 340, Train Loss: 0.528, Val f1_micro: 0.306
Epoch: 360, Train Loss: 0.504, Val f1_micro: 0.307
Epoch: 380, Train Loss: 0.464, Val f1_micro: 0.308
Epoch: 400, Train Loss: 0.448, Val f1_micro: 0.311
Epoch: 420, Train Loss: 0.423, Val f1_micro: 0.311
Epoch: 440, Train Loss: 0.385, Val f1_micro: 0.314
Epoch: 460, Train Loss: 0.384, Val f1_micro: 0.312
Epoch: 480, Train Loss: 0.370, Val f1_micro: 0.310
Epoch: 500, Train Loss: 0.352, Val f1_micro: 0.314
f1-micro: 0.314, f1-macro: 0.307, f1-weighted: 0.314, , roc-auc: 0.684
##### RUN 2 #####
Epoch: 020, Train Loss: 1.748, Val f1_micro: 0.208
Epoch: 040, Train Loss: 1.477, Val f1_micro: 0.238
Epoch: 060, Train Loss: 1.323, Val f1_micro: 0.255
Epoch: 080, Train Loss: 1.216, Val f1_micro: 0.264
Epoch: 100, Train Loss: 1.112, Val f1_micro: 0.271
Epoch: 120, Train Loss: 1.046, Val f1_micro: 0.276
Epoch: 140, Train Loss: 0.953, Val f1_micro: 0.281
Epoch: 160, Train Loss: 0.880, Val f1_micro: 0.285
Epoch: 180, Train Loss: 0.843, Val f1_micro: 0.289
Epoch: 200, Train Loss: 0.797, Val f1_micro: 0.291
Epoch: 220, Train Loss: 0.739, Val f1_micro: 0.296
Epoch: 240, Train Loss: 0.707, Val f1_micro: 0.300
Epoch: 260, Train Loss: 0.628, Val f1_micro: 0.301
Epoch: 280, Train Loss: 0.599, Val f1_micro: 0.302
Epoch: 300, Train Loss: 0.573, Val f1_micro: 0.306
Epoch: 320, Train Loss: 0.549, Val f1_micro: 0.308
Epoch: 340, Train Loss: 0.512, Val f1_micro: 0.306
Epoch: 360, Train Loss: 0.500, Val f1_micro: 0.306
Epoch: 380, Train Loss: 0.467, Val f1_micro: 0.309
Epoch: 400, Train Loss: 0.433, Val f1_micro: 0.309
Epoch: 420, Train Loss: 0.424, Val f1_micro: 0.311
Epoch: 440, Train Loss: 0.411, Val f1_micro: 0.311
Epoch: 460, Train Loss: 0.388, Val f1_micro: 0.311
Epoch: 480, Train Loss: 0.375, Val f1_micro: 0.312
Epoch: 500, Train Loss: 0.350, Val f1_micro: 0.311
f1-micro: 0.311, f1-macro: 0.306, f1-weighted: 0.312, , roc-auc: 0.681
##### RUN 3 #####
Epoch: 020, Train Loss: 1.771, Val f1_micro: 0.221
Epoch: 040, Train Loss: 1.507, Val f1_micro: 0.234
Epoch: 060, Train Loss: 1.326, Val f1_micro: 0.258
Epoch: 080, Train Loss: 1.245, Val f1_micro: 0.267
Epoch: 100, Train Loss: 1.103, Val f1_micro: 0.268
Epoch: 120, Train Loss: 1.020, Val f1_micro: 0.278
Epoch: 140, Train Loss: 0.957, Val f1_micro: 0.285
Epoch: 160, Train Loss: 0.907, Val f1_micro: 0.288
Epoch: 180, Train Loss: 0.835, Val f1_micro: 0.289
Epoch: 200, Train Loss: 0.789, Val f1_micro: 0.292
Epoch: 220, Train Loss: 0.732, Val f1_micro: 0.293
Epoch: 240, Train Loss: 0.689, Val f1_micro: 0.298
Epoch: 260, Train Loss: 0.640, Val f1_micro: 0.298
Epoch: 280, Train Loss: 0.590, Val f1_micro: 0.303
Epoch: 300, Train Loss: 0.574, Val f1_micro: 0.304
Epoch: 320, Train Loss: 0.538, Val f1_micro: 0.309
Epoch: 340, Train Loss: 0.519, Val f1_micro: 0.305
Epoch: 360, Train Loss: 0.492, Val f1_micro: 0.307
Epoch: 380, Train Loss: 0.466, Val f1_micro: 0.309
Epoch: 400, Train Loss: 0.438, Val f1_micro: 0.306
Epoch: 420, Train Loss: 0.421, Val f1_micro: 0.313
Epoch: 440, Train Loss: 0.410, Val f1_micro: 0.310
Epoch: 460, Train Loss: 0.375, Val f1_micro: 0.313
Epoch: 480, Train Loss: 0.367, Val f1_micro: 0.310
Epoch: 500, Train Loss: 0.350, Val f1_micro: 0.315
f1-micro: 0.315, f1-macro: 0.308, f1-weighted: 0.314, , roc-auc: 0.682
##### RUN 4 #####
Epoch: 020, Train Loss: 1.748, Val f1_micro: 0.222
Epoch: 040, Train Loss: 1.471, Val f1_micro: 0.242
Epoch: 060, Train Loss: 1.311, Val f1_micro: 0.260
Epoch: 080, Train Loss: 1.197, Val f1_micro: 0.264
Epoch: 100, Train Loss: 1.112, Val f1_micro: 0.270
Epoch: 120, Train Loss: 1.015, Val f1_micro: 0.278
Epoch: 140, Train Loss: 0.939, Val f1_micro: 0.284
Epoch: 160, Train Loss: 0.879, Val f1_micro: 0.287
Epoch: 180, Train Loss: 0.841, Val f1_micro: 0.290
Epoch: 200, Train Loss: 0.772, Val f1_micro: 0.293
Epoch: 220, Train Loss: 0.729, Val f1_micro: 0.291
Epoch: 240, Train Loss: 0.686, Val f1_micro: 0.297
Epoch: 260, Train Loss: 0.659, Val f1_micro: 0.298
Epoch: 280, Train Loss: 0.606, Val f1_micro: 0.301
Epoch: 300, Train Loss: 0.573, Val f1_micro: 0.302
Epoch: 320, Train Loss: 0.551, Val f1_micro: 0.305
Epoch: 340, Train Loss: 0.486, Val f1_micro: 0.308
Epoch: 360, Train Loss: 0.478, Val f1_micro: 0.309
Epoch: 380, Train Loss: 0.452, Val f1_micro: 0.309
Epoch: 400, Train Loss: 0.433, Val f1_micro: 0.309
Epoch: 420, Train Loss: 0.425, Val f1_micro: 0.310
Epoch: 440, Train Loss: 0.398, Val f1_micro: 0.310
Epoch: 460, Train Loss: 0.379, Val f1_micro: 0.311
Epoch: 480, Train Loss: 0.375, Val f1_micro: 0.311
Epoch: 500, Train Loss: 0.361, Val f1_micro: 0.311
f1-micro: 0.311, f1-macro: 0.306, f1-weighted: 0.313, , roc-auc: 0.681
##### RUN 5 #####
Epoch: 020, Train Loss: 1.749, Val f1_micro: 0.214
Epoch: 040, Train Loss: 1.500, Val f1_micro: 0.242
Epoch: 060, Train Loss: 1.327, Val f1_micro: 0.260
Epoch: 080, Train Loss: 1.201, Val f1_micro: 0.266
Epoch: 100, Train Loss: 1.112, Val f1_micro: 0.274
Epoch: 120, Train Loss: 1.044, Val f1_micro: 0.280
Epoch: 140, Train Loss: 0.958, Val f1_micro: 0.281
Epoch: 160, Train Loss: 0.873, Val f1_micro: 0.288
Epoch: 180, Train Loss: 0.826, Val f1_micro: 0.291
Epoch: 200, Train Loss: 0.760, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.739, Val f1_micro: 0.294
Epoch: 240, Train Loss: 0.706, Val f1_micro: 0.295
Epoch: 260, Train Loss: 0.662, Val f1_micro: 0.298
Epoch: 280, Train Loss: 0.604, Val f1_micro: 0.303
Epoch: 300, Train Loss: 0.599, Val f1_micro: 0.302
Epoch: 320, Train Loss: 0.553, Val f1_micro: 0.306
Epoch: 340, Train Loss: 0.523, Val f1_micro: 0.304
Epoch: 360, Train Loss: 0.489, Val f1_micro: 0.307
Epoch: 380, Train Loss: 0.464, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.435, Val f1_micro: 0.309
Epoch: 420, Train Loss: 0.430, Val f1_micro: 0.309
Epoch: 440, Train Loss: 0.407, Val f1_micro: 0.309
Epoch: 460, Train Loss: 0.383, Val f1_micro: 0.309
Epoch: 480, Train Loss: 0.393, Val f1_micro: 0.310
Epoch: 500, Train Loss: 0.347, Val f1_micro: 0.312
f1-micro: 0.312, f1-macro: 0.307, f1-weighted: 0.313, , roc-auc: 0.683
########## Hyperparameters combination ##########
(512, 0.5, 0.005, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.760, Val f1_micro: 0.208
Epoch: 040, Train Loss: 1.506, Val f1_micro: 0.238
Epoch: 060, Train Loss: 1.357, Val f1_micro: 0.258
Epoch: 080, Train Loss: 1.252, Val f1_micro: 0.257
Epoch: 100, Train Loss: 1.184, Val f1_micro: 0.261
Epoch: 120, Train Loss: 1.106, Val f1_micro: 0.265
Epoch: 140, Train Loss: 1.066, Val f1_micro: 0.274
Epoch: 160, Train Loss: 0.999, Val f1_micro: 0.273
Epoch: 180, Train Loss: 0.961, Val f1_micro: 0.274
Epoch: 200, Train Loss: 0.927, Val f1_micro: 0.281
Epoch: 220, Train Loss: 0.906, Val f1_micro: 0.283
Epoch: 240, Train Loss: 0.874, Val f1_micro: 0.284
Epoch: 260, Train Loss: 0.826, Val f1_micro: 0.289
Epoch: 280, Train Loss: 0.816, Val f1_micro: 0.291
Epoch: 300, Train Loss: 0.775, Val f1_micro: 0.290
Epoch: 320, Train Loss: 0.772, Val f1_micro: 0.288
Epoch: 340, Train Loss: 0.765, Val f1_micro: 0.292
Epoch: 360, Train Loss: 0.742, Val f1_micro: 0.298
Epoch: 380, Train Loss: 0.699, Val f1_micro: 0.297
Epoch: 400, Train Loss: 0.697, Val f1_micro: 0.301
Epoch: 420, Train Loss: 0.667, Val f1_micro: 0.296
Epoch: 440, Train Loss: 0.661, Val f1_micro: 0.300
Epoch: 460, Train Loss: 0.656, Val f1_micro: 0.302
Epoch: 480, Train Loss: 0.650, Val f1_micro: 0.302
Epoch: 500, Train Loss: 0.625, Val f1_micro: 0.300
f1-micro: 0.300, f1-macro: 0.294, f1-weighted: 0.300, , roc-auc: 0.674
##### RUN 2 #####
Epoch: 020, Train Loss: 1.744, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.497, Val f1_micro: 0.231
Epoch: 060, Train Loss: 1.358, Val f1_micro: 0.246
Epoch: 080, Train Loss: 1.255, Val f1_micro: 0.257
Epoch: 100, Train Loss: 1.169, Val f1_micro: 0.266
Epoch: 120, Train Loss: 1.136, Val f1_micro: 0.269
Epoch: 140, Train Loss: 1.061, Val f1_micro: 0.277
Epoch: 160, Train Loss: 1.028, Val f1_micro: 0.269
Epoch: 180, Train Loss: 0.967, Val f1_micro: 0.277
Epoch: 200, Train Loss: 0.948, Val f1_micro: 0.283
Epoch: 220, Train Loss: 0.898, Val f1_micro: 0.282
Epoch: 240, Train Loss: 0.863, Val f1_micro: 0.290
Epoch: 260, Train Loss: 0.844, Val f1_micro: 0.287
Epoch: 280, Train Loss: 0.816, Val f1_micro: 0.291
Epoch: 300, Train Loss: 0.813, Val f1_micro: 0.293
Epoch: 320, Train Loss: 0.768, Val f1_micro: 0.296
Epoch: 340, Train Loss: 0.748, Val f1_micro: 0.298
Epoch: 360, Train Loss: 0.737, Val f1_micro: 0.298
Epoch: 380, Train Loss: 0.709, Val f1_micro: 0.299
Epoch: 400, Train Loss: 0.704, Val f1_micro: 0.298
Epoch: 420, Train Loss: 0.678, Val f1_micro: 0.299
Epoch: 440, Train Loss: 0.670, Val f1_micro: 0.301
Epoch: 460, Train Loss: 0.661, Val f1_micro: 0.301
Epoch: 480, Train Loss: 0.652, Val f1_micro: 0.300
Epoch: 500, Train Loss: 0.650, Val f1_micro: 0.301
f1-micro: 0.301, f1-macro: 0.293, f1-weighted: 0.299, , roc-auc: 0.673
##### RUN 3 #####
Epoch: 020, Train Loss: 1.755, Val f1_micro: 0.213
Epoch: 040, Train Loss: 1.513, Val f1_micro: 0.235
Epoch: 060, Train Loss: 1.347, Val f1_micro: 0.254
Epoch: 080, Train Loss: 1.241, Val f1_micro: 0.261
Epoch: 100, Train Loss: 1.189, Val f1_micro: 0.267
Epoch: 120, Train Loss: 1.113, Val f1_micro: 0.269
Epoch: 140, Train Loss: 1.055, Val f1_micro: 0.272
Epoch: 160, Train Loss: 1.040, Val f1_micro: 0.278
Epoch: 180, Train Loss: 0.971, Val f1_micro: 0.276
Epoch: 200, Train Loss: 0.933, Val f1_micro: 0.281
Epoch: 220, Train Loss: 0.892, Val f1_micro: 0.281
Epoch: 240, Train Loss: 0.865, Val f1_micro: 0.280
Epoch: 260, Train Loss: 0.849, Val f1_micro: 0.287
Epoch: 280, Train Loss: 0.810, Val f1_micro: 0.292
Epoch: 300, Train Loss: 0.795, Val f1_micro: 0.294
Epoch: 320, Train Loss: 0.768, Val f1_micro: 0.294
Epoch: 340, Train Loss: 0.756, Val f1_micro: 0.292
Epoch: 360, Train Loss: 0.741, Val f1_micro: 0.295
Epoch: 380, Train Loss: 0.719, Val f1_micro: 0.294
Epoch: 400, Train Loss: 0.698, Val f1_micro: 0.300
Epoch: 420, Train Loss: 0.680, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.671, Val f1_micro: 0.303
Epoch: 460, Train Loss: 0.658, Val f1_micro: 0.299
Epoch: 480, Train Loss: 0.663, Val f1_micro: 0.302
Epoch: 500, Train Loss: 0.627, Val f1_micro: 0.303
f1-micro: 0.303, f1-macro: 0.298, f1-weighted: 0.303, , roc-auc: 0.673
##### RUN 4 #####
Epoch: 020, Train Loss: 1.762, Val f1_micro: 0.210
Epoch: 040, Train Loss: 1.486, Val f1_micro: 0.236
Epoch: 060, Train Loss: 1.362, Val f1_micro: 0.251
Epoch: 080, Train Loss: 1.243, Val f1_micro: 0.259
Epoch: 100, Train Loss: 1.190, Val f1_micro: 0.262
Epoch: 120, Train Loss: 1.125, Val f1_micro: 0.264
Epoch: 140, Train Loss: 1.077, Val f1_micro: 0.272
Epoch: 160, Train Loss: 1.015, Val f1_micro: 0.275
Epoch: 180, Train Loss: 0.980, Val f1_micro: 0.277
Epoch: 200, Train Loss: 0.934, Val f1_micro: 0.279
Epoch: 220, Train Loss: 0.898, Val f1_micro: 0.277
Epoch: 240, Train Loss: 0.868, Val f1_micro: 0.283
Epoch: 260, Train Loss: 0.849, Val f1_micro: 0.290
Epoch: 280, Train Loss: 0.821, Val f1_micro: 0.288
Epoch: 300, Train Loss: 0.796, Val f1_micro: 0.290
Epoch: 320, Train Loss: 0.759, Val f1_micro: 0.290
Epoch: 340, Train Loss: 0.761, Val f1_micro: 0.295
Epoch: 360, Train Loss: 0.732, Val f1_micro: 0.297
Epoch: 380, Train Loss: 0.715, Val f1_micro: 0.298
Epoch: 400, Train Loss: 0.685, Val f1_micro: 0.296
Epoch: 420, Train Loss: 0.655, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.677, Val f1_micro: 0.300
Epoch: 460, Train Loss: 0.659, Val f1_micro: 0.302
Epoch: 480, Train Loss: 0.651, Val f1_micro: 0.296
Epoch: 500, Train Loss: 0.643, Val f1_micro: 0.304
f1-micro: 0.304, f1-macro: 0.298, f1-weighted: 0.303, , roc-auc: 0.673
##### RUN 5 #####
Epoch: 020, Train Loss: 1.756, Val f1_micro: 0.214
Epoch: 040, Train Loss: 1.498, Val f1_micro: 0.235
Epoch: 060, Train Loss: 1.342, Val f1_micro: 0.253
Epoch: 080, Train Loss: 1.244, Val f1_micro: 0.252
Epoch: 100, Train Loss: 1.177, Val f1_micro: 0.258
Epoch: 120, Train Loss: 1.117, Val f1_micro: 0.271
Epoch: 140, Train Loss: 1.049, Val f1_micro: 0.276
Epoch: 160, Train Loss: 0.989, Val f1_micro: 0.274
Epoch: 180, Train Loss: 0.964, Val f1_micro: 0.281
Epoch: 200, Train Loss: 0.915, Val f1_micro: 0.278
Epoch: 220, Train Loss: 0.905, Val f1_micro: 0.280
Epoch: 240, Train Loss: 0.860, Val f1_micro: 0.284
Epoch: 260, Train Loss: 0.843, Val f1_micro: 0.288
Epoch: 280, Train Loss: 0.814, Val f1_micro: 0.291
Epoch: 300, Train Loss: 0.794, Val f1_micro: 0.295
Epoch: 320, Train Loss: 0.769, Val f1_micro: 0.293
Epoch: 340, Train Loss: 0.738, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.720, Val f1_micro: 0.294
Epoch: 380, Train Loss: 0.708, Val f1_micro: 0.301
Epoch: 400, Train Loss: 0.690, Val f1_micro: 0.297
Epoch: 420, Train Loss: 0.681, Val f1_micro: 0.295
Epoch: 440, Train Loss: 0.688, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.658, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.638, Val f1_micro: 0.296
Epoch: 500, Train Loss: 0.643, Val f1_micro: 0.302
f1-micro: 0.302, f1-macro: 0.296, f1-weighted: 0.301, , roc-auc: 0.672
########## Hyperparameters combination ##########
(512, 0.5, 0.005, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.768, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.518, Val f1_micro: 0.244
Epoch: 060, Train Loss: 1.382, Val f1_micro: 0.253
Epoch: 080, Train Loss: 1.303, Val f1_micro: 0.259
Epoch: 100, Train Loss: 1.252, Val f1_micro: 0.266
Epoch: 120, Train Loss: 1.218, Val f1_micro: 0.265
Epoch: 140, Train Loss: 1.157, Val f1_micro: 0.274
Epoch: 160, Train Loss: 1.122, Val f1_micro: 0.273
Epoch: 180, Train Loss: 1.106, Val f1_micro: 0.275
Epoch: 200, Train Loss: 1.079, Val f1_micro: 0.274
Epoch: 220, Train Loss: 1.038, Val f1_micro: 0.279
Epoch: 240, Train Loss: 1.016, Val f1_micro: 0.281
Epoch: 260, Train Loss: 1.010, Val f1_micro: 0.282
Epoch: 280, Train Loss: 0.993, Val f1_micro: 0.282
Epoch: 300, Train Loss: 0.986, Val f1_micro: 0.287
Epoch: 320, Train Loss: 0.965, Val f1_micro: 0.287
Epoch: 340, Train Loss: 0.954, Val f1_micro: 0.285
Epoch: 360, Train Loss: 0.947, Val f1_micro: 0.289
Epoch: 380, Train Loss: 0.933, Val f1_micro: 0.287
Epoch: 400, Train Loss: 0.917, Val f1_micro: 0.289
Epoch: 420, Train Loss: 0.911, Val f1_micro: 0.288
Epoch: 440, Train Loss: 0.887, Val f1_micro: 0.288
Epoch: 460, Train Loss: 0.890, Val f1_micro: 0.293
Epoch: 480, Train Loss: 0.884, Val f1_micro: 0.296
Epoch: 500, Train Loss: 0.898, Val f1_micro: 0.291
f1-micro: 0.291, f1-macro: 0.279, f1-weighted: 0.285, , roc-auc: 0.663
##### RUN 2 #####
Epoch: 020, Train Loss: 1.771, Val f1_micro: 0.212
Epoch: 040, Train Loss: 1.521, Val f1_micro: 0.240
Epoch: 060, Train Loss: 1.386, Val f1_micro: 0.252
Epoch: 080, Train Loss: 1.302, Val f1_micro: 0.260
Epoch: 100, Train Loss: 1.257, Val f1_micro: 0.264
Epoch: 120, Train Loss: 1.198, Val f1_micro: 0.266
Epoch: 140, Train Loss: 1.193, Val f1_micro: 0.268
Epoch: 160, Train Loss: 1.139, Val f1_micro: 0.271
Epoch: 180, Train Loss: 1.085, Val f1_micro: 0.270
Epoch: 200, Train Loss: 1.071, Val f1_micro: 0.277
Epoch: 220, Train Loss: 1.057, Val f1_micro: 0.278
Epoch: 240, Train Loss: 1.032, Val f1_micro: 0.281
Epoch: 260, Train Loss: 1.023, Val f1_micro: 0.280
Epoch: 280, Train Loss: 0.991, Val f1_micro: 0.288
Epoch: 300, Train Loss: 0.991, Val f1_micro: 0.287
Epoch: 320, Train Loss: 0.964, Val f1_micro: 0.290
Epoch: 340, Train Loss: 0.961, Val f1_micro: 0.286
Epoch: 360, Train Loss: 0.942, Val f1_micro: 0.288
Epoch: 380, Train Loss: 0.919, Val f1_micro: 0.287
Epoch: 400, Train Loss: 0.931, Val f1_micro: 0.286
Epoch: 420, Train Loss: 0.914, Val f1_micro: 0.287
Epoch: 440, Train Loss: 0.897, Val f1_micro: 0.287
Epoch: 460, Train Loss: 0.886, Val f1_micro: 0.292
Epoch: 480, Train Loss: 0.892, Val f1_micro: 0.292
Epoch: 500, Train Loss: 0.868, Val f1_micro: 0.288
f1-micro: 0.288, f1-macro: 0.277, f1-weighted: 0.283, , roc-auc: 0.663
##### RUN 3 #####
Epoch: 020, Train Loss: 1.780, Val f1_micro: 0.223
Epoch: 040, Train Loss: 1.510, Val f1_micro: 0.239
Epoch: 060, Train Loss: 1.408, Val f1_micro: 0.258
Epoch: 080, Train Loss: 1.305, Val f1_micro: 0.257
Epoch: 100, Train Loss: 1.264, Val f1_micro: 0.258
Epoch: 120, Train Loss: 1.224, Val f1_micro: 0.268
Epoch: 140, Train Loss: 1.167, Val f1_micro: 0.274
Epoch: 160, Train Loss: 1.129, Val f1_micro: 0.274
Epoch: 180, Train Loss: 1.103, Val f1_micro: 0.274
Epoch: 200, Train Loss: 1.061, Val f1_micro: 0.279
Epoch: 220, Train Loss: 1.048, Val f1_micro: 0.276
Epoch: 240, Train Loss: 1.035, Val f1_micro: 0.278
Epoch: 260, Train Loss: 1.019, Val f1_micro: 0.279
Epoch: 280, Train Loss: 0.988, Val f1_micro: 0.284
Epoch: 300, Train Loss: 0.977, Val f1_micro: 0.278
Epoch: 320, Train Loss: 0.971, Val f1_micro: 0.276
Epoch: 340, Train Loss: 0.947, Val f1_micro: 0.292
Epoch: 360, Train Loss: 0.946, Val f1_micro: 0.287
Epoch: 380, Train Loss: 0.930, Val f1_micro: 0.291
Epoch: 400, Train Loss: 0.935, Val f1_micro: 0.286
Epoch: 420, Train Loss: 0.906, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.909, Val f1_micro: 0.290
Epoch: 460, Train Loss: 0.903, Val f1_micro: 0.294
Epoch: 480, Train Loss: 0.877, Val f1_micro: 0.291
Epoch: 500, Train Loss: 0.879, Val f1_micro: 0.290
f1-micro: 0.290, f1-macro: 0.278, f1-weighted: 0.283, , roc-auc: 0.665
##### RUN 4 #####
Epoch: 020, Train Loss: 1.759, Val f1_micro: 0.220
Epoch: 040, Train Loss: 1.520, Val f1_micro: 0.244
Epoch: 060, Train Loss: 1.396, Val f1_micro: 0.253
Epoch: 080, Train Loss: 1.317, Val f1_micro: 0.258
Epoch: 100, Train Loss: 1.254, Val f1_micro: 0.263
Epoch: 120, Train Loss: 1.195, Val f1_micro: 0.270
Epoch: 140, Train Loss: 1.163, Val f1_micro: 0.273
Epoch: 160, Train Loss: 1.134, Val f1_micro: 0.266
Epoch: 180, Train Loss: 1.081, Val f1_micro: 0.271
Epoch: 200, Train Loss: 1.087, Val f1_micro: 0.273
Epoch: 220, Train Loss: 1.047, Val f1_micro: 0.283
Epoch: 240, Train Loss: 1.025, Val f1_micro: 0.274
Epoch: 260, Train Loss: 1.020, Val f1_micro: 0.283
Epoch: 280, Train Loss: 1.000, Val f1_micro: 0.276
Epoch: 300, Train Loss: 0.970, Val f1_micro: 0.278
Epoch: 320, Train Loss: 0.964, Val f1_micro: 0.279
Epoch: 340, Train Loss: 0.949, Val f1_micro: 0.283
Epoch: 360, Train Loss: 0.950, Val f1_micro: 0.282
Epoch: 380, Train Loss: 0.942, Val f1_micro: 0.283
Epoch: 400, Train Loss: 0.912, Val f1_micro: 0.286
Epoch: 420, Train Loss: 0.897, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.909, Val f1_micro: 0.291
Epoch: 460, Train Loss: 0.901, Val f1_micro: 0.292
Epoch: 480, Train Loss: 0.887, Val f1_micro: 0.288
Epoch: 500, Train Loss: 0.894, Val f1_micro: 0.293
f1-micro: 0.293, f1-macro: 0.281, f1-weighted: 0.286, , roc-auc: 0.666
##### RUN 5 #####
Epoch: 020, Train Loss: 1.771, Val f1_micro: 0.223
Epoch: 040, Train Loss: 1.511, Val f1_micro: 0.247
Epoch: 060, Train Loss: 1.410, Val f1_micro: 0.256
Epoch: 080, Train Loss: 1.312, Val f1_micro: 0.261
Epoch: 100, Train Loss: 1.246, Val f1_micro: 0.263
Epoch: 120, Train Loss: 1.192, Val f1_micro: 0.268
Epoch: 140, Train Loss: 1.165, Val f1_micro: 0.269
Epoch: 160, Train Loss: 1.133, Val f1_micro: 0.273
Epoch: 180, Train Loss: 1.089, Val f1_micro: 0.274
Epoch: 200, Train Loss: 1.084, Val f1_micro: 0.277
Epoch: 220, Train Loss: 1.060, Val f1_micro: 0.277
Epoch: 240, Train Loss: 1.034, Val f1_micro: 0.275
Epoch: 260, Train Loss: 1.022, Val f1_micro: 0.280
Epoch: 280, Train Loss: 1.019, Val f1_micro: 0.283
Epoch: 300, Train Loss: 0.981, Val f1_micro: 0.283
Epoch: 320, Train Loss: 0.983, Val f1_micro: 0.288
Epoch: 340, Train Loss: 0.960, Val f1_micro: 0.279
Epoch: 360, Train Loss: 0.948, Val f1_micro: 0.284
Epoch: 380, Train Loss: 0.933, Val f1_micro: 0.286
Epoch: 400, Train Loss: 0.915, Val f1_micro: 0.285
Epoch: 420, Train Loss: 0.902, Val f1_micro: 0.282
Epoch: 440, Train Loss: 0.894, Val f1_micro: 0.291
Epoch: 460, Train Loss: 0.922, Val f1_micro: 0.290
Epoch: 480, Train Loss: 0.888, Val f1_micro: 0.297
Epoch: 500, Train Loss: 0.876, Val f1_micro: 0.293
f1-micro: 0.293, f1-macro: 0.282, f1-weighted: 0.288, , roc-auc: 0.665
########## Hyperparameters combination ##########
(512, 0.5, 0.005, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.812, Val f1_micro: 0.217
Epoch: 040, Train Loss: 1.638, Val f1_micro: 0.233
Epoch: 060, Train Loss: 1.613, Val f1_micro: 0.235
Epoch: 080, Train Loss: 1.602, Val f1_micro: 0.231
Epoch: 100, Train Loss: 1.620, Val f1_micro: 0.233
Epoch: 120, Train Loss: 1.610, Val f1_micro: 0.227
Epoch: 140, Train Loss: 1.621, Val f1_micro: 0.229
Epoch: 160, Train Loss: 1.625, Val f1_micro: 0.227
Epoch: 180, Train Loss: 1.628, Val f1_micro: 0.236
Epoch: 200, Train Loss: 1.642, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.638, Val f1_micro: 0.228
Epoch: 240, Train Loss: 1.643, Val f1_micro: 0.228
Epoch: 260, Train Loss: 1.644, Val f1_micro: 0.224
Epoch: 280, Train Loss: 1.641, Val f1_micro: 0.229
Epoch: 300, Train Loss: 1.640, Val f1_micro: 0.224
Epoch: 320, Train Loss: 1.638, Val f1_micro: 0.221
Epoch: 340, Train Loss: 1.638, Val f1_micro: 0.224
Epoch: 360, Train Loss: 1.641, Val f1_micro: 0.226
Epoch: 380, Train Loss: 1.653, Val f1_micro: 0.229
Epoch: 400, Train Loss: 1.642, Val f1_micro: 0.230
Epoch: 420, Train Loss: 1.643, Val f1_micro: 0.229
Epoch: 440, Train Loss: 1.642, Val f1_micro: 0.219
Epoch: 460, Train Loss: 1.637, Val f1_micro: 0.228
Epoch: 480, Train Loss: 1.633, Val f1_micro: 0.219
Epoch: 500, Train Loss: 1.626, Val f1_micro: 0.226
f1-micro: 0.226, f1-macro: 0.194, f1-weighted: 0.194, , roc-auc: 0.639
##### RUN 2 #####
Epoch: 020, Train Loss: 1.805, Val f1_micro: 0.212
Epoch: 040, Train Loss: 1.645, Val f1_micro: 0.230
Epoch: 060, Train Loss: 1.598, Val f1_micro: 0.226
Epoch: 080, Train Loss: 1.606, Val f1_micro: 0.235
Epoch: 100, Train Loss: 1.609, Val f1_micro: 0.233
Epoch: 120, Train Loss: 1.612, Val f1_micro: 0.226
Epoch: 140, Train Loss: 1.623, Val f1_micro: 0.225
Epoch: 160, Train Loss: 1.628, Val f1_micro: 0.228
Epoch: 180, Train Loss: 1.621, Val f1_micro: 0.225
Epoch: 200, Train Loss: 1.640, Val f1_micro: 0.232
Epoch: 220, Train Loss: 1.642, Val f1_micro: 0.230
Epoch: 240, Train Loss: 1.636, Val f1_micro: 0.224
Epoch: 260, Train Loss: 1.635, Val f1_micro: 0.221
Epoch: 280, Train Loss: 1.648, Val f1_micro: 0.228
Epoch: 300, Train Loss: 1.656, Val f1_micro: 0.220
Epoch: 320, Train Loss: 1.643, Val f1_micro: 0.223
Epoch: 340, Train Loss: 1.643, Val f1_micro: 0.228
Epoch: 360, Train Loss: 1.637, Val f1_micro: 0.229
Epoch: 380, Train Loss: 1.645, Val f1_micro: 0.230
Epoch: 400, Train Loss: 1.634, Val f1_micro: 0.220
Epoch: 420, Train Loss: 1.643, Val f1_micro: 0.228
Epoch: 440, Train Loss: 1.640, Val f1_micro: 0.227
Epoch: 460, Train Loss: 1.643, Val f1_micro: 0.224
Epoch: 480, Train Loss: 1.632, Val f1_micro: 0.221
Epoch: 500, Train Loss: 1.649, Val f1_micro: 0.221
f1-micro: 0.221, f1-macro: 0.189, f1-weighted: 0.189, , roc-auc: 0.639
##### RUN 3 #####
Epoch: 020, Train Loss: 1.797, Val f1_micro: 0.217
Epoch: 040, Train Loss: 1.639, Val f1_micro: 0.229
Epoch: 060, Train Loss: 1.596, Val f1_micro: 0.239
Epoch: 080, Train Loss: 1.590, Val f1_micro: 0.235
Epoch: 100, Train Loss: 1.612, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.602, Val f1_micro: 0.224
Epoch: 140, Train Loss: 1.623, Val f1_micro: 0.228
Epoch: 160, Train Loss: 1.620, Val f1_micro: 0.229
Epoch: 180, Train Loss: 1.634, Val f1_micro: 0.222
Epoch: 200, Train Loss: 1.633, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.628, Val f1_micro: 0.226
Epoch: 240, Train Loss: 1.630, Val f1_micro: 0.230
Epoch: 260, Train Loss: 1.643, Val f1_micro: 0.227
Epoch: 280, Train Loss: 1.643, Val f1_micro: 0.230
Epoch: 300, Train Loss: 1.648, Val f1_micro: 0.224
Epoch: 320, Train Loss: 1.646, Val f1_micro: 0.225
Epoch: 340, Train Loss: 1.651, Val f1_micro: 0.222
Epoch: 360, Train Loss: 1.627, Val f1_micro: 0.221
Epoch: 380, Train Loss: 1.628, Val f1_micro: 0.224
Epoch: 400, Train Loss: 1.646, Val f1_micro: 0.223
Epoch: 420, Train Loss: 1.655, Val f1_micro: 0.224
Epoch: 440, Train Loss: 1.647, Val f1_micro: 0.226
Epoch: 460, Train Loss: 1.635, Val f1_micro: 0.221
Epoch: 480, Train Loss: 1.636, Val f1_micro: 0.229
Epoch: 500, Train Loss: 1.632, Val f1_micro: 0.219
f1-micro: 0.219, f1-macro: 0.186, f1-weighted: 0.186, , roc-auc: 0.638
##### RUN 4 #####
Epoch: 020, Train Loss: 1.789, Val f1_micro: 0.221
Epoch: 040, Train Loss: 1.615, Val f1_micro: 0.226
Epoch: 060, Train Loss: 1.611, Val f1_micro: 0.235
Epoch: 080, Train Loss: 1.599, Val f1_micro: 0.231
Epoch: 100, Train Loss: 1.605, Val f1_micro: 0.229
Epoch: 120, Train Loss: 1.603, Val f1_micro: 0.228
Epoch: 140, Train Loss: 1.614, Val f1_micro: 0.227
Epoch: 160, Train Loss: 1.622, Val f1_micro: 0.225
Epoch: 180, Train Loss: 1.619, Val f1_micro: 0.225
Epoch: 200, Train Loss: 1.637, Val f1_micro: 0.228
Epoch: 220, Train Loss: 1.639, Val f1_micro: 0.228
Epoch: 240, Train Loss: 1.633, Val f1_micro: 0.225
Epoch: 260, Train Loss: 1.641, Val f1_micro: 0.223
Epoch: 280, Train Loss: 1.646, Val f1_micro: 0.232
Epoch: 300, Train Loss: 1.645, Val f1_micro: 0.224
Epoch: 320, Train Loss: 1.636, Val f1_micro: 0.223
Epoch: 340, Train Loss: 1.642, Val f1_micro: 0.223
Epoch: 360, Train Loss: 1.652, Val f1_micro: 0.220
Epoch: 380, Train Loss: 1.636, Val f1_micro: 0.223
Epoch: 400, Train Loss: 1.637, Val f1_micro: 0.222
Epoch: 420, Train Loss: 1.643, Val f1_micro: 0.222
Epoch: 440, Train Loss: 1.645, Val f1_micro: 0.222
Epoch: 460, Train Loss: 1.647, Val f1_micro: 0.223
Epoch: 480, Train Loss: 1.639, Val f1_micro: 0.228
Epoch: 500, Train Loss: 1.643, Val f1_micro: 0.233
f1-micro: 0.233, f1-macro: 0.195, f1-weighted: 0.196, , roc-auc: 0.639
##### RUN 5 #####
Epoch: 020, Train Loss: 1.791, Val f1_micro: 0.212
Epoch: 040, Train Loss: 1.631, Val f1_micro: 0.218
Epoch: 060, Train Loss: 1.591, Val f1_micro: 0.230
Epoch: 080, Train Loss: 1.607, Val f1_micro: 0.228
Epoch: 100, Train Loss: 1.599, Val f1_micro: 0.229
Epoch: 120, Train Loss: 1.602, Val f1_micro: 0.231
Epoch: 140, Train Loss: 1.617, Val f1_micro: 0.223
Epoch: 160, Train Loss: 1.618, Val f1_micro: 0.229
Epoch: 180, Train Loss: 1.627, Val f1_micro: 0.220
Epoch: 200, Train Loss: 1.620, Val f1_micro: 0.229
Epoch: 220, Train Loss: 1.646, Val f1_micro: 0.232
Epoch: 240, Train Loss: 1.641, Val f1_micro: 0.230
Epoch: 260, Train Loss: 1.636, Val f1_micro: 0.232
Epoch: 280, Train Loss: 1.641, Val f1_micro: 0.232
Epoch: 300, Train Loss: 1.643, Val f1_micro: 0.224
Epoch: 320, Train Loss: 1.634, Val f1_micro: 0.225
Epoch: 340, Train Loss: 1.644, Val f1_micro: 0.224
Epoch: 360, Train Loss: 1.640, Val f1_micro: 0.229
Epoch: 380, Train Loss: 1.643, Val f1_micro: 0.229
Epoch: 400, Train Loss: 1.648, Val f1_micro: 0.226
Epoch: 420, Train Loss: 1.651, Val f1_micro: 0.217
Epoch: 440, Train Loss: 1.640, Val f1_micro: 0.222
Epoch: 460, Train Loss: 1.638, Val f1_micro: 0.224
Epoch: 480, Train Loss: 1.640, Val f1_micro: 0.226
Epoch: 500, Train Loss: 1.652, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.198, f1-weighted: 0.198, , roc-auc: 0.641
########## Hyperparameters combination ##########
(512, 0.5, 0.01, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.679, Val f1_micro: 0.220
Epoch: 040, Train Loss: 1.386, Val f1_micro: 0.253
Epoch: 060, Train Loss: 1.238, Val f1_micro: 0.265
Epoch: 080, Train Loss: 1.083, Val f1_micro: 0.275
Epoch: 100, Train Loss: 0.996, Val f1_micro: 0.281
Epoch: 120, Train Loss: 0.871, Val f1_micro: 0.291
Epoch: 140, Train Loss: 0.819, Val f1_micro: 0.298
Epoch: 160, Train Loss: 0.722, Val f1_micro: 0.297
Epoch: 180, Train Loss: 0.669, Val f1_micro: 0.304
Epoch: 200, Train Loss: 0.617, Val f1_micro: 0.307
Epoch: 220, Train Loss: 0.560, Val f1_micro: 0.309
Epoch: 240, Train Loss: 0.513, Val f1_micro: 0.311
Epoch: 260, Train Loss: 0.513, Val f1_micro: 0.312
Epoch: 280, Train Loss: 0.454, Val f1_micro: 0.317
Epoch: 300, Train Loss: 0.433, Val f1_micro: 0.316
Epoch: 320, Train Loss: 0.421, Val f1_micro: 0.316
Epoch: 340, Train Loss: 0.385, Val f1_micro: 0.319
Epoch: 360, Train Loss: 0.364, Val f1_micro: 0.318
Epoch: 380, Train Loss: 0.346, Val f1_micro: 0.319
Epoch: 400, Train Loss: 0.326, Val f1_micro: 0.320
Epoch: 420, Train Loss: 0.319, Val f1_micro: 0.318
Epoch: 440, Train Loss: 0.308, Val f1_micro: 0.319
Epoch: 460, Train Loss: 0.290, Val f1_micro: 0.322
Epoch: 480, Train Loss: 0.286, Val f1_micro: 0.321
Epoch: 500, Train Loss: 0.278, Val f1_micro: 0.319
f1-micro: 0.319, f1-macro: 0.312, f1-weighted: 0.318, , roc-auc: 0.681
##### RUN 2 #####
Epoch: 020, Train Loss: 1.697, Val f1_micro: 0.219
Epoch: 040, Train Loss: 1.390, Val f1_micro: 0.255
Epoch: 060, Train Loss: 1.248, Val f1_micro: 0.273
Epoch: 080, Train Loss: 1.104, Val f1_micro: 0.281
Epoch: 100, Train Loss: 0.967, Val f1_micro: 0.285
Epoch: 120, Train Loss: 0.890, Val f1_micro: 0.291
Epoch: 140, Train Loss: 0.800, Val f1_micro: 0.291
Epoch: 160, Train Loss: 0.731, Val f1_micro: 0.299
Epoch: 180, Train Loss: 0.670, Val f1_micro: 0.305
Epoch: 200, Train Loss: 0.629, Val f1_micro: 0.306
Epoch: 220, Train Loss: 0.576, Val f1_micro: 0.309
Epoch: 240, Train Loss: 0.527, Val f1_micro: 0.314
Epoch: 260, Train Loss: 0.493, Val f1_micro: 0.316
Epoch: 280, Train Loss: 0.452, Val f1_micro: 0.312
Epoch: 300, Train Loss: 0.451, Val f1_micro: 0.319
Epoch: 320, Train Loss: 0.411, Val f1_micro: 0.319
Epoch: 340, Train Loss: 0.394, Val f1_micro: 0.318
Epoch: 360, Train Loss: 0.350, Val f1_micro: 0.320
Epoch: 380, Train Loss: 0.344, Val f1_micro: 0.317
Epoch: 400, Train Loss: 0.344, Val f1_micro: 0.318
Epoch: 420, Train Loss: 0.310, Val f1_micro: 0.320
Epoch: 440, Train Loss: 0.296, Val f1_micro: 0.318
Epoch: 460, Train Loss: 0.286, Val f1_micro: 0.315
Epoch: 480, Train Loss: 0.287, Val f1_micro: 0.319
Epoch: 500, Train Loss: 0.267, Val f1_micro: 0.319
f1-micro: 0.319, f1-macro: 0.311, f1-weighted: 0.318, , roc-auc: 0.682
##### RUN 3 #####
Epoch: 020, Train Loss: 1.685, Val f1_micro: 0.221
Epoch: 040, Train Loss: 1.420, Val f1_micro: 0.253
Epoch: 060, Train Loss: 1.237, Val f1_micro: 0.266
Epoch: 080, Train Loss: 1.092, Val f1_micro: 0.279
Epoch: 100, Train Loss: 0.997, Val f1_micro: 0.277
Epoch: 120, Train Loss: 0.887, Val f1_micro: 0.280
Epoch: 140, Train Loss: 0.812, Val f1_micro: 0.293
Epoch: 160, Train Loss: 0.738, Val f1_micro: 0.299
Epoch: 180, Train Loss: 0.661, Val f1_micro: 0.302
Epoch: 200, Train Loss: 0.642, Val f1_micro: 0.303
Epoch: 220, Train Loss: 0.570, Val f1_micro: 0.310
Epoch: 240, Train Loss: 0.549, Val f1_micro: 0.311
Epoch: 260, Train Loss: 0.477, Val f1_micro: 0.311
Epoch: 280, Train Loss: 0.459, Val f1_micro: 0.315
Epoch: 300, Train Loss: 0.432, Val f1_micro: 0.316
Epoch: 320, Train Loss: 0.411, Val f1_micro: 0.317
Epoch: 340, Train Loss: 0.381, Val f1_micro: 0.320
Epoch: 360, Train Loss: 0.361, Val f1_micro: 0.315
Epoch: 380, Train Loss: 0.357, Val f1_micro: 0.316
Epoch: 400, Train Loss: 0.331, Val f1_micro: 0.319
Epoch: 420, Train Loss: 0.343, Val f1_micro: 0.318
Epoch: 440, Train Loss: 0.284, Val f1_micro: 0.320
Epoch: 460, Train Loss: 0.289, Val f1_micro: 0.320
Epoch: 480, Train Loss: 0.306, Val f1_micro: 0.320
Epoch: 500, Train Loss: 0.275, Val f1_micro: 0.318
f1-micro: 0.318, f1-macro: 0.312, f1-weighted: 0.318, , roc-auc: 0.684
##### RUN 4 #####
Epoch: 020, Train Loss: 1.698, Val f1_micro: 0.218
Epoch: 040, Train Loss: 1.406, Val f1_micro: 0.252
Epoch: 060, Train Loss: 1.229, Val f1_micro: 0.271
Epoch: 080, Train Loss: 1.111, Val f1_micro: 0.280
Epoch: 100, Train Loss: 0.966, Val f1_micro: 0.283
Epoch: 120, Train Loss: 0.886, Val f1_micro: 0.287
Epoch: 140, Train Loss: 0.803, Val f1_micro: 0.296
Epoch: 160, Train Loss: 0.735, Val f1_micro: 0.300
Epoch: 180, Train Loss: 0.675, Val f1_micro: 0.304
Epoch: 200, Train Loss: 0.605, Val f1_micro: 0.309
Epoch: 220, Train Loss: 0.575, Val f1_micro: 0.313
Epoch: 240, Train Loss: 0.511, Val f1_micro: 0.312
Epoch: 260, Train Loss: 0.491, Val f1_micro: 0.315
Epoch: 280, Train Loss: 0.439, Val f1_micro: 0.312
Epoch: 300, Train Loss: 0.418, Val f1_micro: 0.317
Epoch: 320, Train Loss: 0.412, Val f1_micro: 0.315
Epoch: 340, Train Loss: 0.389, Val f1_micro: 0.314
Epoch: 360, Train Loss: 0.352, Val f1_micro: 0.319
Epoch: 380, Train Loss: 0.339, Val f1_micro: 0.317
Epoch: 400, Train Loss: 0.319, Val f1_micro: 0.319
Epoch: 420, Train Loss: 0.320, Val f1_micro: 0.322
Epoch: 440, Train Loss: 0.309, Val f1_micro: 0.320
Epoch: 460, Train Loss: 0.302, Val f1_micro: 0.317
Epoch: 480, Train Loss: 0.277, Val f1_micro: 0.321
Epoch: 500, Train Loss: 0.263, Val f1_micro: 0.319
f1-micro: 0.319, f1-macro: 0.312, f1-weighted: 0.319, , roc-auc: 0.681
##### RUN 5 #####
Epoch: 020, Train Loss: 1.704, Val f1_micro: 0.223
Epoch: 040, Train Loss: 1.401, Val f1_micro: 0.251
Epoch: 060, Train Loss: 1.215, Val f1_micro: 0.275
Epoch: 080, Train Loss: 1.074, Val f1_micro: 0.279
Epoch: 100, Train Loss: 0.960, Val f1_micro: 0.288
Epoch: 120, Train Loss: 0.898, Val f1_micro: 0.290
Epoch: 140, Train Loss: 0.813, Val f1_micro: 0.295
Epoch: 160, Train Loss: 0.729, Val f1_micro: 0.298
Epoch: 180, Train Loss: 0.672, Val f1_micro: 0.301
Epoch: 200, Train Loss: 0.612, Val f1_micro: 0.308
Epoch: 220, Train Loss: 0.573, Val f1_micro: 0.311
Epoch: 240, Train Loss: 0.515, Val f1_micro: 0.313
Epoch: 260, Train Loss: 0.502, Val f1_micro: 0.316
Epoch: 280, Train Loss: 0.459, Val f1_micro: 0.314
Epoch: 300, Train Loss: 0.422, Val f1_micro: 0.316
Epoch: 320, Train Loss: 0.403, Val f1_micro: 0.317
Epoch: 340, Train Loss: 0.374, Val f1_micro: 0.313
Epoch: 360, Train Loss: 0.370, Val f1_micro: 0.317
Epoch: 380, Train Loss: 0.357, Val f1_micro: 0.316
Epoch: 400, Train Loss: 0.331, Val f1_micro: 0.317
Epoch: 420, Train Loss: 0.303, Val f1_micro: 0.317
Epoch: 440, Train Loss: 0.327, Val f1_micro: 0.317
Epoch: 460, Train Loss: 0.294, Val f1_micro: 0.321
Epoch: 480, Train Loss: 0.288, Val f1_micro: 0.318
Epoch: 500, Train Loss: 0.257, Val f1_micro: 0.320
f1-micro: 0.320, f1-macro: 0.313, f1-weighted: 0.319, , roc-auc: 0.680
########## Hyperparameters combination ##########
(512, 0.5, 0.01, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.676, Val f1_micro: 0.218
Epoch: 040, Train Loss: 1.417, Val f1_micro: 0.242
Epoch: 060, Train Loss: 1.270, Val f1_micro: 0.266
Epoch: 080, Train Loss: 1.173, Val f1_micro: 0.271
Epoch: 100, Train Loss: 1.080, Val f1_micro: 0.270
Epoch: 120, Train Loss: 1.035, Val f1_micro: 0.271
Epoch: 140, Train Loss: 0.956, Val f1_micro: 0.285
Epoch: 160, Train Loss: 0.910, Val f1_micro: 0.283
Epoch: 180, Train Loss: 0.859, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.834, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.814, Val f1_micro: 0.292
Epoch: 240, Train Loss: 0.784, Val f1_micro: 0.295
Epoch: 260, Train Loss: 0.759, Val f1_micro: 0.301
Epoch: 280, Train Loss: 0.722, Val f1_micro: 0.300
Epoch: 300, Train Loss: 0.697, Val f1_micro: 0.301
Epoch: 320, Train Loss: 0.665, Val f1_micro: 0.304
Epoch: 340, Train Loss: 0.664, Val f1_micro: 0.303
Epoch: 360, Train Loss: 0.662, Val f1_micro: 0.302
Epoch: 380, Train Loss: 0.640, Val f1_micro: 0.300
Epoch: 400, Train Loss: 0.605, Val f1_micro: 0.306
Epoch: 420, Train Loss: 0.606, Val f1_micro: 0.307
Epoch: 440, Train Loss: 0.595, Val f1_micro: 0.307
Epoch: 460, Train Loss: 0.573, Val f1_micro: 0.304
Epoch: 480, Train Loss: 0.583, Val f1_micro: 0.309
Epoch: 500, Train Loss: 0.553, Val f1_micro: 0.310
f1-micro: 0.310, f1-macro: 0.303, f1-weighted: 0.309, , roc-auc: 0.675
##### RUN 2 #####
Epoch: 020, Train Loss: 1.677, Val f1_micro: 0.218
Epoch: 040, Train Loss: 1.406, Val f1_micro: 0.250
Epoch: 060, Train Loss: 1.281, Val f1_micro: 0.264
Epoch: 080, Train Loss: 1.160, Val f1_micro: 0.264
Epoch: 100, Train Loss: 1.086, Val f1_micro: 0.272
Epoch: 120, Train Loss: 1.020, Val f1_micro: 0.274
Epoch: 140, Train Loss: 0.963, Val f1_micro: 0.280
Epoch: 160, Train Loss: 0.906, Val f1_micro: 0.284
Epoch: 180, Train Loss: 0.872, Val f1_micro: 0.287
Epoch: 200, Train Loss: 0.854, Val f1_micro: 0.283
Epoch: 220, Train Loss: 0.816, Val f1_micro: 0.288
Epoch: 240, Train Loss: 0.795, Val f1_micro: 0.290
Epoch: 260, Train Loss: 0.746, Val f1_micro: 0.295
Epoch: 280, Train Loss: 0.730, Val f1_micro: 0.296
Epoch: 300, Train Loss: 0.708, Val f1_micro: 0.301
Epoch: 320, Train Loss: 0.684, Val f1_micro: 0.301
Epoch: 340, Train Loss: 0.679, Val f1_micro: 0.301
Epoch: 360, Train Loss: 0.648, Val f1_micro: 0.306
Epoch: 380, Train Loss: 0.653, Val f1_micro: 0.302
Epoch: 400, Train Loss: 0.615, Val f1_micro: 0.300
Epoch: 420, Train Loss: 0.620, Val f1_micro: 0.306
Epoch: 440, Train Loss: 0.582, Val f1_micro: 0.304
Epoch: 460, Train Loss: 0.594, Val f1_micro: 0.305
Epoch: 480, Train Loss: 0.593, Val f1_micro: 0.307
Epoch: 500, Train Loss: 0.583, Val f1_micro: 0.305
f1-micro: 0.305, f1-macro: 0.299, f1-weighted: 0.305, , roc-auc: 0.674
##### RUN 3 #####
Epoch: 020, Train Loss: 1.693, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.415, Val f1_micro: 0.249
Epoch: 060, Train Loss: 1.256, Val f1_micro: 0.265
Epoch: 080, Train Loss: 1.165, Val f1_micro: 0.270
Epoch: 100, Train Loss: 1.083, Val f1_micro: 0.271
Epoch: 120, Train Loss: 1.019, Val f1_micro: 0.273
Epoch: 140, Train Loss: 0.967, Val f1_micro: 0.278
Epoch: 160, Train Loss: 0.923, Val f1_micro: 0.287
Epoch: 180, Train Loss: 0.881, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.857, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.801, Val f1_micro: 0.291
Epoch: 240, Train Loss: 0.773, Val f1_micro: 0.298
Epoch: 260, Train Loss: 0.748, Val f1_micro: 0.299
Epoch: 280, Train Loss: 0.728, Val f1_micro: 0.297
Epoch: 300, Train Loss: 0.715, Val f1_micro: 0.301
Epoch: 320, Train Loss: 0.705, Val f1_micro: 0.303
Epoch: 340, Train Loss: 0.668, Val f1_micro: 0.305
Epoch: 360, Train Loss: 0.668, Val f1_micro: 0.305
Epoch: 380, Train Loss: 0.641, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.639, Val f1_micro: 0.302
Epoch: 420, Train Loss: 0.604, Val f1_micro: 0.309
Epoch: 440, Train Loss: 0.602, Val f1_micro: 0.307
Epoch: 460, Train Loss: 0.601, Val f1_micro: 0.311
Epoch: 480, Train Loss: 0.599, Val f1_micro: 0.303
Epoch: 500, Train Loss: 0.583, Val f1_micro: 0.312
f1-micro: 0.312, f1-macro: 0.303, f1-weighted: 0.309, , roc-auc: 0.675
##### RUN 4 #####
Epoch: 020, Train Loss: 1.697, Val f1_micro: 0.217
Epoch: 040, Train Loss: 1.419, Val f1_micro: 0.248
Epoch: 060, Train Loss: 1.294, Val f1_micro: 0.258
Epoch: 080, Train Loss: 1.172, Val f1_micro: 0.268
Epoch: 100, Train Loss: 1.088, Val f1_micro: 0.276
Epoch: 120, Train Loss: 1.025, Val f1_micro: 0.279
Epoch: 140, Train Loss: 0.963, Val f1_micro: 0.279
Epoch: 160, Train Loss: 0.932, Val f1_micro: 0.287
Epoch: 180, Train Loss: 0.885, Val f1_micro: 0.287
Epoch: 200, Train Loss: 0.840, Val f1_micro: 0.296
Epoch: 220, Train Loss: 0.818, Val f1_micro: 0.290
Epoch: 240, Train Loss: 0.794, Val f1_micro: 0.295
Epoch: 260, Train Loss: 0.751, Val f1_micro: 0.292
Epoch: 280, Train Loss: 0.733, Val f1_micro: 0.298
Epoch: 300, Train Loss: 0.708, Val f1_micro: 0.303
Epoch: 320, Train Loss: 0.688, Val f1_micro: 0.304
Epoch: 340, Train Loss: 0.653, Val f1_micro: 0.301
Epoch: 360, Train Loss: 0.656, Val f1_micro: 0.304
Epoch: 380, Train Loss: 0.638, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.629, Val f1_micro: 0.307
Epoch: 420, Train Loss: 0.609, Val f1_micro: 0.303
Epoch: 440, Train Loss: 0.596, Val f1_micro: 0.305
Epoch: 460, Train Loss: 0.590, Val f1_micro: 0.304
Epoch: 480, Train Loss: 0.582, Val f1_micro: 0.308
Epoch: 500, Train Loss: 0.578, Val f1_micro: 0.311
f1-micro: 0.311, f1-macro: 0.304, f1-weighted: 0.310, , roc-auc: 0.676
##### RUN 5 #####
Epoch: 020, Train Loss: 1.708, Val f1_micro: 0.218
Epoch: 040, Train Loss: 1.410, Val f1_micro: 0.252
Epoch: 060, Train Loss: 1.279, Val f1_micro: 0.264
Epoch: 080, Train Loss: 1.176, Val f1_micro: 0.266
Epoch: 100, Train Loss: 1.093, Val f1_micro: 0.273
Epoch: 120, Train Loss: 1.026, Val f1_micro: 0.279
Epoch: 140, Train Loss: 0.978, Val f1_micro: 0.278
Epoch: 160, Train Loss: 0.916, Val f1_micro: 0.279
Epoch: 180, Train Loss: 0.883, Val f1_micro: 0.288
Epoch: 200, Train Loss: 0.834, Val f1_micro: 0.291
Epoch: 220, Train Loss: 0.807, Val f1_micro: 0.289
Epoch: 240, Train Loss: 0.800, Val f1_micro: 0.291
Epoch: 260, Train Loss: 0.765, Val f1_micro: 0.293
Epoch: 280, Train Loss: 0.728, Val f1_micro: 0.294
Epoch: 300, Train Loss: 0.685, Val f1_micro: 0.298
Epoch: 320, Train Loss: 0.664, Val f1_micro: 0.298
Epoch: 340, Train Loss: 0.667, Val f1_micro: 0.298
Epoch: 360, Train Loss: 0.658, Val f1_micro: 0.304
Epoch: 380, Train Loss: 0.648, Val f1_micro: 0.301
Epoch: 400, Train Loss: 0.622, Val f1_micro: 0.302
Epoch: 420, Train Loss: 0.588, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.584, Val f1_micro: 0.303
Epoch: 460, Train Loss: 0.596, Val f1_micro: 0.307
Epoch: 480, Train Loss: 0.576, Val f1_micro: 0.304
Epoch: 500, Train Loss: 0.572, Val f1_micro: 0.305
f1-micro: 0.305, f1-macro: 0.299, f1-weighted: 0.305, , roc-auc: 0.674
########## Hyperparameters combination ##########
(512, 0.5, 0.01, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.695, Val f1_micro: 0.213
Epoch: 040, Train Loss: 1.427, Val f1_micro: 0.253
Epoch: 060, Train Loss: 1.305, Val f1_micro: 0.254
Epoch: 080, Train Loss: 1.255, Val f1_micro: 0.261
Epoch: 100, Train Loss: 1.165, Val f1_micro: 0.265
Epoch: 120, Train Loss: 1.133, Val f1_micro: 0.271
Epoch: 140, Train Loss: 1.096, Val f1_micro: 0.270
Epoch: 160, Train Loss: 1.051, Val f1_micro: 0.274
Epoch: 180, Train Loss: 1.028, Val f1_micro: 0.276
Epoch: 200, Train Loss: 1.016, Val f1_micro: 0.276
Epoch: 220, Train Loss: 0.982, Val f1_micro: 0.280
Epoch: 240, Train Loss: 0.977, Val f1_micro: 0.275
Epoch: 260, Train Loss: 0.943, Val f1_micro: 0.282
Epoch: 280, Train Loss: 0.936, Val f1_micro: 0.281
Epoch: 300, Train Loss: 0.915, Val f1_micro: 0.280
Epoch: 320, Train Loss: 0.919, Val f1_micro: 0.286
Epoch: 340, Train Loss: 0.903, Val f1_micro: 0.279
Epoch: 360, Train Loss: 0.899, Val f1_micro: 0.291
Epoch: 380, Train Loss: 0.876, Val f1_micro: 0.286
Epoch: 400, Train Loss: 0.862, Val f1_micro: 0.290
Epoch: 420, Train Loss: 0.861, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.873, Val f1_micro: 0.295
Epoch: 460, Train Loss: 0.841, Val f1_micro: 0.292
Epoch: 480, Train Loss: 0.834, Val f1_micro: 0.293
Epoch: 500, Train Loss: 0.877, Val f1_micro: 0.294
f1-micro: 0.294, f1-macro: 0.285, f1-weighted: 0.291, , roc-auc: 0.667
##### RUN 2 #####
Epoch: 020, Train Loss: 1.680, Val f1_micro: 0.209
Epoch: 040, Train Loss: 1.435, Val f1_micro: 0.253
Epoch: 060, Train Loss: 1.329, Val f1_micro: 0.260
Epoch: 080, Train Loss: 1.244, Val f1_micro: 0.263
Epoch: 100, Train Loss: 1.188, Val f1_micro: 0.266
Epoch: 120, Train Loss: 1.125, Val f1_micro: 0.271
Epoch: 140, Train Loss: 1.090, Val f1_micro: 0.278
Epoch: 160, Train Loss: 1.062, Val f1_micro: 0.276
Epoch: 180, Train Loss: 1.020, Val f1_micro: 0.279
Epoch: 200, Train Loss: 0.994, Val f1_micro: 0.279
Epoch: 220, Train Loss: 0.977, Val f1_micro: 0.281
Epoch: 240, Train Loss: 0.988, Val f1_micro: 0.281
Epoch: 260, Train Loss: 0.959, Val f1_micro: 0.279
Epoch: 280, Train Loss: 0.937, Val f1_micro: 0.284
Epoch: 300, Train Loss: 0.938, Val f1_micro: 0.288
Epoch: 320, Train Loss: 0.902, Val f1_micro: 0.287
Epoch: 340, Train Loss: 0.888, Val f1_micro: 0.286
Epoch: 360, Train Loss: 0.879, Val f1_micro: 0.286
Epoch: 380, Train Loss: 0.890, Val f1_micro: 0.289
Epoch: 400, Train Loss: 0.885, Val f1_micro: 0.288
Epoch: 420, Train Loss: 0.864, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.852, Val f1_micro: 0.283
Epoch: 460, Train Loss: 0.845, Val f1_micro: 0.286
Epoch: 480, Train Loss: 0.843, Val f1_micro: 0.291
Epoch: 500, Train Loss: 0.839, Val f1_micro: 0.293
f1-micro: 0.293, f1-macro: 0.285, f1-weighted: 0.290, , roc-auc: 0.665
##### RUN 3 #####
Epoch: 020, Train Loss: 1.713, Val f1_micro: 0.213
Epoch: 040, Train Loss: 1.435, Val f1_micro: 0.246
Epoch: 060, Train Loss: 1.318, Val f1_micro: 0.252
Epoch: 080, Train Loss: 1.240, Val f1_micro: 0.259
Epoch: 100, Train Loss: 1.199, Val f1_micro: 0.263
Epoch: 120, Train Loss: 1.138, Val f1_micro: 0.271
Epoch: 140, Train Loss: 1.094, Val f1_micro: 0.271
Epoch: 160, Train Loss: 1.071, Val f1_micro: 0.276
Epoch: 180, Train Loss: 1.031, Val f1_micro: 0.275
Epoch: 200, Train Loss: 1.021, Val f1_micro: 0.277
Epoch: 220, Train Loss: 0.988, Val f1_micro: 0.277
Epoch: 240, Train Loss: 0.972, Val f1_micro: 0.280
Epoch: 260, Train Loss: 0.957, Val f1_micro: 0.281
Epoch: 280, Train Loss: 0.937, Val f1_micro: 0.282
Epoch: 300, Train Loss: 0.931, Val f1_micro: 0.285
Epoch: 320, Train Loss: 0.924, Val f1_micro: 0.284
Epoch: 340, Train Loss: 0.924, Val f1_micro: 0.284
Epoch: 360, Train Loss: 0.903, Val f1_micro: 0.287
Epoch: 380, Train Loss: 0.880, Val f1_micro: 0.280
Epoch: 400, Train Loss: 0.885, Val f1_micro: 0.288
Epoch: 420, Train Loss: 0.875, Val f1_micro: 0.285
Epoch: 440, Train Loss: 0.860, Val f1_micro: 0.291
Epoch: 460, Train Loss: 0.843, Val f1_micro: 0.289
Epoch: 480, Train Loss: 0.860, Val f1_micro: 0.287
Epoch: 500, Train Loss: 0.850, Val f1_micro: 0.292
f1-micro: 0.292, f1-macro: 0.285, f1-weighted: 0.290, , roc-auc: 0.666
##### RUN 4 #####
Epoch: 020, Train Loss: 1.698, Val f1_micro: 0.220
Epoch: 040, Train Loss: 1.453, Val f1_micro: 0.246
Epoch: 060, Train Loss: 1.333, Val f1_micro: 0.259
Epoch: 080, Train Loss: 1.233, Val f1_micro: 0.258
Epoch: 100, Train Loss: 1.162, Val f1_micro: 0.269
Epoch: 120, Train Loss: 1.135, Val f1_micro: 0.269
Epoch: 140, Train Loss: 1.095, Val f1_micro: 0.272
Epoch: 160, Train Loss: 1.071, Val f1_micro: 0.275
Epoch: 180, Train Loss: 1.029, Val f1_micro: 0.274
Epoch: 200, Train Loss: 1.036, Val f1_micro: 0.278
Epoch: 220, Train Loss: 0.984, Val f1_micro: 0.274
Epoch: 240, Train Loss: 0.976, Val f1_micro: 0.279
Epoch: 260, Train Loss: 0.975, Val f1_micro: 0.275
Epoch: 280, Train Loss: 0.956, Val f1_micro: 0.282
Epoch: 300, Train Loss: 0.930, Val f1_micro: 0.282
Epoch: 320, Train Loss: 0.943, Val f1_micro: 0.282
Epoch: 340, Train Loss: 0.895, Val f1_micro: 0.287
Epoch: 360, Train Loss: 0.897, Val f1_micro: 0.288
Epoch: 380, Train Loss: 0.903, Val f1_micro: 0.285
Epoch: 400, Train Loss: 0.899, Val f1_micro: 0.287
Epoch: 420, Train Loss: 0.876, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.868, Val f1_micro: 0.292
Epoch: 460, Train Loss: 0.840, Val f1_micro: 0.289
Epoch: 480, Train Loss: 0.873, Val f1_micro: 0.291
Epoch: 500, Train Loss: 0.819, Val f1_micro: 0.294
f1-micro: 0.294, f1-macro: 0.285, f1-weighted: 0.290, , roc-auc: 0.666
##### RUN 5 #####
Epoch: 020, Train Loss: 1.694, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.454, Val f1_micro: 0.248
Epoch: 060, Train Loss: 1.341, Val f1_micro: 0.255
Epoch: 080, Train Loss: 1.250, Val f1_micro: 0.261
Epoch: 100, Train Loss: 1.186, Val f1_micro: 0.264
Epoch: 120, Train Loss: 1.148, Val f1_micro: 0.273
Epoch: 140, Train Loss: 1.104, Val f1_micro: 0.271
Epoch: 160, Train Loss: 1.056, Val f1_micro: 0.276
Epoch: 180, Train Loss: 1.050, Val f1_micro: 0.276
Epoch: 200, Train Loss: 1.004, Val f1_micro: 0.278
Epoch: 220, Train Loss: 1.009, Val f1_micro: 0.279
Epoch: 240, Train Loss: 0.960, Val f1_micro: 0.277
Epoch: 260, Train Loss: 0.975, Val f1_micro: 0.283
Epoch: 280, Train Loss: 0.924, Val f1_micro: 0.284
Epoch: 300, Train Loss: 0.938, Val f1_micro: 0.279
Epoch: 320, Train Loss: 0.910, Val f1_micro: 0.284
Epoch: 340, Train Loss: 0.898, Val f1_micro: 0.285
Epoch: 360, Train Loss: 0.870, Val f1_micro: 0.286
Epoch: 380, Train Loss: 0.889, Val f1_micro: 0.285
Epoch: 400, Train Loss: 0.889, Val f1_micro: 0.289
Epoch: 420, Train Loss: 0.882, Val f1_micro: 0.290
Epoch: 440, Train Loss: 0.865, Val f1_micro: 0.289
Epoch: 460, Train Loss: 0.857, Val f1_micro: 0.282
Epoch: 480, Train Loss: 0.846, Val f1_micro: 0.290
Epoch: 500, Train Loss: 0.830, Val f1_micro: 0.288
f1-micro: 0.288, f1-macro: 0.282, f1-weighted: 0.287, , roc-auc: 0.663
########## Hyperparameters combination ##########
(512, 0.5, 0.01, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.780, Val f1_micro: 0.203
Epoch: 040, Train Loss: 1.660, Val f1_micro: 0.221
Epoch: 060, Train Loss: 1.636, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.637, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.638, Val f1_micro: 0.223
Epoch: 120, Train Loss: 1.639, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.624, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.638, Val f1_micro: 0.225
Epoch: 180, Train Loss: 1.644, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.650, Val f1_micro: 0.220
Epoch: 220, Train Loss: 1.641, Val f1_micro: 0.213
Epoch: 240, Train Loss: 1.658, Val f1_micro: 0.217
Epoch: 260, Train Loss: 1.653, Val f1_micro: 0.223
Epoch: 280, Train Loss: 1.657, Val f1_micro: 0.220
Epoch: 300, Train Loss: 1.649, Val f1_micro: 0.220
Epoch: 320, Train Loss: 1.646, Val f1_micro: 0.208
Epoch: 340, Train Loss: 1.633, Val f1_micro: 0.224
Epoch: 360, Train Loss: 1.631, Val f1_micro: 0.212
Epoch: 380, Train Loss: 1.637, Val f1_micro: 0.214
Epoch: 400, Train Loss: 1.644, Val f1_micro: 0.226
Epoch: 420, Train Loss: 1.649, Val f1_micro: 0.221
Epoch: 440, Train Loss: 1.645, Val f1_micro: 0.222
Epoch: 460, Train Loss: 1.631, Val f1_micro: 0.230
Epoch: 480, Train Loss: 1.650, Val f1_micro: 0.223
Epoch: 500, Train Loss: 1.648, Val f1_micro: 0.225
f1-micro: 0.225, f1-macro: 0.186, f1-weighted: 0.185, , roc-auc: 0.642
##### RUN 2 #####
Epoch: 020, Train Loss: 1.760, Val f1_micro: 0.199
Epoch: 040, Train Loss: 1.652, Val f1_micro: 0.217
Epoch: 060, Train Loss: 1.643, Val f1_micro: 0.224
Epoch: 080, Train Loss: 1.624, Val f1_micro: 0.222
Epoch: 100, Train Loss: 1.640, Val f1_micro: 0.222
Epoch: 120, Train Loss: 1.640, Val f1_micro: 0.216
Epoch: 140, Train Loss: 1.642, Val f1_micro: 0.223
Epoch: 160, Train Loss: 1.641, Val f1_micro: 0.222
Epoch: 180, Train Loss: 1.646, Val f1_micro: 0.223
Epoch: 200, Train Loss: 1.640, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.645, Val f1_micro: 0.225
Epoch: 240, Train Loss: 1.642, Val f1_micro: 0.222
Epoch: 260, Train Loss: 1.656, Val f1_micro: 0.223
Epoch: 280, Train Loss: 1.644, Val f1_micro: 0.217
Epoch: 300, Train Loss: 1.646, Val f1_micro: 0.221
Epoch: 320, Train Loss: 1.651, Val f1_micro: 0.214
Epoch: 340, Train Loss: 1.644, Val f1_micro: 0.223
Epoch: 360, Train Loss: 1.633, Val f1_micro: 0.216
Epoch: 380, Train Loss: 1.647, Val f1_micro: 0.220
Epoch: 400, Train Loss: 1.647, Val f1_micro: 0.228
Epoch: 420, Train Loss: 1.633, Val f1_micro: 0.225
Epoch: 440, Train Loss: 1.649, Val f1_micro: 0.218
Epoch: 460, Train Loss: 1.636, Val f1_micro: 0.221
Epoch: 480, Train Loss: 1.633, Val f1_micro: 0.211
Epoch: 500, Train Loss: 1.636, Val f1_micro: 0.218
f1-micro: 0.218, f1-macro: 0.184, f1-weighted: 0.183, , roc-auc: 0.640
##### RUN 3 #####
Epoch: 020, Train Loss: 1.766, Val f1_micro: 0.200
Epoch: 040, Train Loss: 1.656, Val f1_micro: 0.223
Epoch: 060, Train Loss: 1.623, Val f1_micro: 0.223
Epoch: 080, Train Loss: 1.629, Val f1_micro: 0.235
Epoch: 100, Train Loss: 1.632, Val f1_micro: 0.226
Epoch: 120, Train Loss: 1.637, Val f1_micro: 0.223
Epoch: 140, Train Loss: 1.639, Val f1_micro: 0.228
Epoch: 160, Train Loss: 1.643, Val f1_micro: 0.224
Epoch: 180, Train Loss: 1.643, Val f1_micro: 0.215
Epoch: 200, Train Loss: 1.655, Val f1_micro: 0.216
Epoch: 220, Train Loss: 1.663, Val f1_micro: 0.224
Epoch: 240, Train Loss: 1.664, Val f1_micro: 0.224
Epoch: 260, Train Loss: 1.659, Val f1_micro: 0.214
Epoch: 280, Train Loss: 1.649, Val f1_micro: 0.220
Epoch: 300, Train Loss: 1.653, Val f1_micro: 0.223
Epoch: 320, Train Loss: 1.659, Val f1_micro: 0.211
Epoch: 340, Train Loss: 1.655, Val f1_micro: 0.225
Epoch: 360, Train Loss: 1.647, Val f1_micro: 0.220
Epoch: 380, Train Loss: 1.646, Val f1_micro: 0.221
Epoch: 400, Train Loss: 1.658, Val f1_micro: 0.207
Epoch: 420, Train Loss: 1.658, Val f1_micro: 0.222
Epoch: 440, Train Loss: 1.628, Val f1_micro: 0.219
Epoch: 460, Train Loss: 1.645, Val f1_micro: 0.215
Epoch: 480, Train Loss: 1.648, Val f1_micro: 0.220
Epoch: 500, Train Loss: 1.621, Val f1_micro: 0.221
f1-micro: 0.221, f1-macro: 0.187, f1-weighted: 0.186, , roc-auc: 0.644
##### RUN 4 #####
Epoch: 020, Train Loss: 1.779, Val f1_micro: 0.210
Epoch: 040, Train Loss: 1.667, Val f1_micro: 0.226
Epoch: 060, Train Loss: 1.645, Val f1_micro: 0.229
Epoch: 080, Train Loss: 1.623, Val f1_micro: 0.227
Epoch: 100, Train Loss: 1.629, Val f1_micro: 0.222
Epoch: 120, Train Loss: 1.646, Val f1_micro: 0.228
Epoch: 140, Train Loss: 1.650, Val f1_micro: 0.225
Epoch: 160, Train Loss: 1.653, Val f1_micro: 0.227
Epoch: 180, Train Loss: 1.660, Val f1_micro: 0.213
Epoch: 200, Train Loss: 1.649, Val f1_micro: 0.225
Epoch: 220, Train Loss: 1.649, Val f1_micro: 0.223
Epoch: 240, Train Loss: 1.630, Val f1_micro: 0.219
Epoch: 260, Train Loss: 1.641, Val f1_micro: 0.217
Epoch: 280, Train Loss: 1.640, Val f1_micro: 0.218
Epoch: 300, Train Loss: 1.642, Val f1_micro: 0.223
Epoch: 320, Train Loss: 1.648, Val f1_micro: 0.231
Epoch: 340, Train Loss: 1.650, Val f1_micro: 0.218
Epoch: 360, Train Loss: 1.647, Val f1_micro: 0.213
Epoch: 380, Train Loss: 1.645, Val f1_micro: 0.225
Epoch: 400, Train Loss: 1.636, Val f1_micro: 0.223
Epoch: 420, Train Loss: 1.649, Val f1_micro: 0.224
Epoch: 440, Train Loss: 1.636, Val f1_micro: 0.226
Epoch: 460, Train Loss: 1.653, Val f1_micro: 0.222
Epoch: 480, Train Loss: 1.643, Val f1_micro: 0.223
Epoch: 500, Train Loss: 1.629, Val f1_micro: 0.215
f1-micro: 0.215, f1-macro: 0.178, f1-weighted: 0.178, , roc-auc: 0.644
##### RUN 5 #####
Epoch: 020, Train Loss: 1.771, Val f1_micro: 0.204
Epoch: 040, Train Loss: 1.652, Val f1_micro: 0.229
Epoch: 060, Train Loss: 1.621, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.613, Val f1_micro: 0.219
Epoch: 100, Train Loss: 1.614, Val f1_micro: 0.220
Epoch: 120, Train Loss: 1.646, Val f1_micro: 0.226
Epoch: 140, Train Loss: 1.651, Val f1_micro: 0.226
Epoch: 160, Train Loss: 1.649, Val f1_micro: 0.218
Epoch: 180, Train Loss: 1.639, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.644, Val f1_micro: 0.224
Epoch: 220, Train Loss: 1.653, Val f1_micro: 0.210
Epoch: 240, Train Loss: 1.664, Val f1_micro: 0.222
Epoch: 260, Train Loss: 1.651, Val f1_micro: 0.216
Epoch: 280, Train Loss: 1.657, Val f1_micro: 0.210
Epoch: 300, Train Loss: 1.645, Val f1_micro: 0.214
Epoch: 320, Train Loss: 1.663, Val f1_micro: 0.207
Epoch: 340, Train Loss: 1.640, Val f1_micro: 0.218
Epoch: 360, Train Loss: 1.647, Val f1_micro: 0.225
Epoch: 380, Train Loss: 1.651, Val f1_micro: 0.223
Epoch: 400, Train Loss: 1.636, Val f1_micro: 0.217
Epoch: 420, Train Loss: 1.644, Val f1_micro: 0.221
Epoch: 440, Train Loss: 1.636, Val f1_micro: 0.212
Epoch: 460, Train Loss: 1.639, Val f1_micro: 0.217
Epoch: 480, Train Loss: 1.619, Val f1_micro: 0.221
Epoch: 500, Train Loss: 1.636, Val f1_micro: 0.226
f1-micro: 0.226, f1-macro: 0.189, f1-weighted: 0.187, , roc-auc: 0.642
########## Hyperparameters combination ##########
(512, 0.5, 0.05, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.048, Val f1_micro: 0.143
Epoch: 040, Train Loss: 1.933, Val f1_micro: 0.169
Epoch: 060, Train Loss: 1.841, Val f1_micro: 0.178
Epoch: 080, Train Loss: 1.753, Val f1_micro: 0.136
Epoch: 100, Train Loss: 1.658, Val f1_micro: 0.177
Epoch: 120, Train Loss: 1.566, Val f1_micro: 0.186
Epoch: 140, Train Loss: 1.481, Val f1_micro: 0.190
Epoch: 160, Train Loss: 1.406, Val f1_micro: 0.202
Epoch: 180, Train Loss: 1.327, Val f1_micro: 0.209
Epoch: 200, Train Loss: 1.281, Val f1_micro: 0.222
Epoch: 220, Train Loss: 1.176, Val f1_micro: 0.225
Epoch: 240, Train Loss: 1.152, Val f1_micro: 0.236
Epoch: 260, Train Loss: 1.094, Val f1_micro: 0.240
Epoch: 280, Train Loss: 1.057, Val f1_micro: 0.241
Epoch: 300, Train Loss: 0.972, Val f1_micro: 0.249
Epoch: 320, Train Loss: 0.956, Val f1_micro: 0.248
Epoch: 340, Train Loss: 0.908, Val f1_micro: 0.259
Epoch: 360, Train Loss: 0.844, Val f1_micro: 0.267
Epoch: 380, Train Loss: 0.793, Val f1_micro: 0.268
Epoch: 400, Train Loss: 0.783, Val f1_micro: 0.270
Epoch: 420, Train Loss: 0.755, Val f1_micro: 0.271
Epoch: 440, Train Loss: 0.691, Val f1_micro: 0.274
Epoch: 460, Train Loss: 0.681, Val f1_micro: 0.280
Epoch: 480, Train Loss: 0.660, Val f1_micro: 0.274
Epoch: 500, Train Loss: 0.608, Val f1_micro: 0.283
f1-micro: 0.283, f1-macro: 0.279, f1-weighted: 0.283, , roc-auc: 0.654
##### RUN 2 #####
Epoch: 020, Train Loss: 2.007, Val f1_micro: 0.101
Epoch: 040, Train Loss: 1.934, Val f1_micro: 0.169
Epoch: 060, Train Loss: 1.819, Val f1_micro: 0.133
Epoch: 080, Train Loss: 1.709, Val f1_micro: 0.146
Epoch: 100, Train Loss: 1.644, Val f1_micro: 0.161
Epoch: 120, Train Loss: 1.556, Val f1_micro: 0.185
Epoch: 140, Train Loss: 1.440, Val f1_micro: 0.194
Epoch: 160, Train Loss: 1.319, Val f1_micro: 0.209
Epoch: 180, Train Loss: 1.242, Val f1_micro: 0.224
Epoch: 200, Train Loss: 1.178, Val f1_micro: 0.229
Epoch: 220, Train Loss: 1.061, Val f1_micro: 0.241
Epoch: 240, Train Loss: 0.999, Val f1_micro: 0.250
Epoch: 260, Train Loss: 0.931, Val f1_micro: 0.258
Epoch: 280, Train Loss: 0.902, Val f1_micro: 0.257
Epoch: 300, Train Loss: 0.844, Val f1_micro: 0.264
Epoch: 320, Train Loss: 0.789, Val f1_micro: 0.266
Epoch: 340, Train Loss: 0.792, Val f1_micro: 0.266
Epoch: 360, Train Loss: 0.700, Val f1_micro: 0.273
Epoch: 380, Train Loss: 0.714, Val f1_micro: 0.270
Epoch: 400, Train Loss: 0.718, Val f1_micro: 0.280
Epoch: 420, Train Loss: 0.659, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.628, Val f1_micro: 0.286
Epoch: 460, Train Loss: 0.593, Val f1_micro: 0.282
Epoch: 480, Train Loss: 0.556, Val f1_micro: 0.284
Epoch: 500, Train Loss: 0.577, Val f1_micro: 0.286
f1-micro: 0.286, f1-macro: 0.280, f1-weighted: 0.287, , roc-auc: 0.655
##### RUN 3 #####
Epoch: 020, Train Loss: 2.013, Val f1_micro: 0.099
Epoch: 040, Train Loss: 1.927, Val f1_micro: 0.172
Epoch: 060, Train Loss: 1.847, Val f1_micro: 0.133
Epoch: 080, Train Loss: 1.724, Val f1_micro: 0.156
Epoch: 100, Train Loss: 1.625, Val f1_micro: 0.169
Epoch: 120, Train Loss: 1.520, Val f1_micro: 0.180
Epoch: 140, Train Loss: 1.428, Val f1_micro: 0.192
Epoch: 160, Train Loss: 1.322, Val f1_micro: 0.199
Epoch: 180, Train Loss: 1.261, Val f1_micro: 0.216
Epoch: 200, Train Loss: 1.170, Val f1_micro: 0.224
Epoch: 220, Train Loss: 1.048, Val f1_micro: 0.231
Epoch: 240, Train Loss: 0.984, Val f1_micro: 0.244
Epoch: 260, Train Loss: 0.936, Val f1_micro: 0.253
Epoch: 280, Train Loss: 0.898, Val f1_micro: 0.252
Epoch: 300, Train Loss: 0.859, Val f1_micro: 0.256
Epoch: 320, Train Loss: 0.827, Val f1_micro: 0.268
Epoch: 340, Train Loss: 0.768, Val f1_micro: 0.267
Epoch: 360, Train Loss: 0.732, Val f1_micro: 0.270
Epoch: 380, Train Loss: 0.748, Val f1_micro: 0.273
Epoch: 400, Train Loss: 0.711, Val f1_micro: 0.276
Epoch: 420, Train Loss: 0.678, Val f1_micro: 0.277
Epoch: 440, Train Loss: 0.643, Val f1_micro: 0.280
Epoch: 460, Train Loss: 0.614, Val f1_micro: 0.279
Epoch: 480, Train Loss: 0.626, Val f1_micro: 0.281
Epoch: 500, Train Loss: 0.611, Val f1_micro: 0.282
f1-micro: 0.282, f1-macro: 0.277, f1-weighted: 0.282, , roc-auc: 0.653
##### RUN 4 #####
Epoch: 020, Train Loss: 2.019, Val f1_micro: 0.102
Epoch: 040, Train Loss: 1.920, Val f1_micro: 0.170
Epoch: 060, Train Loss: 1.853, Val f1_micro: 0.123
Epoch: 080, Train Loss: 1.769, Val f1_micro: 0.136
Epoch: 100, Train Loss: 1.683, Val f1_micro: 0.164
Epoch: 120, Train Loss: 1.579, Val f1_micro: 0.175
Epoch: 140, Train Loss: 1.468, Val f1_micro: 0.188
Epoch: 160, Train Loss: 1.378, Val f1_micro: 0.217
Epoch: 180, Train Loss: 1.235, Val f1_micro: 0.226
Epoch: 200, Train Loss: 1.139, Val f1_micro: 0.234
Epoch: 220, Train Loss: 1.077, Val f1_micro: 0.238
Epoch: 240, Train Loss: 0.981, Val f1_micro: 0.248
Epoch: 260, Train Loss: 0.910, Val f1_micro: 0.264
Epoch: 280, Train Loss: 0.862, Val f1_micro: 0.262
Epoch: 300, Train Loss: 0.825, Val f1_micro: 0.264
Epoch: 320, Train Loss: 0.765, Val f1_micro: 0.271
Epoch: 340, Train Loss: 0.738, Val f1_micro: 0.275
Epoch: 360, Train Loss: 0.697, Val f1_micro: 0.278
Epoch: 380, Train Loss: 0.696, Val f1_micro: 0.281
Epoch: 400, Train Loss: 0.630, Val f1_micro: 0.286
Epoch: 420, Train Loss: 0.612, Val f1_micro: 0.283
Epoch: 440, Train Loss: 0.619, Val f1_micro: 0.286
Epoch: 460, Train Loss: 0.613, Val f1_micro: 0.288
Epoch: 480, Train Loss: 0.561, Val f1_micro: 0.283
Epoch: 500, Train Loss: 0.540, Val f1_micro: 0.285
f1-micro: 0.285, f1-macro: 0.282, f1-weighted: 0.287, , roc-auc: 0.657
##### RUN 5 #####
Epoch: 020, Train Loss: 2.052, Val f1_micro: 0.099
Epoch: 040, Train Loss: 1.942, Val f1_micro: 0.168
Epoch: 060, Train Loss: 1.873, Val f1_micro: 0.132
Epoch: 080, Train Loss: 1.785, Val f1_micro: 0.142
Epoch: 100, Train Loss: 1.702, Val f1_micro: 0.168
Epoch: 120, Train Loss: 1.622, Val f1_micro: 0.192
Epoch: 140, Train Loss: 1.559, Val f1_micro: 0.190
Epoch: 160, Train Loss: 1.461, Val f1_micro: 0.200
Epoch: 180, Train Loss: 1.382, Val f1_micro: 0.204
Epoch: 200, Train Loss: 1.303, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.230, Val f1_micro: 0.234
Epoch: 240, Train Loss: 1.139, Val f1_micro: 0.238
Epoch: 260, Train Loss: 1.070, Val f1_micro: 0.243
Epoch: 280, Train Loss: 1.014, Val f1_micro: 0.248
Epoch: 300, Train Loss: 0.984, Val f1_micro: 0.256
Epoch: 320, Train Loss: 0.938, Val f1_micro: 0.259
Epoch: 340, Train Loss: 0.876, Val f1_micro: 0.267
Epoch: 360, Train Loss: 0.854, Val f1_micro: 0.266
Epoch: 380, Train Loss: 0.813, Val f1_micro: 0.267
Epoch: 400, Train Loss: 0.753, Val f1_micro: 0.268
Epoch: 420, Train Loss: 0.713, Val f1_micro: 0.269
Epoch: 440, Train Loss: 0.718, Val f1_micro: 0.271
Epoch: 460, Train Loss: 0.705, Val f1_micro: 0.271
Epoch: 480, Train Loss: 0.702, Val f1_micro: 0.288
Epoch: 500, Train Loss: 0.674, Val f1_micro: 0.284
f1-micro: 0.284, f1-macro: 0.276, f1-weighted: 0.282, , roc-auc: 0.660
########## Hyperparameters combination ##########
(512, 0.5, 0.05, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.052, Val f1_micro: 0.143
Epoch: 040, Train Loss: 1.954, Val f1_micro: 0.171
Epoch: 060, Train Loss: 1.873, Val f1_micro: 0.131
Epoch: 080, Train Loss: 1.783, Val f1_micro: 0.177
Epoch: 100, Train Loss: 1.676, Val f1_micro: 0.189
Epoch: 120, Train Loss: 1.622, Val f1_micro: 0.197
Epoch: 140, Train Loss: 1.534, Val f1_micro: 0.206
Epoch: 160, Train Loss: 1.472, Val f1_micro: 0.214
Epoch: 180, Train Loss: 1.434, Val f1_micro: 0.219
Epoch: 200, Train Loss: 1.381, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.329, Val f1_micro: 0.225
Epoch: 240, Train Loss: 1.280, Val f1_micro: 0.236
Epoch: 260, Train Loss: 1.232, Val f1_micro: 0.236
Epoch: 280, Train Loss: 1.212, Val f1_micro: 0.239
Epoch: 300, Train Loss: 1.167, Val f1_micro: 0.236
Epoch: 320, Train Loss: 1.194, Val f1_micro: 0.249
Epoch: 340, Train Loss: 1.101, Val f1_micro: 0.251
Epoch: 360, Train Loss: 1.089, Val f1_micro: 0.247
Epoch: 380, Train Loss: 1.134, Val f1_micro: 0.255
Epoch: 400, Train Loss: 1.057, Val f1_micro: 0.252
Epoch: 420, Train Loss: 1.039, Val f1_micro: 0.259
Epoch: 440, Train Loss: 1.060, Val f1_micro: 0.220
Epoch: 460, Train Loss: 1.026, Val f1_micro: 0.253
Epoch: 480, Train Loss: 0.996, Val f1_micro: 0.266
Epoch: 500, Train Loss: 0.990, Val f1_micro: 0.258
f1-micro: 0.258, f1-macro: 0.254, f1-weighted: 0.258, , roc-auc: 0.646
##### RUN 2 #####
Epoch: 020, Train Loss: 2.036, Val f1_micro: 0.100
Epoch: 040, Train Loss: 1.955, Val f1_micro: 0.173
Epoch: 060, Train Loss: 1.860, Val f1_micro: 0.178
Epoch: 080, Train Loss: 1.799, Val f1_micro: 0.153
Epoch: 100, Train Loss: 1.744, Val f1_micro: 0.196
Epoch: 120, Train Loss: 1.675, Val f1_micro: 0.194
Epoch: 140, Train Loss: 1.578, Val f1_micro: 0.201
Epoch: 160, Train Loss: 1.559, Val f1_micro: 0.207
Epoch: 180, Train Loss: 1.496, Val f1_micro: 0.220
Epoch: 200, Train Loss: 1.393, Val f1_micro: 0.216
Epoch: 220, Train Loss: 1.334, Val f1_micro: 0.223
Epoch: 240, Train Loss: 1.273, Val f1_micro: 0.235
Epoch: 260, Train Loss: 1.228, Val f1_micro: 0.237
Epoch: 280, Train Loss: 1.198, Val f1_micro: 0.247
Epoch: 300, Train Loss: 1.170, Val f1_micro: 0.247
Epoch: 320, Train Loss: 1.102, Val f1_micro: 0.244
Epoch: 340, Train Loss: 1.100, Val f1_micro: 0.248
Epoch: 360, Train Loss: 1.061, Val f1_micro: 0.259
Epoch: 380, Train Loss: 1.027, Val f1_micro: 0.264
Epoch: 400, Train Loss: 1.016, Val f1_micro: 0.259
Epoch: 420, Train Loss: 1.006, Val f1_micro: 0.263
Epoch: 440, Train Loss: 0.960, Val f1_micro: 0.272
Epoch: 460, Train Loss: 0.967, Val f1_micro: 0.264
Epoch: 480, Train Loss: 0.950, Val f1_micro: 0.268
Epoch: 500, Train Loss: 0.937, Val f1_micro: 0.272
f1-micro: 0.272, f1-macro: 0.257, f1-weighted: 0.262, , roc-auc: 0.650
##### RUN 3 #####
Epoch: 020, Train Loss: 2.024, Val f1_micro: 0.104
Epoch: 040, Train Loss: 1.939, Val f1_micro: 0.166
Epoch: 060, Train Loss: 1.839, Val f1_micro: 0.137
Epoch: 080, Train Loss: 1.752, Val f1_micro: 0.167
Epoch: 100, Train Loss: 1.647, Val f1_micro: 0.207
Epoch: 120, Train Loss: 1.579, Val f1_micro: 0.202
Epoch: 140, Train Loss: 1.492, Val f1_micro: 0.205
Epoch: 160, Train Loss: 1.430, Val f1_micro: 0.214
Epoch: 180, Train Loss: 1.385, Val f1_micro: 0.224
Epoch: 200, Train Loss: 1.346, Val f1_micro: 0.228
Epoch: 220, Train Loss: 1.270, Val f1_micro: 0.235
Epoch: 240, Train Loss: 1.209, Val f1_micro: 0.243
Epoch: 260, Train Loss: 1.221, Val f1_micro: 0.244
Epoch: 280, Train Loss: 1.183, Val f1_micro: 0.243
Epoch: 300, Train Loss: 1.129, Val f1_micro: 0.249
Epoch: 320, Train Loss: 1.121, Val f1_micro: 0.244
Epoch: 340, Train Loss: 1.092, Val f1_micro: 0.255
Epoch: 360, Train Loss: 1.096, Val f1_micro: 0.251
Epoch: 380, Train Loss: 1.079, Val f1_micro: 0.249
Epoch: 400, Train Loss: 1.049, Val f1_micro: 0.260
Epoch: 420, Train Loss: 1.018, Val f1_micro: 0.259
Epoch: 440, Train Loss: 0.987, Val f1_micro: 0.263
Epoch: 460, Train Loss: 0.989, Val f1_micro: 0.269
Epoch: 480, Train Loss: 0.978, Val f1_micro: 0.256
Epoch: 500, Train Loss: 0.950, Val f1_micro: 0.263
f1-micro: 0.263, f1-macro: 0.253, f1-weighted: 0.256, , roc-auc: 0.645
##### RUN 4 #####
Epoch: 020, Train Loss: 2.041, Val f1_micro: 0.145
Epoch: 040, Train Loss: 1.958, Val f1_micro: 0.167
Epoch: 060, Train Loss: 1.873, Val f1_micro: 0.130
Epoch: 080, Train Loss: 1.805, Val f1_micro: 0.169
Epoch: 100, Train Loss: 1.681, Val f1_micro: 0.194
Epoch: 120, Train Loss: 1.601, Val f1_micro: 0.198
Epoch: 140, Train Loss: 1.529, Val f1_micro: 0.212
Epoch: 160, Train Loss: 1.451, Val f1_micro: 0.225
Epoch: 180, Train Loss: 1.376, Val f1_micro: 0.224
Epoch: 200, Train Loss: 1.353, Val f1_micro: 0.219
Epoch: 220, Train Loss: 1.297, Val f1_micro: 0.241
Epoch: 240, Train Loss: 1.234, Val f1_micro: 0.238
Epoch: 260, Train Loss: 1.204, Val f1_micro: 0.243
Epoch: 280, Train Loss: 1.191, Val f1_micro: 0.246
Epoch: 300, Train Loss: 1.199, Val f1_micro: 0.256
Epoch: 320, Train Loss: 1.138, Val f1_micro: 0.241
Epoch: 340, Train Loss: 1.114, Val f1_micro: 0.254
Epoch: 360, Train Loss: 1.080, Val f1_micro: 0.243
Epoch: 380, Train Loss: 1.106, Val f1_micro: 0.249
Epoch: 400, Train Loss: 1.006, Val f1_micro: 0.243
Epoch: 420, Train Loss: 1.042, Val f1_micro: 0.261
Epoch: 440, Train Loss: 1.018, Val f1_micro: 0.256
Epoch: 460, Train Loss: 0.985, Val f1_micro: 0.264
Epoch: 480, Train Loss: 0.994, Val f1_micro: 0.265
Epoch: 500, Train Loss: 0.966, Val f1_micro: 0.269
f1-micro: 0.269, f1-macro: 0.263, f1-weighted: 0.266, , roc-auc: 0.649
##### RUN 5 #####
Epoch: 020, Train Loss: 2.038, Val f1_micro: 0.103
Epoch: 040, Train Loss: 1.959, Val f1_micro: 0.169
Epoch: 060, Train Loss: 1.902, Val f1_micro: 0.129
Epoch: 080, Train Loss: 1.839, Val f1_micro: 0.134
Epoch: 100, Train Loss: 1.768, Val f1_micro: 0.185
Epoch: 120, Train Loss: 1.706, Val f1_micro: 0.189
Epoch: 140, Train Loss: 1.623, Val f1_micro: 0.203
Epoch: 160, Train Loss: 1.554, Val f1_micro: 0.205
Epoch: 180, Train Loss: 1.507, Val f1_micro: 0.209
Epoch: 200, Train Loss: 1.480, Val f1_micro: 0.221
Epoch: 220, Train Loss: 1.435, Val f1_micro: 0.222
Epoch: 240, Train Loss: 1.403, Val f1_micro: 0.218
Epoch: 260, Train Loss: 1.342, Val f1_micro: 0.215
Epoch: 280, Train Loss: 1.277, Val f1_micro: 0.239
Epoch: 300, Train Loss: 1.302, Val f1_micro: 0.229
Epoch: 320, Train Loss: 1.231, Val f1_micro: 0.245
Epoch: 340, Train Loss: 1.205, Val f1_micro: 0.244
Epoch: 360, Train Loss: 1.185, Val f1_micro: 0.242
Epoch: 380, Train Loss: 1.108, Val f1_micro: 0.252
Epoch: 400, Train Loss: 1.076, Val f1_micro: 0.261
Epoch: 420, Train Loss: 1.069, Val f1_micro: 0.249
Epoch: 440, Train Loss: 1.056, Val f1_micro: 0.254
Epoch: 460, Train Loss: 1.032, Val f1_micro: 0.257
Epoch: 480, Train Loss: 1.027, Val f1_micro: 0.262
Epoch: 500, Train Loss: 1.032, Val f1_micro: 0.269
f1-micro: 0.269, f1-macro: 0.263, f1-weighted: 0.267, , roc-auc: 0.645
########## Hyperparameters combination ##########
(512, 0.5, 0.05, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.049, Val f1_micro: 0.100
Epoch: 040, Train Loss: 1.991, Val f1_micro: 0.161
Epoch: 060, Train Loss: 1.944, Val f1_micro: 0.119
Epoch: 080, Train Loss: 1.894, Val f1_micro: 0.157
Epoch: 100, Train Loss: 1.839, Val f1_micro: 0.178
Epoch: 120, Train Loss: 1.792, Val f1_micro: 0.182
Epoch: 140, Train Loss: 1.696, Val f1_micro: 0.191
Epoch: 160, Train Loss: 1.632, Val f1_micro: 0.191
Epoch: 180, Train Loss: 1.608, Val f1_micro: 0.196
Epoch: 200, Train Loss: 1.557, Val f1_micro: 0.208
Epoch: 220, Train Loss: 1.546, Val f1_micro: 0.213
Epoch: 240, Train Loss: 1.522, Val f1_micro: 0.213
Epoch: 260, Train Loss: 1.484, Val f1_micro: 0.220
Epoch: 280, Train Loss: 1.482, Val f1_micro: 0.222
Epoch: 300, Train Loss: 1.436, Val f1_micro: 0.221
Epoch: 320, Train Loss: 1.421, Val f1_micro: 0.214
Epoch: 340, Train Loss: 1.408, Val f1_micro: 0.227
Epoch: 360, Train Loss: 1.403, Val f1_micro: 0.229
Epoch: 380, Train Loss: 1.350, Val f1_micro: 0.235
Epoch: 400, Train Loss: 1.381, Val f1_micro: 0.221
Epoch: 420, Train Loss: 1.338, Val f1_micro: 0.230
Epoch: 440, Train Loss: 1.394, Val f1_micro: 0.223
Epoch: 460, Train Loss: 1.316, Val f1_micro: 0.236
Epoch: 480, Train Loss: 1.314, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.300, Val f1_micro: 0.245
f1-micro: 0.245, f1-macro: 0.228, f1-weighted: 0.228, , roc-auc: 0.642
##### RUN 2 #####
Epoch: 020, Train Loss: 2.045, Val f1_micro: 0.102
Epoch: 040, Train Loss: 1.975, Val f1_micro: 0.167
Epoch: 060, Train Loss: 1.921, Val f1_micro: 0.125
Epoch: 080, Train Loss: 1.885, Val f1_micro: 0.130
Epoch: 100, Train Loss: 1.791, Val f1_micro: 0.173
Epoch: 120, Train Loss: 1.732, Val f1_micro: 0.195
Epoch: 140, Train Loss: 1.653, Val f1_micro: 0.198
Epoch: 160, Train Loss: 1.589, Val f1_micro: 0.211
Epoch: 180, Train Loss: 1.541, Val f1_micro: 0.209
Epoch: 200, Train Loss: 1.513, Val f1_micro: 0.215
Epoch: 220, Train Loss: 1.495, Val f1_micro: 0.224
Epoch: 240, Train Loss: 1.450, Val f1_micro: 0.233
Epoch: 260, Train Loss: 1.418, Val f1_micro: 0.242
Epoch: 280, Train Loss: 1.353, Val f1_micro: 0.235
Epoch: 300, Train Loss: 1.345, Val f1_micro: 0.242
Epoch: 320, Train Loss: 1.349, Val f1_micro: 0.230
Epoch: 340, Train Loss: 1.327, Val f1_micro: 0.248
Epoch: 360, Train Loss: 1.287, Val f1_micro: 0.255
Epoch: 380, Train Loss: 1.297, Val f1_micro: 0.232
Epoch: 400, Train Loss: 1.282, Val f1_micro: 0.254
Epoch: 420, Train Loss: 1.276, Val f1_micro: 0.248
Epoch: 440, Train Loss: 1.255, Val f1_micro: 0.252
Epoch: 460, Train Loss: 1.233, Val f1_micro: 0.253
Epoch: 480, Train Loss: 1.280, Val f1_micro: 0.222
Epoch: 500, Train Loss: 1.242, Val f1_micro: 0.247
f1-micro: 0.247, f1-macro: 0.231, f1-weighted: 0.234, , roc-auc: 0.645
##### RUN 3 #####
Epoch: 020, Train Loss: 2.057, Val f1_micro: 0.148
Epoch: 040, Train Loss: 1.992, Val f1_micro: 0.163
Epoch: 060, Train Loss: 1.957, Val f1_micro: 0.117
Epoch: 080, Train Loss: 1.927, Val f1_micro: 0.123
Epoch: 100, Train Loss: 1.869, Val f1_micro: 0.148
Epoch: 120, Train Loss: 1.761, Val f1_micro: 0.185
Epoch: 140, Train Loss: 1.728, Val f1_micro: 0.191
Epoch: 160, Train Loss: 1.671, Val f1_micro: 0.201
Epoch: 180, Train Loss: 1.615, Val f1_micro: 0.188
Epoch: 200, Train Loss: 1.575, Val f1_micro: 0.210
Epoch: 220, Train Loss: 1.575, Val f1_micro: 0.198
Epoch: 240, Train Loss: 1.543, Val f1_micro: 0.213
Epoch: 260, Train Loss: 1.497, Val f1_micro: 0.224
Epoch: 280, Train Loss: 1.476, Val f1_micro: 0.213
Epoch: 300, Train Loss: 1.496, Val f1_micro: 0.210
Epoch: 320, Train Loss: 1.452, Val f1_micro: 0.224
Epoch: 340, Train Loss: 1.412, Val f1_micro: 0.228
Epoch: 360, Train Loss: 1.377, Val f1_micro: 0.223
Epoch: 380, Train Loss: 1.349, Val f1_micro: 0.230
Epoch: 400, Train Loss: 1.383, Val f1_micro: 0.218
Epoch: 420, Train Loss: 1.367, Val f1_micro: 0.232
Epoch: 440, Train Loss: 1.328, Val f1_micro: 0.232
Epoch: 460, Train Loss: 1.351, Val f1_micro: 0.238
Epoch: 480, Train Loss: 1.321, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.315, Val f1_micro: 0.237
f1-micro: 0.237, f1-macro: 0.215, f1-weighted: 0.214, , roc-auc: 0.644
##### RUN 4 #####
Epoch: 020, Train Loss: 2.047, Val f1_micro: 0.098
Epoch: 040, Train Loss: 1.965, Val f1_micro: 0.168
Epoch: 060, Train Loss: 1.913, Val f1_micro: 0.127
Epoch: 080, Train Loss: 1.851, Val f1_micro: 0.168
Epoch: 100, Train Loss: 1.799, Val f1_micro: 0.171
Epoch: 120, Train Loss: 1.723, Val f1_micro: 0.176
Epoch: 140, Train Loss: 1.656, Val f1_micro: 0.202
Epoch: 160, Train Loss: 1.613, Val f1_micro: 0.201
Epoch: 180, Train Loss: 1.544, Val f1_micro: 0.215
Epoch: 200, Train Loss: 1.507, Val f1_micro: 0.209
Epoch: 220, Train Loss: 1.496, Val f1_micro: 0.215
Epoch: 240, Train Loss: 1.473, Val f1_micro: 0.218
Epoch: 260, Train Loss: 1.434, Val f1_micro: 0.221
Epoch: 280, Train Loss: 1.408, Val f1_micro: 0.232
Epoch: 300, Train Loss: 1.374, Val f1_micro: 0.226
Epoch: 320, Train Loss: 1.348, Val f1_micro: 0.229
Epoch: 340, Train Loss: 1.329, Val f1_micro: 0.234
Epoch: 360, Train Loss: 1.347, Val f1_micro: 0.233
Epoch: 380, Train Loss: 1.287, Val f1_micro: 0.242
Epoch: 400, Train Loss: 1.279, Val f1_micro: 0.244
Epoch: 420, Train Loss: 1.276, Val f1_micro: 0.236
Epoch: 440, Train Loss: 1.283, Val f1_micro: 0.241
Epoch: 460, Train Loss: 1.289, Val f1_micro: 0.241
Epoch: 480, Train Loss: 1.258, Val f1_micro: 0.246
Epoch: 500, Train Loss: 1.254, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.214, f1-weighted: 0.215, , roc-auc: 0.640
##### RUN 5 #####
Epoch: 020, Train Loss: 2.059, Val f1_micro: 0.145
Epoch: 040, Train Loss: 1.989, Val f1_micro: 0.165
Epoch: 060, Train Loss: 1.913, Val f1_micro: 0.130
Epoch: 080, Train Loss: 1.874, Val f1_micro: 0.147
Epoch: 100, Train Loss: 1.803, Val f1_micro: 0.168
Epoch: 120, Train Loss: 1.759, Val f1_micro: 0.196
Epoch: 140, Train Loss: 1.694, Val f1_micro: 0.188
Epoch: 160, Train Loss: 1.632, Val f1_micro: 0.213
Epoch: 180, Train Loss: 1.536, Val f1_micro: 0.207
Epoch: 200, Train Loss: 1.539, Val f1_micro: 0.216
Epoch: 220, Train Loss: 1.494, Val f1_micro: 0.220
Epoch: 240, Train Loss: 1.449, Val f1_micro: 0.225
Epoch: 260, Train Loss: 1.425, Val f1_micro: 0.224
Epoch: 280, Train Loss: 1.404, Val f1_micro: 0.239
Epoch: 300, Train Loss: 1.376, Val f1_micro: 0.231
Epoch: 320, Train Loss: 1.350, Val f1_micro: 0.235
Epoch: 340, Train Loss: 1.333, Val f1_micro: 0.240
Epoch: 360, Train Loss: 1.320, Val f1_micro: 0.238
Epoch: 380, Train Loss: 1.286, Val f1_micro: 0.235
Epoch: 400, Train Loss: 1.246, Val f1_micro: 0.236
Epoch: 420, Train Loss: 1.297, Val f1_micro: 0.235
Epoch: 440, Train Loss: 1.276, Val f1_micro: 0.246
Epoch: 460, Train Loss: 1.249, Val f1_micro: 0.250
Epoch: 480, Train Loss: 1.293, Val f1_micro: 0.236
Epoch: 500, Train Loss: 1.221, Val f1_micro: 0.253
f1-micro: 0.253, f1-macro: 0.242, f1-weighted: 0.245, , roc-auc: 0.643
########## Hyperparameters combination ##########
(512, 0.5, 0.05, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.061, Val f1_micro: 0.097
Epoch: 040, Train Loss: 2.027, Val f1_micro: 0.158
Epoch: 060, Train Loss: 1.981, Val f1_micro: 0.154
Epoch: 080, Train Loss: 1.956, Val f1_micro: 0.172
Epoch: 100, Train Loss: 1.894, Val f1_micro: 0.183
Epoch: 120, Train Loss: 1.876, Val f1_micro: 0.184
Epoch: 140, Train Loss: 1.865, Val f1_micro: 0.182
Epoch: 160, Train Loss: 1.863, Val f1_micro: 0.186
Epoch: 180, Train Loss: 1.842, Val f1_micro: 0.181
Epoch: 200, Train Loss: 1.839, Val f1_micro: 0.185
Epoch: 220, Train Loss: 1.837, Val f1_micro: 0.211
Epoch: 240, Train Loss: 1.839, Val f1_micro: 0.188
Epoch: 260, Train Loss: 1.820, Val f1_micro: 0.205
Epoch: 280, Train Loss: 1.802, Val f1_micro: 0.201
Epoch: 300, Train Loss: 1.835, Val f1_micro: 0.182
Epoch: 320, Train Loss: 1.836, Val f1_micro: 0.199
Epoch: 340, Train Loss: 1.831, Val f1_micro: 0.196
Epoch: 360, Train Loss: 1.826, Val f1_micro: 0.199
Epoch: 380, Train Loss: 1.816, Val f1_micro: 0.201
Epoch: 400, Train Loss: 1.805, Val f1_micro: 0.201
Epoch: 420, Train Loss: 1.814, Val f1_micro: 0.212
Epoch: 440, Train Loss: 1.803, Val f1_micro: 0.199
Epoch: 460, Train Loss: 1.805, Val f1_micro: 0.184
Epoch: 480, Train Loss: 1.801, Val f1_micro: 0.200
Epoch: 500, Train Loss: 1.800, Val f1_micro: 0.211
f1-micro: 0.211, f1-macro: 0.166, f1-weighted: 0.168, , roc-auc: 0.621
##### RUN 2 #####
Epoch: 020, Train Loss: 2.064, Val f1_micro: 0.141
Epoch: 040, Train Loss: 2.028, Val f1_micro: 0.155
Epoch: 060, Train Loss: 1.985, Val f1_micro: 0.179
Epoch: 080, Train Loss: 1.936, Val f1_micro: 0.177
Epoch: 100, Train Loss: 1.913, Val f1_micro: 0.174
Epoch: 120, Train Loss: 1.896, Val f1_micro: 0.177
Epoch: 140, Train Loss: 1.863, Val f1_micro: 0.182
Epoch: 160, Train Loss: 1.847, Val f1_micro: 0.193
Epoch: 180, Train Loss: 1.855, Val f1_micro: 0.200
Epoch: 200, Train Loss: 1.854, Val f1_micro: 0.183
Epoch: 220, Train Loss: 1.850, Val f1_micro: 0.193
Epoch: 240, Train Loss: 1.834, Val f1_micro: 0.184
Epoch: 260, Train Loss: 1.835, Val f1_micro: 0.190
Epoch: 280, Train Loss: 1.820, Val f1_micro: 0.198
Epoch: 300, Train Loss: 1.827, Val f1_micro: 0.189
Epoch: 320, Train Loss: 1.828, Val f1_micro: 0.225
Epoch: 340, Train Loss: 1.818, Val f1_micro: 0.193
Epoch: 360, Train Loss: 1.822, Val f1_micro: 0.194
Epoch: 380, Train Loss: 1.807, Val f1_micro: 0.193
Epoch: 400, Train Loss: 1.830, Val f1_micro: 0.194
Epoch: 420, Train Loss: 1.802, Val f1_micro: 0.202
Epoch: 440, Train Loss: 1.807, Val f1_micro: 0.197
Epoch: 460, Train Loss: 1.797, Val f1_micro: 0.210
Epoch: 480, Train Loss: 1.795, Val f1_micro: 0.218
Epoch: 500, Train Loss: 1.806, Val f1_micro: 0.209
f1-micro: 0.209, f1-macro: 0.159, f1-weighted: 0.162, , roc-auc: 0.625
##### RUN 3 #####
Epoch: 020, Train Loss: 2.069, Val f1_micro: 0.141
Epoch: 040, Train Loss: 2.028, Val f1_micro: 0.158
Epoch: 060, Train Loss: 2.012, Val f1_micro: 0.159
Epoch: 080, Train Loss: 1.974, Val f1_micro: 0.165
Epoch: 100, Train Loss: 1.948, Val f1_micro: 0.167
Epoch: 120, Train Loss: 1.899, Val f1_micro: 0.168
Epoch: 140, Train Loss: 1.889, Val f1_micro: 0.178
Epoch: 160, Train Loss: 1.854, Val f1_micro: 0.186
Epoch: 180, Train Loss: 1.852, Val f1_micro: 0.194
Epoch: 200, Train Loss: 1.849, Val f1_micro: 0.186
Epoch: 220, Train Loss: 1.831, Val f1_micro: 0.202
Epoch: 240, Train Loss: 1.824, Val f1_micro: 0.180
Epoch: 260, Train Loss: 1.824, Val f1_micro: 0.195
Epoch: 280, Train Loss: 1.816, Val f1_micro: 0.198
Epoch: 300, Train Loss: 1.820, Val f1_micro: 0.193
Epoch: 320, Train Loss: 1.820, Val f1_micro: 0.199
Epoch: 340, Train Loss: 1.821, Val f1_micro: 0.191
Epoch: 360, Train Loss: 1.826, Val f1_micro: 0.193
Epoch: 380, Train Loss: 1.825, Val f1_micro: 0.209
Epoch: 400, Train Loss: 1.811, Val f1_micro: 0.199
Epoch: 420, Train Loss: 1.809, Val f1_micro: 0.200
Epoch: 440, Train Loss: 1.814, Val f1_micro: 0.200
Epoch: 460, Train Loss: 1.814, Val f1_micro: 0.189
Epoch: 480, Train Loss: 1.805, Val f1_micro: 0.206
Epoch: 500, Train Loss: 1.801, Val f1_micro: 0.198
f1-micro: 0.198, f1-macro: 0.159, f1-weighted: 0.160, , roc-auc: 0.625
##### RUN 4 #####
Epoch: 020, Train Loss: 2.063, Val f1_micro: 0.098
Epoch: 040, Train Loss: 2.031, Val f1_micro: 0.159
Epoch: 060, Train Loss: 2.000, Val f1_micro: 0.158
Epoch: 080, Train Loss: 1.951, Val f1_micro: 0.171
Epoch: 100, Train Loss: 1.933, Val f1_micro: 0.180
Epoch: 120, Train Loss: 1.902, Val f1_micro: 0.195
Epoch: 140, Train Loss: 1.873, Val f1_micro: 0.197
Epoch: 160, Train Loss: 1.864, Val f1_micro: 0.199
Epoch: 180, Train Loss: 1.858, Val f1_micro: 0.186
Epoch: 200, Train Loss: 1.838, Val f1_micro: 0.198
Epoch: 220, Train Loss: 1.831, Val f1_micro: 0.195
Epoch: 240, Train Loss: 1.837, Val f1_micro: 0.192
Epoch: 260, Train Loss: 1.830, Val f1_micro: 0.192
Epoch: 280, Train Loss: 1.836, Val f1_micro: 0.198
Epoch: 300, Train Loss: 1.842, Val f1_micro: 0.180
Epoch: 320, Train Loss: 1.816, Val f1_micro: 0.198
Epoch: 340, Train Loss: 1.821, Val f1_micro: 0.200
Epoch: 360, Train Loss: 1.824, Val f1_micro: 0.193
Epoch: 380, Train Loss: 1.823, Val f1_micro: 0.187
Epoch: 400, Train Loss: 1.824, Val f1_micro: 0.206
Epoch: 420, Train Loss: 1.828, Val f1_micro: 0.196
Epoch: 440, Train Loss: 1.810, Val f1_micro: 0.201
Epoch: 460, Train Loss: 1.818, Val f1_micro: 0.202
Epoch: 480, Train Loss: 1.825, Val f1_micro: 0.202
Epoch: 500, Train Loss: 1.823, Val f1_micro: 0.187
f1-micro: 0.187, f1-macro: 0.153, f1-weighted: 0.153, , roc-auc: 0.619
##### RUN 5 #####
Epoch: 020, Train Loss: 2.073, Val f1_micro: 0.140
Epoch: 040, Train Loss: 2.027, Val f1_micro: 0.156
Epoch: 060, Train Loss: 2.008, Val f1_micro: 0.129
Epoch: 080, Train Loss: 1.964, Val f1_micro: 0.173
Epoch: 100, Train Loss: 1.927, Val f1_micro: 0.174
Epoch: 120, Train Loss: 1.897, Val f1_micro: 0.181
Epoch: 140, Train Loss: 1.877, Val f1_micro: 0.170
Epoch: 160, Train Loss: 1.853, Val f1_micro: 0.181
Epoch: 180, Train Loss: 1.840, Val f1_micro: 0.195
Epoch: 200, Train Loss: 1.841, Val f1_micro: 0.188
Epoch: 220, Train Loss: 1.824, Val f1_micro: 0.191
Epoch: 240, Train Loss: 1.837, Val f1_micro: 0.194
Epoch: 260, Train Loss: 1.825, Val f1_micro: 0.197
Epoch: 280, Train Loss: 1.816, Val f1_micro: 0.194
Epoch: 300, Train Loss: 1.815, Val f1_micro: 0.193
Epoch: 320, Train Loss: 1.821, Val f1_micro: 0.205
Epoch: 340, Train Loss: 1.814, Val f1_micro: 0.195
Epoch: 360, Train Loss: 1.834, Val f1_micro: 0.181
Epoch: 380, Train Loss: 1.838, Val f1_micro: 0.196
Epoch: 400, Train Loss: 1.814, Val f1_micro: 0.191
Epoch: 420, Train Loss: 1.804, Val f1_micro: 0.220
Epoch: 440, Train Loss: 1.818, Val f1_micro: 0.201
Epoch: 460, Train Loss: 1.811, Val f1_micro: 0.169
Epoch: 480, Train Loss: 1.813, Val f1_micro: 0.200
Epoch: 500, Train Loss: 1.818, Val f1_micro: 0.196
f1-micro: 0.196, f1-macro: 0.156, f1-weighted: 0.155, , roc-auc: 0.619
########## Hyperparameters combination ##########
(512, 0.6, 0.001, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.376, Val f1_micro: 0.191
Epoch: 040, Train Loss: 2.037, Val f1_micro: 0.203
Epoch: 060, Train Loss: 1.906, Val f1_micro: 0.212
Epoch: 080, Train Loss: 1.807, Val f1_micro: 0.215
Epoch: 100, Train Loss: 1.709, Val f1_micro: 0.225
Epoch: 120, Train Loss: 1.681, Val f1_micro: 0.228
Epoch: 140, Train Loss: 1.602, Val f1_micro: 0.233
Epoch: 160, Train Loss: 1.533, Val f1_micro: 0.239
Epoch: 180, Train Loss: 1.516, Val f1_micro: 0.241
Epoch: 200, Train Loss: 1.457, Val f1_micro: 0.239
Epoch: 220, Train Loss: 1.438, Val f1_micro: 0.247
Epoch: 240, Train Loss: 1.400, Val f1_micro: 0.248
Epoch: 260, Train Loss: 1.377, Val f1_micro: 0.249
Epoch: 280, Train Loss: 1.369, Val f1_micro: 0.251
Epoch: 300, Train Loss: 1.322, Val f1_micro: 0.251
Epoch: 320, Train Loss: 1.291, Val f1_micro: 0.258
Epoch: 340, Train Loss: 1.273, Val f1_micro: 0.257
Epoch: 360, Train Loss: 1.260, Val f1_micro: 0.261
Epoch: 380, Train Loss: 1.236, Val f1_micro: 0.261
Epoch: 400, Train Loss: 1.207, Val f1_micro: 0.257
Epoch: 420, Train Loss: 1.178, Val f1_micro: 0.264
Epoch: 440, Train Loss: 1.187, Val f1_micro: 0.263
Epoch: 460, Train Loss: 1.122, Val f1_micro: 0.265
Epoch: 480, Train Loss: 1.120, Val f1_micro: 0.264
Epoch: 500, Train Loss: 1.109, Val f1_micro: 0.265
f1-micro: 0.265, f1-macro: 0.257, f1-weighted: 0.260, , roc-auc: 0.664
##### RUN 2 #####
Epoch: 020, Train Loss: 2.359, Val f1_micro: 0.187
Epoch: 040, Train Loss: 2.071, Val f1_micro: 0.203
Epoch: 060, Train Loss: 1.927, Val f1_micro: 0.205
Epoch: 080, Train Loss: 1.822, Val f1_micro: 0.218
Epoch: 100, Train Loss: 1.742, Val f1_micro: 0.226
Epoch: 120, Train Loss: 1.651, Val f1_micro: 0.235
Epoch: 140, Train Loss: 1.604, Val f1_micro: 0.232
Epoch: 160, Train Loss: 1.554, Val f1_micro: 0.238
Epoch: 180, Train Loss: 1.507, Val f1_micro: 0.240
Epoch: 200, Train Loss: 1.473, Val f1_micro: 0.243
Epoch: 220, Train Loss: 1.437, Val f1_micro: 0.251
Epoch: 240, Train Loss: 1.401, Val f1_micro: 0.249
Epoch: 260, Train Loss: 1.377, Val f1_micro: 0.249
Epoch: 280, Train Loss: 1.356, Val f1_micro: 0.254
Epoch: 300, Train Loss: 1.321, Val f1_micro: 0.249
Epoch: 320, Train Loss: 1.284, Val f1_micro: 0.256
Epoch: 340, Train Loss: 1.263, Val f1_micro: 0.259
Epoch: 360, Train Loss: 1.238, Val f1_micro: 0.260
Epoch: 380, Train Loss: 1.229, Val f1_micro: 0.261
Epoch: 400, Train Loss: 1.217, Val f1_micro: 0.262
Epoch: 420, Train Loss: 1.185, Val f1_micro: 0.265
Epoch: 440, Train Loss: 1.160, Val f1_micro: 0.264
Epoch: 460, Train Loss: 1.144, Val f1_micro: 0.263
Epoch: 480, Train Loss: 1.127, Val f1_micro: 0.264
Epoch: 500, Train Loss: 1.105, Val f1_micro: 0.264
f1-micro: 0.264, f1-macro: 0.255, f1-weighted: 0.258, , roc-auc: 0.665
##### RUN 3 #####
Epoch: 020, Train Loss: 2.397, Val f1_micro: 0.191
Epoch: 040, Train Loss: 2.061, Val f1_micro: 0.203
Epoch: 060, Train Loss: 1.909, Val f1_micro: 0.215
Epoch: 080, Train Loss: 1.812, Val f1_micro: 0.215
Epoch: 100, Train Loss: 1.724, Val f1_micro: 0.222
Epoch: 120, Train Loss: 1.662, Val f1_micro: 0.231
Epoch: 140, Train Loss: 1.600, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.562, Val f1_micro: 0.238
Epoch: 180, Train Loss: 1.488, Val f1_micro: 0.243
Epoch: 200, Train Loss: 1.493, Val f1_micro: 0.246
Epoch: 220, Train Loss: 1.435, Val f1_micro: 0.245
Epoch: 240, Train Loss: 1.405, Val f1_micro: 0.250
Epoch: 260, Train Loss: 1.377, Val f1_micro: 0.253
Epoch: 280, Train Loss: 1.347, Val f1_micro: 0.250
Epoch: 300, Train Loss: 1.305, Val f1_micro: 0.255
Epoch: 320, Train Loss: 1.310, Val f1_micro: 0.261
Epoch: 340, Train Loss: 1.270, Val f1_micro: 0.262
Epoch: 360, Train Loss: 1.227, Val f1_micro: 0.258
Epoch: 380, Train Loss: 1.217, Val f1_micro: 0.261
Epoch: 400, Train Loss: 1.225, Val f1_micro: 0.264
Epoch: 420, Train Loss: 1.186, Val f1_micro: 0.264
Epoch: 440, Train Loss: 1.166, Val f1_micro: 0.259
Epoch: 460, Train Loss: 1.165, Val f1_micro: 0.266
Epoch: 480, Train Loss: 1.133, Val f1_micro: 0.266
Epoch: 500, Train Loss: 1.108, Val f1_micro: 0.266
f1-micro: 0.266, f1-macro: 0.256, f1-weighted: 0.258, , roc-auc: 0.665
##### RUN 4 #####
Epoch: 020, Train Loss: 2.390, Val f1_micro: 0.193
Epoch: 040, Train Loss: 2.027, Val f1_micro: 0.205
Epoch: 060, Train Loss: 1.923, Val f1_micro: 0.214
Epoch: 080, Train Loss: 1.821, Val f1_micro: 0.218
Epoch: 100, Train Loss: 1.724, Val f1_micro: 0.226
Epoch: 120, Train Loss: 1.653, Val f1_micro: 0.229
Epoch: 140, Train Loss: 1.606, Val f1_micro: 0.233
Epoch: 160, Train Loss: 1.565, Val f1_micro: 0.243
Epoch: 180, Train Loss: 1.528, Val f1_micro: 0.237
Epoch: 200, Train Loss: 1.476, Val f1_micro: 0.245
Epoch: 220, Train Loss: 1.428, Val f1_micro: 0.244
Epoch: 240, Train Loss: 1.416, Val f1_micro: 0.248
Epoch: 260, Train Loss: 1.366, Val f1_micro: 0.249
Epoch: 280, Train Loss: 1.364, Val f1_micro: 0.252
Epoch: 300, Train Loss: 1.329, Val f1_micro: 0.255
Epoch: 320, Train Loss: 1.292, Val f1_micro: 0.258
Epoch: 340, Train Loss: 1.259, Val f1_micro: 0.260
Epoch: 360, Train Loss: 1.231, Val f1_micro: 0.258
Epoch: 380, Train Loss: 1.229, Val f1_micro: 0.260
Epoch: 400, Train Loss: 1.200, Val f1_micro: 0.261
Epoch: 420, Train Loss: 1.196, Val f1_micro: 0.263
Epoch: 440, Train Loss: 1.158, Val f1_micro: 0.262
Epoch: 460, Train Loss: 1.149, Val f1_micro: 0.268
Epoch: 480, Train Loss: 1.107, Val f1_micro: 0.264
Epoch: 500, Train Loss: 1.121, Val f1_micro: 0.265
f1-micro: 0.265, f1-macro: 0.257, f1-weighted: 0.260, , roc-auc: 0.665
##### RUN 5 #####
Epoch: 020, Train Loss: 2.351, Val f1_micro: 0.190
Epoch: 040, Train Loss: 2.068, Val f1_micro: 0.205
Epoch: 060, Train Loss: 1.925, Val f1_micro: 0.211
Epoch: 080, Train Loss: 1.814, Val f1_micro: 0.213
Epoch: 100, Train Loss: 1.717, Val f1_micro: 0.221
Epoch: 120, Train Loss: 1.655, Val f1_micro: 0.233
Epoch: 140, Train Loss: 1.604, Val f1_micro: 0.228
Epoch: 160, Train Loss: 1.547, Val f1_micro: 0.237
Epoch: 180, Train Loss: 1.510, Val f1_micro: 0.242
Epoch: 200, Train Loss: 1.498, Val f1_micro: 0.242
Epoch: 220, Train Loss: 1.437, Val f1_micro: 0.246
Epoch: 240, Train Loss: 1.396, Val f1_micro: 0.249
Epoch: 260, Train Loss: 1.368, Val f1_micro: 0.250
Epoch: 280, Train Loss: 1.346, Val f1_micro: 0.255
Epoch: 300, Train Loss: 1.323, Val f1_micro: 0.254
Epoch: 320, Train Loss: 1.302, Val f1_micro: 0.255
Epoch: 340, Train Loss: 1.286, Val f1_micro: 0.257
Epoch: 360, Train Loss: 1.237, Val f1_micro: 0.261
Epoch: 380, Train Loss: 1.240, Val f1_micro: 0.259
Epoch: 400, Train Loss: 1.198, Val f1_micro: 0.261
Epoch: 420, Train Loss: 1.173, Val f1_micro: 0.262
Epoch: 440, Train Loss: 1.151, Val f1_micro: 0.261
Epoch: 460, Train Loss: 1.161, Val f1_micro: 0.265
Epoch: 480, Train Loss: 1.141, Val f1_micro: 0.265
Epoch: 500, Train Loss: 1.120, Val f1_micro: 0.265
f1-micro: 0.265, f1-macro: 0.256, f1-weighted: 0.259, , roc-auc: 0.665
########## Hyperparameters combination ##########
(512, 0.6, 0.001, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.387, Val f1_micro: 0.194
Epoch: 040, Train Loss: 2.052, Val f1_micro: 0.206
Epoch: 060, Train Loss: 1.925, Val f1_micro: 0.206
Epoch: 080, Train Loss: 1.826, Val f1_micro: 0.216
Epoch: 100, Train Loss: 1.750, Val f1_micro: 0.221
Epoch: 120, Train Loss: 1.671, Val f1_micro: 0.225
Epoch: 140, Train Loss: 1.613, Val f1_micro: 0.230
Epoch: 160, Train Loss: 1.585, Val f1_micro: 0.230
Epoch: 180, Train Loss: 1.554, Val f1_micro: 0.238
Epoch: 200, Train Loss: 1.508, Val f1_micro: 0.237
Epoch: 220, Train Loss: 1.478, Val f1_micro: 0.243
Epoch: 240, Train Loss: 1.462, Val f1_micro: 0.244
Epoch: 260, Train Loss: 1.418, Val f1_micro: 0.242
Epoch: 280, Train Loss: 1.378, Val f1_micro: 0.248
Epoch: 300, Train Loss: 1.365, Val f1_micro: 0.246
Epoch: 320, Train Loss: 1.355, Val f1_micro: 0.249
Epoch: 340, Train Loss: 1.314, Val f1_micro: 0.254
Epoch: 360, Train Loss: 1.281, Val f1_micro: 0.257
Epoch: 380, Train Loss: 1.284, Val f1_micro: 0.255
Epoch: 400, Train Loss: 1.284, Val f1_micro: 0.257
Epoch: 420, Train Loss: 1.269, Val f1_micro: 0.255
Epoch: 440, Train Loss: 1.235, Val f1_micro: 0.263
Epoch: 460, Train Loss: 1.234, Val f1_micro: 0.262
Epoch: 480, Train Loss: 1.206, Val f1_micro: 0.263
Epoch: 500, Train Loss: 1.190, Val f1_micro: 0.266
f1-micro: 0.266, f1-macro: 0.253, f1-weighted: 0.256, , roc-auc: 0.668
##### RUN 2 #####
Epoch: 020, Train Loss: 2.361, Val f1_micro: 0.194
Epoch: 040, Train Loss: 2.085, Val f1_micro: 0.207
Epoch: 060, Train Loss: 1.924, Val f1_micro: 0.206
Epoch: 080, Train Loss: 1.823, Val f1_micro: 0.212
Epoch: 100, Train Loss: 1.731, Val f1_micro: 0.224
Epoch: 120, Train Loss: 1.679, Val f1_micro: 0.224
Epoch: 140, Train Loss: 1.611, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.579, Val f1_micro: 0.235
Epoch: 180, Train Loss: 1.519, Val f1_micro: 0.237
Epoch: 200, Train Loss: 1.511, Val f1_micro: 0.238
Epoch: 220, Train Loss: 1.471, Val f1_micro: 0.240
Epoch: 240, Train Loss: 1.428, Val f1_micro: 0.242
Epoch: 260, Train Loss: 1.426, Val f1_micro: 0.245
Epoch: 280, Train Loss: 1.401, Val f1_micro: 0.249
Epoch: 300, Train Loss: 1.377, Val f1_micro: 0.249
Epoch: 320, Train Loss: 1.342, Val f1_micro: 0.253
Epoch: 340, Train Loss: 1.318, Val f1_micro: 0.249
Epoch: 360, Train Loss: 1.306, Val f1_micro: 0.251
Epoch: 380, Train Loss: 1.296, Val f1_micro: 0.257
Epoch: 400, Train Loss: 1.289, Val f1_micro: 0.259
Epoch: 420, Train Loss: 1.263, Val f1_micro: 0.257
Epoch: 440, Train Loss: 1.263, Val f1_micro: 0.258
Epoch: 460, Train Loss: 1.223, Val f1_micro: 0.263
Epoch: 480, Train Loss: 1.205, Val f1_micro: 0.262
Epoch: 500, Train Loss: 1.195, Val f1_micro: 0.259
f1-micro: 0.259, f1-macro: 0.248, f1-weighted: 0.250, , roc-auc: 0.666
##### RUN 3 #####
Epoch: 020, Train Loss: 2.348, Val f1_micro: 0.196
Epoch: 040, Train Loss: 2.090, Val f1_micro: 0.201
Epoch: 060, Train Loss: 1.909, Val f1_micro: 0.207
Epoch: 080, Train Loss: 1.819, Val f1_micro: 0.213
Epoch: 100, Train Loss: 1.749, Val f1_micro: 0.224
Epoch: 120, Train Loss: 1.678, Val f1_micro: 0.228
Epoch: 140, Train Loss: 1.630, Val f1_micro: 0.229
Epoch: 160, Train Loss: 1.566, Val f1_micro: 0.233
Epoch: 180, Train Loss: 1.525, Val f1_micro: 0.234
Epoch: 200, Train Loss: 1.488, Val f1_micro: 0.240
Epoch: 220, Train Loss: 1.471, Val f1_micro: 0.237
Epoch: 240, Train Loss: 1.461, Val f1_micro: 0.249
Epoch: 260, Train Loss: 1.403, Val f1_micro: 0.245
Epoch: 280, Train Loss: 1.391, Val f1_micro: 0.245
Epoch: 300, Train Loss: 1.378, Val f1_micro: 0.249
Epoch: 320, Train Loss: 1.362, Val f1_micro: 0.249
Epoch: 340, Train Loss: 1.329, Val f1_micro: 0.252
Epoch: 360, Train Loss: 1.292, Val f1_micro: 0.254
Epoch: 380, Train Loss: 1.284, Val f1_micro: 0.255
Epoch: 400, Train Loss: 1.287, Val f1_micro: 0.256
Epoch: 420, Train Loss: 1.248, Val f1_micro: 0.259
Epoch: 440, Train Loss: 1.239, Val f1_micro: 0.261
Epoch: 460, Train Loss: 1.235, Val f1_micro: 0.263
Epoch: 480, Train Loss: 1.215, Val f1_micro: 0.263
Epoch: 500, Train Loss: 1.179, Val f1_micro: 0.262
f1-micro: 0.262, f1-macro: 0.250, f1-weighted: 0.252, , roc-auc: 0.667
##### RUN 4 #####
Epoch: 020, Train Loss: 2.378, Val f1_micro: 0.196
Epoch: 040, Train Loss: 2.093, Val f1_micro: 0.207
Epoch: 060, Train Loss: 1.891, Val f1_micro: 0.206
Epoch: 080, Train Loss: 1.806, Val f1_micro: 0.217
Epoch: 100, Train Loss: 1.747, Val f1_micro: 0.216
Epoch: 120, Train Loss: 1.677, Val f1_micro: 0.228
Epoch: 140, Train Loss: 1.631, Val f1_micro: 0.228
Epoch: 160, Train Loss: 1.581, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.548, Val f1_micro: 0.237
Epoch: 200, Train Loss: 1.497, Val f1_micro: 0.241
Epoch: 220, Train Loss: 1.486, Val f1_micro: 0.240
Epoch: 240, Train Loss: 1.461, Val f1_micro: 0.243
Epoch: 260, Train Loss: 1.428, Val f1_micro: 0.242
Epoch: 280, Train Loss: 1.402, Val f1_micro: 0.248
Epoch: 300, Train Loss: 1.368, Val f1_micro: 0.248
Epoch: 320, Train Loss: 1.354, Val f1_micro: 0.248
Epoch: 340, Train Loss: 1.325, Val f1_micro: 0.254
Epoch: 360, Train Loss: 1.291, Val f1_micro: 0.252
Epoch: 380, Train Loss: 1.282, Val f1_micro: 0.257
Epoch: 400, Train Loss: 1.277, Val f1_micro: 0.256
Epoch: 420, Train Loss: 1.249, Val f1_micro: 0.259
Epoch: 440, Train Loss: 1.250, Val f1_micro: 0.258
Epoch: 460, Train Loss: 1.211, Val f1_micro: 0.259
Epoch: 480, Train Loss: 1.196, Val f1_micro: 0.263
Epoch: 500, Train Loss: 1.182, Val f1_micro: 0.263
f1-micro: 0.263, f1-macro: 0.252, f1-weighted: 0.254, , roc-auc: 0.668
##### RUN 5 #####
Epoch: 020, Train Loss: 2.320, Val f1_micro: 0.194
Epoch: 040, Train Loss: 2.081, Val f1_micro: 0.205
Epoch: 060, Train Loss: 1.924, Val f1_micro: 0.208
Epoch: 080, Train Loss: 1.800, Val f1_micro: 0.218
Epoch: 100, Train Loss: 1.756, Val f1_micro: 0.219
Epoch: 120, Train Loss: 1.673, Val f1_micro: 0.225
Epoch: 140, Train Loss: 1.611, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.588, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.530, Val f1_micro: 0.237
Epoch: 200, Train Loss: 1.496, Val f1_micro: 0.238
Epoch: 220, Train Loss: 1.487, Val f1_micro: 0.239
Epoch: 240, Train Loss: 1.458, Val f1_micro: 0.244
Epoch: 260, Train Loss: 1.412, Val f1_micro: 0.243
Epoch: 280, Train Loss: 1.409, Val f1_micro: 0.249
Epoch: 300, Train Loss: 1.365, Val f1_micro: 0.252
Epoch: 320, Train Loss: 1.336, Val f1_micro: 0.252
Epoch: 340, Train Loss: 1.321, Val f1_micro: 0.251
Epoch: 360, Train Loss: 1.310, Val f1_micro: 0.254
Epoch: 380, Train Loss: 1.294, Val f1_micro: 0.257
Epoch: 400, Train Loss: 1.266, Val f1_micro: 0.258
Epoch: 420, Train Loss: 1.245, Val f1_micro: 0.257
Epoch: 440, Train Loss: 1.227, Val f1_micro: 0.262
Epoch: 460, Train Loss: 1.226, Val f1_micro: 0.257
Epoch: 480, Train Loss: 1.203, Val f1_micro: 0.257
Epoch: 500, Train Loss: 1.190, Val f1_micro: 0.264
f1-micro: 0.264, f1-macro: 0.253, f1-weighted: 0.255, , roc-auc: 0.667
########## Hyperparameters combination ##########
(512, 0.6, 0.001, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.372, Val f1_micro: 0.189
Epoch: 040, Train Loss: 2.052, Val f1_micro: 0.203
Epoch: 060, Train Loss: 1.897, Val f1_micro: 0.213
Epoch: 080, Train Loss: 1.816, Val f1_micro: 0.214
Epoch: 100, Train Loss: 1.728, Val f1_micro: 0.216
Epoch: 120, Train Loss: 1.677, Val f1_micro: 0.223
Epoch: 140, Train Loss: 1.627, Val f1_micro: 0.225
Epoch: 160, Train Loss: 1.589, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.540, Val f1_micro: 0.237
Epoch: 200, Train Loss: 1.510, Val f1_micro: 0.240
Epoch: 220, Train Loss: 1.480, Val f1_micro: 0.240
Epoch: 240, Train Loss: 1.454, Val f1_micro: 0.240
Epoch: 260, Train Loss: 1.433, Val f1_micro: 0.242
Epoch: 280, Train Loss: 1.422, Val f1_micro: 0.246
Epoch: 300, Train Loss: 1.405, Val f1_micro: 0.247
Epoch: 320, Train Loss: 1.380, Val f1_micro: 0.244
Epoch: 340, Train Loss: 1.373, Val f1_micro: 0.251
Epoch: 360, Train Loss: 1.359, Val f1_micro: 0.249
Epoch: 380, Train Loss: 1.323, Val f1_micro: 0.247
Epoch: 400, Train Loss: 1.312, Val f1_micro: 0.254
Epoch: 420, Train Loss: 1.323, Val f1_micro: 0.252
Epoch: 440, Train Loss: 1.308, Val f1_micro: 0.253
Epoch: 460, Train Loss: 1.288, Val f1_micro: 0.251
Epoch: 480, Train Loss: 1.285, Val f1_micro: 0.254
Epoch: 500, Train Loss: 1.266, Val f1_micro: 0.255
f1-micro: 0.255, f1-macro: 0.242, f1-weighted: 0.243, , roc-auc: 0.662
##### RUN 2 #####
Epoch: 020, Train Loss: 2.354, Val f1_micro: 0.189
Epoch: 040, Train Loss: 2.054, Val f1_micro: 0.203
Epoch: 060, Train Loss: 1.915, Val f1_micro: 0.210
Epoch: 080, Train Loss: 1.793, Val f1_micro: 0.213
Epoch: 100, Train Loss: 1.733, Val f1_micro: 0.220
Epoch: 120, Train Loss: 1.668, Val f1_micro: 0.223
Epoch: 140, Train Loss: 1.623, Val f1_micro: 0.226
Epoch: 160, Train Loss: 1.563, Val f1_micro: 0.230
Epoch: 180, Train Loss: 1.542, Val f1_micro: 0.233
Epoch: 200, Train Loss: 1.505, Val f1_micro: 0.241
Epoch: 220, Train Loss: 1.491, Val f1_micro: 0.239
Epoch: 240, Train Loss: 1.452, Val f1_micro: 0.244
Epoch: 260, Train Loss: 1.459, Val f1_micro: 0.243
Epoch: 280, Train Loss: 1.413, Val f1_micro: 0.246
Epoch: 300, Train Loss: 1.405, Val f1_micro: 0.250
Epoch: 320, Train Loss: 1.396, Val f1_micro: 0.244
Epoch: 340, Train Loss: 1.387, Val f1_micro: 0.249
Epoch: 360, Train Loss: 1.355, Val f1_micro: 0.250
Epoch: 380, Train Loss: 1.349, Val f1_micro: 0.251
Epoch: 400, Train Loss: 1.333, Val f1_micro: 0.252
Epoch: 420, Train Loss: 1.322, Val f1_micro: 0.251
Epoch: 440, Train Loss: 1.310, Val f1_micro: 0.253
Epoch: 460, Train Loss: 1.306, Val f1_micro: 0.252
Epoch: 480, Train Loss: 1.257, Val f1_micro: 0.255
Epoch: 500, Train Loss: 1.272, Val f1_micro: 0.255
f1-micro: 0.255, f1-macro: 0.243, f1-weighted: 0.244, , roc-auc: 0.660
##### RUN 3 #####
Epoch: 020, Train Loss: 2.363, Val f1_micro: 0.193
Epoch: 040, Train Loss: 2.094, Val f1_micro: 0.203
Epoch: 060, Train Loss: 1.916, Val f1_micro: 0.209
Epoch: 080, Train Loss: 1.818, Val f1_micro: 0.214
Epoch: 100, Train Loss: 1.724, Val f1_micro: 0.219
Epoch: 120, Train Loss: 1.674, Val f1_micro: 0.222
Epoch: 140, Train Loss: 1.615, Val f1_micro: 0.222
Epoch: 160, Train Loss: 1.576, Val f1_micro: 0.233
Epoch: 180, Train Loss: 1.554, Val f1_micro: 0.234
Epoch: 200, Train Loss: 1.512, Val f1_micro: 0.236
Epoch: 220, Train Loss: 1.500, Val f1_micro: 0.238
Epoch: 240, Train Loss: 1.468, Val f1_micro: 0.242
Epoch: 260, Train Loss: 1.435, Val f1_micro: 0.243
Epoch: 280, Train Loss: 1.441, Val f1_micro: 0.242
Epoch: 300, Train Loss: 1.408, Val f1_micro: 0.244
Epoch: 320, Train Loss: 1.400, Val f1_micro: 0.246
Epoch: 340, Train Loss: 1.356, Val f1_micro: 0.246
Epoch: 360, Train Loss: 1.351, Val f1_micro: 0.248
Epoch: 380, Train Loss: 1.317, Val f1_micro: 0.248
Epoch: 400, Train Loss: 1.321, Val f1_micro: 0.253
Epoch: 420, Train Loss: 1.326, Val f1_micro: 0.251
Epoch: 440, Train Loss: 1.309, Val f1_micro: 0.253
Epoch: 460, Train Loss: 1.278, Val f1_micro: 0.253
Epoch: 480, Train Loss: 1.264, Val f1_micro: 0.253
Epoch: 500, Train Loss: 1.271, Val f1_micro: 0.254
f1-micro: 0.254, f1-macro: 0.241, f1-weighted: 0.242, , roc-auc: 0.661
##### RUN 4 #####
Epoch: 020, Train Loss: 2.344, Val f1_micro: 0.191
Epoch: 040, Train Loss: 2.043, Val f1_micro: 0.204
Epoch: 060, Train Loss: 1.914, Val f1_micro: 0.210
Epoch: 080, Train Loss: 1.812, Val f1_micro: 0.214
Epoch: 100, Train Loss: 1.734, Val f1_micro: 0.221
Epoch: 120, Train Loss: 1.677, Val f1_micro: 0.222
Epoch: 140, Train Loss: 1.605, Val f1_micro: 0.227
Epoch: 160, Train Loss: 1.569, Val f1_micro: 0.230
Epoch: 180, Train Loss: 1.558, Val f1_micro: 0.237
Epoch: 200, Train Loss: 1.511, Val f1_micro: 0.238
Epoch: 220, Train Loss: 1.494, Val f1_micro: 0.236
Epoch: 240, Train Loss: 1.465, Val f1_micro: 0.240
Epoch: 260, Train Loss: 1.413, Val f1_micro: 0.246
Epoch: 280, Train Loss: 1.431, Val f1_micro: 0.246
Epoch: 300, Train Loss: 1.409, Val f1_micro: 0.243
Epoch: 320, Train Loss: 1.385, Val f1_micro: 0.248
Epoch: 340, Train Loss: 1.373, Val f1_micro: 0.249
Epoch: 360, Train Loss: 1.362, Val f1_micro: 0.250
Epoch: 380, Train Loss: 1.329, Val f1_micro: 0.254
Epoch: 400, Train Loss: 1.345, Val f1_micro: 0.251
Epoch: 420, Train Loss: 1.302, Val f1_micro: 0.251
Epoch: 440, Train Loss: 1.301, Val f1_micro: 0.255
Epoch: 460, Train Loss: 1.282, Val f1_micro: 0.256
Epoch: 480, Train Loss: 1.286, Val f1_micro: 0.255
Epoch: 500, Train Loss: 1.251, Val f1_micro: 0.256
f1-micro: 0.256, f1-macro: 0.243, f1-weighted: 0.244, , roc-auc: 0.662
##### RUN 5 #####
Epoch: 020, Train Loss: 2.338, Val f1_micro: 0.190
Epoch: 040, Train Loss: 2.055, Val f1_micro: 0.204
Epoch: 060, Train Loss: 1.902, Val f1_micro: 0.210
Epoch: 080, Train Loss: 1.809, Val f1_micro: 0.215
Epoch: 100, Train Loss: 1.739, Val f1_micro: 0.219
Epoch: 120, Train Loss: 1.665, Val f1_micro: 0.223
Epoch: 140, Train Loss: 1.632, Val f1_micro: 0.227
Epoch: 160, Train Loss: 1.583, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.558, Val f1_micro: 0.235
Epoch: 200, Train Loss: 1.519, Val f1_micro: 0.238
Epoch: 220, Train Loss: 1.484, Val f1_micro: 0.239
Epoch: 240, Train Loss: 1.471, Val f1_micro: 0.248
Epoch: 260, Train Loss: 1.435, Val f1_micro: 0.238
Epoch: 280, Train Loss: 1.420, Val f1_micro: 0.243
Epoch: 300, Train Loss: 1.401, Val f1_micro: 0.248
Epoch: 320, Train Loss: 1.389, Val f1_micro: 0.249
Epoch: 340, Train Loss: 1.365, Val f1_micro: 0.247
Epoch: 360, Train Loss: 1.359, Val f1_micro: 0.246
Epoch: 380, Train Loss: 1.361, Val f1_micro: 0.248
Epoch: 400, Train Loss: 1.315, Val f1_micro: 0.247
Epoch: 420, Train Loss: 1.317, Val f1_micro: 0.253
Epoch: 440, Train Loss: 1.300, Val f1_micro: 0.253
Epoch: 460, Train Loss: 1.301, Val f1_micro: 0.252
Epoch: 480, Train Loss: 1.275, Val f1_micro: 0.256
Epoch: 500, Train Loss: 1.286, Val f1_micro: 0.254
f1-micro: 0.254, f1-macro: 0.242, f1-weighted: 0.243, , roc-auc: 0.661
########## Hyperparameters combination ##########
(512, 0.6, 0.001, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.361, Val f1_micro: 0.194
Epoch: 040, Train Loss: 2.083, Val f1_micro: 0.202
Epoch: 060, Train Loss: 1.914, Val f1_micro: 0.208
Epoch: 080, Train Loss: 1.834, Val f1_micro: 0.210
Epoch: 100, Train Loss: 1.787, Val f1_micro: 0.208
Epoch: 120, Train Loss: 1.734, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.691, Val f1_micro: 0.215
Epoch: 160, Train Loss: 1.709, Val f1_micro: 0.218
Epoch: 180, Train Loss: 1.663, Val f1_micro: 0.224
Epoch: 200, Train Loss: 1.662, Val f1_micro: 0.218
Epoch: 220, Train Loss: 1.660, Val f1_micro: 0.221
Epoch: 240, Train Loss: 1.650, Val f1_micro: 0.222
Epoch: 260, Train Loss: 1.653, Val f1_micro: 0.224
Epoch: 280, Train Loss: 1.635, Val f1_micro: 0.220
Epoch: 300, Train Loss: 1.645, Val f1_micro: 0.223
Epoch: 320, Train Loss: 1.640, Val f1_micro: 0.224
Epoch: 340, Train Loss: 1.633, Val f1_micro: 0.219
Epoch: 360, Train Loss: 1.642, Val f1_micro: 0.222
Epoch: 380, Train Loss: 1.637, Val f1_micro: 0.225
Epoch: 400, Train Loss: 1.642, Val f1_micro: 0.223
Epoch: 420, Train Loss: 1.626, Val f1_micro: 0.225
Epoch: 440, Train Loss: 1.637, Val f1_micro: 0.223
Epoch: 460, Train Loss: 1.638, Val f1_micro: 0.219
Epoch: 480, Train Loss: 1.636, Val f1_micro: 0.220
Epoch: 500, Train Loss: 1.641, Val f1_micro: 0.217
f1-micro: 0.217, f1-macro: 0.189, f1-weighted: 0.191, , roc-auc: 0.656
##### RUN 2 #####
Epoch: 020, Train Loss: 2.362, Val f1_micro: 0.192
Epoch: 040, Train Loss: 2.063, Val f1_micro: 0.204
Epoch: 060, Train Loss: 1.936, Val f1_micro: 0.212
Epoch: 080, Train Loss: 1.851, Val f1_micro: 0.210
Epoch: 100, Train Loss: 1.790, Val f1_micro: 0.218
Epoch: 120, Train Loss: 1.757, Val f1_micro: 0.217
Epoch: 140, Train Loss: 1.716, Val f1_micro: 0.218
Epoch: 160, Train Loss: 1.701, Val f1_micro: 0.223
Epoch: 180, Train Loss: 1.687, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.663, Val f1_micro: 0.223
Epoch: 220, Train Loss: 1.658, Val f1_micro: 0.221
Epoch: 240, Train Loss: 1.656, Val f1_micro: 0.224
Epoch: 260, Train Loss: 1.642, Val f1_micro: 0.217
Epoch: 280, Train Loss: 1.649, Val f1_micro: 0.229
Epoch: 300, Train Loss: 1.641, Val f1_micro: 0.220
Epoch: 320, Train Loss: 1.634, Val f1_micro: 0.225
Epoch: 340, Train Loss: 1.635, Val f1_micro: 0.221
Epoch: 360, Train Loss: 1.630, Val f1_micro: 0.222
Epoch: 380, Train Loss: 1.637, Val f1_micro: 0.223
Epoch: 400, Train Loss: 1.624, Val f1_micro: 0.224
Epoch: 420, Train Loss: 1.633, Val f1_micro: 0.218
Epoch: 440, Train Loss: 1.638, Val f1_micro: 0.219
Epoch: 460, Train Loss: 1.644, Val f1_micro: 0.219
Epoch: 480, Train Loss: 1.628, Val f1_micro: 0.221
Epoch: 500, Train Loss: 1.641, Val f1_micro: 0.222
f1-micro: 0.222, f1-macro: 0.194, f1-weighted: 0.195, , roc-auc: 0.658
##### RUN 3 #####
Epoch: 020, Train Loss: 2.340, Val f1_micro: 0.193
Epoch: 040, Train Loss: 2.076, Val f1_micro: 0.203
Epoch: 060, Train Loss: 1.922, Val f1_micro: 0.204
Epoch: 080, Train Loss: 1.835, Val f1_micro: 0.203
Epoch: 100, Train Loss: 1.793, Val f1_micro: 0.218
Epoch: 120, Train Loss: 1.736, Val f1_micro: 0.216
Epoch: 140, Train Loss: 1.702, Val f1_micro: 0.220
Epoch: 160, Train Loss: 1.694, Val f1_micro: 0.216
Epoch: 180, Train Loss: 1.683, Val f1_micro: 0.214
Epoch: 200, Train Loss: 1.663, Val f1_micro: 0.223
Epoch: 220, Train Loss: 1.645, Val f1_micro: 0.220
Epoch: 240, Train Loss: 1.645, Val f1_micro: 0.222
Epoch: 260, Train Loss: 1.647, Val f1_micro: 0.220
Epoch: 280, Train Loss: 1.647, Val f1_micro: 0.223
Epoch: 300, Train Loss: 1.650, Val f1_micro: 0.225
Epoch: 320, Train Loss: 1.655, Val f1_micro: 0.222
Epoch: 340, Train Loss: 1.637, Val f1_micro: 0.223
Epoch: 360, Train Loss: 1.660, Val f1_micro: 0.225
Epoch: 380, Train Loss: 1.630, Val f1_micro: 0.224
Epoch: 400, Train Loss: 1.631, Val f1_micro: 0.219
Epoch: 420, Train Loss: 1.636, Val f1_micro: 0.221
Epoch: 440, Train Loss: 1.654, Val f1_micro: 0.215
Epoch: 460, Train Loss: 1.636, Val f1_micro: 0.219
Epoch: 480, Train Loss: 1.649, Val f1_micro: 0.220
Epoch: 500, Train Loss: 1.648, Val f1_micro: 0.220
f1-micro: 0.220, f1-macro: 0.193, f1-weighted: 0.194, , roc-auc: 0.657
##### RUN 4 #####
Epoch: 020, Train Loss: 2.393, Val f1_micro: 0.188
Epoch: 040, Train Loss: 2.064, Val f1_micro: 0.199
Epoch: 060, Train Loss: 1.921, Val f1_micro: 0.208
Epoch: 080, Train Loss: 1.841, Val f1_micro: 0.212
Epoch: 100, Train Loss: 1.799, Val f1_micro: 0.214
Epoch: 120, Train Loss: 1.739, Val f1_micro: 0.212
Epoch: 140, Train Loss: 1.708, Val f1_micro: 0.221
Epoch: 160, Train Loss: 1.706, Val f1_micro: 0.218
Epoch: 180, Train Loss: 1.668, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.680, Val f1_micro: 0.215
Epoch: 220, Train Loss: 1.658, Val f1_micro: 0.224
Epoch: 240, Train Loss: 1.648, Val f1_micro: 0.217
Epoch: 260, Train Loss: 1.646, Val f1_micro: 0.224
Epoch: 280, Train Loss: 1.649, Val f1_micro: 0.220
Epoch: 300, Train Loss: 1.641, Val f1_micro: 0.221
Epoch: 320, Train Loss: 1.657, Val f1_micro: 0.222
Epoch: 340, Train Loss: 1.641, Val f1_micro: 0.220
Epoch: 360, Train Loss: 1.642, Val f1_micro: 0.220
Epoch: 380, Train Loss: 1.641, Val f1_micro: 0.218
Epoch: 400, Train Loss: 1.636, Val f1_micro: 0.223
Epoch: 420, Train Loss: 1.645, Val f1_micro: 0.223
Epoch: 440, Train Loss: 1.639, Val f1_micro: 0.221
Epoch: 460, Train Loss: 1.643, Val f1_micro: 0.222
Epoch: 480, Train Loss: 1.642, Val f1_micro: 0.223
Epoch: 500, Train Loss: 1.641, Val f1_micro: 0.214
f1-micro: 0.214, f1-macro: 0.186, f1-weighted: 0.187, , roc-auc: 0.657
##### RUN 5 #####
Epoch: 020, Train Loss: 2.382, Val f1_micro: 0.189
Epoch: 040, Train Loss: 2.079, Val f1_micro: 0.203
Epoch: 060, Train Loss: 1.907, Val f1_micro: 0.213
Epoch: 080, Train Loss: 1.821, Val f1_micro: 0.208
Epoch: 100, Train Loss: 1.775, Val f1_micro: 0.216
Epoch: 120, Train Loss: 1.743, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.717, Val f1_micro: 0.218
Epoch: 160, Train Loss: 1.693, Val f1_micro: 0.219
Epoch: 180, Train Loss: 1.681, Val f1_micro: 0.220
Epoch: 200, Train Loss: 1.662, Val f1_micro: 0.219
Epoch: 220, Train Loss: 1.663, Val f1_micro: 0.224
Epoch: 240, Train Loss: 1.663, Val f1_micro: 0.223
Epoch: 260, Train Loss: 1.650, Val f1_micro: 0.225
Epoch: 280, Train Loss: 1.640, Val f1_micro: 0.223
Epoch: 300, Train Loss: 1.648, Val f1_micro: 0.226
Epoch: 320, Train Loss: 1.624, Val f1_micro: 0.221
Epoch: 340, Train Loss: 1.657, Val f1_micro: 0.226
Epoch: 360, Train Loss: 1.630, Val f1_micro: 0.224
Epoch: 380, Train Loss: 1.646, Val f1_micro: 0.222
Epoch: 400, Train Loss: 1.632, Val f1_micro: 0.220
Epoch: 420, Train Loss: 1.655, Val f1_micro: 0.222
Epoch: 440, Train Loss: 1.646, Val f1_micro: 0.223
Epoch: 460, Train Loss: 1.641, Val f1_micro: 0.219
Epoch: 480, Train Loss: 1.648, Val f1_micro: 0.221
Epoch: 500, Train Loss: 1.644, Val f1_micro: 0.224
f1-micro: 0.224, f1-macro: 0.195, f1-weighted: 0.196, , roc-auc: 0.657
########## Hyperparameters combination ##########
(512, 0.6, 0.005, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.848, Val f1_micro: 0.211
Epoch: 040, Train Loss: 1.607, Val f1_micro: 0.234
Epoch: 060, Train Loss: 1.459, Val f1_micro: 0.248
Epoch: 080, Train Loss: 1.342, Val f1_micro: 0.255
Epoch: 100, Train Loss: 1.254, Val f1_micro: 0.267
Epoch: 120, Train Loss: 1.158, Val f1_micro: 0.271
Epoch: 140, Train Loss: 1.088, Val f1_micro: 0.271
Epoch: 160, Train Loss: 1.025, Val f1_micro: 0.278
Epoch: 180, Train Loss: 0.978, Val f1_micro: 0.280
Epoch: 200, Train Loss: 0.906, Val f1_micro: 0.285
Epoch: 220, Train Loss: 0.854, Val f1_micro: 0.290
Epoch: 240, Train Loss: 0.829, Val f1_micro: 0.290
Epoch: 260, Train Loss: 0.791, Val f1_micro: 0.294
Epoch: 280, Train Loss: 0.714, Val f1_micro: 0.301
Epoch: 300, Train Loss: 0.695, Val f1_micro: 0.296
Epoch: 320, Train Loss: 0.645, Val f1_micro: 0.299
Epoch: 340, Train Loss: 0.644, Val f1_micro: 0.301
Epoch: 360, Train Loss: 0.615, Val f1_micro: 0.303
Epoch: 380, Train Loss: 0.569, Val f1_micro: 0.307
Epoch: 400, Train Loss: 0.568, Val f1_micro: 0.302
Epoch: 420, Train Loss: 0.529, Val f1_micro: 0.307
Epoch: 440, Train Loss: 0.498, Val f1_micro: 0.309
Epoch: 460, Train Loss: 0.498, Val f1_micro: 0.309
Epoch: 480, Train Loss: 0.478, Val f1_micro: 0.310
Epoch: 500, Train Loss: 0.462, Val f1_micro: 0.309
f1-micro: 0.309, f1-macro: 0.303, f1-weighted: 0.309, , roc-auc: 0.676
##### RUN 2 #####
Epoch: 020, Train Loss: 1.878, Val f1_micro: 0.206
Epoch: 040, Train Loss: 1.593, Val f1_micro: 0.233
Epoch: 060, Train Loss: 1.472, Val f1_micro: 0.256
Epoch: 080, Train Loss: 1.345, Val f1_micro: 0.259
Epoch: 100, Train Loss: 1.267, Val f1_micro: 0.263
Epoch: 120, Train Loss: 1.151, Val f1_micro: 0.271
Epoch: 140, Train Loss: 1.095, Val f1_micro: 0.270
Epoch: 160, Train Loss: 1.045, Val f1_micro: 0.276
Epoch: 180, Train Loss: 0.977, Val f1_micro: 0.281
Epoch: 200, Train Loss: 0.920, Val f1_micro: 0.284
Epoch: 220, Train Loss: 0.863, Val f1_micro: 0.289
Epoch: 240, Train Loss: 0.827, Val f1_micro: 0.286
Epoch: 260, Train Loss: 0.806, Val f1_micro: 0.293
Epoch: 280, Train Loss: 0.752, Val f1_micro: 0.291
Epoch: 300, Train Loss: 0.700, Val f1_micro: 0.299
Epoch: 320, Train Loss: 0.695, Val f1_micro: 0.295
Epoch: 340, Train Loss: 0.655, Val f1_micro: 0.302
Epoch: 360, Train Loss: 0.606, Val f1_micro: 0.302
Epoch: 380, Train Loss: 0.586, Val f1_micro: 0.299
Epoch: 400, Train Loss: 0.575, Val f1_micro: 0.300
Epoch: 420, Train Loss: 0.533, Val f1_micro: 0.306
Epoch: 440, Train Loss: 0.515, Val f1_micro: 0.309
Epoch: 460, Train Loss: 0.484, Val f1_micro: 0.309
Epoch: 480, Train Loss: 0.483, Val f1_micro: 0.310
Epoch: 500, Train Loss: 0.449, Val f1_micro: 0.311
f1-micro: 0.311, f1-macro: 0.304, f1-weighted: 0.311, , roc-auc: 0.677
##### RUN 3 #####
Epoch: 020, Train Loss: 1.865, Val f1_micro: 0.209
Epoch: 040, Train Loss: 1.626, Val f1_micro: 0.234
Epoch: 060, Train Loss: 1.463, Val f1_micro: 0.245
Epoch: 080, Train Loss: 1.323, Val f1_micro: 0.255
Epoch: 100, Train Loss: 1.252, Val f1_micro: 0.269
Epoch: 120, Train Loss: 1.172, Val f1_micro: 0.263
Epoch: 140, Train Loss: 1.102, Val f1_micro: 0.270
Epoch: 160, Train Loss: 1.047, Val f1_micro: 0.276
Epoch: 180, Train Loss: 0.990, Val f1_micro: 0.282
Epoch: 200, Train Loss: 0.928, Val f1_micro: 0.285
Epoch: 220, Train Loss: 0.880, Val f1_micro: 0.284
Epoch: 240, Train Loss: 0.847, Val f1_micro: 0.289
Epoch: 260, Train Loss: 0.785, Val f1_micro: 0.292
Epoch: 280, Train Loss: 0.745, Val f1_micro: 0.298
Epoch: 300, Train Loss: 0.706, Val f1_micro: 0.299
Epoch: 320, Train Loss: 0.673, Val f1_micro: 0.299
Epoch: 340, Train Loss: 0.636, Val f1_micro: 0.301
Epoch: 360, Train Loss: 0.628, Val f1_micro: 0.304
Epoch: 380, Train Loss: 0.588, Val f1_micro: 0.301
Epoch: 400, Train Loss: 0.548, Val f1_micro: 0.311
Epoch: 420, Train Loss: 0.542, Val f1_micro: 0.309
Epoch: 440, Train Loss: 0.514, Val f1_micro: 0.310
Epoch: 460, Train Loss: 0.493, Val f1_micro: 0.312
Epoch: 480, Train Loss: 0.480, Val f1_micro: 0.313
Epoch: 500, Train Loss: 0.462, Val f1_micro: 0.312
f1-micro: 0.312, f1-macro: 0.305, f1-weighted: 0.313, , roc-auc: 0.678
##### RUN 4 #####
Epoch: 020, Train Loss: 1.870, Val f1_micro: 0.212
Epoch: 040, Train Loss: 1.598, Val f1_micro: 0.227
Epoch: 060, Train Loss: 1.448, Val f1_micro: 0.249
Epoch: 080, Train Loss: 1.341, Val f1_micro: 0.256
Epoch: 100, Train Loss: 1.268, Val f1_micro: 0.265
Epoch: 120, Train Loss: 1.174, Val f1_micro: 0.266
Epoch: 140, Train Loss: 1.097, Val f1_micro: 0.275
Epoch: 160, Train Loss: 1.059, Val f1_micro: 0.272
Epoch: 180, Train Loss: 0.992, Val f1_micro: 0.282
Epoch: 200, Train Loss: 0.936, Val f1_micro: 0.284
Epoch: 220, Train Loss: 0.873, Val f1_micro: 0.283
Epoch: 240, Train Loss: 0.828, Val f1_micro: 0.292
Epoch: 260, Train Loss: 0.771, Val f1_micro: 0.295
Epoch: 280, Train Loss: 0.761, Val f1_micro: 0.298
Epoch: 300, Train Loss: 0.719, Val f1_micro: 0.297
Epoch: 320, Train Loss: 0.681, Val f1_micro: 0.300
Epoch: 340, Train Loss: 0.637, Val f1_micro: 0.303
Epoch: 360, Train Loss: 0.626, Val f1_micro: 0.301
Epoch: 380, Train Loss: 0.592, Val f1_micro: 0.304
Epoch: 400, Train Loss: 0.567, Val f1_micro: 0.303
Epoch: 420, Train Loss: 0.533, Val f1_micro: 0.309
Epoch: 440, Train Loss: 0.509, Val f1_micro: 0.307
Epoch: 460, Train Loss: 0.490, Val f1_micro: 0.307
Epoch: 480, Train Loss: 0.481, Val f1_micro: 0.310
Epoch: 500, Train Loss: 0.460, Val f1_micro: 0.311
f1-micro: 0.311, f1-macro: 0.302, f1-weighted: 0.310, , roc-auc: 0.677
##### RUN 5 #####
Epoch: 020, Train Loss: 1.836, Val f1_micro: 0.209
Epoch: 040, Train Loss: 1.614, Val f1_micro: 0.242
Epoch: 060, Train Loss: 1.454, Val f1_micro: 0.249
Epoch: 080, Train Loss: 1.363, Val f1_micro: 0.264
Epoch: 100, Train Loss: 1.229, Val f1_micro: 0.266
Epoch: 120, Train Loss: 1.176, Val f1_micro: 0.272
Epoch: 140, Train Loss: 1.097, Val f1_micro: 0.280
Epoch: 160, Train Loss: 1.047, Val f1_micro: 0.282
Epoch: 180, Train Loss: 0.973, Val f1_micro: 0.280
Epoch: 200, Train Loss: 0.912, Val f1_micro: 0.285
Epoch: 220, Train Loss: 0.867, Val f1_micro: 0.290
Epoch: 240, Train Loss: 0.833, Val f1_micro: 0.290
Epoch: 260, Train Loss: 0.794, Val f1_micro: 0.297
Epoch: 280, Train Loss: 0.741, Val f1_micro: 0.294
Epoch: 300, Train Loss: 0.710, Val f1_micro: 0.302
Epoch: 320, Train Loss: 0.673, Val f1_micro: 0.305
Epoch: 340, Train Loss: 0.653, Val f1_micro: 0.299
Epoch: 360, Train Loss: 0.616, Val f1_micro: 0.301
Epoch: 380, Train Loss: 0.583, Val f1_micro: 0.303
Epoch: 400, Train Loss: 0.561, Val f1_micro: 0.304
Epoch: 420, Train Loss: 0.548, Val f1_micro: 0.305
Epoch: 440, Train Loss: 0.515, Val f1_micro: 0.307
Epoch: 460, Train Loss: 0.485, Val f1_micro: 0.307
Epoch: 480, Train Loss: 0.471, Val f1_micro: 0.306
Epoch: 500, Train Loss: 0.464, Val f1_micro: 0.307
f1-micro: 0.307, f1-macro: 0.300, f1-weighted: 0.307, , roc-auc: 0.675
########## Hyperparameters combination ##########
(512, 0.6, 0.005, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.884, Val f1_micro: 0.209
Epoch: 040, Train Loss: 1.601, Val f1_micro: 0.233
Epoch: 060, Train Loss: 1.472, Val f1_micro: 0.251
Epoch: 080, Train Loss: 1.399, Val f1_micro: 0.257
Epoch: 100, Train Loss: 1.306, Val f1_micro: 0.263
Epoch: 120, Train Loss: 1.237, Val f1_micro: 0.260
Epoch: 140, Train Loss: 1.194, Val f1_micro: 0.265
Epoch: 160, Train Loss: 1.142, Val f1_micro: 0.266
Epoch: 180, Train Loss: 1.097, Val f1_micro: 0.270
Epoch: 200, Train Loss: 1.054, Val f1_micro: 0.271
Epoch: 220, Train Loss: 1.005, Val f1_micro: 0.277
Epoch: 240, Train Loss: 0.991, Val f1_micro: 0.276
Epoch: 260, Train Loss: 0.951, Val f1_micro: 0.280
Epoch: 280, Train Loss: 0.933, Val f1_micro: 0.279
Epoch: 300, Train Loss: 0.883, Val f1_micro: 0.284
Epoch: 320, Train Loss: 0.893, Val f1_micro: 0.284
Epoch: 340, Train Loss: 0.866, Val f1_micro: 0.284
Epoch: 360, Train Loss: 0.833, Val f1_micro: 0.282
Epoch: 380, Train Loss: 0.830, Val f1_micro: 0.287
Epoch: 400, Train Loss: 0.810, Val f1_micro: 0.289
Epoch: 420, Train Loss: 0.794, Val f1_micro: 0.290
Epoch: 440, Train Loss: 0.787, Val f1_micro: 0.290
Epoch: 460, Train Loss: 0.774, Val f1_micro: 0.294
Epoch: 480, Train Loss: 0.756, Val f1_micro: 0.293
Epoch: 500, Train Loss: 0.716, Val f1_micro: 0.299
f1-micro: 0.299, f1-macro: 0.291, f1-weighted: 0.297, , roc-auc: 0.668
##### RUN 2 #####
Epoch: 020, Train Loss: 1.871, Val f1_micro: 0.214
Epoch: 040, Train Loss: 1.602, Val f1_micro: 0.226
Epoch: 060, Train Loss: 1.449, Val f1_micro: 0.246
Epoch: 080, Train Loss: 1.381, Val f1_micro: 0.249
Epoch: 100, Train Loss: 1.291, Val f1_micro: 0.255
Epoch: 120, Train Loss: 1.240, Val f1_micro: 0.256
Epoch: 140, Train Loss: 1.215, Val f1_micro: 0.257
Epoch: 160, Train Loss: 1.153, Val f1_micro: 0.268
Epoch: 180, Train Loss: 1.123, Val f1_micro: 0.266
Epoch: 200, Train Loss: 1.091, Val f1_micro: 0.273
Epoch: 220, Train Loss: 1.025, Val f1_micro: 0.276
Epoch: 240, Train Loss: 0.994, Val f1_micro: 0.276
Epoch: 260, Train Loss: 0.982, Val f1_micro: 0.278
Epoch: 280, Train Loss: 0.942, Val f1_micro: 0.281
Epoch: 300, Train Loss: 0.919, Val f1_micro: 0.283
Epoch: 320, Train Loss: 0.876, Val f1_micro: 0.285
Epoch: 340, Train Loss: 0.861, Val f1_micro: 0.285
Epoch: 360, Train Loss: 0.864, Val f1_micro: 0.285
Epoch: 380, Train Loss: 0.835, Val f1_micro: 0.288
Epoch: 400, Train Loss: 0.809, Val f1_micro: 0.289
Epoch: 420, Train Loss: 0.807, Val f1_micro: 0.292
Epoch: 440, Train Loss: 0.790, Val f1_micro: 0.290
Epoch: 460, Train Loss: 0.776, Val f1_micro: 0.290
Epoch: 480, Train Loss: 0.744, Val f1_micro: 0.290
Epoch: 500, Train Loss: 0.741, Val f1_micro: 0.297
f1-micro: 0.297, f1-macro: 0.288, f1-weighted: 0.294, , roc-auc: 0.669
##### RUN 3 #####
Epoch: 020, Train Loss: 1.891, Val f1_micro: 0.204
Epoch: 040, Train Loss: 1.624, Val f1_micro: 0.227
Epoch: 060, Train Loss: 1.480, Val f1_micro: 0.248
Epoch: 080, Train Loss: 1.366, Val f1_micro: 0.253
Epoch: 100, Train Loss: 1.317, Val f1_micro: 0.256
Epoch: 120, Train Loss: 1.252, Val f1_micro: 0.257
Epoch: 140, Train Loss: 1.183, Val f1_micro: 0.261
Epoch: 160, Train Loss: 1.133, Val f1_micro: 0.270
Epoch: 180, Train Loss: 1.091, Val f1_micro: 0.271
Epoch: 200, Train Loss: 1.049, Val f1_micro: 0.271
Epoch: 220, Train Loss: 1.011, Val f1_micro: 0.275
Epoch: 240, Train Loss: 0.988, Val f1_micro: 0.276
Epoch: 260, Train Loss: 0.955, Val f1_micro: 0.276
Epoch: 280, Train Loss: 0.949, Val f1_micro: 0.279
Epoch: 300, Train Loss: 0.912, Val f1_micro: 0.282
Epoch: 320, Train Loss: 0.900, Val f1_micro: 0.279
Epoch: 340, Train Loss: 0.847, Val f1_micro: 0.282
Epoch: 360, Train Loss: 0.842, Val f1_micro: 0.285
Epoch: 380, Train Loss: 0.829, Val f1_micro: 0.288
Epoch: 400, Train Loss: 0.812, Val f1_micro: 0.288
Epoch: 420, Train Loss: 0.778, Val f1_micro: 0.291
Epoch: 440, Train Loss: 0.781, Val f1_micro: 0.291
Epoch: 460, Train Loss: 0.788, Val f1_micro: 0.293
Epoch: 480, Train Loss: 0.748, Val f1_micro: 0.292
Epoch: 500, Train Loss: 0.736, Val f1_micro: 0.291
f1-micro: 0.291, f1-macro: 0.283, f1-weighted: 0.289, , roc-auc: 0.668
##### RUN 4 #####
Epoch: 020, Train Loss: 1.856, Val f1_micro: 0.217
Epoch: 040, Train Loss: 1.611, Val f1_micro: 0.233
Epoch: 060, Train Loss: 1.479, Val f1_micro: 0.241
Epoch: 080, Train Loss: 1.407, Val f1_micro: 0.245
Epoch: 100, Train Loss: 1.291, Val f1_micro: 0.254
Epoch: 120, Train Loss: 1.254, Val f1_micro: 0.263
Epoch: 140, Train Loss: 1.194, Val f1_micro: 0.266
Epoch: 160, Train Loss: 1.143, Val f1_micro: 0.266
Epoch: 180, Train Loss: 1.090, Val f1_micro: 0.267
Epoch: 200, Train Loss: 1.074, Val f1_micro: 0.273
Epoch: 220, Train Loss: 1.024, Val f1_micro: 0.277
Epoch: 240, Train Loss: 0.991, Val f1_micro: 0.280
Epoch: 260, Train Loss: 0.968, Val f1_micro: 0.277
Epoch: 280, Train Loss: 0.937, Val f1_micro: 0.278
Epoch: 300, Train Loss: 0.898, Val f1_micro: 0.282
Epoch: 320, Train Loss: 0.906, Val f1_micro: 0.281
Epoch: 340, Train Loss: 0.873, Val f1_micro: 0.284
Epoch: 360, Train Loss: 0.845, Val f1_micro: 0.287
Epoch: 380, Train Loss: 0.830, Val f1_micro: 0.292
Epoch: 400, Train Loss: 0.817, Val f1_micro: 0.293
Epoch: 420, Train Loss: 0.812, Val f1_micro: 0.291
Epoch: 440, Train Loss: 0.767, Val f1_micro: 0.289
Epoch: 460, Train Loss: 0.772, Val f1_micro: 0.295
Epoch: 480, Train Loss: 0.765, Val f1_micro: 0.293
Epoch: 500, Train Loss: 0.749, Val f1_micro: 0.296
f1-micro: 0.296, f1-macro: 0.288, f1-weighted: 0.294, , roc-auc: 0.666
##### RUN 5 #####
Epoch: 020, Train Loss: 1.876, Val f1_micro: 0.198
Epoch: 040, Train Loss: 1.631, Val f1_micro: 0.235
Epoch: 060, Train Loss: 1.462, Val f1_micro: 0.242
Epoch: 080, Train Loss: 1.376, Val f1_micro: 0.254
Epoch: 100, Train Loss: 1.303, Val f1_micro: 0.255
Epoch: 120, Train Loss: 1.236, Val f1_micro: 0.267
Epoch: 140, Train Loss: 1.204, Val f1_micro: 0.266
Epoch: 160, Train Loss: 1.135, Val f1_micro: 0.267
Epoch: 180, Train Loss: 1.110, Val f1_micro: 0.271
Epoch: 200, Train Loss: 1.055, Val f1_micro: 0.273
Epoch: 220, Train Loss: 1.033, Val f1_micro: 0.274
Epoch: 240, Train Loss: 1.011, Val f1_micro: 0.279
Epoch: 260, Train Loss: 0.946, Val f1_micro: 0.278
Epoch: 280, Train Loss: 0.932, Val f1_micro: 0.282
Epoch: 300, Train Loss: 0.911, Val f1_micro: 0.284
Epoch: 320, Train Loss: 0.884, Val f1_micro: 0.284
Epoch: 340, Train Loss: 0.861, Val f1_micro: 0.284
Epoch: 360, Train Loss: 0.853, Val f1_micro: 0.285
Epoch: 380, Train Loss: 0.827, Val f1_micro: 0.285
Epoch: 400, Train Loss: 0.788, Val f1_micro: 0.288
Epoch: 420, Train Loss: 0.791, Val f1_micro: 0.287
Epoch: 440, Train Loss: 0.782, Val f1_micro: 0.294
Epoch: 460, Train Loss: 0.767, Val f1_micro: 0.292
Epoch: 480, Train Loss: 0.756, Val f1_micro: 0.290
Epoch: 500, Train Loss: 0.740, Val f1_micro: 0.293
f1-micro: 0.293, f1-macro: 0.286, f1-weighted: 0.292, , roc-auc: 0.668
########## Hyperparameters combination ##########
(512, 0.6, 0.005, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.851, Val f1_micro: 0.196
Epoch: 040, Train Loss: 1.624, Val f1_micro: 0.230
Epoch: 060, Train Loss: 1.512, Val f1_micro: 0.241
Epoch: 080, Train Loss: 1.423, Val f1_micro: 0.254
Epoch: 100, Train Loss: 1.354, Val f1_micro: 0.252
Epoch: 120, Train Loss: 1.318, Val f1_micro: 0.256
Epoch: 140, Train Loss: 1.293, Val f1_micro: 0.263
Epoch: 160, Train Loss: 1.260, Val f1_micro: 0.260
Epoch: 180, Train Loss: 1.221, Val f1_micro: 0.263
Epoch: 200, Train Loss: 1.195, Val f1_micro: 0.267
Epoch: 220, Train Loss: 1.153, Val f1_micro: 0.267
Epoch: 240, Train Loss: 1.153, Val f1_micro: 0.266
Epoch: 260, Train Loss: 1.133, Val f1_micro: 0.264
Epoch: 280, Train Loss: 1.121, Val f1_micro: 0.269
Epoch: 300, Train Loss: 1.096, Val f1_micro: 0.270
Epoch: 320, Train Loss: 1.063, Val f1_micro: 0.272
Epoch: 340, Train Loss: 1.060, Val f1_micro: 0.276
Epoch: 360, Train Loss: 1.069, Val f1_micro: 0.273
Epoch: 380, Train Loss: 1.027, Val f1_micro: 0.277
Epoch: 400, Train Loss: 1.035, Val f1_micro: 0.278
Epoch: 420, Train Loss: 1.001, Val f1_micro: 0.275
Epoch: 440, Train Loss: 1.015, Val f1_micro: 0.281
Epoch: 460, Train Loss: 1.002, Val f1_micro: 0.278
Epoch: 480, Train Loss: 0.986, Val f1_micro: 0.278
Epoch: 500, Train Loss: 0.986, Val f1_micro: 0.283
f1-micro: 0.283, f1-macro: 0.276, f1-weighted: 0.280, , roc-auc: 0.662
##### RUN 2 #####
Epoch: 020, Train Loss: 1.858, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.630, Val f1_micro: 0.227
Epoch: 060, Train Loss: 1.519, Val f1_micro: 0.242
Epoch: 080, Train Loss: 1.401, Val f1_micro: 0.252
Epoch: 100, Train Loss: 1.350, Val f1_micro: 0.252
Epoch: 120, Train Loss: 1.322, Val f1_micro: 0.257
Epoch: 140, Train Loss: 1.264, Val f1_micro: 0.260
Epoch: 160, Train Loss: 1.256, Val f1_micro: 0.264
Epoch: 180, Train Loss: 1.235, Val f1_micro: 0.264
Epoch: 200, Train Loss: 1.189, Val f1_micro: 0.268
Epoch: 220, Train Loss: 1.168, Val f1_micro: 0.267
Epoch: 240, Train Loss: 1.144, Val f1_micro: 0.270
Epoch: 260, Train Loss: 1.128, Val f1_micro: 0.274
Epoch: 280, Train Loss: 1.111, Val f1_micro: 0.270
Epoch: 300, Train Loss: 1.100, Val f1_micro: 0.275
Epoch: 320, Train Loss: 1.073, Val f1_micro: 0.277
Epoch: 340, Train Loss: 1.057, Val f1_micro: 0.277
Epoch: 360, Train Loss: 1.051, Val f1_micro: 0.281
Epoch: 380, Train Loss: 1.054, Val f1_micro: 0.282
Epoch: 400, Train Loss: 1.046, Val f1_micro: 0.283
Epoch: 420, Train Loss: 1.009, Val f1_micro: 0.284
Epoch: 440, Train Loss: 0.985, Val f1_micro: 0.280
Epoch: 460, Train Loss: 0.992, Val f1_micro: 0.279
Epoch: 480, Train Loss: 0.995, Val f1_micro: 0.282
Epoch: 500, Train Loss: 0.971, Val f1_micro: 0.282
f1-micro: 0.282, f1-macro: 0.272, f1-weighted: 0.276, , roc-auc: 0.664
##### RUN 3 #####
Epoch: 020, Train Loss: 1.849, Val f1_micro: 0.203
Epoch: 040, Train Loss: 1.626, Val f1_micro: 0.226
Epoch: 060, Train Loss: 1.493, Val f1_micro: 0.242
Epoch: 080, Train Loss: 1.406, Val f1_micro: 0.247
Epoch: 100, Train Loss: 1.374, Val f1_micro: 0.251
Epoch: 120, Train Loss: 1.330, Val f1_micro: 0.257
Epoch: 140, Train Loss: 1.271, Val f1_micro: 0.260
Epoch: 160, Train Loss: 1.247, Val f1_micro: 0.255
Epoch: 180, Train Loss: 1.231, Val f1_micro: 0.260
Epoch: 200, Train Loss: 1.204, Val f1_micro: 0.264
Epoch: 220, Train Loss: 1.172, Val f1_micro: 0.268
Epoch: 240, Train Loss: 1.152, Val f1_micro: 0.263
Epoch: 260, Train Loss: 1.118, Val f1_micro: 0.271
Epoch: 280, Train Loss: 1.119, Val f1_micro: 0.272
Epoch: 300, Train Loss: 1.108, Val f1_micro: 0.272
Epoch: 320, Train Loss: 1.077, Val f1_micro: 0.277
Epoch: 340, Train Loss: 1.060, Val f1_micro: 0.280
Epoch: 360, Train Loss: 1.059, Val f1_micro: 0.277
Epoch: 380, Train Loss: 1.046, Val f1_micro: 0.275
Epoch: 400, Train Loss: 1.035, Val f1_micro: 0.283
Epoch: 420, Train Loss: 1.013, Val f1_micro: 0.281
Epoch: 440, Train Loss: 0.991, Val f1_micro: 0.282
Epoch: 460, Train Loss: 0.994, Val f1_micro: 0.281
Epoch: 480, Train Loss: 0.985, Val f1_micro: 0.281
Epoch: 500, Train Loss: 0.977, Val f1_micro: 0.282
f1-micro: 0.282, f1-macro: 0.274, f1-weighted: 0.279, , roc-auc: 0.666
##### RUN 4 #####
Epoch: 020, Train Loss: 1.862, Val f1_micro: 0.199
Epoch: 040, Train Loss: 1.615, Val f1_micro: 0.228
Epoch: 060, Train Loss: 1.501, Val f1_micro: 0.244
Epoch: 080, Train Loss: 1.437, Val f1_micro: 0.255
Epoch: 100, Train Loss: 1.374, Val f1_micro: 0.254
Epoch: 120, Train Loss: 1.316, Val f1_micro: 0.258
Epoch: 140, Train Loss: 1.283, Val f1_micro: 0.259
Epoch: 160, Train Loss: 1.249, Val f1_micro: 0.259
Epoch: 180, Train Loss: 1.221, Val f1_micro: 0.264
Epoch: 200, Train Loss: 1.199, Val f1_micro: 0.265
Epoch: 220, Train Loss: 1.171, Val f1_micro: 0.264
Epoch: 240, Train Loss: 1.144, Val f1_micro: 0.272
Epoch: 260, Train Loss: 1.139, Val f1_micro: 0.270
Epoch: 280, Train Loss: 1.106, Val f1_micro: 0.273
Epoch: 300, Train Loss: 1.108, Val f1_micro: 0.274
Epoch: 320, Train Loss: 1.083, Val f1_micro: 0.276
Epoch: 340, Train Loss: 1.094, Val f1_micro: 0.276
Epoch: 360, Train Loss: 1.058, Val f1_micro: 0.276
Epoch: 380, Train Loss: 1.052, Val f1_micro: 0.274
Epoch: 400, Train Loss: 1.056, Val f1_micro: 0.280
Epoch: 420, Train Loss: 1.010, Val f1_micro: 0.280
Epoch: 440, Train Loss: 0.993, Val f1_micro: 0.281
Epoch: 460, Train Loss: 1.001, Val f1_micro: 0.282
Epoch: 480, Train Loss: 0.994, Val f1_micro: 0.282
Epoch: 500, Train Loss: 0.988, Val f1_micro: 0.282
f1-micro: 0.282, f1-macro: 0.273, f1-weighted: 0.276, , roc-auc: 0.664
##### RUN 5 #####
Epoch: 020, Train Loss: 1.845, Val f1_micro: 0.218
Epoch: 040, Train Loss: 1.630, Val f1_micro: 0.236
Epoch: 060, Train Loss: 1.514, Val f1_micro: 0.240
Epoch: 080, Train Loss: 1.407, Val f1_micro: 0.250
Epoch: 100, Train Loss: 1.381, Val f1_micro: 0.255
Epoch: 120, Train Loss: 1.304, Val f1_micro: 0.261
Epoch: 140, Train Loss: 1.279, Val f1_micro: 0.259
Epoch: 160, Train Loss: 1.238, Val f1_micro: 0.261
Epoch: 180, Train Loss: 1.217, Val f1_micro: 0.257
Epoch: 200, Train Loss: 1.183, Val f1_micro: 0.269
Epoch: 220, Train Loss: 1.177, Val f1_micro: 0.263
Epoch: 240, Train Loss: 1.150, Val f1_micro: 0.267
Epoch: 260, Train Loss: 1.141, Val f1_micro: 0.268
Epoch: 280, Train Loss: 1.123, Val f1_micro: 0.273
Epoch: 300, Train Loss: 1.088, Val f1_micro: 0.270
Epoch: 320, Train Loss: 1.067, Val f1_micro: 0.277
Epoch: 340, Train Loss: 1.073, Val f1_micro: 0.277
Epoch: 360, Train Loss: 1.052, Val f1_micro: 0.278
Epoch: 380, Train Loss: 1.039, Val f1_micro: 0.277
Epoch: 400, Train Loss: 1.035, Val f1_micro: 0.280
Epoch: 420, Train Loss: 1.028, Val f1_micro: 0.280
Epoch: 440, Train Loss: 1.025, Val f1_micro: 0.282
Epoch: 460, Train Loss: 1.010, Val f1_micro: 0.280
Epoch: 480, Train Loss: 0.969, Val f1_micro: 0.280
Epoch: 500, Train Loss: 1.006, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.272, f1-weighted: 0.277, , roc-auc: 0.663
########## Hyperparameters combination ##########
(512, 0.6, 0.005, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.873, Val f1_micro: 0.203
Epoch: 040, Train Loss: 1.710, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.657, Val f1_micro: 0.222
Epoch: 080, Train Loss: 1.682, Val f1_micro: 0.218
Epoch: 100, Train Loss: 1.672, Val f1_micro: 0.222
Epoch: 120, Train Loss: 1.667, Val f1_micro: 0.222
Epoch: 140, Train Loss: 1.662, Val f1_micro: 0.225
Epoch: 160, Train Loss: 1.672, Val f1_micro: 0.214
Epoch: 180, Train Loss: 1.696, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.697, Val f1_micro: 0.211
Epoch: 220, Train Loss: 1.689, Val f1_micro: 0.214
Epoch: 240, Train Loss: 1.706, Val f1_micro: 0.207
Epoch: 260, Train Loss: 1.705, Val f1_micro: 0.218
Epoch: 280, Train Loss: 1.694, Val f1_micro: 0.216
Epoch: 300, Train Loss: 1.711, Val f1_micro: 0.204
Epoch: 320, Train Loss: 1.699, Val f1_micro: 0.219
Epoch: 340, Train Loss: 1.703, Val f1_micro: 0.221
Epoch: 360, Train Loss: 1.701, Val f1_micro: 0.213
Epoch: 380, Train Loss: 1.711, Val f1_micro: 0.226
Epoch: 400, Train Loss: 1.714, Val f1_micro: 0.211
Epoch: 420, Train Loss: 1.713, Val f1_micro: 0.209
Epoch: 440, Train Loss: 1.711, Val f1_micro: 0.206
Epoch: 460, Train Loss: 1.698, Val f1_micro: 0.213
Epoch: 480, Train Loss: 1.716, Val f1_micro: 0.219
Epoch: 500, Train Loss: 1.694, Val f1_micro: 0.212
f1-micro: 0.212, f1-macro: 0.175, f1-weighted: 0.178, , roc-auc: 0.633
##### RUN 2 #####
Epoch: 020, Train Loss: 1.887, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.699, Val f1_micro: 0.214
Epoch: 060, Train Loss: 1.677, Val f1_micro: 0.221
Epoch: 080, Train Loss: 1.655, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.669, Val f1_micro: 0.218
Epoch: 120, Train Loss: 1.651, Val f1_micro: 0.226
Epoch: 140, Train Loss: 1.690, Val f1_micro: 0.214
Epoch: 160, Train Loss: 1.700, Val f1_micro: 0.222
Epoch: 180, Train Loss: 1.676, Val f1_micro: 0.223
Epoch: 200, Train Loss: 1.707, Val f1_micro: 0.213
Epoch: 220, Train Loss: 1.692, Val f1_micro: 0.221
Epoch: 240, Train Loss: 1.702, Val f1_micro: 0.212
Epoch: 260, Train Loss: 1.716, Val f1_micro: 0.225
Epoch: 280, Train Loss: 1.709, Val f1_micro: 0.210
Epoch: 300, Train Loss: 1.704, Val f1_micro: 0.204
Epoch: 320, Train Loss: 1.710, Val f1_micro: 0.213
Epoch: 340, Train Loss: 1.718, Val f1_micro: 0.213
Epoch: 360, Train Loss: 1.700, Val f1_micro: 0.209
Epoch: 380, Train Loss: 1.713, Val f1_micro: 0.213
Epoch: 400, Train Loss: 1.721, Val f1_micro: 0.209
Epoch: 420, Train Loss: 1.719, Val f1_micro: 0.207
Epoch: 440, Train Loss: 1.709, Val f1_micro: 0.200
Epoch: 460, Train Loss: 1.702, Val f1_micro: 0.210
Epoch: 480, Train Loss: 1.704, Val f1_micro: 0.210
Epoch: 500, Train Loss: 1.708, Val f1_micro: 0.212
f1-micro: 0.212, f1-macro: 0.179, f1-weighted: 0.180, , roc-auc: 0.634
##### RUN 3 #####
Epoch: 020, Train Loss: 1.881, Val f1_micro: 0.203
Epoch: 040, Train Loss: 1.716, Val f1_micro: 0.209
Epoch: 060, Train Loss: 1.665, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.650, Val f1_micro: 0.225
Epoch: 100, Train Loss: 1.667, Val f1_micro: 0.220
Epoch: 120, Train Loss: 1.673, Val f1_micro: 0.221
Epoch: 140, Train Loss: 1.667, Val f1_micro: 0.217
Epoch: 160, Train Loss: 1.680, Val f1_micro: 0.220
Epoch: 180, Train Loss: 1.672, Val f1_micro: 0.211
Epoch: 200, Train Loss: 1.693, Val f1_micro: 0.217
Epoch: 220, Train Loss: 1.700, Val f1_micro: 0.206
Epoch: 240, Train Loss: 1.690, Val f1_micro: 0.220
Epoch: 260, Train Loss: 1.711, Val f1_micro: 0.225
Epoch: 280, Train Loss: 1.711, Val f1_micro: 0.221
Epoch: 300, Train Loss: 1.699, Val f1_micro: 0.213
Epoch: 320, Train Loss: 1.706, Val f1_micro: 0.205
Epoch: 340, Train Loss: 1.708, Val f1_micro: 0.222
Epoch: 360, Train Loss: 1.707, Val f1_micro: 0.214
Epoch: 380, Train Loss: 1.707, Val f1_micro: 0.214
Epoch: 400, Train Loss: 1.709, Val f1_micro: 0.219
Epoch: 420, Train Loss: 1.701, Val f1_micro: 0.217
Epoch: 440, Train Loss: 1.707, Val f1_micro: 0.209
Epoch: 460, Train Loss: 1.711, Val f1_micro: 0.213
Epoch: 480, Train Loss: 1.709, Val f1_micro: 0.205
Epoch: 500, Train Loss: 1.714, Val f1_micro: 0.217
f1-micro: 0.217, f1-macro: 0.181, f1-weighted: 0.182, , roc-auc: 0.634
##### RUN 4 #####
Epoch: 020, Train Loss: 1.892, Val f1_micro: 0.195
Epoch: 040, Train Loss: 1.715, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.670, Val f1_micro: 0.215
Epoch: 080, Train Loss: 1.660, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.648, Val f1_micro: 0.217
Epoch: 120, Train Loss: 1.679, Val f1_micro: 0.220
Epoch: 140, Train Loss: 1.658, Val f1_micro: 0.206
Epoch: 160, Train Loss: 1.689, Val f1_micro: 0.214
Epoch: 180, Train Loss: 1.683, Val f1_micro: 0.216
Epoch: 200, Train Loss: 1.701, Val f1_micro: 0.220
Epoch: 220, Train Loss: 1.692, Val f1_micro: 0.225
Epoch: 240, Train Loss: 1.706, Val f1_micro: 0.220
Epoch: 260, Train Loss: 1.696, Val f1_micro: 0.212
Epoch: 280, Train Loss: 1.699, Val f1_micro: 0.216
Epoch: 300, Train Loss: 1.705, Val f1_micro: 0.211
Epoch: 320, Train Loss: 1.698, Val f1_micro: 0.222
Epoch: 340, Train Loss: 1.711, Val f1_micro: 0.214
Epoch: 360, Train Loss: 1.710, Val f1_micro: 0.207
Epoch: 380, Train Loss: 1.708, Val f1_micro: 0.214
Epoch: 400, Train Loss: 1.701, Val f1_micro: 0.212
Epoch: 420, Train Loss: 1.715, Val f1_micro: 0.219
Epoch: 440, Train Loss: 1.711, Val f1_micro: 0.215
Epoch: 460, Train Loss: 1.710, Val f1_micro: 0.205
Epoch: 480, Train Loss: 1.716, Val f1_micro: 0.214
Epoch: 500, Train Loss: 1.708, Val f1_micro: 0.208
f1-micro: 0.208, f1-macro: 0.170, f1-weighted: 0.172, , roc-auc: 0.636
##### RUN 5 #####
Epoch: 020, Train Loss: 1.887, Val f1_micro: 0.196
Epoch: 040, Train Loss: 1.707, Val f1_micro: 0.206
Epoch: 060, Train Loss: 1.676, Val f1_micro: 0.224
Epoch: 080, Train Loss: 1.657, Val f1_micro: 0.215
Epoch: 100, Train Loss: 1.659, Val f1_micro: 0.215
Epoch: 120, Train Loss: 1.679, Val f1_micro: 0.217
Epoch: 140, Train Loss: 1.662, Val f1_micro: 0.220
Epoch: 160, Train Loss: 1.685, Val f1_micro: 0.215
Epoch: 180, Train Loss: 1.693, Val f1_micro: 0.219
Epoch: 200, Train Loss: 1.692, Val f1_micro: 0.211
Epoch: 220, Train Loss: 1.693, Val f1_micro: 0.212
Epoch: 240, Train Loss: 1.697, Val f1_micro: 0.222
Epoch: 260, Train Loss: 1.718, Val f1_micro: 0.212
Epoch: 280, Train Loss: 1.708, Val f1_micro: 0.211
Epoch: 300, Train Loss: 1.697, Val f1_micro: 0.216
Epoch: 320, Train Loss: 1.708, Val f1_micro: 0.213
Epoch: 340, Train Loss: 1.700, Val f1_micro: 0.214
Epoch: 360, Train Loss: 1.717, Val f1_micro: 0.212
Epoch: 380, Train Loss: 1.705, Val f1_micro: 0.214
Epoch: 400, Train Loss: 1.709, Val f1_micro: 0.211
Epoch: 420, Train Loss: 1.709, Val f1_micro: 0.218
Epoch: 440, Train Loss: 1.700, Val f1_micro: 0.213
Epoch: 460, Train Loss: 1.700, Val f1_micro: 0.210
Epoch: 480, Train Loss: 1.694, Val f1_micro: 0.200
Epoch: 500, Train Loss: 1.706, Val f1_micro: 0.214
f1-micro: 0.214, f1-macro: 0.176, f1-weighted: 0.177, , roc-auc: 0.636
########## Hyperparameters combination ##########
(512, 0.6, 0.01, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.806, Val f1_micro: 0.186
Epoch: 040, Train Loss: 1.526, Val f1_micro: 0.233
Epoch: 060, Train Loss: 1.377, Val f1_micro: 0.248
Epoch: 080, Train Loss: 1.250, Val f1_micro: 0.264
Epoch: 100, Train Loss: 1.126, Val f1_micro: 0.269
Epoch: 120, Train Loss: 1.035, Val f1_micro: 0.273
Epoch: 140, Train Loss: 0.962, Val f1_micro: 0.277
Epoch: 160, Train Loss: 0.879, Val f1_micro: 0.280
Epoch: 180, Train Loss: 0.833, Val f1_micro: 0.289
Epoch: 200, Train Loss: 0.760, Val f1_micro: 0.289
Epoch: 220, Train Loss: 0.694, Val f1_micro: 0.295
Epoch: 240, Train Loss: 0.644, Val f1_micro: 0.300
Epoch: 260, Train Loss: 0.615, Val f1_micro: 0.295
Epoch: 280, Train Loss: 0.561, Val f1_micro: 0.303
Epoch: 300, Train Loss: 0.533, Val f1_micro: 0.300
Epoch: 320, Train Loss: 0.483, Val f1_micro: 0.304
Epoch: 340, Train Loss: 0.454, Val f1_micro: 0.302
Epoch: 360, Train Loss: 0.449, Val f1_micro: 0.307
Epoch: 380, Train Loss: 0.425, Val f1_micro: 0.310
Epoch: 400, Train Loss: 0.387, Val f1_micro: 0.306
Epoch: 420, Train Loss: 0.390, Val f1_micro: 0.306
Epoch: 440, Train Loss: 0.367, Val f1_micro: 0.307
Epoch: 460, Train Loss: 0.352, Val f1_micro: 0.306
Epoch: 480, Train Loss: 0.348, Val f1_micro: 0.307
Epoch: 500, Train Loss: 0.337, Val f1_micro: 0.306
f1-micro: 0.306, f1-macro: 0.300, f1-weighted: 0.307, , roc-auc: 0.672
##### RUN 2 #####
Epoch: 020, Train Loss: 1.780, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.502, Val f1_micro: 0.226
Epoch: 060, Train Loss: 1.358, Val f1_micro: 0.249
Epoch: 080, Train Loss: 1.234, Val f1_micro: 0.260
Epoch: 100, Train Loss: 1.110, Val f1_micro: 0.269
Epoch: 120, Train Loss: 1.038, Val f1_micro: 0.275
Epoch: 140, Train Loss: 0.937, Val f1_micro: 0.279
Epoch: 160, Train Loss: 0.872, Val f1_micro: 0.285
Epoch: 180, Train Loss: 0.818, Val f1_micro: 0.284
Epoch: 200, Train Loss: 0.745, Val f1_micro: 0.289
Epoch: 220, Train Loss: 0.696, Val f1_micro: 0.294
Epoch: 240, Train Loss: 0.638, Val f1_micro: 0.299
Epoch: 260, Train Loss: 0.618, Val f1_micro: 0.302
Epoch: 280, Train Loss: 0.553, Val f1_micro: 0.303
Epoch: 300, Train Loss: 0.525, Val f1_micro: 0.302
Epoch: 320, Train Loss: 0.485, Val f1_micro: 0.307
Epoch: 340, Train Loss: 0.479, Val f1_micro: 0.303
Epoch: 360, Train Loss: 0.421, Val f1_micro: 0.306
Epoch: 380, Train Loss: 0.410, Val f1_micro: 0.307
Epoch: 400, Train Loss: 0.402, Val f1_micro: 0.308
Epoch: 420, Train Loss: 0.365, Val f1_micro: 0.312
Epoch: 440, Train Loss: 0.356, Val f1_micro: 0.307
Epoch: 460, Train Loss: 0.341, Val f1_micro: 0.309
Epoch: 480, Train Loss: 0.348, Val f1_micro: 0.309
Epoch: 500, Train Loss: 0.314, Val f1_micro: 0.310
f1-micro: 0.310, f1-macro: 0.304, f1-weighted: 0.311, , roc-auc: 0.672
##### RUN 3 #####
Epoch: 020, Train Loss: 1.772, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.537, Val f1_micro: 0.230
Epoch: 060, Train Loss: 1.391, Val f1_micro: 0.244
Epoch: 080, Train Loss: 1.241, Val f1_micro: 0.254
Epoch: 100, Train Loss: 1.138, Val f1_micro: 0.267
Epoch: 120, Train Loss: 1.047, Val f1_micro: 0.276
Epoch: 140, Train Loss: 0.958, Val f1_micro: 0.280
Epoch: 160, Train Loss: 0.883, Val f1_micro: 0.287
Epoch: 180, Train Loss: 0.822, Val f1_micro: 0.284
Epoch: 200, Train Loss: 0.743, Val f1_micro: 0.291
Epoch: 220, Train Loss: 0.716, Val f1_micro: 0.302
Epoch: 240, Train Loss: 0.669, Val f1_micro: 0.298
Epoch: 260, Train Loss: 0.620, Val f1_micro: 0.306
Epoch: 280, Train Loss: 0.579, Val f1_micro: 0.302
Epoch: 300, Train Loss: 0.537, Val f1_micro: 0.307
Epoch: 320, Train Loss: 0.514, Val f1_micro: 0.308
Epoch: 340, Train Loss: 0.474, Val f1_micro: 0.307
Epoch: 360, Train Loss: 0.424, Val f1_micro: 0.309
Epoch: 380, Train Loss: 0.435, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.394, Val f1_micro: 0.308
Epoch: 420, Train Loss: 0.398, Val f1_micro: 0.305
Epoch: 440, Train Loss: 0.378, Val f1_micro: 0.308
Epoch: 460, Train Loss: 0.356, Val f1_micro: 0.307
Epoch: 480, Train Loss: 0.346, Val f1_micro: 0.307
Epoch: 500, Train Loss: 0.321, Val f1_micro: 0.305
f1-micro: 0.305, f1-macro: 0.301, f1-weighted: 0.307, , roc-auc: 0.673
##### RUN 4 #####
Epoch: 020, Train Loss: 1.772, Val f1_micro: 0.200
Epoch: 040, Train Loss: 1.555, Val f1_micro: 0.223
Epoch: 060, Train Loss: 1.362, Val f1_micro: 0.242
Epoch: 080, Train Loss: 1.241, Val f1_micro: 0.255
Epoch: 100, Train Loss: 1.141, Val f1_micro: 0.264
Epoch: 120, Train Loss: 1.050, Val f1_micro: 0.273
Epoch: 140, Train Loss: 0.984, Val f1_micro: 0.278
Epoch: 160, Train Loss: 0.901, Val f1_micro: 0.284
Epoch: 180, Train Loss: 0.835, Val f1_micro: 0.288
Epoch: 200, Train Loss: 0.749, Val f1_micro: 0.291
Epoch: 220, Train Loss: 0.724, Val f1_micro: 0.296
Epoch: 240, Train Loss: 0.673, Val f1_micro: 0.298
Epoch: 260, Train Loss: 0.642, Val f1_micro: 0.296
Epoch: 280, Train Loss: 0.589, Val f1_micro: 0.301
Epoch: 300, Train Loss: 0.549, Val f1_micro: 0.308
Epoch: 320, Train Loss: 0.510, Val f1_micro: 0.304
Epoch: 340, Train Loss: 0.482, Val f1_micro: 0.305
Epoch: 360, Train Loss: 0.434, Val f1_micro: 0.305
Epoch: 380, Train Loss: 0.443, Val f1_micro: 0.305
Epoch: 400, Train Loss: 0.404, Val f1_micro: 0.306
Epoch: 420, Train Loss: 0.400, Val f1_micro: 0.306
Epoch: 440, Train Loss: 0.370, Val f1_micro: 0.310
Epoch: 460, Train Loss: 0.372, Val f1_micro: 0.305
Epoch: 480, Train Loss: 0.364, Val f1_micro: 0.307
Epoch: 500, Train Loss: 0.342, Val f1_micro: 0.306
f1-micro: 0.306, f1-macro: 0.301, f1-weighted: 0.308, , roc-auc: 0.671
##### RUN 5 #####
Epoch: 020, Train Loss: 1.804, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.542, Val f1_micro: 0.220
Epoch: 060, Train Loss: 1.376, Val f1_micro: 0.242
Epoch: 080, Train Loss: 1.258, Val f1_micro: 0.253
Epoch: 100, Train Loss: 1.141, Val f1_micro: 0.268
Epoch: 120, Train Loss: 1.029, Val f1_micro: 0.272
Epoch: 140, Train Loss: 1.009, Val f1_micro: 0.282
Epoch: 160, Train Loss: 0.912, Val f1_micro: 0.280
Epoch: 180, Train Loss: 0.828, Val f1_micro: 0.284
Epoch: 200, Train Loss: 0.779, Val f1_micro: 0.292
Epoch: 220, Train Loss: 0.701, Val f1_micro: 0.298
Epoch: 240, Train Loss: 0.661, Val f1_micro: 0.295
Epoch: 260, Train Loss: 0.630, Val f1_micro: 0.301
Epoch: 280, Train Loss: 0.547, Val f1_micro: 0.300
Epoch: 300, Train Loss: 0.552, Val f1_micro: 0.302
Epoch: 320, Train Loss: 0.503, Val f1_micro: 0.301
Epoch: 340, Train Loss: 0.485, Val f1_micro: 0.304
Epoch: 360, Train Loss: 0.451, Val f1_micro: 0.303
Epoch: 380, Train Loss: 0.441, Val f1_micro: 0.305
Epoch: 400, Train Loss: 0.405, Val f1_micro: 0.304
Epoch: 420, Train Loss: 0.387, Val f1_micro: 0.305
Epoch: 440, Train Loss: 0.367, Val f1_micro: 0.303
Epoch: 460, Train Loss: 0.356, Val f1_micro: 0.304
Epoch: 480, Train Loss: 0.346, Val f1_micro: 0.304
Epoch: 500, Train Loss: 0.347, Val f1_micro: 0.307
f1-micro: 0.307, f1-macro: 0.301, f1-weighted: 0.307, , roc-auc: 0.675
########## Hyperparameters combination ##########
(512, 0.6, 0.01, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.825, Val f1_micro: 0.199
Epoch: 040, Train Loss: 1.535, Val f1_micro: 0.235
Epoch: 060, Train Loss: 1.400, Val f1_micro: 0.253
Epoch: 080, Train Loss: 1.328, Val f1_micro: 0.259
Epoch: 100, Train Loss: 1.219, Val f1_micro: 0.262
Epoch: 120, Train Loss: 1.153, Val f1_micro: 0.268
Epoch: 140, Train Loss: 1.124, Val f1_micro: 0.271
Epoch: 160, Train Loss: 1.063, Val f1_micro: 0.277
Epoch: 180, Train Loss: 1.023, Val f1_micro: 0.276
Epoch: 200, Train Loss: 0.959, Val f1_micro: 0.281
Epoch: 220, Train Loss: 0.942, Val f1_micro: 0.279
Epoch: 240, Train Loss: 0.898, Val f1_micro: 0.285
Epoch: 260, Train Loss: 0.874, Val f1_micro: 0.290
Epoch: 280, Train Loss: 0.863, Val f1_micro: 0.296
Epoch: 300, Train Loss: 0.829, Val f1_micro: 0.292
Epoch: 320, Train Loss: 0.807, Val f1_micro: 0.287
Epoch: 340, Train Loss: 0.778, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.775, Val f1_micro: 0.296
Epoch: 380, Train Loss: 0.753, Val f1_micro: 0.294
Epoch: 400, Train Loss: 0.719, Val f1_micro: 0.299
Epoch: 420, Train Loss: 0.702, Val f1_micro: 0.299
Epoch: 440, Train Loss: 0.725, Val f1_micro: 0.299
Epoch: 460, Train Loss: 0.688, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.687, Val f1_micro: 0.301
Epoch: 500, Train Loss: 0.680, Val f1_micro: 0.299
f1-micro: 0.299, f1-macro: 0.292, f1-weighted: 0.298, , roc-auc: 0.669
##### RUN 2 #####
Epoch: 020, Train Loss: 1.781, Val f1_micro: 0.201
Epoch: 040, Train Loss: 1.558, Val f1_micro: 0.237
Epoch: 060, Train Loss: 1.404, Val f1_micro: 0.249
Epoch: 080, Train Loss: 1.327, Val f1_micro: 0.260
Epoch: 100, Train Loss: 1.246, Val f1_micro: 0.265
Epoch: 120, Train Loss: 1.184, Val f1_micro: 0.266
Epoch: 140, Train Loss: 1.090, Val f1_micro: 0.271
Epoch: 160, Train Loss: 1.078, Val f1_micro: 0.271
Epoch: 180, Train Loss: 1.010, Val f1_micro: 0.278
Epoch: 200, Train Loss: 0.987, Val f1_micro: 0.286
Epoch: 220, Train Loss: 0.941, Val f1_micro: 0.288
Epoch: 240, Train Loss: 0.911, Val f1_micro: 0.285
Epoch: 260, Train Loss: 0.881, Val f1_micro: 0.288
Epoch: 280, Train Loss: 0.842, Val f1_micro: 0.294
Epoch: 300, Train Loss: 0.822, Val f1_micro: 0.293
Epoch: 320, Train Loss: 0.781, Val f1_micro: 0.297
Epoch: 340, Train Loss: 0.777, Val f1_micro: 0.293
Epoch: 360, Train Loss: 0.763, Val f1_micro: 0.294
Epoch: 380, Train Loss: 0.743, Val f1_micro: 0.299
Epoch: 400, Train Loss: 0.716, Val f1_micro: 0.299
Epoch: 420, Train Loss: 0.716, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.691, Val f1_micro: 0.304
Epoch: 460, Train Loss: 0.694, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.666, Val f1_micro: 0.301
Epoch: 500, Train Loss: 0.669, Val f1_micro: 0.305
f1-micro: 0.305, f1-macro: 0.297, f1-weighted: 0.303, , roc-auc: 0.667
##### RUN 3 #####
Epoch: 020, Train Loss: 1.805, Val f1_micro: 0.199
Epoch: 040, Train Loss: 1.589, Val f1_micro: 0.222
Epoch: 060, Train Loss: 1.449, Val f1_micro: 0.244
Epoch: 080, Train Loss: 1.346, Val f1_micro: 0.258
Epoch: 100, Train Loss: 1.272, Val f1_micro: 0.264
Epoch: 120, Train Loss: 1.183, Val f1_micro: 0.271
Epoch: 140, Train Loss: 1.124, Val f1_micro: 0.268
Epoch: 160, Train Loss: 1.081, Val f1_micro: 0.276
Epoch: 180, Train Loss: 1.034, Val f1_micro: 0.276
Epoch: 200, Train Loss: 1.012, Val f1_micro: 0.278
Epoch: 220, Train Loss: 0.962, Val f1_micro: 0.280
Epoch: 240, Train Loss: 0.935, Val f1_micro: 0.280
Epoch: 260, Train Loss: 0.917, Val f1_micro: 0.284
Epoch: 280, Train Loss: 0.878, Val f1_micro: 0.286
Epoch: 300, Train Loss: 0.837, Val f1_micro: 0.291
Epoch: 320, Train Loss: 0.796, Val f1_micro: 0.291
Epoch: 340, Train Loss: 0.804, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.780, Val f1_micro: 0.297
Epoch: 380, Train Loss: 0.759, Val f1_micro: 0.297
Epoch: 400, Train Loss: 0.771, Val f1_micro: 0.293
Epoch: 420, Train Loss: 0.742, Val f1_micro: 0.301
Epoch: 440, Train Loss: 0.729, Val f1_micro: 0.291
Epoch: 460, Train Loss: 0.705, Val f1_micro: 0.291
Epoch: 480, Train Loss: 0.678, Val f1_micro: 0.298
Epoch: 500, Train Loss: 0.695, Val f1_micro: 0.298
f1-micro: 0.298, f1-macro: 0.291, f1-weighted: 0.297, , roc-auc: 0.668
##### RUN 4 #####
Epoch: 020, Train Loss: 1.789, Val f1_micro: 0.204
Epoch: 040, Train Loss: 1.560, Val f1_micro: 0.237
Epoch: 060, Train Loss: 1.399, Val f1_micro: 0.251
Epoch: 080, Train Loss: 1.307, Val f1_micro: 0.262
Epoch: 100, Train Loss: 1.218, Val f1_micro: 0.264
Epoch: 120, Train Loss: 1.170, Val f1_micro: 0.269
Epoch: 140, Train Loss: 1.104, Val f1_micro: 0.275
Epoch: 160, Train Loss: 1.047, Val f1_micro: 0.276
Epoch: 180, Train Loss: 1.003, Val f1_micro: 0.280
Epoch: 200, Train Loss: 0.979, Val f1_micro: 0.282
Epoch: 220, Train Loss: 0.914, Val f1_micro: 0.281
Epoch: 240, Train Loss: 0.893, Val f1_micro: 0.283
Epoch: 260, Train Loss: 0.877, Val f1_micro: 0.280
Epoch: 280, Train Loss: 0.849, Val f1_micro: 0.287
Epoch: 300, Train Loss: 0.810, Val f1_micro: 0.290
Epoch: 320, Train Loss: 0.792, Val f1_micro: 0.292
Epoch: 340, Train Loss: 0.758, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.781, Val f1_micro: 0.298
Epoch: 380, Train Loss: 0.750, Val f1_micro: 0.293
Epoch: 400, Train Loss: 0.727, Val f1_micro: 0.299
Epoch: 420, Train Loss: 0.713, Val f1_micro: 0.294
Epoch: 440, Train Loss: 0.687, Val f1_micro: 0.301
Epoch: 460, Train Loss: 0.682, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.669, Val f1_micro: 0.300
Epoch: 500, Train Loss: 0.660, Val f1_micro: 0.300
f1-micro: 0.300, f1-macro: 0.292, f1-weighted: 0.299, , roc-auc: 0.668
##### RUN 5 #####
Epoch: 020, Train Loss: 1.816, Val f1_micro: 0.201
Epoch: 040, Train Loss: 1.553, Val f1_micro: 0.241
Epoch: 060, Train Loss: 1.408, Val f1_micro: 0.255
Epoch: 080, Train Loss: 1.320, Val f1_micro: 0.261
Epoch: 100, Train Loss: 1.231, Val f1_micro: 0.266
Epoch: 120, Train Loss: 1.166, Val f1_micro: 0.270
Epoch: 140, Train Loss: 1.108, Val f1_micro: 0.273
Epoch: 160, Train Loss: 1.059, Val f1_micro: 0.277
Epoch: 180, Train Loss: 1.008, Val f1_micro: 0.278
Epoch: 200, Train Loss: 0.971, Val f1_micro: 0.281
Epoch: 220, Train Loss: 0.941, Val f1_micro: 0.288
Epoch: 240, Train Loss: 0.899, Val f1_micro: 0.287
Epoch: 260, Train Loss: 0.870, Val f1_micro: 0.287
Epoch: 280, Train Loss: 0.865, Val f1_micro: 0.293
Epoch: 300, Train Loss: 0.815, Val f1_micro: 0.294
Epoch: 320, Train Loss: 0.784, Val f1_micro: 0.294
Epoch: 340, Train Loss: 0.780, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.755, Val f1_micro: 0.293
Epoch: 380, Train Loss: 0.728, Val f1_micro: 0.298
Epoch: 400, Train Loss: 0.719, Val f1_micro: 0.301
Epoch: 420, Train Loss: 0.689, Val f1_micro: 0.301
Epoch: 440, Train Loss: 0.681, Val f1_micro: 0.303
Epoch: 460, Train Loss: 0.675, Val f1_micro: 0.299
Epoch: 480, Train Loss: 0.674, Val f1_micro: 0.302
Epoch: 500, Train Loss: 0.664, Val f1_micro: 0.306
f1-micro: 0.306, f1-macro: 0.297, f1-weighted: 0.303, , roc-auc: 0.670
########## Hyperparameters combination ##########
(512, 0.6, 0.01, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.801, Val f1_micro: 0.203
Epoch: 040, Train Loss: 1.572, Val f1_micro: 0.230
Epoch: 060, Train Loss: 1.464, Val f1_micro: 0.242
Epoch: 080, Train Loss: 1.376, Val f1_micro: 0.245
Epoch: 100, Train Loss: 1.322, Val f1_micro: 0.258
Epoch: 120, Train Loss: 1.291, Val f1_micro: 0.258
Epoch: 140, Train Loss: 1.243, Val f1_micro: 0.265
Epoch: 160, Train Loss: 1.221, Val f1_micro: 0.265
Epoch: 180, Train Loss: 1.201, Val f1_micro: 0.265
Epoch: 200, Train Loss: 1.155, Val f1_micro: 0.270
Epoch: 220, Train Loss: 1.109, Val f1_micro: 0.268
Epoch: 240, Train Loss: 1.128, Val f1_micro: 0.267
Epoch: 260, Train Loss: 1.103, Val f1_micro: 0.273
Epoch: 280, Train Loss: 1.071, Val f1_micro: 0.275
Epoch: 300, Train Loss: 1.042, Val f1_micro: 0.282
Epoch: 320, Train Loss: 1.038, Val f1_micro: 0.280
Epoch: 340, Train Loss: 1.027, Val f1_micro: 0.281
Epoch: 360, Train Loss: 1.023, Val f1_micro: 0.280
Epoch: 380, Train Loss: 0.999, Val f1_micro: 0.286
Epoch: 400, Train Loss: 0.987, Val f1_micro: 0.281
Epoch: 420, Train Loss: 0.973, Val f1_micro: 0.282
Epoch: 440, Train Loss: 0.979, Val f1_micro: 0.286
Epoch: 460, Train Loss: 0.964, Val f1_micro: 0.286
Epoch: 480, Train Loss: 0.957, Val f1_micro: 0.282
Epoch: 500, Train Loss: 0.952, Val f1_micro: 0.287
f1-micro: 0.287, f1-macro: 0.275, f1-weighted: 0.281, , roc-auc: 0.660
##### RUN 2 #####
Epoch: 020, Train Loss: 1.818, Val f1_micro: 0.205
Epoch: 040, Train Loss: 1.577, Val f1_micro: 0.228
Epoch: 060, Train Loss: 1.471, Val f1_micro: 0.244
Epoch: 080, Train Loss: 1.392, Val f1_micro: 0.250
Epoch: 100, Train Loss: 1.336, Val f1_micro: 0.253
Epoch: 120, Train Loss: 1.301, Val f1_micro: 0.258
Epoch: 140, Train Loss: 1.241, Val f1_micro: 0.262
Epoch: 160, Train Loss: 1.214, Val f1_micro: 0.262
Epoch: 180, Train Loss: 1.163, Val f1_micro: 0.264
Epoch: 200, Train Loss: 1.155, Val f1_micro: 0.264
Epoch: 220, Train Loss: 1.146, Val f1_micro: 0.265
Epoch: 240, Train Loss: 1.098, Val f1_micro: 0.274
Epoch: 260, Train Loss: 1.081, Val f1_micro: 0.271
Epoch: 280, Train Loss: 1.070, Val f1_micro: 0.276
Epoch: 300, Train Loss: 1.051, Val f1_micro: 0.280
Epoch: 320, Train Loss: 1.049, Val f1_micro: 0.279
Epoch: 340, Train Loss: 1.014, Val f1_micro: 0.285
Epoch: 360, Train Loss: 1.009, Val f1_micro: 0.279
Epoch: 380, Train Loss: 0.994, Val f1_micro: 0.276
Epoch: 400, Train Loss: 0.998, Val f1_micro: 0.283
Epoch: 420, Train Loss: 0.974, Val f1_micro: 0.278
Epoch: 440, Train Loss: 0.972, Val f1_micro: 0.285
Epoch: 460, Train Loss: 0.963, Val f1_micro: 0.280
Epoch: 480, Train Loss: 0.963, Val f1_micro: 0.286
Epoch: 500, Train Loss: 0.957, Val f1_micro: 0.282
f1-micro: 0.282, f1-macro: 0.273, f1-weighted: 0.277, , roc-auc: 0.662
##### RUN 3 #####
Epoch: 020, Train Loss: 1.823, Val f1_micro: 0.205
Epoch: 040, Train Loss: 1.589, Val f1_micro: 0.216
Epoch: 060, Train Loss: 1.481, Val f1_micro: 0.235
Epoch: 080, Train Loss: 1.394, Val f1_micro: 0.249
Epoch: 100, Train Loss: 1.325, Val f1_micro: 0.256
Epoch: 120, Train Loss: 1.305, Val f1_micro: 0.262
Epoch: 140, Train Loss: 1.260, Val f1_micro: 0.259
Epoch: 160, Train Loss: 1.221, Val f1_micro: 0.260
Epoch: 180, Train Loss: 1.192, Val f1_micro: 0.262
Epoch: 200, Train Loss: 1.155, Val f1_micro: 0.264
Epoch: 220, Train Loss: 1.141, Val f1_micro: 0.266
Epoch: 240, Train Loss: 1.122, Val f1_micro: 0.264
Epoch: 260, Train Loss: 1.098, Val f1_micro: 0.272
Epoch: 280, Train Loss: 1.089, Val f1_micro: 0.275
Epoch: 300, Train Loss: 1.051, Val f1_micro: 0.276
Epoch: 320, Train Loss: 1.051, Val f1_micro: 0.275
Epoch: 340, Train Loss: 1.035, Val f1_micro: 0.279
Epoch: 360, Train Loss: 1.023, Val f1_micro: 0.282
Epoch: 380, Train Loss: 0.992, Val f1_micro: 0.282
Epoch: 400, Train Loss: 0.990, Val f1_micro: 0.280
Epoch: 420, Train Loss: 0.986, Val f1_micro: 0.279
Epoch: 440, Train Loss: 0.990, Val f1_micro: 0.282
Epoch: 460, Train Loss: 0.987, Val f1_micro: 0.282
Epoch: 480, Train Loss: 0.987, Val f1_micro: 0.283
Epoch: 500, Train Loss: 0.961, Val f1_micro: 0.288
f1-micro: 0.288, f1-macro: 0.278, f1-weighted: 0.281, , roc-auc: 0.659
##### RUN 4 #####
Epoch: 020, Train Loss: 1.769, Val f1_micro: 0.199
Epoch: 040, Train Loss: 1.580, Val f1_micro: 0.233
Epoch: 060, Train Loss: 1.475, Val f1_micro: 0.245
Epoch: 080, Train Loss: 1.388, Val f1_micro: 0.249
Epoch: 100, Train Loss: 1.331, Val f1_micro: 0.248
Epoch: 120, Train Loss: 1.301, Val f1_micro: 0.250
Epoch: 140, Train Loss: 1.261, Val f1_micro: 0.264
Epoch: 160, Train Loss: 1.214, Val f1_micro: 0.260
Epoch: 180, Train Loss: 1.189, Val f1_micro: 0.269
Epoch: 200, Train Loss: 1.168, Val f1_micro: 0.263
Epoch: 220, Train Loss: 1.138, Val f1_micro: 0.265
Epoch: 240, Train Loss: 1.121, Val f1_micro: 0.268
Epoch: 260, Train Loss: 1.071, Val f1_micro: 0.276
Epoch: 280, Train Loss: 1.074, Val f1_micro: 0.271
Epoch: 300, Train Loss: 1.046, Val f1_micro: 0.280
Epoch: 320, Train Loss: 1.025, Val f1_micro: 0.277
Epoch: 340, Train Loss: 1.024, Val f1_micro: 0.278
Epoch: 360, Train Loss: 1.012, Val f1_micro: 0.279
Epoch: 380, Train Loss: 1.006, Val f1_micro: 0.282
Epoch: 400, Train Loss: 0.982, Val f1_micro: 0.283
Epoch: 420, Train Loss: 0.987, Val f1_micro: 0.276
Epoch: 440, Train Loss: 0.985, Val f1_micro: 0.284
Epoch: 460, Train Loss: 0.964, Val f1_micro: 0.284
Epoch: 480, Train Loss: 0.961, Val f1_micro: 0.282
Epoch: 500, Train Loss: 0.955, Val f1_micro: 0.285
f1-micro: 0.285, f1-macro: 0.275, f1-weighted: 0.280, , roc-auc: 0.660
##### RUN 5 #####
Epoch: 020, Train Loss: 1.802, Val f1_micro: 0.196
Epoch: 040, Train Loss: 1.570, Val f1_micro: 0.225
Epoch: 060, Train Loss: 1.478, Val f1_micro: 0.240
Epoch: 080, Train Loss: 1.381, Val f1_micro: 0.247
Epoch: 100, Train Loss: 1.333, Val f1_micro: 0.254
Epoch: 120, Train Loss: 1.291, Val f1_micro: 0.258
Epoch: 140, Train Loss: 1.249, Val f1_micro: 0.264
Epoch: 160, Train Loss: 1.207, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.190, Val f1_micro: 0.268
Epoch: 200, Train Loss: 1.171, Val f1_micro: 0.267
Epoch: 220, Train Loss: 1.114, Val f1_micro: 0.268
Epoch: 240, Train Loss: 1.105, Val f1_micro: 0.269
Epoch: 260, Train Loss: 1.080, Val f1_micro: 0.271
Epoch: 280, Train Loss: 1.071, Val f1_micro: 0.274
Epoch: 300, Train Loss: 1.063, Val f1_micro: 0.275
Epoch: 320, Train Loss: 1.043, Val f1_micro: 0.273
Epoch: 340, Train Loss: 1.030, Val f1_micro: 0.280
Epoch: 360, Train Loss: 1.020, Val f1_micro: 0.283
Epoch: 380, Train Loss: 1.011, Val f1_micro: 0.279
Epoch: 400, Train Loss: 0.999, Val f1_micro: 0.273
Epoch: 420, Train Loss: 0.989, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.966, Val f1_micro: 0.284
Epoch: 460, Train Loss: 0.971, Val f1_micro: 0.285
Epoch: 480, Train Loss: 0.955, Val f1_micro: 0.289
Epoch: 500, Train Loss: 0.969, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.271, f1-weighted: 0.274, , roc-auc: 0.658
########## Hyperparameters combination ##########
(512, 0.6, 0.01, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.852, Val f1_micro: 0.187
Epoch: 040, Train Loss: 1.727, Val f1_micro: 0.220
Epoch: 060, Train Loss: 1.717, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.706, Val f1_micro: 0.220
Epoch: 100, Train Loss: 1.713, Val f1_micro: 0.225
Epoch: 120, Train Loss: 1.717, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.713, Val f1_micro: 0.206
Epoch: 160, Train Loss: 1.718, Val f1_micro: 0.215
Epoch: 180, Train Loss: 1.721, Val f1_micro: 0.220
Epoch: 200, Train Loss: 1.719, Val f1_micro: 0.219
Epoch: 220, Train Loss: 1.711, Val f1_micro: 0.222
Epoch: 240, Train Loss: 1.715, Val f1_micro: 0.217
Epoch: 260, Train Loss: 1.707, Val f1_micro: 0.207
Epoch: 280, Train Loss: 1.713, Val f1_micro: 0.210
Epoch: 300, Train Loss: 1.721, Val f1_micro: 0.217
Epoch: 320, Train Loss: 1.731, Val f1_micro: 0.215
Epoch: 340, Train Loss: 1.719, Val f1_micro: 0.216
Epoch: 360, Train Loss: 1.729, Val f1_micro: 0.218
Epoch: 380, Train Loss: 1.709, Val f1_micro: 0.219
Epoch: 400, Train Loss: 1.721, Val f1_micro: 0.215
Epoch: 420, Train Loss: 1.725, Val f1_micro: 0.213
Epoch: 440, Train Loss: 1.715, Val f1_micro: 0.214
Epoch: 460, Train Loss: 1.726, Val f1_micro: 0.214
Epoch: 480, Train Loss: 1.715, Val f1_micro: 0.218
Epoch: 500, Train Loss: 1.724, Val f1_micro: 0.217
f1-micro: 0.217, f1-macro: 0.186, f1-weighted: 0.189, , roc-auc: 0.633
##### RUN 2 #####
Epoch: 020, Train Loss: 1.818, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.718, Val f1_micro: 0.224
Epoch: 060, Train Loss: 1.699, Val f1_micro: 0.223
Epoch: 080, Train Loss: 1.707, Val f1_micro: 0.212
Epoch: 100, Train Loss: 1.700, Val f1_micro: 0.221
Epoch: 120, Train Loss: 1.704, Val f1_micro: 0.223
Epoch: 140, Train Loss: 1.728, Val f1_micro: 0.221
Epoch: 160, Train Loss: 1.727, Val f1_micro: 0.206
Epoch: 180, Train Loss: 1.733, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.718, Val f1_micro: 0.220
Epoch: 220, Train Loss: 1.731, Val f1_micro: 0.209
Epoch: 240, Train Loss: 1.726, Val f1_micro: 0.213
Epoch: 260, Train Loss: 1.723, Val f1_micro: 0.219
Epoch: 280, Train Loss: 1.715, Val f1_micro: 0.205
Epoch: 300, Train Loss: 1.736, Val f1_micro: 0.214
Epoch: 320, Train Loss: 1.730, Val f1_micro: 0.216
Epoch: 340, Train Loss: 1.729, Val f1_micro: 0.223
Epoch: 360, Train Loss: 1.722, Val f1_micro: 0.201
Epoch: 380, Train Loss: 1.719, Val f1_micro: 0.219
Epoch: 400, Train Loss: 1.724, Val f1_micro: 0.220
Epoch: 420, Train Loss: 1.705, Val f1_micro: 0.204
Epoch: 440, Train Loss: 1.712, Val f1_micro: 0.208
Epoch: 460, Train Loss: 1.722, Val f1_micro: 0.211
Epoch: 480, Train Loss: 1.727, Val f1_micro: 0.210
Epoch: 500, Train Loss: 1.724, Val f1_micro: 0.218
f1-micro: 0.218, f1-macro: 0.182, f1-weighted: 0.185, , roc-auc: 0.632
##### RUN 3 #####
Epoch: 020, Train Loss: 1.828, Val f1_micro: 0.200
Epoch: 040, Train Loss: 1.742, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.703, Val f1_micro: 0.216
Epoch: 080, Train Loss: 1.701, Val f1_micro: 0.212
Epoch: 100, Train Loss: 1.711, Val f1_micro: 0.219
Epoch: 120, Train Loss: 1.712, Val f1_micro: 0.217
Epoch: 140, Train Loss: 1.717, Val f1_micro: 0.221
Epoch: 160, Train Loss: 1.736, Val f1_micro: 0.218
Epoch: 180, Train Loss: 1.716, Val f1_micro: 0.216
Epoch: 200, Train Loss: 1.735, Val f1_micro: 0.212
Epoch: 220, Train Loss: 1.719, Val f1_micro: 0.221
Epoch: 240, Train Loss: 1.719, Val f1_micro: 0.221
Epoch: 260, Train Loss: 1.720, Val f1_micro: 0.216
Epoch: 280, Train Loss: 1.720, Val f1_micro: 0.220
Epoch: 300, Train Loss: 1.710, Val f1_micro: 0.222
Epoch: 320, Train Loss: 1.713, Val f1_micro: 0.228
Epoch: 340, Train Loss: 1.723, Val f1_micro: 0.208
Epoch: 360, Train Loss: 1.733, Val f1_micro: 0.219
Epoch: 380, Train Loss: 1.717, Val f1_micro: 0.211
Epoch: 400, Train Loss: 1.713, Val f1_micro: 0.215
Epoch: 420, Train Loss: 1.717, Val f1_micro: 0.211
Epoch: 440, Train Loss: 1.725, Val f1_micro: 0.213
Epoch: 460, Train Loss: 1.720, Val f1_micro: 0.211
Epoch: 480, Train Loss: 1.713, Val f1_micro: 0.215
Epoch: 500, Train Loss: 1.722, Val f1_micro: 0.213
f1-micro: 0.213, f1-macro: 0.179, f1-weighted: 0.180, , roc-auc: 0.633
##### RUN 4 #####
Epoch: 020, Train Loss: 1.851, Val f1_micro: 0.173
Epoch: 040, Train Loss: 1.716, Val f1_micro: 0.221
Epoch: 060, Train Loss: 1.707, Val f1_micro: 0.227
Epoch: 080, Train Loss: 1.689, Val f1_micro: 0.218
Epoch: 100, Train Loss: 1.726, Val f1_micro: 0.223
Epoch: 120, Train Loss: 1.702, Val f1_micro: 0.223
Epoch: 140, Train Loss: 1.714, Val f1_micro: 0.219
Epoch: 160, Train Loss: 1.724, Val f1_micro: 0.223
Epoch: 180, Train Loss: 1.723, Val f1_micro: 0.221
Epoch: 200, Train Loss: 1.722, Val f1_micro: 0.213
Epoch: 220, Train Loss: 1.718, Val f1_micro: 0.213
Epoch: 240, Train Loss: 1.718, Val f1_micro: 0.213
Epoch: 260, Train Loss: 1.728, Val f1_micro: 0.223
Epoch: 280, Train Loss: 1.725, Val f1_micro: 0.214
Epoch: 300, Train Loss: 1.735, Val f1_micro: 0.219
Epoch: 320, Train Loss: 1.723, Val f1_micro: 0.217
Epoch: 340, Train Loss: 1.714, Val f1_micro: 0.206
Epoch: 360, Train Loss: 1.713, Val f1_micro: 0.222
Epoch: 380, Train Loss: 1.725, Val f1_micro: 0.218
Epoch: 400, Train Loss: 1.715, Val f1_micro: 0.221
Epoch: 420, Train Loss: 1.715, Val f1_micro: 0.220
Epoch: 440, Train Loss: 1.721, Val f1_micro: 0.215
Epoch: 460, Train Loss: 1.711, Val f1_micro: 0.218
Epoch: 480, Train Loss: 1.707, Val f1_micro: 0.222
Epoch: 500, Train Loss: 1.711, Val f1_micro: 0.209
f1-micro: 0.209, f1-macro: 0.179, f1-weighted: 0.178, , roc-auc: 0.631
##### RUN 5 #####
Epoch: 020, Train Loss: 1.831, Val f1_micro: 0.197
Epoch: 040, Train Loss: 1.741, Val f1_micro: 0.223
Epoch: 060, Train Loss: 1.704, Val f1_micro: 0.211
Epoch: 080, Train Loss: 1.705, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.707, Val f1_micro: 0.221
Epoch: 120, Train Loss: 1.715, Val f1_micro: 0.217
Epoch: 140, Train Loss: 1.716, Val f1_micro: 0.215
Epoch: 160, Train Loss: 1.706, Val f1_micro: 0.215
Epoch: 180, Train Loss: 1.730, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.729, Val f1_micro: 0.208
Epoch: 220, Train Loss: 1.725, Val f1_micro: 0.212
Epoch: 240, Train Loss: 1.736, Val f1_micro: 0.215
Epoch: 260, Train Loss: 1.720, Val f1_micro: 0.212
Epoch: 280, Train Loss: 1.731, Val f1_micro: 0.210
Epoch: 300, Train Loss: 1.714, Val f1_micro: 0.220
Epoch: 320, Train Loss: 1.723, Val f1_micro: 0.217
Epoch: 340, Train Loss: 1.732, Val f1_micro: 0.218
Epoch: 360, Train Loss: 1.717, Val f1_micro: 0.215
Epoch: 380, Train Loss: 1.721, Val f1_micro: 0.213
Epoch: 400, Train Loss: 1.721, Val f1_micro: 0.211
Epoch: 420, Train Loss: 1.716, Val f1_micro: 0.216
Epoch: 440, Train Loss: 1.721, Val f1_micro: 0.218
Epoch: 460, Train Loss: 1.717, Val f1_micro: 0.211
Epoch: 480, Train Loss: 1.720, Val f1_micro: 0.209
Epoch: 500, Train Loss: 1.716, Val f1_micro: 0.210
f1-micro: 0.210, f1-macro: 0.172, f1-weighted: 0.175, , roc-auc: 0.635
########## Hyperparameters combination ##########
(512, 0.6, 0.05, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.052, Val f1_micro: 0.143
Epoch: 040, Train Loss: 1.986, Val f1_micro: 0.157
Epoch: 060, Train Loss: 1.921, Val f1_micro: 0.122
Epoch: 080, Train Loss: 1.855, Val f1_micro: 0.129
Epoch: 100, Train Loss: 1.794, Val f1_micro: 0.137
Epoch: 120, Train Loss: 1.729, Val f1_micro: 0.158
Epoch: 140, Train Loss: 1.631, Val f1_micro: 0.175
Epoch: 160, Train Loss: 1.540, Val f1_micro: 0.197
Epoch: 180, Train Loss: 1.447, Val f1_micro: 0.194
Epoch: 200, Train Loss: 1.367, Val f1_micro: 0.192
Epoch: 220, Train Loss: 1.321, Val f1_micro: 0.216
Epoch: 240, Train Loss: 1.252, Val f1_micro: 0.213
Epoch: 260, Train Loss: 1.215, Val f1_micro: 0.219
Epoch: 280, Train Loss: 1.223, Val f1_micro: 0.224
Epoch: 300, Train Loss: 1.093, Val f1_micro: 0.235
Epoch: 320, Train Loss: 1.072, Val f1_micro: 0.240
Epoch: 340, Train Loss: 1.024, Val f1_micro: 0.237
Epoch: 360, Train Loss: 1.010, Val f1_micro: 0.254
Epoch: 380, Train Loss: 0.966, Val f1_micro: 0.251
Epoch: 400, Train Loss: 0.940, Val f1_micro: 0.254
Epoch: 420, Train Loss: 0.914, Val f1_micro: 0.256
Epoch: 440, Train Loss: 0.854, Val f1_micro: 0.263
Epoch: 460, Train Loss: 0.854, Val f1_micro: 0.263
Epoch: 480, Train Loss: 0.812, Val f1_micro: 0.261
Epoch: 500, Train Loss: 0.787, Val f1_micro: 0.265
f1-micro: 0.265, f1-macro: 0.260, f1-weighted: 0.264, , roc-auc: 0.643
##### RUN 2 #####
Epoch: 020, Train Loss: 2.068, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.065, Val f1_micro: 0.162
Epoch: 060, Train Loss: 1.906, Val f1_micro: 0.119
Epoch: 080, Train Loss: 1.861, Val f1_micro: 0.128
Epoch: 100, Train Loss: 1.788, Val f1_micro: 0.138
Epoch: 120, Train Loss: 1.712, Val f1_micro: 0.143
Epoch: 140, Train Loss: 1.615, Val f1_micro: 0.165
Epoch: 160, Train Loss: 1.532, Val f1_micro: 0.181
Epoch: 180, Train Loss: 1.479, Val f1_micro: 0.193
Epoch: 200, Train Loss: 1.367, Val f1_micro: 0.204
Epoch: 220, Train Loss: 1.323, Val f1_micro: 0.208
Epoch: 240, Train Loss: 1.233, Val f1_micro: 0.220
Epoch: 260, Train Loss: 1.218, Val f1_micro: 0.218
Epoch: 280, Train Loss: 1.120, Val f1_micro: 0.229
Epoch: 300, Train Loss: 1.083, Val f1_micro: 0.233
Epoch: 320, Train Loss: 1.077, Val f1_micro: 0.233
Epoch: 340, Train Loss: 1.018, Val f1_micro: 0.241
Epoch: 360, Train Loss: 1.012, Val f1_micro: 0.242
Epoch: 380, Train Loss: 0.962, Val f1_micro: 0.238
Epoch: 400, Train Loss: 0.910, Val f1_micro: 0.246
Epoch: 420, Train Loss: 0.902, Val f1_micro: 0.251
Epoch: 440, Train Loss: 0.885, Val f1_micro: 0.248
Epoch: 460, Train Loss: 0.852, Val f1_micro: 0.250
Epoch: 480, Train Loss: 0.835, Val f1_micro: 0.261
Epoch: 500, Train Loss: 0.804, Val f1_micro: 0.267
f1-micro: 0.267, f1-macro: 0.262, f1-weighted: 0.266, , roc-auc: 0.636
##### RUN 3 #####
Epoch: 020, Train Loss: 2.055, Val f1_micro: 0.104
Epoch: 040, Train Loss: 1.970, Val f1_micro: 0.163
Epoch: 060, Train Loss: 1.937, Val f1_micro: 0.124
Epoch: 080, Train Loss: 1.849, Val f1_micro: 0.130
Epoch: 100, Train Loss: 1.774, Val f1_micro: 0.144
Epoch: 120, Train Loss: 1.694, Val f1_micro: 0.166
Epoch: 140, Train Loss: 1.587, Val f1_micro: 0.183
Epoch: 160, Train Loss: 1.560, Val f1_micro: 0.180
Epoch: 180, Train Loss: 1.490, Val f1_micro: 0.194
Epoch: 200, Train Loss: 1.432, Val f1_micro: 0.208
Epoch: 220, Train Loss: 1.387, Val f1_micro: 0.212
Epoch: 240, Train Loss: 1.298, Val f1_micro: 0.219
Epoch: 260, Train Loss: 1.299, Val f1_micro: 0.217
Epoch: 280, Train Loss: 1.213, Val f1_micro: 0.224
Epoch: 300, Train Loss: 1.174, Val f1_micro: 0.227
Epoch: 320, Train Loss: 1.152, Val f1_micro: 0.227
Epoch: 340, Train Loss: 1.097, Val f1_micro: 0.236
Epoch: 360, Train Loss: 1.055, Val f1_micro: 0.238
Epoch: 380, Train Loss: 1.030, Val f1_micro: 0.237
Epoch: 400, Train Loss: 0.994, Val f1_micro: 0.246
Epoch: 420, Train Loss: 0.966, Val f1_micro: 0.245
Epoch: 440, Train Loss: 0.935, Val f1_micro: 0.246
Epoch: 460, Train Loss: 0.908, Val f1_micro: 0.244
Epoch: 480, Train Loss: 0.884, Val f1_micro: 0.256
Epoch: 500, Train Loss: 0.891, Val f1_micro: 0.252
f1-micro: 0.252, f1-macro: 0.247, f1-weighted: 0.250, , roc-auc: 0.638
##### RUN 4 #####
Epoch: 020, Train Loss: 2.053, Val f1_micro: 0.144
Epoch: 040, Train Loss: 1.978, Val f1_micro: 0.152
Epoch: 060, Train Loss: 1.906, Val f1_micro: 0.118
Epoch: 080, Train Loss: 1.868, Val f1_micro: 0.126
Epoch: 100, Train Loss: 1.789, Val f1_micro: 0.133
Epoch: 120, Train Loss: 1.735, Val f1_micro: 0.139
Epoch: 140, Train Loss: 1.675, Val f1_micro: 0.145
Epoch: 160, Train Loss: 1.608, Val f1_micro: 0.156
Epoch: 180, Train Loss: 1.523, Val f1_micro: 0.174
Epoch: 200, Train Loss: 1.474, Val f1_micro: 0.182
Epoch: 220, Train Loss: 1.381, Val f1_micro: 0.201
Epoch: 240, Train Loss: 1.323, Val f1_micro: 0.214
Epoch: 260, Train Loss: 1.240, Val f1_micro: 0.215
Epoch: 280, Train Loss: 1.186, Val f1_micro: 0.222
Epoch: 300, Train Loss: 1.130, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.092, Val f1_micro: 0.230
Epoch: 340, Train Loss: 1.067, Val f1_micro: 0.236
Epoch: 360, Train Loss: 0.990, Val f1_micro: 0.236
Epoch: 380, Train Loss: 1.090, Val f1_micro: 0.242
Epoch: 400, Train Loss: 0.962, Val f1_micro: 0.237
Epoch: 420, Train Loss: 0.948, Val f1_micro: 0.245
Epoch: 440, Train Loss: 0.877, Val f1_micro: 0.253
Epoch: 460, Train Loss: 0.921, Val f1_micro: 0.253
Epoch: 480, Train Loss: 0.867, Val f1_micro: 0.257
Epoch: 500, Train Loss: 0.809, Val f1_micro: 0.253
f1-micro: 0.253, f1-macro: 0.249, f1-weighted: 0.252, , roc-auc: 0.637
##### RUN 5 #####
Epoch: 020, Train Loss: 2.080, Val f1_micro: 0.098
Epoch: 040, Train Loss: 1.991, Val f1_micro: 0.157
Epoch: 060, Train Loss: 1.934, Val f1_micro: 0.121
Epoch: 080, Train Loss: 1.864, Val f1_micro: 0.124
Epoch: 100, Train Loss: 1.794, Val f1_micro: 0.130
Epoch: 120, Train Loss: 1.731, Val f1_micro: 0.137
Epoch: 140, Train Loss: 1.680, Val f1_micro: 0.153
Epoch: 160, Train Loss: 1.619, Val f1_micro: 0.171
Epoch: 180, Train Loss: 1.533, Val f1_micro: 0.196
Epoch: 200, Train Loss: 1.449, Val f1_micro: 0.200
Epoch: 220, Train Loss: 1.409, Val f1_micro: 0.208
Epoch: 240, Train Loss: 1.322, Val f1_micro: 0.207
Epoch: 260, Train Loss: 1.261, Val f1_micro: 0.210
Epoch: 280, Train Loss: 1.228, Val f1_micro: 0.219
Epoch: 300, Train Loss: 1.167, Val f1_micro: 0.226
Epoch: 320, Train Loss: 1.138, Val f1_micro: 0.223
Epoch: 340, Train Loss: 1.073, Val f1_micro: 0.227
Epoch: 360, Train Loss: 1.055, Val f1_micro: 0.237
Epoch: 380, Train Loss: 1.090, Val f1_micro: 0.239
Epoch: 400, Train Loss: 0.998, Val f1_micro: 0.243
Epoch: 420, Train Loss: 0.936, Val f1_micro: 0.245
Epoch: 440, Train Loss: 0.951, Val f1_micro: 0.246
Epoch: 460, Train Loss: 0.917, Val f1_micro: 0.249
Epoch: 480, Train Loss: 0.900, Val f1_micro: 0.250
Epoch: 500, Train Loss: 0.844, Val f1_micro: 0.251
f1-micro: 0.251, f1-macro: 0.245, f1-weighted: 0.248, , roc-auc: 0.635
########## Hyperparameters combination ##########
(512, 0.6, 0.05, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.062, Val f1_micro: 0.139
Epoch: 040, Train Loss: 2.018, Val f1_micro: 0.163
Epoch: 060, Train Loss: 1.956, Val f1_micro: 0.119
Epoch: 080, Train Loss: 1.917, Val f1_micro: 0.171
Epoch: 100, Train Loss: 1.848, Val f1_micro: 0.162
Epoch: 120, Train Loss: 1.807, Val f1_micro: 0.172
Epoch: 140, Train Loss: 1.757, Val f1_micro: 0.168
Epoch: 160, Train Loss: 1.710, Val f1_micro: 0.183
Epoch: 180, Train Loss: 1.662, Val f1_micro: 0.193
Epoch: 200, Train Loss: 1.632, Val f1_micro: 0.195
Epoch: 220, Train Loss: 1.560, Val f1_micro: 0.193
Epoch: 240, Train Loss: 1.538, Val f1_micro: 0.205
Epoch: 260, Train Loss: 1.501, Val f1_micro: 0.204
Epoch: 280, Train Loss: 1.457, Val f1_micro: 0.211
Epoch: 300, Train Loss: 1.428, Val f1_micro: 0.214
Epoch: 320, Train Loss: 1.404, Val f1_micro: 0.220
Epoch: 340, Train Loss: 1.449, Val f1_micro: 0.215
Epoch: 360, Train Loss: 1.362, Val f1_micro: 0.228
Epoch: 380, Train Loss: 1.276, Val f1_micro: 0.230
Epoch: 400, Train Loss: 1.294, Val f1_micro: 0.228
Epoch: 420, Train Loss: 1.267, Val f1_micro: 0.235
Epoch: 440, Train Loss: 1.256, Val f1_micro: 0.237
Epoch: 460, Train Loss: 1.234, Val f1_micro: 0.236
Epoch: 480, Train Loss: 1.191, Val f1_micro: 0.242
Epoch: 500, Train Loss: 1.184, Val f1_micro: 0.248
f1-micro: 0.248, f1-macro: 0.236, f1-weighted: 0.237, , roc-auc: 0.640
##### RUN 2 #####
Epoch: 020, Train Loss: 2.088, Val f1_micro: 0.095
Epoch: 040, Train Loss: 2.002, Val f1_micro: 0.167
Epoch: 060, Train Loss: 1.983, Val f1_micro: 0.117
Epoch: 080, Train Loss: 1.957, Val f1_micro: 0.122
Epoch: 100, Train Loss: 1.937, Val f1_micro: 0.164
Epoch: 120, Train Loss: 1.837, Val f1_micro: 0.162
Epoch: 140, Train Loss: 1.792, Val f1_micro: 0.163
Epoch: 160, Train Loss: 1.721, Val f1_micro: 0.190
Epoch: 180, Train Loss: 1.657, Val f1_micro: 0.199
Epoch: 200, Train Loss: 1.611, Val f1_micro: 0.193
Epoch: 220, Train Loss: 1.553, Val f1_micro: 0.207
Epoch: 240, Train Loss: 1.497, Val f1_micro: 0.203
Epoch: 260, Train Loss: 1.472, Val f1_micro: 0.213
Epoch: 280, Train Loss: 1.396, Val f1_micro: 0.228
Epoch: 300, Train Loss: 1.414, Val f1_micro: 0.225
Epoch: 320, Train Loss: 1.376, Val f1_micro: 0.232
Epoch: 340, Train Loss: 1.324, Val f1_micro: 0.231
Epoch: 360, Train Loss: 1.304, Val f1_micro: 0.237
Epoch: 380, Train Loss: 1.329, Val f1_micro: 0.233
Epoch: 400, Train Loss: 1.275, Val f1_micro: 0.240
Epoch: 420, Train Loss: 1.255, Val f1_micro: 0.248
Epoch: 440, Train Loss: 1.209, Val f1_micro: 0.239
Epoch: 460, Train Loss: 1.182, Val f1_micro: 0.251
Epoch: 480, Train Loss: 1.163, Val f1_micro: 0.247
Epoch: 500, Train Loss: 1.165, Val f1_micro: 0.251
f1-micro: 0.251, f1-macro: 0.240, f1-weighted: 0.242, , roc-auc: 0.641
##### RUN 3 #####
Epoch: 020, Train Loss: 2.087, Val f1_micro: 0.099
Epoch: 040, Train Loss: 2.006, Val f1_micro: 0.163
Epoch: 060, Train Loss: 1.970, Val f1_micro: 0.124
Epoch: 080, Train Loss: 1.914, Val f1_micro: 0.134
Epoch: 100, Train Loss: 1.868, Val f1_micro: 0.162
Epoch: 120, Train Loss: 1.801, Val f1_micro: 0.183
Epoch: 140, Train Loss: 1.742, Val f1_micro: 0.189
Epoch: 160, Train Loss: 1.665, Val f1_micro: 0.201
Epoch: 180, Train Loss: 1.595, Val f1_micro: 0.201
Epoch: 200, Train Loss: 1.546, Val f1_micro: 0.209
Epoch: 220, Train Loss: 1.513, Val f1_micro: 0.210
Epoch: 240, Train Loss: 1.468, Val f1_micro: 0.214
Epoch: 260, Train Loss: 1.419, Val f1_micro: 0.220
Epoch: 280, Train Loss: 1.400, Val f1_micro: 0.216
Epoch: 300, Train Loss: 1.366, Val f1_micro: 0.223
Epoch: 320, Train Loss: 1.338, Val f1_micro: 0.221
Epoch: 340, Train Loss: 1.290, Val f1_micro: 0.231
Epoch: 360, Train Loss: 1.270, Val f1_micro: 0.236
Epoch: 380, Train Loss: 1.293, Val f1_micro: 0.227
Epoch: 400, Train Loss: 1.235, Val f1_micro: 0.239
Epoch: 420, Train Loss: 1.234, Val f1_micro: 0.240
Epoch: 440, Train Loss: 1.216, Val f1_micro: 0.236
Epoch: 460, Train Loss: 1.181, Val f1_micro: 0.250
Epoch: 480, Train Loss: 1.155, Val f1_micro: 0.253
Epoch: 500, Train Loss: 1.168, Val f1_micro: 0.252
f1-micro: 0.252, f1-macro: 0.243, f1-weighted: 0.245, , roc-auc: 0.642
##### RUN 4 #####
Epoch: 020, Train Loss: 2.078, Val f1_micro: 0.137
Epoch: 040, Train Loss: 2.013, Val f1_micro: 0.162
Epoch: 060, Train Loss: 1.972, Val f1_micro: 0.116
Epoch: 080, Train Loss: 1.944, Val f1_micro: 0.119
Epoch: 100, Train Loss: 1.902, Val f1_micro: 0.130
Epoch: 120, Train Loss: 1.814, Val f1_micro: 0.175
Epoch: 140, Train Loss: 1.755, Val f1_micro: 0.168
Epoch: 160, Train Loss: 1.683, Val f1_micro: 0.203
Epoch: 180, Train Loss: 1.605, Val f1_micro: 0.198
Epoch: 200, Train Loss: 1.587, Val f1_micro: 0.202
Epoch: 220, Train Loss: 1.523, Val f1_micro: 0.211
Epoch: 240, Train Loss: 1.488, Val f1_micro: 0.223
Epoch: 260, Train Loss: 1.441, Val f1_micro: 0.219
Epoch: 280, Train Loss: 1.411, Val f1_micro: 0.224
Epoch: 300, Train Loss: 1.379, Val f1_micro: 0.228
Epoch: 320, Train Loss: 1.370, Val f1_micro: 0.221
Epoch: 340, Train Loss: 1.342, Val f1_micro: 0.232
Epoch: 360, Train Loss: 1.293, Val f1_micro: 0.239
Epoch: 380, Train Loss: 1.290, Val f1_micro: 0.247
Epoch: 400, Train Loss: 1.227, Val f1_micro: 0.243
Epoch: 420, Train Loss: 1.217, Val f1_micro: 0.250
Epoch: 440, Train Loss: 1.251, Val f1_micro: 0.253
Epoch: 460, Train Loss: 1.199, Val f1_micro: 0.240
Epoch: 480, Train Loss: 1.155, Val f1_micro: 0.253
Epoch: 500, Train Loss: 1.132, Val f1_micro: 0.244
f1-micro: 0.244, f1-macro: 0.233, f1-weighted: 0.235, , roc-auc: 0.647
##### RUN 5 #####
Epoch: 020, Train Loss: 2.125, Val f1_micro: 0.095
Epoch: 040, Train Loss: 2.033, Val f1_micro: 0.163
Epoch: 060, Train Loss: 1.989, Val f1_micro: 0.118
Epoch: 080, Train Loss: 1.941, Val f1_micro: 0.123
Epoch: 100, Train Loss: 1.933, Val f1_micro: 0.128
Epoch: 120, Train Loss: 1.866, Val f1_micro: 0.186
Epoch: 140, Train Loss: 1.809, Val f1_micro: 0.187
Epoch: 160, Train Loss: 1.768, Val f1_micro: 0.186
Epoch: 180, Train Loss: 1.705, Val f1_micro: 0.184
Epoch: 200, Train Loss: 1.689, Val f1_micro: 0.190
Epoch: 220, Train Loss: 1.643, Val f1_micro: 0.194
Epoch: 240, Train Loss: 1.635, Val f1_micro: 0.195
Epoch: 260, Train Loss: 1.601, Val f1_micro: 0.208
Epoch: 280, Train Loss: 1.574, Val f1_micro: 0.208
Epoch: 300, Train Loss: 1.520, Val f1_micro: 0.208
Epoch: 320, Train Loss: 1.462, Val f1_micro: 0.217
Epoch: 340, Train Loss: 1.427, Val f1_micro: 0.231
Epoch: 360, Train Loss: 1.403, Val f1_micro: 0.219
Epoch: 380, Train Loss: 1.379, Val f1_micro: 0.222
Epoch: 400, Train Loss: 1.339, Val f1_micro: 0.230
Epoch: 420, Train Loss: 1.338, Val f1_micro: 0.231
Epoch: 440, Train Loss: 1.318, Val f1_micro: 0.229
Epoch: 460, Train Loss: 1.332, Val f1_micro: 0.237
Epoch: 480, Train Loss: 1.283, Val f1_micro: 0.240
Epoch: 500, Train Loss: 1.265, Val f1_micro: 0.236
f1-micro: 0.236, f1-macro: 0.224, f1-weighted: 0.225, , roc-auc: 0.635
########## Hyperparameters combination ##########
(512, 0.6, 0.05, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.068, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.007, Val f1_micro: 0.163
Epoch: 060, Train Loss: 1.990, Val f1_micro: 0.118
Epoch: 080, Train Loss: 1.954, Val f1_micro: 0.130
Epoch: 100, Train Loss: 1.917, Val f1_micro: 0.159
Epoch: 120, Train Loss: 1.864, Val f1_micro: 0.179
Epoch: 140, Train Loss: 1.803, Val f1_micro: 0.181
Epoch: 160, Train Loss: 1.762, Val f1_micro: 0.191
Epoch: 180, Train Loss: 1.740, Val f1_micro: 0.194
Epoch: 200, Train Loss: 1.739, Val f1_micro: 0.178
Epoch: 220, Train Loss: 1.697, Val f1_micro: 0.197
Epoch: 240, Train Loss: 1.656, Val f1_micro: 0.197
Epoch: 260, Train Loss: 1.640, Val f1_micro: 0.207
Epoch: 280, Train Loss: 1.634, Val f1_micro: 0.215
Epoch: 300, Train Loss: 1.628, Val f1_micro: 0.213
Epoch: 320, Train Loss: 1.581, Val f1_micro: 0.217
Epoch: 340, Train Loss: 1.574, Val f1_micro: 0.218
Epoch: 360, Train Loss: 1.582, Val f1_micro: 0.223
Epoch: 380, Train Loss: 1.583, Val f1_micro: 0.218
Epoch: 400, Train Loss: 1.547, Val f1_micro: 0.214
Epoch: 420, Train Loss: 1.524, Val f1_micro: 0.223
Epoch: 440, Train Loss: 1.561, Val f1_micro: 0.233
Epoch: 460, Train Loss: 1.535, Val f1_micro: 0.234
Epoch: 480, Train Loss: 1.507, Val f1_micro: 0.227
Epoch: 500, Train Loss: 1.497, Val f1_micro: 0.227
f1-micro: 0.227, f1-macro: 0.207, f1-weighted: 0.209, , roc-auc: 0.634
##### RUN 2 #####
Epoch: 020, Train Loss: 2.064, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.019, Val f1_micro: 0.164
Epoch: 060, Train Loss: 1.991, Val f1_micro: 0.121
Epoch: 080, Train Loss: 1.951, Val f1_micro: 0.133
Epoch: 100, Train Loss: 1.892, Val f1_micro: 0.177
Epoch: 120, Train Loss: 1.817, Val f1_micro: 0.194
Epoch: 140, Train Loss: 1.776, Val f1_micro: 0.182
Epoch: 160, Train Loss: 1.739, Val f1_micro: 0.195
Epoch: 180, Train Loss: 1.712, Val f1_micro: 0.200
Epoch: 200, Train Loss: 1.698, Val f1_micro: 0.199
Epoch: 220, Train Loss: 1.658, Val f1_micro: 0.201
Epoch: 240, Train Loss: 1.671, Val f1_micro: 0.205
Epoch: 260, Train Loss: 1.613, Val f1_micro: 0.213
Epoch: 280, Train Loss: 1.619, Val f1_micro: 0.207
Epoch: 300, Train Loss: 1.587, Val f1_micro: 0.208
Epoch: 320, Train Loss: 1.553, Val f1_micro: 0.214
Epoch: 340, Train Loss: 1.538, Val f1_micro: 0.209
Epoch: 360, Train Loss: 1.516, Val f1_micro: 0.213
Epoch: 380, Train Loss: 1.531, Val f1_micro: 0.221
Epoch: 400, Train Loss: 1.511, Val f1_micro: 0.222
Epoch: 420, Train Loss: 1.468, Val f1_micro: 0.215
Epoch: 440, Train Loss: 1.466, Val f1_micro: 0.235
Epoch: 460, Train Loss: 1.455, Val f1_micro: 0.236
Epoch: 480, Train Loss: 1.456, Val f1_micro: 0.230
Epoch: 500, Train Loss: 1.437, Val f1_micro: 0.244
f1-micro: 0.244, f1-macro: 0.220, f1-weighted: 0.221, , roc-auc: 0.636
##### RUN 3 #####
Epoch: 020, Train Loss: 2.052, Val f1_micro: 0.139
Epoch: 040, Train Loss: 2.001, Val f1_micro: 0.165
Epoch: 060, Train Loss: 1.973, Val f1_micro: 0.117
Epoch: 080, Train Loss: 1.937, Val f1_micro: 0.161
Epoch: 100, Train Loss: 1.871, Val f1_micro: 0.172
Epoch: 120, Train Loss: 1.831, Val f1_micro: 0.173
Epoch: 140, Train Loss: 1.766, Val f1_micro: 0.200
Epoch: 160, Train Loss: 1.727, Val f1_micro: 0.187
Epoch: 180, Train Loss: 1.687, Val f1_micro: 0.201
Epoch: 200, Train Loss: 1.671, Val f1_micro: 0.207
Epoch: 220, Train Loss: 1.608, Val f1_micro: 0.223
Epoch: 240, Train Loss: 1.630, Val f1_micro: 0.202
Epoch: 260, Train Loss: 1.604, Val f1_micro: 0.212
Epoch: 280, Train Loss: 1.576, Val f1_micro: 0.219
Epoch: 300, Train Loss: 1.542, Val f1_micro: 0.218
Epoch: 320, Train Loss: 1.530, Val f1_micro: 0.216
Epoch: 340, Train Loss: 1.536, Val f1_micro: 0.213
Epoch: 360, Train Loss: 1.493, Val f1_micro: 0.219
Epoch: 380, Train Loss: 1.502, Val f1_micro: 0.214
Epoch: 400, Train Loss: 1.474, Val f1_micro: 0.224
Epoch: 420, Train Loss: 1.508, Val f1_micro: 0.221
Epoch: 440, Train Loss: 1.436, Val f1_micro: 0.225
Epoch: 460, Train Loss: 1.456, Val f1_micro: 0.227
Epoch: 480, Train Loss: 1.450, Val f1_micro: 0.237
Epoch: 500, Train Loss: 1.425, Val f1_micro: 0.233
f1-micro: 0.233, f1-macro: 0.216, f1-weighted: 0.218, , roc-auc: 0.632
##### RUN 4 #####
Epoch: 020, Train Loss: 2.068, Val f1_micro: 0.097
Epoch: 040, Train Loss: 2.016, Val f1_micro: 0.164
Epoch: 060, Train Loss: 1.972, Val f1_micro: 0.121
Epoch: 080, Train Loss: 1.912, Val f1_micro: 0.179
Epoch: 100, Train Loss: 1.826, Val f1_micro: 0.187
Epoch: 120, Train Loss: 1.787, Val f1_micro: 0.184
Epoch: 140, Train Loss: 1.760, Val f1_micro: 0.187
Epoch: 160, Train Loss: 1.713, Val f1_micro: 0.195
Epoch: 180, Train Loss: 1.672, Val f1_micro: 0.187
Epoch: 200, Train Loss: 1.649, Val f1_micro: 0.211
Epoch: 220, Train Loss: 1.623, Val f1_micro: 0.210
Epoch: 240, Train Loss: 1.612, Val f1_micro: 0.217
Epoch: 260, Train Loss: 1.565, Val f1_micro: 0.223
Epoch: 280, Train Loss: 1.548, Val f1_micro: 0.224
Epoch: 300, Train Loss: 1.531, Val f1_micro: 0.215
Epoch: 320, Train Loss: 1.497, Val f1_micro: 0.215
Epoch: 340, Train Loss: 1.498, Val f1_micro: 0.230
Epoch: 360, Train Loss: 1.467, Val f1_micro: 0.219
Epoch: 380, Train Loss: 1.458, Val f1_micro: 0.231
Epoch: 400, Train Loss: 1.463, Val f1_micro: 0.218
Epoch: 420, Train Loss: 1.436, Val f1_micro: 0.234
Epoch: 440, Train Loss: 1.413, Val f1_micro: 0.228
Epoch: 460, Train Loss: 1.466, Val f1_micro: 0.230
Epoch: 480, Train Loss: 1.411, Val f1_micro: 0.237
Epoch: 500, Train Loss: 1.400, Val f1_micro: 0.241
f1-micro: 0.241, f1-macro: 0.224, f1-weighted: 0.226, , roc-auc: 0.635
##### RUN 5 #####
Epoch: 020, Train Loss: 2.056, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.019, Val f1_micro: 0.163
Epoch: 060, Train Loss: 1.987, Val f1_micro: 0.122
Epoch: 080, Train Loss: 1.947, Val f1_micro: 0.166
Epoch: 100, Train Loss: 1.911, Val f1_micro: 0.183
Epoch: 120, Train Loss: 1.858, Val f1_micro: 0.191
Epoch: 140, Train Loss: 1.806, Val f1_micro: 0.200
Epoch: 160, Train Loss: 1.777, Val f1_micro: 0.180
Epoch: 180, Train Loss: 1.707, Val f1_micro: 0.213
Epoch: 200, Train Loss: 1.651, Val f1_micro: 0.211
Epoch: 220, Train Loss: 1.641, Val f1_micro: 0.206
Epoch: 240, Train Loss: 1.649, Val f1_micro: 0.204
Epoch: 260, Train Loss: 1.586, Val f1_micro: 0.208
Epoch: 280, Train Loss: 1.590, Val f1_micro: 0.217
Epoch: 300, Train Loss: 1.561, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.542, Val f1_micro: 0.223
Epoch: 340, Train Loss: 1.538, Val f1_micro: 0.221
Epoch: 360, Train Loss: 1.517, Val f1_micro: 0.220
Epoch: 380, Train Loss: 1.499, Val f1_micro: 0.224
Epoch: 400, Train Loss: 1.498, Val f1_micro: 0.188
Epoch: 420, Train Loss: 1.508, Val f1_micro: 0.229
Epoch: 440, Train Loss: 1.479, Val f1_micro: 0.220
Epoch: 460, Train Loss: 1.473, Val f1_micro: 0.222
Epoch: 480, Train Loss: 1.444, Val f1_micro: 0.234
Epoch: 500, Train Loss: 1.427, Val f1_micro: 0.227
f1-micro: 0.227, f1-macro: 0.209, f1-weighted: 0.215, , roc-auc: 0.628
########## Hyperparameters combination ##########
(512, 0.6, 0.05, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.090, Val f1_micro: 0.098
Epoch: 040, Train Loss: 2.048, Val f1_micro: 0.112
Epoch: 060, Train Loss: 2.008, Val f1_micro: 0.119
Epoch: 080, Train Loss: 1.965, Val f1_micro: 0.162
Epoch: 100, Train Loss: 1.957, Val f1_micro: 0.169
Epoch: 120, Train Loss: 1.931, Val f1_micro: 0.163
Epoch: 140, Train Loss: 1.938, Val f1_micro: 0.150
Epoch: 160, Train Loss: 1.917, Val f1_micro: 0.165
Epoch: 180, Train Loss: 1.907, Val f1_micro: 0.180
Epoch: 200, Train Loss: 1.899, Val f1_micro: 0.170
Epoch: 220, Train Loss: 1.895, Val f1_micro: 0.163
Epoch: 240, Train Loss: 1.885, Val f1_micro: 0.194
Epoch: 260, Train Loss: 1.884, Val f1_micro: 0.163
Epoch: 280, Train Loss: 1.877, Val f1_micro: 0.185
Epoch: 300, Train Loss: 1.873, Val f1_micro: 0.176
Epoch: 320, Train Loss: 1.870, Val f1_micro: 0.188
Epoch: 340, Train Loss: 1.872, Val f1_micro: 0.191
Epoch: 360, Train Loss: 1.846, Val f1_micro: 0.174
Epoch: 380, Train Loss: 1.878, Val f1_micro: 0.166
Epoch: 400, Train Loss: 1.879, Val f1_micro: 0.160
Epoch: 420, Train Loss: 1.851, Val f1_micro: 0.178
Epoch: 440, Train Loss: 1.884, Val f1_micro: 0.185
Epoch: 460, Train Loss: 1.860, Val f1_micro: 0.193
Epoch: 480, Train Loss: 1.861, Val f1_micro: 0.179
Epoch: 500, Train Loss: 1.854, Val f1_micro: 0.179
f1-micro: 0.179, f1-macro: 0.142, f1-weighted: 0.140, , roc-auc: 0.619
##### RUN 2 #####
Epoch: 020, Train Loss: 2.070, Val f1_micro: 0.095
Epoch: 040, Train Loss: 2.035, Val f1_micro: 0.177
Epoch: 060, Train Loss: 1.995, Val f1_micro: 0.159
Epoch: 080, Train Loss: 1.983, Val f1_micro: 0.130
Epoch: 100, Train Loss: 1.940, Val f1_micro: 0.158
Epoch: 120, Train Loss: 1.925, Val f1_micro: 0.160
Epoch: 140, Train Loss: 1.925, Val f1_micro: 0.180
Epoch: 160, Train Loss: 1.894, Val f1_micro: 0.187
Epoch: 180, Train Loss: 1.900, Val f1_micro: 0.161
Epoch: 200, Train Loss: 1.897, Val f1_micro: 0.182
Epoch: 220, Train Loss: 1.894, Val f1_micro: 0.192
Epoch: 240, Train Loss: 1.893, Val f1_micro: 0.183
Epoch: 260, Train Loss: 1.877, Val f1_micro: 0.184
Epoch: 280, Train Loss: 1.886, Val f1_micro: 0.186
Epoch: 300, Train Loss: 1.885, Val f1_micro: 0.173
Epoch: 320, Train Loss: 1.862, Val f1_micro: 0.188
Epoch: 340, Train Loss: 1.882, Val f1_micro: 0.192
Epoch: 360, Train Loss: 1.876, Val f1_micro: 0.145
Epoch: 380, Train Loss: 1.878, Val f1_micro: 0.162
Epoch: 400, Train Loss: 1.857, Val f1_micro: 0.177
Epoch: 420, Train Loss: 1.864, Val f1_micro: 0.191
Epoch: 440, Train Loss: 1.862, Val f1_micro: 0.190
Epoch: 460, Train Loss: 1.853, Val f1_micro: 0.190
Epoch: 480, Train Loss: 1.863, Val f1_micro: 0.192
Epoch: 500, Train Loss: 1.872, Val f1_micro: 0.192
f1-micro: 0.192, f1-macro: 0.162, f1-weighted: 0.162, , roc-auc: 0.611
##### RUN 3 #####
Epoch: 020, Train Loss: 2.081, Val f1_micro: 0.098
Epoch: 040, Train Loss: 2.036, Val f1_micro: 0.114
Epoch: 060, Train Loss: 2.024, Val f1_micro: 0.115
Epoch: 080, Train Loss: 1.975, Val f1_micro: 0.162
Epoch: 100, Train Loss: 1.958, Val f1_micro: 0.163
Epoch: 120, Train Loss: 1.941, Val f1_micro: 0.161
Epoch: 140, Train Loss: 1.934, Val f1_micro: 0.170
Epoch: 160, Train Loss: 1.909, Val f1_micro: 0.171
Epoch: 180, Train Loss: 1.902, Val f1_micro: 0.181
Epoch: 200, Train Loss: 1.878, Val f1_micro: 0.178
Epoch: 220, Train Loss: 1.898, Val f1_micro: 0.191
Epoch: 240, Train Loss: 1.889, Val f1_micro: 0.187
Epoch: 260, Train Loss: 1.875, Val f1_micro: 0.186
Epoch: 280, Train Loss: 1.884, Val f1_micro: 0.181
Epoch: 300, Train Loss: 1.876, Val f1_micro: 0.178
Epoch: 320, Train Loss: 1.861, Val f1_micro: 0.183
Epoch: 340, Train Loss: 1.865, Val f1_micro: 0.175
Epoch: 360, Train Loss: 1.856, Val f1_micro: 0.172
Epoch: 380, Train Loss: 1.872, Val f1_micro: 0.160
Epoch: 400, Train Loss: 1.869, Val f1_micro: 0.203
Epoch: 420, Train Loss: 1.880, Val f1_micro: 0.186
Epoch: 440, Train Loss: 1.870, Val f1_micro: 0.185
Epoch: 460, Train Loss: 1.873, Val f1_micro: 0.190
Epoch: 480, Train Loss: 1.865, Val f1_micro: 0.185
Epoch: 500, Train Loss: 1.845, Val f1_micro: 0.191
f1-micro: 0.191, f1-macro: 0.155, f1-weighted: 0.158, , roc-auc: 0.616
##### RUN 4 #####
Epoch: 020, Train Loss: 2.094, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.035, Val f1_micro: 0.164
Epoch: 060, Train Loss: 2.027, Val f1_micro: 0.107
Epoch: 080, Train Loss: 1.982, Val f1_micro: 0.123
Epoch: 100, Train Loss: 1.942, Val f1_micro: 0.138
Epoch: 120, Train Loss: 1.940, Val f1_micro: 0.161
Epoch: 140, Train Loss: 1.925, Val f1_micro: 0.172
Epoch: 160, Train Loss: 1.912, Val f1_micro: 0.183
Epoch: 180, Train Loss: 1.910, Val f1_micro: 0.159
Epoch: 200, Train Loss: 1.900, Val f1_micro: 0.180
Epoch: 220, Train Loss: 1.914, Val f1_micro: 0.167
Epoch: 240, Train Loss: 1.897, Val f1_micro: 0.178
Epoch: 260, Train Loss: 1.896, Val f1_micro: 0.180
Epoch: 280, Train Loss: 1.878, Val f1_micro: 0.171
Epoch: 300, Train Loss: 1.879, Val f1_micro: 0.174
Epoch: 320, Train Loss: 1.882, Val f1_micro: 0.189
Epoch: 340, Train Loss: 1.891, Val f1_micro: 0.197
Epoch: 360, Train Loss: 1.868, Val f1_micro: 0.193
Epoch: 380, Train Loss: 1.888, Val f1_micro: 0.179
Epoch: 400, Train Loss: 1.872, Val f1_micro: 0.188
Epoch: 420, Train Loss: 1.866, Val f1_micro: 0.197
Epoch: 440, Train Loss: 1.867, Val f1_micro: 0.183
Epoch: 460, Train Loss: 1.879, Val f1_micro: 0.185
Epoch: 480, Train Loss: 1.856, Val f1_micro: 0.183
Epoch: 500, Train Loss: 1.864, Val f1_micro: 0.156
f1-micro: 0.156, f1-macro: 0.126, f1-weighted: 0.120, , roc-auc: 0.612
##### RUN 5 #####
Epoch: 020, Train Loss: 2.076, Val f1_micro: 0.098
Epoch: 040, Train Loss: 2.051, Val f1_micro: 0.161
Epoch: 060, Train Loss: 2.025, Val f1_micro: 0.120
Epoch: 080, Train Loss: 1.992, Val f1_micro: 0.125
Epoch: 100, Train Loss: 1.952, Val f1_micro: 0.156
Epoch: 120, Train Loss: 1.925, Val f1_micro: 0.173
Epoch: 140, Train Loss: 1.923, Val f1_micro: 0.177
Epoch: 160, Train Loss: 1.918, Val f1_micro: 0.167
Epoch: 180, Train Loss: 1.894, Val f1_micro: 0.171
Epoch: 200, Train Loss: 1.907, Val f1_micro: 0.152
Epoch: 220, Train Loss: 1.899, Val f1_micro: 0.183
Epoch: 240, Train Loss: 1.888, Val f1_micro: 0.178
Epoch: 260, Train Loss: 1.890, Val f1_micro: 0.190
Epoch: 280, Train Loss: 1.877, Val f1_micro: 0.195
Epoch: 300, Train Loss: 1.870, Val f1_micro: 0.179
Epoch: 320, Train Loss: 1.873, Val f1_micro: 0.147
Epoch: 340, Train Loss: 1.879, Val f1_micro: 0.183
Epoch: 360, Train Loss: 1.870, Val f1_micro: 0.181
Epoch: 380, Train Loss: 1.874, Val f1_micro: 0.152
Epoch: 400, Train Loss: 1.872, Val f1_micro: 0.172
Epoch: 420, Train Loss: 1.881, Val f1_micro: 0.161
Epoch: 440, Train Loss: 1.867, Val f1_micro: 0.180
Epoch: 460, Train Loss: 1.854, Val f1_micro: 0.186
Epoch: 480, Train Loss: 1.856, Val f1_micro: 0.164
Epoch: 500, Train Loss: 1.876, Val f1_micro: 0.179
f1-micro: 0.179, f1-macro: 0.135, f1-weighted: 0.130, , roc-auc: 0.618
########## Hyperparameters combination ##########
(512, 0.7, 0.001, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.575, Val f1_micro: 0.199
Epoch: 040, Train Loss: 2.191, Val f1_micro: 0.191
Epoch: 060, Train Loss: 2.025, Val f1_micro: 0.202
Epoch: 080, Train Loss: 1.941, Val f1_micro: 0.204
Epoch: 100, Train Loss: 1.859, Val f1_micro: 0.211
Epoch: 120, Train Loss: 1.772, Val f1_micro: 0.212
Epoch: 140, Train Loss: 1.730, Val f1_micro: 0.214
Epoch: 160, Train Loss: 1.686, Val f1_micro: 0.224
Epoch: 180, Train Loss: 1.662, Val f1_micro: 0.230
Epoch: 200, Train Loss: 1.599, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.562, Val f1_micro: 0.235
Epoch: 240, Train Loss: 1.560, Val f1_micro: 0.235
Epoch: 260, Train Loss: 1.515, Val f1_micro: 0.236
Epoch: 280, Train Loss: 1.494, Val f1_micro: 0.239
Epoch: 300, Train Loss: 1.454, Val f1_micro: 0.241
Epoch: 320, Train Loss: 1.449, Val f1_micro: 0.244
Epoch: 340, Train Loss: 1.410, Val f1_micro: 0.243
Epoch: 360, Train Loss: 1.403, Val f1_micro: 0.248
Epoch: 380, Train Loss: 1.384, Val f1_micro: 0.244
Epoch: 400, Train Loss: 1.370, Val f1_micro: 0.249
Epoch: 420, Train Loss: 1.354, Val f1_micro: 0.252
Epoch: 440, Train Loss: 1.334, Val f1_micro: 0.254
Epoch: 460, Train Loss: 1.322, Val f1_micro: 0.256
Epoch: 480, Train Loss: 1.279, Val f1_micro: 0.255
Epoch: 500, Train Loss: 1.283, Val f1_micro: 0.257
f1-micro: 0.257, f1-macro: 0.246, f1-weighted: 0.248, , roc-auc: 0.658
##### RUN 2 #####
Epoch: 020, Train Loss: 2.539, Val f1_micro: 0.201
Epoch: 040, Train Loss: 2.220, Val f1_micro: 0.197
Epoch: 060, Train Loss: 2.068, Val f1_micro: 0.205
Epoch: 080, Train Loss: 1.934, Val f1_micro: 0.205
Epoch: 100, Train Loss: 1.854, Val f1_micro: 0.212
Epoch: 120, Train Loss: 1.796, Val f1_micro: 0.213
Epoch: 140, Train Loss: 1.745, Val f1_micro: 0.217
Epoch: 160, Train Loss: 1.681, Val f1_micro: 0.224
Epoch: 180, Train Loss: 1.654, Val f1_micro: 0.225
Epoch: 200, Train Loss: 1.607, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.585, Val f1_micro: 0.231
Epoch: 240, Train Loss: 1.551, Val f1_micro: 0.234
Epoch: 260, Train Loss: 1.521, Val f1_micro: 0.236
Epoch: 280, Train Loss: 1.493, Val f1_micro: 0.241
Epoch: 300, Train Loss: 1.486, Val f1_micro: 0.243
Epoch: 320, Train Loss: 1.456, Val f1_micro: 0.241
Epoch: 340, Train Loss: 1.419, Val f1_micro: 0.243
Epoch: 360, Train Loss: 1.389, Val f1_micro: 0.246
Epoch: 380, Train Loss: 1.398, Val f1_micro: 0.248
Epoch: 400, Train Loss: 1.368, Val f1_micro: 0.250
Epoch: 420, Train Loss: 1.349, Val f1_micro: 0.250
Epoch: 440, Train Loss: 1.320, Val f1_micro: 0.250
Epoch: 460, Train Loss: 1.334, Val f1_micro: 0.252
Epoch: 480, Train Loss: 1.286, Val f1_micro: 0.257
Epoch: 500, Train Loss: 1.286, Val f1_micro: 0.256
f1-micro: 0.256, f1-macro: 0.244, f1-weighted: 0.247, , roc-auc: 0.658
##### RUN 3 #####
Epoch: 020, Train Loss: 2.579, Val f1_micro: 0.198
Epoch: 040, Train Loss: 2.210, Val f1_micro: 0.200
Epoch: 060, Train Loss: 2.040, Val f1_micro: 0.206
Epoch: 080, Train Loss: 1.936, Val f1_micro: 0.208
Epoch: 100, Train Loss: 1.874, Val f1_micro: 0.210
Epoch: 120, Train Loss: 1.773, Val f1_micro: 0.217
Epoch: 140, Train Loss: 1.739, Val f1_micro: 0.221
Epoch: 160, Train Loss: 1.681, Val f1_micro: 0.220
Epoch: 180, Train Loss: 1.640, Val f1_micro: 0.226
Epoch: 200, Train Loss: 1.614, Val f1_micro: 0.233
Epoch: 220, Train Loss: 1.578, Val f1_micro: 0.235
Epoch: 240, Train Loss: 1.564, Val f1_micro: 0.231
Epoch: 260, Train Loss: 1.520, Val f1_micro: 0.238
Epoch: 280, Train Loss: 1.480, Val f1_micro: 0.241
Epoch: 300, Train Loss: 1.470, Val f1_micro: 0.243
Epoch: 320, Train Loss: 1.433, Val f1_micro: 0.243
Epoch: 340, Train Loss: 1.420, Val f1_micro: 0.247
Epoch: 360, Train Loss: 1.414, Val f1_micro: 0.247
Epoch: 380, Train Loss: 1.386, Val f1_micro: 0.250
Epoch: 400, Train Loss: 1.381, Val f1_micro: 0.250
Epoch: 420, Train Loss: 1.340, Val f1_micro: 0.251
Epoch: 440, Train Loss: 1.326, Val f1_micro: 0.252
Epoch: 460, Train Loss: 1.303, Val f1_micro: 0.256
Epoch: 480, Train Loss: 1.290, Val f1_micro: 0.254
Epoch: 500, Train Loss: 1.254, Val f1_micro: 0.257
f1-micro: 0.257, f1-macro: 0.244, f1-weighted: 0.246, , roc-auc: 0.658
##### RUN 4 #####
Epoch: 020, Train Loss: 2.578, Val f1_micro: 0.199
Epoch: 040, Train Loss: 2.195, Val f1_micro: 0.200
Epoch: 060, Train Loss: 2.007, Val f1_micro: 0.202
Epoch: 080, Train Loss: 1.933, Val f1_micro: 0.203
Epoch: 100, Train Loss: 1.875, Val f1_micro: 0.208
Epoch: 120, Train Loss: 1.804, Val f1_micro: 0.216
Epoch: 140, Train Loss: 1.766, Val f1_micro: 0.220
Epoch: 160, Train Loss: 1.695, Val f1_micro: 0.221
Epoch: 180, Train Loss: 1.666, Val f1_micro: 0.233
Epoch: 200, Train Loss: 1.637, Val f1_micro: 0.229
Epoch: 220, Train Loss: 1.586, Val f1_micro: 0.233
Epoch: 240, Train Loss: 1.557, Val f1_micro: 0.236
Epoch: 260, Train Loss: 1.525, Val f1_micro: 0.242
Epoch: 280, Train Loss: 1.481, Val f1_micro: 0.241
Epoch: 300, Train Loss: 1.488, Val f1_micro: 0.242
Epoch: 320, Train Loss: 1.442, Val f1_micro: 0.245
Epoch: 340, Train Loss: 1.430, Val f1_micro: 0.249
Epoch: 360, Train Loss: 1.398, Val f1_micro: 0.246
Epoch: 380, Train Loss: 1.373, Val f1_micro: 0.250
Epoch: 400, Train Loss: 1.353, Val f1_micro: 0.250
Epoch: 420, Train Loss: 1.330, Val f1_micro: 0.252
Epoch: 440, Train Loss: 1.323, Val f1_micro: 0.255
Epoch: 460, Train Loss: 1.315, Val f1_micro: 0.254
Epoch: 480, Train Loss: 1.300, Val f1_micro: 0.253
Epoch: 500, Train Loss: 1.274, Val f1_micro: 0.256
f1-micro: 0.256, f1-macro: 0.244, f1-weighted: 0.247, , roc-auc: 0.658
##### RUN 5 #####
Epoch: 020, Train Loss: 2.525, Val f1_micro: 0.196
Epoch: 040, Train Loss: 2.229, Val f1_micro: 0.201
Epoch: 060, Train Loss: 2.008, Val f1_micro: 0.206
Epoch: 080, Train Loss: 1.954, Val f1_micro: 0.208
Epoch: 100, Train Loss: 1.851, Val f1_micro: 0.209
Epoch: 120, Train Loss: 1.793, Val f1_micro: 0.213
Epoch: 140, Train Loss: 1.747, Val f1_micro: 0.219
Epoch: 160, Train Loss: 1.680, Val f1_micro: 0.220
Epoch: 180, Train Loss: 1.641, Val f1_micro: 0.234
Epoch: 200, Train Loss: 1.614, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.585, Val f1_micro: 0.238
Epoch: 240, Train Loss: 1.556, Val f1_micro: 0.237
Epoch: 260, Train Loss: 1.500, Val f1_micro: 0.235
Epoch: 280, Train Loss: 1.476, Val f1_micro: 0.241
Epoch: 300, Train Loss: 1.471, Val f1_micro: 0.239
Epoch: 320, Train Loss: 1.438, Val f1_micro: 0.246
Epoch: 340, Train Loss: 1.424, Val f1_micro: 0.246
Epoch: 360, Train Loss: 1.405, Val f1_micro: 0.242
Epoch: 380, Train Loss: 1.395, Val f1_micro: 0.248
Epoch: 400, Train Loss: 1.366, Val f1_micro: 0.248
Epoch: 420, Train Loss: 1.340, Val f1_micro: 0.254
Epoch: 440, Train Loss: 1.327, Val f1_micro: 0.253
Epoch: 460, Train Loss: 1.293, Val f1_micro: 0.252
Epoch: 480, Train Loss: 1.288, Val f1_micro: 0.253
Epoch: 500, Train Loss: 1.280, Val f1_micro: 0.259
f1-micro: 0.259, f1-macro: 0.246, f1-weighted: 0.248, , roc-auc: 0.658
########## Hyperparameters combination ##########
(512, 0.7, 0.001, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.520, Val f1_micro: 0.191
Epoch: 040, Train Loss: 2.221, Val f1_micro: 0.198
Epoch: 060, Train Loss: 2.057, Val f1_micro: 0.199
Epoch: 080, Train Loss: 1.958, Val f1_micro: 0.207
Epoch: 100, Train Loss: 1.852, Val f1_micro: 0.211
Epoch: 120, Train Loss: 1.790, Val f1_micro: 0.216
Epoch: 140, Train Loss: 1.749, Val f1_micro: 0.221
Epoch: 160, Train Loss: 1.683, Val f1_micro: 0.227
Epoch: 180, Train Loss: 1.660, Val f1_micro: 0.223
Epoch: 200, Train Loss: 1.619, Val f1_micro: 0.231
Epoch: 220, Train Loss: 1.601, Val f1_micro: 0.231
Epoch: 240, Train Loss: 1.562, Val f1_micro: 0.235
Epoch: 260, Train Loss: 1.551, Val f1_micro: 0.234
Epoch: 280, Train Loss: 1.544, Val f1_micro: 0.235
Epoch: 300, Train Loss: 1.493, Val f1_micro: 0.239
Epoch: 320, Train Loss: 1.492, Val f1_micro: 0.238
Epoch: 340, Train Loss: 1.473, Val f1_micro: 0.237
Epoch: 360, Train Loss: 1.453, Val f1_micro: 0.244
Epoch: 380, Train Loss: 1.436, Val f1_micro: 0.245
Epoch: 400, Train Loss: 1.386, Val f1_micro: 0.247
Epoch: 420, Train Loss: 1.403, Val f1_micro: 0.244
Epoch: 440, Train Loss: 1.380, Val f1_micro: 0.248
Epoch: 460, Train Loss: 1.360, Val f1_micro: 0.245
Epoch: 480, Train Loss: 1.358, Val f1_micro: 0.247
Epoch: 500, Train Loss: 1.333, Val f1_micro: 0.252
f1-micro: 0.252, f1-macro: 0.239, f1-weighted: 0.240, , roc-auc: 0.660
##### RUN 2 #####
Epoch: 020, Train Loss: 2.617, Val f1_micro: 0.190
Epoch: 040, Train Loss: 2.242, Val f1_micro: 0.196
Epoch: 060, Train Loss: 2.021, Val f1_micro: 0.199
Epoch: 080, Train Loss: 1.939, Val f1_micro: 0.201
Epoch: 100, Train Loss: 1.872, Val f1_micro: 0.208
Epoch: 120, Train Loss: 1.790, Val f1_micro: 0.213
Epoch: 140, Train Loss: 1.752, Val f1_micro: 0.218
Epoch: 160, Train Loss: 1.700, Val f1_micro: 0.221
Epoch: 180, Train Loss: 1.666, Val f1_micro: 0.227
Epoch: 200, Train Loss: 1.628, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.597, Val f1_micro: 0.231
Epoch: 240, Train Loss: 1.577, Val f1_micro: 0.234
Epoch: 260, Train Loss: 1.530, Val f1_micro: 0.233
Epoch: 280, Train Loss: 1.506, Val f1_micro: 0.239
Epoch: 300, Train Loss: 1.494, Val f1_micro: 0.238
Epoch: 320, Train Loss: 1.474, Val f1_micro: 0.241
Epoch: 340, Train Loss: 1.481, Val f1_micro: 0.241
Epoch: 360, Train Loss: 1.431, Val f1_micro: 0.243
Epoch: 380, Train Loss: 1.428, Val f1_micro: 0.246
Epoch: 400, Train Loss: 1.407, Val f1_micro: 0.248
Epoch: 420, Train Loss: 1.401, Val f1_micro: 0.246
Epoch: 440, Train Loss: 1.376, Val f1_micro: 0.248
Epoch: 460, Train Loss: 1.368, Val f1_micro: 0.253
Epoch: 480, Train Loss: 1.352, Val f1_micro: 0.255
Epoch: 500, Train Loss: 1.330, Val f1_micro: 0.250
f1-micro: 0.250, f1-macro: 0.238, f1-weighted: 0.239, , roc-auc: 0.661
##### RUN 3 #####
Epoch: 020, Train Loss: 2.540, Val f1_micro: 0.188
Epoch: 040, Train Loss: 2.209, Val f1_micro: 0.192
Epoch: 060, Train Loss: 2.055, Val f1_micro: 0.206
Epoch: 080, Train Loss: 1.935, Val f1_micro: 0.206
Epoch: 100, Train Loss: 1.866, Val f1_micro: 0.210
Epoch: 120, Train Loss: 1.807, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.756, Val f1_micro: 0.220
Epoch: 160, Train Loss: 1.694, Val f1_micro: 0.218
Epoch: 180, Train Loss: 1.668, Val f1_micro: 0.228
Epoch: 200, Train Loss: 1.621, Val f1_micro: 0.225
Epoch: 220, Train Loss: 1.605, Val f1_micro: 0.233
Epoch: 240, Train Loss: 1.581, Val f1_micro: 0.234
Epoch: 260, Train Loss: 1.551, Val f1_micro: 0.237
Epoch: 280, Train Loss: 1.532, Val f1_micro: 0.237
Epoch: 300, Train Loss: 1.493, Val f1_micro: 0.238
Epoch: 320, Train Loss: 1.480, Val f1_micro: 0.241
Epoch: 340, Train Loss: 1.481, Val f1_micro: 0.245
Epoch: 360, Train Loss: 1.432, Val f1_micro: 0.242
Epoch: 380, Train Loss: 1.425, Val f1_micro: 0.246
Epoch: 400, Train Loss: 1.392, Val f1_micro: 0.248
Epoch: 420, Train Loss: 1.392, Val f1_micro: 0.247
Epoch: 440, Train Loss: 1.384, Val f1_micro: 0.249
Epoch: 460, Train Loss: 1.363, Val f1_micro: 0.248
Epoch: 480, Train Loss: 1.357, Val f1_micro: 0.251
Epoch: 500, Train Loss: 1.328, Val f1_micro: 0.248
f1-micro: 0.248, f1-macro: 0.235, f1-weighted: 0.236, , roc-auc: 0.659
##### RUN 4 #####
Epoch: 020, Train Loss: 2.568, Val f1_micro: 0.190
Epoch: 040, Train Loss: 2.275, Val f1_micro: 0.194
Epoch: 060, Train Loss: 2.067, Val f1_micro: 0.199
Epoch: 080, Train Loss: 1.953, Val f1_micro: 0.197
Epoch: 100, Train Loss: 1.842, Val f1_micro: 0.208
Epoch: 120, Train Loss: 1.821, Val f1_micro: 0.207
Epoch: 140, Train Loss: 1.743, Val f1_micro: 0.221
Epoch: 160, Train Loss: 1.725, Val f1_micro: 0.222
Epoch: 180, Train Loss: 1.657, Val f1_micro: 0.228
Epoch: 200, Train Loss: 1.643, Val f1_micro: 0.231
Epoch: 220, Train Loss: 1.614, Val f1_micro: 0.231
Epoch: 240, Train Loss: 1.571, Val f1_micro: 0.234
Epoch: 260, Train Loss: 1.549, Val f1_micro: 0.234
Epoch: 280, Train Loss: 1.509, Val f1_micro: 0.238
Epoch: 300, Train Loss: 1.500, Val f1_micro: 0.236
Epoch: 320, Train Loss: 1.490, Val f1_micro: 0.243
Epoch: 340, Train Loss: 1.462, Val f1_micro: 0.240
Epoch: 360, Train Loss: 1.445, Val f1_micro: 0.241
Epoch: 380, Train Loss: 1.420, Val f1_micro: 0.245
Epoch: 400, Train Loss: 1.432, Val f1_micro: 0.243
Epoch: 420, Train Loss: 1.394, Val f1_micro: 0.241
Epoch: 440, Train Loss: 1.370, Val f1_micro: 0.249
Epoch: 460, Train Loss: 1.365, Val f1_micro: 0.248
Epoch: 480, Train Loss: 1.350, Val f1_micro: 0.253
Epoch: 500, Train Loss: 1.346, Val f1_micro: 0.252
f1-micro: 0.252, f1-macro: 0.240, f1-weighted: 0.243, , roc-auc: 0.659
##### RUN 5 #####
Epoch: 020, Train Loss: 2.582, Val f1_micro: 0.189
Epoch: 040, Train Loss: 2.219, Val f1_micro: 0.193
Epoch: 060, Train Loss: 2.052, Val f1_micro: 0.202
Epoch: 080, Train Loss: 1.967, Val f1_micro: 0.202
Epoch: 100, Train Loss: 1.867, Val f1_micro: 0.211
Epoch: 120, Train Loss: 1.818, Val f1_micro: 0.214
Epoch: 140, Train Loss: 1.732, Val f1_micro: 0.213
Epoch: 160, Train Loss: 1.698, Val f1_micro: 0.217
Epoch: 180, Train Loss: 1.685, Val f1_micro: 0.228
Epoch: 200, Train Loss: 1.649, Val f1_micro: 0.232
Epoch: 220, Train Loss: 1.611, Val f1_micro: 0.229
Epoch: 240, Train Loss: 1.568, Val f1_micro: 0.234
Epoch: 260, Train Loss: 1.543, Val f1_micro: 0.233
Epoch: 280, Train Loss: 1.524, Val f1_micro: 0.238
Epoch: 300, Train Loss: 1.496, Val f1_micro: 0.237
Epoch: 320, Train Loss: 1.459, Val f1_micro: 0.236
Epoch: 340, Train Loss: 1.450, Val f1_micro: 0.238
Epoch: 360, Train Loss: 1.456, Val f1_micro: 0.243
Epoch: 380, Train Loss: 1.426, Val f1_micro: 0.244
Epoch: 400, Train Loss: 1.399, Val f1_micro: 0.245
Epoch: 420, Train Loss: 1.397, Val f1_micro: 0.246
Epoch: 440, Train Loss: 1.382, Val f1_micro: 0.247
Epoch: 460, Train Loss: 1.372, Val f1_micro: 0.252
Epoch: 480, Train Loss: 1.332, Val f1_micro: 0.252
Epoch: 500, Train Loss: 1.338, Val f1_micro: 0.253
f1-micro: 0.253, f1-macro: 0.240, f1-weighted: 0.242, , roc-auc: 0.660
########## Hyperparameters combination ##########
(512, 0.7, 0.001, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.552, Val f1_micro: 0.198
Epoch: 040, Train Loss: 2.217, Val f1_micro: 0.200
Epoch: 060, Train Loss: 2.063, Val f1_micro: 0.205
Epoch: 080, Train Loss: 1.945, Val f1_micro: 0.207
Epoch: 100, Train Loss: 1.896, Val f1_micro: 0.208
Epoch: 120, Train Loss: 1.809, Val f1_micro: 0.209
Epoch: 140, Train Loss: 1.772, Val f1_micro: 0.216
Epoch: 160, Train Loss: 1.713, Val f1_micro: 0.223
Epoch: 180, Train Loss: 1.668, Val f1_micro: 0.221
Epoch: 200, Train Loss: 1.650, Val f1_micro: 0.226
Epoch: 220, Train Loss: 1.616, Val f1_micro: 0.230
Epoch: 240, Train Loss: 1.599, Val f1_micro: 0.228
Epoch: 260, Train Loss: 1.584, Val f1_micro: 0.233
Epoch: 280, Train Loss: 1.558, Val f1_micro: 0.232
Epoch: 300, Train Loss: 1.538, Val f1_micro: 0.236
Epoch: 320, Train Loss: 1.538, Val f1_micro: 0.234
Epoch: 340, Train Loss: 1.518, Val f1_micro: 0.236
Epoch: 360, Train Loss: 1.477, Val f1_micro: 0.238
Epoch: 380, Train Loss: 1.470, Val f1_micro: 0.236
Epoch: 400, Train Loss: 1.468, Val f1_micro: 0.242
Epoch: 420, Train Loss: 1.479, Val f1_micro: 0.237
Epoch: 440, Train Loss: 1.450, Val f1_micro: 0.239
Epoch: 460, Train Loss: 1.415, Val f1_micro: 0.244
Epoch: 480, Train Loss: 1.423, Val f1_micro: 0.247
Epoch: 500, Train Loss: 1.418, Val f1_micro: 0.244
f1-micro: 0.244, f1-macro: 0.228, f1-weighted: 0.230, , roc-auc: 0.655
##### RUN 2 #####
Epoch: 020, Train Loss: 2.547, Val f1_micro: 0.196
Epoch: 040, Train Loss: 2.219, Val f1_micro: 0.198
Epoch: 060, Train Loss: 2.077, Val f1_micro: 0.203
Epoch: 080, Train Loss: 1.940, Val f1_micro: 0.202
Epoch: 100, Train Loss: 1.870, Val f1_micro: 0.204
Epoch: 120, Train Loss: 1.825, Val f1_micro: 0.212
Epoch: 140, Train Loss: 1.751, Val f1_micro: 0.217
Epoch: 160, Train Loss: 1.728, Val f1_micro: 0.217
Epoch: 180, Train Loss: 1.661, Val f1_micro: 0.226
Epoch: 200, Train Loss: 1.651, Val f1_micro: 0.224
Epoch: 220, Train Loss: 1.622, Val f1_micro: 0.229
Epoch: 240, Train Loss: 1.598, Val f1_micro: 0.232
Epoch: 260, Train Loss: 1.573, Val f1_micro: 0.231
Epoch: 280, Train Loss: 1.556, Val f1_micro: 0.236
Epoch: 300, Train Loss: 1.533, Val f1_micro: 0.233
Epoch: 320, Train Loss: 1.519, Val f1_micro: 0.237
Epoch: 340, Train Loss: 1.503, Val f1_micro: 0.236
Epoch: 360, Train Loss: 1.501, Val f1_micro: 0.235
Epoch: 380, Train Loss: 1.485, Val f1_micro: 0.243
Epoch: 400, Train Loss: 1.468, Val f1_micro: 0.240
Epoch: 420, Train Loss: 1.463, Val f1_micro: 0.245
Epoch: 440, Train Loss: 1.424, Val f1_micro: 0.241
Epoch: 460, Train Loss: 1.431, Val f1_micro: 0.242
Epoch: 480, Train Loss: 1.411, Val f1_micro: 0.243
Epoch: 500, Train Loss: 1.426, Val f1_micro: 0.246
f1-micro: 0.246, f1-macro: 0.230, f1-weighted: 0.233, , roc-auc: 0.657
##### RUN 3 #####
Epoch: 020, Train Loss: 2.505, Val f1_micro: 0.196
Epoch: 040, Train Loss: 2.198, Val f1_micro: 0.198
Epoch: 060, Train Loss: 2.034, Val f1_micro: 0.204
Epoch: 080, Train Loss: 1.934, Val f1_micro: 0.199
Epoch: 100, Train Loss: 1.856, Val f1_micro: 0.213
Epoch: 120, Train Loss: 1.798, Val f1_micro: 0.212
Epoch: 140, Train Loss: 1.767, Val f1_micro: 0.214
Epoch: 160, Train Loss: 1.697, Val f1_micro: 0.219
Epoch: 180, Train Loss: 1.672, Val f1_micro: 0.222
Epoch: 200, Train Loss: 1.644, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.627, Val f1_micro: 0.230
Epoch: 240, Train Loss: 1.584, Val f1_micro: 0.232
Epoch: 260, Train Loss: 1.588, Val f1_micro: 0.227
Epoch: 280, Train Loss: 1.563, Val f1_micro: 0.235
Epoch: 300, Train Loss: 1.536, Val f1_micro: 0.235
Epoch: 320, Train Loss: 1.543, Val f1_micro: 0.238
Epoch: 340, Train Loss: 1.510, Val f1_micro: 0.236
Epoch: 360, Train Loss: 1.491, Val f1_micro: 0.240
Epoch: 380, Train Loss: 1.474, Val f1_micro: 0.240
Epoch: 400, Train Loss: 1.442, Val f1_micro: 0.235
Epoch: 420, Train Loss: 1.452, Val f1_micro: 0.242
Epoch: 440, Train Loss: 1.446, Val f1_micro: 0.242
Epoch: 460, Train Loss: 1.446, Val f1_micro: 0.242
Epoch: 480, Train Loss: 1.437, Val f1_micro: 0.242
Epoch: 500, Train Loss: 1.402, Val f1_micro: 0.245
f1-micro: 0.245, f1-macro: 0.228, f1-weighted: 0.231, , roc-auc: 0.657
##### RUN 4 #####
Epoch: 020, Train Loss: 2.549, Val f1_micro: 0.193
Epoch: 040, Train Loss: 2.209, Val f1_micro: 0.197
Epoch: 060, Train Loss: 2.065, Val f1_micro: 0.202
Epoch: 080, Train Loss: 1.951, Val f1_micro: 0.200
Epoch: 100, Train Loss: 1.890, Val f1_micro: 0.209
Epoch: 120, Train Loss: 1.806, Val f1_micro: 0.212
Epoch: 140, Train Loss: 1.756, Val f1_micro: 0.217
Epoch: 160, Train Loss: 1.716, Val f1_micro: 0.222
Epoch: 180, Train Loss: 1.693, Val f1_micro: 0.222
Epoch: 200, Train Loss: 1.649, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.614, Val f1_micro: 0.225
Epoch: 240, Train Loss: 1.601, Val f1_micro: 0.230
Epoch: 260, Train Loss: 1.576, Val f1_micro: 0.230
Epoch: 280, Train Loss: 1.563, Val f1_micro: 0.237
Epoch: 300, Train Loss: 1.534, Val f1_micro: 0.234
Epoch: 320, Train Loss: 1.532, Val f1_micro: 0.234
Epoch: 340, Train Loss: 1.512, Val f1_micro: 0.239
Epoch: 360, Train Loss: 1.499, Val f1_micro: 0.240
Epoch: 380, Train Loss: 1.488, Val f1_micro: 0.240
Epoch: 400, Train Loss: 1.478, Val f1_micro: 0.241
Epoch: 420, Train Loss: 1.457, Val f1_micro: 0.242
Epoch: 440, Train Loss: 1.458, Val f1_micro: 0.244
Epoch: 460, Train Loss: 1.426, Val f1_micro: 0.244
Epoch: 480, Train Loss: 1.427, Val f1_micro: 0.248
Epoch: 500, Train Loss: 1.426, Val f1_micro: 0.243
f1-micro: 0.243, f1-macro: 0.226, f1-weighted: 0.229, , roc-auc: 0.657
##### RUN 5 #####
Epoch: 020, Train Loss: 2.559, Val f1_micro: 0.191
Epoch: 040, Train Loss: 2.204, Val f1_micro: 0.193
Epoch: 060, Train Loss: 2.039, Val f1_micro: 0.198
Epoch: 080, Train Loss: 1.943, Val f1_micro: 0.202
Epoch: 100, Train Loss: 1.859, Val f1_micro: 0.212
Epoch: 120, Train Loss: 1.793, Val f1_micro: 0.213
Epoch: 140, Train Loss: 1.762, Val f1_micro: 0.216
Epoch: 160, Train Loss: 1.726, Val f1_micro: 0.220
Epoch: 180, Train Loss: 1.666, Val f1_micro: 0.228
Epoch: 200, Train Loss: 1.636, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.617, Val f1_micro: 0.235
Epoch: 240, Train Loss: 1.600, Val f1_micro: 0.231
Epoch: 260, Train Loss: 1.572, Val f1_micro: 0.231
Epoch: 280, Train Loss: 1.543, Val f1_micro: 0.232
Epoch: 300, Train Loss: 1.537, Val f1_micro: 0.234
Epoch: 320, Train Loss: 1.516, Val f1_micro: 0.236
Epoch: 340, Train Loss: 1.506, Val f1_micro: 0.238
Epoch: 360, Train Loss: 1.496, Val f1_micro: 0.241
Epoch: 380, Train Loss: 1.477, Val f1_micro: 0.237
Epoch: 400, Train Loss: 1.453, Val f1_micro: 0.237
Epoch: 420, Train Loss: 1.450, Val f1_micro: 0.241
Epoch: 440, Train Loss: 1.424, Val f1_micro: 0.244
Epoch: 460, Train Loss: 1.444, Val f1_micro: 0.238
Epoch: 480, Train Loss: 1.431, Val f1_micro: 0.242
Epoch: 500, Train Loss: 1.428, Val f1_micro: 0.244
f1-micro: 0.244, f1-macro: 0.227, f1-weighted: 0.229, , roc-auc: 0.657
########## Hyperparameters combination ##########
(512, 0.7, 0.001, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.555, Val f1_micro: 0.195
Epoch: 040, Train Loss: 2.161, Val f1_micro: 0.198
Epoch: 060, Train Loss: 2.037, Val f1_micro: 0.206
Epoch: 080, Train Loss: 1.970, Val f1_micro: 0.206
Epoch: 100, Train Loss: 1.902, Val f1_micro: 0.208
Epoch: 120, Train Loss: 1.843, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.835, Val f1_micro: 0.219
Epoch: 160, Train Loss: 1.795, Val f1_micro: 0.215
Epoch: 180, Train Loss: 1.777, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.745, Val f1_micro: 0.219
Epoch: 220, Train Loss: 1.721, Val f1_micro: 0.224
Epoch: 240, Train Loss: 1.740, Val f1_micro: 0.223
Epoch: 260, Train Loss: 1.716, Val f1_micro: 0.228
Epoch: 280, Train Loss: 1.712, Val f1_micro: 0.221
Epoch: 300, Train Loss: 1.711, Val f1_micro: 0.228
Epoch: 320, Train Loss: 1.720, Val f1_micro: 0.226
Epoch: 340, Train Loss: 1.714, Val f1_micro: 0.227
Epoch: 360, Train Loss: 1.705, Val f1_micro: 0.219
Epoch: 380, Train Loss: 1.699, Val f1_micro: 0.229
Epoch: 400, Train Loss: 1.726, Val f1_micro: 0.228
Epoch: 420, Train Loss: 1.710, Val f1_micro: 0.224
Epoch: 440, Train Loss: 1.715, Val f1_micro: 0.222
Epoch: 460, Train Loss: 1.712, Val f1_micro: 0.226
Epoch: 480, Train Loss: 1.698, Val f1_micro: 0.219
Epoch: 500, Train Loss: 1.724, Val f1_micro: 0.221
f1-micro: 0.221, f1-macro: 0.189, f1-weighted: 0.190, , roc-auc: 0.651
##### RUN 2 #####
Epoch: 020, Train Loss: 2.572, Val f1_micro: 0.190
Epoch: 040, Train Loss: 2.208, Val f1_micro: 0.199
Epoch: 060, Train Loss: 2.066, Val f1_micro: 0.210
Epoch: 080, Train Loss: 1.964, Val f1_micro: 0.208
Epoch: 100, Train Loss: 1.892, Val f1_micro: 0.210
Epoch: 120, Train Loss: 1.861, Val f1_micro: 0.216
Epoch: 140, Train Loss: 1.807, Val f1_micro: 0.219
Epoch: 160, Train Loss: 1.785, Val f1_micro: 0.220
Epoch: 180, Train Loss: 1.768, Val f1_micro: 0.225
Epoch: 200, Train Loss: 1.758, Val f1_micro: 0.220
Epoch: 220, Train Loss: 1.742, Val f1_micro: 0.224
Epoch: 240, Train Loss: 1.746, Val f1_micro: 0.215
Epoch: 260, Train Loss: 1.732, Val f1_micro: 0.221
Epoch: 280, Train Loss: 1.717, Val f1_micro: 0.224
Epoch: 300, Train Loss: 1.730, Val f1_micro: 0.228
Epoch: 320, Train Loss: 1.713, Val f1_micro: 0.220
Epoch: 340, Train Loss: 1.711, Val f1_micro: 0.222
Epoch: 360, Train Loss: 1.719, Val f1_micro: 0.225
Epoch: 380, Train Loss: 1.694, Val f1_micro: 0.227
Epoch: 400, Train Loss: 1.715, Val f1_micro: 0.225
Epoch: 420, Train Loss: 1.715, Val f1_micro: 0.220
Epoch: 440, Train Loss: 1.720, Val f1_micro: 0.226
Epoch: 460, Train Loss: 1.705, Val f1_micro: 0.221
Epoch: 480, Train Loss: 1.704, Val f1_micro: 0.222
Epoch: 500, Train Loss: 1.708, Val f1_micro: 0.222
f1-micro: 0.222, f1-macro: 0.190, f1-weighted: 0.192, , roc-auc: 0.651
##### RUN 3 #####
Epoch: 020, Train Loss: 2.540, Val f1_micro: 0.196
Epoch: 040, Train Loss: 2.172, Val f1_micro: 0.202
Epoch: 060, Train Loss: 2.064, Val f1_micro: 0.204
Epoch: 080, Train Loss: 1.936, Val f1_micro: 0.207
Epoch: 100, Train Loss: 1.891, Val f1_micro: 0.218
Epoch: 120, Train Loss: 1.853, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.817, Val f1_micro: 0.216
Epoch: 160, Train Loss: 1.786, Val f1_micro: 0.217
Epoch: 180, Train Loss: 1.762, Val f1_micro: 0.217
Epoch: 200, Train Loss: 1.759, Val f1_micro: 0.222
Epoch: 220, Train Loss: 1.735, Val f1_micro: 0.218
Epoch: 240, Train Loss: 1.724, Val f1_micro: 0.220
Epoch: 260, Train Loss: 1.723, Val f1_micro: 0.221
Epoch: 280, Train Loss: 1.714, Val f1_micro: 0.218
Epoch: 300, Train Loss: 1.712, Val f1_micro: 0.223
Epoch: 320, Train Loss: 1.706, Val f1_micro: 0.214
Epoch: 340, Train Loss: 1.705, Val f1_micro: 0.224
Epoch: 360, Train Loss: 1.699, Val f1_micro: 0.225
Epoch: 380, Train Loss: 1.707, Val f1_micro: 0.218
Epoch: 400, Train Loss: 1.701, Val f1_micro: 0.218
Epoch: 420, Train Loss: 1.713, Val f1_micro: 0.220
Epoch: 440, Train Loss: 1.716, Val f1_micro: 0.222
Epoch: 460, Train Loss: 1.692, Val f1_micro: 0.215
Epoch: 480, Train Loss: 1.709, Val f1_micro: 0.224
Epoch: 500, Train Loss: 1.707, Val f1_micro: 0.219
f1-micro: 0.219, f1-macro: 0.188, f1-weighted: 0.189, , roc-auc: 0.652
##### RUN 4 #####
Epoch: 020, Train Loss: 2.585, Val f1_micro: 0.191
Epoch: 040, Train Loss: 2.286, Val f1_micro: 0.198
Epoch: 060, Train Loss: 2.060, Val f1_micro: 0.205
Epoch: 080, Train Loss: 1.954, Val f1_micro: 0.211
Epoch: 100, Train Loss: 1.871, Val f1_micro: 0.215
Epoch: 120, Train Loss: 1.871, Val f1_micro: 0.209
Epoch: 140, Train Loss: 1.803, Val f1_micro: 0.218
Epoch: 160, Train Loss: 1.791, Val f1_micro: 0.214
Epoch: 180, Train Loss: 1.757, Val f1_micro: 0.219
Epoch: 200, Train Loss: 1.738, Val f1_micro: 0.222
Epoch: 220, Train Loss: 1.735, Val f1_micro: 0.222
Epoch: 240, Train Loss: 1.722, Val f1_micro: 0.221
Epoch: 260, Train Loss: 1.719, Val f1_micro: 0.223
Epoch: 280, Train Loss: 1.731, Val f1_micro: 0.225
Epoch: 300, Train Loss: 1.709, Val f1_micro: 0.221
Epoch: 320, Train Loss: 1.722, Val f1_micro: 0.224
Epoch: 340, Train Loss: 1.699, Val f1_micro: 0.219
Epoch: 360, Train Loss: 1.716, Val f1_micro: 0.220
Epoch: 380, Train Loss: 1.695, Val f1_micro: 0.218
Epoch: 400, Train Loss: 1.703, Val f1_micro: 0.221
Epoch: 420, Train Loss: 1.700, Val f1_micro: 0.217
Epoch: 440, Train Loss: 1.709, Val f1_micro: 0.218
Epoch: 460, Train Loss: 1.703, Val f1_micro: 0.220
Epoch: 480, Train Loss: 1.699, Val f1_micro: 0.212
Epoch: 500, Train Loss: 1.716, Val f1_micro: 0.223
f1-micro: 0.223, f1-macro: 0.191, f1-weighted: 0.193, , roc-auc: 0.652
##### RUN 5 #####
Epoch: 020, Train Loss: 2.509, Val f1_micro: 0.188
Epoch: 040, Train Loss: 2.219, Val f1_micro: 0.202
Epoch: 060, Train Loss: 2.043, Val f1_micro: 0.206
Epoch: 080, Train Loss: 1.944, Val f1_micro: 0.212
Epoch: 100, Train Loss: 1.882, Val f1_micro: 0.205
Epoch: 120, Train Loss: 1.857, Val f1_micro: 0.214
Epoch: 140, Train Loss: 1.826, Val f1_micro: 0.218
Epoch: 160, Train Loss: 1.786, Val f1_micro: 0.220
Epoch: 180, Train Loss: 1.773, Val f1_micro: 0.226
Epoch: 200, Train Loss: 1.753, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.735, Val f1_micro: 0.217
Epoch: 240, Train Loss: 1.724, Val f1_micro: 0.229
Epoch: 260, Train Loss: 1.724, Val f1_micro: 0.215
Epoch: 280, Train Loss: 1.712, Val f1_micro: 0.222
Epoch: 300, Train Loss: 1.713, Val f1_micro: 0.219
Epoch: 320, Train Loss: 1.708, Val f1_micro: 0.221
Epoch: 340, Train Loss: 1.705, Val f1_micro: 0.219
Epoch: 360, Train Loss: 1.708, Val f1_micro: 0.215
Epoch: 380, Train Loss: 1.704, Val f1_micro: 0.220
Epoch: 400, Train Loss: 1.707, Val f1_micro: 0.225
Epoch: 420, Train Loss: 1.707, Val f1_micro: 0.217
Epoch: 440, Train Loss: 1.704, Val f1_micro: 0.211
Epoch: 460, Train Loss: 1.710, Val f1_micro: 0.220
Epoch: 480, Train Loss: 1.712, Val f1_micro: 0.225
Epoch: 500, Train Loss: 1.733, Val f1_micro: 0.215
f1-micro: 0.215, f1-macro: 0.187, f1-weighted: 0.188, , roc-auc: 0.650
########## Hyperparameters combination ##########
(512, 0.7, 0.005, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.998, Val f1_micro: 0.205
Epoch: 040, Train Loss: 1.738, Val f1_micro: 0.208
Epoch: 060, Train Loss: 1.612, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.490, Val f1_micro: 0.238
Epoch: 100, Train Loss: 1.413, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.374, Val f1_micro: 0.255
Epoch: 140, Train Loss: 1.275, Val f1_micro: 0.257
Epoch: 160, Train Loss: 1.215, Val f1_micro: 0.260
Epoch: 180, Train Loss: 1.150, Val f1_micro: 0.258
Epoch: 200, Train Loss: 1.114, Val f1_micro: 0.262
Epoch: 220, Train Loss: 1.061, Val f1_micro: 0.268
Epoch: 240, Train Loss: 1.015, Val f1_micro: 0.272
Epoch: 260, Train Loss: 0.945, Val f1_micro: 0.272
Epoch: 280, Train Loss: 0.917, Val f1_micro: 0.281
Epoch: 300, Train Loss: 0.869, Val f1_micro: 0.279
Epoch: 320, Train Loss: 0.840, Val f1_micro: 0.285
Epoch: 340, Train Loss: 0.816, Val f1_micro: 0.285
Epoch: 360, Train Loss: 0.753, Val f1_micro: 0.289
Epoch: 380, Train Loss: 0.742, Val f1_micro: 0.288
Epoch: 400, Train Loss: 0.709, Val f1_micro: 0.295
Epoch: 420, Train Loss: 0.682, Val f1_micro: 0.294
Epoch: 440, Train Loss: 0.618, Val f1_micro: 0.297
Epoch: 460, Train Loss: 0.631, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.600, Val f1_micro: 0.298
Epoch: 500, Train Loss: 0.587, Val f1_micro: 0.296
f1-micro: 0.296, f1-macro: 0.291, f1-weighted: 0.297, , roc-auc: 0.669
##### RUN 2 #####
Epoch: 020, Train Loss: 2.000, Val f1_micro: 0.195
Epoch: 040, Train Loss: 1.731, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.605, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.516, Val f1_micro: 0.238
Epoch: 100, Train Loss: 1.435, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.359, Val f1_micro: 0.256
Epoch: 140, Train Loss: 1.286, Val f1_micro: 0.253
Epoch: 160, Train Loss: 1.216, Val f1_micro: 0.257
Epoch: 180, Train Loss: 1.168, Val f1_micro: 0.261
Epoch: 200, Train Loss: 1.126, Val f1_micro: 0.263
Epoch: 220, Train Loss: 1.057, Val f1_micro: 0.269
Epoch: 240, Train Loss: 1.029, Val f1_micro: 0.273
Epoch: 260, Train Loss: 0.971, Val f1_micro: 0.276
Epoch: 280, Train Loss: 0.937, Val f1_micro: 0.277
Epoch: 300, Train Loss: 0.898, Val f1_micro: 0.281
Epoch: 320, Train Loss: 0.864, Val f1_micro: 0.284
Epoch: 340, Train Loss: 0.829, Val f1_micro: 0.287
Epoch: 360, Train Loss: 0.791, Val f1_micro: 0.287
Epoch: 380, Train Loss: 0.776, Val f1_micro: 0.288
Epoch: 400, Train Loss: 0.734, Val f1_micro: 0.289
Epoch: 420, Train Loss: 0.690, Val f1_micro: 0.295
Epoch: 440, Train Loss: 0.661, Val f1_micro: 0.293
Epoch: 460, Train Loss: 0.627, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.603, Val f1_micro: 0.297
Epoch: 500, Train Loss: 0.587, Val f1_micro: 0.298
f1-micro: 0.298, f1-macro: 0.293, f1-weighted: 0.299, , roc-auc: 0.668
##### RUN 3 #####
Epoch: 020, Train Loss: 2.009, Val f1_micro: 0.200
Epoch: 040, Train Loss: 1.741, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.601, Val f1_micro: 0.231
Epoch: 080, Train Loss: 1.522, Val f1_micro: 0.232
Epoch: 100, Train Loss: 1.441, Val f1_micro: 0.244
Epoch: 120, Train Loss: 1.356, Val f1_micro: 0.248
Epoch: 140, Train Loss: 1.264, Val f1_micro: 0.252
Epoch: 160, Train Loss: 1.205, Val f1_micro: 0.259
Epoch: 180, Train Loss: 1.150, Val f1_micro: 0.265
Epoch: 200, Train Loss: 1.124, Val f1_micro: 0.268
Epoch: 220, Train Loss: 1.073, Val f1_micro: 0.269
Epoch: 240, Train Loss: 0.996, Val f1_micro: 0.276
Epoch: 260, Train Loss: 0.964, Val f1_micro: 0.275
Epoch: 280, Train Loss: 0.932, Val f1_micro: 0.282
Epoch: 300, Train Loss: 0.897, Val f1_micro: 0.277
Epoch: 320, Train Loss: 0.829, Val f1_micro: 0.290
Epoch: 340, Train Loss: 0.796, Val f1_micro: 0.283
Epoch: 360, Train Loss: 0.758, Val f1_micro: 0.290
Epoch: 380, Train Loss: 0.747, Val f1_micro: 0.292
Epoch: 400, Train Loss: 0.707, Val f1_micro: 0.292
Epoch: 420, Train Loss: 0.683, Val f1_micro: 0.289
Epoch: 440, Train Loss: 0.639, Val f1_micro: 0.297
Epoch: 460, Train Loss: 0.627, Val f1_micro: 0.296
Epoch: 480, Train Loss: 0.605, Val f1_micro: 0.293
Epoch: 500, Train Loss: 0.589, Val f1_micro: 0.300
f1-micro: 0.300, f1-macro: 0.295, f1-weighted: 0.301, , roc-auc: 0.669
##### RUN 4 #####
Epoch: 020, Train Loss: 1.987, Val f1_micro: 0.183
Epoch: 040, Train Loss: 1.733, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.632, Val f1_micro: 0.231
Epoch: 080, Train Loss: 1.515, Val f1_micro: 0.240
Epoch: 100, Train Loss: 1.409, Val f1_micro: 0.244
Epoch: 120, Train Loss: 1.328, Val f1_micro: 0.246
Epoch: 140, Train Loss: 1.307, Val f1_micro: 0.256
Epoch: 160, Train Loss: 1.211, Val f1_micro: 0.262
Epoch: 180, Train Loss: 1.173, Val f1_micro: 0.264
Epoch: 200, Train Loss: 1.128, Val f1_micro: 0.266
Epoch: 220, Train Loss: 1.059, Val f1_micro: 0.271
Epoch: 240, Train Loss: 1.001, Val f1_micro: 0.272
Epoch: 260, Train Loss: 0.965, Val f1_micro: 0.276
Epoch: 280, Train Loss: 0.922, Val f1_micro: 0.279
Epoch: 300, Train Loss: 0.874, Val f1_micro: 0.280
Epoch: 320, Train Loss: 0.850, Val f1_micro: 0.276
Epoch: 340, Train Loss: 0.794, Val f1_micro: 0.286
Epoch: 360, Train Loss: 0.773, Val f1_micro: 0.286
Epoch: 380, Train Loss: 0.725, Val f1_micro: 0.293
Epoch: 400, Train Loss: 0.709, Val f1_micro: 0.287
Epoch: 420, Train Loss: 0.695, Val f1_micro: 0.293
Epoch: 440, Train Loss: 0.662, Val f1_micro: 0.292
Epoch: 460, Train Loss: 0.647, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.603, Val f1_micro: 0.297
Epoch: 500, Train Loss: 0.586, Val f1_micro: 0.299
f1-micro: 0.299, f1-macro: 0.293, f1-weighted: 0.299, , roc-auc: 0.668
##### RUN 5 #####
Epoch: 020, Train Loss: 2.020, Val f1_micro: 0.196
Epoch: 040, Train Loss: 1.733, Val f1_micro: 0.210
Epoch: 060, Train Loss: 1.627, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.507, Val f1_micro: 0.242
Epoch: 100, Train Loss: 1.421, Val f1_micro: 0.248
Epoch: 120, Train Loss: 1.345, Val f1_micro: 0.252
Epoch: 140, Train Loss: 1.271, Val f1_micro: 0.254
Epoch: 160, Train Loss: 1.238, Val f1_micro: 0.256
Epoch: 180, Train Loss: 1.157, Val f1_micro: 0.266
Epoch: 200, Train Loss: 1.090, Val f1_micro: 0.265
Epoch: 220, Train Loss: 1.073, Val f1_micro: 0.272
Epoch: 240, Train Loss: 1.005, Val f1_micro: 0.271
Epoch: 260, Train Loss: 0.978, Val f1_micro: 0.277
Epoch: 280, Train Loss: 0.934, Val f1_micro: 0.276
Epoch: 300, Train Loss: 0.896, Val f1_micro: 0.276
Epoch: 320, Train Loss: 0.846, Val f1_micro: 0.281
Epoch: 340, Train Loss: 0.821, Val f1_micro: 0.283
Epoch: 360, Train Loss: 0.775, Val f1_micro: 0.289
Epoch: 380, Train Loss: 0.729, Val f1_micro: 0.290
Epoch: 400, Train Loss: 0.708, Val f1_micro: 0.289
Epoch: 420, Train Loss: 0.680, Val f1_micro: 0.292
Epoch: 440, Train Loss: 0.654, Val f1_micro: 0.294
Epoch: 460, Train Loss: 0.635, Val f1_micro: 0.295
Epoch: 480, Train Loss: 0.620, Val f1_micro: 0.290
Epoch: 500, Train Loss: 0.591, Val f1_micro: 0.296
f1-micro: 0.296, f1-macro: 0.289, f1-weighted: 0.295, , roc-auc: 0.667
########## Hyperparameters combination ##########
(512, 0.7, 0.005, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.986, Val f1_micro: 0.196
Epoch: 040, Train Loss: 1.752, Val f1_micro: 0.223
Epoch: 060, Train Loss: 1.623, Val f1_micro: 0.227
Epoch: 080, Train Loss: 1.524, Val f1_micro: 0.246
Epoch: 100, Train Loss: 1.483, Val f1_micro: 0.243
Epoch: 120, Train Loss: 1.424, Val f1_micro: 0.244
Epoch: 140, Train Loss: 1.372, Val f1_micro: 0.244
Epoch: 160, Train Loss: 1.322, Val f1_micro: 0.255
Epoch: 180, Train Loss: 1.306, Val f1_micro: 0.259
Epoch: 200, Train Loss: 1.241, Val f1_micro: 0.266
Epoch: 220, Train Loss: 1.209, Val f1_micro: 0.264
Epoch: 240, Train Loss: 1.157, Val f1_micro: 0.263
Epoch: 260, Train Loss: 1.141, Val f1_micro: 0.270
Epoch: 280, Train Loss: 1.121, Val f1_micro: 0.266
Epoch: 300, Train Loss: 1.075, Val f1_micro: 0.271
Epoch: 320, Train Loss: 1.058, Val f1_micro: 0.269
Epoch: 340, Train Loss: 1.027, Val f1_micro: 0.275
Epoch: 360, Train Loss: 1.015, Val f1_micro: 0.276
Epoch: 380, Train Loss: 0.975, Val f1_micro: 0.275
Epoch: 400, Train Loss: 0.978, Val f1_micro: 0.277
Epoch: 420, Train Loss: 0.959, Val f1_micro: 0.277
Epoch: 440, Train Loss: 0.930, Val f1_micro: 0.277
Epoch: 460, Train Loss: 0.922, Val f1_micro: 0.279
Epoch: 480, Train Loss: 0.891, Val f1_micro: 0.283
Epoch: 500, Train Loss: 0.895, Val f1_micro: 0.283
f1-micro: 0.283, f1-macro: 0.276, f1-weighted: 0.281, , roc-auc: 0.663
##### RUN 2 #####
Epoch: 020, Train Loss: 1.989, Val f1_micro: 0.201
Epoch: 040, Train Loss: 1.764, Val f1_micro: 0.224
Epoch: 060, Train Loss: 1.618, Val f1_micro: 0.234
Epoch: 080, Train Loss: 1.537, Val f1_micro: 0.233
Epoch: 100, Train Loss: 1.475, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.390, Val f1_micro: 0.252
Epoch: 140, Train Loss: 1.361, Val f1_micro: 0.250
Epoch: 160, Train Loss: 1.319, Val f1_micro: 0.259
Epoch: 180, Train Loss: 1.268, Val f1_micro: 0.263
Epoch: 200, Train Loss: 1.261, Val f1_micro: 0.265
Epoch: 220, Train Loss: 1.197, Val f1_micro: 0.260
Epoch: 240, Train Loss: 1.155, Val f1_micro: 0.265
Epoch: 260, Train Loss: 1.114, Val f1_micro: 0.267
Epoch: 280, Train Loss: 1.095, Val f1_micro: 0.267
Epoch: 300, Train Loss: 1.076, Val f1_micro: 0.273
Epoch: 320, Train Loss: 1.069, Val f1_micro: 0.273
Epoch: 340, Train Loss: 1.033, Val f1_micro: 0.273
Epoch: 360, Train Loss: 1.009, Val f1_micro: 0.275
Epoch: 380, Train Loss: 0.992, Val f1_micro: 0.273
Epoch: 400, Train Loss: 0.953, Val f1_micro: 0.279
Epoch: 420, Train Loss: 0.960, Val f1_micro: 0.282
Epoch: 440, Train Loss: 0.926, Val f1_micro: 0.281
Epoch: 460, Train Loss: 0.908, Val f1_micro: 0.284
Epoch: 480, Train Loss: 0.894, Val f1_micro: 0.284
Epoch: 500, Train Loss: 0.873, Val f1_micro: 0.285
f1-micro: 0.285, f1-macro: 0.279, f1-weighted: 0.284, , roc-auc: 0.662
##### RUN 3 #####
Epoch: 020, Train Loss: 2.039, Val f1_micro: 0.205
Epoch: 040, Train Loss: 1.768, Val f1_micro: 0.218
Epoch: 060, Train Loss: 1.625, Val f1_micro: 0.234
Epoch: 080, Train Loss: 1.524, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.489, Val f1_micro: 0.251
Epoch: 120, Train Loss: 1.415, Val f1_micro: 0.249
Epoch: 140, Train Loss: 1.376, Val f1_micro: 0.247
Epoch: 160, Train Loss: 1.321, Val f1_micro: 0.254
Epoch: 180, Train Loss: 1.271, Val f1_micro: 0.256
Epoch: 200, Train Loss: 1.250, Val f1_micro: 0.257
Epoch: 220, Train Loss: 1.214, Val f1_micro: 0.270
Epoch: 240, Train Loss: 1.168, Val f1_micro: 0.267
Epoch: 260, Train Loss: 1.121, Val f1_micro: 0.267
Epoch: 280, Train Loss: 1.125, Val f1_micro: 0.269
Epoch: 300, Train Loss: 1.074, Val f1_micro: 0.271
Epoch: 320, Train Loss: 1.052, Val f1_micro: 0.274
Epoch: 340, Train Loss: 1.035, Val f1_micro: 0.276
Epoch: 360, Train Loss: 1.017, Val f1_micro: 0.277
Epoch: 380, Train Loss: 0.959, Val f1_micro: 0.277
Epoch: 400, Train Loss: 0.978, Val f1_micro: 0.278
Epoch: 420, Train Loss: 0.946, Val f1_micro: 0.279
Epoch: 440, Train Loss: 0.938, Val f1_micro: 0.282
Epoch: 460, Train Loss: 0.911, Val f1_micro: 0.284
Epoch: 480, Train Loss: 0.921, Val f1_micro: 0.284
Epoch: 500, Train Loss: 0.894, Val f1_micro: 0.284
f1-micro: 0.284, f1-macro: 0.275, f1-weighted: 0.280, , roc-auc: 0.660
##### RUN 4 #####
Epoch: 020, Train Loss: 1.998, Val f1_micro: 0.201
Epoch: 040, Train Loss: 1.761, Val f1_micro: 0.220
Epoch: 060, Train Loss: 1.616, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.540, Val f1_micro: 0.243
Epoch: 100, Train Loss: 1.463, Val f1_micro: 0.248
Epoch: 120, Train Loss: 1.404, Val f1_micro: 0.250
Epoch: 140, Train Loss: 1.350, Val f1_micro: 0.255
Epoch: 160, Train Loss: 1.316, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.252, Val f1_micro: 0.256
Epoch: 200, Train Loss: 1.228, Val f1_micro: 0.265
Epoch: 220, Train Loss: 1.184, Val f1_micro: 0.267
Epoch: 240, Train Loss: 1.187, Val f1_micro: 0.268
Epoch: 260, Train Loss: 1.126, Val f1_micro: 0.273
Epoch: 280, Train Loss: 1.104, Val f1_micro: 0.269
Epoch: 300, Train Loss: 1.080, Val f1_micro: 0.275
Epoch: 320, Train Loss: 1.038, Val f1_micro: 0.278
Epoch: 340, Train Loss: 1.027, Val f1_micro: 0.277
Epoch: 360, Train Loss: 0.987, Val f1_micro: 0.278
Epoch: 380, Train Loss: 0.972, Val f1_micro: 0.278
Epoch: 400, Train Loss: 0.967, Val f1_micro: 0.282
Epoch: 420, Train Loss: 0.962, Val f1_micro: 0.283
Epoch: 440, Train Loss: 0.927, Val f1_micro: 0.284
Epoch: 460, Train Loss: 0.904, Val f1_micro: 0.287
Epoch: 480, Train Loss: 0.898, Val f1_micro: 0.285
Epoch: 500, Train Loss: 0.883, Val f1_micro: 0.288
f1-micro: 0.288, f1-macro: 0.280, f1-weighted: 0.286, , roc-auc: 0.662
##### RUN 5 #####
Epoch: 020, Train Loss: 2.013, Val f1_micro: 0.207
Epoch: 040, Train Loss: 1.782, Val f1_micro: 0.224
Epoch: 060, Train Loss: 1.625, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.543, Val f1_micro: 0.238
Epoch: 100, Train Loss: 1.461, Val f1_micro: 0.250
Epoch: 120, Train Loss: 1.412, Val f1_micro: 0.243
Epoch: 140, Train Loss: 1.363, Val f1_micro: 0.253
Epoch: 160, Train Loss: 1.299, Val f1_micro: 0.253
Epoch: 180, Train Loss: 1.276, Val f1_micro: 0.263
Epoch: 200, Train Loss: 1.230, Val f1_micro: 0.267
Epoch: 220, Train Loss: 1.194, Val f1_micro: 0.266
Epoch: 240, Train Loss: 1.175, Val f1_micro: 0.266
Epoch: 260, Train Loss: 1.147, Val f1_micro: 0.267
Epoch: 280, Train Loss: 1.072, Val f1_micro: 0.272
Epoch: 300, Train Loss: 1.102, Val f1_micro: 0.273
Epoch: 320, Train Loss: 1.048, Val f1_micro: 0.273
Epoch: 340, Train Loss: 1.003, Val f1_micro: 0.275
Epoch: 360, Train Loss: 1.008, Val f1_micro: 0.274
Epoch: 380, Train Loss: 0.994, Val f1_micro: 0.280
Epoch: 400, Train Loss: 0.976, Val f1_micro: 0.283
Epoch: 420, Train Loss: 0.949, Val f1_micro: 0.284
Epoch: 440, Train Loss: 0.936, Val f1_micro: 0.281
Epoch: 460, Train Loss: 0.921, Val f1_micro: 0.280
Epoch: 480, Train Loss: 0.898, Val f1_micro: 0.286
Epoch: 500, Train Loss: 0.893, Val f1_micro: 0.285
f1-micro: 0.285, f1-macro: 0.278, f1-weighted: 0.283, , roc-auc: 0.662
########## Hyperparameters combination ##########
(512, 0.7, 0.005, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.061, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.761, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.652, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.567, Val f1_micro: 0.231
Epoch: 100, Train Loss: 1.504, Val f1_micro: 0.239
Epoch: 120, Train Loss: 1.480, Val f1_micro: 0.236
Epoch: 140, Train Loss: 1.445, Val f1_micro: 0.244
Epoch: 160, Train Loss: 1.413, Val f1_micro: 0.245
Epoch: 180, Train Loss: 1.382, Val f1_micro: 0.245
Epoch: 200, Train Loss: 1.352, Val f1_micro: 0.252
Epoch: 220, Train Loss: 1.318, Val f1_micro: 0.253
Epoch: 240, Train Loss: 1.300, Val f1_micro: 0.258
Epoch: 260, Train Loss: 1.309, Val f1_micro: 0.250
Epoch: 280, Train Loss: 1.275, Val f1_micro: 0.260
Epoch: 300, Train Loss: 1.246, Val f1_micro: 0.249
Epoch: 320, Train Loss: 1.225, Val f1_micro: 0.256
Epoch: 340, Train Loss: 1.228, Val f1_micro: 0.264
Epoch: 360, Train Loss: 1.197, Val f1_micro: 0.261
Epoch: 380, Train Loss: 1.181, Val f1_micro: 0.266
Epoch: 400, Train Loss: 1.184, Val f1_micro: 0.258
Epoch: 420, Train Loss: 1.165, Val f1_micro: 0.263
Epoch: 440, Train Loss: 1.154, Val f1_micro: 0.262
Epoch: 460, Train Loss: 1.147, Val f1_micro: 0.267
Epoch: 480, Train Loss: 1.130, Val f1_micro: 0.269
Epoch: 500, Train Loss: 1.123, Val f1_micro: 0.268
f1-micro: 0.268, f1-macro: 0.260, f1-weighted: 0.264, , roc-auc: 0.653
##### RUN 2 #####
Epoch: 020, Train Loss: 2.078, Val f1_micro: 0.177
Epoch: 040, Train Loss: 1.779, Val f1_micro: 0.207
Epoch: 060, Train Loss: 1.653, Val f1_micro: 0.222
Epoch: 080, Train Loss: 1.572, Val f1_micro: 0.219
Epoch: 100, Train Loss: 1.534, Val f1_micro: 0.235
Epoch: 120, Train Loss: 1.492, Val f1_micro: 0.234
Epoch: 140, Train Loss: 1.442, Val f1_micro: 0.247
Epoch: 160, Train Loss: 1.408, Val f1_micro: 0.244
Epoch: 180, Train Loss: 1.379, Val f1_micro: 0.240
Epoch: 200, Train Loss: 1.357, Val f1_micro: 0.242
Epoch: 220, Train Loss: 1.329, Val f1_micro: 0.251
Epoch: 240, Train Loss: 1.306, Val f1_micro: 0.246
Epoch: 260, Train Loss: 1.301, Val f1_micro: 0.251
Epoch: 280, Train Loss: 1.264, Val f1_micro: 0.256
Epoch: 300, Train Loss: 1.255, Val f1_micro: 0.253
Epoch: 320, Train Loss: 1.237, Val f1_micro: 0.259
Epoch: 340, Train Loss: 1.217, Val f1_micro: 0.262
Epoch: 360, Train Loss: 1.199, Val f1_micro: 0.262
Epoch: 380, Train Loss: 1.189, Val f1_micro: 0.266
Epoch: 400, Train Loss: 1.164, Val f1_micro: 0.265
Epoch: 420, Train Loss: 1.165, Val f1_micro: 0.266
Epoch: 440, Train Loss: 1.141, Val f1_micro: 0.270
Epoch: 460, Train Loss: 1.152, Val f1_micro: 0.260
Epoch: 480, Train Loss: 1.135, Val f1_micro: 0.270
Epoch: 500, Train Loss: 1.126, Val f1_micro: 0.271
f1-micro: 0.271, f1-macro: 0.261, f1-weighted: 0.265, , roc-auc: 0.652
##### RUN 3 #####
Epoch: 020, Train Loss: 2.017, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.792, Val f1_micro: 0.206
Epoch: 060, Train Loss: 1.631, Val f1_micro: 0.224
Epoch: 080, Train Loss: 1.597, Val f1_micro: 0.232
Epoch: 100, Train Loss: 1.534, Val f1_micro: 0.237
Epoch: 120, Train Loss: 1.492, Val f1_micro: 0.240
Epoch: 140, Train Loss: 1.441, Val f1_micro: 0.245
Epoch: 160, Train Loss: 1.405, Val f1_micro: 0.242
Epoch: 180, Train Loss: 1.391, Val f1_micro: 0.247
Epoch: 200, Train Loss: 1.355, Val f1_micro: 0.253
Epoch: 220, Train Loss: 1.319, Val f1_micro: 0.247
Epoch: 240, Train Loss: 1.308, Val f1_micro: 0.254
Epoch: 260, Train Loss: 1.281, Val f1_micro: 0.251
Epoch: 280, Train Loss: 1.290, Val f1_micro: 0.251
Epoch: 300, Train Loss: 1.259, Val f1_micro: 0.266
Epoch: 320, Train Loss: 1.226, Val f1_micro: 0.262
Epoch: 340, Train Loss: 1.215, Val f1_micro: 0.255
Epoch: 360, Train Loss: 1.184, Val f1_micro: 0.262
Epoch: 380, Train Loss: 1.182, Val f1_micro: 0.264
Epoch: 400, Train Loss: 1.177, Val f1_micro: 0.265
Epoch: 420, Train Loss: 1.162, Val f1_micro: 0.264
Epoch: 440, Train Loss: 1.146, Val f1_micro: 0.264
Epoch: 460, Train Loss: 1.128, Val f1_micro: 0.270
Epoch: 480, Train Loss: 1.120, Val f1_micro: 0.268
Epoch: 500, Train Loss: 1.126, Val f1_micro: 0.265
f1-micro: 0.265, f1-macro: 0.257, f1-weighted: 0.261, , roc-auc: 0.651
##### RUN 4 #####
Epoch: 020, Train Loss: 2.036, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.758, Val f1_micro: 0.198
Epoch: 060, Train Loss: 1.666, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.579, Val f1_micro: 0.234
Epoch: 100, Train Loss: 1.534, Val f1_micro: 0.233
Epoch: 120, Train Loss: 1.468, Val f1_micro: 0.243
Epoch: 140, Train Loss: 1.426, Val f1_micro: 0.240
Epoch: 160, Train Loss: 1.415, Val f1_micro: 0.238
Epoch: 180, Train Loss: 1.391, Val f1_micro: 0.243
Epoch: 200, Train Loss: 1.363, Val f1_micro: 0.242
Epoch: 220, Train Loss: 1.322, Val f1_micro: 0.248
Epoch: 240, Train Loss: 1.296, Val f1_micro: 0.248
Epoch: 260, Train Loss: 1.284, Val f1_micro: 0.246
Epoch: 280, Train Loss: 1.239, Val f1_micro: 0.249
Epoch: 300, Train Loss: 1.251, Val f1_micro: 0.257
Epoch: 320, Train Loss: 1.242, Val f1_micro: 0.258
Epoch: 340, Train Loss: 1.228, Val f1_micro: 0.259
Epoch: 360, Train Loss: 1.222, Val f1_micro: 0.255
Epoch: 380, Train Loss: 1.194, Val f1_micro: 0.250
Epoch: 400, Train Loss: 1.197, Val f1_micro: 0.260
Epoch: 420, Train Loss: 1.151, Val f1_micro: 0.265
Epoch: 440, Train Loss: 1.160, Val f1_micro: 0.264
Epoch: 460, Train Loss: 1.156, Val f1_micro: 0.262
Epoch: 480, Train Loss: 1.143, Val f1_micro: 0.268
Epoch: 500, Train Loss: 1.110, Val f1_micro: 0.267
f1-micro: 0.267, f1-macro: 0.259, f1-weighted: 0.262, , roc-auc: 0.653
##### RUN 5 #####
Epoch: 020, Train Loss: 2.022, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.779, Val f1_micro: 0.208
Epoch: 060, Train Loss: 1.649, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.570, Val f1_micro: 0.221
Epoch: 100, Train Loss: 1.504, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.507, Val f1_micro: 0.239
Epoch: 140, Train Loss: 1.455, Val f1_micro: 0.240
Epoch: 160, Train Loss: 1.432, Val f1_micro: 0.240
Epoch: 180, Train Loss: 1.375, Val f1_micro: 0.240
Epoch: 200, Train Loss: 1.339, Val f1_micro: 0.243
Epoch: 220, Train Loss: 1.320, Val f1_micro: 0.251
Epoch: 240, Train Loss: 1.302, Val f1_micro: 0.249
Epoch: 260, Train Loss: 1.270, Val f1_micro: 0.253
Epoch: 280, Train Loss: 1.253, Val f1_micro: 0.252
Epoch: 300, Train Loss: 1.249, Val f1_micro: 0.261
Epoch: 320, Train Loss: 1.213, Val f1_micro: 0.253
Epoch: 340, Train Loss: 1.203, Val f1_micro: 0.263
Epoch: 360, Train Loss: 1.191, Val f1_micro: 0.257
Epoch: 380, Train Loss: 1.176, Val f1_micro: 0.259
Epoch: 400, Train Loss: 1.165, Val f1_micro: 0.263
Epoch: 420, Train Loss: 1.173, Val f1_micro: 0.262
Epoch: 440, Train Loss: 1.154, Val f1_micro: 0.266
Epoch: 460, Train Loss: 1.122, Val f1_micro: 0.266
Epoch: 480, Train Loss: 1.130, Val f1_micro: 0.271
Epoch: 500, Train Loss: 1.112, Val f1_micro: 0.272
f1-micro: 0.272, f1-macro: 0.262, f1-weighted: 0.266, , roc-auc: 0.653
########## Hyperparameters combination ##########
(512, 0.7, 0.005, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.001, Val f1_micro: 0.201
Epoch: 040, Train Loss: 1.788, Val f1_micro: 0.220
Epoch: 060, Train Loss: 1.742, Val f1_micro: 0.214
Epoch: 080, Train Loss: 1.750, Val f1_micro: 0.222
Epoch: 100, Train Loss: 1.729, Val f1_micro: 0.226
Epoch: 120, Train Loss: 1.733, Val f1_micro: 0.219
Epoch: 140, Train Loss: 1.741, Val f1_micro: 0.219
Epoch: 160, Train Loss: 1.747, Val f1_micro: 0.222
Epoch: 180, Train Loss: 1.750, Val f1_micro: 0.220
Epoch: 200, Train Loss: 1.743, Val f1_micro: 0.211
Epoch: 220, Train Loss: 1.754, Val f1_micro: 0.200
Epoch: 240, Train Loss: 1.766, Val f1_micro: 0.209
Epoch: 260, Train Loss: 1.771, Val f1_micro: 0.212
Epoch: 280, Train Loss: 1.760, Val f1_micro: 0.211
Epoch: 300, Train Loss: 1.774, Val f1_micro: 0.210
Epoch: 320, Train Loss: 1.761, Val f1_micro: 0.215
Epoch: 340, Train Loss: 1.762, Val f1_micro: 0.212
Epoch: 360, Train Loss: 1.778, Val f1_micro: 0.209
Epoch: 380, Train Loss: 1.763, Val f1_micro: 0.197
Epoch: 400, Train Loss: 1.768, Val f1_micro: 0.218
Epoch: 420, Train Loss: 1.778, Val f1_micro: 0.208
Epoch: 440, Train Loss: 1.780, Val f1_micro: 0.206
Epoch: 460, Train Loss: 1.764, Val f1_micro: 0.213
Epoch: 480, Train Loss: 1.765, Val f1_micro: 0.204
Epoch: 500, Train Loss: 1.779, Val f1_micro: 0.203
f1-micro: 0.203, f1-macro: 0.164, f1-weighted: 0.165, , roc-auc: 0.636
##### RUN 2 #####
Epoch: 020, Train Loss: 1.990, Val f1_micro: 0.199
Epoch: 040, Train Loss: 1.802, Val f1_micro: 0.202
Epoch: 060, Train Loss: 1.736, Val f1_micro: 0.223
Epoch: 080, Train Loss: 1.744, Val f1_micro: 0.217
Epoch: 100, Train Loss: 1.722, Val f1_micro: 0.224
Epoch: 120, Train Loss: 1.741, Val f1_micro: 0.220
Epoch: 140, Train Loss: 1.745, Val f1_micro: 0.214
Epoch: 160, Train Loss: 1.743, Val f1_micro: 0.212
Epoch: 180, Train Loss: 1.761, Val f1_micro: 0.217
Epoch: 200, Train Loss: 1.752, Val f1_micro: 0.215
Epoch: 220, Train Loss: 1.755, Val f1_micro: 0.221
Epoch: 240, Train Loss: 1.763, Val f1_micro: 0.212
Epoch: 260, Train Loss: 1.759, Val f1_micro: 0.210
Epoch: 280, Train Loss: 1.761, Val f1_micro: 0.211
Epoch: 300, Train Loss: 1.766, Val f1_micro: 0.216
Epoch: 320, Train Loss: 1.767, Val f1_micro: 0.210
Epoch: 340, Train Loss: 1.766, Val f1_micro: 0.217
Epoch: 360, Train Loss: 1.762, Val f1_micro: 0.217
Epoch: 380, Train Loss: 1.771, Val f1_micro: 0.195
Epoch: 400, Train Loss: 1.781, Val f1_micro: 0.209
Epoch: 420, Train Loss: 1.787, Val f1_micro: 0.216
Epoch: 440, Train Loss: 1.772, Val f1_micro: 0.214
Epoch: 460, Train Loss: 1.765, Val f1_micro: 0.214
Epoch: 480, Train Loss: 1.768, Val f1_micro: 0.217
Epoch: 500, Train Loss: 1.779, Val f1_micro: 0.217
f1-micro: 0.217, f1-macro: 0.171, f1-weighted: 0.173, , roc-auc: 0.633
##### RUN 3 #####
Epoch: 020, Train Loss: 1.998, Val f1_micro: 0.205
Epoch: 040, Train Loss: 1.789, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.762, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.732, Val f1_micro: 0.224
Epoch: 100, Train Loss: 1.727, Val f1_micro: 0.224
Epoch: 120, Train Loss: 1.742, Val f1_micro: 0.226
Epoch: 140, Train Loss: 1.723, Val f1_micro: 0.216
Epoch: 160, Train Loss: 1.754, Val f1_micro: 0.220
Epoch: 180, Train Loss: 1.747, Val f1_micro: 0.220
Epoch: 200, Train Loss: 1.757, Val f1_micro: 0.217
Epoch: 220, Train Loss: 1.748, Val f1_micro: 0.216
Epoch: 240, Train Loss: 1.756, Val f1_micro: 0.217
Epoch: 260, Train Loss: 1.771, Val f1_micro: 0.216
Epoch: 280, Train Loss: 1.763, Val f1_micro: 0.217
Epoch: 300, Train Loss: 1.777, Val f1_micro: 0.217
Epoch: 320, Train Loss: 1.769, Val f1_micro: 0.220
Epoch: 340, Train Loss: 1.770, Val f1_micro: 0.217
Epoch: 360, Train Loss: 1.782, Val f1_micro: 0.212
Epoch: 380, Train Loss: 1.770, Val f1_micro: 0.209
Epoch: 400, Train Loss: 1.772, Val f1_micro: 0.215
Epoch: 420, Train Loss: 1.769, Val f1_micro: 0.216
Epoch: 440, Train Loss: 1.778, Val f1_micro: 0.214
Epoch: 460, Train Loss: 1.759, Val f1_micro: 0.204
Epoch: 480, Train Loss: 1.771, Val f1_micro: 0.203
Epoch: 500, Train Loss: 1.772, Val f1_micro: 0.212
f1-micro: 0.212, f1-macro: 0.166, f1-weighted: 0.168, , roc-auc: 0.632
##### RUN 4 #####
Epoch: 020, Train Loss: 1.996, Val f1_micro: 0.202
Epoch: 040, Train Loss: 1.808, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.750, Val f1_micro: 0.217
Epoch: 080, Train Loss: 1.724, Val f1_micro: 0.224
Epoch: 100, Train Loss: 1.735, Val f1_micro: 0.220
Epoch: 120, Train Loss: 1.734, Val f1_micro: 0.220
Epoch: 140, Train Loss: 1.738, Val f1_micro: 0.223
Epoch: 160, Train Loss: 1.748, Val f1_micro: 0.218
Epoch: 180, Train Loss: 1.755, Val f1_micro: 0.217
Epoch: 200, Train Loss: 1.745, Val f1_micro: 0.211
Epoch: 220, Train Loss: 1.752, Val f1_micro: 0.215
Epoch: 240, Train Loss: 1.780, Val f1_micro: 0.207
Epoch: 260, Train Loss: 1.762, Val f1_micro: 0.213
Epoch: 280, Train Loss: 1.787, Val f1_micro: 0.212
Epoch: 300, Train Loss: 1.770, Val f1_micro: 0.210
Epoch: 320, Train Loss: 1.791, Val f1_micro: 0.201
Epoch: 340, Train Loss: 1.775, Val f1_micro: 0.210
Epoch: 360, Train Loss: 1.776, Val f1_micro: 0.211
Epoch: 380, Train Loss: 1.771, Val f1_micro: 0.208
Epoch: 400, Train Loss: 1.773, Val f1_micro: 0.209
Epoch: 420, Train Loss: 1.772, Val f1_micro: 0.209
Epoch: 440, Train Loss: 1.757, Val f1_micro: 0.211
Epoch: 460, Train Loss: 1.764, Val f1_micro: 0.209
Epoch: 480, Train Loss: 1.770, Val f1_micro: 0.205
Epoch: 500, Train Loss: 1.769, Val f1_micro: 0.209
f1-micro: 0.209, f1-macro: 0.171, f1-weighted: 0.171, , roc-auc: 0.633
##### RUN 5 #####
Epoch: 020, Train Loss: 2.010, Val f1_micro: 0.198
Epoch: 040, Train Loss: 1.793, Val f1_micro: 0.222
Epoch: 060, Train Loss: 1.748, Val f1_micro: 0.224
Epoch: 080, Train Loss: 1.740, Val f1_micro: 0.217
Epoch: 100, Train Loss: 1.717, Val f1_micro: 0.216
Epoch: 120, Train Loss: 1.725, Val f1_micro: 0.218
Epoch: 140, Train Loss: 1.744, Val f1_micro: 0.213
Epoch: 160, Train Loss: 1.754, Val f1_micro: 0.215
Epoch: 180, Train Loss: 1.752, Val f1_micro: 0.213
Epoch: 200, Train Loss: 1.738, Val f1_micro: 0.215
Epoch: 220, Train Loss: 1.762, Val f1_micro: 0.221
Epoch: 240, Train Loss: 1.755, Val f1_micro: 0.210
Epoch: 260, Train Loss: 1.751, Val f1_micro: 0.217
Epoch: 280, Train Loss: 1.766, Val f1_micro: 0.216
Epoch: 300, Train Loss: 1.764, Val f1_micro: 0.214
Epoch: 320, Train Loss: 1.769, Val f1_micro: 0.217
Epoch: 340, Train Loss: 1.776, Val f1_micro: 0.214
Epoch: 360, Train Loss: 1.748, Val f1_micro: 0.213
Epoch: 380, Train Loss: 1.763, Val f1_micro: 0.209
Epoch: 400, Train Loss: 1.770, Val f1_micro: 0.211
Epoch: 420, Train Loss: 1.795, Val f1_micro: 0.211
Epoch: 440, Train Loss: 1.765, Val f1_micro: 0.216
Epoch: 460, Train Loss: 1.762, Val f1_micro: 0.215
Epoch: 480, Train Loss: 1.765, Val f1_micro: 0.210
Epoch: 500, Train Loss: 1.767, Val f1_micro: 0.210
f1-micro: 0.210, f1-macro: 0.172, f1-weighted: 0.174, , roc-auc: 0.636
########## Hyperparameters combination ##########
(512, 0.7, 0.01, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.932, Val f1_micro: 0.164
Epoch: 040, Train Loss: 1.722, Val f1_micro: 0.205
Epoch: 060, Train Loss: 1.562, Val f1_micro: 0.235
Epoch: 080, Train Loss: 1.451, Val f1_micro: 0.242
Epoch: 100, Train Loss: 1.355, Val f1_micro: 0.252
Epoch: 120, Train Loss: 1.261, Val f1_micro: 0.249
Epoch: 140, Train Loss: 1.162, Val f1_micro: 0.259
Epoch: 160, Train Loss: 1.112, Val f1_micro: 0.260
Epoch: 180, Train Loss: 1.041, Val f1_micro: 0.266
Epoch: 200, Train Loss: 0.997, Val f1_micro: 0.276
Epoch: 220, Train Loss: 0.927, Val f1_micro: 0.278
Epoch: 240, Train Loss: 0.868, Val f1_micro: 0.285
Epoch: 260, Train Loss: 0.814, Val f1_micro: 0.289
Epoch: 280, Train Loss: 0.760, Val f1_micro: 0.286
Epoch: 300, Train Loss: 0.716, Val f1_micro: 0.294
Epoch: 320, Train Loss: 0.683, Val f1_micro: 0.295
Epoch: 340, Train Loss: 0.670, Val f1_micro: 0.297
Epoch: 360, Train Loss: 0.610, Val f1_micro: 0.296
Epoch: 380, Train Loss: 0.582, Val f1_micro: 0.303
Epoch: 400, Train Loss: 0.570, Val f1_micro: 0.301
Epoch: 420, Train Loss: 0.536, Val f1_micro: 0.304
Epoch: 440, Train Loss: 0.502, Val f1_micro: 0.303
Epoch: 460, Train Loss: 0.496, Val f1_micro: 0.301
Epoch: 480, Train Loss: 0.460, Val f1_micro: 0.304
Epoch: 500, Train Loss: 0.449, Val f1_micro: 0.303
f1-micro: 0.303, f1-macro: 0.297, f1-weighted: 0.304, , roc-auc: 0.668
##### RUN 2 #####
Epoch: 020, Train Loss: 1.955, Val f1_micro: 0.180
Epoch: 040, Train Loss: 1.721, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.564, Val f1_micro: 0.231
Epoch: 080, Train Loss: 1.439, Val f1_micro: 0.243
Epoch: 100, Train Loss: 1.335, Val f1_micro: 0.251
Epoch: 120, Train Loss: 1.266, Val f1_micro: 0.260
Epoch: 140, Train Loss: 1.181, Val f1_micro: 0.263
Epoch: 160, Train Loss: 1.104, Val f1_micro: 0.263
Epoch: 180, Train Loss: 1.042, Val f1_micro: 0.272
Epoch: 200, Train Loss: 0.994, Val f1_micro: 0.276
Epoch: 220, Train Loss: 0.919, Val f1_micro: 0.277
Epoch: 240, Train Loss: 0.877, Val f1_micro: 0.280
Epoch: 260, Train Loss: 0.806, Val f1_micro: 0.282
Epoch: 280, Train Loss: 0.776, Val f1_micro: 0.287
Epoch: 300, Train Loss: 0.722, Val f1_micro: 0.291
Epoch: 320, Train Loss: 0.702, Val f1_micro: 0.292
Epoch: 340, Train Loss: 0.635, Val f1_micro: 0.293
Epoch: 360, Train Loss: 0.616, Val f1_micro: 0.297
Epoch: 380, Train Loss: 0.607, Val f1_micro: 0.300
Epoch: 400, Train Loss: 0.548, Val f1_micro: 0.295
Epoch: 420, Train Loss: 0.532, Val f1_micro: 0.302
Epoch: 440, Train Loss: 0.497, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.514, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.449, Val f1_micro: 0.303
Epoch: 500, Train Loss: 0.461, Val f1_micro: 0.304
f1-micro: 0.304, f1-macro: 0.299, f1-weighted: 0.304, , roc-auc: 0.667
##### RUN 3 #####
Epoch: 020, Train Loss: 1.962, Val f1_micro: 0.175
Epoch: 040, Train Loss: 1.706, Val f1_micro: 0.205
Epoch: 060, Train Loss: 1.561, Val f1_micro: 0.231
Epoch: 080, Train Loss: 1.448, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.329, Val f1_micro: 0.251
Epoch: 120, Train Loss: 1.291, Val f1_micro: 0.255
Epoch: 140, Train Loss: 1.215, Val f1_micro: 0.264
Epoch: 160, Train Loss: 1.149, Val f1_micro: 0.263
Epoch: 180, Train Loss: 1.056, Val f1_micro: 0.268
Epoch: 200, Train Loss: 0.964, Val f1_micro: 0.275
Epoch: 220, Train Loss: 0.958, Val f1_micro: 0.279
Epoch: 240, Train Loss: 0.907, Val f1_micro: 0.282
Epoch: 260, Train Loss: 0.848, Val f1_micro: 0.285
Epoch: 280, Train Loss: 0.806, Val f1_micro: 0.288
Epoch: 300, Train Loss: 0.734, Val f1_micro: 0.290
Epoch: 320, Train Loss: 0.699, Val f1_micro: 0.289
Epoch: 340, Train Loss: 0.674, Val f1_micro: 0.291
Epoch: 360, Train Loss: 0.626, Val f1_micro: 0.296
Epoch: 380, Train Loss: 0.618, Val f1_micro: 0.292
Epoch: 400, Train Loss: 0.590, Val f1_micro: 0.298
Epoch: 420, Train Loss: 0.571, Val f1_micro: 0.301
Epoch: 440, Train Loss: 0.531, Val f1_micro: 0.297
Epoch: 460, Train Loss: 0.501, Val f1_micro: 0.300
Epoch: 480, Train Loss: 0.483, Val f1_micro: 0.299
Epoch: 500, Train Loss: 0.460, Val f1_micro: 0.298
f1-micro: 0.298, f1-macro: 0.292, f1-weighted: 0.298, , roc-auc: 0.666
##### RUN 4 #####
Epoch: 020, Train Loss: 1.928, Val f1_micro: 0.150
Epoch: 040, Train Loss: 1.694, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.537, Val f1_micro: 0.234
Epoch: 080, Train Loss: 1.445, Val f1_micro: 0.242
Epoch: 100, Train Loss: 1.321, Val f1_micro: 0.250
Epoch: 120, Train Loss: 1.256, Val f1_micro: 0.253
Epoch: 140, Train Loss: 1.200, Val f1_micro: 0.260
Epoch: 160, Train Loss: 1.101, Val f1_micro: 0.264
Epoch: 180, Train Loss: 1.065, Val f1_micro: 0.269
Epoch: 200, Train Loss: 1.022, Val f1_micro: 0.274
Epoch: 220, Train Loss: 0.930, Val f1_micro: 0.278
Epoch: 240, Train Loss: 0.871, Val f1_micro: 0.282
Epoch: 260, Train Loss: 0.816, Val f1_micro: 0.281
Epoch: 280, Train Loss: 0.790, Val f1_micro: 0.283
Epoch: 300, Train Loss: 0.735, Val f1_micro: 0.291
Epoch: 320, Train Loss: 0.695, Val f1_micro: 0.288
Epoch: 340, Train Loss: 0.637, Val f1_micro: 0.293
Epoch: 360, Train Loss: 0.622, Val f1_micro: 0.295
Epoch: 380, Train Loss: 0.559, Val f1_micro: 0.295
Epoch: 400, Train Loss: 0.552, Val f1_micro: 0.298
Epoch: 420, Train Loss: 0.531, Val f1_micro: 0.297
Epoch: 440, Train Loss: 0.507, Val f1_micro: 0.299
Epoch: 460, Train Loss: 0.475, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.468, Val f1_micro: 0.298
Epoch: 500, Train Loss: 0.460, Val f1_micro: 0.300
f1-micro: 0.300, f1-macro: 0.294, f1-weighted: 0.300, , roc-auc: 0.666
##### RUN 5 #####
Epoch: 020, Train Loss: 1.939, Val f1_micro: 0.181
Epoch: 040, Train Loss: 1.692, Val f1_micro: 0.210
Epoch: 060, Train Loss: 1.572, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.455, Val f1_micro: 0.231
Epoch: 100, Train Loss: 1.356, Val f1_micro: 0.242
Epoch: 120, Train Loss: 1.281, Val f1_micro: 0.250
Epoch: 140, Train Loss: 1.177, Val f1_micro: 0.261
Epoch: 160, Train Loss: 1.117, Val f1_micro: 0.264
Epoch: 180, Train Loss: 1.054, Val f1_micro: 0.268
Epoch: 200, Train Loss: 0.999, Val f1_micro: 0.266
Epoch: 220, Train Loss: 0.923, Val f1_micro: 0.276
Epoch: 240, Train Loss: 0.879, Val f1_micro: 0.281
Epoch: 260, Train Loss: 0.809, Val f1_micro: 0.286
Epoch: 280, Train Loss: 0.787, Val f1_micro: 0.290
Epoch: 300, Train Loss: 0.711, Val f1_micro: 0.288
Epoch: 320, Train Loss: 0.693, Val f1_micro: 0.287
Epoch: 340, Train Loss: 0.637, Val f1_micro: 0.292
Epoch: 360, Train Loss: 0.605, Val f1_micro: 0.290
Epoch: 380, Train Loss: 0.581, Val f1_micro: 0.299
Epoch: 400, Train Loss: 0.553, Val f1_micro: 0.301
Epoch: 420, Train Loss: 0.521, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.488, Val f1_micro: 0.301
Epoch: 460, Train Loss: 0.502, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.478, Val f1_micro: 0.299
Epoch: 500, Train Loss: 0.445, Val f1_micro: 0.301
f1-micro: 0.301, f1-macro: 0.296, f1-weighted: 0.302, , roc-auc: 0.666
########## Hyperparameters combination ##########
(512, 0.7, 0.01, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.924, Val f1_micro: 0.170
Epoch: 040, Train Loss: 1.721, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.617, Val f1_micro: 0.238
Epoch: 080, Train Loss: 1.483, Val f1_micro: 0.240
Epoch: 100, Train Loss: 1.403, Val f1_micro: 0.255
Epoch: 120, Train Loss: 1.356, Val f1_micro: 0.253
Epoch: 140, Train Loss: 1.274, Val f1_micro: 0.256
Epoch: 160, Train Loss: 1.241, Val f1_micro: 0.253
Epoch: 180, Train Loss: 1.209, Val f1_micro: 0.262
Epoch: 200, Train Loss: 1.159, Val f1_micro: 0.267
Epoch: 220, Train Loss: 1.113, Val f1_micro: 0.269
Epoch: 240, Train Loss: 1.077, Val f1_micro: 0.269
Epoch: 260, Train Loss: 1.034, Val f1_micro: 0.275
Epoch: 280, Train Loss: 1.000, Val f1_micro: 0.269
Epoch: 300, Train Loss: 0.998, Val f1_micro: 0.277
Epoch: 320, Train Loss: 0.960, Val f1_micro: 0.278
Epoch: 340, Train Loss: 0.946, Val f1_micro: 0.274
Epoch: 360, Train Loss: 0.914, Val f1_micro: 0.283
Epoch: 380, Train Loss: 0.901, Val f1_micro: 0.288
Epoch: 400, Train Loss: 0.898, Val f1_micro: 0.282
Epoch: 420, Train Loss: 0.856, Val f1_micro: 0.282
Epoch: 440, Train Loss: 0.850, Val f1_micro: 0.283
Epoch: 460, Train Loss: 0.823, Val f1_micro: 0.289
Epoch: 480, Train Loss: 0.824, Val f1_micro: 0.289
Epoch: 500, Train Loss: 0.827, Val f1_micro: 0.290
f1-micro: 0.290, f1-macro: 0.279, f1-weighted: 0.287, , roc-auc: 0.660
##### RUN 2 #####
Epoch: 020, Train Loss: 1.961, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.705, Val f1_micro: 0.225
Epoch: 060, Train Loss: 1.578, Val f1_micro: 0.242
Epoch: 080, Train Loss: 1.489, Val f1_micro: 0.242
Epoch: 100, Train Loss: 1.414, Val f1_micro: 0.247
Epoch: 120, Train Loss: 1.336, Val f1_micro: 0.249
Epoch: 140, Train Loss: 1.280, Val f1_micro: 0.255
Epoch: 160, Train Loss: 1.247, Val f1_micro: 0.260
Epoch: 180, Train Loss: 1.220, Val f1_micro: 0.265
Epoch: 200, Train Loss: 1.120, Val f1_micro: 0.271
Epoch: 220, Train Loss: 1.106, Val f1_micro: 0.274
Epoch: 240, Train Loss: 1.071, Val f1_micro: 0.270
Epoch: 260, Train Loss: 1.041, Val f1_micro: 0.271
Epoch: 280, Train Loss: 1.013, Val f1_micro: 0.274
Epoch: 300, Train Loss: 0.975, Val f1_micro: 0.278
Epoch: 320, Train Loss: 0.972, Val f1_micro: 0.278
Epoch: 340, Train Loss: 0.960, Val f1_micro: 0.282
Epoch: 360, Train Loss: 0.911, Val f1_micro: 0.278
Epoch: 380, Train Loss: 0.889, Val f1_micro: 0.280
Epoch: 400, Train Loss: 0.890, Val f1_micro: 0.283
Epoch: 420, Train Loss: 0.866, Val f1_micro: 0.276
Epoch: 440, Train Loss: 0.848, Val f1_micro: 0.288
Epoch: 460, Train Loss: 0.814, Val f1_micro: 0.291
Epoch: 480, Train Loss: 0.796, Val f1_micro: 0.289
Epoch: 500, Train Loss: 0.799, Val f1_micro: 0.287
f1-micro: 0.287, f1-macro: 0.279, f1-weighted: 0.286, , roc-auc: 0.662
##### RUN 3 #####
Epoch: 020, Train Loss: 1.920, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.691, Val f1_micro: 0.225
Epoch: 060, Train Loss: 1.602, Val f1_micro: 0.241
Epoch: 080, Train Loss: 1.492, Val f1_micro: 0.246
Epoch: 100, Train Loss: 1.422, Val f1_micro: 0.251
Epoch: 120, Train Loss: 1.339, Val f1_micro: 0.256
Epoch: 140, Train Loss: 1.273, Val f1_micro: 0.260
Epoch: 160, Train Loss: 1.265, Val f1_micro: 0.266
Epoch: 180, Train Loss: 1.205, Val f1_micro: 0.265
Epoch: 200, Train Loss: 1.162, Val f1_micro: 0.266
Epoch: 220, Train Loss: 1.116, Val f1_micro: 0.271
Epoch: 240, Train Loss: 1.074, Val f1_micro: 0.273
Epoch: 260, Train Loss: 1.070, Val f1_micro: 0.276
Epoch: 280, Train Loss: 1.026, Val f1_micro: 0.277
Epoch: 300, Train Loss: 0.986, Val f1_micro: 0.280
Epoch: 320, Train Loss: 0.936, Val f1_micro: 0.281
Epoch: 340, Train Loss: 0.936, Val f1_micro: 0.284
Epoch: 360, Train Loss: 0.922, Val f1_micro: 0.282
Epoch: 380, Train Loss: 0.901, Val f1_micro: 0.279
Epoch: 400, Train Loss: 0.879, Val f1_micro: 0.288
Epoch: 420, Train Loss: 0.862, Val f1_micro: 0.288
Epoch: 440, Train Loss: 0.829, Val f1_micro: 0.288
Epoch: 460, Train Loss: 0.839, Val f1_micro: 0.290
Epoch: 480, Train Loss: 0.829, Val f1_micro: 0.292
Epoch: 500, Train Loss: 0.808, Val f1_micro: 0.292
f1-micro: 0.292, f1-macro: 0.282, f1-weighted: 0.289, , roc-auc: 0.662
##### RUN 4 #####
Epoch: 020, Train Loss: 1.938, Val f1_micro: 0.187
Epoch: 040, Train Loss: 1.691, Val f1_micro: 0.229
Epoch: 060, Train Loss: 1.577, Val f1_micro: 0.242
Epoch: 080, Train Loss: 1.503, Val f1_micro: 0.245
Epoch: 100, Train Loss: 1.408, Val f1_micro: 0.245
Epoch: 120, Train Loss: 1.339, Val f1_micro: 0.251
Epoch: 140, Train Loss: 1.307, Val f1_micro: 0.256
Epoch: 160, Train Loss: 1.250, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.208, Val f1_micro: 0.265
Epoch: 200, Train Loss: 1.154, Val f1_micro: 0.265
Epoch: 220, Train Loss: 1.134, Val f1_micro: 0.264
Epoch: 240, Train Loss: 1.095, Val f1_micro: 0.269
Epoch: 260, Train Loss: 1.080, Val f1_micro: 0.273
Epoch: 280, Train Loss: 1.027, Val f1_micro: 0.280
Epoch: 300, Train Loss: 0.991, Val f1_micro: 0.281
Epoch: 320, Train Loss: 0.983, Val f1_micro: 0.288
Epoch: 340, Train Loss: 0.952, Val f1_micro: 0.281
Epoch: 360, Train Loss: 0.922, Val f1_micro: 0.282
Epoch: 380, Train Loss: 0.902, Val f1_micro: 0.286
Epoch: 400, Train Loss: 0.886, Val f1_micro: 0.286
Epoch: 420, Train Loss: 0.876, Val f1_micro: 0.291
Epoch: 440, Train Loss: 0.833, Val f1_micro: 0.284
Epoch: 460, Train Loss: 0.833, Val f1_micro: 0.288
Epoch: 480, Train Loss: 0.825, Val f1_micro: 0.296
Epoch: 500, Train Loss: 0.813, Val f1_micro: 0.291
f1-micro: 0.291, f1-macro: 0.280, f1-weighted: 0.286, , roc-auc: 0.664
##### RUN 5 #####
Epoch: 020, Train Loss: 1.932, Val f1_micro: 0.187
Epoch: 040, Train Loss: 1.705, Val f1_micro: 0.210
Epoch: 060, Train Loss: 1.559, Val f1_micro: 0.241
Epoch: 080, Train Loss: 1.465, Val f1_micro: 0.247
Epoch: 100, Train Loss: 1.414, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.341, Val f1_micro: 0.255
Epoch: 140, Train Loss: 1.287, Val f1_micro: 0.261
Epoch: 160, Train Loss: 1.227, Val f1_micro: 0.261
Epoch: 180, Train Loss: 1.194, Val f1_micro: 0.263
Epoch: 200, Train Loss: 1.173, Val f1_micro: 0.263
Epoch: 220, Train Loss: 1.118, Val f1_micro: 0.263
Epoch: 240, Train Loss: 1.073, Val f1_micro: 0.269
Epoch: 260, Train Loss: 1.054, Val f1_micro: 0.274
Epoch: 280, Train Loss: 1.017, Val f1_micro: 0.274
Epoch: 300, Train Loss: 0.992, Val f1_micro: 0.281
Epoch: 320, Train Loss: 0.953, Val f1_micro: 0.278
Epoch: 340, Train Loss: 0.935, Val f1_micro: 0.279
Epoch: 360, Train Loss: 0.913, Val f1_micro: 0.278
Epoch: 380, Train Loss: 0.884, Val f1_micro: 0.278
Epoch: 400, Train Loss: 0.851, Val f1_micro: 0.280
Epoch: 420, Train Loss: 0.855, Val f1_micro: 0.282
Epoch: 440, Train Loss: 0.834, Val f1_micro: 0.288
Epoch: 460, Train Loss: 0.841, Val f1_micro: 0.287
Epoch: 480, Train Loss: 0.847, Val f1_micro: 0.289
Epoch: 500, Train Loss: 0.820, Val f1_micro: 0.293
f1-micro: 0.293, f1-macro: 0.285, f1-weighted: 0.291, , roc-auc: 0.662
########## Hyperparameters combination ##########
(512, 0.7, 0.01, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.918, Val f1_micro: 0.180
Epoch: 040, Train Loss: 1.702, Val f1_micro: 0.216
Epoch: 060, Train Loss: 1.629, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.540, Val f1_micro: 0.242
Epoch: 100, Train Loss: 1.472, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.431, Val f1_micro: 0.245
Epoch: 140, Train Loss: 1.420, Val f1_micro: 0.256
Epoch: 160, Train Loss: 1.387, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.337, Val f1_micro: 0.250
Epoch: 200, Train Loss: 1.313, Val f1_micro: 0.253
Epoch: 220, Train Loss: 1.300, Val f1_micro: 0.256
Epoch: 240, Train Loss: 1.254, Val f1_micro: 0.257
Epoch: 260, Train Loss: 1.248, Val f1_micro: 0.256
Epoch: 280, Train Loss: 1.222, Val f1_micro: 0.258
Epoch: 300, Train Loss: 1.204, Val f1_micro: 0.265
Epoch: 320, Train Loss: 1.178, Val f1_micro: 0.266
Epoch: 340, Train Loss: 1.169, Val f1_micro: 0.263
Epoch: 360, Train Loss: 1.167, Val f1_micro: 0.265
Epoch: 380, Train Loss: 1.158, Val f1_micro: 0.268
Epoch: 400, Train Loss: 1.144, Val f1_micro: 0.266
Epoch: 420, Train Loss: 1.147, Val f1_micro: 0.273
Epoch: 440, Train Loss: 1.121, Val f1_micro: 0.267
Epoch: 460, Train Loss: 1.120, Val f1_micro: 0.269
Epoch: 480, Train Loss: 1.090, Val f1_micro: 0.273
Epoch: 500, Train Loss: 1.084, Val f1_micro: 0.272
f1-micro: 0.272, f1-macro: 0.259, f1-weighted: 0.263, , roc-auc: 0.655
##### RUN 2 #####
Epoch: 020, Train Loss: 1.944, Val f1_micro: 0.187
Epoch: 040, Train Loss: 1.723, Val f1_micro: 0.221
Epoch: 060, Train Loss: 1.626, Val f1_micro: 0.239
Epoch: 080, Train Loss: 1.540, Val f1_micro: 0.237
Epoch: 100, Train Loss: 1.490, Val f1_micro: 0.244
Epoch: 120, Train Loss: 1.436, Val f1_micro: 0.252
Epoch: 140, Train Loss: 1.391, Val f1_micro: 0.251
Epoch: 160, Train Loss: 1.373, Val f1_micro: 0.252
Epoch: 180, Train Loss: 1.343, Val f1_micro: 0.248
Epoch: 200, Train Loss: 1.303, Val f1_micro: 0.254
Epoch: 220, Train Loss: 1.281, Val f1_micro: 0.259
Epoch: 240, Train Loss: 1.240, Val f1_micro: 0.258
Epoch: 260, Train Loss: 1.245, Val f1_micro: 0.262
Epoch: 280, Train Loss: 1.226, Val f1_micro: 0.262
Epoch: 300, Train Loss: 1.189, Val f1_micro: 0.265
Epoch: 320, Train Loss: 1.191, Val f1_micro: 0.266
Epoch: 340, Train Loss: 1.175, Val f1_micro: 0.268
Epoch: 360, Train Loss: 1.163, Val f1_micro: 0.269
Epoch: 380, Train Loss: 1.167, Val f1_micro: 0.270
Epoch: 400, Train Loss: 1.147, Val f1_micro: 0.272
Epoch: 420, Train Loss: 1.131, Val f1_micro: 0.270
Epoch: 440, Train Loss: 1.121, Val f1_micro: 0.267
Epoch: 460, Train Loss: 1.108, Val f1_micro: 0.274
Epoch: 480, Train Loss: 1.084, Val f1_micro: 0.270
Epoch: 500, Train Loss: 1.077, Val f1_micro: 0.271
f1-micro: 0.271, f1-macro: 0.259, f1-weighted: 0.264, , roc-auc: 0.654
##### RUN 3 #####
Epoch: 020, Train Loss: 1.948, Val f1_micro: 0.199
Epoch: 040, Train Loss: 1.708, Val f1_micro: 0.224
Epoch: 060, Train Loss: 1.616, Val f1_micro: 0.239
Epoch: 080, Train Loss: 1.514, Val f1_micro: 0.243
Epoch: 100, Train Loss: 1.488, Val f1_micro: 0.248
Epoch: 120, Train Loss: 1.430, Val f1_micro: 0.247
Epoch: 140, Train Loss: 1.397, Val f1_micro: 0.254
Epoch: 160, Train Loss: 1.370, Val f1_micro: 0.256
Epoch: 180, Train Loss: 1.340, Val f1_micro: 0.260
Epoch: 200, Train Loss: 1.306, Val f1_micro: 0.263
Epoch: 220, Train Loss: 1.287, Val f1_micro: 0.258
Epoch: 240, Train Loss: 1.268, Val f1_micro: 0.262
Epoch: 260, Train Loss: 1.241, Val f1_micro: 0.263
Epoch: 280, Train Loss: 1.217, Val f1_micro: 0.266
Epoch: 300, Train Loss: 1.216, Val f1_micro: 0.263
Epoch: 320, Train Loss: 1.179, Val f1_micro: 0.271
Epoch: 340, Train Loss: 1.164, Val f1_micro: 0.264
Epoch: 360, Train Loss: 1.156, Val f1_micro: 0.268
Epoch: 380, Train Loss: 1.145, Val f1_micro: 0.269
Epoch: 400, Train Loss: 1.133, Val f1_micro: 0.266
Epoch: 420, Train Loss: 1.119, Val f1_micro: 0.271
Epoch: 440, Train Loss: 1.107, Val f1_micro: 0.274
Epoch: 460, Train Loss: 1.112, Val f1_micro: 0.272
Epoch: 480, Train Loss: 1.090, Val f1_micro: 0.271
Epoch: 500, Train Loss: 1.095, Val f1_micro: 0.275
f1-micro: 0.275, f1-macro: 0.263, f1-weighted: 0.268, , roc-auc: 0.654
##### RUN 4 #####
Epoch: 020, Train Loss: 1.928, Val f1_micro: 0.184
Epoch: 040, Train Loss: 1.720, Val f1_micro: 0.219
Epoch: 060, Train Loss: 1.590, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.529, Val f1_micro: 0.247
Epoch: 100, Train Loss: 1.473, Val f1_micro: 0.245
Epoch: 120, Train Loss: 1.436, Val f1_micro: 0.246
Epoch: 140, Train Loss: 1.410, Val f1_micro: 0.253
Epoch: 160, Train Loss: 1.371, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.341, Val f1_micro: 0.249
Epoch: 200, Train Loss: 1.307, Val f1_micro: 0.260
Epoch: 220, Train Loss: 1.285, Val f1_micro: 0.259
Epoch: 240, Train Loss: 1.265, Val f1_micro: 0.265
Epoch: 260, Train Loss: 1.219, Val f1_micro: 0.269
Epoch: 280, Train Loss: 1.203, Val f1_micro: 0.264
Epoch: 300, Train Loss: 1.208, Val f1_micro: 0.262
Epoch: 320, Train Loss: 1.192, Val f1_micro: 0.270
Epoch: 340, Train Loss: 1.174, Val f1_micro: 0.271
Epoch: 360, Train Loss: 1.158, Val f1_micro: 0.273
Epoch: 380, Train Loss: 1.116, Val f1_micro: 0.271
Epoch: 400, Train Loss: 1.127, Val f1_micro: 0.269
Epoch: 420, Train Loss: 1.124, Val f1_micro: 0.268
Epoch: 440, Train Loss: 1.113, Val f1_micro: 0.278
Epoch: 460, Train Loss: 1.115, Val f1_micro: 0.274
Epoch: 480, Train Loss: 1.108, Val f1_micro: 0.269
Epoch: 500, Train Loss: 1.095, Val f1_micro: 0.272
f1-micro: 0.272, f1-macro: 0.260, f1-weighted: 0.265, , roc-auc: 0.654
##### RUN 5 #####
Epoch: 020, Train Loss: 1.949, Val f1_micro: 0.187
Epoch: 040, Train Loss: 1.718, Val f1_micro: 0.224
Epoch: 060, Train Loss: 1.619, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.548, Val f1_micro: 0.248
Epoch: 100, Train Loss: 1.497, Val f1_micro: 0.251
Epoch: 120, Train Loss: 1.428, Val f1_micro: 0.252
Epoch: 140, Train Loss: 1.390, Val f1_micro: 0.251
Epoch: 160, Train Loss: 1.396, Val f1_micro: 0.249
Epoch: 180, Train Loss: 1.333, Val f1_micro: 0.260
Epoch: 200, Train Loss: 1.288, Val f1_micro: 0.259
Epoch: 220, Train Loss: 1.296, Val f1_micro: 0.259
Epoch: 240, Train Loss: 1.247, Val f1_micro: 0.261
Epoch: 260, Train Loss: 1.232, Val f1_micro: 0.265
Epoch: 280, Train Loss: 1.240, Val f1_micro: 0.263
Epoch: 300, Train Loss: 1.195, Val f1_micro: 0.257
Epoch: 320, Train Loss: 1.209, Val f1_micro: 0.268
Epoch: 340, Train Loss: 1.194, Val f1_micro: 0.269
Epoch: 360, Train Loss: 1.174, Val f1_micro: 0.270
Epoch: 380, Train Loss: 1.146, Val f1_micro: 0.272
Epoch: 400, Train Loss: 1.139, Val f1_micro: 0.269
Epoch: 420, Train Loss: 1.122, Val f1_micro: 0.270
Epoch: 440, Train Loss: 1.123, Val f1_micro: 0.275
Epoch: 460, Train Loss: 1.088, Val f1_micro: 0.270
Epoch: 480, Train Loss: 1.116, Val f1_micro: 0.275
Epoch: 500, Train Loss: 1.092, Val f1_micro: 0.270
f1-micro: 0.270, f1-macro: 0.258, f1-weighted: 0.261, , roc-auc: 0.654
########## Hyperparameters combination ##########
(512, 0.7, 0.01, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.981, Val f1_micro: 0.143
Epoch: 040, Train Loss: 1.815, Val f1_micro: 0.203
Epoch: 060, Train Loss: 1.802, Val f1_micro: 0.199
Epoch: 080, Train Loss: 1.774, Val f1_micro: 0.208
Epoch: 100, Train Loss: 1.782, Val f1_micro: 0.207
Epoch: 120, Train Loss: 1.789, Val f1_micro: 0.214
Epoch: 140, Train Loss: 1.791, Val f1_micro: 0.213
Epoch: 160, Train Loss: 1.790, Val f1_micro: 0.205
Epoch: 180, Train Loss: 1.811, Val f1_micro: 0.200
Epoch: 200, Train Loss: 1.794, Val f1_micro: 0.200
Epoch: 220, Train Loss: 1.802, Val f1_micro: 0.205
Epoch: 240, Train Loss: 1.799, Val f1_micro: 0.206
Epoch: 260, Train Loss: 1.817, Val f1_micro: 0.201
Epoch: 280, Train Loss: 1.793, Val f1_micro: 0.200
Epoch: 300, Train Loss: 1.805, Val f1_micro: 0.200
Epoch: 320, Train Loss: 1.800, Val f1_micro: 0.207
Epoch: 340, Train Loss: 1.807, Val f1_micro: 0.204
Epoch: 360, Train Loss: 1.808, Val f1_micro: 0.204
Epoch: 380, Train Loss: 1.796, Val f1_micro: 0.207
Epoch: 400, Train Loss: 1.801, Val f1_micro: 0.213
Epoch: 420, Train Loss: 1.790, Val f1_micro: 0.211
Epoch: 440, Train Loss: 1.789, Val f1_micro: 0.207
Epoch: 460, Train Loss: 1.790, Val f1_micro: 0.205
Epoch: 480, Train Loss: 1.794, Val f1_micro: 0.208
Epoch: 500, Train Loss: 1.793, Val f1_micro: 0.202
f1-micro: 0.202, f1-macro: 0.162, f1-weighted: 0.164, , roc-auc: 0.630
##### RUN 2 #####
Epoch: 020, Train Loss: 1.944, Val f1_micro: 0.183
Epoch: 040, Train Loss: 1.812, Val f1_micro: 0.204
Epoch: 060, Train Loss: 1.781, Val f1_micro: 0.197
Epoch: 080, Train Loss: 1.766, Val f1_micro: 0.209
Epoch: 100, Train Loss: 1.787, Val f1_micro: 0.205
Epoch: 120, Train Loss: 1.793, Val f1_micro: 0.205
Epoch: 140, Train Loss: 1.796, Val f1_micro: 0.201
Epoch: 160, Train Loss: 1.804, Val f1_micro: 0.204
Epoch: 180, Train Loss: 1.806, Val f1_micro: 0.209
Epoch: 200, Train Loss: 1.807, Val f1_micro: 0.209
Epoch: 220, Train Loss: 1.809, Val f1_micro: 0.204
Epoch: 240, Train Loss: 1.802, Val f1_micro: 0.204
Epoch: 260, Train Loss: 1.810, Val f1_micro: 0.204
Epoch: 280, Train Loss: 1.806, Val f1_micro: 0.206
Epoch: 300, Train Loss: 1.798, Val f1_micro: 0.205
Epoch: 320, Train Loss: 1.810, Val f1_micro: 0.204
Epoch: 340, Train Loss: 1.816, Val f1_micro: 0.200
Epoch: 360, Train Loss: 1.795, Val f1_micro: 0.210
Epoch: 380, Train Loss: 1.800, Val f1_micro: 0.203
Epoch: 400, Train Loss: 1.800, Val f1_micro: 0.211
Epoch: 420, Train Loss: 1.815, Val f1_micro: 0.200
Epoch: 440, Train Loss: 1.822, Val f1_micro: 0.198
Epoch: 460, Train Loss: 1.797, Val f1_micro: 0.203
Epoch: 480, Train Loss: 1.794, Val f1_micro: 0.210
Epoch: 500, Train Loss: 1.803, Val f1_micro: 0.203
f1-micro: 0.203, f1-macro: 0.158, f1-weighted: 0.161, , roc-auc: 0.631
##### RUN 3 #####
Epoch: 020, Train Loss: 1.940, Val f1_micro: 0.174
Epoch: 040, Train Loss: 1.818, Val f1_micro: 0.199
Epoch: 060, Train Loss: 1.792, Val f1_micro: 0.198
Epoch: 080, Train Loss: 1.783, Val f1_micro: 0.211
Epoch: 100, Train Loss: 1.788, Val f1_micro: 0.209
Epoch: 120, Train Loss: 1.789, Val f1_micro: 0.213
Epoch: 140, Train Loss: 1.790, Val f1_micro: 0.204
Epoch: 160, Train Loss: 1.799, Val f1_micro: 0.209
Epoch: 180, Train Loss: 1.802, Val f1_micro: 0.203
Epoch: 200, Train Loss: 1.806, Val f1_micro: 0.205
Epoch: 220, Train Loss: 1.796, Val f1_micro: 0.205
Epoch: 240, Train Loss: 1.807, Val f1_micro: 0.211
Epoch: 260, Train Loss: 1.800, Val f1_micro: 0.207
Epoch: 280, Train Loss: 1.792, Val f1_micro: 0.203
Epoch: 300, Train Loss: 1.797, Val f1_micro: 0.206
Epoch: 320, Train Loss: 1.796, Val f1_micro: 0.208
Epoch: 340, Train Loss: 1.802, Val f1_micro: 0.208
Epoch: 360, Train Loss: 1.802, Val f1_micro: 0.200
Epoch: 380, Train Loss: 1.808, Val f1_micro: 0.205
Epoch: 400, Train Loss: 1.791, Val f1_micro: 0.206
Epoch: 420, Train Loss: 1.795, Val f1_micro: 0.208
Epoch: 440, Train Loss: 1.799, Val f1_micro: 0.203
Epoch: 460, Train Loss: 1.802, Val f1_micro: 0.195
Epoch: 480, Train Loss: 1.803, Val f1_micro: 0.203
Epoch: 500, Train Loss: 1.783, Val f1_micro: 0.211
f1-micro: 0.211, f1-macro: 0.167, f1-weighted: 0.166, , roc-auc: 0.632
##### RUN 4 #####
Epoch: 020, Train Loss: 1.936, Val f1_micro: 0.154
Epoch: 040, Train Loss: 1.819, Val f1_micro: 0.207
Epoch: 060, Train Loss: 1.789, Val f1_micro: 0.199
Epoch: 080, Train Loss: 1.794, Val f1_micro: 0.216
Epoch: 100, Train Loss: 1.794, Val f1_micro: 0.200
Epoch: 120, Train Loss: 1.782, Val f1_micro: 0.208
Epoch: 140, Train Loss: 1.804, Val f1_micro: 0.204
Epoch: 160, Train Loss: 1.793, Val f1_micro: 0.194
Epoch: 180, Train Loss: 1.803, Val f1_micro: 0.208
Epoch: 200, Train Loss: 1.788, Val f1_micro: 0.206
Epoch: 220, Train Loss: 1.804, Val f1_micro: 0.218
Epoch: 240, Train Loss: 1.808, Val f1_micro: 0.205
Epoch: 260, Train Loss: 1.802, Val f1_micro: 0.203
Epoch: 280, Train Loss: 1.806, Val f1_micro: 0.208
Epoch: 300, Train Loss: 1.800, Val f1_micro: 0.210
Epoch: 320, Train Loss: 1.802, Val f1_micro: 0.201
Epoch: 340, Train Loss: 1.797, Val f1_micro: 0.208
Epoch: 360, Train Loss: 1.797, Val f1_micro: 0.210
Epoch: 380, Train Loss: 1.796, Val f1_micro: 0.201
Epoch: 400, Train Loss: 1.795, Val f1_micro: 0.204
Epoch: 420, Train Loss: 1.793, Val f1_micro: 0.205
Epoch: 440, Train Loss: 1.809, Val f1_micro: 0.210
Epoch: 460, Train Loss: 1.795, Val f1_micro: 0.206
Epoch: 480, Train Loss: 1.804, Val f1_micro: 0.204
Epoch: 500, Train Loss: 1.801, Val f1_micro: 0.203
f1-micro: 0.203, f1-macro: 0.168, f1-weighted: 0.167, , roc-auc: 0.631
##### RUN 5 #####
Epoch: 020, Train Loss: 1.946, Val f1_micro: 0.163
Epoch: 040, Train Loss: 1.812, Val f1_micro: 0.206
Epoch: 060, Train Loss: 1.786, Val f1_micro: 0.203
Epoch: 080, Train Loss: 1.783, Val f1_micro: 0.204
Epoch: 100, Train Loss: 1.789, Val f1_micro: 0.201
Epoch: 120, Train Loss: 1.768, Val f1_micro: 0.209
Epoch: 140, Train Loss: 1.800, Val f1_micro: 0.210
Epoch: 160, Train Loss: 1.797, Val f1_micro: 0.212
Epoch: 180, Train Loss: 1.783, Val f1_micro: 0.200
Epoch: 200, Train Loss: 1.797, Val f1_micro: 0.211
Epoch: 220, Train Loss: 1.801, Val f1_micro: 0.202
Epoch: 240, Train Loss: 1.803, Val f1_micro: 0.210
Epoch: 260, Train Loss: 1.804, Val f1_micro: 0.209
Epoch: 280, Train Loss: 1.803, Val f1_micro: 0.209
Epoch: 300, Train Loss: 1.797, Val f1_micro: 0.214
Epoch: 320, Train Loss: 1.797, Val f1_micro: 0.208
Epoch: 340, Train Loss: 1.797, Val f1_micro: 0.211
Epoch: 360, Train Loss: 1.812, Val f1_micro: 0.208
Epoch: 380, Train Loss: 1.801, Val f1_micro: 0.205
Epoch: 400, Train Loss: 1.805, Val f1_micro: 0.201
Epoch: 420, Train Loss: 1.800, Val f1_micro: 0.200
Epoch: 440, Train Loss: 1.808, Val f1_micro: 0.206
Epoch: 460, Train Loss: 1.799, Val f1_micro: 0.209
Epoch: 480, Train Loss: 1.790, Val f1_micro: 0.202
Epoch: 500, Train Loss: 1.799, Val f1_micro: 0.210
f1-micro: 0.210, f1-macro: 0.173, f1-weighted: 0.175, , roc-auc: 0.633
########## Hyperparameters combination ##########
(512, 0.7, 0.05, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.070, Val f1_micro: 0.138
Epoch: 040, Train Loss: 2.003, Val f1_micro: 0.152
Epoch: 060, Train Loss: 1.975, Val f1_micro: 0.104
Epoch: 080, Train Loss: 1.940, Val f1_micro: 0.105
Epoch: 100, Train Loss: 1.908, Val f1_micro: 0.111
Epoch: 120, Train Loss: 1.874, Val f1_micro: 0.132
Epoch: 140, Train Loss: 1.821, Val f1_micro: 0.137
Epoch: 160, Train Loss: 1.752, Val f1_micro: 0.138
Epoch: 180, Train Loss: 1.726, Val f1_micro: 0.152
Epoch: 200, Train Loss: 1.668, Val f1_micro: 0.163
Epoch: 220, Train Loss: 1.578, Val f1_micro: 0.176
Epoch: 240, Train Loss: 1.498, Val f1_micro: 0.183
Epoch: 260, Train Loss: 1.520, Val f1_micro: 0.172
Epoch: 280, Train Loss: 1.447, Val f1_micro: 0.177
Epoch: 300, Train Loss: 1.416, Val f1_micro: 0.177
Epoch: 320, Train Loss: 1.370, Val f1_micro: 0.187
Epoch: 340, Train Loss: 1.331, Val f1_micro: 0.191
Epoch: 360, Train Loss: 1.322, Val f1_micro: 0.192
Epoch: 380, Train Loss: 1.300, Val f1_micro: 0.199
Epoch: 400, Train Loss: 1.256, Val f1_micro: 0.192
Epoch: 420, Train Loss: 1.231, Val f1_micro: 0.199
Epoch: 440, Train Loss: 1.203, Val f1_micro: 0.195
Epoch: 460, Train Loss: 1.221, Val f1_micro: 0.199
Epoch: 480, Train Loss: 1.159, Val f1_micro: 0.200
Epoch: 500, Train Loss: 1.161, Val f1_micro: 0.208
f1-micro: 0.208, f1-macro: 0.194, f1-weighted: 0.194, , roc-auc: 0.610
##### RUN 2 #####
Epoch: 020, Train Loss: 2.108, Val f1_micro: 0.141
Epoch: 040, Train Loss: 2.022, Val f1_micro: 0.151
Epoch: 060, Train Loss: 1.970, Val f1_micro: 0.151
Epoch: 080, Train Loss: 1.935, Val f1_micro: 0.105
Epoch: 100, Train Loss: 1.885, Val f1_micro: 0.114
Epoch: 120, Train Loss: 1.839, Val f1_micro: 0.151
Epoch: 140, Train Loss: 1.783, Val f1_micro: 0.152
Epoch: 160, Train Loss: 1.705, Val f1_micro: 0.150
Epoch: 180, Train Loss: 1.704, Val f1_micro: 0.156
Epoch: 200, Train Loss: 1.629, Val f1_micro: 0.172
Epoch: 220, Train Loss: 1.538, Val f1_micro: 0.168
Epoch: 240, Train Loss: 1.548, Val f1_micro: 0.173
Epoch: 260, Train Loss: 1.481, Val f1_micro: 0.177
Epoch: 280, Train Loss: 1.469, Val f1_micro: 0.190
Epoch: 300, Train Loss: 1.384, Val f1_micro: 0.185
Epoch: 320, Train Loss: 1.370, Val f1_micro: 0.197
Epoch: 340, Train Loss: 1.336, Val f1_micro: 0.198
Epoch: 360, Train Loss: 1.308, Val f1_micro: 0.201
Epoch: 380, Train Loss: 1.267, Val f1_micro: 0.204
Epoch: 400, Train Loss: 1.219, Val f1_micro: 0.209
Epoch: 420, Train Loss: 1.216, Val f1_micro: 0.207
Epoch: 440, Train Loss: 1.144, Val f1_micro: 0.216
Epoch: 460, Train Loss: 1.134, Val f1_micro: 0.220
Epoch: 480, Train Loss: 1.134, Val f1_micro: 0.220
Epoch: 500, Train Loss: 1.090, Val f1_micro: 0.216
f1-micro: 0.216, f1-macro: 0.206, f1-weighted: 0.206, , roc-auc: 0.605
##### RUN 3 #####
Epoch: 020, Train Loss: 2.063, Val f1_micro: 0.142
Epoch: 040, Train Loss: 2.000, Val f1_micro: 0.148
Epoch: 060, Train Loss: 1.969, Val f1_micro: 0.108
Epoch: 080, Train Loss: 1.950, Val f1_micro: 0.109
Epoch: 100, Train Loss: 1.902, Val f1_micro: 0.115
Epoch: 120, Train Loss: 1.879, Val f1_micro: 0.114
Epoch: 140, Train Loss: 1.850, Val f1_micro: 0.124
Epoch: 160, Train Loss: 1.777, Val f1_micro: 0.157
Epoch: 180, Train Loss: 1.711, Val f1_micro: 0.155
Epoch: 200, Train Loss: 1.703, Val f1_micro: 0.162
Epoch: 220, Train Loss: 1.617, Val f1_micro: 0.176
Epoch: 240, Train Loss: 1.568, Val f1_micro: 0.173
Epoch: 260, Train Loss: 1.510, Val f1_micro: 0.179
Epoch: 280, Train Loss: 1.472, Val f1_micro: 0.180
Epoch: 300, Train Loss: 1.441, Val f1_micro: 0.182
Epoch: 320, Train Loss: 1.403, Val f1_micro: 0.185
Epoch: 340, Train Loss: 1.394, Val f1_micro: 0.187
Epoch: 360, Train Loss: 1.305, Val f1_micro: 0.186
Epoch: 380, Train Loss: 1.344, Val f1_micro: 0.189
Epoch: 400, Train Loss: 1.272, Val f1_micro: 0.189
Epoch: 420, Train Loss: 1.267, Val f1_micro: 0.191
Epoch: 440, Train Loss: 1.237, Val f1_micro: 0.200
Epoch: 460, Train Loss: 1.215, Val f1_micro: 0.201
Epoch: 480, Train Loss: 1.167, Val f1_micro: 0.203
Epoch: 500, Train Loss: 1.139, Val f1_micro: 0.209
f1-micro: 0.209, f1-macro: 0.199, f1-weighted: 0.198, , roc-auc: 0.609
##### RUN 4 #####
Epoch: 020, Train Loss: 2.062, Val f1_micro: 0.096
Epoch: 040, Train Loss: 1.994, Val f1_micro: 0.099
Epoch: 060, Train Loss: 1.956, Val f1_micro: 0.106
Epoch: 080, Train Loss: 1.911, Val f1_micro: 0.112
Epoch: 100, Train Loss: 1.897, Val f1_micro: 0.122
Epoch: 120, Train Loss: 1.835, Val f1_micro: 0.123
Epoch: 140, Train Loss: 1.785, Val f1_micro: 0.130
Epoch: 160, Train Loss: 1.751, Val f1_micro: 0.154
Epoch: 180, Train Loss: 1.675, Val f1_micro: 0.165
Epoch: 200, Train Loss: 1.649, Val f1_micro: 0.170
Epoch: 220, Train Loss: 1.592, Val f1_micro: 0.173
Epoch: 240, Train Loss: 1.532, Val f1_micro: 0.174
Epoch: 260, Train Loss: 1.499, Val f1_micro: 0.179
Epoch: 280, Train Loss: 1.448, Val f1_micro: 0.184
Epoch: 300, Train Loss: 1.429, Val f1_micro: 0.180
Epoch: 320, Train Loss: 1.361, Val f1_micro: 0.183
Epoch: 340, Train Loss: 1.357, Val f1_micro: 0.190
Epoch: 360, Train Loss: 1.305, Val f1_micro: 0.197
Epoch: 380, Train Loss: 1.263, Val f1_micro: 0.200
Epoch: 400, Train Loss: 1.225, Val f1_micro: 0.210
Epoch: 420, Train Loss: 1.187, Val f1_micro: 0.211
Epoch: 440, Train Loss: 1.163, Val f1_micro: 0.209
Epoch: 460, Train Loss: 1.140, Val f1_micro: 0.211
Epoch: 480, Train Loss: 1.100, Val f1_micro: 0.214
Epoch: 500, Train Loss: 1.095, Val f1_micro: 0.225
f1-micro: 0.225, f1-macro: 0.217, f1-weighted: 0.217, , roc-auc: 0.610
##### RUN 5 #####
Epoch: 020, Train Loss: 2.091, Val f1_micro: 0.137
Epoch: 040, Train Loss: 1.992, Val f1_micro: 0.157
Epoch: 060, Train Loss: 1.972, Val f1_micro: 0.110
Epoch: 080, Train Loss: 1.922, Val f1_micro: 0.114
Epoch: 100, Train Loss: 1.861, Val f1_micro: 0.122
Epoch: 120, Train Loss: 1.852, Val f1_micro: 0.122
Epoch: 140, Train Loss: 1.805, Val f1_micro: 0.168
Epoch: 160, Train Loss: 1.746, Val f1_micro: 0.152
Epoch: 180, Train Loss: 1.702, Val f1_micro: 0.156
Epoch: 200, Train Loss: 1.649, Val f1_micro: 0.165
Epoch: 220, Train Loss: 1.619, Val f1_micro: 0.169
Epoch: 240, Train Loss: 1.576, Val f1_micro: 0.176
Epoch: 260, Train Loss: 1.550, Val f1_micro: 0.175
Epoch: 280, Train Loss: 1.530, Val f1_micro: 0.182
Epoch: 300, Train Loss: 1.474, Val f1_micro: 0.182
Epoch: 320, Train Loss: 1.428, Val f1_micro: 0.191
Epoch: 340, Train Loss: 1.376, Val f1_micro: 0.194
Epoch: 360, Train Loss: 1.305, Val f1_micro: 0.198
Epoch: 380, Train Loss: 1.270, Val f1_micro: 0.202
Epoch: 400, Train Loss: 1.275, Val f1_micro: 0.204
Epoch: 420, Train Loss: 1.227, Val f1_micro: 0.208
Epoch: 440, Train Loss: 1.188, Val f1_micro: 0.207
Epoch: 460, Train Loss: 1.144, Val f1_micro: 0.222
Epoch: 480, Train Loss: 1.152, Val f1_micro: 0.216
Epoch: 500, Train Loss: 1.119, Val f1_micro: 0.216
f1-micro: 0.216, f1-macro: 0.206, f1-weighted: 0.204, , roc-auc: 0.613
########## Hyperparameters combination ##########
(512, 0.7, 0.05, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.070, Val f1_micro: 0.100
Epoch: 040, Train Loss: 2.025, Val f1_micro: 0.107
Epoch: 060, Train Loss: 1.978, Val f1_micro: 0.113
Epoch: 080, Train Loss: 1.950, Val f1_micro: 0.110
Epoch: 100, Train Loss: 1.910, Val f1_micro: 0.153
Epoch: 120, Train Loss: 1.915, Val f1_micro: 0.150
Epoch: 140, Train Loss: 1.883, Val f1_micro: 0.157
Epoch: 160, Train Loss: 1.848, Val f1_micro: 0.155
Epoch: 180, Train Loss: 1.820, Val f1_micro: 0.167
Epoch: 200, Train Loss: 1.709, Val f1_micro: 0.178
Epoch: 220, Train Loss: 1.740, Val f1_micro: 0.182
Epoch: 240, Train Loss: 1.674, Val f1_micro: 0.185
Epoch: 260, Train Loss: 1.676, Val f1_micro: 0.178
Epoch: 280, Train Loss: 1.639, Val f1_micro: 0.185
Epoch: 300, Train Loss: 1.612, Val f1_micro: 0.185
Epoch: 320, Train Loss: 1.613, Val f1_micro: 0.194
Epoch: 340, Train Loss: 1.557, Val f1_micro: 0.194
Epoch: 360, Train Loss: 1.525, Val f1_micro: 0.195
Epoch: 380, Train Loss: 1.547, Val f1_micro: 0.204
Epoch: 400, Train Loss: 1.503, Val f1_micro: 0.204
Epoch: 420, Train Loss: 1.477, Val f1_micro: 0.191
Epoch: 440, Train Loss: 1.441, Val f1_micro: 0.201
Epoch: 460, Train Loss: 1.422, Val f1_micro: 0.205
Epoch: 480, Train Loss: 1.439, Val f1_micro: 0.203
Epoch: 500, Train Loss: 1.429, Val f1_micro: 0.212
f1-micro: 0.212, f1-macro: 0.193, f1-weighted: 0.192, , roc-auc: 0.615
##### RUN 2 #####
Epoch: 020, Train Loss: 2.112, Val f1_micro: 0.097
Epoch: 040, Train Loss: 2.016, Val f1_micro: 0.108
Epoch: 060, Train Loss: 1.984, Val f1_micro: 0.112
Epoch: 080, Train Loss: 1.954, Val f1_micro: 0.115
Epoch: 100, Train Loss: 1.916, Val f1_micro: 0.154
Epoch: 120, Train Loss: 1.889, Val f1_micro: 0.157
Epoch: 140, Train Loss: 1.856, Val f1_micro: 0.147
Epoch: 160, Train Loss: 1.843, Val f1_micro: 0.140
Epoch: 180, Train Loss: 1.815, Val f1_micro: 0.154
Epoch: 200, Train Loss: 1.754, Val f1_micro: 0.166
Epoch: 220, Train Loss: 1.712, Val f1_micro: 0.181
Epoch: 240, Train Loss: 1.667, Val f1_micro: 0.193
Epoch: 260, Train Loss: 1.667, Val f1_micro: 0.182
Epoch: 280, Train Loss: 1.627, Val f1_micro: 0.192
Epoch: 300, Train Loss: 1.606, Val f1_micro: 0.183
Epoch: 320, Train Loss: 1.589, Val f1_micro: 0.184
Epoch: 340, Train Loss: 1.560, Val f1_micro: 0.202
Epoch: 360, Train Loss: 1.565, Val f1_micro: 0.208
Epoch: 380, Train Loss: 1.528, Val f1_micro: 0.210
Epoch: 400, Train Loss: 1.474, Val f1_micro: 0.214
Epoch: 420, Train Loss: 1.520, Val f1_micro: 0.200
Epoch: 440, Train Loss: 1.467, Val f1_micro: 0.203
Epoch: 460, Train Loss: 1.476, Val f1_micro: 0.203
Epoch: 480, Train Loss: 1.456, Val f1_micro: 0.208
Epoch: 500, Train Loss: 1.410, Val f1_micro: 0.206
f1-micro: 0.206, f1-macro: 0.188, f1-weighted: 0.185, , roc-auc: 0.616
##### RUN 3 #####
Epoch: 020, Train Loss: 2.085, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.010, Val f1_micro: 0.160
Epoch: 060, Train Loss: 2.004, Val f1_micro: 0.114
Epoch: 080, Train Loss: 1.966, Val f1_micro: 0.117
Epoch: 100, Train Loss: 1.949, Val f1_micro: 0.153
Epoch: 120, Train Loss: 1.895, Val f1_micro: 0.154
Epoch: 140, Train Loss: 1.855, Val f1_micro: 0.156
Epoch: 160, Train Loss: 1.815, Val f1_micro: 0.164
Epoch: 180, Train Loss: 1.780, Val f1_micro: 0.174
Epoch: 200, Train Loss: 1.756, Val f1_micro: 0.177
Epoch: 220, Train Loss: 1.734, Val f1_micro: 0.174
Epoch: 240, Train Loss: 1.729, Val f1_micro: 0.180
Epoch: 260, Train Loss: 1.645, Val f1_micro: 0.183
Epoch: 280, Train Loss: 1.644, Val f1_micro: 0.185
Epoch: 300, Train Loss: 1.635, Val f1_micro: 0.172
Epoch: 320, Train Loss: 1.610, Val f1_micro: 0.189
Epoch: 340, Train Loss: 1.605, Val f1_micro: 0.184
Epoch: 360, Train Loss: 1.561, Val f1_micro: 0.202
Epoch: 380, Train Loss: 1.552, Val f1_micro: 0.197
Epoch: 400, Train Loss: 1.528, Val f1_micro: 0.208
Epoch: 420, Train Loss: 1.487, Val f1_micro: 0.204
Epoch: 440, Train Loss: 1.507, Val f1_micro: 0.197
Epoch: 460, Train Loss: 1.487, Val f1_micro: 0.206
Epoch: 480, Train Loss: 1.462, Val f1_micro: 0.210
Epoch: 500, Train Loss: 1.455, Val f1_micro: 0.201
f1-micro: 0.201, f1-macro: 0.189, f1-weighted: 0.187, , roc-auc: 0.615
##### RUN 4 #####
Epoch: 020, Train Loss: 2.096, Val f1_micro: 0.095
Epoch: 040, Train Loss: 2.023, Val f1_micro: 0.107
Epoch: 060, Train Loss: 2.015, Val f1_micro: 0.105
Epoch: 080, Train Loss: 1.993, Val f1_micro: 0.112
Epoch: 100, Train Loss: 1.952, Val f1_micro: 0.116
Epoch: 120, Train Loss: 1.924, Val f1_micro: 0.140
Epoch: 140, Train Loss: 1.871, Val f1_micro: 0.153
Epoch: 160, Train Loss: 1.832, Val f1_micro: 0.161
Epoch: 180, Train Loss: 1.783, Val f1_micro: 0.166
Epoch: 200, Train Loss: 1.762, Val f1_micro: 0.178
Epoch: 220, Train Loss: 1.733, Val f1_micro: 0.188
Epoch: 240, Train Loss: 1.693, Val f1_micro: 0.184
Epoch: 260, Train Loss: 1.675, Val f1_micro: 0.190
Epoch: 280, Train Loss: 1.641, Val f1_micro: 0.187
Epoch: 300, Train Loss: 1.593, Val f1_micro: 0.191
Epoch: 320, Train Loss: 1.604, Val f1_micro: 0.204
Epoch: 340, Train Loss: 1.543, Val f1_micro: 0.197
Epoch: 360, Train Loss: 1.531, Val f1_micro: 0.197
Epoch: 380, Train Loss: 1.525, Val f1_micro: 0.199
Epoch: 400, Train Loss: 1.473, Val f1_micro: 0.214
Epoch: 420, Train Loss: 1.471, Val f1_micro: 0.211
Epoch: 440, Train Loss: 1.460, Val f1_micro: 0.215
Epoch: 460, Train Loss: 1.447, Val f1_micro: 0.210
Epoch: 480, Train Loss: 1.458, Val f1_micro: 0.216
Epoch: 500, Train Loss: 1.408, Val f1_micro: 0.219
f1-micro: 0.219, f1-macro: 0.203, f1-weighted: 0.204, , roc-auc: 0.615
##### RUN 5 #####
Epoch: 020, Train Loss: 2.116, Val f1_micro: 0.097
Epoch: 040, Train Loss: 2.011, Val f1_micro: 0.105
Epoch: 060, Train Loss: 1.983, Val f1_micro: 0.107
Epoch: 080, Train Loss: 1.966, Val f1_micro: 0.113
Epoch: 100, Train Loss: 1.943, Val f1_micro: 0.145
Epoch: 120, Train Loss: 1.918, Val f1_micro: 0.138
Epoch: 140, Train Loss: 1.910, Val f1_micro: 0.137
Epoch: 160, Train Loss: 1.894, Val f1_micro: 0.128
Epoch: 180, Train Loss: 1.863, Val f1_micro: 0.151
Epoch: 200, Train Loss: 1.830, Val f1_micro: 0.159
Epoch: 220, Train Loss: 1.768, Val f1_micro: 0.166
Epoch: 240, Train Loss: 1.743, Val f1_micro: 0.164
Epoch: 260, Train Loss: 1.705, Val f1_micro: 0.185
Epoch: 280, Train Loss: 1.665, Val f1_micro: 0.192
Epoch: 300, Train Loss: 1.613, Val f1_micro: 0.204
Epoch: 320, Train Loss: 1.573, Val f1_micro: 0.195
Epoch: 340, Train Loss: 1.551, Val f1_micro: 0.210
Epoch: 360, Train Loss: 1.530, Val f1_micro: 0.198
Epoch: 380, Train Loss: 1.544, Val f1_micro: 0.207
Epoch: 400, Train Loss: 1.506, Val f1_micro: 0.191
Epoch: 420, Train Loss: 1.505, Val f1_micro: 0.210
Epoch: 440, Train Loss: 1.471, Val f1_micro: 0.219
Epoch: 460, Train Loss: 1.445, Val f1_micro: 0.204
Epoch: 480, Train Loss: 1.438, Val f1_micro: 0.208
Epoch: 500, Train Loss: 1.438, Val f1_micro: 0.219
f1-micro: 0.219, f1-macro: 0.200, f1-weighted: 0.199, , roc-auc: 0.620
########## Hyperparameters combination ##########
(512, 0.7, 0.05, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.121, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.032, Val f1_micro: 0.158
Epoch: 060, Train Loss: 2.017, Val f1_micro: 0.107
Epoch: 080, Train Loss: 1.991, Val f1_micro: 0.115
Epoch: 100, Train Loss: 1.978, Val f1_micro: 0.157
Epoch: 120, Train Loss: 1.960, Val f1_micro: 0.156
Epoch: 140, Train Loss: 1.960, Val f1_micro: 0.162
Epoch: 160, Train Loss: 1.898, Val f1_micro: 0.172
Epoch: 180, Train Loss: 1.866, Val f1_micro: 0.166
Epoch: 200, Train Loss: 1.825, Val f1_micro: 0.182
Epoch: 220, Train Loss: 1.803, Val f1_micro: 0.189
Epoch: 240, Train Loss: 1.783, Val f1_micro: 0.190
Epoch: 260, Train Loss: 1.758, Val f1_micro: 0.197
Epoch: 280, Train Loss: 1.733, Val f1_micro: 0.185
Epoch: 300, Train Loss: 1.737, Val f1_micro: 0.210
Epoch: 320, Train Loss: 1.730, Val f1_micro: 0.199
Epoch: 340, Train Loss: 1.720, Val f1_micro: 0.208
Epoch: 360, Train Loss: 1.704, Val f1_micro: 0.207
Epoch: 380, Train Loss: 1.787, Val f1_micro: 0.193
Epoch: 400, Train Loss: 1.679, Val f1_micro: 0.206
Epoch: 420, Train Loss: 1.646, Val f1_micro: 0.215
Epoch: 440, Train Loss: 1.640, Val f1_micro: 0.205
Epoch: 460, Train Loss: 1.643, Val f1_micro: 0.217
Epoch: 480, Train Loss: 1.618, Val f1_micro: 0.210
Epoch: 500, Train Loss: 1.612, Val f1_micro: 0.214
f1-micro: 0.214, f1-macro: 0.191, f1-weighted: 0.192, , roc-auc: 0.625
##### RUN 2 #####
Epoch: 020, Train Loss: 2.067, Val f1_micro: 0.095
Epoch: 040, Train Loss: 2.032, Val f1_micro: 0.158
Epoch: 060, Train Loss: 2.010, Val f1_micro: 0.144
Epoch: 080, Train Loss: 1.984, Val f1_micro: 0.143
Epoch: 100, Train Loss: 1.962, Val f1_micro: 0.143
Epoch: 120, Train Loss: 1.938, Val f1_micro: 0.161
Epoch: 140, Train Loss: 1.911, Val f1_micro: 0.162
Epoch: 160, Train Loss: 1.874, Val f1_micro: 0.175
Epoch: 180, Train Loss: 1.852, Val f1_micro: 0.179
Epoch: 200, Train Loss: 1.807, Val f1_micro: 0.183
Epoch: 220, Train Loss: 1.792, Val f1_micro: 0.185
Epoch: 240, Train Loss: 1.798, Val f1_micro: 0.179
Epoch: 260, Train Loss: 1.741, Val f1_micro: 0.185
Epoch: 280, Train Loss: 1.757, Val f1_micro: 0.183
Epoch: 300, Train Loss: 1.741, Val f1_micro: 0.196
Epoch: 320, Train Loss: 1.713, Val f1_micro: 0.197
Epoch: 340, Train Loss: 1.712, Val f1_micro: 0.199
Epoch: 360, Train Loss: 1.701, Val f1_micro: 0.202
Epoch: 380, Train Loss: 1.693, Val f1_micro: 0.189
Epoch: 400, Train Loss: 1.660, Val f1_micro: 0.205
Epoch: 420, Train Loss: 1.677, Val f1_micro: 0.197
Epoch: 440, Train Loss: 1.662, Val f1_micro: 0.206
Epoch: 460, Train Loss: 1.644, Val f1_micro: 0.213
Epoch: 480, Train Loss: 1.654, Val f1_micro: 0.205
Epoch: 500, Train Loss: 1.649, Val f1_micro: 0.200
f1-micro: 0.200, f1-macro: 0.180, f1-weighted: 0.178, , roc-auc: 0.617
##### RUN 3 #####
Epoch: 020, Train Loss: 2.092, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.023, Val f1_micro: 0.158
Epoch: 060, Train Loss: 2.017, Val f1_micro: 0.116
Epoch: 080, Train Loss: 1.992, Val f1_micro: 0.117
Epoch: 100, Train Loss: 1.956, Val f1_micro: 0.140
Epoch: 120, Train Loss: 1.915, Val f1_micro: 0.158
Epoch: 140, Train Loss: 1.886, Val f1_micro: 0.164
Epoch: 160, Train Loss: 1.857, Val f1_micro: 0.175
Epoch: 180, Train Loss: 1.848, Val f1_micro: 0.186
Epoch: 200, Train Loss: 1.832, Val f1_micro: 0.179
Epoch: 220, Train Loss: 1.800, Val f1_micro: 0.186
Epoch: 240, Train Loss: 1.763, Val f1_micro: 0.190
Epoch: 260, Train Loss: 1.737, Val f1_micro: 0.190
Epoch: 280, Train Loss: 1.743, Val f1_micro: 0.180
Epoch: 300, Train Loss: 1.733, Val f1_micro: 0.195
Epoch: 320, Train Loss: 1.707, Val f1_micro: 0.199
Epoch: 340, Train Loss: 1.708, Val f1_micro: 0.202
Epoch: 360, Train Loss: 1.695, Val f1_micro: 0.204
Epoch: 380, Train Loss: 1.673, Val f1_micro: 0.194
Epoch: 400, Train Loss: 1.669, Val f1_micro: 0.196
Epoch: 420, Train Loss: 1.679, Val f1_micro: 0.194
Epoch: 440, Train Loss: 1.668, Val f1_micro: 0.212
Epoch: 460, Train Loss: 1.626, Val f1_micro: 0.203
Epoch: 480, Train Loss: 1.675, Val f1_micro: 0.218
Epoch: 500, Train Loss: 1.630, Val f1_micro: 0.203
f1-micro: 0.203, f1-macro: 0.177, f1-weighted: 0.177, , roc-auc: 0.614
##### RUN 4 #####
Epoch: 020, Train Loss: 2.094, Val f1_micro: 0.095
Epoch: 040, Train Loss: 2.032, Val f1_micro: 0.160
Epoch: 060, Train Loss: 2.025, Val f1_micro: 0.110
Epoch: 080, Train Loss: 2.007, Val f1_micro: 0.111
Epoch: 100, Train Loss: 2.009, Val f1_micro: 0.116
Epoch: 120, Train Loss: 1.984, Val f1_micro: 0.165
Epoch: 140, Train Loss: 1.964, Val f1_micro: 0.162
Epoch: 160, Train Loss: 1.907, Val f1_micro: 0.172
Epoch: 180, Train Loss: 1.882, Val f1_micro: 0.175
Epoch: 200, Train Loss: 1.861, Val f1_micro: 0.171
Epoch: 220, Train Loss: 1.855, Val f1_micro: 0.184
Epoch: 240, Train Loss: 1.814, Val f1_micro: 0.186
Epoch: 260, Train Loss: 1.802, Val f1_micro: 0.178
Epoch: 280, Train Loss: 1.762, Val f1_micro: 0.199
Epoch: 300, Train Loss: 1.767, Val f1_micro: 0.192
Epoch: 320, Train Loss: 1.742, Val f1_micro: 0.192
Epoch: 340, Train Loss: 1.730, Val f1_micro: 0.194
Epoch: 360, Train Loss: 1.721, Val f1_micro: 0.189
Epoch: 380, Train Loss: 1.699, Val f1_micro: 0.201
Epoch: 400, Train Loss: 1.698, Val f1_micro: 0.204
Epoch: 420, Train Loss: 1.687, Val f1_micro: 0.215
Epoch: 440, Train Loss: 1.686, Val f1_micro: 0.195
Epoch: 460, Train Loss: 1.668, Val f1_micro: 0.210
Epoch: 480, Train Loss: 1.704, Val f1_micro: 0.201
Epoch: 500, Train Loss: 1.650, Val f1_micro: 0.219
f1-micro: 0.219, f1-macro: 0.196, f1-weighted: 0.198, , roc-auc: 0.622
##### RUN 5 #####
Epoch: 020, Train Loss: 2.077, Val f1_micro: 0.095
Epoch: 040, Train Loss: 2.038, Val f1_micro: 0.161
Epoch: 060, Train Loss: 2.025, Val f1_micro: 0.114
Epoch: 080, Train Loss: 1.991, Val f1_micro: 0.166
Epoch: 100, Train Loss: 1.963, Val f1_micro: 0.144
Epoch: 120, Train Loss: 1.928, Val f1_micro: 0.162
Epoch: 140, Train Loss: 1.891, Val f1_micro: 0.171
Epoch: 160, Train Loss: 1.886, Val f1_micro: 0.165
Epoch: 180, Train Loss: 1.861, Val f1_micro: 0.183
Epoch: 200, Train Loss: 1.826, Val f1_micro: 0.180
Epoch: 220, Train Loss: 1.789, Val f1_micro: 0.187
Epoch: 240, Train Loss: 1.804, Val f1_micro: 0.186
Epoch: 260, Train Loss: 1.774, Val f1_micro: 0.187
Epoch: 280, Train Loss: 1.755, Val f1_micro: 0.180
Epoch: 300, Train Loss: 1.755, Val f1_micro: 0.194
Epoch: 320, Train Loss: 1.729, Val f1_micro: 0.195
Epoch: 340, Train Loss: 1.718, Val f1_micro: 0.194
Epoch: 360, Train Loss: 1.691, Val f1_micro: 0.197
Epoch: 380, Train Loss: 1.710, Val f1_micro: 0.183
Epoch: 400, Train Loss: 1.702, Val f1_micro: 0.192
Epoch: 420, Train Loss: 1.697, Val f1_micro: 0.201
Epoch: 440, Train Loss: 1.657, Val f1_micro: 0.204
Epoch: 460, Train Loss: 1.668, Val f1_micro: 0.206
Epoch: 480, Train Loss: 1.646, Val f1_micro: 0.197
Epoch: 500, Train Loss: 1.656, Val f1_micro: 0.205
f1-micro: 0.205, f1-macro: 0.186, f1-weighted: 0.186, , roc-auc: 0.622
########## Hyperparameters combination ##########
(512, 0.7, 0.05, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.072, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.055, Val f1_micro: 0.153
Epoch: 060, Train Loss: 2.037, Val f1_micro: 0.132
Epoch: 080, Train Loss: 2.023, Val f1_micro: 0.150
Epoch: 100, Train Loss: 1.981, Val f1_micro: 0.168
Epoch: 120, Train Loss: 1.975, Val f1_micro: 0.169
Epoch: 140, Train Loss: 1.964, Val f1_micro: 0.186
Epoch: 160, Train Loss: 1.960, Val f1_micro: 0.140
Epoch: 180, Train Loss: 1.955, Val f1_micro: 0.174
Epoch: 200, Train Loss: 1.943, Val f1_micro: 0.175
Epoch: 220, Train Loss: 1.958, Val f1_micro: 0.169
Epoch: 240, Train Loss: 1.944, Val f1_micro: 0.179
Epoch: 260, Train Loss: 1.946, Val f1_micro: 0.183
Epoch: 280, Train Loss: 1.935, Val f1_micro: 0.174
Epoch: 300, Train Loss: 1.938, Val f1_micro: 0.185
Epoch: 320, Train Loss: 1.942, Val f1_micro: 0.190
Epoch: 340, Train Loss: 1.935, Val f1_micro: 0.178
Epoch: 360, Train Loss: 1.940, Val f1_micro: 0.187
Epoch: 380, Train Loss: 1.929, Val f1_micro: 0.193
Epoch: 400, Train Loss: 1.941, Val f1_micro: 0.181
Epoch: 420, Train Loss: 1.924, Val f1_micro: 0.178
Epoch: 440, Train Loss: 1.927, Val f1_micro: 0.183
Epoch: 460, Train Loss: 1.937, Val f1_micro: 0.188
Epoch: 480, Train Loss: 1.928, Val f1_micro: 0.204
Epoch: 500, Train Loss: 1.936, Val f1_micro: 0.170
f1-micro: 0.170, f1-macro: 0.123, f1-weighted: 0.121, , roc-auc: 0.601
##### RUN 2 #####
Epoch: 020, Train Loss: 2.073, Val f1_micro: 0.140
Epoch: 040, Train Loss: 2.058, Val f1_micro: 0.170
Epoch: 060, Train Loss: 2.030, Val f1_micro: 0.115
Epoch: 080, Train Loss: 2.018, Val f1_micro: 0.150
Epoch: 100, Train Loss: 1.995, Val f1_micro: 0.166
Epoch: 120, Train Loss: 1.987, Val f1_micro: 0.159
Epoch: 140, Train Loss: 1.962, Val f1_micro: 0.167
Epoch: 160, Train Loss: 1.967, Val f1_micro: 0.169
Epoch: 180, Train Loss: 1.954, Val f1_micro: 0.166
Epoch: 200, Train Loss: 1.951, Val f1_micro: 0.159
Epoch: 220, Train Loss: 1.956, Val f1_micro: 0.176
Epoch: 240, Train Loss: 1.960, Val f1_micro: 0.190
Epoch: 260, Train Loss: 1.942, Val f1_micro: 0.171
Epoch: 280, Train Loss: 1.953, Val f1_micro: 0.179
Epoch: 300, Train Loss: 1.939, Val f1_micro: 0.180
Epoch: 320, Train Loss: 1.947, Val f1_micro: 0.172
Epoch: 340, Train Loss: 1.945, Val f1_micro: 0.185
Epoch: 360, Train Loss: 1.932, Val f1_micro: 0.177
Epoch: 380, Train Loss: 1.924, Val f1_micro: 0.193
Epoch: 400, Train Loss: 1.952, Val f1_micro: 0.173
Epoch: 420, Train Loss: 1.933, Val f1_micro: 0.186
Epoch: 440, Train Loss: 1.937, Val f1_micro: 0.180
Epoch: 460, Train Loss: 1.929, Val f1_micro: 0.168
Epoch: 480, Train Loss: 1.940, Val f1_micro: 0.173
Epoch: 500, Train Loss: 1.934, Val f1_micro: 0.192
f1-micro: 0.192, f1-macro: 0.146, f1-weighted: 0.150, , roc-auc: 0.597
##### RUN 3 #####
Epoch: 020, Train Loss: 2.070, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.048, Val f1_micro: 0.158
Epoch: 060, Train Loss: 2.023, Val f1_micro: 0.119
Epoch: 080, Train Loss: 1.989, Val f1_micro: 0.168
Epoch: 100, Train Loss: 1.979, Val f1_micro: 0.164
Epoch: 120, Train Loss: 1.960, Val f1_micro: 0.176
Epoch: 140, Train Loss: 1.959, Val f1_micro: 0.183
Epoch: 160, Train Loss: 1.957, Val f1_micro: 0.167
Epoch: 180, Train Loss: 1.958, Val f1_micro: 0.172
Epoch: 200, Train Loss: 1.950, Val f1_micro: 0.185
Epoch: 220, Train Loss: 1.952, Val f1_micro: 0.168
Epoch: 240, Train Loss: 1.935, Val f1_micro: 0.185
Epoch: 260, Train Loss: 1.936, Val f1_micro: 0.170
Epoch: 280, Train Loss: 1.940, Val f1_micro: 0.155
Epoch: 300, Train Loss: 1.944, Val f1_micro: 0.178
Epoch: 320, Train Loss: 1.946, Val f1_micro: 0.180
Epoch: 340, Train Loss: 1.939, Val f1_micro: 0.177
Epoch: 360, Train Loss: 1.943, Val f1_micro: 0.185
Epoch: 380, Train Loss: 1.938, Val f1_micro: 0.156
Epoch: 400, Train Loss: 1.935, Val f1_micro: 0.191
Epoch: 420, Train Loss: 1.935, Val f1_micro: 0.178
Epoch: 440, Train Loss: 1.938, Val f1_micro: 0.173
Epoch: 460, Train Loss: 1.931, Val f1_micro: 0.194
Epoch: 480, Train Loss: 1.936, Val f1_micro: 0.183
Epoch: 500, Train Loss: 1.949, Val f1_micro: 0.171
f1-micro: 0.171, f1-macro: 0.120, f1-weighted: 0.120, , roc-auc: 0.607
##### RUN 4 #####
Epoch: 020, Train Loss: 2.097, Val f1_micro: 0.137
Epoch: 040, Train Loss: 2.049, Val f1_micro: 0.150
Epoch: 060, Train Loss: 2.033, Val f1_micro: 0.103
Epoch: 080, Train Loss: 2.017, Val f1_micro: 0.159
Epoch: 100, Train Loss: 2.005, Val f1_micro: 0.156
Epoch: 120, Train Loss: 1.985, Val f1_micro: 0.166
Epoch: 140, Train Loss: 1.974, Val f1_micro: 0.122
Epoch: 160, Train Loss: 1.986, Val f1_micro: 0.182
Epoch: 180, Train Loss: 1.951, Val f1_micro: 0.185
Epoch: 200, Train Loss: 1.933, Val f1_micro: 0.174
Epoch: 220, Train Loss: 1.948, Val f1_micro: 0.191
Epoch: 240, Train Loss: 1.937, Val f1_micro: 0.180
Epoch: 260, Train Loss: 1.946, Val f1_micro: 0.168
Epoch: 280, Train Loss: 1.941, Val f1_micro: 0.185
Epoch: 300, Train Loss: 1.928, Val f1_micro: 0.179
Epoch: 320, Train Loss: 1.946, Val f1_micro: 0.155
Epoch: 340, Train Loss: 1.937, Val f1_micro: 0.179
Epoch: 360, Train Loss: 1.935, Val f1_micro: 0.164
Epoch: 380, Train Loss: 1.944, Val f1_micro: 0.178
Epoch: 400, Train Loss: 1.946, Val f1_micro: 0.187
Epoch: 420, Train Loss: 1.926, Val f1_micro: 0.160
Epoch: 440, Train Loss: 1.931, Val f1_micro: 0.190
Epoch: 460, Train Loss: 1.937, Val f1_micro: 0.197
Epoch: 480, Train Loss: 1.937, Val f1_micro: 0.181
Epoch: 500, Train Loss: 1.928, Val f1_micro: 0.189
f1-micro: 0.189, f1-macro: 0.128, f1-weighted: 0.129, , roc-auc: 0.605
##### RUN 5 #####
Epoch: 020, Train Loss: 2.098, Val f1_micro: 0.101
Epoch: 040, Train Loss: 2.054, Val f1_micro: 0.154
Epoch: 060, Train Loss: 2.035, Val f1_micro: 0.152
Epoch: 080, Train Loss: 2.015, Val f1_micro: 0.162
Epoch: 100, Train Loss: 1.985, Val f1_micro: 0.143
Epoch: 120, Train Loss: 1.982, Val f1_micro: 0.171
Epoch: 140, Train Loss: 1.969, Val f1_micro: 0.171
Epoch: 160, Train Loss: 1.963, Val f1_micro: 0.167
Epoch: 180, Train Loss: 1.950, Val f1_micro: 0.168
Epoch: 200, Train Loss: 1.957, Val f1_micro: 0.179
Epoch: 220, Train Loss: 1.954, Val f1_micro: 0.176
Epoch: 240, Train Loss: 1.963, Val f1_micro: 0.184
Epoch: 260, Train Loss: 1.937, Val f1_micro: 0.182
Epoch: 280, Train Loss: 1.931, Val f1_micro: 0.186
Epoch: 300, Train Loss: 1.944, Val f1_micro: 0.184
Epoch: 320, Train Loss: 1.939, Val f1_micro: 0.190
Epoch: 340, Train Loss: 1.944, Val f1_micro: 0.191
Epoch: 360, Train Loss: 1.943, Val f1_micro: 0.180
Epoch: 380, Train Loss: 1.934, Val f1_micro: 0.190
Epoch: 400, Train Loss: 1.940, Val f1_micro: 0.179
Epoch: 420, Train Loss: 1.934, Val f1_micro: 0.187
Epoch: 440, Train Loss: 1.926, Val f1_micro: 0.185
Epoch: 460, Train Loss: 1.946, Val f1_micro: 0.192
Epoch: 480, Train Loss: 1.931, Val f1_micro: 0.188
Epoch: 500, Train Loss: 1.923, Val f1_micro: 0.196
f1-micro: 0.196, f1-macro: 0.142, f1-weighted: 0.145, , roc-auc: 0.600
########## Hyperparameters combination ##########
(1024, 0.3, 0.001, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.088, Val f1_micro: 0.183
Epoch: 040, Train Loss: 1.810, Val f1_micro: 0.217
Epoch: 060, Train Loss: 1.665, Val f1_micro: 0.233
Epoch: 080, Train Loss: 1.554, Val f1_micro: 0.238
Epoch: 100, Train Loss: 1.449, Val f1_micro: 0.241
Epoch: 120, Train Loss: 1.364, Val f1_micro: 0.248
Epoch: 140, Train Loss: 1.307, Val f1_micro: 0.254
Epoch: 160, Train Loss: 1.239, Val f1_micro: 0.261
Epoch: 180, Train Loss: 1.194, Val f1_micro: 0.267
Epoch: 200, Train Loss: 1.146, Val f1_micro: 0.268
Epoch: 220, Train Loss: 1.096, Val f1_micro: 0.271
Epoch: 240, Train Loss: 1.062, Val f1_micro: 0.274
Epoch: 260, Train Loss: 1.019, Val f1_micro: 0.277
Epoch: 280, Train Loss: 0.990, Val f1_micro: 0.280
Epoch: 300, Train Loss: 0.949, Val f1_micro: 0.282
Epoch: 320, Train Loss: 0.922, Val f1_micro: 0.282
Epoch: 340, Train Loss: 0.888, Val f1_micro: 0.282
Epoch: 360, Train Loss: 0.852, Val f1_micro: 0.287
Epoch: 380, Train Loss: 0.834, Val f1_micro: 0.288
Epoch: 400, Train Loss: 0.830, Val f1_micro: 0.291
Epoch: 420, Train Loss: 0.795, Val f1_micro: 0.291
Epoch: 440, Train Loss: 0.777, Val f1_micro: 0.292
Epoch: 460, Train Loss: 0.751, Val f1_micro: 0.291
Epoch: 480, Train Loss: 0.730, Val f1_micro: 0.294
Epoch: 500, Train Loss: 0.722, Val f1_micro: 0.295
f1-micro: 0.295, f1-macro: 0.288, f1-weighted: 0.291, , roc-auc: 0.689
##### RUN 2 #####
Epoch: 020, Train Loss: 2.090, Val f1_micro: 0.185
Epoch: 040, Train Loss: 1.813, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.662, Val f1_micro: 0.230
Epoch: 080, Train Loss: 1.545, Val f1_micro: 0.239
Epoch: 100, Train Loss: 1.451, Val f1_micro: 0.243
Epoch: 120, Train Loss: 1.372, Val f1_micro: 0.249
Epoch: 140, Train Loss: 1.307, Val f1_micro: 0.257
Epoch: 160, Train Loss: 1.244, Val f1_micro: 0.261
Epoch: 180, Train Loss: 1.188, Val f1_micro: 0.264
Epoch: 200, Train Loss: 1.137, Val f1_micro: 0.270
Epoch: 220, Train Loss: 1.100, Val f1_micro: 0.273
Epoch: 240, Train Loss: 1.050, Val f1_micro: 0.275
Epoch: 260, Train Loss: 0.999, Val f1_micro: 0.278
Epoch: 280, Train Loss: 0.984, Val f1_micro: 0.280
Epoch: 300, Train Loss: 0.940, Val f1_micro: 0.282
Epoch: 320, Train Loss: 0.923, Val f1_micro: 0.283
Epoch: 340, Train Loss: 0.896, Val f1_micro: 0.286
Epoch: 360, Train Loss: 0.864, Val f1_micro: 0.286
Epoch: 380, Train Loss: 0.832, Val f1_micro: 0.288
Epoch: 400, Train Loss: 0.818, Val f1_micro: 0.290
Epoch: 420, Train Loss: 0.794, Val f1_micro: 0.290
Epoch: 440, Train Loss: 0.775, Val f1_micro: 0.293
Epoch: 460, Train Loss: 0.752, Val f1_micro: 0.293
Epoch: 480, Train Loss: 0.733, Val f1_micro: 0.295
Epoch: 500, Train Loss: 0.724, Val f1_micro: 0.294
f1-micro: 0.294, f1-macro: 0.288, f1-weighted: 0.291, , roc-auc: 0.689
##### RUN 3 #####
Epoch: 020, Train Loss: 2.082, Val f1_micro: 0.185
Epoch: 040, Train Loss: 1.840, Val f1_micro: 0.217
Epoch: 060, Train Loss: 1.663, Val f1_micro: 0.231
Epoch: 080, Train Loss: 1.540, Val f1_micro: 0.242
Epoch: 100, Train Loss: 1.450, Val f1_micro: 0.243
Epoch: 120, Train Loss: 1.369, Val f1_micro: 0.252
Epoch: 140, Train Loss: 1.305, Val f1_micro: 0.254
Epoch: 160, Train Loss: 1.233, Val f1_micro: 0.262
Epoch: 180, Train Loss: 1.200, Val f1_micro: 0.265
Epoch: 200, Train Loss: 1.134, Val f1_micro: 0.269
Epoch: 220, Train Loss: 1.106, Val f1_micro: 0.272
Epoch: 240, Train Loss: 1.056, Val f1_micro: 0.274
Epoch: 260, Train Loss: 1.026, Val f1_micro: 0.278
Epoch: 280, Train Loss: 0.984, Val f1_micro: 0.281
Epoch: 300, Train Loss: 0.959, Val f1_micro: 0.281
Epoch: 320, Train Loss: 0.919, Val f1_micro: 0.281
Epoch: 340, Train Loss: 0.895, Val f1_micro: 0.286
Epoch: 360, Train Loss: 0.864, Val f1_micro: 0.287
Epoch: 380, Train Loss: 0.840, Val f1_micro: 0.287
Epoch: 400, Train Loss: 0.811, Val f1_micro: 0.288
Epoch: 420, Train Loss: 0.800, Val f1_micro: 0.289
Epoch: 440, Train Loss: 0.777, Val f1_micro: 0.291
Epoch: 460, Train Loss: 0.749, Val f1_micro: 0.293
Epoch: 480, Train Loss: 0.744, Val f1_micro: 0.293
Epoch: 500, Train Loss: 0.719, Val f1_micro: 0.295
f1-micro: 0.295, f1-macro: 0.289, f1-weighted: 0.292, , roc-auc: 0.689
##### RUN 4 #####
Epoch: 020, Train Loss: 2.083, Val f1_micro: 0.186
Epoch: 040, Train Loss: 1.824, Val f1_micro: 0.218
Epoch: 060, Train Loss: 1.666, Val f1_micro: 0.230
Epoch: 080, Train Loss: 1.549, Val f1_micro: 0.240
Epoch: 100, Train Loss: 1.448, Val f1_micro: 0.242
Epoch: 120, Train Loss: 1.365, Val f1_micro: 0.249
Epoch: 140, Train Loss: 1.302, Val f1_micro: 0.256
Epoch: 160, Train Loss: 1.246, Val f1_micro: 0.261
Epoch: 180, Train Loss: 1.189, Val f1_micro: 0.266
Epoch: 200, Train Loss: 1.164, Val f1_micro: 0.271
Epoch: 220, Train Loss: 1.082, Val f1_micro: 0.273
Epoch: 240, Train Loss: 1.041, Val f1_micro: 0.276
Epoch: 260, Train Loss: 1.018, Val f1_micro: 0.276
Epoch: 280, Train Loss: 0.985, Val f1_micro: 0.280
Epoch: 300, Train Loss: 0.936, Val f1_micro: 0.281
Epoch: 320, Train Loss: 0.919, Val f1_micro: 0.281
Epoch: 340, Train Loss: 0.900, Val f1_micro: 0.284
Epoch: 360, Train Loss: 0.864, Val f1_micro: 0.286
Epoch: 380, Train Loss: 0.850, Val f1_micro: 0.289
Epoch: 400, Train Loss: 0.806, Val f1_micro: 0.290
Epoch: 420, Train Loss: 0.803, Val f1_micro: 0.289
Epoch: 440, Train Loss: 0.786, Val f1_micro: 0.290
Epoch: 460, Train Loss: 0.738, Val f1_micro: 0.290
Epoch: 480, Train Loss: 0.722, Val f1_micro: 0.295
Epoch: 500, Train Loss: 0.718, Val f1_micro: 0.295
f1-micro: 0.295, f1-macro: 0.290, f1-weighted: 0.293, , roc-auc: 0.689
##### RUN 5 #####
Epoch: 020, Train Loss: 2.096, Val f1_micro: 0.186
Epoch: 040, Train Loss: 1.827, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.666, Val f1_micro: 0.230
Epoch: 080, Train Loss: 1.531, Val f1_micro: 0.238
Epoch: 100, Train Loss: 1.456, Val f1_micro: 0.240
Epoch: 120, Train Loss: 1.369, Val f1_micro: 0.248
Epoch: 140, Train Loss: 1.317, Val f1_micro: 0.255
Epoch: 160, Train Loss: 1.247, Val f1_micro: 0.259
Epoch: 180, Train Loss: 1.194, Val f1_micro: 0.265
Epoch: 200, Train Loss: 1.133, Val f1_micro: 0.269
Epoch: 220, Train Loss: 1.111, Val f1_micro: 0.274
Epoch: 240, Train Loss: 1.046, Val f1_micro: 0.273
Epoch: 260, Train Loss: 1.017, Val f1_micro: 0.277
Epoch: 280, Train Loss: 0.991, Val f1_micro: 0.280
Epoch: 300, Train Loss: 0.947, Val f1_micro: 0.282
Epoch: 320, Train Loss: 0.926, Val f1_micro: 0.284
Epoch: 340, Train Loss: 0.875, Val f1_micro: 0.284
Epoch: 360, Train Loss: 0.863, Val f1_micro: 0.286
Epoch: 380, Train Loss: 0.858, Val f1_micro: 0.287
Epoch: 400, Train Loss: 0.818, Val f1_micro: 0.288
Epoch: 420, Train Loss: 0.798, Val f1_micro: 0.290
Epoch: 440, Train Loss: 0.791, Val f1_micro: 0.290
Epoch: 460, Train Loss: 0.759, Val f1_micro: 0.293
Epoch: 480, Train Loss: 0.743, Val f1_micro: 0.293
Epoch: 500, Train Loss: 0.720, Val f1_micro: 0.292
f1-micro: 0.292, f1-macro: 0.286, f1-weighted: 0.288, , roc-auc: 0.689
########## Hyperparameters combination ##########
(1024, 0.3, 0.001, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.101, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.837, Val f1_micro: 0.218
Epoch: 060, Train Loss: 1.667, Val f1_micro: 0.234
Epoch: 080, Train Loss: 1.546, Val f1_micro: 0.240
Epoch: 100, Train Loss: 1.461, Val f1_micro: 0.242
Epoch: 120, Train Loss: 1.385, Val f1_micro: 0.249
Epoch: 140, Train Loss: 1.322, Val f1_micro: 0.253
Epoch: 160, Train Loss: 1.277, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.220, Val f1_micro: 0.260
Epoch: 200, Train Loss: 1.175, Val f1_micro: 0.264
Epoch: 220, Train Loss: 1.153, Val f1_micro: 0.266
Epoch: 240, Train Loss: 1.107, Val f1_micro: 0.270
Epoch: 260, Train Loss: 1.063, Val f1_micro: 0.270
Epoch: 280, Train Loss: 1.039, Val f1_micro: 0.273
Epoch: 300, Train Loss: 1.029, Val f1_micro: 0.274
Epoch: 320, Train Loss: 0.998, Val f1_micro: 0.274
Epoch: 340, Train Loss: 0.974, Val f1_micro: 0.277
Epoch: 360, Train Loss: 0.949, Val f1_micro: 0.277
Epoch: 380, Train Loss: 0.924, Val f1_micro: 0.280
Epoch: 400, Train Loss: 0.901, Val f1_micro: 0.280
Epoch: 420, Train Loss: 0.893, Val f1_micro: 0.281
Epoch: 440, Train Loss: 0.875, Val f1_micro: 0.281
Epoch: 460, Train Loss: 0.867, Val f1_micro: 0.284
Epoch: 480, Train Loss: 0.845, Val f1_micro: 0.285
Epoch: 500, Train Loss: 0.830, Val f1_micro: 0.286
f1-micro: 0.286, f1-macro: 0.278, f1-weighted: 0.280, , roc-auc: 0.684
##### RUN 2 #####
Epoch: 020, Train Loss: 2.101, Val f1_micro: 0.190
Epoch: 040, Train Loss: 1.828, Val f1_micro: 0.218
Epoch: 060, Train Loss: 1.684, Val f1_micro: 0.233
Epoch: 080, Train Loss: 1.555, Val f1_micro: 0.240
Epoch: 100, Train Loss: 1.456, Val f1_micro: 0.245
Epoch: 120, Train Loss: 1.392, Val f1_micro: 0.247
Epoch: 140, Train Loss: 1.339, Val f1_micro: 0.255
Epoch: 160, Train Loss: 1.277, Val f1_micro: 0.256
Epoch: 180, Train Loss: 1.238, Val f1_micro: 0.259
Epoch: 200, Train Loss: 1.183, Val f1_micro: 0.264
Epoch: 220, Train Loss: 1.155, Val f1_micro: 0.268
Epoch: 240, Train Loss: 1.114, Val f1_micro: 0.269
Epoch: 260, Train Loss: 1.095, Val f1_micro: 0.273
Epoch: 280, Train Loss: 1.054, Val f1_micro: 0.272
Epoch: 300, Train Loss: 1.024, Val f1_micro: 0.275
Epoch: 320, Train Loss: 0.982, Val f1_micro: 0.276
Epoch: 340, Train Loss: 0.962, Val f1_micro: 0.277
Epoch: 360, Train Loss: 0.954, Val f1_micro: 0.276
Epoch: 380, Train Loss: 0.931, Val f1_micro: 0.278
Epoch: 400, Train Loss: 0.902, Val f1_micro: 0.279
Epoch: 420, Train Loss: 0.888, Val f1_micro: 0.279
Epoch: 440, Train Loss: 0.873, Val f1_micro: 0.279
Epoch: 460, Train Loss: 0.864, Val f1_micro: 0.281
Epoch: 480, Train Loss: 0.855, Val f1_micro: 0.282
Epoch: 500, Train Loss: 0.826, Val f1_micro: 0.283
f1-micro: 0.283, f1-macro: 0.275, f1-weighted: 0.277, , roc-auc: 0.683
##### RUN 3 #####
Epoch: 020, Train Loss: 2.097, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.830, Val f1_micro: 0.218
Epoch: 060, Train Loss: 1.683, Val f1_micro: 0.233
Epoch: 080, Train Loss: 1.553, Val f1_micro: 0.241
Epoch: 100, Train Loss: 1.470, Val f1_micro: 0.245
Epoch: 120, Train Loss: 1.393, Val f1_micro: 0.250
Epoch: 140, Train Loss: 1.332, Val f1_micro: 0.254
Epoch: 160, Train Loss: 1.283, Val f1_micro: 0.259
Epoch: 180, Train Loss: 1.238, Val f1_micro: 0.261
Epoch: 200, Train Loss: 1.193, Val f1_micro: 0.263
Epoch: 220, Train Loss: 1.145, Val f1_micro: 0.268
Epoch: 240, Train Loss: 1.103, Val f1_micro: 0.269
Epoch: 260, Train Loss: 1.068, Val f1_micro: 0.270
Epoch: 280, Train Loss: 1.044, Val f1_micro: 0.273
Epoch: 300, Train Loss: 1.026, Val f1_micro: 0.274
Epoch: 320, Train Loss: 0.988, Val f1_micro: 0.275
Epoch: 340, Train Loss: 0.967, Val f1_micro: 0.277
Epoch: 360, Train Loss: 0.940, Val f1_micro: 0.278
Epoch: 380, Train Loss: 0.927, Val f1_micro: 0.280
Epoch: 400, Train Loss: 0.897, Val f1_micro: 0.280
Epoch: 420, Train Loss: 0.892, Val f1_micro: 0.281
Epoch: 440, Train Loss: 0.882, Val f1_micro: 0.282
Epoch: 460, Train Loss: 0.861, Val f1_micro: 0.283
Epoch: 480, Train Loss: 0.845, Val f1_micro: 0.283
Epoch: 500, Train Loss: 0.837, Val f1_micro: 0.285
f1-micro: 0.285, f1-macro: 0.276, f1-weighted: 0.278, , roc-auc: 0.684
##### RUN 4 #####
Epoch: 020, Train Loss: 2.099, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.823, Val f1_micro: 0.219
Epoch: 060, Train Loss: 1.660, Val f1_micro: 0.233
Epoch: 080, Train Loss: 1.549, Val f1_micro: 0.242
Epoch: 100, Train Loss: 1.455, Val f1_micro: 0.245
Epoch: 120, Train Loss: 1.392, Val f1_micro: 0.250
Epoch: 140, Train Loss: 1.333, Val f1_micro: 0.254
Epoch: 160, Train Loss: 1.276, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.225, Val f1_micro: 0.260
Epoch: 200, Train Loss: 1.194, Val f1_micro: 0.265
Epoch: 220, Train Loss: 1.145, Val f1_micro: 0.266
Epoch: 240, Train Loss: 1.100, Val f1_micro: 0.269
Epoch: 260, Train Loss: 1.098, Val f1_micro: 0.271
Epoch: 280, Train Loss: 1.054, Val f1_micro: 0.273
Epoch: 300, Train Loss: 1.032, Val f1_micro: 0.275
Epoch: 320, Train Loss: 0.982, Val f1_micro: 0.277
Epoch: 340, Train Loss: 0.955, Val f1_micro: 0.276
Epoch: 360, Train Loss: 0.953, Val f1_micro: 0.278
Epoch: 380, Train Loss: 0.925, Val f1_micro: 0.277
Epoch: 400, Train Loss: 0.905, Val f1_micro: 0.281
Epoch: 420, Train Loss: 0.894, Val f1_micro: 0.281
Epoch: 440, Train Loss: 0.864, Val f1_micro: 0.282
Epoch: 460, Train Loss: 0.860, Val f1_micro: 0.282
Epoch: 480, Train Loss: 0.845, Val f1_micro: 0.285
Epoch: 500, Train Loss: 0.832, Val f1_micro: 0.285
f1-micro: 0.285, f1-macro: 0.276, f1-weighted: 0.278, , roc-auc: 0.684
##### RUN 5 #####
Epoch: 020, Train Loss: 2.108, Val f1_micro: 0.194
Epoch: 040, Train Loss: 1.830, Val f1_micro: 0.218
Epoch: 060, Train Loss: 1.664, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.560, Val f1_micro: 0.242
Epoch: 100, Train Loss: 1.458, Val f1_micro: 0.244
Epoch: 120, Train Loss: 1.381, Val f1_micro: 0.248
Epoch: 140, Train Loss: 1.343, Val f1_micro: 0.251
Epoch: 160, Train Loss: 1.284, Val f1_micro: 0.257
Epoch: 180, Train Loss: 1.227, Val f1_micro: 0.261
Epoch: 200, Train Loss: 1.185, Val f1_micro: 0.263
Epoch: 220, Train Loss: 1.141, Val f1_micro: 0.268
Epoch: 240, Train Loss: 1.101, Val f1_micro: 0.269
Epoch: 260, Train Loss: 1.084, Val f1_micro: 0.271
Epoch: 280, Train Loss: 1.040, Val f1_micro: 0.274
Epoch: 300, Train Loss: 1.023, Val f1_micro: 0.273
Epoch: 320, Train Loss: 1.000, Val f1_micro: 0.276
Epoch: 340, Train Loss: 0.970, Val f1_micro: 0.277
Epoch: 360, Train Loss: 0.950, Val f1_micro: 0.276
Epoch: 380, Train Loss: 0.936, Val f1_micro: 0.278
Epoch: 400, Train Loss: 0.908, Val f1_micro: 0.279
Epoch: 420, Train Loss: 0.888, Val f1_micro: 0.280
Epoch: 440, Train Loss: 0.878, Val f1_micro: 0.281
Epoch: 460, Train Loss: 0.855, Val f1_micro: 0.283
Epoch: 480, Train Loss: 0.842, Val f1_micro: 0.283
Epoch: 500, Train Loss: 0.812, Val f1_micro: 0.283
f1-micro: 0.283, f1-macro: 0.276, f1-weighted: 0.278, , roc-auc: 0.684
########## Hyperparameters combination ##########
(1024, 0.3, 0.001, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.099, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.818, Val f1_micro: 0.222
Epoch: 060, Train Loss: 1.680, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.567, Val f1_micro: 0.241
Epoch: 100, Train Loss: 1.482, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.413, Val f1_micro: 0.252
Epoch: 140, Train Loss: 1.366, Val f1_micro: 0.256
Epoch: 160, Train Loss: 1.314, Val f1_micro: 0.261
Epoch: 180, Train Loss: 1.271, Val f1_micro: 0.261
Epoch: 200, Train Loss: 1.236, Val f1_micro: 0.265
Epoch: 220, Train Loss: 1.214, Val f1_micro: 0.270
Epoch: 240, Train Loss: 1.177, Val f1_micro: 0.272
Epoch: 260, Train Loss: 1.156, Val f1_micro: 0.273
Epoch: 280, Train Loss: 1.122, Val f1_micro: 0.275
Epoch: 300, Train Loss: 1.101, Val f1_micro: 0.276
Epoch: 320, Train Loss: 1.079, Val f1_micro: 0.277
Epoch: 340, Train Loss: 1.064, Val f1_micro: 0.278
Epoch: 360, Train Loss: 1.046, Val f1_micro: 0.276
Epoch: 380, Train Loss: 1.032, Val f1_micro: 0.278
Epoch: 400, Train Loss: 1.028, Val f1_micro: 0.281
Epoch: 420, Train Loss: 1.005, Val f1_micro: 0.282
Epoch: 440, Train Loss: 1.004, Val f1_micro: 0.281
Epoch: 460, Train Loss: 0.964, Val f1_micro: 0.280
Epoch: 480, Train Loss: 0.975, Val f1_micro: 0.283
Epoch: 500, Train Loss: 0.952, Val f1_micro: 0.284
f1-micro: 0.284, f1-macro: 0.275, f1-weighted: 0.278, , roc-auc: 0.685
##### RUN 2 #####
Epoch: 020, Train Loss: 2.080, Val f1_micro: 0.195
Epoch: 040, Train Loss: 1.828, Val f1_micro: 0.222
Epoch: 060, Train Loss: 1.690, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.585, Val f1_micro: 0.239
Epoch: 100, Train Loss: 1.491, Val f1_micro: 0.245
Epoch: 120, Train Loss: 1.416, Val f1_micro: 0.251
Epoch: 140, Train Loss: 1.373, Val f1_micro: 0.255
Epoch: 160, Train Loss: 1.306, Val f1_micro: 0.260
Epoch: 180, Train Loss: 1.279, Val f1_micro: 0.262
Epoch: 200, Train Loss: 1.247, Val f1_micro: 0.266
Epoch: 220, Train Loss: 1.207, Val f1_micro: 0.269
Epoch: 240, Train Loss: 1.180, Val f1_micro: 0.273
Epoch: 260, Train Loss: 1.150, Val f1_micro: 0.273
Epoch: 280, Train Loss: 1.129, Val f1_micro: 0.273
Epoch: 300, Train Loss: 1.123, Val f1_micro: 0.275
Epoch: 320, Train Loss: 1.087, Val f1_micro: 0.279
Epoch: 340, Train Loss: 1.059, Val f1_micro: 0.277
Epoch: 360, Train Loss: 1.050, Val f1_micro: 0.278
Epoch: 380, Train Loss: 1.033, Val f1_micro: 0.279
Epoch: 400, Train Loss: 1.018, Val f1_micro: 0.278
Epoch: 420, Train Loss: 1.003, Val f1_micro: 0.281
Epoch: 440, Train Loss: 0.983, Val f1_micro: 0.282
Epoch: 460, Train Loss: 0.971, Val f1_micro: 0.282
Epoch: 480, Train Loss: 0.958, Val f1_micro: 0.283
Epoch: 500, Train Loss: 0.957, Val f1_micro: 0.283
f1-micro: 0.283, f1-macro: 0.274, f1-weighted: 0.277, , roc-auc: 0.684
##### RUN 3 #####
Epoch: 020, Train Loss: 2.084, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.823, Val f1_micro: 0.223
Epoch: 060, Train Loss: 1.677, Val f1_micro: 0.234
Epoch: 080, Train Loss: 1.585, Val f1_micro: 0.241
Epoch: 100, Train Loss: 1.487, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.430, Val f1_micro: 0.252
Epoch: 140, Train Loss: 1.380, Val f1_micro: 0.255
Epoch: 160, Train Loss: 1.334, Val f1_micro: 0.259
Epoch: 180, Train Loss: 1.279, Val f1_micro: 0.263
Epoch: 200, Train Loss: 1.246, Val f1_micro: 0.266
Epoch: 220, Train Loss: 1.197, Val f1_micro: 0.271
Epoch: 240, Train Loss: 1.175, Val f1_micro: 0.272
Epoch: 260, Train Loss: 1.140, Val f1_micro: 0.275
Epoch: 280, Train Loss: 1.131, Val f1_micro: 0.276
Epoch: 300, Train Loss: 1.101, Val f1_micro: 0.276
Epoch: 320, Train Loss: 1.079, Val f1_micro: 0.277
Epoch: 340, Train Loss: 1.060, Val f1_micro: 0.278
Epoch: 360, Train Loss: 1.048, Val f1_micro: 0.278
Epoch: 380, Train Loss: 1.026, Val f1_micro: 0.279
Epoch: 400, Train Loss: 1.017, Val f1_micro: 0.282
Epoch: 420, Train Loss: 0.999, Val f1_micro: 0.282
Epoch: 440, Train Loss: 0.989, Val f1_micro: 0.281
Epoch: 460, Train Loss: 0.967, Val f1_micro: 0.280
Epoch: 480, Train Loss: 0.975, Val f1_micro: 0.284
Epoch: 500, Train Loss: 0.964, Val f1_micro: 0.284
f1-micro: 0.284, f1-macro: 0.275, f1-weighted: 0.277, , roc-auc: 0.685
##### RUN 4 #####
Epoch: 020, Train Loss: 2.113, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.824, Val f1_micro: 0.221
Epoch: 060, Train Loss: 1.681, Val f1_micro: 0.235
Epoch: 080, Train Loss: 1.559, Val f1_micro: 0.239
Epoch: 100, Train Loss: 1.484, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.416, Val f1_micro: 0.252
Epoch: 140, Train Loss: 1.365, Val f1_micro: 0.258
Epoch: 160, Train Loss: 1.319, Val f1_micro: 0.260
Epoch: 180, Train Loss: 1.277, Val f1_micro: 0.265
Epoch: 200, Train Loss: 1.241, Val f1_micro: 0.265
Epoch: 220, Train Loss: 1.211, Val f1_micro: 0.270
Epoch: 240, Train Loss: 1.178, Val f1_micro: 0.271
Epoch: 260, Train Loss: 1.148, Val f1_micro: 0.273
Epoch: 280, Train Loss: 1.137, Val f1_micro: 0.274
Epoch: 300, Train Loss: 1.104, Val f1_micro: 0.274
Epoch: 320, Train Loss: 1.088, Val f1_micro: 0.276
Epoch: 340, Train Loss: 1.073, Val f1_micro: 0.277
Epoch: 360, Train Loss: 1.054, Val f1_micro: 0.278
Epoch: 380, Train Loss: 1.027, Val f1_micro: 0.280
Epoch: 400, Train Loss: 1.015, Val f1_micro: 0.280
Epoch: 420, Train Loss: 1.001, Val f1_micro: 0.282
Epoch: 440, Train Loss: 0.980, Val f1_micro: 0.281
Epoch: 460, Train Loss: 0.982, Val f1_micro: 0.282
Epoch: 480, Train Loss: 0.967, Val f1_micro: 0.283
Epoch: 500, Train Loss: 0.960, Val f1_micro: 0.283
f1-micro: 0.283, f1-macro: 0.274, f1-weighted: 0.277, , roc-auc: 0.684
##### RUN 5 #####
Epoch: 020, Train Loss: 2.087, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.835, Val f1_micro: 0.222
Epoch: 060, Train Loss: 1.669, Val f1_micro: 0.234
Epoch: 080, Train Loss: 1.567, Val f1_micro: 0.240
Epoch: 100, Train Loss: 1.489, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.421, Val f1_micro: 0.253
Epoch: 140, Train Loss: 1.356, Val f1_micro: 0.256
Epoch: 160, Train Loss: 1.320, Val f1_micro: 0.260
Epoch: 180, Train Loss: 1.273, Val f1_micro: 0.262
Epoch: 200, Train Loss: 1.238, Val f1_micro: 0.264
Epoch: 220, Train Loss: 1.208, Val f1_micro: 0.272
Epoch: 240, Train Loss: 1.171, Val f1_micro: 0.272
Epoch: 260, Train Loss: 1.143, Val f1_micro: 0.272
Epoch: 280, Train Loss: 1.139, Val f1_micro: 0.275
Epoch: 300, Train Loss: 1.109, Val f1_micro: 0.276
Epoch: 320, Train Loss: 1.086, Val f1_micro: 0.276
Epoch: 340, Train Loss: 1.066, Val f1_micro: 0.276
Epoch: 360, Train Loss: 1.064, Val f1_micro: 0.278
Epoch: 380, Train Loss: 1.036, Val f1_micro: 0.278
Epoch: 400, Train Loss: 1.020, Val f1_micro: 0.278
Epoch: 420, Train Loss: 0.996, Val f1_micro: 0.281
Epoch: 440, Train Loss: 0.986, Val f1_micro: 0.282
Epoch: 460, Train Loss: 0.984, Val f1_micro: 0.282
Epoch: 480, Train Loss: 0.967, Val f1_micro: 0.282
Epoch: 500, Train Loss: 0.956, Val f1_micro: 0.284
f1-micro: 0.284, f1-macro: 0.274, f1-weighted: 0.277, , roc-auc: 0.685
########## Hyperparameters combination ##########
(1024, 0.3, 0.001, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.094, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.860, Val f1_micro: 0.217
Epoch: 060, Train Loss: 1.734, Val f1_micro: 0.226
Epoch: 080, Train Loss: 1.651, Val f1_micro: 0.229
Epoch: 100, Train Loss: 1.606, Val f1_micro: 0.236
Epoch: 120, Train Loss: 1.569, Val f1_micro: 0.234
Epoch: 140, Train Loss: 1.544, Val f1_micro: 0.238
Epoch: 160, Train Loss: 1.522, Val f1_micro: 0.241
Epoch: 180, Train Loss: 1.519, Val f1_micro: 0.241
Epoch: 200, Train Loss: 1.499, Val f1_micro: 0.241
Epoch: 220, Train Loss: 1.483, Val f1_micro: 0.237
Epoch: 240, Train Loss: 1.495, Val f1_micro: 0.242
Epoch: 260, Train Loss: 1.464, Val f1_micro: 0.242
Epoch: 280, Train Loss: 1.479, Val f1_micro: 0.242
Epoch: 300, Train Loss: 1.471, Val f1_micro: 0.244
Epoch: 320, Train Loss: 1.485, Val f1_micro: 0.243
Epoch: 340, Train Loss: 1.494, Val f1_micro: 0.242
Epoch: 360, Train Loss: 1.488, Val f1_micro: 0.242
Epoch: 380, Train Loss: 1.477, Val f1_micro: 0.240
Epoch: 400, Train Loss: 1.475, Val f1_micro: 0.241
Epoch: 420, Train Loss: 1.485, Val f1_micro: 0.240
Epoch: 440, Train Loss: 1.498, Val f1_micro: 0.240
Epoch: 460, Train Loss: 1.494, Val f1_micro: 0.241
Epoch: 480, Train Loss: 1.484, Val f1_micro: 0.241
Epoch: 500, Train Loss: 1.490, Val f1_micro: 0.240
f1-micro: 0.240, f1-macro: 0.219, f1-weighted: 0.218, , roc-auc: 0.663
##### RUN 2 #####
Epoch: 020, Train Loss: 2.102, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.857, Val f1_micro: 0.217
Epoch: 060, Train Loss: 1.731, Val f1_micro: 0.224
Epoch: 080, Train Loss: 1.657, Val f1_micro: 0.232
Epoch: 100, Train Loss: 1.606, Val f1_micro: 0.234
Epoch: 120, Train Loss: 1.563, Val f1_micro: 0.238
Epoch: 140, Train Loss: 1.538, Val f1_micro: 0.240
Epoch: 160, Train Loss: 1.515, Val f1_micro: 0.238
Epoch: 180, Train Loss: 1.510, Val f1_micro: 0.238
Epoch: 200, Train Loss: 1.490, Val f1_micro: 0.240
Epoch: 220, Train Loss: 1.487, Val f1_micro: 0.238
Epoch: 240, Train Loss: 1.477, Val f1_micro: 0.240
Epoch: 260, Train Loss: 1.483, Val f1_micro: 0.243
Epoch: 280, Train Loss: 1.482, Val f1_micro: 0.242
Epoch: 300, Train Loss: 1.482, Val f1_micro: 0.241
Epoch: 320, Train Loss: 1.471, Val f1_micro: 0.243
Epoch: 340, Train Loss: 1.472, Val f1_micro: 0.241
Epoch: 360, Train Loss: 1.471, Val f1_micro: 0.241
Epoch: 380, Train Loss: 1.478, Val f1_micro: 0.240
Epoch: 400, Train Loss: 1.480, Val f1_micro: 0.241
Epoch: 420, Train Loss: 1.480, Val f1_micro: 0.239
Epoch: 440, Train Loss: 1.485, Val f1_micro: 0.242
Epoch: 460, Train Loss: 1.484, Val f1_micro: 0.241
Epoch: 480, Train Loss: 1.488, Val f1_micro: 0.241
Epoch: 500, Train Loss: 1.497, Val f1_micro: 0.241
f1-micro: 0.241, f1-macro: 0.219, f1-weighted: 0.218, , roc-auc: 0.664
##### RUN 3 #####
Epoch: 020, Train Loss: 2.089, Val f1_micro: 0.188
Epoch: 040, Train Loss: 1.862, Val f1_micro: 0.214
Epoch: 060, Train Loss: 1.718, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.654, Val f1_micro: 0.230
Epoch: 100, Train Loss: 1.602, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.560, Val f1_micro: 0.236
Epoch: 140, Train Loss: 1.535, Val f1_micro: 0.239
Epoch: 160, Train Loss: 1.519, Val f1_micro: 0.237
Epoch: 180, Train Loss: 1.500, Val f1_micro: 0.239
Epoch: 200, Train Loss: 1.497, Val f1_micro: 0.237
Epoch: 220, Train Loss: 1.489, Val f1_micro: 0.244
Epoch: 240, Train Loss: 1.483, Val f1_micro: 0.245
Epoch: 260, Train Loss: 1.476, Val f1_micro: 0.243
Epoch: 280, Train Loss: 1.478, Val f1_micro: 0.244
Epoch: 300, Train Loss: 1.480, Val f1_micro: 0.241
Epoch: 320, Train Loss: 1.488, Val f1_micro: 0.242
Epoch: 340, Train Loss: 1.480, Val f1_micro: 0.244
Epoch: 360, Train Loss: 1.474, Val f1_micro: 0.244
Epoch: 380, Train Loss: 1.485, Val f1_micro: 0.242
Epoch: 400, Train Loss: 1.484, Val f1_micro: 0.240
Epoch: 420, Train Loss: 1.492, Val f1_micro: 0.240
Epoch: 440, Train Loss: 1.490, Val f1_micro: 0.242
Epoch: 460, Train Loss: 1.489, Val f1_micro: 0.240
Epoch: 480, Train Loss: 1.496, Val f1_micro: 0.239
Epoch: 500, Train Loss: 1.500, Val f1_micro: 0.240
f1-micro: 0.240, f1-macro: 0.219, f1-weighted: 0.217, , roc-auc: 0.662
##### RUN 4 #####
Epoch: 020, Train Loss: 2.105, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.858, Val f1_micro: 0.214
Epoch: 060, Train Loss: 1.732, Val f1_micro: 0.227
Epoch: 080, Train Loss: 1.655, Val f1_micro: 0.230
Epoch: 100, Train Loss: 1.593, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.568, Val f1_micro: 0.239
Epoch: 140, Train Loss: 1.538, Val f1_micro: 0.238
Epoch: 160, Train Loss: 1.507, Val f1_micro: 0.240
Epoch: 180, Train Loss: 1.508, Val f1_micro: 0.239
Epoch: 200, Train Loss: 1.495, Val f1_micro: 0.242
Epoch: 220, Train Loss: 1.487, Val f1_micro: 0.240
Epoch: 240, Train Loss: 1.482, Val f1_micro: 0.243
Epoch: 260, Train Loss: 1.479, Val f1_micro: 0.243
Epoch: 280, Train Loss: 1.479, Val f1_micro: 0.243
Epoch: 300, Train Loss: 1.482, Val f1_micro: 0.243
Epoch: 320, Train Loss: 1.473, Val f1_micro: 0.242
Epoch: 340, Train Loss: 1.480, Val f1_micro: 0.244
Epoch: 360, Train Loss: 1.476, Val f1_micro: 0.243
Epoch: 380, Train Loss: 1.479, Val f1_micro: 0.242
Epoch: 400, Train Loss: 1.484, Val f1_micro: 0.243
Epoch: 420, Train Loss: 1.480, Val f1_micro: 0.241
Epoch: 440, Train Loss: 1.486, Val f1_micro: 0.241
Epoch: 460, Train Loss: 1.492, Val f1_micro: 0.242
Epoch: 480, Train Loss: 1.504, Val f1_micro: 0.240
Epoch: 500, Train Loss: 1.485, Val f1_micro: 0.241
f1-micro: 0.241, f1-macro: 0.219, f1-weighted: 0.218, , roc-auc: 0.662
##### RUN 5 #####
Epoch: 020, Train Loss: 2.095, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.855, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.746, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.648, Val f1_micro: 0.232
Epoch: 100, Train Loss: 1.603, Val f1_micro: 0.233
Epoch: 120, Train Loss: 1.563, Val f1_micro: 0.236
Epoch: 140, Train Loss: 1.532, Val f1_micro: 0.237
Epoch: 160, Train Loss: 1.519, Val f1_micro: 0.241
Epoch: 180, Train Loss: 1.510, Val f1_micro: 0.240
Epoch: 200, Train Loss: 1.486, Val f1_micro: 0.241
Epoch: 220, Train Loss: 1.484, Val f1_micro: 0.242
Epoch: 240, Train Loss: 1.481, Val f1_micro: 0.243
Epoch: 260, Train Loss: 1.482, Val f1_micro: 0.242
Epoch: 280, Train Loss: 1.486, Val f1_micro: 0.242
Epoch: 300, Train Loss: 1.479, Val f1_micro: 0.241
Epoch: 320, Train Loss: 1.480, Val f1_micro: 0.240
Epoch: 340, Train Loss: 1.482, Val f1_micro: 0.243
Epoch: 360, Train Loss: 1.473, Val f1_micro: 0.241
Epoch: 380, Train Loss: 1.494, Val f1_micro: 0.242
Epoch: 400, Train Loss: 1.486, Val f1_micro: 0.241
Epoch: 420, Train Loss: 1.487, Val f1_micro: 0.242
Epoch: 440, Train Loss: 1.483, Val f1_micro: 0.242
Epoch: 460, Train Loss: 1.484, Val f1_micro: 0.241
Epoch: 480, Train Loss: 1.491, Val f1_micro: 0.241
Epoch: 500, Train Loss: 1.496, Val f1_micro: 0.241
f1-micro: 0.241, f1-macro: 0.220, f1-weighted: 0.218, , roc-auc: 0.663
########## Hyperparameters combination ##########
(1024, 0.3, 0.005, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.579, Val f1_micro: 0.242
Epoch: 040, Train Loss: 1.259, Val f1_micro: 0.257
Epoch: 060, Train Loss: 1.070, Val f1_micro: 0.272
Epoch: 080, Train Loss: 0.940, Val f1_micro: 0.283
Epoch: 100, Train Loss: 0.854, Val f1_micro: 0.289
Epoch: 120, Train Loss: 0.754, Val f1_micro: 0.296
Epoch: 140, Train Loss: 0.674, Val f1_micro: 0.301
Epoch: 160, Train Loss: 0.636, Val f1_micro: 0.303
Epoch: 180, Train Loss: 0.554, Val f1_micro: 0.307
Epoch: 200, Train Loss: 0.515, Val f1_micro: 0.309
Epoch: 220, Train Loss: 0.488, Val f1_micro: 0.314
Epoch: 240, Train Loss: 0.461, Val f1_micro: 0.317
Epoch: 260, Train Loss: 0.395, Val f1_micro: 0.315
Epoch: 280, Train Loss: 0.373, Val f1_micro: 0.318
Epoch: 300, Train Loss: 0.346, Val f1_micro: 0.320
Epoch: 320, Train Loss: 0.323, Val f1_micro: 0.320
Epoch: 340, Train Loss: 0.320, Val f1_micro: 0.323
Epoch: 360, Train Loss: 0.306, Val f1_micro: 0.323
Epoch: 380, Train Loss: 0.270, Val f1_micro: 0.323
Epoch: 400, Train Loss: 0.263, Val f1_micro: 0.322
Epoch: 420, Train Loss: 0.251, Val f1_micro: 0.320
Epoch: 440, Train Loss: 0.244, Val f1_micro: 0.321
Epoch: 460, Train Loss: 0.232, Val f1_micro: 0.323
Epoch: 480, Train Loss: 0.227, Val f1_micro: 0.324
Epoch: 500, Train Loss: 0.208, Val f1_micro: 0.326
f1-micro: 0.326, f1-macro: 0.320, f1-weighted: 0.325, , roc-auc: 0.700
##### RUN 2 #####
Epoch: 020, Train Loss: 1.590, Val f1_micro: 0.240
Epoch: 040, Train Loss: 1.276, Val f1_micro: 0.254
Epoch: 060, Train Loss: 1.092, Val f1_micro: 0.271
Epoch: 080, Train Loss: 0.951, Val f1_micro: 0.282
Epoch: 100, Train Loss: 0.844, Val f1_micro: 0.290
Epoch: 120, Train Loss: 0.771, Val f1_micro: 0.294
Epoch: 140, Train Loss: 0.701, Val f1_micro: 0.298
Epoch: 160, Train Loss: 0.639, Val f1_micro: 0.303
Epoch: 180, Train Loss: 0.568, Val f1_micro: 0.305
Epoch: 200, Train Loss: 0.527, Val f1_micro: 0.311
Epoch: 220, Train Loss: 0.475, Val f1_micro: 0.312
Epoch: 240, Train Loss: 0.455, Val f1_micro: 0.315
Epoch: 260, Train Loss: 0.400, Val f1_micro: 0.317
Epoch: 280, Train Loss: 0.375, Val f1_micro: 0.317
Epoch: 300, Train Loss: 0.369, Val f1_micro: 0.319
Epoch: 320, Train Loss: 0.321, Val f1_micro: 0.321
Epoch: 340, Train Loss: 0.305, Val f1_micro: 0.319
Epoch: 360, Train Loss: 0.286, Val f1_micro: 0.321
Epoch: 380, Train Loss: 0.285, Val f1_micro: 0.322
Epoch: 400, Train Loss: 0.270, Val f1_micro: 0.322
Epoch: 420, Train Loss: 0.245, Val f1_micro: 0.324
Epoch: 440, Train Loss: 0.239, Val f1_micro: 0.325
Epoch: 460, Train Loss: 0.248, Val f1_micro: 0.327
Epoch: 480, Train Loss: 0.230, Val f1_micro: 0.320
Epoch: 500, Train Loss: 0.234, Val f1_micro: 0.324
f1-micro: 0.324, f1-macro: 0.319, f1-weighted: 0.324, , roc-auc: 0.699
##### RUN 3 #####
Epoch: 020, Train Loss: 1.580, Val f1_micro: 0.239
Epoch: 040, Train Loss: 1.276, Val f1_micro: 0.259
Epoch: 060, Train Loss: 1.098, Val f1_micro: 0.271
Epoch: 080, Train Loss: 0.964, Val f1_micro: 0.281
Epoch: 100, Train Loss: 0.865, Val f1_micro: 0.285
Epoch: 120, Train Loss: 0.763, Val f1_micro: 0.297
Epoch: 140, Train Loss: 0.696, Val f1_micro: 0.301
Epoch: 160, Train Loss: 0.630, Val f1_micro: 0.302
Epoch: 180, Train Loss: 0.575, Val f1_micro: 0.306
Epoch: 200, Train Loss: 0.543, Val f1_micro: 0.310
Epoch: 220, Train Loss: 0.489, Val f1_micro: 0.310
Epoch: 240, Train Loss: 0.466, Val f1_micro: 0.313
Epoch: 260, Train Loss: 0.388, Val f1_micro: 0.314
Epoch: 280, Train Loss: 0.387, Val f1_micro: 0.317
Epoch: 300, Train Loss: 0.356, Val f1_micro: 0.319
Epoch: 320, Train Loss: 0.337, Val f1_micro: 0.320
Epoch: 340, Train Loss: 0.327, Val f1_micro: 0.320
Epoch: 360, Train Loss: 0.297, Val f1_micro: 0.318
Epoch: 380, Train Loss: 0.289, Val f1_micro: 0.318
Epoch: 400, Train Loss: 0.263, Val f1_micro: 0.318
Epoch: 420, Train Loss: 0.239, Val f1_micro: 0.320
Epoch: 440, Train Loss: 0.250, Val f1_micro: 0.322
Epoch: 460, Train Loss: 0.240, Val f1_micro: 0.322
Epoch: 480, Train Loss: 0.241, Val f1_micro: 0.322
Epoch: 500, Train Loss: 0.212, Val f1_micro: 0.322
f1-micro: 0.322, f1-macro: 0.316, f1-weighted: 0.321, , roc-auc: 0.698
##### RUN 4 #####
Epoch: 020, Train Loss: 1.592, Val f1_micro: 0.239
Epoch: 040, Train Loss: 1.281, Val f1_micro: 0.255
Epoch: 060, Train Loss: 1.094, Val f1_micro: 0.272
Epoch: 080, Train Loss: 0.952, Val f1_micro: 0.286
Epoch: 100, Train Loss: 0.862, Val f1_micro: 0.291
Epoch: 120, Train Loss: 0.773, Val f1_micro: 0.293
Epoch: 140, Train Loss: 0.703, Val f1_micro: 0.300
Epoch: 160, Train Loss: 0.641, Val f1_micro: 0.301
Epoch: 180, Train Loss: 0.565, Val f1_micro: 0.306
Epoch: 200, Train Loss: 0.533, Val f1_micro: 0.310
Epoch: 220, Train Loss: 0.495, Val f1_micro: 0.312
Epoch: 240, Train Loss: 0.457, Val f1_micro: 0.313
Epoch: 260, Train Loss: 0.418, Val f1_micro: 0.316
Epoch: 280, Train Loss: 0.385, Val f1_micro: 0.317
Epoch: 300, Train Loss: 0.372, Val f1_micro: 0.317
Epoch: 320, Train Loss: 0.345, Val f1_micro: 0.318
Epoch: 340, Train Loss: 0.322, Val f1_micro: 0.321
Epoch: 360, Train Loss: 0.300, Val f1_micro: 0.324
Epoch: 380, Train Loss: 0.290, Val f1_micro: 0.321
Epoch: 400, Train Loss: 0.269, Val f1_micro: 0.323
Epoch: 420, Train Loss: 0.267, Val f1_micro: 0.324
Epoch: 440, Train Loss: 0.244, Val f1_micro: 0.323
Epoch: 460, Train Loss: 0.225, Val f1_micro: 0.326
Epoch: 480, Train Loss: 0.214, Val f1_micro: 0.325
Epoch: 500, Train Loss: 0.221, Val f1_micro: 0.325
f1-micro: 0.325, f1-macro: 0.320, f1-weighted: 0.325, , roc-auc: 0.698
##### RUN 5 #####
Epoch: 020, Train Loss: 1.565, Val f1_micro: 0.241
Epoch: 040, Train Loss: 1.273, Val f1_micro: 0.257
Epoch: 060, Train Loss: 1.092, Val f1_micro: 0.276
Epoch: 080, Train Loss: 0.949, Val f1_micro: 0.285
Epoch: 100, Train Loss: 0.839, Val f1_micro: 0.289
Epoch: 120, Train Loss: 0.771, Val f1_micro: 0.294
Epoch: 140, Train Loss: 0.684, Val f1_micro: 0.299
Epoch: 160, Train Loss: 0.635, Val f1_micro: 0.301
Epoch: 180, Train Loss: 0.556, Val f1_micro: 0.304
Epoch: 200, Train Loss: 0.504, Val f1_micro: 0.309
Epoch: 220, Train Loss: 0.488, Val f1_micro: 0.311
Epoch: 240, Train Loss: 0.448, Val f1_micro: 0.312
Epoch: 260, Train Loss: 0.405, Val f1_micro: 0.312
Epoch: 280, Train Loss: 0.381, Val f1_micro: 0.314
Epoch: 300, Train Loss: 0.363, Val f1_micro: 0.315
Epoch: 320, Train Loss: 0.316, Val f1_micro: 0.318
Epoch: 340, Train Loss: 0.315, Val f1_micro: 0.316
Epoch: 360, Train Loss: 0.304, Val f1_micro: 0.318
Epoch: 380, Train Loss: 0.284, Val f1_micro: 0.320
Epoch: 400, Train Loss: 0.280, Val f1_micro: 0.319
Epoch: 420, Train Loss: 0.266, Val f1_micro: 0.318
Epoch: 440, Train Loss: 0.259, Val f1_micro: 0.317
Epoch: 460, Train Loss: 0.235, Val f1_micro: 0.321
Epoch: 480, Train Loss: 0.235, Val f1_micro: 0.320
Epoch: 500, Train Loss: 0.213, Val f1_micro: 0.320
f1-micro: 0.320, f1-macro: 0.315, f1-weighted: 0.321, , roc-auc: 0.697
########## Hyperparameters combination ##########
(1024, 0.3, 0.005, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.576, Val f1_micro: 0.242
Epoch: 040, Train Loss: 1.302, Val f1_micro: 0.256
Epoch: 060, Train Loss: 1.148, Val f1_micro: 0.267
Epoch: 080, Train Loss: 1.035, Val f1_micro: 0.274
Epoch: 100, Train Loss: 0.958, Val f1_micro: 0.283
Epoch: 120, Train Loss: 0.882, Val f1_micro: 0.281
Epoch: 140, Train Loss: 0.820, Val f1_micro: 0.288
Epoch: 160, Train Loss: 0.781, Val f1_micro: 0.291
Epoch: 180, Train Loss: 0.753, Val f1_micro: 0.289
Epoch: 200, Train Loss: 0.712, Val f1_micro: 0.295
Epoch: 220, Train Loss: 0.679, Val f1_micro: 0.296
Epoch: 240, Train Loss: 0.640, Val f1_micro: 0.299
Epoch: 260, Train Loss: 0.641, Val f1_micro: 0.299
Epoch: 280, Train Loss: 0.624, Val f1_micro: 0.301
Epoch: 300, Train Loss: 0.586, Val f1_micro: 0.302
Epoch: 320, Train Loss: 0.572, Val f1_micro: 0.303
Epoch: 340, Train Loss: 0.571, Val f1_micro: 0.305
Epoch: 360, Train Loss: 0.546, Val f1_micro: 0.310
Epoch: 380, Train Loss: 0.528, Val f1_micro: 0.310
Epoch: 400, Train Loss: 0.522, Val f1_micro: 0.311
Epoch: 420, Train Loss: 0.518, Val f1_micro: 0.310
Epoch: 440, Train Loss: 0.504, Val f1_micro: 0.311
Epoch: 460, Train Loss: 0.502, Val f1_micro: 0.310
Epoch: 480, Train Loss: 0.474, Val f1_micro: 0.313
Epoch: 500, Train Loss: 0.475, Val f1_micro: 0.312
f1-micro: 0.312, f1-macro: 0.307, f1-weighted: 0.312, , roc-auc: 0.690
##### RUN 2 #####
Epoch: 020, Train Loss: 1.599, Val f1_micro: 0.238
Epoch: 040, Train Loss: 1.292, Val f1_micro: 0.254
Epoch: 060, Train Loss: 1.145, Val f1_micro: 0.263
Epoch: 080, Train Loss: 1.034, Val f1_micro: 0.272
Epoch: 100, Train Loss: 0.939, Val f1_micro: 0.280
Epoch: 120, Train Loss: 0.882, Val f1_micro: 0.284
Epoch: 140, Train Loss: 0.824, Val f1_micro: 0.285
Epoch: 160, Train Loss: 0.801, Val f1_micro: 0.291
Epoch: 180, Train Loss: 0.734, Val f1_micro: 0.294
Epoch: 200, Train Loss: 0.713, Val f1_micro: 0.295
Epoch: 220, Train Loss: 0.682, Val f1_micro: 0.299
Epoch: 240, Train Loss: 0.639, Val f1_micro: 0.297
Epoch: 260, Train Loss: 0.640, Val f1_micro: 0.304
Epoch: 280, Train Loss: 0.612, Val f1_micro: 0.303
Epoch: 300, Train Loss: 0.594, Val f1_micro: 0.309
Epoch: 320, Train Loss: 0.596, Val f1_micro: 0.307
Epoch: 340, Train Loss: 0.566, Val f1_micro: 0.308
Epoch: 360, Train Loss: 0.560, Val f1_micro: 0.308
Epoch: 380, Train Loss: 0.540, Val f1_micro: 0.312
Epoch: 400, Train Loss: 0.540, Val f1_micro: 0.309
Epoch: 420, Train Loss: 0.508, Val f1_micro: 0.312
Epoch: 440, Train Loss: 0.499, Val f1_micro: 0.311
Epoch: 460, Train Loss: 0.485, Val f1_micro: 0.314
Epoch: 480, Train Loss: 0.488, Val f1_micro: 0.312
Epoch: 500, Train Loss: 0.479, Val f1_micro: 0.314
f1-micro: 0.314, f1-macro: 0.309, f1-weighted: 0.314, , roc-auc: 0.689
##### RUN 3 #####
Epoch: 020, Train Loss: 1.587, Val f1_micro: 0.241
Epoch: 040, Train Loss: 1.287, Val f1_micro: 0.257
Epoch: 060, Train Loss: 1.126, Val f1_micro: 0.268
Epoch: 080, Train Loss: 1.028, Val f1_micro: 0.273
Epoch: 100, Train Loss: 0.950, Val f1_micro: 0.278
Epoch: 120, Train Loss: 0.883, Val f1_micro: 0.285
Epoch: 140, Train Loss: 0.833, Val f1_micro: 0.286
Epoch: 160, Train Loss: 0.789, Val f1_micro: 0.291
Epoch: 180, Train Loss: 0.753, Val f1_micro: 0.290
Epoch: 200, Train Loss: 0.715, Val f1_micro: 0.295
Epoch: 220, Train Loss: 0.683, Val f1_micro: 0.300
Epoch: 240, Train Loss: 0.653, Val f1_micro: 0.300
Epoch: 260, Train Loss: 0.643, Val f1_micro: 0.298
Epoch: 280, Train Loss: 0.604, Val f1_micro: 0.304
Epoch: 300, Train Loss: 0.598, Val f1_micro: 0.304
Epoch: 320, Train Loss: 0.585, Val f1_micro: 0.302
Epoch: 340, Train Loss: 0.550, Val f1_micro: 0.308
Epoch: 360, Train Loss: 0.547, Val f1_micro: 0.308
Epoch: 380, Train Loss: 0.549, Val f1_micro: 0.311
Epoch: 400, Train Loss: 0.519, Val f1_micro: 0.309
Epoch: 420, Train Loss: 0.498, Val f1_micro: 0.311
Epoch: 440, Train Loss: 0.492, Val f1_micro: 0.311
Epoch: 460, Train Loss: 0.482, Val f1_micro: 0.318
Epoch: 480, Train Loss: 0.483, Val f1_micro: 0.315
Epoch: 500, Train Loss: 0.485, Val f1_micro: 0.318
f1-micro: 0.318, f1-macro: 0.312, f1-weighted: 0.317, , roc-auc: 0.690
##### RUN 4 #####
Epoch: 020, Train Loss: 1.584, Val f1_micro: 0.234
Epoch: 040, Train Loss: 1.296, Val f1_micro: 0.255
Epoch: 060, Train Loss: 1.141, Val f1_micro: 0.267
Epoch: 080, Train Loss: 1.029, Val f1_micro: 0.275
Epoch: 100, Train Loss: 0.941, Val f1_micro: 0.279
Epoch: 120, Train Loss: 0.881, Val f1_micro: 0.284
Epoch: 140, Train Loss: 0.818, Val f1_micro: 0.284
Epoch: 160, Train Loss: 0.786, Val f1_micro: 0.289
Epoch: 180, Train Loss: 0.757, Val f1_micro: 0.292
Epoch: 200, Train Loss: 0.712, Val f1_micro: 0.295
Epoch: 220, Train Loss: 0.673, Val f1_micro: 0.299
Epoch: 240, Train Loss: 0.653, Val f1_micro: 0.300
Epoch: 260, Train Loss: 0.634, Val f1_micro: 0.303
Epoch: 280, Train Loss: 0.599, Val f1_micro: 0.302
Epoch: 300, Train Loss: 0.611, Val f1_micro: 0.302
Epoch: 320, Train Loss: 0.597, Val f1_micro: 0.304
Epoch: 340, Train Loss: 0.556, Val f1_micro: 0.306
Epoch: 360, Train Loss: 0.550, Val f1_micro: 0.305
Epoch: 380, Train Loss: 0.522, Val f1_micro: 0.308
Epoch: 400, Train Loss: 0.520, Val f1_micro: 0.308
Epoch: 420, Train Loss: 0.512, Val f1_micro: 0.313
Epoch: 440, Train Loss: 0.501, Val f1_micro: 0.312
Epoch: 460, Train Loss: 0.501, Val f1_micro: 0.311
Epoch: 480, Train Loss: 0.491, Val f1_micro: 0.314
Epoch: 500, Train Loss: 0.477, Val f1_micro: 0.314
f1-micro: 0.314, f1-macro: 0.309, f1-weighted: 0.314, , roc-auc: 0.690
##### RUN 5 #####
Epoch: 020, Train Loss: 1.573, Val f1_micro: 0.240
Epoch: 040, Train Loss: 1.313, Val f1_micro: 0.251
Epoch: 060, Train Loss: 1.130, Val f1_micro: 0.263
Epoch: 080, Train Loss: 1.018, Val f1_micro: 0.276
Epoch: 100, Train Loss: 0.951, Val f1_micro: 0.278
Epoch: 120, Train Loss: 0.902, Val f1_micro: 0.283
Epoch: 140, Train Loss: 0.835, Val f1_micro: 0.284
Epoch: 160, Train Loss: 0.792, Val f1_micro: 0.289
Epoch: 180, Train Loss: 0.748, Val f1_micro: 0.292
Epoch: 200, Train Loss: 0.719, Val f1_micro: 0.294
Epoch: 220, Train Loss: 0.683, Val f1_micro: 0.294
Epoch: 240, Train Loss: 0.662, Val f1_micro: 0.296
Epoch: 260, Train Loss: 0.633, Val f1_micro: 0.300
Epoch: 280, Train Loss: 0.613, Val f1_micro: 0.302
Epoch: 300, Train Loss: 0.602, Val f1_micro: 0.305
Epoch: 320, Train Loss: 0.577, Val f1_micro: 0.301
Epoch: 340, Train Loss: 0.550, Val f1_micro: 0.307
Epoch: 360, Train Loss: 0.527, Val f1_micro: 0.308
Epoch: 380, Train Loss: 0.531, Val f1_micro: 0.307
Epoch: 400, Train Loss: 0.527, Val f1_micro: 0.312
Epoch: 420, Train Loss: 0.506, Val f1_micro: 0.310
Epoch: 440, Train Loss: 0.511, Val f1_micro: 0.309
Epoch: 460, Train Loss: 0.472, Val f1_micro: 0.313
Epoch: 480, Train Loss: 0.482, Val f1_micro: 0.313
Epoch: 500, Train Loss: 0.475, Val f1_micro: 0.315
f1-micro: 0.315, f1-macro: 0.308, f1-weighted: 0.313, , roc-auc: 0.690
########## Hyperparameters combination ##########
(1024, 0.3, 0.005, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.565, Val f1_micro: 0.238
Epoch: 040, Train Loss: 1.329, Val f1_micro: 0.254
Epoch: 060, Train Loss: 1.186, Val f1_micro: 0.264
Epoch: 080, Train Loss: 1.110, Val f1_micro: 0.269
Epoch: 100, Train Loss: 1.039, Val f1_micro: 0.277
Epoch: 120, Train Loss: 0.982, Val f1_micro: 0.281
Epoch: 140, Train Loss: 0.960, Val f1_micro: 0.284
Epoch: 160, Train Loss: 0.922, Val f1_micro: 0.286
Epoch: 180, Train Loss: 0.891, Val f1_micro: 0.288
Epoch: 200, Train Loss: 0.858, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.831, Val f1_micro: 0.291
Epoch: 240, Train Loss: 0.830, Val f1_micro: 0.294
Epoch: 260, Train Loss: 0.804, Val f1_micro: 0.289
Epoch: 280, Train Loss: 0.806, Val f1_micro: 0.294
Epoch: 300, Train Loss: 0.783, Val f1_micro: 0.292
Epoch: 320, Train Loss: 0.777, Val f1_micro: 0.297
Epoch: 340, Train Loss: 0.765, Val f1_micro: 0.296
Epoch: 360, Train Loss: 0.752, Val f1_micro: 0.297
Epoch: 380, Train Loss: 0.749, Val f1_micro: 0.299
Epoch: 400, Train Loss: 0.731, Val f1_micro: 0.300
Epoch: 420, Train Loss: 0.720, Val f1_micro: 0.301
Epoch: 440, Train Loss: 0.720, Val f1_micro: 0.301
Epoch: 460, Train Loss: 0.710, Val f1_micro: 0.303
Epoch: 480, Train Loss: 0.707, Val f1_micro: 0.301
Epoch: 500, Train Loss: 0.707, Val f1_micro: 0.302
f1-micro: 0.302, f1-macro: 0.297, f1-weighted: 0.301, , roc-auc: 0.687
##### RUN 2 #####
Epoch: 020, Train Loss: 1.565, Val f1_micro: 0.241
Epoch: 040, Train Loss: 1.313, Val f1_micro: 0.253
Epoch: 060, Train Loss: 1.187, Val f1_micro: 0.264
Epoch: 080, Train Loss: 1.090, Val f1_micro: 0.271
Epoch: 100, Train Loss: 1.037, Val f1_micro: 0.278
Epoch: 120, Train Loss: 1.000, Val f1_micro: 0.278
Epoch: 140, Train Loss: 0.954, Val f1_micro: 0.279
Epoch: 160, Train Loss: 0.923, Val f1_micro: 0.283
Epoch: 180, Train Loss: 0.886, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.863, Val f1_micro: 0.287
Epoch: 220, Train Loss: 0.827, Val f1_micro: 0.287
Epoch: 240, Train Loss: 0.822, Val f1_micro: 0.294
Epoch: 260, Train Loss: 0.815, Val f1_micro: 0.292
Epoch: 280, Train Loss: 0.786, Val f1_micro: 0.296
Epoch: 300, Train Loss: 0.784, Val f1_micro: 0.297
Epoch: 320, Train Loss: 0.773, Val f1_micro: 0.293
Epoch: 340, Train Loss: 0.748, Val f1_micro: 0.300
Epoch: 360, Train Loss: 0.762, Val f1_micro: 0.296
Epoch: 380, Train Loss: 0.740, Val f1_micro: 0.299
Epoch: 400, Train Loss: 0.734, Val f1_micro: 0.302
Epoch: 420, Train Loss: 0.718, Val f1_micro: 0.300
Epoch: 440, Train Loss: 0.718, Val f1_micro: 0.303
Epoch: 460, Train Loss: 0.712, Val f1_micro: 0.302
Epoch: 480, Train Loss: 0.690, Val f1_micro: 0.303
Epoch: 500, Train Loss: 0.703, Val f1_micro: 0.305
f1-micro: 0.305, f1-macro: 0.299, f1-weighted: 0.303, , roc-auc: 0.689
##### RUN 3 #####
Epoch: 020, Train Loss: 1.585, Val f1_micro: 0.240
Epoch: 040, Train Loss: 1.311, Val f1_micro: 0.255
Epoch: 060, Train Loss: 1.194, Val f1_micro: 0.262
Epoch: 080, Train Loss: 1.118, Val f1_micro: 0.273
Epoch: 100, Train Loss: 1.045, Val f1_micro: 0.275
Epoch: 120, Train Loss: 0.992, Val f1_micro: 0.278
Epoch: 140, Train Loss: 0.944, Val f1_micro: 0.281
Epoch: 160, Train Loss: 0.917, Val f1_micro: 0.285
Epoch: 180, Train Loss: 0.898, Val f1_micro: 0.284
Epoch: 200, Train Loss: 0.865, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.849, Val f1_micro: 0.289
Epoch: 240, Train Loss: 0.823, Val f1_micro: 0.295
Epoch: 260, Train Loss: 0.813, Val f1_micro: 0.294
Epoch: 280, Train Loss: 0.808, Val f1_micro: 0.296
Epoch: 300, Train Loss: 0.772, Val f1_micro: 0.296
Epoch: 320, Train Loss: 0.764, Val f1_micro: 0.295
Epoch: 340, Train Loss: 0.771, Val f1_micro: 0.300
Epoch: 360, Train Loss: 0.752, Val f1_micro: 0.301
Epoch: 380, Train Loss: 0.740, Val f1_micro: 0.300
Epoch: 400, Train Loss: 0.720, Val f1_micro: 0.299
Epoch: 420, Train Loss: 0.717, Val f1_micro: 0.303
Epoch: 440, Train Loss: 0.722, Val f1_micro: 0.300
Epoch: 460, Train Loss: 0.727, Val f1_micro: 0.301
Epoch: 480, Train Loss: 0.691, Val f1_micro: 0.303
Epoch: 500, Train Loss: 0.712, Val f1_micro: 0.306
f1-micro: 0.306, f1-macro: 0.300, f1-weighted: 0.303, , roc-auc: 0.688
##### RUN 4 #####
Epoch: 020, Train Loss: 1.580, Val f1_micro: 0.238
Epoch: 040, Train Loss: 1.315, Val f1_micro: 0.254
Epoch: 060, Train Loss: 1.193, Val f1_micro: 0.263
Epoch: 080, Train Loss: 1.088, Val f1_micro: 0.272
Epoch: 100, Train Loss: 1.052, Val f1_micro: 0.274
Epoch: 120, Train Loss: 0.996, Val f1_micro: 0.280
Epoch: 140, Train Loss: 0.948, Val f1_micro: 0.278
Epoch: 160, Train Loss: 0.922, Val f1_micro: 0.286
Epoch: 180, Train Loss: 0.892, Val f1_micro: 0.288
Epoch: 200, Train Loss: 0.880, Val f1_micro: 0.291
Epoch: 220, Train Loss: 0.851, Val f1_micro: 0.289
Epoch: 240, Train Loss: 0.835, Val f1_micro: 0.292
Epoch: 260, Train Loss: 0.802, Val f1_micro: 0.295
Epoch: 280, Train Loss: 0.799, Val f1_micro: 0.295
Epoch: 300, Train Loss: 0.786, Val f1_micro: 0.296
Epoch: 320, Train Loss: 0.784, Val f1_micro: 0.295
Epoch: 340, Train Loss: 0.748, Val f1_micro: 0.297
Epoch: 360, Train Loss: 0.757, Val f1_micro: 0.299
Epoch: 380, Train Loss: 0.732, Val f1_micro: 0.300
Epoch: 400, Train Loss: 0.729, Val f1_micro: 0.300
Epoch: 420, Train Loss: 0.726, Val f1_micro: 0.299
Epoch: 440, Train Loss: 0.718, Val f1_micro: 0.299
Epoch: 460, Train Loss: 0.729, Val f1_micro: 0.301
Epoch: 480, Train Loss: 0.714, Val f1_micro: 0.303
Epoch: 500, Train Loss: 0.702, Val f1_micro: 0.304
f1-micro: 0.304, f1-macro: 0.297, f1-weighted: 0.300, , roc-auc: 0.687
##### RUN 5 #####
Epoch: 020, Train Loss: 1.582, Val f1_micro: 0.240
Epoch: 040, Train Loss: 1.318, Val f1_micro: 0.250
Epoch: 060, Train Loss: 1.188, Val f1_micro: 0.262
Epoch: 080, Train Loss: 1.111, Val f1_micro: 0.274
Epoch: 100, Train Loss: 1.036, Val f1_micro: 0.277
Epoch: 120, Train Loss: 0.994, Val f1_micro: 0.281
Epoch: 140, Train Loss: 0.955, Val f1_micro: 0.284
Epoch: 160, Train Loss: 0.915, Val f1_micro: 0.286
Epoch: 180, Train Loss: 0.908, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.872, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.851, Val f1_micro: 0.287
Epoch: 240, Train Loss: 0.830, Val f1_micro: 0.294
Epoch: 260, Train Loss: 0.800, Val f1_micro: 0.297
Epoch: 280, Train Loss: 0.797, Val f1_micro: 0.292
Epoch: 300, Train Loss: 0.780, Val f1_micro: 0.296
Epoch: 320, Train Loss: 0.774, Val f1_micro: 0.297
Epoch: 340, Train Loss: 0.763, Val f1_micro: 0.300
Epoch: 360, Train Loss: 0.750, Val f1_micro: 0.301
Epoch: 380, Train Loss: 0.735, Val f1_micro: 0.301
Epoch: 400, Train Loss: 0.729, Val f1_micro: 0.302
Epoch: 420, Train Loss: 0.730, Val f1_micro: 0.304
Epoch: 440, Train Loss: 0.732, Val f1_micro: 0.302
Epoch: 460, Train Loss: 0.716, Val f1_micro: 0.305
Epoch: 480, Train Loss: 0.726, Val f1_micro: 0.303
Epoch: 500, Train Loss: 0.706, Val f1_micro: 0.306
f1-micro: 0.306, f1-macro: 0.300, f1-weighted: 0.304, , roc-auc: 0.687
########## Hyperparameters combination ##########
(1024, 0.3, 0.005, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.651, Val f1_micro: 0.234
Epoch: 040, Train Loss: 1.521, Val f1_micro: 0.238
Epoch: 060, Train Loss: 1.502, Val f1_micro: 0.240
Epoch: 080, Train Loss: 1.503, Val f1_micro: 0.237
Epoch: 100, Train Loss: 1.507, Val f1_micro: 0.237
Epoch: 120, Train Loss: 1.514, Val f1_micro: 0.233
Epoch: 140, Train Loss: 1.531, Val f1_micro: 0.234
Epoch: 160, Train Loss: 1.530, Val f1_micro: 0.232
Epoch: 180, Train Loss: 1.530, Val f1_micro: 0.234
Epoch: 200, Train Loss: 1.521, Val f1_micro: 0.232
Epoch: 220, Train Loss: 1.524, Val f1_micro: 0.235
Epoch: 240, Train Loss: 1.525, Val f1_micro: 0.236
Epoch: 260, Train Loss: 1.524, Val f1_micro: 0.233
Epoch: 280, Train Loss: 1.526, Val f1_micro: 0.235
Epoch: 300, Train Loss: 1.522, Val f1_micro: 0.231
Epoch: 320, Train Loss: 1.526, Val f1_micro: 0.229
Epoch: 340, Train Loss: 1.508, Val f1_micro: 0.232
Epoch: 360, Train Loss: 1.524, Val f1_micro: 0.236
Epoch: 380, Train Loss: 1.518, Val f1_micro: 0.235
Epoch: 400, Train Loss: 1.517, Val f1_micro: 0.230
Epoch: 420, Train Loss: 1.517, Val f1_micro: 0.234
Epoch: 440, Train Loss: 1.515, Val f1_micro: 0.234
Epoch: 460, Train Loss: 1.520, Val f1_micro: 0.234
Epoch: 480, Train Loss: 1.510, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.503, Val f1_micro: 0.232
f1-micro: 0.232, f1-macro: 0.209, f1-weighted: 0.206, , roc-auc: 0.654
##### RUN 2 #####
Epoch: 020, Train Loss: 1.656, Val f1_micro: 0.236
Epoch: 040, Train Loss: 1.518, Val f1_micro: 0.234
Epoch: 060, Train Loss: 1.502, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.497, Val f1_micro: 0.237
Epoch: 100, Train Loss: 1.507, Val f1_micro: 0.238
Epoch: 120, Train Loss: 1.517, Val f1_micro: 0.238
Epoch: 140, Train Loss: 1.513, Val f1_micro: 0.237
Epoch: 160, Train Loss: 1.517, Val f1_micro: 0.234
Epoch: 180, Train Loss: 1.517, Val f1_micro: 0.234
Epoch: 200, Train Loss: 1.527, Val f1_micro: 0.237
Epoch: 220, Train Loss: 1.526, Val f1_micro: 0.235
Epoch: 240, Train Loss: 1.527, Val f1_micro: 0.233
Epoch: 260, Train Loss: 1.532, Val f1_micro: 0.232
Epoch: 280, Train Loss: 1.522, Val f1_micro: 0.232
Epoch: 300, Train Loss: 1.521, Val f1_micro: 0.238
Epoch: 320, Train Loss: 1.515, Val f1_micro: 0.231
Epoch: 340, Train Loss: 1.519, Val f1_micro: 0.232
Epoch: 360, Train Loss: 1.520, Val f1_micro: 0.232
Epoch: 380, Train Loss: 1.522, Val f1_micro: 0.232
Epoch: 400, Train Loss: 1.516, Val f1_micro: 0.238
Epoch: 420, Train Loss: 1.511, Val f1_micro: 0.234
Epoch: 440, Train Loss: 1.514, Val f1_micro: 0.232
Epoch: 460, Train Loss: 1.509, Val f1_micro: 0.231
Epoch: 480, Train Loss: 1.520, Val f1_micro: 0.234
Epoch: 500, Train Loss: 1.520, Val f1_micro: 0.235
f1-micro: 0.235, f1-macro: 0.209, f1-weighted: 0.207, , roc-auc: 0.654
##### RUN 3 #####
Epoch: 020, Train Loss: 1.662, Val f1_micro: 0.237
Epoch: 040, Train Loss: 1.522, Val f1_micro: 0.236
Epoch: 060, Train Loss: 1.505, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.504, Val f1_micro: 0.237
Epoch: 100, Train Loss: 1.506, Val f1_micro: 0.233
Epoch: 120, Train Loss: 1.505, Val f1_micro: 0.232
Epoch: 140, Train Loss: 1.520, Val f1_micro: 0.232
Epoch: 160, Train Loss: 1.525, Val f1_micro: 0.234
Epoch: 180, Train Loss: 1.535, Val f1_micro: 0.229
Epoch: 200, Train Loss: 1.530, Val f1_micro: 0.234
Epoch: 220, Train Loss: 1.524, Val f1_micro: 0.232
Epoch: 240, Train Loss: 1.526, Val f1_micro: 0.234
Epoch: 260, Train Loss: 1.522, Val f1_micro: 0.229
Epoch: 280, Train Loss: 1.526, Val f1_micro: 0.234
Epoch: 300, Train Loss: 1.533, Val f1_micro: 0.233
Epoch: 320, Train Loss: 1.518, Val f1_micro: 0.231
Epoch: 340, Train Loss: 1.532, Val f1_micro: 0.230
Epoch: 360, Train Loss: 1.530, Val f1_micro: 0.231
Epoch: 380, Train Loss: 1.516, Val f1_micro: 0.234
Epoch: 400, Train Loss: 1.521, Val f1_micro: 0.233
Epoch: 420, Train Loss: 1.518, Val f1_micro: 0.235
Epoch: 440, Train Loss: 1.516, Val f1_micro: 0.234
Epoch: 460, Train Loss: 1.510, Val f1_micro: 0.235
Epoch: 480, Train Loss: 1.500, Val f1_micro: 0.234
Epoch: 500, Train Loss: 1.511, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.204, f1-weighted: 0.201, , roc-auc: 0.656
##### RUN 4 #####
Epoch: 020, Train Loss: 1.662, Val f1_micro: 0.233
Epoch: 040, Train Loss: 1.519, Val f1_micro: 0.236
Epoch: 060, Train Loss: 1.509, Val f1_micro: 0.241
Epoch: 080, Train Loss: 1.494, Val f1_micro: 0.234
Epoch: 100, Train Loss: 1.495, Val f1_micro: 0.237
Epoch: 120, Train Loss: 1.511, Val f1_micro: 0.235
Epoch: 140, Train Loss: 1.522, Val f1_micro: 0.234
Epoch: 160, Train Loss: 1.523, Val f1_micro: 0.229
Epoch: 180, Train Loss: 1.535, Val f1_micro: 0.230
Epoch: 200, Train Loss: 1.536, Val f1_micro: 0.229
Epoch: 220, Train Loss: 1.537, Val f1_micro: 0.231
Epoch: 240, Train Loss: 1.519, Val f1_micro: 0.227
Epoch: 260, Train Loss: 1.521, Val f1_micro: 0.234
Epoch: 280, Train Loss: 1.521, Val f1_micro: 0.233
Epoch: 300, Train Loss: 1.529, Val f1_micro: 0.236
Epoch: 320, Train Loss: 1.523, Val f1_micro: 0.234
Epoch: 340, Train Loss: 1.518, Val f1_micro: 0.234
Epoch: 360, Train Loss: 1.522, Val f1_micro: 0.236
Epoch: 380, Train Loss: 1.510, Val f1_micro: 0.226
Epoch: 400, Train Loss: 1.511, Val f1_micro: 0.233
Epoch: 420, Train Loss: 1.508, Val f1_micro: 0.234
Epoch: 440, Train Loss: 1.513, Val f1_micro: 0.236
Epoch: 460, Train Loss: 1.509, Val f1_micro: 0.234
Epoch: 480, Train Loss: 1.510, Val f1_micro: 0.235
Epoch: 500, Train Loss: 1.504, Val f1_micro: 0.234
f1-micro: 0.234, f1-macro: 0.206, f1-weighted: 0.203, , roc-auc: 0.654
##### RUN 5 #####
Epoch: 020, Train Loss: 1.660, Val f1_micro: 0.235
Epoch: 040, Train Loss: 1.530, Val f1_micro: 0.238
Epoch: 060, Train Loss: 1.491, Val f1_micro: 0.235
Epoch: 080, Train Loss: 1.503, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.512, Val f1_micro: 0.237
Epoch: 120, Train Loss: 1.509, Val f1_micro: 0.236
Epoch: 140, Train Loss: 1.508, Val f1_micro: 0.233
Epoch: 160, Train Loss: 1.524, Val f1_micro: 0.235
Epoch: 180, Train Loss: 1.517, Val f1_micro: 0.236
Epoch: 200, Train Loss: 1.522, Val f1_micro: 0.235
Epoch: 220, Train Loss: 1.536, Val f1_micro: 0.233
Epoch: 240, Train Loss: 1.522, Val f1_micro: 0.236
Epoch: 260, Train Loss: 1.520, Val f1_micro: 0.236
Epoch: 280, Train Loss: 1.527, Val f1_micro: 0.233
Epoch: 300, Train Loss: 1.522, Val f1_micro: 0.232
Epoch: 320, Train Loss: 1.517, Val f1_micro: 0.232
Epoch: 340, Train Loss: 1.522, Val f1_micro: 0.235
Epoch: 360, Train Loss: 1.514, Val f1_micro: 0.231
Epoch: 380, Train Loss: 1.513, Val f1_micro: 0.235
Epoch: 400, Train Loss: 1.502, Val f1_micro: 0.235
Epoch: 420, Train Loss: 1.511, Val f1_micro: 0.232
Epoch: 440, Train Loss: 1.508, Val f1_micro: 0.237
Epoch: 460, Train Loss: 1.511, Val f1_micro: 0.238
Epoch: 480, Train Loss: 1.508, Val f1_micro: 0.237
Epoch: 500, Train Loss: 1.507, Val f1_micro: 0.233
f1-micro: 0.233, f1-macro: 0.211, f1-weighted: 0.207, , roc-auc: 0.657
########## Hyperparameters combination ##########
(1024, 0.3, 0.01, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.490, Val f1_micro: 0.232
Epoch: 040, Train Loss: 1.150, Val f1_micro: 0.269
Epoch: 060, Train Loss: 0.965, Val f1_micro: 0.279
Epoch: 080, Train Loss: 0.819, Val f1_micro: 0.290
Epoch: 100, Train Loss: 0.686, Val f1_micro: 0.300
Epoch: 120, Train Loss: 0.615, Val f1_micro: 0.302
Epoch: 140, Train Loss: 0.532, Val f1_micro: 0.308
Epoch: 160, Train Loss: 0.466, Val f1_micro: 0.314
Epoch: 180, Train Loss: 0.421, Val f1_micro: 0.317
Epoch: 200, Train Loss: 0.361, Val f1_micro: 0.318
Epoch: 220, Train Loss: 0.342, Val f1_micro: 0.321
Epoch: 240, Train Loss: 0.321, Val f1_micro: 0.321
Epoch: 260, Train Loss: 0.304, Val f1_micro: 0.325
Epoch: 280, Train Loss: 0.272, Val f1_micro: 0.326
Epoch: 300, Train Loss: 0.257, Val f1_micro: 0.323
Epoch: 320, Train Loss: 0.254, Val f1_micro: 0.322
Epoch: 340, Train Loss: 0.234, Val f1_micro: 0.325
Epoch: 360, Train Loss: 0.226, Val f1_micro: 0.325
Epoch: 380, Train Loss: 0.226, Val f1_micro: 0.323
Epoch: 400, Train Loss: 0.201, Val f1_micro: 0.325
Epoch: 420, Train Loss: 0.191, Val f1_micro: 0.324
Epoch: 440, Train Loss: 0.201, Val f1_micro: 0.321
Epoch: 460, Train Loss: 0.175, Val f1_micro: 0.325
Epoch: 480, Train Loss: 0.165, Val f1_micro: 0.324
Epoch: 500, Train Loss: 0.161, Val f1_micro: 0.325
f1-micro: 0.325, f1-macro: 0.318, f1-weighted: 0.325, , roc-auc: 0.694
##### RUN 2 #####
Epoch: 020, Train Loss: 1.505, Val f1_micro: 0.236
Epoch: 040, Train Loss: 1.174, Val f1_micro: 0.267
Epoch: 060, Train Loss: 0.982, Val f1_micro: 0.283
Epoch: 080, Train Loss: 0.835, Val f1_micro: 0.289
Epoch: 100, Train Loss: 0.739, Val f1_micro: 0.299
Epoch: 120, Train Loss: 0.635, Val f1_micro: 0.302
Epoch: 140, Train Loss: 0.541, Val f1_micro: 0.312
Epoch: 160, Train Loss: 0.491, Val f1_micro: 0.313
Epoch: 180, Train Loss: 0.423, Val f1_micro: 0.318
Epoch: 200, Train Loss: 0.384, Val f1_micro: 0.323
Epoch: 220, Train Loss: 0.363, Val f1_micro: 0.323
Epoch: 240, Train Loss: 0.332, Val f1_micro: 0.322
Epoch: 260, Train Loss: 0.303, Val f1_micro: 0.323
Epoch: 280, Train Loss: 0.275, Val f1_micro: 0.321
Epoch: 300, Train Loss: 0.268, Val f1_micro: 0.324
Epoch: 320, Train Loss: 0.247, Val f1_micro: 0.323
Epoch: 340, Train Loss: 0.236, Val f1_micro: 0.325
Epoch: 360, Train Loss: 0.222, Val f1_micro: 0.320
Epoch: 380, Train Loss: 0.215, Val f1_micro: 0.327
Epoch: 400, Train Loss: 0.205, Val f1_micro: 0.325
Epoch: 420, Train Loss: 0.204, Val f1_micro: 0.326
Epoch: 440, Train Loss: 0.196, Val f1_micro: 0.323
Epoch: 460, Train Loss: 0.183, Val f1_micro: 0.325
Epoch: 480, Train Loss: 0.178, Val f1_micro: 0.323
Epoch: 500, Train Loss: 0.184, Val f1_micro: 0.322
f1-micro: 0.322, f1-macro: 0.316, f1-weighted: 0.322, , roc-auc: 0.697
##### RUN 3 #####
Epoch: 020, Train Loss: 1.498, Val f1_micro: 0.243
Epoch: 040, Train Loss: 1.175, Val f1_micro: 0.267
Epoch: 060, Train Loss: 0.956, Val f1_micro: 0.282
Epoch: 080, Train Loss: 0.824, Val f1_micro: 0.289
Epoch: 100, Train Loss: 0.726, Val f1_micro: 0.298
Epoch: 120, Train Loss: 0.617, Val f1_micro: 0.305
Epoch: 140, Train Loss: 0.562, Val f1_micro: 0.311
Epoch: 160, Train Loss: 0.488, Val f1_micro: 0.317
Epoch: 180, Train Loss: 0.444, Val f1_micro: 0.317
Epoch: 200, Train Loss: 0.400, Val f1_micro: 0.320
Epoch: 220, Train Loss: 0.354, Val f1_micro: 0.323
Epoch: 240, Train Loss: 0.318, Val f1_micro: 0.324
Epoch: 260, Train Loss: 0.304, Val f1_micro: 0.324
Epoch: 280, Train Loss: 0.289, Val f1_micro: 0.325
Epoch: 300, Train Loss: 0.267, Val f1_micro: 0.327
Epoch: 320, Train Loss: 0.254, Val f1_micro: 0.325
Epoch: 340, Train Loss: 0.258, Val f1_micro: 0.327
Epoch: 360, Train Loss: 0.233, Val f1_micro: 0.326
Epoch: 380, Train Loss: 0.210, Val f1_micro: 0.326
Epoch: 400, Train Loss: 0.201, Val f1_micro: 0.326
Epoch: 420, Train Loss: 0.208, Val f1_micro: 0.325
Epoch: 440, Train Loss: 0.203, Val f1_micro: 0.326
Epoch: 460, Train Loss: 0.199, Val f1_micro: 0.326
Epoch: 480, Train Loss: 0.189, Val f1_micro: 0.325
Epoch: 500, Train Loss: 0.175, Val f1_micro: 0.328
f1-micro: 0.328, f1-macro: 0.322, f1-weighted: 0.328, , roc-auc: 0.697
##### RUN 4 #####
Epoch: 020, Train Loss: 1.499, Val f1_micro: 0.240
Epoch: 040, Train Loss: 1.169, Val f1_micro: 0.270
Epoch: 060, Train Loss: 0.957, Val f1_micro: 0.281
Epoch: 080, Train Loss: 0.823, Val f1_micro: 0.287
Epoch: 100, Train Loss: 0.712, Val f1_micro: 0.298
Epoch: 120, Train Loss: 0.632, Val f1_micro: 0.305
Epoch: 140, Train Loss: 0.559, Val f1_micro: 0.309
Epoch: 160, Train Loss: 0.503, Val f1_micro: 0.314
Epoch: 180, Train Loss: 0.428, Val f1_micro: 0.319
Epoch: 200, Train Loss: 0.390, Val f1_micro: 0.321
Epoch: 220, Train Loss: 0.353, Val f1_micro: 0.323
Epoch: 240, Train Loss: 0.341, Val f1_micro: 0.325
Epoch: 260, Train Loss: 0.314, Val f1_micro: 0.327
Epoch: 280, Train Loss: 0.293, Val f1_micro: 0.326
Epoch: 300, Train Loss: 0.268, Val f1_micro: 0.325
Epoch: 320, Train Loss: 0.253, Val f1_micro: 0.326
Epoch: 340, Train Loss: 0.226, Val f1_micro: 0.326
Epoch: 360, Train Loss: 0.229, Val f1_micro: 0.327
Epoch: 380, Train Loss: 0.219, Val f1_micro: 0.326
Epoch: 400, Train Loss: 0.218, Val f1_micro: 0.322
Epoch: 420, Train Loss: 0.194, Val f1_micro: 0.326
Epoch: 440, Train Loss: 0.187, Val f1_micro: 0.328
Epoch: 460, Train Loss: 0.179, Val f1_micro: 0.322
Epoch: 480, Train Loss: 0.189, Val f1_micro: 0.327
Epoch: 500, Train Loss: 0.170, Val f1_micro: 0.323
f1-micro: 0.323, f1-macro: 0.317, f1-weighted: 0.323, , roc-auc: 0.696
##### RUN 5 #####
Epoch: 020, Train Loss: 1.491, Val f1_micro: 0.240
Epoch: 040, Train Loss: 1.150, Val f1_micro: 0.268
Epoch: 060, Train Loss: 0.953, Val f1_micro: 0.280
Epoch: 080, Train Loss: 0.808, Val f1_micro: 0.290
Epoch: 100, Train Loss: 0.699, Val f1_micro: 0.301
Epoch: 120, Train Loss: 0.616, Val f1_micro: 0.305
Epoch: 140, Train Loss: 0.526, Val f1_micro: 0.306
Epoch: 160, Train Loss: 0.469, Val f1_micro: 0.313
Epoch: 180, Train Loss: 0.416, Val f1_micro: 0.317
Epoch: 200, Train Loss: 0.400, Val f1_micro: 0.321
Epoch: 220, Train Loss: 0.347, Val f1_micro: 0.321
Epoch: 240, Train Loss: 0.296, Val f1_micro: 0.323
Epoch: 260, Train Loss: 0.303, Val f1_micro: 0.323
Epoch: 280, Train Loss: 0.290, Val f1_micro: 0.323
Epoch: 300, Train Loss: 0.277, Val f1_micro: 0.322
Epoch: 320, Train Loss: 0.260, Val f1_micro: 0.324
Epoch: 340, Train Loss: 0.248, Val f1_micro: 0.325
Epoch: 360, Train Loss: 0.225, Val f1_micro: 0.322
Epoch: 380, Train Loss: 0.219, Val f1_micro: 0.325
Epoch: 400, Train Loss: 0.198, Val f1_micro: 0.324
Epoch: 420, Train Loss: 0.199, Val f1_micro: 0.324
Epoch: 440, Train Loss: 0.183, Val f1_micro: 0.321
Epoch: 460, Train Loss: 0.181, Val f1_micro: 0.321
Epoch: 480, Train Loss: 0.179, Val f1_micro: 0.320
Epoch: 500, Train Loss: 0.170, Val f1_micro: 0.322
f1-micro: 0.322, f1-macro: 0.316, f1-weighted: 0.322, , roc-auc: 0.697
########## Hyperparameters combination ##########
(1024, 0.3, 0.01, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.499, Val f1_micro: 0.233
Epoch: 040, Train Loss: 1.192, Val f1_micro: 0.262
Epoch: 060, Train Loss: 1.043, Val f1_micro: 0.273
Epoch: 080, Train Loss: 0.947, Val f1_micro: 0.280
Epoch: 100, Train Loss: 0.846, Val f1_micro: 0.286
Epoch: 120, Train Loss: 0.773, Val f1_micro: 0.290
Epoch: 140, Train Loss: 0.741, Val f1_micro: 0.296
Epoch: 160, Train Loss: 0.692, Val f1_micro: 0.295
Epoch: 180, Train Loss: 0.642, Val f1_micro: 0.304
Epoch: 200, Train Loss: 0.627, Val f1_micro: 0.307
Epoch: 220, Train Loss: 0.606, Val f1_micro: 0.310
Epoch: 240, Train Loss: 0.580, Val f1_micro: 0.312
Epoch: 260, Train Loss: 0.547, Val f1_micro: 0.308
Epoch: 280, Train Loss: 0.536, Val f1_micro: 0.312
Epoch: 300, Train Loss: 0.517, Val f1_micro: 0.313
Epoch: 320, Train Loss: 0.512, Val f1_micro: 0.314
Epoch: 340, Train Loss: 0.483, Val f1_micro: 0.315
Epoch: 360, Train Loss: 0.476, Val f1_micro: 0.316
Epoch: 380, Train Loss: 0.471, Val f1_micro: 0.317
Epoch: 400, Train Loss: 0.463, Val f1_micro: 0.316
Epoch: 420, Train Loss: 0.459, Val f1_micro: 0.316
Epoch: 440, Train Loss: 0.425, Val f1_micro: 0.312
Epoch: 460, Train Loss: 0.439, Val f1_micro: 0.318
Epoch: 480, Train Loss: 0.434, Val f1_micro: 0.321
Epoch: 500, Train Loss: 0.437, Val f1_micro: 0.319
f1-micro: 0.319, f1-macro: 0.314, f1-weighted: 0.320, , roc-auc: 0.695
##### RUN 2 #####
Epoch: 020, Train Loss: 1.496, Val f1_micro: 0.231
Epoch: 040, Train Loss: 1.206, Val f1_micro: 0.264
Epoch: 060, Train Loss: 1.051, Val f1_micro: 0.275
Epoch: 080, Train Loss: 0.940, Val f1_micro: 0.281
Epoch: 100, Train Loss: 0.869, Val f1_micro: 0.286
Epoch: 120, Train Loss: 0.813, Val f1_micro: 0.288
Epoch: 140, Train Loss: 0.750, Val f1_micro: 0.296
Epoch: 160, Train Loss: 0.709, Val f1_micro: 0.296
Epoch: 180, Train Loss: 0.680, Val f1_micro: 0.298
Epoch: 200, Train Loss: 0.649, Val f1_micro: 0.303
Epoch: 220, Train Loss: 0.606, Val f1_micro: 0.305
Epoch: 240, Train Loss: 0.576, Val f1_micro: 0.314
Epoch: 260, Train Loss: 0.560, Val f1_micro: 0.309
Epoch: 280, Train Loss: 0.545, Val f1_micro: 0.313
Epoch: 300, Train Loss: 0.531, Val f1_micro: 0.309
Epoch: 320, Train Loss: 0.529, Val f1_micro: 0.314
Epoch: 340, Train Loss: 0.500, Val f1_micro: 0.316
Epoch: 360, Train Loss: 0.502, Val f1_micro: 0.309
Epoch: 380, Train Loss: 0.489, Val f1_micro: 0.314
Epoch: 400, Train Loss: 0.464, Val f1_micro: 0.318
Epoch: 420, Train Loss: 0.464, Val f1_micro: 0.316
Epoch: 440, Train Loss: 0.457, Val f1_micro: 0.316
Epoch: 460, Train Loss: 0.449, Val f1_micro: 0.319
Epoch: 480, Train Loss: 0.429, Val f1_micro: 0.316
Epoch: 500, Train Loss: 0.445, Val f1_micro: 0.319
f1-micro: 0.319, f1-macro: 0.312, f1-weighted: 0.319, , roc-auc: 0.691
##### RUN 3 #####
Epoch: 020, Train Loss: 1.494, Val f1_micro: 0.234
Epoch: 040, Train Loss: 1.202, Val f1_micro: 0.262
Epoch: 060, Train Loss: 1.056, Val f1_micro: 0.273
Epoch: 080, Train Loss: 0.926, Val f1_micro: 0.283
Epoch: 100, Train Loss: 0.854, Val f1_micro: 0.289
Epoch: 120, Train Loss: 0.801, Val f1_micro: 0.291
Epoch: 140, Train Loss: 0.737, Val f1_micro: 0.289
Epoch: 160, Train Loss: 0.707, Val f1_micro: 0.300
Epoch: 180, Train Loss: 0.673, Val f1_micro: 0.297
Epoch: 200, Train Loss: 0.619, Val f1_micro: 0.302
Epoch: 220, Train Loss: 0.607, Val f1_micro: 0.309
Epoch: 240, Train Loss: 0.598, Val f1_micro: 0.307
Epoch: 260, Train Loss: 0.571, Val f1_micro: 0.309
Epoch: 280, Train Loss: 0.549, Val f1_micro: 0.309
Epoch: 300, Train Loss: 0.533, Val f1_micro: 0.311
Epoch: 320, Train Loss: 0.507, Val f1_micro: 0.310
Epoch: 340, Train Loss: 0.500, Val f1_micro: 0.313
Epoch: 360, Train Loss: 0.476, Val f1_micro: 0.313
Epoch: 380, Train Loss: 0.474, Val f1_micro: 0.313
Epoch: 400, Train Loss: 0.458, Val f1_micro: 0.316
Epoch: 420, Train Loss: 0.452, Val f1_micro: 0.316
Epoch: 440, Train Loss: 0.444, Val f1_micro: 0.319
Epoch: 460, Train Loss: 0.446, Val f1_micro: 0.318
Epoch: 480, Train Loss: 0.447, Val f1_micro: 0.316
Epoch: 500, Train Loss: 0.444, Val f1_micro: 0.317
f1-micro: 0.317, f1-macro: 0.312, f1-weighted: 0.318, , roc-auc: 0.693
##### RUN 4 #####
Epoch: 020, Train Loss: 1.501, Val f1_micro: 0.231
Epoch: 040, Train Loss: 1.187, Val f1_micro: 0.266
Epoch: 060, Train Loss: 1.057, Val f1_micro: 0.276
Epoch: 080, Train Loss: 0.945, Val f1_micro: 0.285
Epoch: 100, Train Loss: 0.853, Val f1_micro: 0.289
Epoch: 120, Train Loss: 0.805, Val f1_micro: 0.293
Epoch: 140, Train Loss: 0.754, Val f1_micro: 0.295
Epoch: 160, Train Loss: 0.702, Val f1_micro: 0.298
Epoch: 180, Train Loss: 0.657, Val f1_micro: 0.304
Epoch: 200, Train Loss: 0.636, Val f1_micro: 0.303
Epoch: 220, Train Loss: 0.593, Val f1_micro: 0.305
Epoch: 240, Train Loss: 0.589, Val f1_micro: 0.311
Epoch: 260, Train Loss: 0.560, Val f1_micro: 0.309
Epoch: 280, Train Loss: 0.537, Val f1_micro: 0.313
Epoch: 300, Train Loss: 0.526, Val f1_micro: 0.314
Epoch: 320, Train Loss: 0.512, Val f1_micro: 0.313
Epoch: 340, Train Loss: 0.504, Val f1_micro: 0.313
Epoch: 360, Train Loss: 0.466, Val f1_micro: 0.315
Epoch: 380, Train Loss: 0.487, Val f1_micro: 0.313
Epoch: 400, Train Loss: 0.468, Val f1_micro: 0.317
Epoch: 420, Train Loss: 0.461, Val f1_micro: 0.319
Epoch: 440, Train Loss: 0.444, Val f1_micro: 0.318
Epoch: 460, Train Loss: 0.421, Val f1_micro: 0.317
Epoch: 480, Train Loss: 0.451, Val f1_micro: 0.321
Epoch: 500, Train Loss: 0.428, Val f1_micro: 0.319
f1-micro: 0.319, f1-macro: 0.312, f1-weighted: 0.319, , roc-auc: 0.693
##### RUN 5 #####
Epoch: 020, Train Loss: 1.516, Val f1_micro: 0.234
Epoch: 040, Train Loss: 1.202, Val f1_micro: 0.259
Epoch: 060, Train Loss: 1.060, Val f1_micro: 0.271
Epoch: 080, Train Loss: 0.950, Val f1_micro: 0.280
Epoch: 100, Train Loss: 0.864, Val f1_micro: 0.284
Epoch: 120, Train Loss: 0.809, Val f1_micro: 0.291
Epoch: 140, Train Loss: 0.741, Val f1_micro: 0.293
Epoch: 160, Train Loss: 0.697, Val f1_micro: 0.295
Epoch: 180, Train Loss: 0.672, Val f1_micro: 0.298
Epoch: 200, Train Loss: 0.625, Val f1_micro: 0.301
Epoch: 220, Train Loss: 0.608, Val f1_micro: 0.307
Epoch: 240, Train Loss: 0.594, Val f1_micro: 0.305
Epoch: 260, Train Loss: 0.568, Val f1_micro: 0.312
Epoch: 280, Train Loss: 0.549, Val f1_micro: 0.311
Epoch: 300, Train Loss: 0.514, Val f1_micro: 0.308
Epoch: 320, Train Loss: 0.509, Val f1_micro: 0.312
Epoch: 340, Train Loss: 0.487, Val f1_micro: 0.313
Epoch: 360, Train Loss: 0.498, Val f1_micro: 0.316
Epoch: 380, Train Loss: 0.478, Val f1_micro: 0.317
Epoch: 400, Train Loss: 0.473, Val f1_micro: 0.317
Epoch: 420, Train Loss: 0.471, Val f1_micro: 0.316
Epoch: 440, Train Loss: 0.464, Val f1_micro: 0.312
Epoch: 460, Train Loss: 0.446, Val f1_micro: 0.318
Epoch: 480, Train Loss: 0.431, Val f1_micro: 0.317
Epoch: 500, Train Loss: 0.427, Val f1_micro: 0.315
f1-micro: 0.315, f1-macro: 0.310, f1-weighted: 0.316, , roc-auc: 0.692
########## Hyperparameters combination ##########
(1024, 0.3, 0.01, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.528, Val f1_micro: 0.240
Epoch: 040, Train Loss: 1.259, Val f1_micro: 0.266
Epoch: 060, Train Loss: 1.132, Val f1_micro: 0.273
Epoch: 080, Train Loss: 1.063, Val f1_micro: 0.277
Epoch: 100, Train Loss: 1.006, Val f1_micro: 0.279
Epoch: 120, Train Loss: 0.943, Val f1_micro: 0.286
Epoch: 140, Train Loss: 0.903, Val f1_micro: 0.288
Epoch: 160, Train Loss: 0.867, Val f1_micro: 0.287
Epoch: 180, Train Loss: 0.846, Val f1_micro: 0.291
Epoch: 200, Train Loss: 0.835, Val f1_micro: 0.293
Epoch: 220, Train Loss: 0.801, Val f1_micro: 0.295
Epoch: 240, Train Loss: 0.784, Val f1_micro: 0.301
Epoch: 260, Train Loss: 0.778, Val f1_micro: 0.304
Epoch: 280, Train Loss: 0.770, Val f1_micro: 0.303
Epoch: 300, Train Loss: 0.760, Val f1_micro: 0.302
Epoch: 320, Train Loss: 0.730, Val f1_micro: 0.302
Epoch: 340, Train Loss: 0.729, Val f1_micro: 0.300
Epoch: 360, Train Loss: 0.717, Val f1_micro: 0.302
Epoch: 380, Train Loss: 0.709, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.699, Val f1_micro: 0.305
Epoch: 420, Train Loss: 0.687, Val f1_micro: 0.304
Epoch: 440, Train Loss: 0.695, Val f1_micro: 0.304
Epoch: 460, Train Loss: 0.682, Val f1_micro: 0.306
Epoch: 480, Train Loss: 0.694, Val f1_micro: 0.305
Epoch: 500, Train Loss: 0.675, Val f1_micro: 0.309
f1-micro: 0.309, f1-macro: 0.301, f1-weighted: 0.305, , roc-auc: 0.688
##### RUN 2 #####
Epoch: 020, Train Loss: 1.531, Val f1_micro: 0.240
Epoch: 040, Train Loss: 1.280, Val f1_micro: 0.262
Epoch: 060, Train Loss: 1.153, Val f1_micro: 0.269
Epoch: 080, Train Loss: 1.053, Val f1_micro: 0.279
Epoch: 100, Train Loss: 1.002, Val f1_micro: 0.282
Epoch: 120, Train Loss: 0.955, Val f1_micro: 0.286
Epoch: 140, Train Loss: 0.916, Val f1_micro: 0.287
Epoch: 160, Train Loss: 0.877, Val f1_micro: 0.294
Epoch: 180, Train Loss: 0.851, Val f1_micro: 0.295
Epoch: 200, Train Loss: 0.827, Val f1_micro: 0.297
Epoch: 220, Train Loss: 0.806, Val f1_micro: 0.296
Epoch: 240, Train Loss: 0.773, Val f1_micro: 0.297
Epoch: 260, Train Loss: 0.779, Val f1_micro: 0.297
Epoch: 280, Train Loss: 0.757, Val f1_micro: 0.294
Epoch: 300, Train Loss: 0.765, Val f1_micro: 0.302
Epoch: 320, Train Loss: 0.728, Val f1_micro: 0.302
Epoch: 340, Train Loss: 0.707, Val f1_micro: 0.301
Epoch: 360, Train Loss: 0.714, Val f1_micro: 0.308
Epoch: 380, Train Loss: 0.711, Val f1_micro: 0.302
Epoch: 400, Train Loss: 0.703, Val f1_micro: 0.303
Epoch: 420, Train Loss: 0.701, Val f1_micro: 0.307
Epoch: 440, Train Loss: 0.688, Val f1_micro: 0.306
Epoch: 460, Train Loss: 0.692, Val f1_micro: 0.305
Epoch: 480, Train Loss: 0.687, Val f1_micro: 0.306
Epoch: 500, Train Loss: 0.681, Val f1_micro: 0.308
f1-micro: 0.308, f1-macro: 0.298, f1-weighted: 0.303, , roc-auc: 0.690
##### RUN 3 #####
Epoch: 020, Train Loss: 1.521, Val f1_micro: 0.238
Epoch: 040, Train Loss: 1.269, Val f1_micro: 0.264
Epoch: 060, Train Loss: 1.142, Val f1_micro: 0.272
Epoch: 080, Train Loss: 1.075, Val f1_micro: 0.276
Epoch: 100, Train Loss: 0.994, Val f1_micro: 0.283
Epoch: 120, Train Loss: 0.945, Val f1_micro: 0.283
Epoch: 140, Train Loss: 0.899, Val f1_micro: 0.282
Epoch: 160, Train Loss: 0.870, Val f1_micro: 0.292
Epoch: 180, Train Loss: 0.850, Val f1_micro: 0.295
Epoch: 200, Train Loss: 0.818, Val f1_micro: 0.297
Epoch: 220, Train Loss: 0.804, Val f1_micro: 0.297
Epoch: 240, Train Loss: 0.789, Val f1_micro: 0.296
Epoch: 260, Train Loss: 0.774, Val f1_micro: 0.299
Epoch: 280, Train Loss: 0.762, Val f1_micro: 0.301
Epoch: 300, Train Loss: 0.744, Val f1_micro: 0.304
Epoch: 320, Train Loss: 0.747, Val f1_micro: 0.306
Epoch: 340, Train Loss: 0.719, Val f1_micro: 0.301
Epoch: 360, Train Loss: 0.724, Val f1_micro: 0.306
Epoch: 380, Train Loss: 0.705, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.711, Val f1_micro: 0.305
Epoch: 420, Train Loss: 0.695, Val f1_micro: 0.305
Epoch: 440, Train Loss: 0.702, Val f1_micro: 0.311
Epoch: 460, Train Loss: 0.688, Val f1_micro: 0.313
Epoch: 480, Train Loss: 0.691, Val f1_micro: 0.306
Epoch: 500, Train Loss: 0.670, Val f1_micro: 0.312
f1-micro: 0.312, f1-macro: 0.303, f1-weighted: 0.308, , roc-auc: 0.691
##### RUN 4 #####
Epoch: 020, Train Loss: 1.537, Val f1_micro: 0.237
Epoch: 040, Train Loss: 1.254, Val f1_micro: 0.265
Epoch: 060, Train Loss: 1.140, Val f1_micro: 0.271
Epoch: 080, Train Loss: 1.046, Val f1_micro: 0.276
Epoch: 100, Train Loss: 0.986, Val f1_micro: 0.281
Epoch: 120, Train Loss: 0.940, Val f1_micro: 0.284
Epoch: 140, Train Loss: 0.903, Val f1_micro: 0.291
Epoch: 160, Train Loss: 0.885, Val f1_micro: 0.291
Epoch: 180, Train Loss: 0.851, Val f1_micro: 0.293
Epoch: 200, Train Loss: 0.809, Val f1_micro: 0.297
Epoch: 220, Train Loss: 0.804, Val f1_micro: 0.294
Epoch: 240, Train Loss: 0.794, Val f1_micro: 0.300
Epoch: 260, Train Loss: 0.780, Val f1_micro: 0.299
Epoch: 280, Train Loss: 0.762, Val f1_micro: 0.300
Epoch: 300, Train Loss: 0.740, Val f1_micro: 0.303
Epoch: 320, Train Loss: 0.749, Val f1_micro: 0.301
Epoch: 340, Train Loss: 0.734, Val f1_micro: 0.302
Epoch: 360, Train Loss: 0.712, Val f1_micro: 0.305
Epoch: 380, Train Loss: 0.723, Val f1_micro: 0.305
Epoch: 400, Train Loss: 0.699, Val f1_micro: 0.307
Epoch: 420, Train Loss: 0.692, Val f1_micro: 0.306
Epoch: 440, Train Loss: 0.686, Val f1_micro: 0.306
Epoch: 460, Train Loss: 0.697, Val f1_micro: 0.309
Epoch: 480, Train Loss: 0.712, Val f1_micro: 0.306
Epoch: 500, Train Loss: 0.668, Val f1_micro: 0.308
f1-micro: 0.308, f1-macro: 0.301, f1-weighted: 0.305, , roc-auc: 0.690
##### RUN 5 #####
Epoch: 020, Train Loss: 1.523, Val f1_micro: 0.239
Epoch: 040, Train Loss: 1.259, Val f1_micro: 0.266
Epoch: 060, Train Loss: 1.151, Val f1_micro: 0.272
Epoch: 080, Train Loss: 1.052, Val f1_micro: 0.279
Epoch: 100, Train Loss: 0.993, Val f1_micro: 0.281
Epoch: 120, Train Loss: 0.943, Val f1_micro: 0.285
Epoch: 140, Train Loss: 0.906, Val f1_micro: 0.291
Epoch: 160, Train Loss: 0.868, Val f1_micro: 0.291
Epoch: 180, Train Loss: 0.844, Val f1_micro: 0.297
Epoch: 200, Train Loss: 0.812, Val f1_micro: 0.296
Epoch: 220, Train Loss: 0.804, Val f1_micro: 0.301
Epoch: 240, Train Loss: 0.802, Val f1_micro: 0.297
Epoch: 260, Train Loss: 0.771, Val f1_micro: 0.301
Epoch: 280, Train Loss: 0.764, Val f1_micro: 0.296
Epoch: 300, Train Loss: 0.748, Val f1_micro: 0.304
Epoch: 320, Train Loss: 0.736, Val f1_micro: 0.303
Epoch: 340, Train Loss: 0.731, Val f1_micro: 0.306
Epoch: 360, Train Loss: 0.721, Val f1_micro: 0.306
Epoch: 380, Train Loss: 0.721, Val f1_micro: 0.304
Epoch: 400, Train Loss: 0.703, Val f1_micro: 0.300
Epoch: 420, Train Loss: 0.705, Val f1_micro: 0.306
Epoch: 440, Train Loss: 0.689, Val f1_micro: 0.302
Epoch: 460, Train Loss: 0.707, Val f1_micro: 0.309
Epoch: 480, Train Loss: 0.686, Val f1_micro: 0.310
Epoch: 500, Train Loss: 0.674, Val f1_micro: 0.310
f1-micro: 0.310, f1-macro: 0.301, f1-weighted: 0.306, , roc-auc: 0.690
########## Hyperparameters combination ##########
(1024, 0.3, 0.01, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.653, Val f1_micro: 0.222
Epoch: 040, Train Loss: 1.543, Val f1_micro: 0.240
Epoch: 060, Train Loss: 1.524, Val f1_micro: 0.234
Epoch: 080, Train Loss: 1.528, Val f1_micro: 0.234
Epoch: 100, Train Loss: 1.527, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.538, Val f1_micro: 0.232
Epoch: 140, Train Loss: 1.529, Val f1_micro: 0.233
Epoch: 160, Train Loss: 1.538, Val f1_micro: 0.235
Epoch: 180, Train Loss: 1.542, Val f1_micro: 0.233
Epoch: 200, Train Loss: 1.529, Val f1_micro: 0.231
Epoch: 220, Train Loss: 1.524, Val f1_micro: 0.232
Epoch: 240, Train Loss: 1.528, Val f1_micro: 0.231
Epoch: 260, Train Loss: 1.521, Val f1_micro: 0.231
Epoch: 280, Train Loss: 1.525, Val f1_micro: 0.230
Epoch: 300, Train Loss: 1.504, Val f1_micro: 0.235
Epoch: 320, Train Loss: 1.510, Val f1_micro: 0.234
Epoch: 340, Train Loss: 1.513, Val f1_micro: 0.233
Epoch: 360, Train Loss: 1.525, Val f1_micro: 0.234
Epoch: 380, Train Loss: 1.513, Val f1_micro: 0.235
Epoch: 400, Train Loss: 1.517, Val f1_micro: 0.234
Epoch: 420, Train Loss: 1.507, Val f1_micro: 0.229
Epoch: 440, Train Loss: 1.512, Val f1_micro: 0.234
Epoch: 460, Train Loss: 1.507, Val f1_micro: 0.234
Epoch: 480, Train Loss: 1.513, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.504, Val f1_micro: 0.231
f1-micro: 0.231, f1-macro: 0.208, f1-weighted: 0.206, , roc-auc: 0.655
##### RUN 2 #####
Epoch: 020, Train Loss: 1.659, Val f1_micro: 0.227
Epoch: 040, Train Loss: 1.548, Val f1_micro: 0.238
Epoch: 060, Train Loss: 1.540, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.520, Val f1_micro: 0.233
Epoch: 100, Train Loss: 1.533, Val f1_micro: 0.231
Epoch: 120, Train Loss: 1.536, Val f1_micro: 0.232
Epoch: 140, Train Loss: 1.540, Val f1_micro: 0.235
Epoch: 160, Train Loss: 1.528, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.540, Val f1_micro: 0.231
Epoch: 200, Train Loss: 1.536, Val f1_micro: 0.231
Epoch: 220, Train Loss: 1.540, Val f1_micro: 0.230
Epoch: 240, Train Loss: 1.529, Val f1_micro: 0.233
Epoch: 260, Train Loss: 1.519, Val f1_micro: 0.234
Epoch: 280, Train Loss: 1.520, Val f1_micro: 0.233
Epoch: 300, Train Loss: 1.520, Val f1_micro: 0.237
Epoch: 320, Train Loss: 1.512, Val f1_micro: 0.236
Epoch: 340, Train Loss: 1.516, Val f1_micro: 0.234
Epoch: 360, Train Loss: 1.514, Val f1_micro: 0.233
Epoch: 380, Train Loss: 1.519, Val f1_micro: 0.239
Epoch: 400, Train Loss: 1.506, Val f1_micro: 0.237
Epoch: 420, Train Loss: 1.511, Val f1_micro: 0.234
Epoch: 440, Train Loss: 1.502, Val f1_micro: 0.236
Epoch: 460, Train Loss: 1.520, Val f1_micro: 0.232
Epoch: 480, Train Loss: 1.507, Val f1_micro: 0.235
Epoch: 500, Train Loss: 1.509, Val f1_micro: 0.235
f1-micro: 0.235, f1-macro: 0.213, f1-weighted: 0.209, , roc-auc: 0.654
##### RUN 3 #####
Epoch: 020, Train Loss: 1.642, Val f1_micro: 0.232
Epoch: 040, Train Loss: 1.545, Val f1_micro: 0.239
Epoch: 060, Train Loss: 1.522, Val f1_micro: 0.237
Epoch: 080, Train Loss: 1.524, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.533, Val f1_micro: 0.231
Epoch: 120, Train Loss: 1.543, Val f1_micro: 0.236
Epoch: 140, Train Loss: 1.523, Val f1_micro: 0.237
Epoch: 160, Train Loss: 1.537, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.535, Val f1_micro: 0.229
Epoch: 200, Train Loss: 1.532, Val f1_micro: 0.235
Epoch: 220, Train Loss: 1.517, Val f1_micro: 0.236
Epoch: 240, Train Loss: 1.516, Val f1_micro: 0.232
Epoch: 260, Train Loss: 1.527, Val f1_micro: 0.235
Epoch: 280, Train Loss: 1.523, Val f1_micro: 0.236
Epoch: 300, Train Loss: 1.514, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.525, Val f1_micro: 0.230
Epoch: 340, Train Loss: 1.519, Val f1_micro: 0.233
Epoch: 360, Train Loss: 1.516, Val f1_micro: 0.234
Epoch: 380, Train Loss: 1.512, Val f1_micro: 0.230
Epoch: 400, Train Loss: 1.513, Val f1_micro: 0.234
Epoch: 420, Train Loss: 1.519, Val f1_micro: 0.236
Epoch: 440, Train Loss: 1.517, Val f1_micro: 0.234
Epoch: 460, Train Loss: 1.513, Val f1_micro: 0.234
Epoch: 480, Train Loss: 1.514, Val f1_micro: 0.230
Epoch: 500, Train Loss: 1.495, Val f1_micro: 0.237
f1-micro: 0.237, f1-macro: 0.218, f1-weighted: 0.215, , roc-auc: 0.654
##### RUN 4 #####
Epoch: 020, Train Loss: 1.651, Val f1_micro: 0.226
Epoch: 040, Train Loss: 1.549, Val f1_micro: 0.239
Epoch: 060, Train Loss: 1.522, Val f1_micro: 0.234
Epoch: 080, Train Loss: 1.535, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.538, Val f1_micro: 0.233
Epoch: 120, Train Loss: 1.526, Val f1_micro: 0.233
Epoch: 140, Train Loss: 1.539, Val f1_micro: 0.232
Epoch: 160, Train Loss: 1.537, Val f1_micro: 0.234
Epoch: 180, Train Loss: 1.520, Val f1_micro: 0.235
Epoch: 200, Train Loss: 1.529, Val f1_micro: 0.235
Epoch: 220, Train Loss: 1.526, Val f1_micro: 0.230
Epoch: 240, Train Loss: 1.526, Val f1_micro: 0.235
Epoch: 260, Train Loss: 1.515, Val f1_micro: 0.232
Epoch: 280, Train Loss: 1.527, Val f1_micro: 0.236
Epoch: 300, Train Loss: 1.521, Val f1_micro: 0.235
Epoch: 320, Train Loss: 1.515, Val f1_micro: 0.234
Epoch: 340, Train Loss: 1.517, Val f1_micro: 0.230
Epoch: 360, Train Loss: 1.524, Val f1_micro: 0.232
Epoch: 380, Train Loss: 1.517, Val f1_micro: 0.231
Epoch: 400, Train Loss: 1.524, Val f1_micro: 0.238
Epoch: 420, Train Loss: 1.514, Val f1_micro: 0.232
Epoch: 440, Train Loss: 1.506, Val f1_micro: 0.236
Epoch: 460, Train Loss: 1.512, Val f1_micro: 0.230
Epoch: 480, Train Loss: 1.508, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.511, Val f1_micro: 0.237
f1-micro: 0.237, f1-macro: 0.212, f1-weighted: 0.209, , roc-auc: 0.656
##### RUN 5 #####
Epoch: 020, Train Loss: 1.655, Val f1_micro: 0.222
Epoch: 040, Train Loss: 1.546, Val f1_micro: 0.239
Epoch: 060, Train Loss: 1.532, Val f1_micro: 0.235
Epoch: 080, Train Loss: 1.527, Val f1_micro: 0.234
Epoch: 100, Train Loss: 1.533, Val f1_micro: 0.236
Epoch: 120, Train Loss: 1.528, Val f1_micro: 0.237
Epoch: 140, Train Loss: 1.536, Val f1_micro: 0.237
Epoch: 160, Train Loss: 1.532, Val f1_micro: 0.237
Epoch: 180, Train Loss: 1.537, Val f1_micro: 0.235
Epoch: 200, Train Loss: 1.522, Val f1_micro: 0.233
Epoch: 220, Train Loss: 1.534, Val f1_micro: 0.232
Epoch: 240, Train Loss: 1.520, Val f1_micro: 0.238
Epoch: 260, Train Loss: 1.529, Val f1_micro: 0.234
Epoch: 280, Train Loss: 1.518, Val f1_micro: 0.235
Epoch: 300, Train Loss: 1.523, Val f1_micro: 0.235
Epoch: 320, Train Loss: 1.519, Val f1_micro: 0.233
Epoch: 340, Train Loss: 1.525, Val f1_micro: 0.237
Epoch: 360, Train Loss: 1.512, Val f1_micro: 0.237
Epoch: 380, Train Loss: 1.515, Val f1_micro: 0.237
Epoch: 400, Train Loss: 1.508, Val f1_micro: 0.228
Epoch: 420, Train Loss: 1.521, Val f1_micro: 0.233
Epoch: 440, Train Loss: 1.506, Val f1_micro: 0.236
Epoch: 460, Train Loss: 1.512, Val f1_micro: 0.239
Epoch: 480, Train Loss: 1.513, Val f1_micro: 0.237
Epoch: 500, Train Loss: 1.495, Val f1_micro: 0.227
f1-micro: 0.227, f1-macro: 0.207, f1-weighted: 0.204, , roc-auc: 0.656
########## Hyperparameters combination ##########
(1024, 0.3, 0.05, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.998, Val f1_micro: 0.112
Epoch: 040, Train Loss: 1.827, Val f1_micro: 0.136
Epoch: 060, Train Loss: 1.645, Val f1_micro: 0.157
Epoch: 080, Train Loss: 1.511, Val f1_micro: 0.185
Epoch: 100, Train Loss: 1.376, Val f1_micro: 0.194
Epoch: 120, Train Loss: 1.257, Val f1_micro: 0.208
Epoch: 140, Train Loss: 1.164, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.013, Val f1_micro: 0.252
Epoch: 180, Train Loss: 0.901, Val f1_micro: 0.262
Epoch: 200, Train Loss: 0.766, Val f1_micro: 0.277
Epoch: 220, Train Loss: 0.693, Val f1_micro: 0.283
Epoch: 240, Train Loss: 0.646, Val f1_micro: 0.292
Epoch: 260, Train Loss: 0.569, Val f1_micro: 0.295
Epoch: 280, Train Loss: 0.539, Val f1_micro: 0.298
Epoch: 300, Train Loss: 0.495, Val f1_micro: 0.300
Epoch: 320, Train Loss: 0.483, Val f1_micro: 0.299
Epoch: 340, Train Loss: 0.458, Val f1_micro: 0.306
Epoch: 360, Train Loss: 0.419, Val f1_micro: 0.308
Epoch: 380, Train Loss: 0.400, Val f1_micro: 0.302
Epoch: 400, Train Loss: 0.391, Val f1_micro: 0.302
Epoch: 420, Train Loss: 0.367, Val f1_micro: 0.309
Epoch: 440, Train Loss: 0.358, Val f1_micro: 0.306
Epoch: 460, Train Loss: 0.360, Val f1_micro: 0.306
Epoch: 480, Train Loss: 0.348, Val f1_micro: 0.309
Epoch: 500, Train Loss: 0.335, Val f1_micro: 0.309
f1-micro: 0.309, f1-macro: 0.305, f1-weighted: 0.310, , roc-auc: 0.673
##### RUN 2 #####
Epoch: 020, Train Loss: 2.006, Val f1_micro: 0.147
Epoch: 040, Train Loss: 1.846, Val f1_micro: 0.132
Epoch: 060, Train Loss: 1.697, Val f1_micro: 0.145
Epoch: 080, Train Loss: 1.582, Val f1_micro: 0.210
Epoch: 100, Train Loss: 1.427, Val f1_micro: 0.214
Epoch: 120, Train Loss: 1.321, Val f1_micro: 0.225
Epoch: 140, Train Loss: 1.183, Val f1_micro: 0.232
Epoch: 160, Train Loss: 1.050, Val f1_micro: 0.244
Epoch: 180, Train Loss: 0.980, Val f1_micro: 0.257
Epoch: 200, Train Loss: 0.867, Val f1_micro: 0.263
Epoch: 220, Train Loss: 0.776, Val f1_micro: 0.275
Epoch: 240, Train Loss: 0.710, Val f1_micro: 0.289
Epoch: 260, Train Loss: 0.658, Val f1_micro: 0.285
Epoch: 280, Train Loss: 0.601, Val f1_micro: 0.291
Epoch: 300, Train Loss: 0.563, Val f1_micro: 0.290
Epoch: 320, Train Loss: 0.486, Val f1_micro: 0.290
Epoch: 340, Train Loss: 0.480, Val f1_micro: 0.291
Epoch: 360, Train Loss: 0.459, Val f1_micro: 0.294
Epoch: 380, Train Loss: 0.435, Val f1_micro: 0.298
Epoch: 400, Train Loss: 0.414, Val f1_micro: 0.299
Epoch: 420, Train Loss: 0.404, Val f1_micro: 0.299
Epoch: 440, Train Loss: 0.384, Val f1_micro: 0.301
Epoch: 460, Train Loss: 0.358, Val f1_micro: 0.304
Epoch: 480, Train Loss: 0.358, Val f1_micro: 0.301
Epoch: 500, Train Loss: 0.348, Val f1_micro: 0.304
f1-micro: 0.304, f1-macro: 0.299, f1-weighted: 0.306, , roc-auc: 0.676
##### RUN 3 #####
Epoch: 020, Train Loss: 2.010, Val f1_micro: 0.105
Epoch: 040, Train Loss: 1.858, Val f1_micro: 0.177
Epoch: 060, Train Loss: 1.721, Val f1_micro: 0.143
Epoch: 080, Train Loss: 1.561, Val f1_micro: 0.173
Epoch: 100, Train Loss: 1.436, Val f1_micro: 0.194
Epoch: 120, Train Loss: 1.331, Val f1_micro: 0.211
Epoch: 140, Train Loss: 1.217, Val f1_micro: 0.215
Epoch: 160, Train Loss: 1.115, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.013, Val f1_micro: 0.254
Epoch: 200, Train Loss: 0.896, Val f1_micro: 0.254
Epoch: 220, Train Loss: 0.807, Val f1_micro: 0.272
Epoch: 240, Train Loss: 0.765, Val f1_micro: 0.275
Epoch: 260, Train Loss: 0.707, Val f1_micro: 0.282
Epoch: 280, Train Loss: 0.644, Val f1_micro: 0.283
Epoch: 300, Train Loss: 0.580, Val f1_micro: 0.292
Epoch: 320, Train Loss: 0.576, Val f1_micro: 0.291
Epoch: 340, Train Loss: 0.525, Val f1_micro: 0.295
Epoch: 360, Train Loss: 0.506, Val f1_micro: 0.297
Epoch: 380, Train Loss: 0.495, Val f1_micro: 0.299
Epoch: 400, Train Loss: 0.457, Val f1_micro: 0.300
Epoch: 420, Train Loss: 0.456, Val f1_micro: 0.302
Epoch: 440, Train Loss: 0.556, Val f1_micro: 0.292
Epoch: 460, Train Loss: 0.510, Val f1_micro: 0.300
Epoch: 480, Train Loss: 0.425, Val f1_micro: 0.303
Epoch: 500, Train Loss: 0.403, Val f1_micro: 0.304
f1-micro: 0.304, f1-macro: 0.301, f1-weighted: 0.306, , roc-auc: 0.676
##### RUN 4 #####
Epoch: 020, Train Loss: 2.006, Val f1_micro: 0.104
Epoch: 040, Train Loss: 1.842, Val f1_micro: 0.170
Epoch: 060, Train Loss: 1.644, Val f1_micro: 0.173
Epoch: 080, Train Loss: 1.495, Val f1_micro: 0.185
Epoch: 100, Train Loss: 1.365, Val f1_micro: 0.211
Epoch: 120, Train Loss: 1.263, Val f1_micro: 0.220
Epoch: 140, Train Loss: 1.133, Val f1_micro: 0.241
Epoch: 160, Train Loss: 1.034, Val f1_micro: 0.256
Epoch: 180, Train Loss: 0.955, Val f1_micro: 0.265
Epoch: 200, Train Loss: 0.869, Val f1_micro: 0.269
Epoch: 220, Train Loss: 0.817, Val f1_micro: 0.276
Epoch: 240, Train Loss: 0.736, Val f1_micro: 0.279
Epoch: 260, Train Loss: 0.690, Val f1_micro: 0.284
Epoch: 280, Train Loss: 0.628, Val f1_micro: 0.287
Epoch: 300, Train Loss: 0.599, Val f1_micro: 0.289
Epoch: 320, Train Loss: 0.576, Val f1_micro: 0.293
Epoch: 340, Train Loss: 0.544, Val f1_micro: 0.300
Epoch: 360, Train Loss: 0.466, Val f1_micro: 0.300
Epoch: 380, Train Loss: 0.465, Val f1_micro: 0.299
Epoch: 400, Train Loss: 0.444, Val f1_micro: 0.304
Epoch: 420, Train Loss: 0.421, Val f1_micro: 0.307
Epoch: 440, Train Loss: 0.422, Val f1_micro: 0.304
Epoch: 460, Train Loss: 0.427, Val f1_micro: 0.299
Epoch: 480, Train Loss: 0.402, Val f1_micro: 0.305
Epoch: 500, Train Loss: 0.388, Val f1_micro: 0.309
f1-micro: 0.309, f1-macro: 0.305, f1-weighted: 0.311, , roc-auc: 0.675
##### RUN 5 #####
Epoch: 020, Train Loss: 2.015, Val f1_micro: 0.148
Epoch: 040, Train Loss: 1.859, Val f1_micro: 0.133
Epoch: 060, Train Loss: 1.683, Val f1_micro: 0.149
Epoch: 080, Train Loss: 1.538, Val f1_micro: 0.167
Epoch: 100, Train Loss: 1.447, Val f1_micro: 0.182
Epoch: 120, Train Loss: 1.309, Val f1_micro: 0.221
Epoch: 140, Train Loss: 1.188, Val f1_micro: 0.232
Epoch: 160, Train Loss: 1.095, Val f1_micro: 0.244
Epoch: 180, Train Loss: 0.978, Val f1_micro: 0.257
Epoch: 200, Train Loss: 0.883, Val f1_micro: 0.265
Epoch: 220, Train Loss: 0.806, Val f1_micro: 0.273
Epoch: 240, Train Loss: 0.765, Val f1_micro: 0.281
Epoch: 260, Train Loss: 0.680, Val f1_micro: 0.290
Epoch: 280, Train Loss: 0.634, Val f1_micro: 0.296
Epoch: 300, Train Loss: 0.572, Val f1_micro: 0.300
Epoch: 320, Train Loss: 0.532, Val f1_micro: 0.298
Epoch: 340, Train Loss: 0.497, Val f1_micro: 0.298
Epoch: 360, Train Loss: 0.454, Val f1_micro: 0.302
Epoch: 380, Train Loss: 0.438, Val f1_micro: 0.303
Epoch: 400, Train Loss: 0.427, Val f1_micro: 0.303
Epoch: 420, Train Loss: 0.409, Val f1_micro: 0.302
Epoch: 440, Train Loss: 0.404, Val f1_micro: 0.304
Epoch: 460, Train Loss: 0.374, Val f1_micro: 0.303
Epoch: 480, Train Loss: 0.353, Val f1_micro: 0.303
Epoch: 500, Train Loss: 0.355, Val f1_micro: 0.305
f1-micro: 0.305, f1-macro: 0.301, f1-weighted: 0.307, , roc-auc: 0.671
########## Hyperparameters combination ##########
(1024, 0.3, 0.05, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.003, Val f1_micro: 0.154
Epoch: 040, Train Loss: 1.866, Val f1_micro: 0.140
Epoch: 060, Train Loss: 1.704, Val f1_micro: 0.165
Epoch: 080, Train Loss: 1.588, Val f1_micro: 0.197
Epoch: 100, Train Loss: 1.429, Val f1_micro: 0.226
Epoch: 120, Train Loss: 1.309, Val f1_micro: 0.237
Epoch: 140, Train Loss: 1.220, Val f1_micro: 0.246
Epoch: 160, Train Loss: 1.139, Val f1_micro: 0.256
Epoch: 180, Train Loss: 1.130, Val f1_micro: 0.252
Epoch: 200, Train Loss: 1.034, Val f1_micro: 0.255
Epoch: 220, Train Loss: 0.963, Val f1_micro: 0.265
Epoch: 240, Train Loss: 0.923, Val f1_micro: 0.262
Epoch: 260, Train Loss: 0.893, Val f1_micro: 0.265
Epoch: 280, Train Loss: 0.930, Val f1_micro: 0.263
Epoch: 300, Train Loss: 0.859, Val f1_micro: 0.270
Epoch: 320, Train Loss: 0.802, Val f1_micro: 0.276
Epoch: 340, Train Loss: 0.790, Val f1_micro: 0.281
Epoch: 360, Train Loss: 0.765, Val f1_micro: 0.281
Epoch: 380, Train Loss: 0.742, Val f1_micro: 0.290
Epoch: 400, Train Loss: 0.721, Val f1_micro: 0.285
Epoch: 420, Train Loss: 0.728, Val f1_micro: 0.290
Epoch: 440, Train Loss: 0.712, Val f1_micro: 0.283
Epoch: 460, Train Loss: 0.685, Val f1_micro: 0.285
Epoch: 480, Train Loss: 0.803, Val f1_micro: 0.262
Epoch: 500, Train Loss: 0.677, Val f1_micro: 0.287
f1-micro: 0.287, f1-macro: 0.282, f1-weighted: 0.287, , roc-auc: 0.670
##### RUN 2 #####
Epoch: 020, Train Loss: 2.017, Val f1_micro: 0.105
Epoch: 040, Train Loss: 1.836, Val f1_micro: 0.165
Epoch: 060, Train Loss: 1.688, Val f1_micro: 0.162
Epoch: 080, Train Loss: 1.559, Val f1_micro: 0.187
Epoch: 100, Train Loss: 1.450, Val f1_micro: 0.220
Epoch: 120, Train Loss: 1.328, Val f1_micro: 0.231
Epoch: 140, Train Loss: 1.242, Val f1_micro: 0.243
Epoch: 160, Train Loss: 1.160, Val f1_micro: 0.250
Epoch: 180, Train Loss: 1.127, Val f1_micro: 0.246
Epoch: 200, Train Loss: 1.074, Val f1_micro: 0.261
Epoch: 220, Train Loss: 1.038, Val f1_micro: 0.260
Epoch: 240, Train Loss: 0.966, Val f1_micro: 0.267
Epoch: 260, Train Loss: 0.893, Val f1_micro: 0.264
Epoch: 280, Train Loss: 0.916, Val f1_micro: 0.256
Epoch: 300, Train Loss: 0.846, Val f1_micro: 0.276
Epoch: 320, Train Loss: 0.815, Val f1_micro: 0.280
Epoch: 340, Train Loss: 0.797, Val f1_micro: 0.283
Epoch: 360, Train Loss: 0.744, Val f1_micro: 0.285
Epoch: 380, Train Loss: 0.747, Val f1_micro: 0.281
Epoch: 400, Train Loss: 0.766, Val f1_micro: 0.276
Epoch: 420, Train Loss: 0.729, Val f1_micro: 0.290
Epoch: 440, Train Loss: 0.709, Val f1_micro: 0.289
Epoch: 460, Train Loss: 0.719, Val f1_micro: 0.282
Epoch: 480, Train Loss: 0.665, Val f1_micro: 0.297
Epoch: 500, Train Loss: 0.695, Val f1_micro: 0.291
f1-micro: 0.291, f1-macro: 0.282, f1-weighted: 0.284, , roc-auc: 0.673
##### RUN 3 #####
Epoch: 020, Train Loss: 2.004, Val f1_micro: 0.107
Epoch: 040, Train Loss: 1.856, Val f1_micro: 0.181
Epoch: 060, Train Loss: 1.719, Val f1_micro: 0.177
Epoch: 080, Train Loss: 1.598, Val f1_micro: 0.190
Epoch: 100, Train Loss: 1.483, Val f1_micro: 0.210
Epoch: 120, Train Loss: 1.349, Val f1_micro: 0.220
Epoch: 140, Train Loss: 1.247, Val f1_micro: 0.233
Epoch: 160, Train Loss: 1.154, Val f1_micro: 0.248
Epoch: 180, Train Loss: 1.159, Val f1_micro: 0.246
Epoch: 200, Train Loss: 1.042, Val f1_micro: 0.257
Epoch: 220, Train Loss: 1.008, Val f1_micro: 0.256
Epoch: 240, Train Loss: 0.942, Val f1_micro: 0.270
Epoch: 260, Train Loss: 0.882, Val f1_micro: 0.261
Epoch: 280, Train Loss: 0.885, Val f1_micro: 0.268
Epoch: 300, Train Loss: 0.872, Val f1_micro: 0.270
Epoch: 320, Train Loss: 0.826, Val f1_micro: 0.272
Epoch: 340, Train Loss: 0.810, Val f1_micro: 0.281
Epoch: 360, Train Loss: 0.774, Val f1_micro: 0.274
Epoch: 380, Train Loss: 0.773, Val f1_micro: 0.277
Epoch: 400, Train Loss: 0.745, Val f1_micro: 0.287
Epoch: 420, Train Loss: 0.727, Val f1_micro: 0.282
Epoch: 440, Train Loss: 0.696, Val f1_micro: 0.290
Epoch: 460, Train Loss: 0.671, Val f1_micro: 0.272
Epoch: 480, Train Loss: 0.656, Val f1_micro: 0.287
Epoch: 500, Train Loss: 0.654, Val f1_micro: 0.296
f1-micro: 0.296, f1-macro: 0.291, f1-weighted: 0.296, , roc-auc: 0.675
##### RUN 4 #####
Epoch: 020, Train Loss: 2.009, Val f1_micro: 0.151
Epoch: 040, Train Loss: 1.876, Val f1_micro: 0.181
Epoch: 060, Train Loss: 1.777, Val f1_micro: 0.145
Epoch: 080, Train Loss: 1.678, Val f1_micro: 0.163
Epoch: 100, Train Loss: 1.539, Val f1_micro: 0.201
Epoch: 120, Train Loss: 1.372, Val f1_micro: 0.231
Epoch: 140, Train Loss: 1.264, Val f1_micro: 0.242
Epoch: 160, Train Loss: 1.173, Val f1_micro: 0.244
Epoch: 180, Train Loss: 1.091, Val f1_micro: 0.258
Epoch: 200, Train Loss: 1.034, Val f1_micro: 0.253
Epoch: 220, Train Loss: 0.979, Val f1_micro: 0.267
Epoch: 240, Train Loss: 0.945, Val f1_micro: 0.278
Epoch: 260, Train Loss: 0.920, Val f1_micro: 0.277
Epoch: 280, Train Loss: 0.831, Val f1_micro: 0.275
Epoch: 300, Train Loss: 0.816, Val f1_micro: 0.282
Epoch: 320, Train Loss: 0.825, Val f1_micro: 0.283
Epoch: 340, Train Loss: 0.756, Val f1_micro: 0.286
Epoch: 360, Train Loss: 0.734, Val f1_micro: 0.292
Epoch: 380, Train Loss: 0.782, Val f1_micro: 0.270
Epoch: 400, Train Loss: 0.709, Val f1_micro: 0.291
Epoch: 420, Train Loss: 0.713, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.703, Val f1_micro: 0.291
Epoch: 460, Train Loss: 0.644, Val f1_micro: 0.300
Epoch: 480, Train Loss: 0.655, Val f1_micro: 0.300
Epoch: 500, Train Loss: 0.635, Val f1_micro: 0.298
f1-micro: 0.298, f1-macro: 0.293, f1-weighted: 0.298, , roc-auc: 0.671
##### RUN 5 #####
Epoch: 020, Train Loss: 2.009, Val f1_micro: 0.156
Epoch: 040, Train Loss: 1.860, Val f1_micro: 0.180
Epoch: 060, Train Loss: 1.711, Val f1_micro: 0.170
Epoch: 080, Train Loss: 1.563, Val f1_micro: 0.198
Epoch: 100, Train Loss: 1.423, Val f1_micro: 0.216
Epoch: 120, Train Loss: 1.345, Val f1_micro: 0.230
Epoch: 140, Train Loss: 1.264, Val f1_micro: 0.238
Epoch: 160, Train Loss: 1.162, Val f1_micro: 0.251
Epoch: 180, Train Loss: 1.130, Val f1_micro: 0.255
Epoch: 200, Train Loss: 1.035, Val f1_micro: 0.261
Epoch: 220, Train Loss: 0.957, Val f1_micro: 0.267
Epoch: 240, Train Loss: 0.903, Val f1_micro: 0.272
Epoch: 260, Train Loss: 0.898, Val f1_micro: 0.273
Epoch: 280, Train Loss: 0.857, Val f1_micro: 0.274
Epoch: 300, Train Loss: 0.839, Val f1_micro: 0.273
Epoch: 320, Train Loss: 0.804, Val f1_micro: 0.289
Epoch: 340, Train Loss: 0.833, Val f1_micro: 0.279
Epoch: 360, Train Loss: 0.754, Val f1_micro: 0.297
Epoch: 380, Train Loss: 0.723, Val f1_micro: 0.292
Epoch: 400, Train Loss: 0.716, Val f1_micro: 0.283
Epoch: 420, Train Loss: 0.698, Val f1_micro: 0.293
Epoch: 440, Train Loss: 0.670, Val f1_micro: 0.300
Epoch: 460, Train Loss: 0.632, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.662, Val f1_micro: 0.296
Epoch: 500, Train Loss: 0.607, Val f1_micro: 0.295
f1-micro: 0.295, f1-macro: 0.291, f1-weighted: 0.294, , roc-auc: 0.674
########## Hyperparameters combination ##########
(1024, 0.3, 0.05, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.007, Val f1_micro: 0.109
Epoch: 040, Train Loss: 1.896, Val f1_micro: 0.176
Epoch: 060, Train Loss: 1.775, Val f1_micro: 0.149
Epoch: 080, Train Loss: 1.677, Val f1_micro: 0.179
Epoch: 100, Train Loss: 1.559, Val f1_micro: 0.195
Epoch: 120, Train Loss: 1.513, Val f1_micro: 0.214
Epoch: 140, Train Loss: 1.386, Val f1_micro: 0.223
Epoch: 160, Train Loss: 1.342, Val f1_micro: 0.233
Epoch: 180, Train Loss: 1.350, Val f1_micro: 0.213
Epoch: 200, Train Loss: 1.248, Val f1_micro: 0.242
Epoch: 220, Train Loss: 1.224, Val f1_micro: 0.245
Epoch: 240, Train Loss: 1.162, Val f1_micro: 0.262
Epoch: 260, Train Loss: 1.164, Val f1_micro: 0.256
Epoch: 280, Train Loss: 1.089, Val f1_micro: 0.259
Epoch: 300, Train Loss: 1.074, Val f1_micro: 0.267
Epoch: 320, Train Loss: 1.053, Val f1_micro: 0.257
Epoch: 340, Train Loss: 1.042, Val f1_micro: 0.272
Epoch: 360, Train Loss: 1.007, Val f1_micro: 0.259
Epoch: 380, Train Loss: 1.002, Val f1_micro: 0.273
Epoch: 400, Train Loss: 0.951, Val f1_micro: 0.279
Epoch: 420, Train Loss: 0.961, Val f1_micro: 0.280
Epoch: 440, Train Loss: 0.934, Val f1_micro: 0.280
Epoch: 460, Train Loss: 0.939, Val f1_micro: 0.261
Epoch: 480, Train Loss: 0.925, Val f1_micro: 0.280
Epoch: 500, Train Loss: 0.920, Val f1_micro: 0.273
f1-micro: 0.273, f1-macro: 0.264, f1-weighted: 0.266, , roc-auc: 0.667
##### RUN 2 #####
Epoch: 020, Train Loss: 2.021, Val f1_micro: 0.108
Epoch: 040, Train Loss: 1.879, Val f1_micro: 0.151
Epoch: 060, Train Loss: 1.721, Val f1_micro: 0.154
Epoch: 080, Train Loss: 1.623, Val f1_micro: 0.198
Epoch: 100, Train Loss: 1.552, Val f1_micro: 0.211
Epoch: 120, Train Loss: 1.471, Val f1_micro: 0.218
Epoch: 140, Train Loss: 1.422, Val f1_micro: 0.220
Epoch: 160, Train Loss: 1.412, Val f1_micro: 0.225
Epoch: 180, Train Loss: 1.321, Val f1_micro: 0.229
Epoch: 200, Train Loss: 1.322, Val f1_micro: 0.231
Epoch: 220, Train Loss: 1.210, Val f1_micro: 0.235
Epoch: 240, Train Loss: 1.167, Val f1_micro: 0.246
Epoch: 260, Train Loss: 1.116, Val f1_micro: 0.248
Epoch: 280, Train Loss: 1.110, Val f1_micro: 0.252
Epoch: 300, Train Loss: 1.204, Val f1_micro: 0.263
Epoch: 320, Train Loss: 1.054, Val f1_micro: 0.265
Epoch: 340, Train Loss: 1.029, Val f1_micro: 0.266
Epoch: 360, Train Loss: 1.032, Val f1_micro: 0.260
Epoch: 380, Train Loss: 0.978, Val f1_micro: 0.261
Epoch: 400, Train Loss: 1.006, Val f1_micro: 0.251
Epoch: 420, Train Loss: 0.946, Val f1_micro: 0.264
Epoch: 440, Train Loss: 0.966, Val f1_micro: 0.272
Epoch: 460, Train Loss: 0.975, Val f1_micro: 0.274
Epoch: 480, Train Loss: 0.939, Val f1_micro: 0.267
Epoch: 500, Train Loss: 0.921, Val f1_micro: 0.273
f1-micro: 0.273, f1-macro: 0.260, f1-weighted: 0.262, , roc-auc: 0.671
##### RUN 3 #####
Epoch: 020, Train Loss: 2.016, Val f1_micro: 0.106
Epoch: 040, Train Loss: 1.906, Val f1_micro: 0.176
Epoch: 060, Train Loss: 1.795, Val f1_micro: 0.144
Epoch: 080, Train Loss: 1.678, Val f1_micro: 0.177
Epoch: 100, Train Loss: 1.551, Val f1_micro: 0.220
Epoch: 120, Train Loss: 1.470, Val f1_micro: 0.221
Epoch: 140, Train Loss: 1.397, Val f1_micro: 0.218
Epoch: 160, Train Loss: 1.344, Val f1_micro: 0.229
Epoch: 180, Train Loss: 1.270, Val f1_micro: 0.246
Epoch: 200, Train Loss: 1.239, Val f1_micro: 0.238
Epoch: 220, Train Loss: 1.170, Val f1_micro: 0.245
Epoch: 240, Train Loss: 1.161, Val f1_micro: 0.248
Epoch: 260, Train Loss: 1.109, Val f1_micro: 0.266
Epoch: 280, Train Loss: 1.117, Val f1_micro: 0.234
Epoch: 300, Train Loss: 1.049, Val f1_micro: 0.247
Epoch: 320, Train Loss: 1.056, Val f1_micro: 0.264
Epoch: 340, Train Loss: 1.034, Val f1_micro: 0.266
Epoch: 360, Train Loss: 0.994, Val f1_micro: 0.267
Epoch: 380, Train Loss: 1.009, Val f1_micro: 0.268
Epoch: 400, Train Loss: 0.950, Val f1_micro: 0.272
Epoch: 420, Train Loss: 0.978, Val f1_micro: 0.277
Epoch: 440, Train Loss: 0.959, Val f1_micro: 0.270
Epoch: 460, Train Loss: 0.927, Val f1_micro: 0.276
Epoch: 480, Train Loss: 0.923, Val f1_micro: 0.263
Epoch: 500, Train Loss: 0.924, Val f1_micro: 0.276
f1-micro: 0.276, f1-macro: 0.265, f1-weighted: 0.269, , roc-auc: 0.665
##### RUN 4 #####
Epoch: 020, Train Loss: 2.028, Val f1_micro: 0.146
Epoch: 040, Train Loss: 1.913, Val f1_micro: 0.175
Epoch: 060, Train Loss: 1.828, Val f1_micro: 0.137
Epoch: 080, Train Loss: 1.701, Val f1_micro: 0.161
Epoch: 100, Train Loss: 1.587, Val f1_micro: 0.205
Epoch: 120, Train Loss: 1.461, Val f1_micro: 0.217
Epoch: 140, Train Loss: 1.379, Val f1_micro: 0.217
Epoch: 160, Train Loss: 1.325, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.300, Val f1_micro: 0.229
Epoch: 200, Train Loss: 1.242, Val f1_micro: 0.241
Epoch: 220, Train Loss: 1.244, Val f1_micro: 0.243
Epoch: 240, Train Loss: 1.161, Val f1_micro: 0.250
Epoch: 260, Train Loss: 1.132, Val f1_micro: 0.244
Epoch: 280, Train Loss: 1.104, Val f1_micro: 0.263
Epoch: 300, Train Loss: 1.119, Val f1_micro: 0.264
Epoch: 320, Train Loss: 1.094, Val f1_micro: 0.267
Epoch: 340, Train Loss: 1.036, Val f1_micro: 0.251
Epoch: 360, Train Loss: 1.110, Val f1_micro: 0.257
Epoch: 380, Train Loss: 1.026, Val f1_micro: 0.262
Epoch: 400, Train Loss: 1.039, Val f1_micro: 0.257
Epoch: 420, Train Loss: 1.039, Val f1_micro: 0.273
Epoch: 440, Train Loss: 0.987, Val f1_micro: 0.273
Epoch: 460, Train Loss: 0.991, Val f1_micro: 0.266
Epoch: 480, Train Loss: 0.970, Val f1_micro: 0.271
Epoch: 500, Train Loss: 0.973, Val f1_micro: 0.276
f1-micro: 0.276, f1-macro: 0.265, f1-weighted: 0.268, , roc-auc: 0.662
##### RUN 5 #####
Epoch: 020, Train Loss: 2.018, Val f1_micro: 0.105
Epoch: 040, Train Loss: 1.905, Val f1_micro: 0.129
Epoch: 060, Train Loss: 1.788, Val f1_micro: 0.150
Epoch: 080, Train Loss: 1.672, Val f1_micro: 0.197
Epoch: 100, Train Loss: 1.586, Val f1_micro: 0.206
Epoch: 120, Train Loss: 1.487, Val f1_micro: 0.218
Epoch: 140, Train Loss: 1.422, Val f1_micro: 0.222
Epoch: 160, Train Loss: 1.338, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.330, Val f1_micro: 0.239
Epoch: 200, Train Loss: 1.219, Val f1_micro: 0.253
Epoch: 220, Train Loss: 1.151, Val f1_micro: 0.255
Epoch: 240, Train Loss: 1.124, Val f1_micro: 0.242
Epoch: 260, Train Loss: 1.094, Val f1_micro: 0.263
Epoch: 280, Train Loss: 1.077, Val f1_micro: 0.268
Epoch: 300, Train Loss: 1.019, Val f1_micro: 0.265
Epoch: 320, Train Loss: 1.036, Val f1_micro: 0.246
Epoch: 340, Train Loss: 1.029, Val f1_micro: 0.270
Epoch: 360, Train Loss: 0.990, Val f1_micro: 0.265
Epoch: 380, Train Loss: 1.037, Val f1_micro: 0.265
Epoch: 400, Train Loss: 0.990, Val f1_micro: 0.271
Epoch: 420, Train Loss: 0.927, Val f1_micro: 0.277
Epoch: 440, Train Loss: 0.923, Val f1_micro: 0.281
Epoch: 460, Train Loss: 0.938, Val f1_micro: 0.264
Epoch: 480, Train Loss: 0.967, Val f1_micro: 0.271
Epoch: 500, Train Loss: 0.938, Val f1_micro: 0.274
f1-micro: 0.274, f1-macro: 0.263, f1-weighted: 0.268, , roc-auc: 0.671
########## Hyperparameters combination ##########
(1024, 0.3, 0.05, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.056, Val f1_micro: 0.102
Epoch: 040, Train Loss: 2.008, Val f1_micro: 0.118
Epoch: 060, Train Loss: 1.957, Val f1_micro: 0.169
Epoch: 080, Train Loss: 1.909, Val f1_micro: 0.185
Epoch: 100, Train Loss: 1.838, Val f1_micro: 0.171
Epoch: 120, Train Loss: 1.813, Val f1_micro: 0.176
Epoch: 140, Train Loss: 1.760, Val f1_micro: 0.203
Epoch: 160, Train Loss: 1.728, Val f1_micro: 0.188
Epoch: 180, Train Loss: 1.732, Val f1_micro: 0.199
Epoch: 200, Train Loss: 1.713, Val f1_micro: 0.205
Epoch: 220, Train Loss: 1.711, Val f1_micro: 0.201
Epoch: 240, Train Loss: 1.708, Val f1_micro: 0.205
Epoch: 260, Train Loss: 1.699, Val f1_micro: 0.210
Epoch: 280, Train Loss: 1.697, Val f1_micro: 0.205
Epoch: 300, Train Loss: 1.694, Val f1_micro: 0.212
Epoch: 320, Train Loss: 1.686, Val f1_micro: 0.209
Epoch: 340, Train Loss: 1.694, Val f1_micro: 0.197
Epoch: 360, Train Loss: 1.676, Val f1_micro: 0.220
Epoch: 380, Train Loss: 1.659, Val f1_micro: 0.217
Epoch: 400, Train Loss: 1.675, Val f1_micro: 0.207
Epoch: 420, Train Loss: 1.687, Val f1_micro: 0.210
Epoch: 440, Train Loss: 1.691, Val f1_micro: 0.218
Epoch: 460, Train Loss: 1.661, Val f1_micro: 0.210
Epoch: 480, Train Loss: 1.672, Val f1_micro: 0.209
Epoch: 500, Train Loss: 1.650, Val f1_micro: 0.220
f1-micro: 0.220, f1-macro: 0.189, f1-weighted: 0.187, , roc-auc: 0.637
##### RUN 2 #####
Epoch: 020, Train Loss: 2.057, Val f1_micro: 0.100
Epoch: 040, Train Loss: 2.016, Val f1_micro: 0.164
Epoch: 060, Train Loss: 1.967, Val f1_micro: 0.179
Epoch: 080, Train Loss: 1.868, Val f1_micro: 0.183
Epoch: 100, Train Loss: 1.789, Val f1_micro: 0.196
Epoch: 120, Train Loss: 1.775, Val f1_micro: 0.174
Epoch: 140, Train Loss: 1.765, Val f1_micro: 0.200
Epoch: 160, Train Loss: 1.738, Val f1_micro: 0.196
Epoch: 180, Train Loss: 1.730, Val f1_micro: 0.202
Epoch: 200, Train Loss: 1.749, Val f1_micro: 0.197
Epoch: 220, Train Loss: 1.713, Val f1_micro: 0.203
Epoch: 240, Train Loss: 1.697, Val f1_micro: 0.198
Epoch: 260, Train Loss: 1.723, Val f1_micro: 0.209
Epoch: 280, Train Loss: 1.697, Val f1_micro: 0.203
Epoch: 300, Train Loss: 1.684, Val f1_micro: 0.207
Epoch: 320, Train Loss: 1.682, Val f1_micro: 0.210
Epoch: 340, Train Loss: 1.698, Val f1_micro: 0.212
Epoch: 360, Train Loss: 1.684, Val f1_micro: 0.204
Epoch: 380, Train Loss: 1.727, Val f1_micro: 0.205
Epoch: 400, Train Loss: 1.695, Val f1_micro: 0.210
Epoch: 420, Train Loss: 1.688, Val f1_micro: 0.215
Epoch: 440, Train Loss: 1.673, Val f1_micro: 0.219
Epoch: 460, Train Loss: 1.678, Val f1_micro: 0.219
Epoch: 480, Train Loss: 1.679, Val f1_micro: 0.217
Epoch: 500, Train Loss: 1.685, Val f1_micro: 0.211
f1-micro: 0.211, f1-macro: 0.184, f1-weighted: 0.182, , roc-auc: 0.633
##### RUN 3 #####
Epoch: 020, Train Loss: 2.053, Val f1_micro: 0.104
Epoch: 040, Train Loss: 2.017, Val f1_micro: 0.115
Epoch: 060, Train Loss: 1.951, Val f1_micro: 0.153
Epoch: 080, Train Loss: 1.869, Val f1_micro: 0.166
Epoch: 100, Train Loss: 1.824, Val f1_micro: 0.181
Epoch: 120, Train Loss: 1.785, Val f1_micro: 0.203
Epoch: 140, Train Loss: 1.765, Val f1_micro: 0.172
Epoch: 160, Train Loss: 1.751, Val f1_micro: 0.202
Epoch: 180, Train Loss: 1.722, Val f1_micro: 0.201
Epoch: 200, Train Loss: 1.716, Val f1_micro: 0.202
Epoch: 220, Train Loss: 1.729, Val f1_micro: 0.195
Epoch: 240, Train Loss: 1.703, Val f1_micro: 0.208
Epoch: 260, Train Loss: 1.697, Val f1_micro: 0.203
Epoch: 280, Train Loss: 1.696, Val f1_micro: 0.205
Epoch: 300, Train Loss: 1.689, Val f1_micro: 0.208
Epoch: 320, Train Loss: 1.685, Val f1_micro: 0.198
Epoch: 340, Train Loss: 1.686, Val f1_micro: 0.206
Epoch: 360, Train Loss: 1.693, Val f1_micro: 0.215
Epoch: 380, Train Loss: 1.727, Val f1_micro: 0.201
Epoch: 400, Train Loss: 1.676, Val f1_micro: 0.210
Epoch: 420, Train Loss: 1.665, Val f1_micro: 0.200
Epoch: 440, Train Loss: 1.737, Val f1_micro: 0.206
Epoch: 460, Train Loss: 1.689, Val f1_micro: 0.213
Epoch: 480, Train Loss: 1.658, Val f1_micro: 0.218
Epoch: 500, Train Loss: 1.698, Val f1_micro: 0.190
f1-micro: 0.190, f1-macro: 0.152, f1-weighted: 0.144, , roc-auc: 0.640
##### RUN 4 #####
Epoch: 020, Train Loss: 2.042, Val f1_micro: 0.147
Epoch: 040, Train Loss: 1.968, Val f1_micro: 0.124
Epoch: 060, Train Loss: 1.911, Val f1_micro: 0.148
Epoch: 080, Train Loss: 1.855, Val f1_micro: 0.175
Epoch: 100, Train Loss: 1.803, Val f1_micro: 0.175
Epoch: 120, Train Loss: 1.765, Val f1_micro: 0.195
Epoch: 140, Train Loss: 1.755, Val f1_micro: 0.196
Epoch: 160, Train Loss: 1.746, Val f1_micro: 0.200
Epoch: 180, Train Loss: 1.718, Val f1_micro: 0.201
Epoch: 200, Train Loss: 1.734, Val f1_micro: 0.214
Epoch: 220, Train Loss: 1.698, Val f1_micro: 0.206
Epoch: 240, Train Loss: 1.704, Val f1_micro: 0.203
Epoch: 260, Train Loss: 1.735, Val f1_micro: 0.184
Epoch: 280, Train Loss: 1.716, Val f1_micro: 0.214
Epoch: 300, Train Loss: 1.728, Val f1_micro: 0.218
Epoch: 320, Train Loss: 1.709, Val f1_micro: 0.203
Epoch: 340, Train Loss: 1.682, Val f1_micro: 0.218
Epoch: 360, Train Loss: 1.658, Val f1_micro: 0.211
Epoch: 380, Train Loss: 1.681, Val f1_micro: 0.198
Epoch: 400, Train Loss: 1.672, Val f1_micro: 0.218
Epoch: 420, Train Loss: 1.669, Val f1_micro: 0.216
Epoch: 440, Train Loss: 1.654, Val f1_micro: 0.216
Epoch: 460, Train Loss: 1.674, Val f1_micro: 0.203
Epoch: 480, Train Loss: 1.721, Val f1_micro: 0.219
Epoch: 500, Train Loss: 1.676, Val f1_micro: 0.219
f1-micro: 0.219, f1-macro: 0.195, f1-weighted: 0.193, , roc-auc: 0.639
##### RUN 5 #####
Epoch: 020, Train Loss: 2.072, Val f1_micro: 0.099
Epoch: 040, Train Loss: 2.019, Val f1_micro: 0.118
Epoch: 060, Train Loss: 1.961, Val f1_micro: 0.160
Epoch: 080, Train Loss: 1.875, Val f1_micro: 0.172
Epoch: 100, Train Loss: 1.816, Val f1_micro: 0.191
Epoch: 120, Train Loss: 1.787, Val f1_micro: 0.201
Epoch: 140, Train Loss: 1.778, Val f1_micro: 0.198
Epoch: 160, Train Loss: 1.751, Val f1_micro: 0.199
Epoch: 180, Train Loss: 1.721, Val f1_micro: 0.204
Epoch: 200, Train Loss: 1.723, Val f1_micro: 0.204
Epoch: 220, Train Loss: 1.721, Val f1_micro: 0.209
Epoch: 240, Train Loss: 1.695, Val f1_micro: 0.191
Epoch: 260, Train Loss: 1.695, Val f1_micro: 0.206
Epoch: 280, Train Loss: 1.688, Val f1_micro: 0.204
Epoch: 300, Train Loss: 1.696, Val f1_micro: 0.214
Epoch: 320, Train Loss: 1.683, Val f1_micro: 0.212
Epoch: 340, Train Loss: 1.728, Val f1_micro: 0.198
Epoch: 360, Train Loss: 1.699, Val f1_micro: 0.202
Epoch: 380, Train Loss: 1.665, Val f1_micro: 0.218
Epoch: 400, Train Loss: 1.681, Val f1_micro: 0.211
Epoch: 420, Train Loss: 1.685, Val f1_micro: 0.209
Epoch: 440, Train Loss: 1.665, Val f1_micro: 0.208
Epoch: 460, Train Loss: 1.681, Val f1_micro: 0.208
Epoch: 480, Train Loss: 1.669, Val f1_micro: 0.211
Epoch: 500, Train Loss: 1.663, Val f1_micro: 0.209
f1-micro: 0.209, f1-macro: 0.177, f1-weighted: 0.178, , roc-auc: 0.638
########## Hyperparameters combination ##########
(1024, 0.4, 0.001, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.157, Val f1_micro: 0.194
Epoch: 040, Train Loss: 1.876, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.731, Val f1_micro: 0.228
Epoch: 080, Train Loss: 1.619, Val f1_micro: 0.237
Epoch: 100, Train Loss: 1.546, Val f1_micro: 0.239
Epoch: 120, Train Loss: 1.458, Val f1_micro: 0.251
Epoch: 140, Train Loss: 1.377, Val f1_micro: 0.252
Epoch: 160, Train Loss: 1.326, Val f1_micro: 0.256
Epoch: 180, Train Loss: 1.282, Val f1_micro: 0.260
Epoch: 200, Train Loss: 1.241, Val f1_micro: 0.263
Epoch: 220, Train Loss: 1.202, Val f1_micro: 0.267
Epoch: 240, Train Loss: 1.145, Val f1_micro: 0.272
Epoch: 260, Train Loss: 1.121, Val f1_micro: 0.274
Epoch: 280, Train Loss: 1.080, Val f1_micro: 0.276
Epoch: 300, Train Loss: 1.050, Val f1_micro: 0.279
Epoch: 320, Train Loss: 1.031, Val f1_micro: 0.279
Epoch: 340, Train Loss: 1.012, Val f1_micro: 0.281
Epoch: 360, Train Loss: 0.968, Val f1_micro: 0.280
Epoch: 380, Train Loss: 0.940, Val f1_micro: 0.283
Epoch: 400, Train Loss: 0.935, Val f1_micro: 0.286
Epoch: 420, Train Loss: 0.906, Val f1_micro: 0.284
Epoch: 440, Train Loss: 0.896, Val f1_micro: 0.285
Epoch: 460, Train Loss: 0.872, Val f1_micro: 0.288
Epoch: 480, Train Loss: 0.850, Val f1_micro: 0.289
Epoch: 500, Train Loss: 0.816, Val f1_micro: 0.289
f1-micro: 0.289, f1-macro: 0.282, f1-weighted: 0.285, , roc-auc: 0.681
##### RUN 2 #####
Epoch: 020, Train Loss: 2.143, Val f1_micro: 0.195
Epoch: 040, Train Loss: 1.873, Val f1_micro: 0.217
Epoch: 060, Train Loss: 1.720, Val f1_micro: 0.227
Epoch: 080, Train Loss: 1.609, Val f1_micro: 0.235
Epoch: 100, Train Loss: 1.525, Val f1_micro: 0.239
Epoch: 120, Train Loss: 1.461, Val f1_micro: 0.249
Epoch: 140, Train Loss: 1.389, Val f1_micro: 0.254
Epoch: 160, Train Loss: 1.346, Val f1_micro: 0.256
Epoch: 180, Train Loss: 1.279, Val f1_micro: 0.262
Epoch: 200, Train Loss: 1.229, Val f1_micro: 0.266
Epoch: 220, Train Loss: 1.207, Val f1_micro: 0.270
Epoch: 240, Train Loss: 1.164, Val f1_micro: 0.272
Epoch: 260, Train Loss: 1.113, Val f1_micro: 0.276
Epoch: 280, Train Loss: 1.091, Val f1_micro: 0.276
Epoch: 300, Train Loss: 1.050, Val f1_micro: 0.279
Epoch: 320, Train Loss: 1.027, Val f1_micro: 0.278
Epoch: 340, Train Loss: 1.006, Val f1_micro: 0.280
Epoch: 360, Train Loss: 0.968, Val f1_micro: 0.281
Epoch: 380, Train Loss: 0.949, Val f1_micro: 0.283
Epoch: 400, Train Loss: 0.916, Val f1_micro: 0.283
Epoch: 420, Train Loss: 0.898, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.872, Val f1_micro: 0.288
Epoch: 460, Train Loss: 0.863, Val f1_micro: 0.288
Epoch: 480, Train Loss: 0.866, Val f1_micro: 0.290
Epoch: 500, Train Loss: 0.837, Val f1_micro: 0.290
f1-micro: 0.290, f1-macro: 0.283, f1-weighted: 0.286, , roc-auc: 0.681
##### RUN 3 #####
Epoch: 020, Train Loss: 2.149, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.874, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.720, Val f1_micro: 0.228
Epoch: 080, Train Loss: 1.612, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.517, Val f1_micro: 0.241
Epoch: 120, Train Loss: 1.445, Val f1_micro: 0.245
Epoch: 140, Train Loss: 1.381, Val f1_micro: 0.254
Epoch: 160, Train Loss: 1.329, Val f1_micro: 0.257
Epoch: 180, Train Loss: 1.280, Val f1_micro: 0.261
Epoch: 200, Train Loss: 1.224, Val f1_micro: 0.264
Epoch: 220, Train Loss: 1.193, Val f1_micro: 0.268
Epoch: 240, Train Loss: 1.162, Val f1_micro: 0.273
Epoch: 260, Train Loss: 1.119, Val f1_micro: 0.276
Epoch: 280, Train Loss: 1.089, Val f1_micro: 0.277
Epoch: 300, Train Loss: 1.062, Val f1_micro: 0.280
Epoch: 320, Train Loss: 1.031, Val f1_micro: 0.281
Epoch: 340, Train Loss: 1.013, Val f1_micro: 0.280
Epoch: 360, Train Loss: 0.969, Val f1_micro: 0.281
Epoch: 380, Train Loss: 0.958, Val f1_micro: 0.284
Epoch: 400, Train Loss: 0.929, Val f1_micro: 0.286
Epoch: 420, Train Loss: 0.904, Val f1_micro: 0.287
Epoch: 440, Train Loss: 0.900, Val f1_micro: 0.286
Epoch: 460, Train Loss: 0.868, Val f1_micro: 0.290
Epoch: 480, Train Loss: 0.849, Val f1_micro: 0.290
Epoch: 500, Train Loss: 0.823, Val f1_micro: 0.290
f1-micro: 0.290, f1-macro: 0.283, f1-weighted: 0.286, , roc-auc: 0.681
##### RUN 4 #####
Epoch: 020, Train Loss: 2.148, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.876, Val f1_micro: 0.214
Epoch: 060, Train Loss: 1.732, Val f1_micro: 0.230
Epoch: 080, Train Loss: 1.629, Val f1_micro: 0.237
Epoch: 100, Train Loss: 1.532, Val f1_micro: 0.243
Epoch: 120, Train Loss: 1.437, Val f1_micro: 0.250
Epoch: 140, Train Loss: 1.402, Val f1_micro: 0.251
Epoch: 160, Train Loss: 1.322, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.280, Val f1_micro: 0.260
Epoch: 200, Train Loss: 1.246, Val f1_micro: 0.264
Epoch: 220, Train Loss: 1.203, Val f1_micro: 0.269
Epoch: 240, Train Loss: 1.162, Val f1_micro: 0.269
Epoch: 260, Train Loss: 1.119, Val f1_micro: 0.273
Epoch: 280, Train Loss: 1.095, Val f1_micro: 0.275
Epoch: 300, Train Loss: 1.068, Val f1_micro: 0.276
Epoch: 320, Train Loss: 1.043, Val f1_micro: 0.281
Epoch: 340, Train Loss: 1.005, Val f1_micro: 0.282
Epoch: 360, Train Loss: 0.985, Val f1_micro: 0.284
Epoch: 380, Train Loss: 0.955, Val f1_micro: 0.285
Epoch: 400, Train Loss: 0.945, Val f1_micro: 0.287
Epoch: 420, Train Loss: 0.918, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.893, Val f1_micro: 0.287
Epoch: 460, Train Loss: 0.866, Val f1_micro: 0.289
Epoch: 480, Train Loss: 0.830, Val f1_micro: 0.289
Epoch: 500, Train Loss: 0.814, Val f1_micro: 0.289
f1-micro: 0.289, f1-macro: 0.282, f1-weighted: 0.285, , roc-auc: 0.681
##### RUN 5 #####
Epoch: 020, Train Loss: 2.153, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.869, Val f1_micro: 0.216
Epoch: 060, Train Loss: 1.727, Val f1_micro: 0.228
Epoch: 080, Train Loss: 1.625, Val f1_micro: 0.239
Epoch: 100, Train Loss: 1.527, Val f1_micro: 0.242
Epoch: 120, Train Loss: 1.452, Val f1_micro: 0.252
Epoch: 140, Train Loss: 1.401, Val f1_micro: 0.256
Epoch: 160, Train Loss: 1.331, Val f1_micro: 0.259
Epoch: 180, Train Loss: 1.289, Val f1_micro: 0.264
Epoch: 200, Train Loss: 1.239, Val f1_micro: 0.266
Epoch: 220, Train Loss: 1.195, Val f1_micro: 0.268
Epoch: 240, Train Loss: 1.168, Val f1_micro: 0.273
Epoch: 260, Train Loss: 1.125, Val f1_micro: 0.277
Epoch: 280, Train Loss: 1.102, Val f1_micro: 0.275
Epoch: 300, Train Loss: 1.056, Val f1_micro: 0.280
Epoch: 320, Train Loss: 1.033, Val f1_micro: 0.280
Epoch: 340, Train Loss: 0.986, Val f1_micro: 0.282
Epoch: 360, Train Loss: 0.977, Val f1_micro: 0.282
Epoch: 380, Train Loss: 0.943, Val f1_micro: 0.283
Epoch: 400, Train Loss: 0.925, Val f1_micro: 0.286
Epoch: 420, Train Loss: 0.880, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.880, Val f1_micro: 0.288
Epoch: 460, Train Loss: 0.870, Val f1_micro: 0.287
Epoch: 480, Train Loss: 0.843, Val f1_micro: 0.290
Epoch: 500, Train Loss: 0.812, Val f1_micro: 0.289
f1-micro: 0.289, f1-macro: 0.282, f1-weighted: 0.285, , roc-auc: 0.681
########## Hyperparameters combination ##########
(1024, 0.4, 0.001, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.147, Val f1_micro: 0.195
Epoch: 040, Train Loss: 1.889, Val f1_micro: 0.220
Epoch: 060, Train Loss: 1.749, Val f1_micro: 0.223
Epoch: 080, Train Loss: 1.627, Val f1_micro: 0.232
Epoch: 100, Train Loss: 1.554, Val f1_micro: 0.241
Epoch: 120, Train Loss: 1.482, Val f1_micro: 0.245
Epoch: 140, Train Loss: 1.431, Val f1_micro: 0.249
Epoch: 160, Train Loss: 1.371, Val f1_micro: 0.254
Epoch: 180, Train Loss: 1.320, Val f1_micro: 0.258
Epoch: 200, Train Loss: 1.280, Val f1_micro: 0.260
Epoch: 220, Train Loss: 1.263, Val f1_micro: 0.261
Epoch: 240, Train Loss: 1.217, Val f1_micro: 0.265
Epoch: 260, Train Loss: 1.185, Val f1_micro: 0.265
Epoch: 280, Train Loss: 1.150, Val f1_micro: 0.266
Epoch: 300, Train Loss: 1.132, Val f1_micro: 0.270
Epoch: 320, Train Loss: 1.101, Val f1_micro: 0.271
Epoch: 340, Train Loss: 1.105, Val f1_micro: 0.272
Epoch: 360, Train Loss: 1.087, Val f1_micro: 0.274
Epoch: 380, Train Loss: 1.054, Val f1_micro: 0.274
Epoch: 400, Train Loss: 1.029, Val f1_micro: 0.276
Epoch: 420, Train Loss: 1.017, Val f1_micro: 0.278
Epoch: 440, Train Loss: 0.998, Val f1_micro: 0.278
Epoch: 460, Train Loss: 0.966, Val f1_micro: 0.280
Epoch: 480, Train Loss: 0.969, Val f1_micro: 0.281
Epoch: 500, Train Loss: 0.949, Val f1_micro: 0.282
f1-micro: 0.282, f1-macro: 0.273, f1-weighted: 0.275, , roc-auc: 0.683
##### RUN 2 #####
Epoch: 020, Train Loss: 2.137, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.879, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.733, Val f1_micro: 0.224
Epoch: 080, Train Loss: 1.626, Val f1_micro: 0.232
Epoch: 100, Train Loss: 1.550, Val f1_micro: 0.235
Epoch: 120, Train Loss: 1.486, Val f1_micro: 0.245
Epoch: 140, Train Loss: 1.417, Val f1_micro: 0.249
Epoch: 160, Train Loss: 1.368, Val f1_micro: 0.252
Epoch: 180, Train Loss: 1.307, Val f1_micro: 0.255
Epoch: 200, Train Loss: 1.297, Val f1_micro: 0.260
Epoch: 220, Train Loss: 1.251, Val f1_micro: 0.262
Epoch: 240, Train Loss: 1.218, Val f1_micro: 0.264
Epoch: 260, Train Loss: 1.189, Val f1_micro: 0.268
Epoch: 280, Train Loss: 1.156, Val f1_micro: 0.271
Epoch: 300, Train Loss: 1.130, Val f1_micro: 0.270
Epoch: 320, Train Loss: 1.102, Val f1_micro: 0.270
Epoch: 340, Train Loss: 1.080, Val f1_micro: 0.273
Epoch: 360, Train Loss: 1.058, Val f1_micro: 0.273
Epoch: 380, Train Loss: 1.050, Val f1_micro: 0.276
Epoch: 400, Train Loss: 1.009, Val f1_micro: 0.276
Epoch: 420, Train Loss: 1.003, Val f1_micro: 0.279
Epoch: 440, Train Loss: 0.983, Val f1_micro: 0.278
Epoch: 460, Train Loss: 0.967, Val f1_micro: 0.279
Epoch: 480, Train Loss: 0.953, Val f1_micro: 0.282
Epoch: 500, Train Loss: 0.943, Val f1_micro: 0.282
f1-micro: 0.282, f1-macro: 0.275, f1-weighted: 0.276, , roc-auc: 0.683
##### RUN 3 #####
Epoch: 020, Train Loss: 2.165, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.896, Val f1_micro: 0.219
Epoch: 060, Train Loss: 1.733, Val f1_micro: 0.222
Epoch: 080, Train Loss: 1.634, Val f1_micro: 0.230
Epoch: 100, Train Loss: 1.561, Val f1_micro: 0.237
Epoch: 120, Train Loss: 1.477, Val f1_micro: 0.244
Epoch: 140, Train Loss: 1.419, Val f1_micro: 0.250
Epoch: 160, Train Loss: 1.357, Val f1_micro: 0.254
Epoch: 180, Train Loss: 1.326, Val f1_micro: 0.254
Epoch: 200, Train Loss: 1.288, Val f1_micro: 0.261
Epoch: 220, Train Loss: 1.263, Val f1_micro: 0.262
Epoch: 240, Train Loss: 1.217, Val f1_micro: 0.265
Epoch: 260, Train Loss: 1.183, Val f1_micro: 0.266
Epoch: 280, Train Loss: 1.166, Val f1_micro: 0.268
Epoch: 300, Train Loss: 1.144, Val f1_micro: 0.270
Epoch: 320, Train Loss: 1.112, Val f1_micro: 0.270
Epoch: 340, Train Loss: 1.091, Val f1_micro: 0.274
Epoch: 360, Train Loss: 1.059, Val f1_micro: 0.274
Epoch: 380, Train Loss: 1.044, Val f1_micro: 0.275
Epoch: 400, Train Loss: 1.011, Val f1_micro: 0.276
Epoch: 420, Train Loss: 1.007, Val f1_micro: 0.277
Epoch: 440, Train Loss: 0.987, Val f1_micro: 0.277
Epoch: 460, Train Loss: 0.952, Val f1_micro: 0.276
Epoch: 480, Train Loss: 0.960, Val f1_micro: 0.279
Epoch: 500, Train Loss: 0.945, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.274, f1-weighted: 0.277, , roc-auc: 0.682
##### RUN 4 #####
Epoch: 020, Train Loss: 2.156, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.912, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.745, Val f1_micro: 0.224
Epoch: 080, Train Loss: 1.633, Val f1_micro: 0.233
Epoch: 100, Train Loss: 1.542, Val f1_micro: 0.236
Epoch: 120, Train Loss: 1.480, Val f1_micro: 0.245
Epoch: 140, Train Loss: 1.410, Val f1_micro: 0.244
Epoch: 160, Train Loss: 1.362, Val f1_micro: 0.252
Epoch: 180, Train Loss: 1.330, Val f1_micro: 0.257
Epoch: 200, Train Loss: 1.293, Val f1_micro: 0.260
Epoch: 220, Train Loss: 1.260, Val f1_micro: 0.261
Epoch: 240, Train Loss: 1.221, Val f1_micro: 0.264
Epoch: 260, Train Loss: 1.190, Val f1_micro: 0.264
Epoch: 280, Train Loss: 1.159, Val f1_micro: 0.268
Epoch: 300, Train Loss: 1.124, Val f1_micro: 0.270
Epoch: 320, Train Loss: 1.115, Val f1_micro: 0.273
Epoch: 340, Train Loss: 1.077, Val f1_micro: 0.273
Epoch: 360, Train Loss: 1.059, Val f1_micro: 0.275
Epoch: 380, Train Loss: 1.041, Val f1_micro: 0.275
Epoch: 400, Train Loss: 1.019, Val f1_micro: 0.279
Epoch: 420, Train Loss: 1.021, Val f1_micro: 0.277
Epoch: 440, Train Loss: 0.995, Val f1_micro: 0.281
Epoch: 460, Train Loss: 0.959, Val f1_micro: 0.279
Epoch: 480, Train Loss: 0.959, Val f1_micro: 0.282
Epoch: 500, Train Loss: 0.942, Val f1_micro: 0.282
f1-micro: 0.282, f1-macro: 0.275, f1-weighted: 0.277, , roc-auc: 0.682
##### RUN 5 #####
Epoch: 020, Train Loss: 2.189, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.891, Val f1_micro: 0.217
Epoch: 060, Train Loss: 1.736, Val f1_micro: 0.226
Epoch: 080, Train Loss: 1.618, Val f1_micro: 0.233
Epoch: 100, Train Loss: 1.537, Val f1_micro: 0.238
Epoch: 120, Train Loss: 1.476, Val f1_micro: 0.243
Epoch: 140, Train Loss: 1.424, Val f1_micro: 0.249
Epoch: 160, Train Loss: 1.374, Val f1_micro: 0.253
Epoch: 180, Train Loss: 1.327, Val f1_micro: 0.255
Epoch: 200, Train Loss: 1.285, Val f1_micro: 0.258
Epoch: 220, Train Loss: 1.257, Val f1_micro: 0.261
Epoch: 240, Train Loss: 1.216, Val f1_micro: 0.264
Epoch: 260, Train Loss: 1.183, Val f1_micro: 0.266
Epoch: 280, Train Loss: 1.166, Val f1_micro: 0.269
Epoch: 300, Train Loss: 1.142, Val f1_micro: 0.271
Epoch: 320, Train Loss: 1.107, Val f1_micro: 0.271
Epoch: 340, Train Loss: 1.083, Val f1_micro: 0.274
Epoch: 360, Train Loss: 1.066, Val f1_micro: 0.274
Epoch: 380, Train Loss: 1.045, Val f1_micro: 0.274
Epoch: 400, Train Loss: 1.030, Val f1_micro: 0.275
Epoch: 420, Train Loss: 1.010, Val f1_micro: 0.276
Epoch: 440, Train Loss: 0.994, Val f1_micro: 0.280
Epoch: 460, Train Loss: 0.965, Val f1_micro: 0.277
Epoch: 480, Train Loss: 0.947, Val f1_micro: 0.278
Epoch: 500, Train Loss: 0.943, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.272, f1-weighted: 0.274, , roc-auc: 0.682
########## Hyperparameters combination ##########
(1024, 0.4, 0.001, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.148, Val f1_micro: 0.190
Epoch: 040, Train Loss: 1.877, Val f1_micro: 0.208
Epoch: 060, Train Loss: 1.752, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.620, Val f1_micro: 0.229
Epoch: 100, Train Loss: 1.549, Val f1_micro: 0.231
Epoch: 120, Train Loss: 1.495, Val f1_micro: 0.239
Epoch: 140, Train Loss: 1.440, Val f1_micro: 0.244
Epoch: 160, Train Loss: 1.380, Val f1_micro: 0.243
Epoch: 180, Train Loss: 1.353, Val f1_micro: 0.247
Epoch: 200, Train Loss: 1.319, Val f1_micro: 0.251
Epoch: 220, Train Loss: 1.280, Val f1_micro: 0.252
Epoch: 240, Train Loss: 1.263, Val f1_micro: 0.255
Epoch: 260, Train Loss: 1.236, Val f1_micro: 0.259
Epoch: 280, Train Loss: 1.226, Val f1_micro: 0.257
Epoch: 300, Train Loss: 1.188, Val f1_micro: 0.262
Epoch: 320, Train Loss: 1.171, Val f1_micro: 0.262
Epoch: 340, Train Loss: 1.159, Val f1_micro: 0.266
Epoch: 360, Train Loss: 1.144, Val f1_micro: 0.266
Epoch: 380, Train Loss: 1.119, Val f1_micro: 0.266
Epoch: 400, Train Loss: 1.115, Val f1_micro: 0.268
Epoch: 420, Train Loss: 1.108, Val f1_micro: 0.269
Epoch: 440, Train Loss: 1.100, Val f1_micro: 0.267
Epoch: 460, Train Loss: 1.090, Val f1_micro: 0.272
Epoch: 480, Train Loss: 1.076, Val f1_micro: 0.270
Epoch: 500, Train Loss: 1.049, Val f1_micro: 0.271
f1-micro: 0.271, f1-macro: 0.262, f1-weighted: 0.265, , roc-auc: 0.677
##### RUN 2 #####
Epoch: 020, Train Loss: 2.144, Val f1_micro: 0.186
Epoch: 040, Train Loss: 1.871, Val f1_micro: 0.206
Epoch: 060, Train Loss: 1.722, Val f1_micro: 0.218
Epoch: 080, Train Loss: 1.643, Val f1_micro: 0.227
Epoch: 100, Train Loss: 1.558, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.493, Val f1_micro: 0.237
Epoch: 140, Train Loss: 1.430, Val f1_micro: 0.240
Epoch: 160, Train Loss: 1.405, Val f1_micro: 0.245
Epoch: 180, Train Loss: 1.361, Val f1_micro: 0.247
Epoch: 200, Train Loss: 1.304, Val f1_micro: 0.251
Epoch: 220, Train Loss: 1.293, Val f1_micro: 0.253
Epoch: 240, Train Loss: 1.257, Val f1_micro: 0.258
Epoch: 260, Train Loss: 1.226, Val f1_micro: 0.257
Epoch: 280, Train Loss: 1.228, Val f1_micro: 0.261
Epoch: 300, Train Loss: 1.183, Val f1_micro: 0.261
Epoch: 320, Train Loss: 1.175, Val f1_micro: 0.263
Epoch: 340, Train Loss: 1.156, Val f1_micro: 0.266
Epoch: 360, Train Loss: 1.143, Val f1_micro: 0.266
Epoch: 380, Train Loss: 1.122, Val f1_micro: 0.265
Epoch: 400, Train Loss: 1.110, Val f1_micro: 0.268
Epoch: 420, Train Loss: 1.098, Val f1_micro: 0.268
Epoch: 440, Train Loss: 1.091, Val f1_micro: 0.269
Epoch: 460, Train Loss: 1.066, Val f1_micro: 0.271
Epoch: 480, Train Loss: 1.048, Val f1_micro: 0.271
Epoch: 500, Train Loss: 1.049, Val f1_micro: 0.272
f1-micro: 0.272, f1-macro: 0.263, f1-weighted: 0.265, , roc-auc: 0.676
##### RUN 3 #####
Epoch: 020, Train Loss: 2.152, Val f1_micro: 0.187
Epoch: 040, Train Loss: 1.864, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.735, Val f1_micro: 0.222
Epoch: 080, Train Loss: 1.623, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.538, Val f1_micro: 0.229
Epoch: 120, Train Loss: 1.494, Val f1_micro: 0.237
Epoch: 140, Train Loss: 1.441, Val f1_micro: 0.242
Epoch: 160, Train Loss: 1.392, Val f1_micro: 0.245
Epoch: 180, Train Loss: 1.351, Val f1_micro: 0.249
Epoch: 200, Train Loss: 1.317, Val f1_micro: 0.249
Epoch: 220, Train Loss: 1.286, Val f1_micro: 0.253
Epoch: 240, Train Loss: 1.254, Val f1_micro: 0.255
Epoch: 260, Train Loss: 1.234, Val f1_micro: 0.257
Epoch: 280, Train Loss: 1.213, Val f1_micro: 0.258
Epoch: 300, Train Loss: 1.195, Val f1_micro: 0.261
Epoch: 320, Train Loss: 1.169, Val f1_micro: 0.263
Epoch: 340, Train Loss: 1.158, Val f1_micro: 0.266
Epoch: 360, Train Loss: 1.141, Val f1_micro: 0.265
Epoch: 380, Train Loss: 1.127, Val f1_micro: 0.265
Epoch: 400, Train Loss: 1.114, Val f1_micro: 0.267
Epoch: 420, Train Loss: 1.108, Val f1_micro: 0.270
Epoch: 440, Train Loss: 1.104, Val f1_micro: 0.268
Epoch: 460, Train Loss: 1.075, Val f1_micro: 0.269
Epoch: 480, Train Loss: 1.067, Val f1_micro: 0.270
Epoch: 500, Train Loss: 1.067, Val f1_micro: 0.271
f1-micro: 0.271, f1-macro: 0.262, f1-weighted: 0.264, , roc-auc: 0.677
##### RUN 4 #####
Epoch: 020, Train Loss: 2.126, Val f1_micro: 0.188
Epoch: 040, Train Loss: 1.878, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.728, Val f1_micro: 0.218
Epoch: 080, Train Loss: 1.627, Val f1_micro: 0.228
Epoch: 100, Train Loss: 1.557, Val f1_micro: 0.227
Epoch: 120, Train Loss: 1.488, Val f1_micro: 0.237
Epoch: 140, Train Loss: 1.438, Val f1_micro: 0.238
Epoch: 160, Train Loss: 1.382, Val f1_micro: 0.244
Epoch: 180, Train Loss: 1.341, Val f1_micro: 0.245
Epoch: 200, Train Loss: 1.310, Val f1_micro: 0.251
Epoch: 220, Train Loss: 1.282, Val f1_micro: 0.250
Epoch: 240, Train Loss: 1.240, Val f1_micro: 0.253
Epoch: 260, Train Loss: 1.230, Val f1_micro: 0.256
Epoch: 280, Train Loss: 1.221, Val f1_micro: 0.260
Epoch: 300, Train Loss: 1.191, Val f1_micro: 0.261
Epoch: 320, Train Loss: 1.172, Val f1_micro: 0.264
Epoch: 340, Train Loss: 1.166, Val f1_micro: 0.265
Epoch: 360, Train Loss: 1.140, Val f1_micro: 0.265
Epoch: 380, Train Loss: 1.121, Val f1_micro: 0.267
Epoch: 400, Train Loss: 1.116, Val f1_micro: 0.267
Epoch: 420, Train Loss: 1.102, Val f1_micro: 0.269
Epoch: 440, Train Loss: 1.089, Val f1_micro: 0.269
Epoch: 460, Train Loss: 1.078, Val f1_micro: 0.270
Epoch: 480, Train Loss: 1.063, Val f1_micro: 0.271
Epoch: 500, Train Loss: 1.049, Val f1_micro: 0.271
f1-micro: 0.271, f1-macro: 0.262, f1-weighted: 0.264, , roc-auc: 0.677
##### RUN 5 #####
Epoch: 020, Train Loss: 2.131, Val f1_micro: 0.186
Epoch: 040, Train Loss: 1.869, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.735, Val f1_micro: 0.221
Epoch: 080, Train Loss: 1.626, Val f1_micro: 0.228
Epoch: 100, Train Loss: 1.559, Val f1_micro: 0.235
Epoch: 120, Train Loss: 1.467, Val f1_micro: 0.238
Epoch: 140, Train Loss: 1.431, Val f1_micro: 0.243
Epoch: 160, Train Loss: 1.405, Val f1_micro: 0.245
Epoch: 180, Train Loss: 1.335, Val f1_micro: 0.249
Epoch: 200, Train Loss: 1.308, Val f1_micro: 0.252
Epoch: 220, Train Loss: 1.282, Val f1_micro: 0.255
Epoch: 240, Train Loss: 1.257, Val f1_micro: 0.258
Epoch: 260, Train Loss: 1.234, Val f1_micro: 0.257
Epoch: 280, Train Loss: 1.214, Val f1_micro: 0.260
Epoch: 300, Train Loss: 1.201, Val f1_micro: 0.261
Epoch: 320, Train Loss: 1.183, Val f1_micro: 0.263
Epoch: 340, Train Loss: 1.147, Val f1_micro: 0.264
Epoch: 360, Train Loss: 1.162, Val f1_micro: 0.265
Epoch: 380, Train Loss: 1.114, Val f1_micro: 0.268
Epoch: 400, Train Loss: 1.113, Val f1_micro: 0.269
Epoch: 420, Train Loss: 1.106, Val f1_micro: 0.268
Epoch: 440, Train Loss: 1.082, Val f1_micro: 0.269
Epoch: 460, Train Loss: 1.081, Val f1_micro: 0.273
Epoch: 480, Train Loss: 1.061, Val f1_micro: 0.271
Epoch: 500, Train Loss: 1.054, Val f1_micro: 0.273
f1-micro: 0.273, f1-macro: 0.264, f1-weighted: 0.266, , roc-auc: 0.676
########## Hyperparameters combination ##########
(1024, 0.4, 0.001, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.170, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.919, Val f1_micro: 0.210
Epoch: 060, Train Loss: 1.783, Val f1_micro: 0.215
Epoch: 080, Train Loss: 1.720, Val f1_micro: 0.221
Epoch: 100, Train Loss: 1.669, Val f1_micro: 0.225
Epoch: 120, Train Loss: 1.632, Val f1_micro: 0.226
Epoch: 140, Train Loss: 1.600, Val f1_micro: 0.226
Epoch: 160, Train Loss: 1.573, Val f1_micro: 0.228
Epoch: 180, Train Loss: 1.559, Val f1_micro: 0.229
Epoch: 200, Train Loss: 1.551, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.539, Val f1_micro: 0.230
Epoch: 240, Train Loss: 1.539, Val f1_micro: 0.231
Epoch: 260, Train Loss: 1.532, Val f1_micro: 0.231
Epoch: 280, Train Loss: 1.541, Val f1_micro: 0.230
Epoch: 300, Train Loss: 1.533, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.526, Val f1_micro: 0.233
Epoch: 340, Train Loss: 1.526, Val f1_micro: 0.231
Epoch: 360, Train Loss: 1.529, Val f1_micro: 0.234
Epoch: 380, Train Loss: 1.528, Val f1_micro: 0.232
Epoch: 400, Train Loss: 1.534, Val f1_micro: 0.234
Epoch: 420, Train Loss: 1.533, Val f1_micro: 0.230
Epoch: 440, Train Loss: 1.536, Val f1_micro: 0.229
Epoch: 460, Train Loss: 1.542, Val f1_micro: 0.230
Epoch: 480, Train Loss: 1.544, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.549, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.204, f1-weighted: 0.201, , roc-auc: 0.663
##### RUN 2 #####
Epoch: 020, Train Loss: 2.164, Val f1_micro: 0.188
Epoch: 040, Train Loss: 1.908, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.790, Val f1_micro: 0.217
Epoch: 080, Train Loss: 1.713, Val f1_micro: 0.221
Epoch: 100, Train Loss: 1.666, Val f1_micro: 0.225
Epoch: 120, Train Loss: 1.618, Val f1_micro: 0.227
Epoch: 140, Train Loss: 1.592, Val f1_micro: 0.226
Epoch: 160, Train Loss: 1.577, Val f1_micro: 0.226
Epoch: 180, Train Loss: 1.562, Val f1_micro: 0.230
Epoch: 200, Train Loss: 1.538, Val f1_micro: 0.229
Epoch: 220, Train Loss: 1.550, Val f1_micro: 0.231
Epoch: 240, Train Loss: 1.542, Val f1_micro: 0.228
Epoch: 260, Train Loss: 1.528, Val f1_micro: 0.233
Epoch: 280, Train Loss: 1.533, Val f1_micro: 0.228
Epoch: 300, Train Loss: 1.524, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.538, Val f1_micro: 0.229
Epoch: 340, Train Loss: 1.525, Val f1_micro: 0.230
Epoch: 360, Train Loss: 1.523, Val f1_micro: 0.233
Epoch: 380, Train Loss: 1.541, Val f1_micro: 0.231
Epoch: 400, Train Loss: 1.531, Val f1_micro: 0.233
Epoch: 420, Train Loss: 1.523, Val f1_micro: 0.232
Epoch: 440, Train Loss: 1.534, Val f1_micro: 0.231
Epoch: 460, Train Loss: 1.545, Val f1_micro: 0.233
Epoch: 480, Train Loss: 1.543, Val f1_micro: 0.233
Epoch: 500, Train Loss: 1.536, Val f1_micro: 0.231
f1-micro: 0.231, f1-macro: 0.206, f1-weighted: 0.204, , roc-auc: 0.664
##### RUN 3 #####
Epoch: 020, Train Loss: 2.207, Val f1_micro: 0.190
Epoch: 040, Train Loss: 1.905, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.806, Val f1_micro: 0.217
Epoch: 080, Train Loss: 1.715, Val f1_micro: 0.219
Epoch: 100, Train Loss: 1.666, Val f1_micro: 0.220
Epoch: 120, Train Loss: 1.613, Val f1_micro: 0.226
Epoch: 140, Train Loss: 1.596, Val f1_micro: 0.227
Epoch: 160, Train Loss: 1.582, Val f1_micro: 0.227
Epoch: 180, Train Loss: 1.562, Val f1_micro: 0.227
Epoch: 200, Train Loss: 1.553, Val f1_micro: 0.228
Epoch: 220, Train Loss: 1.553, Val f1_micro: 0.226
Epoch: 240, Train Loss: 1.541, Val f1_micro: 0.230
Epoch: 260, Train Loss: 1.537, Val f1_micro: 0.230
Epoch: 280, Train Loss: 1.528, Val f1_micro: 0.230
Epoch: 300, Train Loss: 1.530, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.522, Val f1_micro: 0.228
Epoch: 340, Train Loss: 1.526, Val f1_micro: 0.229
Epoch: 360, Train Loss: 1.538, Val f1_micro: 0.232
Epoch: 380, Train Loss: 1.534, Val f1_micro: 0.229
Epoch: 400, Train Loss: 1.524, Val f1_micro: 0.230
Epoch: 420, Train Loss: 1.523, Val f1_micro: 0.232
Epoch: 440, Train Loss: 1.532, Val f1_micro: 0.231
Epoch: 460, Train Loss: 1.549, Val f1_micro: 0.228
Epoch: 480, Train Loss: 1.528, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.530, Val f1_micro: 0.232
f1-micro: 0.232, f1-macro: 0.208, f1-weighted: 0.205, , roc-auc: 0.664
##### RUN 4 #####
Epoch: 020, Train Loss: 2.191, Val f1_micro: 0.187
Epoch: 040, Train Loss: 1.920, Val f1_micro: 0.208
Epoch: 060, Train Loss: 1.791, Val f1_micro: 0.215
Epoch: 080, Train Loss: 1.723, Val f1_micro: 0.219
Epoch: 100, Train Loss: 1.661, Val f1_micro: 0.221
Epoch: 120, Train Loss: 1.628, Val f1_micro: 0.227
Epoch: 140, Train Loss: 1.581, Val f1_micro: 0.228
Epoch: 160, Train Loss: 1.577, Val f1_micro: 0.230
Epoch: 180, Train Loss: 1.563, Val f1_micro: 0.227
Epoch: 200, Train Loss: 1.550, Val f1_micro: 0.229
Epoch: 220, Train Loss: 1.535, Val f1_micro: 0.230
Epoch: 240, Train Loss: 1.528, Val f1_micro: 0.232
Epoch: 260, Train Loss: 1.541, Val f1_micro: 0.232
Epoch: 280, Train Loss: 1.525, Val f1_micro: 0.229
Epoch: 300, Train Loss: 1.531, Val f1_micro: 0.228
Epoch: 320, Train Loss: 1.533, Val f1_micro: 0.233
Epoch: 340, Train Loss: 1.550, Val f1_micro: 0.230
Epoch: 360, Train Loss: 1.526, Val f1_micro: 0.234
Epoch: 380, Train Loss: 1.534, Val f1_micro: 0.233
Epoch: 400, Train Loss: 1.533, Val f1_micro: 0.235
Epoch: 420, Train Loss: 1.526, Val f1_micro: 0.232
Epoch: 440, Train Loss: 1.537, Val f1_micro: 0.230
Epoch: 460, Train Loss: 1.529, Val f1_micro: 0.231
Epoch: 480, Train Loss: 1.540, Val f1_micro: 0.231
Epoch: 500, Train Loss: 1.548, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.205, f1-weighted: 0.201, , roc-auc: 0.664
##### RUN 5 #####
Epoch: 020, Train Loss: 2.186, Val f1_micro: 0.187
Epoch: 040, Train Loss: 1.918, Val f1_micro: 0.206
Epoch: 060, Train Loss: 1.798, Val f1_micro: 0.216
Epoch: 080, Train Loss: 1.722, Val f1_micro: 0.220
Epoch: 100, Train Loss: 1.667, Val f1_micro: 0.223
Epoch: 120, Train Loss: 1.626, Val f1_micro: 0.227
Epoch: 140, Train Loss: 1.588, Val f1_micro: 0.225
Epoch: 160, Train Loss: 1.575, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.571, Val f1_micro: 0.230
Epoch: 200, Train Loss: 1.543, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.539, Val f1_micro: 0.231
Epoch: 240, Train Loss: 1.540, Val f1_micro: 0.229
Epoch: 260, Train Loss: 1.539, Val f1_micro: 0.228
Epoch: 280, Train Loss: 1.526, Val f1_micro: 0.229
Epoch: 300, Train Loss: 1.539, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.538, Val f1_micro: 0.230
Epoch: 340, Train Loss: 1.532, Val f1_micro: 0.232
Epoch: 360, Train Loss: 1.518, Val f1_micro: 0.233
Epoch: 380, Train Loss: 1.523, Val f1_micro: 0.229
Epoch: 400, Train Loss: 1.532, Val f1_micro: 0.233
Epoch: 420, Train Loss: 1.528, Val f1_micro: 0.229
Epoch: 440, Train Loss: 1.541, Val f1_micro: 0.232
Epoch: 460, Train Loss: 1.541, Val f1_micro: 0.233
Epoch: 480, Train Loss: 1.554, Val f1_micro: 0.230
Epoch: 500, Train Loss: 1.537, Val f1_micro: 0.228
f1-micro: 0.228, f1-macro: 0.203, f1-weighted: 0.199, , roc-auc: 0.663
########## Hyperparameters combination ##########
(1024, 0.4, 0.005, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.654, Val f1_micro: 0.233
Epoch: 040, Train Loss: 1.385, Val f1_micro: 0.251
Epoch: 060, Train Loss: 1.188, Val f1_micro: 0.266
Epoch: 080, Train Loss: 1.070, Val f1_micro: 0.274
Epoch: 100, Train Loss: 0.955, Val f1_micro: 0.278
Epoch: 120, Train Loss: 0.869, Val f1_micro: 0.282
Epoch: 140, Train Loss: 0.802, Val f1_micro: 0.289
Epoch: 160, Train Loss: 0.742, Val f1_micro: 0.290
Epoch: 180, Train Loss: 0.687, Val f1_micro: 0.294
Epoch: 200, Train Loss: 0.636, Val f1_micro: 0.302
Epoch: 220, Train Loss: 0.578, Val f1_micro: 0.302
Epoch: 240, Train Loss: 0.543, Val f1_micro: 0.310
Epoch: 260, Train Loss: 0.513, Val f1_micro: 0.309
Epoch: 280, Train Loss: 0.463, Val f1_micro: 0.311
Epoch: 300, Train Loss: 0.450, Val f1_micro: 0.313
Epoch: 320, Train Loss: 0.424, Val f1_micro: 0.316
Epoch: 340, Train Loss: 0.398, Val f1_micro: 0.317
Epoch: 360, Train Loss: 0.368, Val f1_micro: 0.316
Epoch: 380, Train Loss: 0.352, Val f1_micro: 0.318
Epoch: 400, Train Loss: 0.338, Val f1_micro: 0.320
Epoch: 420, Train Loss: 0.325, Val f1_micro: 0.321
Epoch: 440, Train Loss: 0.314, Val f1_micro: 0.319
Epoch: 460, Train Loss: 0.307, Val f1_micro: 0.319
Epoch: 480, Train Loss: 0.296, Val f1_micro: 0.317
Epoch: 500, Train Loss: 0.277, Val f1_micro: 0.321
f1-micro: 0.321, f1-macro: 0.315, f1-weighted: 0.321, , roc-auc: 0.691
##### RUN 2 #####
Epoch: 020, Train Loss: 1.643, Val f1_micro: 0.238
Epoch: 040, Train Loss: 1.357, Val f1_micro: 0.244
Epoch: 060, Train Loss: 1.185, Val f1_micro: 0.263
Epoch: 080, Train Loss: 1.046, Val f1_micro: 0.269
Epoch: 100, Train Loss: 0.965, Val f1_micro: 0.278
Epoch: 120, Train Loss: 0.865, Val f1_micro: 0.281
Epoch: 140, Train Loss: 0.800, Val f1_micro: 0.288
Epoch: 160, Train Loss: 0.722, Val f1_micro: 0.292
Epoch: 180, Train Loss: 0.680, Val f1_micro: 0.297
Epoch: 200, Train Loss: 0.632, Val f1_micro: 0.300
Epoch: 220, Train Loss: 0.587, Val f1_micro: 0.304
Epoch: 240, Train Loss: 0.534, Val f1_micro: 0.307
Epoch: 260, Train Loss: 0.495, Val f1_micro: 0.309
Epoch: 280, Train Loss: 0.482, Val f1_micro: 0.314
Epoch: 300, Train Loss: 0.438, Val f1_micro: 0.312
Epoch: 320, Train Loss: 0.419, Val f1_micro: 0.314
Epoch: 340, Train Loss: 0.405, Val f1_micro: 0.317
Epoch: 360, Train Loss: 0.380, Val f1_micro: 0.315
Epoch: 380, Train Loss: 0.345, Val f1_micro: 0.319
Epoch: 400, Train Loss: 0.341, Val f1_micro: 0.320
Epoch: 420, Train Loss: 0.319, Val f1_micro: 0.319
Epoch: 440, Train Loss: 0.309, Val f1_micro: 0.320
Epoch: 460, Train Loss: 0.302, Val f1_micro: 0.321
Epoch: 480, Train Loss: 0.298, Val f1_micro: 0.321
Epoch: 500, Train Loss: 0.278, Val f1_micro: 0.320
f1-micro: 0.320, f1-macro: 0.315, f1-weighted: 0.321, , roc-auc: 0.690
##### RUN 3 #####
Epoch: 020, Train Loss: 1.644, Val f1_micro: 0.229
Epoch: 040, Train Loss: 1.357, Val f1_micro: 0.251
Epoch: 060, Train Loss: 1.202, Val f1_micro: 0.269
Epoch: 080, Train Loss: 1.061, Val f1_micro: 0.274
Epoch: 100, Train Loss: 0.958, Val f1_micro: 0.276
Epoch: 120, Train Loss: 0.885, Val f1_micro: 0.285
Epoch: 140, Train Loss: 0.805, Val f1_micro: 0.286
Epoch: 160, Train Loss: 0.743, Val f1_micro: 0.293
Epoch: 180, Train Loss: 0.694, Val f1_micro: 0.294
Epoch: 200, Train Loss: 0.637, Val f1_micro: 0.301
Epoch: 220, Train Loss: 0.590, Val f1_micro: 0.304
Epoch: 240, Train Loss: 0.561, Val f1_micro: 0.305
Epoch: 260, Train Loss: 0.536, Val f1_micro: 0.309
Epoch: 280, Train Loss: 0.470, Val f1_micro: 0.311
Epoch: 300, Train Loss: 0.446, Val f1_micro: 0.312
Epoch: 320, Train Loss: 0.427, Val f1_micro: 0.312
Epoch: 340, Train Loss: 0.394, Val f1_micro: 0.314
Epoch: 360, Train Loss: 0.371, Val f1_micro: 0.316
Epoch: 380, Train Loss: 0.358, Val f1_micro: 0.317
Epoch: 400, Train Loss: 0.329, Val f1_micro: 0.317
Epoch: 420, Train Loss: 0.332, Val f1_micro: 0.319
Epoch: 440, Train Loss: 0.305, Val f1_micro: 0.319
Epoch: 460, Train Loss: 0.302, Val f1_micro: 0.320
Epoch: 480, Train Loss: 0.294, Val f1_micro: 0.320
Epoch: 500, Train Loss: 0.281, Val f1_micro: 0.319
f1-micro: 0.319, f1-macro: 0.313, f1-weighted: 0.320, , roc-auc: 0.691
##### RUN 4 #####
Epoch: 020, Train Loss: 1.646, Val f1_micro: 0.230
Epoch: 040, Train Loss: 1.361, Val f1_micro: 0.255
Epoch: 060, Train Loss: 1.190, Val f1_micro: 0.261
Epoch: 080, Train Loss: 1.075, Val f1_micro: 0.271
Epoch: 100, Train Loss: 0.963, Val f1_micro: 0.279
Epoch: 120, Train Loss: 0.879, Val f1_micro: 0.285
Epoch: 140, Train Loss: 0.779, Val f1_micro: 0.288
Epoch: 160, Train Loss: 0.749, Val f1_micro: 0.294
Epoch: 180, Train Loss: 0.675, Val f1_micro: 0.300
Epoch: 200, Train Loss: 0.635, Val f1_micro: 0.301
Epoch: 220, Train Loss: 0.586, Val f1_micro: 0.304
Epoch: 240, Train Loss: 0.555, Val f1_micro: 0.308
Epoch: 260, Train Loss: 0.501, Val f1_micro: 0.309
Epoch: 280, Train Loss: 0.477, Val f1_micro: 0.310
Epoch: 300, Train Loss: 0.457, Val f1_micro: 0.313
Epoch: 320, Train Loss: 0.428, Val f1_micro: 0.312
Epoch: 340, Train Loss: 0.382, Val f1_micro: 0.313
Epoch: 360, Train Loss: 0.388, Val f1_micro: 0.317
Epoch: 380, Train Loss: 0.351, Val f1_micro: 0.317
Epoch: 400, Train Loss: 0.342, Val f1_micro: 0.316
Epoch: 420, Train Loss: 0.309, Val f1_micro: 0.318
Epoch: 440, Train Loss: 0.311, Val f1_micro: 0.318
Epoch: 460, Train Loss: 0.299, Val f1_micro: 0.317
Epoch: 480, Train Loss: 0.300, Val f1_micro: 0.318
Epoch: 500, Train Loss: 0.283, Val f1_micro: 0.321
f1-micro: 0.321, f1-macro: 0.315, f1-weighted: 0.321, , roc-auc: 0.690
##### RUN 5 #####
Epoch: 020, Train Loss: 1.650, Val f1_micro: 0.233
Epoch: 040, Train Loss: 1.358, Val f1_micro: 0.252
Epoch: 060, Train Loss: 1.164, Val f1_micro: 0.268
Epoch: 080, Train Loss: 1.054, Val f1_micro: 0.274
Epoch: 100, Train Loss: 0.948, Val f1_micro: 0.280
Epoch: 120, Train Loss: 0.880, Val f1_micro: 0.282
Epoch: 140, Train Loss: 0.798, Val f1_micro: 0.289
Epoch: 160, Train Loss: 0.713, Val f1_micro: 0.290
Epoch: 180, Train Loss: 0.676, Val f1_micro: 0.296
Epoch: 200, Train Loss: 0.641, Val f1_micro: 0.299
Epoch: 220, Train Loss: 0.571, Val f1_micro: 0.305
Epoch: 240, Train Loss: 0.547, Val f1_micro: 0.305
Epoch: 260, Train Loss: 0.499, Val f1_micro: 0.308
Epoch: 280, Train Loss: 0.481, Val f1_micro: 0.312
Epoch: 300, Train Loss: 0.430, Val f1_micro: 0.312
Epoch: 320, Train Loss: 0.426, Val f1_micro: 0.314
Epoch: 340, Train Loss: 0.405, Val f1_micro: 0.313
Epoch: 360, Train Loss: 0.380, Val f1_micro: 0.317
Epoch: 380, Train Loss: 0.325, Val f1_micro: 0.317
Epoch: 400, Train Loss: 0.341, Val f1_micro: 0.317
Epoch: 420, Train Loss: 0.308, Val f1_micro: 0.314
Epoch: 440, Train Loss: 0.319, Val f1_micro: 0.316
Epoch: 460, Train Loss: 0.288, Val f1_micro: 0.319
Epoch: 480, Train Loss: 0.291, Val f1_micro: 0.317
Epoch: 500, Train Loss: 0.277, Val f1_micro: 0.319
f1-micro: 0.319, f1-macro: 0.314, f1-weighted: 0.320, , roc-auc: 0.690
########## Hyperparameters combination ##########
(1024, 0.4, 0.005, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.655, Val f1_micro: 0.232
Epoch: 040, Train Loss: 1.360, Val f1_micro: 0.246
Epoch: 060, Train Loss: 1.235, Val f1_micro: 0.261
Epoch: 080, Train Loss: 1.128, Val f1_micro: 0.268
Epoch: 100, Train Loss: 1.047, Val f1_micro: 0.274
Epoch: 120, Train Loss: 0.994, Val f1_micro: 0.278
Epoch: 140, Train Loss: 0.934, Val f1_micro: 0.281
Epoch: 160, Train Loss: 0.877, Val f1_micro: 0.284
Epoch: 180, Train Loss: 0.852, Val f1_micro: 0.288
Epoch: 200, Train Loss: 0.793, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.785, Val f1_micro: 0.291
Epoch: 240, Train Loss: 0.763, Val f1_micro: 0.292
Epoch: 260, Train Loss: 0.746, Val f1_micro: 0.299
Epoch: 280, Train Loss: 0.701, Val f1_micro: 0.298
Epoch: 300, Train Loss: 0.689, Val f1_micro: 0.303
Epoch: 320, Train Loss: 0.664, Val f1_micro: 0.301
Epoch: 340, Train Loss: 0.660, Val f1_micro: 0.305
Epoch: 360, Train Loss: 0.629, Val f1_micro: 0.301
Epoch: 380, Train Loss: 0.615, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.609, Val f1_micro: 0.306
Epoch: 420, Train Loss: 0.603, Val f1_micro: 0.310
Epoch: 440, Train Loss: 0.589, Val f1_micro: 0.306
Epoch: 460, Train Loss: 0.584, Val f1_micro: 0.307
Epoch: 480, Train Loss: 0.568, Val f1_micro: 0.308
Epoch: 500, Train Loss: 0.546, Val f1_micro: 0.309
f1-micro: 0.309, f1-macro: 0.304, f1-weighted: 0.308, , roc-auc: 0.691
##### RUN 2 #####
Epoch: 020, Train Loss: 1.665, Val f1_micro: 0.226
Epoch: 040, Train Loss: 1.375, Val f1_micro: 0.252
Epoch: 060, Train Loss: 1.229, Val f1_micro: 0.261
Epoch: 080, Train Loss: 1.148, Val f1_micro: 0.267
Epoch: 100, Train Loss: 1.057, Val f1_micro: 0.271
Epoch: 120, Train Loss: 0.987, Val f1_micro: 0.277
Epoch: 140, Train Loss: 0.922, Val f1_micro: 0.281
Epoch: 160, Train Loss: 0.879, Val f1_micro: 0.284
Epoch: 180, Train Loss: 0.834, Val f1_micro: 0.284
Epoch: 200, Train Loss: 0.807, Val f1_micro: 0.291
Epoch: 220, Train Loss: 0.775, Val f1_micro: 0.293
Epoch: 240, Train Loss: 0.764, Val f1_micro: 0.295
Epoch: 260, Train Loss: 0.740, Val f1_micro: 0.298
Epoch: 280, Train Loss: 0.721, Val f1_micro: 0.301
Epoch: 300, Train Loss: 0.687, Val f1_micro: 0.300
Epoch: 320, Train Loss: 0.662, Val f1_micro: 0.304
Epoch: 340, Train Loss: 0.649, Val f1_micro: 0.302
Epoch: 360, Train Loss: 0.647, Val f1_micro: 0.308
Epoch: 380, Train Loss: 0.648, Val f1_micro: 0.305
Epoch: 400, Train Loss: 0.601, Val f1_micro: 0.305
Epoch: 420, Train Loss: 0.599, Val f1_micro: 0.310
Epoch: 440, Train Loss: 0.585, Val f1_micro: 0.308
Epoch: 460, Train Loss: 0.557, Val f1_micro: 0.312
Epoch: 480, Train Loss: 0.578, Val f1_micro: 0.310
Epoch: 500, Train Loss: 0.559, Val f1_micro: 0.308
f1-micro: 0.308, f1-macro: 0.303, f1-weighted: 0.307, , roc-auc: 0.690
##### RUN 3 #####
Epoch: 020, Train Loss: 1.656, Val f1_micro: 0.226
Epoch: 040, Train Loss: 1.373, Val f1_micro: 0.249
Epoch: 060, Train Loss: 1.217, Val f1_micro: 0.263
Epoch: 080, Train Loss: 1.132, Val f1_micro: 0.267
Epoch: 100, Train Loss: 1.045, Val f1_micro: 0.272
Epoch: 120, Train Loss: 0.989, Val f1_micro: 0.275
Epoch: 140, Train Loss: 0.928, Val f1_micro: 0.283
Epoch: 160, Train Loss: 0.891, Val f1_micro: 0.282
Epoch: 180, Train Loss: 0.856, Val f1_micro: 0.288
Epoch: 200, Train Loss: 0.802, Val f1_micro: 0.289
Epoch: 220, Train Loss: 0.777, Val f1_micro: 0.290
Epoch: 240, Train Loss: 0.769, Val f1_micro: 0.296
Epoch: 260, Train Loss: 0.744, Val f1_micro: 0.296
Epoch: 280, Train Loss: 0.712, Val f1_micro: 0.297
Epoch: 300, Train Loss: 0.678, Val f1_micro: 0.299
Epoch: 320, Train Loss: 0.672, Val f1_micro: 0.304
Epoch: 340, Train Loss: 0.642, Val f1_micro: 0.301
Epoch: 360, Train Loss: 0.641, Val f1_micro: 0.305
Epoch: 380, Train Loss: 0.626, Val f1_micro: 0.307
Epoch: 400, Train Loss: 0.614, Val f1_micro: 0.307
Epoch: 420, Train Loss: 0.596, Val f1_micro: 0.308
Epoch: 440, Train Loss: 0.596, Val f1_micro: 0.309
Epoch: 460, Train Loss: 0.566, Val f1_micro: 0.310
Epoch: 480, Train Loss: 0.569, Val f1_micro: 0.311
Epoch: 500, Train Loss: 0.552, Val f1_micro: 0.312
f1-micro: 0.312, f1-macro: 0.306, f1-weighted: 0.311, , roc-auc: 0.690
##### RUN 4 #####
Epoch: 020, Train Loss: 1.657, Val f1_micro: 0.231
Epoch: 040, Train Loss: 1.390, Val f1_micro: 0.244
Epoch: 060, Train Loss: 1.220, Val f1_micro: 0.258
Epoch: 080, Train Loss: 1.116, Val f1_micro: 0.266
Epoch: 100, Train Loss: 1.039, Val f1_micro: 0.269
Epoch: 120, Train Loss: 0.970, Val f1_micro: 0.277
Epoch: 140, Train Loss: 0.935, Val f1_micro: 0.283
Epoch: 160, Train Loss: 0.879, Val f1_micro: 0.284
Epoch: 180, Train Loss: 0.833, Val f1_micro: 0.283
Epoch: 200, Train Loss: 0.794, Val f1_micro: 0.288
Epoch: 220, Train Loss: 0.789, Val f1_micro: 0.290
Epoch: 240, Train Loss: 0.756, Val f1_micro: 0.294
Epoch: 260, Train Loss: 0.731, Val f1_micro: 0.295
Epoch: 280, Train Loss: 0.701, Val f1_micro: 0.299
Epoch: 300, Train Loss: 0.683, Val f1_micro: 0.301
Epoch: 320, Train Loss: 0.657, Val f1_micro: 0.302
Epoch: 340, Train Loss: 0.658, Val f1_micro: 0.296
Epoch: 360, Train Loss: 0.649, Val f1_micro: 0.306
Epoch: 380, Train Loss: 0.605, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.615, Val f1_micro: 0.305
Epoch: 420, Train Loss: 0.601, Val f1_micro: 0.310
Epoch: 440, Train Loss: 0.594, Val f1_micro: 0.309
Epoch: 460, Train Loss: 0.573, Val f1_micro: 0.308
Epoch: 480, Train Loss: 0.552, Val f1_micro: 0.311
Epoch: 500, Train Loss: 0.561, Val f1_micro: 0.309
f1-micro: 0.309, f1-macro: 0.305, f1-weighted: 0.309, , roc-auc: 0.689
##### RUN 5 #####
Epoch: 020, Train Loss: 1.661, Val f1_micro: 0.233
Epoch: 040, Train Loss: 1.390, Val f1_micro: 0.252
Epoch: 060, Train Loss: 1.216, Val f1_micro: 0.259
Epoch: 080, Train Loss: 1.127, Val f1_micro: 0.269
Epoch: 100, Train Loss: 1.065, Val f1_micro: 0.275
Epoch: 120, Train Loss: 0.995, Val f1_micro: 0.276
Epoch: 140, Train Loss: 0.934, Val f1_micro: 0.281
Epoch: 160, Train Loss: 0.897, Val f1_micro: 0.283
Epoch: 180, Train Loss: 0.866, Val f1_micro: 0.285
Epoch: 200, Train Loss: 0.817, Val f1_micro: 0.289
Epoch: 220, Train Loss: 0.783, Val f1_micro: 0.287
Epoch: 240, Train Loss: 0.744, Val f1_micro: 0.294
Epoch: 260, Train Loss: 0.738, Val f1_micro: 0.295
Epoch: 280, Train Loss: 0.712, Val f1_micro: 0.297
Epoch: 300, Train Loss: 0.697, Val f1_micro: 0.299
Epoch: 320, Train Loss: 0.657, Val f1_micro: 0.303
Epoch: 340, Train Loss: 0.646, Val f1_micro: 0.305
Epoch: 360, Train Loss: 0.656, Val f1_micro: 0.305
Epoch: 380, Train Loss: 0.616, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.617, Val f1_micro: 0.307
Epoch: 420, Train Loss: 0.605, Val f1_micro: 0.305
Epoch: 440, Train Loss: 0.576, Val f1_micro: 0.311
Epoch: 460, Train Loss: 0.579, Val f1_micro: 0.309
Epoch: 480, Train Loss: 0.562, Val f1_micro: 0.309
Epoch: 500, Train Loss: 0.559, Val f1_micro: 0.306
f1-micro: 0.306, f1-macro: 0.301, f1-weighted: 0.305, , roc-auc: 0.689
########## Hyperparameters combination ##########
(1024, 0.4, 0.005, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.684, Val f1_micro: 0.226
Epoch: 040, Train Loss: 1.404, Val f1_micro: 0.252
Epoch: 060, Train Loss: 1.258, Val f1_micro: 0.259
Epoch: 080, Train Loss: 1.184, Val f1_micro: 0.269
Epoch: 100, Train Loss: 1.135, Val f1_micro: 0.272
Epoch: 120, Train Loss: 1.083, Val f1_micro: 0.273
Epoch: 140, Train Loss: 1.052, Val f1_micro: 0.280
Epoch: 160, Train Loss: 1.025, Val f1_micro: 0.282
Epoch: 180, Train Loss: 0.986, Val f1_micro: 0.284
Epoch: 200, Train Loss: 0.978, Val f1_micro: 0.280
Epoch: 220, Train Loss: 0.940, Val f1_micro: 0.285
Epoch: 240, Train Loss: 0.929, Val f1_micro: 0.284
Epoch: 260, Train Loss: 0.907, Val f1_micro: 0.287
Epoch: 280, Train Loss: 0.890, Val f1_micro: 0.286
Epoch: 300, Train Loss: 0.862, Val f1_micro: 0.292
Epoch: 320, Train Loss: 0.856, Val f1_micro: 0.290
Epoch: 340, Train Loss: 0.854, Val f1_micro: 0.295
Epoch: 360, Train Loss: 0.838, Val f1_micro: 0.288
Epoch: 380, Train Loss: 0.830, Val f1_micro: 0.292
Epoch: 400, Train Loss: 0.820, Val f1_micro: 0.292
Epoch: 420, Train Loss: 0.821, Val f1_micro: 0.296
Epoch: 440, Train Loss: 0.820, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.788, Val f1_micro: 0.295
Epoch: 480, Train Loss: 0.807, Val f1_micro: 0.296
Epoch: 500, Train Loss: 0.779, Val f1_micro: 0.301
f1-micro: 0.301, f1-macro: 0.292, f1-weighted: 0.297, , roc-auc: 0.683
##### RUN 2 #####
Epoch: 020, Train Loss: 1.673, Val f1_micro: 0.223
Epoch: 040, Train Loss: 1.407, Val f1_micro: 0.244
Epoch: 060, Train Loss: 1.270, Val f1_micro: 0.263
Epoch: 080, Train Loss: 1.192, Val f1_micro: 0.267
Epoch: 100, Train Loss: 1.142, Val f1_micro: 0.272
Epoch: 120, Train Loss: 1.106, Val f1_micro: 0.273
Epoch: 140, Train Loss: 1.043, Val f1_micro: 0.278
Epoch: 160, Train Loss: 1.023, Val f1_micro: 0.276
Epoch: 180, Train Loss: 0.982, Val f1_micro: 0.279
Epoch: 200, Train Loss: 0.965, Val f1_micro: 0.284
Epoch: 220, Train Loss: 0.943, Val f1_micro: 0.285
Epoch: 240, Train Loss: 0.923, Val f1_micro: 0.287
Epoch: 260, Train Loss: 0.897, Val f1_micro: 0.287
Epoch: 280, Train Loss: 0.890, Val f1_micro: 0.287
Epoch: 300, Train Loss: 0.880, Val f1_micro: 0.288
Epoch: 320, Train Loss: 0.862, Val f1_micro: 0.284
Epoch: 340, Train Loss: 0.842, Val f1_micro: 0.293
Epoch: 360, Train Loss: 0.851, Val f1_micro: 0.290
Epoch: 380, Train Loss: 0.828, Val f1_micro: 0.294
Epoch: 400, Train Loss: 0.820, Val f1_micro: 0.297
Epoch: 420, Train Loss: 0.815, Val f1_micro: 0.295
Epoch: 440, Train Loss: 0.800, Val f1_micro: 0.295
Epoch: 460, Train Loss: 0.793, Val f1_micro: 0.293
Epoch: 480, Train Loss: 0.783, Val f1_micro: 0.297
Epoch: 500, Train Loss: 0.795, Val f1_micro: 0.291
f1-micro: 0.291, f1-macro: 0.285, f1-weighted: 0.289, , roc-auc: 0.682
##### RUN 3 #####
Epoch: 020, Train Loss: 1.659, Val f1_micro: 0.231
Epoch: 040, Train Loss: 1.395, Val f1_micro: 0.249
Epoch: 060, Train Loss: 1.260, Val f1_micro: 0.259
Epoch: 080, Train Loss: 1.198, Val f1_micro: 0.265
Epoch: 100, Train Loss: 1.133, Val f1_micro: 0.273
Epoch: 120, Train Loss: 1.093, Val f1_micro: 0.272
Epoch: 140, Train Loss: 1.041, Val f1_micro: 0.276
Epoch: 160, Train Loss: 1.012, Val f1_micro: 0.281
Epoch: 180, Train Loss: 0.992, Val f1_micro: 0.282
Epoch: 200, Train Loss: 0.957, Val f1_micro: 0.278
Epoch: 220, Train Loss: 0.933, Val f1_micro: 0.286
Epoch: 240, Train Loss: 0.932, Val f1_micro: 0.286
Epoch: 260, Train Loss: 0.910, Val f1_micro: 0.285
Epoch: 280, Train Loss: 0.880, Val f1_micro: 0.288
Epoch: 300, Train Loss: 0.880, Val f1_micro: 0.287
Epoch: 320, Train Loss: 0.854, Val f1_micro: 0.290
Epoch: 340, Train Loss: 0.844, Val f1_micro: 0.288
Epoch: 360, Train Loss: 0.844, Val f1_micro: 0.290
Epoch: 380, Train Loss: 0.833, Val f1_micro: 0.292
Epoch: 400, Train Loss: 0.814, Val f1_micro: 0.292
Epoch: 420, Train Loss: 0.817, Val f1_micro: 0.294
Epoch: 440, Train Loss: 0.796, Val f1_micro: 0.291
Epoch: 460, Train Loss: 0.801, Val f1_micro: 0.293
Epoch: 480, Train Loss: 0.790, Val f1_micro: 0.296
Epoch: 500, Train Loss: 0.768, Val f1_micro: 0.299
f1-micro: 0.299, f1-macro: 0.290, f1-weighted: 0.294, , roc-auc: 0.682
##### RUN 4 #####
Epoch: 020, Train Loss: 1.659, Val f1_micro: 0.229
Epoch: 040, Train Loss: 1.410, Val f1_micro: 0.246
Epoch: 060, Train Loss: 1.274, Val f1_micro: 0.256
Epoch: 080, Train Loss: 1.191, Val f1_micro: 0.271
Epoch: 100, Train Loss: 1.125, Val f1_micro: 0.274
Epoch: 120, Train Loss: 1.076, Val f1_micro: 0.275
Epoch: 140, Train Loss: 1.035, Val f1_micro: 0.281
Epoch: 160, Train Loss: 1.010, Val f1_micro: 0.279
Epoch: 180, Train Loss: 0.980, Val f1_micro: 0.282
Epoch: 200, Train Loss: 0.960, Val f1_micro: 0.284
Epoch: 220, Train Loss: 0.929, Val f1_micro: 0.287
Epoch: 240, Train Loss: 0.933, Val f1_micro: 0.285
Epoch: 260, Train Loss: 0.901, Val f1_micro: 0.289
Epoch: 280, Train Loss: 0.879, Val f1_micro: 0.291
Epoch: 300, Train Loss: 0.875, Val f1_micro: 0.289
Epoch: 320, Train Loss: 0.870, Val f1_micro: 0.290
Epoch: 340, Train Loss: 0.863, Val f1_micro: 0.291
Epoch: 360, Train Loss: 0.827, Val f1_micro: 0.293
Epoch: 380, Train Loss: 0.843, Val f1_micro: 0.296
Epoch: 400, Train Loss: 0.824, Val f1_micro: 0.297
Epoch: 420, Train Loss: 0.807, Val f1_micro: 0.297
Epoch: 440, Train Loss: 0.816, Val f1_micro: 0.295
Epoch: 460, Train Loss: 0.807, Val f1_micro: 0.296
Epoch: 480, Train Loss: 0.790, Val f1_micro: 0.294
Epoch: 500, Train Loss: 0.784, Val f1_micro: 0.297
f1-micro: 0.297, f1-macro: 0.289, f1-weighted: 0.293, , roc-auc: 0.683
##### RUN 5 #####
Epoch: 020, Train Loss: 1.672, Val f1_micro: 0.227
Epoch: 040, Train Loss: 1.403, Val f1_micro: 0.247
Epoch: 060, Train Loss: 1.273, Val f1_micro: 0.264
Epoch: 080, Train Loss: 1.192, Val f1_micro: 0.268
Epoch: 100, Train Loss: 1.144, Val f1_micro: 0.269
Epoch: 120, Train Loss: 1.083, Val f1_micro: 0.275
Epoch: 140, Train Loss: 1.043, Val f1_micro: 0.278
Epoch: 160, Train Loss: 1.031, Val f1_micro: 0.275
Epoch: 180, Train Loss: 0.972, Val f1_micro: 0.280
Epoch: 200, Train Loss: 0.943, Val f1_micro: 0.283
Epoch: 220, Train Loss: 0.951, Val f1_micro: 0.281
Epoch: 240, Train Loss: 0.915, Val f1_micro: 0.284
Epoch: 260, Train Loss: 0.910, Val f1_micro: 0.287
Epoch: 280, Train Loss: 0.894, Val f1_micro: 0.285
Epoch: 300, Train Loss: 0.864, Val f1_micro: 0.295
Epoch: 320, Train Loss: 0.848, Val f1_micro: 0.290
Epoch: 340, Train Loss: 0.853, Val f1_micro: 0.291
Epoch: 360, Train Loss: 0.829, Val f1_micro: 0.292
Epoch: 380, Train Loss: 0.826, Val f1_micro: 0.291
Epoch: 400, Train Loss: 0.831, Val f1_micro: 0.291
Epoch: 420, Train Loss: 0.816, Val f1_micro: 0.296
Epoch: 440, Train Loss: 0.808, Val f1_micro: 0.294
Epoch: 460, Train Loss: 0.804, Val f1_micro: 0.293
Epoch: 480, Train Loss: 0.806, Val f1_micro: 0.296
Epoch: 500, Train Loss: 0.778, Val f1_micro: 0.297
f1-micro: 0.297, f1-macro: 0.290, f1-weighted: 0.295, , roc-auc: 0.683
########## Hyperparameters combination ##########
(1024, 0.4, 0.005, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.726, Val f1_micro: 0.226
Epoch: 040, Train Loss: 1.576, Val f1_micro: 0.240
Epoch: 060, Train Loss: 1.545, Val f1_micro: 0.238
Epoch: 080, Train Loss: 1.550, Val f1_micro: 0.229
Epoch: 100, Train Loss: 1.540, Val f1_micro: 0.225
Epoch: 120, Train Loss: 1.547, Val f1_micro: 0.232
Epoch: 140, Train Loss: 1.568, Val f1_micro: 0.228
Epoch: 160, Train Loss: 1.562, Val f1_micro: 0.225
Epoch: 180, Train Loss: 1.553, Val f1_micro: 0.225
Epoch: 200, Train Loss: 1.580, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.574, Val f1_micro: 0.225
Epoch: 240, Train Loss: 1.575, Val f1_micro: 0.224
Epoch: 260, Train Loss: 1.572, Val f1_micro: 0.227
Epoch: 280, Train Loss: 1.575, Val f1_micro: 0.227
Epoch: 300, Train Loss: 1.572, Val f1_micro: 0.228
Epoch: 320, Train Loss: 1.573, Val f1_micro: 0.230
Epoch: 340, Train Loss: 1.571, Val f1_micro: 0.230
Epoch: 360, Train Loss: 1.572, Val f1_micro: 0.230
Epoch: 380, Train Loss: 1.569, Val f1_micro: 0.226
Epoch: 400, Train Loss: 1.572, Val f1_micro: 0.229
Epoch: 420, Train Loss: 1.577, Val f1_micro: 0.229
Epoch: 440, Train Loss: 1.567, Val f1_micro: 0.225
Epoch: 460, Train Loss: 1.578, Val f1_micro: 0.227
Epoch: 480, Train Loss: 1.563, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.563, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.207, f1-weighted: 0.203, , roc-auc: 0.650
##### RUN 2 #####
Epoch: 020, Train Loss: 1.729, Val f1_micro: 0.227
Epoch: 040, Train Loss: 1.554, Val f1_micro: 0.230
Epoch: 060, Train Loss: 1.534, Val f1_micro: 0.230
Epoch: 080, Train Loss: 1.534, Val f1_micro: 0.229
Epoch: 100, Train Loss: 1.547, Val f1_micro: 0.234
Epoch: 120, Train Loss: 1.537, Val f1_micro: 0.230
Epoch: 140, Train Loss: 1.570, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.558, Val f1_micro: 0.228
Epoch: 180, Train Loss: 1.562, Val f1_micro: 0.228
Epoch: 200, Train Loss: 1.563, Val f1_micro: 0.222
Epoch: 220, Train Loss: 1.564, Val f1_micro: 0.230
Epoch: 240, Train Loss: 1.578, Val f1_micro: 0.230
Epoch: 260, Train Loss: 1.572, Val f1_micro: 0.226
Epoch: 280, Train Loss: 1.569, Val f1_micro: 0.230
Epoch: 300, Train Loss: 1.556, Val f1_micro: 0.226
Epoch: 320, Train Loss: 1.572, Val f1_micro: 0.228
Epoch: 340, Train Loss: 1.567, Val f1_micro: 0.219
Epoch: 360, Train Loss: 1.581, Val f1_micro: 0.223
Epoch: 380, Train Loss: 1.574, Val f1_micro: 0.228
Epoch: 400, Train Loss: 1.578, Val f1_micro: 0.228
Epoch: 420, Train Loss: 1.585, Val f1_micro: 0.226
Epoch: 440, Train Loss: 1.557, Val f1_micro: 0.222
Epoch: 460, Train Loss: 1.560, Val f1_micro: 0.228
Epoch: 480, Train Loss: 1.557, Val f1_micro: 0.227
Epoch: 500, Train Loss: 1.554, Val f1_micro: 0.231
f1-micro: 0.231, f1-macro: 0.209, f1-weighted: 0.207, , roc-auc: 0.652
##### RUN 3 #####
Epoch: 020, Train Loss: 1.705, Val f1_micro: 0.227
Epoch: 040, Train Loss: 1.568, Val f1_micro: 0.232
Epoch: 060, Train Loss: 1.535, Val f1_micro: 0.230
Epoch: 080, Train Loss: 1.527, Val f1_micro: 0.229
Epoch: 100, Train Loss: 1.549, Val f1_micro: 0.231
Epoch: 120, Train Loss: 1.556, Val f1_micro: 0.226
Epoch: 140, Train Loss: 1.551, Val f1_micro: 0.234
Epoch: 160, Train Loss: 1.566, Val f1_micro: 0.233
Epoch: 180, Train Loss: 1.577, Val f1_micro: 0.233
Epoch: 200, Train Loss: 1.571, Val f1_micro: 0.226
Epoch: 220, Train Loss: 1.585, Val f1_micro: 0.226
Epoch: 240, Train Loss: 1.572, Val f1_micro: 0.229
Epoch: 260, Train Loss: 1.575, Val f1_micro: 0.228
Epoch: 280, Train Loss: 1.579, Val f1_micro: 0.227
Epoch: 300, Train Loss: 1.578, Val f1_micro: 0.226
Epoch: 320, Train Loss: 1.575, Val f1_micro: 0.228
Epoch: 340, Train Loss: 1.578, Val f1_micro: 0.225
Epoch: 360, Train Loss: 1.574, Val f1_micro: 0.228
Epoch: 380, Train Loss: 1.570, Val f1_micro: 0.224
Epoch: 400, Train Loss: 1.562, Val f1_micro: 0.231
Epoch: 420, Train Loss: 1.564, Val f1_micro: 0.226
Epoch: 440, Train Loss: 1.569, Val f1_micro: 0.225
Epoch: 460, Train Loss: 1.571, Val f1_micro: 0.228
Epoch: 480, Train Loss: 1.577, Val f1_micro: 0.229
Epoch: 500, Train Loss: 1.553, Val f1_micro: 0.228
f1-micro: 0.228, f1-macro: 0.204, f1-weighted: 0.201, , roc-auc: 0.649
##### RUN 4 #####
Epoch: 020, Train Loss: 1.710, Val f1_micro: 0.228
Epoch: 040, Train Loss: 1.567, Val f1_micro: 0.232
Epoch: 060, Train Loss: 1.534, Val f1_micro: 0.235
Epoch: 080, Train Loss: 1.540, Val f1_micro: 0.235
Epoch: 100, Train Loss: 1.540, Val f1_micro: 0.234
Epoch: 120, Train Loss: 1.563, Val f1_micro: 0.232
Epoch: 140, Train Loss: 1.554, Val f1_micro: 0.227
Epoch: 160, Train Loss: 1.568, Val f1_micro: 0.235
Epoch: 180, Train Loss: 1.576, Val f1_micro: 0.230
Epoch: 200, Train Loss: 1.580, Val f1_micro: 0.226
Epoch: 220, Train Loss: 1.564, Val f1_micro: 0.229
Epoch: 240, Train Loss: 1.563, Val f1_micro: 0.225
Epoch: 260, Train Loss: 1.575, Val f1_micro: 0.226
Epoch: 280, Train Loss: 1.581, Val f1_micro: 0.225
Epoch: 300, Train Loss: 1.587, Val f1_micro: 0.223
Epoch: 320, Train Loss: 1.576, Val f1_micro: 0.230
Epoch: 340, Train Loss: 1.570, Val f1_micro: 0.225
Epoch: 360, Train Loss: 1.571, Val f1_micro: 0.226
Epoch: 380, Train Loss: 1.578, Val f1_micro: 0.225
Epoch: 400, Train Loss: 1.578, Val f1_micro: 0.226
Epoch: 420, Train Loss: 1.576, Val f1_micro: 0.229
Epoch: 440, Train Loss: 1.566, Val f1_micro: 0.226
Epoch: 460, Train Loss: 1.561, Val f1_micro: 0.220
Epoch: 480, Train Loss: 1.561, Val f1_micro: 0.226
Epoch: 500, Train Loss: 1.553, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.207, f1-weighted: 0.203, , roc-auc: 0.651
##### RUN 5 #####
Epoch: 020, Train Loss: 1.717, Val f1_micro: 0.233
Epoch: 040, Train Loss: 1.565, Val f1_micro: 0.236
Epoch: 060, Train Loss: 1.546, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.537, Val f1_micro: 0.230
Epoch: 100, Train Loss: 1.549, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.554, Val f1_micro: 0.232
Epoch: 140, Train Loss: 1.562, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.576, Val f1_micro: 0.228
Epoch: 180, Train Loss: 1.561, Val f1_micro: 0.230
Epoch: 200, Train Loss: 1.577, Val f1_micro: 0.228
Epoch: 220, Train Loss: 1.573, Val f1_micro: 0.226
Epoch: 240, Train Loss: 1.579, Val f1_micro: 0.230
Epoch: 260, Train Loss: 1.577, Val f1_micro: 0.226
Epoch: 280, Train Loss: 1.585, Val f1_micro: 0.225
Epoch: 300, Train Loss: 1.578, Val f1_micro: 0.229
Epoch: 320, Train Loss: 1.572, Val f1_micro: 0.224
Epoch: 340, Train Loss: 1.553, Val f1_micro: 0.226
Epoch: 360, Train Loss: 1.569, Val f1_micro: 0.227
Epoch: 380, Train Loss: 1.572, Val f1_micro: 0.221
Epoch: 400, Train Loss: 1.573, Val f1_micro: 0.229
Epoch: 420, Train Loss: 1.563, Val f1_micro: 0.234
Epoch: 440, Train Loss: 1.572, Val f1_micro: 0.226
Epoch: 460, Train Loss: 1.568, Val f1_micro: 0.228
Epoch: 480, Train Loss: 1.565, Val f1_micro: 0.228
Epoch: 500, Train Loss: 1.570, Val f1_micro: 0.225
f1-micro: 0.225, f1-macro: 0.205, f1-weighted: 0.201, , roc-auc: 0.651
########## Hyperparameters combination ##########
(1024, 0.4, 0.01, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.586, Val f1_micro: 0.224
Epoch: 040, Train Loss: 1.273, Val f1_micro: 0.258
Epoch: 060, Train Loss: 1.097, Val f1_micro: 0.275
Epoch: 080, Train Loss: 0.958, Val f1_micro: 0.282
Epoch: 100, Train Loss: 0.848, Val f1_micro: 0.288
Epoch: 120, Train Loss: 0.780, Val f1_micro: 0.293
Epoch: 140, Train Loss: 0.667, Val f1_micro: 0.301
Epoch: 160, Train Loss: 0.596, Val f1_micro: 0.305
Epoch: 180, Train Loss: 0.547, Val f1_micro: 0.308
Epoch: 200, Train Loss: 0.483, Val f1_micro: 0.313
Epoch: 220, Train Loss: 0.458, Val f1_micro: 0.316
Epoch: 240, Train Loss: 0.429, Val f1_micro: 0.315
Epoch: 260, Train Loss: 0.394, Val f1_micro: 0.317
Epoch: 280, Train Loss: 0.359, Val f1_micro: 0.321
Epoch: 300, Train Loss: 0.342, Val f1_micro: 0.321
Epoch: 320, Train Loss: 0.323, Val f1_micro: 0.322
Epoch: 340, Train Loss: 0.305, Val f1_micro: 0.323
Epoch: 360, Train Loss: 0.294, Val f1_micro: 0.326
Epoch: 380, Train Loss: 0.291, Val f1_micro: 0.327
Epoch: 400, Train Loss: 0.270, Val f1_micro: 0.323
Epoch: 420, Train Loss: 0.260, Val f1_micro: 0.324
Epoch: 440, Train Loss: 0.240, Val f1_micro: 0.327
Epoch: 460, Train Loss: 0.228, Val f1_micro: 0.328
Epoch: 480, Train Loss: 0.225, Val f1_micro: 0.325
Epoch: 500, Train Loss: 0.219, Val f1_micro: 0.324
f1-micro: 0.324, f1-macro: 0.318, f1-weighted: 0.325, , roc-auc: 0.695
##### RUN 2 #####
Epoch: 020, Train Loss: 1.594, Val f1_micro: 0.235
Epoch: 040, Train Loss: 1.264, Val f1_micro: 0.257
Epoch: 060, Train Loss: 1.081, Val f1_micro: 0.271
Epoch: 080, Train Loss: 0.935, Val f1_micro: 0.283
Epoch: 100, Train Loss: 0.833, Val f1_micro: 0.290
Epoch: 120, Train Loss: 0.760, Val f1_micro: 0.294
Epoch: 140, Train Loss: 0.692, Val f1_micro: 0.299
Epoch: 160, Train Loss: 0.612, Val f1_micro: 0.308
Epoch: 180, Train Loss: 0.550, Val f1_micro: 0.306
Epoch: 200, Train Loss: 0.489, Val f1_micro: 0.313
Epoch: 220, Train Loss: 0.443, Val f1_micro: 0.315
Epoch: 240, Train Loss: 0.395, Val f1_micro: 0.314
Epoch: 260, Train Loss: 0.382, Val f1_micro: 0.317
Epoch: 280, Train Loss: 0.366, Val f1_micro: 0.318
Epoch: 300, Train Loss: 0.356, Val f1_micro: 0.322
Epoch: 320, Train Loss: 0.328, Val f1_micro: 0.322
Epoch: 340, Train Loss: 0.308, Val f1_micro: 0.323
Epoch: 360, Train Loss: 0.289, Val f1_micro: 0.324
Epoch: 380, Train Loss: 0.284, Val f1_micro: 0.323
Epoch: 400, Train Loss: 0.260, Val f1_micro: 0.325
Epoch: 420, Train Loss: 0.263, Val f1_micro: 0.325
Epoch: 440, Train Loss: 0.252, Val f1_micro: 0.324
Epoch: 460, Train Loss: 0.239, Val f1_micro: 0.326
Epoch: 480, Train Loss: 0.231, Val f1_micro: 0.324
Epoch: 500, Train Loss: 0.225, Val f1_micro: 0.325
f1-micro: 0.325, f1-macro: 0.319, f1-weighted: 0.325, , roc-auc: 0.696
##### RUN 3 #####
Epoch: 020, Train Loss: 1.573, Val f1_micro: 0.230
Epoch: 040, Train Loss: 1.255, Val f1_micro: 0.261
Epoch: 060, Train Loss: 1.094, Val f1_micro: 0.272
Epoch: 080, Train Loss: 0.942, Val f1_micro: 0.280
Epoch: 100, Train Loss: 0.845, Val f1_micro: 0.287
Epoch: 120, Train Loss: 0.733, Val f1_micro: 0.297
Epoch: 140, Train Loss: 0.682, Val f1_micro: 0.303
Epoch: 160, Train Loss: 0.588, Val f1_micro: 0.307
Epoch: 180, Train Loss: 0.567, Val f1_micro: 0.310
Epoch: 200, Train Loss: 0.501, Val f1_micro: 0.311
Epoch: 220, Train Loss: 0.452, Val f1_micro: 0.314
Epoch: 240, Train Loss: 0.406, Val f1_micro: 0.316
Epoch: 260, Train Loss: 0.393, Val f1_micro: 0.318
Epoch: 280, Train Loss: 0.368, Val f1_micro: 0.320
Epoch: 300, Train Loss: 0.339, Val f1_micro: 0.323
Epoch: 320, Train Loss: 0.319, Val f1_micro: 0.325
Epoch: 340, Train Loss: 0.312, Val f1_micro: 0.322
Epoch: 360, Train Loss: 0.315, Val f1_micro: 0.324
Epoch: 380, Train Loss: 0.282, Val f1_micro: 0.327
Epoch: 400, Train Loss: 0.263, Val f1_micro: 0.327
Epoch: 420, Train Loss: 0.261, Val f1_micro: 0.328
Epoch: 440, Train Loss: 0.252, Val f1_micro: 0.328
Epoch: 460, Train Loss: 0.236, Val f1_micro: 0.325
Epoch: 480, Train Loss: 0.218, Val f1_micro: 0.326
Epoch: 500, Train Loss: 0.225, Val f1_micro: 0.327
f1-micro: 0.327, f1-macro: 0.322, f1-weighted: 0.329, , roc-auc: 0.697
##### RUN 4 #####
Epoch: 020, Train Loss: 1.597, Val f1_micro: 0.232
Epoch: 040, Train Loss: 1.278, Val f1_micro: 0.259
Epoch: 060, Train Loss: 1.079, Val f1_micro: 0.272
Epoch: 080, Train Loss: 0.931, Val f1_micro: 0.289
Epoch: 100, Train Loss: 0.831, Val f1_micro: 0.288
Epoch: 120, Train Loss: 0.747, Val f1_micro: 0.296
Epoch: 140, Train Loss: 0.683, Val f1_micro: 0.302
Epoch: 160, Train Loss: 0.606, Val f1_micro: 0.306
Epoch: 180, Train Loss: 0.532, Val f1_micro: 0.309
Epoch: 200, Train Loss: 0.500, Val f1_micro: 0.310
Epoch: 220, Train Loss: 0.443, Val f1_micro: 0.314
Epoch: 240, Train Loss: 0.410, Val f1_micro: 0.315
Epoch: 260, Train Loss: 0.395, Val f1_micro: 0.317
Epoch: 280, Train Loss: 0.343, Val f1_micro: 0.322
Epoch: 300, Train Loss: 0.353, Val f1_micro: 0.321
Epoch: 320, Train Loss: 0.336, Val f1_micro: 0.322
Epoch: 340, Train Loss: 0.300, Val f1_micro: 0.322
Epoch: 360, Train Loss: 0.277, Val f1_micro: 0.325
Epoch: 380, Train Loss: 0.277, Val f1_micro: 0.323
Epoch: 400, Train Loss: 0.257, Val f1_micro: 0.323
Epoch: 420, Train Loss: 0.241, Val f1_micro: 0.324
Epoch: 440, Train Loss: 0.234, Val f1_micro: 0.322
Epoch: 460, Train Loss: 0.242, Val f1_micro: 0.323
Epoch: 480, Train Loss: 0.225, Val f1_micro: 0.326
Epoch: 500, Train Loss: 0.205, Val f1_micro: 0.323
f1-micro: 0.323, f1-macro: 0.318, f1-weighted: 0.324, , roc-auc: 0.694
##### RUN 5 #####
Epoch: 020, Train Loss: 1.613, Val f1_micro: 0.233
Epoch: 040, Train Loss: 1.271, Val f1_micro: 0.258
Epoch: 060, Train Loss: 1.096, Val f1_micro: 0.271
Epoch: 080, Train Loss: 0.959, Val f1_micro: 0.281
Epoch: 100, Train Loss: 0.849, Val f1_micro: 0.295
Epoch: 120, Train Loss: 0.771, Val f1_micro: 0.302
Epoch: 140, Train Loss: 0.661, Val f1_micro: 0.306
Epoch: 160, Train Loss: 0.601, Val f1_micro: 0.305
Epoch: 180, Train Loss: 0.546, Val f1_micro: 0.311
Epoch: 200, Train Loss: 0.504, Val f1_micro: 0.313
Epoch: 220, Train Loss: 0.455, Val f1_micro: 0.316
Epoch: 240, Train Loss: 0.412, Val f1_micro: 0.317
Epoch: 260, Train Loss: 0.386, Val f1_micro: 0.318
Epoch: 280, Train Loss: 0.364, Val f1_micro: 0.321
Epoch: 300, Train Loss: 0.344, Val f1_micro: 0.323
Epoch: 320, Train Loss: 0.314, Val f1_micro: 0.325
Epoch: 340, Train Loss: 0.282, Val f1_micro: 0.324
Epoch: 360, Train Loss: 0.287, Val f1_micro: 0.323
Epoch: 380, Train Loss: 0.282, Val f1_micro: 0.326
Epoch: 400, Train Loss: 0.260, Val f1_micro: 0.324
Epoch: 420, Train Loss: 0.256, Val f1_micro: 0.326
Epoch: 440, Train Loss: 0.258, Val f1_micro: 0.326
Epoch: 460, Train Loss: 0.239, Val f1_micro: 0.323
Epoch: 480, Train Loss: 0.225, Val f1_micro: 0.324
Epoch: 500, Train Loss: 0.223, Val f1_micro: 0.326
f1-micro: 0.326, f1-macro: 0.321, f1-weighted: 0.327, , roc-auc: 0.696
########## Hyperparameters combination ##########
(1024, 0.4, 0.01, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.596, Val f1_micro: 0.231
Epoch: 040, Train Loss: 1.300, Val f1_micro: 0.262
Epoch: 060, Train Loss: 1.175, Val f1_micro: 0.266
Epoch: 080, Train Loss: 1.040, Val f1_micro: 0.273
Epoch: 100, Train Loss: 0.986, Val f1_micro: 0.275
Epoch: 120, Train Loss: 0.914, Val f1_micro: 0.279
Epoch: 140, Train Loss: 0.849, Val f1_micro: 0.287
Epoch: 160, Train Loss: 0.807, Val f1_micro: 0.285
Epoch: 180, Train Loss: 0.766, Val f1_micro: 0.288
Epoch: 200, Train Loss: 0.735, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.722, Val f1_micro: 0.293
Epoch: 240, Train Loss: 0.687, Val f1_micro: 0.295
Epoch: 260, Train Loss: 0.680, Val f1_micro: 0.300
Epoch: 280, Train Loss: 0.633, Val f1_micro: 0.301
Epoch: 300, Train Loss: 0.628, Val f1_micro: 0.302
Epoch: 320, Train Loss: 0.592, Val f1_micro: 0.305
Epoch: 340, Train Loss: 0.568, Val f1_micro: 0.304
Epoch: 360, Train Loss: 0.563, Val f1_micro: 0.305
Epoch: 380, Train Loss: 0.552, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.552, Val f1_micro: 0.309
Epoch: 420, Train Loss: 0.528, Val f1_micro: 0.310
Epoch: 440, Train Loss: 0.517, Val f1_micro: 0.310
Epoch: 460, Train Loss: 0.531, Val f1_micro: 0.310
Epoch: 480, Train Loss: 0.520, Val f1_micro: 0.310
Epoch: 500, Train Loss: 0.502, Val f1_micro: 0.313
f1-micro: 0.313, f1-macro: 0.307, f1-weighted: 0.313, , roc-auc: 0.686
##### RUN 2 #####
Epoch: 020, Train Loss: 1.587, Val f1_micro: 0.234
Epoch: 040, Train Loss: 1.321, Val f1_micro: 0.260
Epoch: 060, Train Loss: 1.172, Val f1_micro: 0.269
Epoch: 080, Train Loss: 1.051, Val f1_micro: 0.275
Epoch: 100, Train Loss: 0.980, Val f1_micro: 0.279
Epoch: 120, Train Loss: 0.922, Val f1_micro: 0.284
Epoch: 140, Train Loss: 0.865, Val f1_micro: 0.285
Epoch: 160, Train Loss: 0.834, Val f1_micro: 0.287
Epoch: 180, Train Loss: 0.777, Val f1_micro: 0.292
Epoch: 200, Train Loss: 0.750, Val f1_micro: 0.293
Epoch: 220, Train Loss: 0.719, Val f1_micro: 0.295
Epoch: 240, Train Loss: 0.692, Val f1_micro: 0.299
Epoch: 260, Train Loss: 0.676, Val f1_micro: 0.296
Epoch: 280, Train Loss: 0.634, Val f1_micro: 0.300
Epoch: 300, Train Loss: 0.628, Val f1_micro: 0.299
Epoch: 320, Train Loss: 0.607, Val f1_micro: 0.301
Epoch: 340, Train Loss: 0.592, Val f1_micro: 0.304
Epoch: 360, Train Loss: 0.546, Val f1_micro: 0.304
Epoch: 380, Train Loss: 0.566, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.549, Val f1_micro: 0.304
Epoch: 420, Train Loss: 0.546, Val f1_micro: 0.310
Epoch: 440, Train Loss: 0.537, Val f1_micro: 0.310
Epoch: 460, Train Loss: 0.523, Val f1_micro: 0.307
Epoch: 480, Train Loss: 0.506, Val f1_micro: 0.311
Epoch: 500, Train Loss: 0.515, Val f1_micro: 0.312
f1-micro: 0.312, f1-macro: 0.306, f1-weighted: 0.311, , roc-auc: 0.686
##### RUN 3 #####
Epoch: 020, Train Loss: 1.596, Val f1_micro: 0.230
Epoch: 040, Train Loss: 1.289, Val f1_micro: 0.261
Epoch: 060, Train Loss: 1.159, Val f1_micro: 0.270
Epoch: 080, Train Loss: 1.047, Val f1_micro: 0.273
Epoch: 100, Train Loss: 0.956, Val f1_micro: 0.283
Epoch: 120, Train Loss: 0.915, Val f1_micro: 0.284
Epoch: 140, Train Loss: 0.865, Val f1_micro: 0.284
Epoch: 160, Train Loss: 0.800, Val f1_micro: 0.287
Epoch: 180, Train Loss: 0.782, Val f1_micro: 0.288
Epoch: 200, Train Loss: 0.748, Val f1_micro: 0.288
Epoch: 220, Train Loss: 0.716, Val f1_micro: 0.292
Epoch: 240, Train Loss: 0.679, Val f1_micro: 0.296
Epoch: 260, Train Loss: 0.648, Val f1_micro: 0.297
Epoch: 280, Train Loss: 0.649, Val f1_micro: 0.299
Epoch: 300, Train Loss: 0.611, Val f1_micro: 0.299
Epoch: 320, Train Loss: 0.593, Val f1_micro: 0.303
Epoch: 340, Train Loss: 0.573, Val f1_micro: 0.304
Epoch: 360, Train Loss: 0.595, Val f1_micro: 0.308
Epoch: 380, Train Loss: 0.542, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.539, Val f1_micro: 0.309
Epoch: 420, Train Loss: 0.527, Val f1_micro: 0.306
Epoch: 440, Train Loss: 0.536, Val f1_micro: 0.311
Epoch: 460, Train Loss: 0.505, Val f1_micro: 0.311
Epoch: 480, Train Loss: 0.502, Val f1_micro: 0.310
Epoch: 500, Train Loss: 0.502, Val f1_micro: 0.313
f1-micro: 0.313, f1-macro: 0.307, f1-weighted: 0.313, , roc-auc: 0.685
##### RUN 4 #####
Epoch: 020, Train Loss: 1.593, Val f1_micro: 0.234
Epoch: 040, Train Loss: 1.288, Val f1_micro: 0.259
Epoch: 060, Train Loss: 1.144, Val f1_micro: 0.268
Epoch: 080, Train Loss: 1.042, Val f1_micro: 0.270
Epoch: 100, Train Loss: 0.963, Val f1_micro: 0.278
Epoch: 120, Train Loss: 0.898, Val f1_micro: 0.282
Epoch: 140, Train Loss: 0.850, Val f1_micro: 0.289
Epoch: 160, Train Loss: 0.801, Val f1_micro: 0.289
Epoch: 180, Train Loss: 0.754, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.726, Val f1_micro: 0.288
Epoch: 220, Train Loss: 0.692, Val f1_micro: 0.288
Epoch: 240, Train Loss: 0.684, Val f1_micro: 0.292
Epoch: 260, Train Loss: 0.658, Val f1_micro: 0.294
Epoch: 280, Train Loss: 0.613, Val f1_micro: 0.299
Epoch: 300, Train Loss: 0.600, Val f1_micro: 0.300
Epoch: 320, Train Loss: 0.591, Val f1_micro: 0.302
Epoch: 340, Train Loss: 0.566, Val f1_micro: 0.306
Epoch: 360, Train Loss: 0.579, Val f1_micro: 0.303
Epoch: 380, Train Loss: 0.541, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.540, Val f1_micro: 0.308
Epoch: 420, Train Loss: 0.535, Val f1_micro: 0.310
Epoch: 440, Train Loss: 0.521, Val f1_micro: 0.304
Epoch: 460, Train Loss: 0.522, Val f1_micro: 0.311
Epoch: 480, Train Loss: 0.517, Val f1_micro: 0.307
Epoch: 500, Train Loss: 0.494, Val f1_micro: 0.313
f1-micro: 0.313, f1-macro: 0.307, f1-weighted: 0.313, , roc-auc: 0.682
##### RUN 5 #####
Epoch: 020, Train Loss: 1.586, Val f1_micro: 0.233
Epoch: 040, Train Loss: 1.296, Val f1_micro: 0.260
Epoch: 060, Train Loss: 1.157, Val f1_micro: 0.265
Epoch: 080, Train Loss: 1.064, Val f1_micro: 0.271
Epoch: 100, Train Loss: 0.979, Val f1_micro: 0.273
Epoch: 120, Train Loss: 0.920, Val f1_micro: 0.279
Epoch: 140, Train Loss: 0.841, Val f1_micro: 0.286
Epoch: 160, Train Loss: 0.817, Val f1_micro: 0.286
Epoch: 180, Train Loss: 0.768, Val f1_micro: 0.287
Epoch: 200, Train Loss: 0.744, Val f1_micro: 0.289
Epoch: 220, Train Loss: 0.731, Val f1_micro: 0.295
Epoch: 240, Train Loss: 0.692, Val f1_micro: 0.294
Epoch: 260, Train Loss: 0.654, Val f1_micro: 0.299
Epoch: 280, Train Loss: 0.664, Val f1_micro: 0.300
Epoch: 300, Train Loss: 0.631, Val f1_micro: 0.303
Epoch: 320, Train Loss: 0.608, Val f1_micro: 0.302
Epoch: 340, Train Loss: 0.597, Val f1_micro: 0.305
Epoch: 360, Train Loss: 0.573, Val f1_micro: 0.305
Epoch: 380, Train Loss: 0.554, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.547, Val f1_micro: 0.312
Epoch: 420, Train Loss: 0.566, Val f1_micro: 0.306
Epoch: 440, Train Loss: 0.526, Val f1_micro: 0.312
Epoch: 460, Train Loss: 0.523, Val f1_micro: 0.309
Epoch: 480, Train Loss: 0.511, Val f1_micro: 0.310
Epoch: 500, Train Loss: 0.512, Val f1_micro: 0.310
f1-micro: 0.310, f1-macro: 0.304, f1-weighted: 0.310, , roc-auc: 0.685
########## Hyperparameters combination ##########
(1024, 0.4, 0.01, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.583, Val f1_micro: 0.221
Epoch: 040, Train Loss: 1.356, Val f1_micro: 0.256
Epoch: 060, Train Loss: 1.220, Val f1_micro: 0.264
Epoch: 080, Train Loss: 1.147, Val f1_micro: 0.267
Epoch: 100, Train Loss: 1.087, Val f1_micro: 0.270
Epoch: 120, Train Loss: 1.054, Val f1_micro: 0.277
Epoch: 140, Train Loss: 1.014, Val f1_micro: 0.278
Epoch: 160, Train Loss: 0.982, Val f1_micro: 0.283
Epoch: 180, Train Loss: 0.934, Val f1_micro: 0.282
Epoch: 200, Train Loss: 0.919, Val f1_micro: 0.285
Epoch: 220, Train Loss: 0.909, Val f1_micro: 0.282
Epoch: 240, Train Loss: 0.867, Val f1_micro: 0.286
Epoch: 260, Train Loss: 0.882, Val f1_micro: 0.288
Epoch: 280, Train Loss: 0.861, Val f1_micro: 0.290
Epoch: 300, Train Loss: 0.850, Val f1_micro: 0.295
Epoch: 320, Train Loss: 0.810, Val f1_micro: 0.291
Epoch: 340, Train Loss: 0.815, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.815, Val f1_micro: 0.299
Epoch: 380, Train Loss: 0.812, Val f1_micro: 0.294
Epoch: 400, Train Loss: 0.793, Val f1_micro: 0.298
Epoch: 420, Train Loss: 0.790, Val f1_micro: 0.299
Epoch: 440, Train Loss: 0.773, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.767, Val f1_micro: 0.301
Epoch: 480, Train Loss: 0.778, Val f1_micro: 0.301
Epoch: 500, Train Loss: 0.773, Val f1_micro: 0.300
f1-micro: 0.300, f1-macro: 0.294, f1-weighted: 0.299, , roc-auc: 0.685
##### RUN 2 #####
Epoch: 020, Train Loss: 1.600, Val f1_micro: 0.224
Epoch: 040, Train Loss: 1.352, Val f1_micro: 0.253
Epoch: 060, Train Loss: 1.244, Val f1_micro: 0.262
Epoch: 080, Train Loss: 1.173, Val f1_micro: 0.266
Epoch: 100, Train Loss: 1.081, Val f1_micro: 0.271
Epoch: 120, Train Loss: 1.054, Val f1_micro: 0.273
Epoch: 140, Train Loss: 1.002, Val f1_micro: 0.276
Epoch: 160, Train Loss: 0.982, Val f1_micro: 0.282
Epoch: 180, Train Loss: 0.945, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.936, Val f1_micro: 0.286
Epoch: 220, Train Loss: 0.902, Val f1_micro: 0.286
Epoch: 240, Train Loss: 0.895, Val f1_micro: 0.290
Epoch: 260, Train Loss: 0.863, Val f1_micro: 0.286
Epoch: 280, Train Loss: 0.870, Val f1_micro: 0.292
Epoch: 300, Train Loss: 0.861, Val f1_micro: 0.295
Epoch: 320, Train Loss: 0.827, Val f1_micro: 0.293
Epoch: 340, Train Loss: 0.827, Val f1_micro: 0.290
Epoch: 360, Train Loss: 0.801, Val f1_micro: 0.299
Epoch: 380, Train Loss: 0.780, Val f1_micro: 0.296
Epoch: 400, Train Loss: 0.808, Val f1_micro: 0.300
Epoch: 420, Train Loss: 0.798, Val f1_micro: 0.297
Epoch: 440, Train Loss: 0.794, Val f1_micro: 0.299
Epoch: 460, Train Loss: 0.774, Val f1_micro: 0.302
Epoch: 480, Train Loss: 0.765, Val f1_micro: 0.295
Epoch: 500, Train Loss: 0.766, Val f1_micro: 0.298
f1-micro: 0.298, f1-macro: 0.291, f1-weighted: 0.295, , roc-auc: 0.685
##### RUN 3 #####
Epoch: 020, Train Loss: 1.620, Val f1_micro: 0.218
Epoch: 040, Train Loss: 1.348, Val f1_micro: 0.255
Epoch: 060, Train Loss: 1.225, Val f1_micro: 0.258
Epoch: 080, Train Loss: 1.148, Val f1_micro: 0.268
Epoch: 100, Train Loss: 1.091, Val f1_micro: 0.268
Epoch: 120, Train Loss: 1.035, Val f1_micro: 0.273
Epoch: 140, Train Loss: 1.006, Val f1_micro: 0.281
Epoch: 160, Train Loss: 0.987, Val f1_micro: 0.278
Epoch: 180, Train Loss: 0.948, Val f1_micro: 0.279
Epoch: 200, Train Loss: 0.941, Val f1_micro: 0.280
Epoch: 220, Train Loss: 0.913, Val f1_micro: 0.286
Epoch: 240, Train Loss: 0.883, Val f1_micro: 0.283
Epoch: 260, Train Loss: 0.896, Val f1_micro: 0.288
Epoch: 280, Train Loss: 0.848, Val f1_micro: 0.286
Epoch: 300, Train Loss: 0.869, Val f1_micro: 0.292
Epoch: 320, Train Loss: 0.844, Val f1_micro: 0.290
Epoch: 340, Train Loss: 0.823, Val f1_micro: 0.296
Epoch: 360, Train Loss: 0.823, Val f1_micro: 0.298
Epoch: 380, Train Loss: 0.798, Val f1_micro: 0.295
Epoch: 400, Train Loss: 0.802, Val f1_micro: 0.298
Epoch: 420, Train Loss: 0.801, Val f1_micro: 0.299
Epoch: 440, Train Loss: 0.794, Val f1_micro: 0.297
Epoch: 460, Train Loss: 0.785, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.759, Val f1_micro: 0.302
Epoch: 500, Train Loss: 0.779, Val f1_micro: 0.303
f1-micro: 0.303, f1-macro: 0.295, f1-weighted: 0.300, , roc-auc: 0.684
##### RUN 4 #####
Epoch: 020, Train Loss: 1.586, Val f1_micro: 0.220
Epoch: 040, Train Loss: 1.337, Val f1_micro: 0.256
Epoch: 060, Train Loss: 1.214, Val f1_micro: 0.263
Epoch: 080, Train Loss: 1.155, Val f1_micro: 0.265
Epoch: 100, Train Loss: 1.077, Val f1_micro: 0.274
Epoch: 120, Train Loss: 1.054, Val f1_micro: 0.271
Epoch: 140, Train Loss: 0.999, Val f1_micro: 0.275
Epoch: 160, Train Loss: 0.977, Val f1_micro: 0.279
Epoch: 180, Train Loss: 0.951, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.921, Val f1_micro: 0.285
Epoch: 220, Train Loss: 0.901, Val f1_micro: 0.287
Epoch: 240, Train Loss: 0.866, Val f1_micro: 0.292
Epoch: 260, Train Loss: 0.858, Val f1_micro: 0.289
Epoch: 280, Train Loss: 0.843, Val f1_micro: 0.290
Epoch: 300, Train Loss: 0.844, Val f1_micro: 0.295
Epoch: 320, Train Loss: 0.820, Val f1_micro: 0.298
Epoch: 340, Train Loss: 0.820, Val f1_micro: 0.295
Epoch: 360, Train Loss: 0.814, Val f1_micro: 0.293
Epoch: 380, Train Loss: 0.787, Val f1_micro: 0.295
Epoch: 400, Train Loss: 0.804, Val f1_micro: 0.295
Epoch: 420, Train Loss: 0.776, Val f1_micro: 0.300
Epoch: 440, Train Loss: 0.775, Val f1_micro: 0.302
Epoch: 460, Train Loss: 0.779, Val f1_micro: 0.303
Epoch: 480, Train Loss: 0.777, Val f1_micro: 0.300
Epoch: 500, Train Loss: 0.760, Val f1_micro: 0.303
f1-micro: 0.303, f1-macro: 0.296, f1-weighted: 0.300, , roc-auc: 0.684
##### RUN 5 #####
Epoch: 020, Train Loss: 1.596, Val f1_micro: 0.221
Epoch: 040, Train Loss: 1.345, Val f1_micro: 0.255
Epoch: 060, Train Loss: 1.236, Val f1_micro: 0.261
Epoch: 080, Train Loss: 1.155, Val f1_micro: 0.270
Epoch: 100, Train Loss: 1.089, Val f1_micro: 0.276
Epoch: 120, Train Loss: 1.043, Val f1_micro: 0.273
Epoch: 140, Train Loss: 1.009, Val f1_micro: 0.280
Epoch: 160, Train Loss: 0.965, Val f1_micro: 0.276
Epoch: 180, Train Loss: 0.943, Val f1_micro: 0.281
Epoch: 200, Train Loss: 0.933, Val f1_micro: 0.286
Epoch: 220, Train Loss: 0.884, Val f1_micro: 0.283
Epoch: 240, Train Loss: 0.896, Val f1_micro: 0.291
Epoch: 260, Train Loss: 0.865, Val f1_micro: 0.292
Epoch: 280, Train Loss: 0.867, Val f1_micro: 0.292
Epoch: 300, Train Loss: 0.850, Val f1_micro: 0.293
Epoch: 320, Train Loss: 0.836, Val f1_micro: 0.291
Epoch: 340, Train Loss: 0.826, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.810, Val f1_micro: 0.298
Epoch: 380, Train Loss: 0.802, Val f1_micro: 0.295
Epoch: 400, Train Loss: 0.787, Val f1_micro: 0.298
Epoch: 420, Train Loss: 0.780, Val f1_micro: 0.296
Epoch: 440, Train Loss: 0.785, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.770, Val f1_micro: 0.301
Epoch: 480, Train Loss: 0.753, Val f1_micro: 0.301
Epoch: 500, Train Loss: 0.761, Val f1_micro: 0.298
f1-micro: 0.298, f1-macro: 0.290, f1-weighted: 0.295, , roc-auc: 0.685
########## Hyperparameters combination ##########
(1024, 0.4, 0.01, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.705, Val f1_micro: 0.228
Epoch: 040, Train Loss: 1.600, Val f1_micro: 0.234
Epoch: 060, Train Loss: 1.575, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.584, Val f1_micro: 0.233
Epoch: 100, Train Loss: 1.579, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.592, Val f1_micro: 0.229
Epoch: 140, Train Loss: 1.581, Val f1_micro: 0.232
Epoch: 160, Train Loss: 1.601, Val f1_micro: 0.221
Epoch: 180, Train Loss: 1.589, Val f1_micro: 0.232
Epoch: 200, Train Loss: 1.590, Val f1_micro: 0.223
Epoch: 220, Train Loss: 1.601, Val f1_micro: 0.227
Epoch: 240, Train Loss: 1.598, Val f1_micro: 0.228
Epoch: 260, Train Loss: 1.591, Val f1_micro: 0.227
Epoch: 280, Train Loss: 1.595, Val f1_micro: 0.233
Epoch: 300, Train Loss: 1.595, Val f1_micro: 0.234
Epoch: 320, Train Loss: 1.586, Val f1_micro: 0.221
Epoch: 340, Train Loss: 1.596, Val f1_micro: 0.226
Epoch: 360, Train Loss: 1.582, Val f1_micro: 0.229
Epoch: 380, Train Loss: 1.591, Val f1_micro: 0.227
Epoch: 400, Train Loss: 1.582, Val f1_micro: 0.228
Epoch: 420, Train Loss: 1.585, Val f1_micro: 0.233
Epoch: 440, Train Loss: 1.589, Val f1_micro: 0.229
Epoch: 460, Train Loss: 1.588, Val f1_micro: 0.231
Epoch: 480, Train Loss: 1.587, Val f1_micro: 0.231
Epoch: 500, Train Loss: 1.586, Val f1_micro: 0.231
f1-micro: 0.231, f1-macro: 0.201, f1-weighted: 0.201, , roc-auc: 0.651
##### RUN 2 #####
Epoch: 020, Train Loss: 1.712, Val f1_micro: 0.223
Epoch: 040, Train Loss: 1.614, Val f1_micro: 0.232
Epoch: 060, Train Loss: 1.577, Val f1_micro: 0.231
Epoch: 080, Train Loss: 1.577, Val f1_micro: 0.224
Epoch: 100, Train Loss: 1.588, Val f1_micro: 0.229
Epoch: 120, Train Loss: 1.599, Val f1_micro: 0.228
Epoch: 140, Train Loss: 1.588, Val f1_micro: 0.226
Epoch: 160, Train Loss: 1.600, Val f1_micro: 0.228
Epoch: 180, Train Loss: 1.599, Val f1_micro: 0.230
Epoch: 200, Train Loss: 1.601, Val f1_micro: 0.225
Epoch: 220, Train Loss: 1.592, Val f1_micro: 0.226
Epoch: 240, Train Loss: 1.593, Val f1_micro: 0.228
Epoch: 260, Train Loss: 1.600, Val f1_micro: 0.231
Epoch: 280, Train Loss: 1.595, Val f1_micro: 0.232
Epoch: 300, Train Loss: 1.594, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.590, Val f1_micro: 0.229
Epoch: 340, Train Loss: 1.591, Val f1_micro: 0.232
Epoch: 360, Train Loss: 1.568, Val f1_micro: 0.228
Epoch: 380, Train Loss: 1.574, Val f1_micro: 0.228
Epoch: 400, Train Loss: 1.572, Val f1_micro: 0.231
Epoch: 420, Train Loss: 1.573, Val f1_micro: 0.225
Epoch: 440, Train Loss: 1.585, Val f1_micro: 0.225
Epoch: 460, Train Loss: 1.590, Val f1_micro: 0.229
Epoch: 480, Train Loss: 1.565, Val f1_micro: 0.226
Epoch: 500, Train Loss: 1.572, Val f1_micro: 0.229
f1-micro: 0.229, f1-macro: 0.200, f1-weighted: 0.197, , roc-auc: 0.651
##### RUN 3 #####
Epoch: 020, Train Loss: 1.712, Val f1_micro: 0.223
Epoch: 040, Train Loss: 1.606, Val f1_micro: 0.240
Epoch: 060, Train Loss: 1.578, Val f1_micro: 0.233
Epoch: 080, Train Loss: 1.588, Val f1_micro: 0.233
Epoch: 100, Train Loss: 1.593, Val f1_micro: 0.229
Epoch: 120, Train Loss: 1.583, Val f1_micro: 0.229
Epoch: 140, Train Loss: 1.596, Val f1_micro: 0.228
Epoch: 160, Train Loss: 1.589, Val f1_micro: 0.227
Epoch: 180, Train Loss: 1.589, Val f1_micro: 0.226
Epoch: 200, Train Loss: 1.602, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.589, Val f1_micro: 0.221
Epoch: 240, Train Loss: 1.605, Val f1_micro: 0.225
Epoch: 260, Train Loss: 1.590, Val f1_micro: 0.226
Epoch: 280, Train Loss: 1.596, Val f1_micro: 0.222
Epoch: 300, Train Loss: 1.594, Val f1_micro: 0.225
Epoch: 320, Train Loss: 1.592, Val f1_micro: 0.228
Epoch: 340, Train Loss: 1.581, Val f1_micro: 0.231
Epoch: 360, Train Loss: 1.588, Val f1_micro: 0.230
Epoch: 380, Train Loss: 1.576, Val f1_micro: 0.230
Epoch: 400, Train Loss: 1.589, Val f1_micro: 0.230
Epoch: 420, Train Loss: 1.577, Val f1_micro: 0.232
Epoch: 440, Train Loss: 1.591, Val f1_micro: 0.229
Epoch: 460, Train Loss: 1.585, Val f1_micro: 0.231
Epoch: 480, Train Loss: 1.579, Val f1_micro: 0.227
Epoch: 500, Train Loss: 1.568, Val f1_micro: 0.227
f1-micro: 0.227, f1-macro: 0.188, f1-weighted: 0.186, , roc-auc: 0.652
##### RUN 4 #####
Epoch: 020, Train Loss: 1.707, Val f1_micro: 0.229
Epoch: 040, Train Loss: 1.598, Val f1_micro: 0.233
Epoch: 060, Train Loss: 1.584, Val f1_micro: 0.232
Epoch: 080, Train Loss: 1.594, Val f1_micro: 0.229
Epoch: 100, Train Loss: 1.591, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.592, Val f1_micro: 0.227
Epoch: 140, Train Loss: 1.593, Val f1_micro: 0.228
Epoch: 160, Train Loss: 1.597, Val f1_micro: 0.229
Epoch: 180, Train Loss: 1.602, Val f1_micro: 0.225
Epoch: 200, Train Loss: 1.596, Val f1_micro: 0.219
Epoch: 220, Train Loss: 1.600, Val f1_micro: 0.228
Epoch: 240, Train Loss: 1.595, Val f1_micro: 0.224
Epoch: 260, Train Loss: 1.599, Val f1_micro: 0.225
Epoch: 280, Train Loss: 1.589, Val f1_micro: 0.231
Epoch: 300, Train Loss: 1.596, Val f1_micro: 0.228
Epoch: 320, Train Loss: 1.588, Val f1_micro: 0.231
Epoch: 340, Train Loss: 1.583, Val f1_micro: 0.229
Epoch: 360, Train Loss: 1.590, Val f1_micro: 0.231
Epoch: 380, Train Loss: 1.596, Val f1_micro: 0.229
Epoch: 400, Train Loss: 1.572, Val f1_micro: 0.234
Epoch: 420, Train Loss: 1.581, Val f1_micro: 0.228
Epoch: 440, Train Loss: 1.573, Val f1_micro: 0.227
Epoch: 460, Train Loss: 1.587, Val f1_micro: 0.233
Epoch: 480, Train Loss: 1.575, Val f1_micro: 0.234
Epoch: 500, Train Loss: 1.580, Val f1_micro: 0.231
f1-micro: 0.231, f1-macro: 0.200, f1-weighted: 0.200, , roc-auc: 0.651
##### RUN 5 #####
Epoch: 020, Train Loss: 1.711, Val f1_micro: 0.228
Epoch: 040, Train Loss: 1.588, Val f1_micro: 0.235
Epoch: 060, Train Loss: 1.584, Val f1_micro: 0.241
Epoch: 080, Train Loss: 1.590, Val f1_micro: 0.224
Epoch: 100, Train Loss: 1.590, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.589, Val f1_micro: 0.228
Epoch: 140, Train Loss: 1.595, Val f1_micro: 0.229
Epoch: 160, Train Loss: 1.596, Val f1_micro: 0.224
Epoch: 180, Train Loss: 1.603, Val f1_micro: 0.233
Epoch: 200, Train Loss: 1.589, Val f1_micro: 0.223
Epoch: 220, Train Loss: 1.594, Val f1_micro: 0.232
Epoch: 240, Train Loss: 1.586, Val f1_micro: 0.233
Epoch: 260, Train Loss: 1.604, Val f1_micro: 0.225
Epoch: 280, Train Loss: 1.592, Val f1_micro: 0.230
Epoch: 300, Train Loss: 1.586, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.599, Val f1_micro: 0.237
Epoch: 340, Train Loss: 1.599, Val f1_micro: 0.233
Epoch: 360, Train Loss: 1.584, Val f1_micro: 0.221
Epoch: 380, Train Loss: 1.596, Val f1_micro: 0.221
Epoch: 400, Train Loss: 1.591, Val f1_micro: 0.229
Epoch: 420, Train Loss: 1.573, Val f1_micro: 0.227
Epoch: 440, Train Loss: 1.584, Val f1_micro: 0.223
Epoch: 460, Train Loss: 1.566, Val f1_micro: 0.231
Epoch: 480, Train Loss: 1.575, Val f1_micro: 0.227
Epoch: 500, Train Loss: 1.585, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.200, f1-weighted: 0.197, , roc-auc: 0.651
########## Hyperparameters combination ##########
(1024, 0.4, 0.05, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.983, Val f1_micro: 0.109
Epoch: 040, Train Loss: 1.844, Val f1_micro: 0.177
Epoch: 060, Train Loss: 1.702, Val f1_micro: 0.146
Epoch: 080, Train Loss: 1.594, Val f1_micro: 0.164
Epoch: 100, Train Loss: 1.455, Val f1_micro: 0.203
Epoch: 120, Train Loss: 1.334, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.262, Val f1_micro: 0.223
Epoch: 160, Train Loss: 1.136, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.033, Val f1_micro: 0.242
Epoch: 200, Train Loss: 0.965, Val f1_micro: 0.257
Epoch: 220, Train Loss: 0.894, Val f1_micro: 0.263
Epoch: 240, Train Loss: 0.800, Val f1_micro: 0.273
Epoch: 260, Train Loss: 0.752, Val f1_micro: 0.270
Epoch: 280, Train Loss: 0.743, Val f1_micro: 0.276
Epoch: 300, Train Loss: 0.676, Val f1_micro: 0.282
Epoch: 320, Train Loss: 0.630, Val f1_micro: 0.283
Epoch: 340, Train Loss: 0.609, Val f1_micro: 0.284
Epoch: 360, Train Loss: 0.582, Val f1_micro: 0.289
Epoch: 380, Train Loss: 0.541, Val f1_micro: 0.291
Epoch: 400, Train Loss: 0.562, Val f1_micro: 0.294
Epoch: 420, Train Loss: 0.544, Val f1_micro: 0.300
Epoch: 440, Train Loss: 0.499, Val f1_micro: 0.296
Epoch: 460, Train Loss: 0.486, Val f1_micro: 0.293
Epoch: 480, Train Loss: 0.450, Val f1_micro: 0.293
Epoch: 500, Train Loss: 0.453, Val f1_micro: 0.292
f1-micro: 0.292, f1-macro: 0.288, f1-weighted: 0.294, , roc-auc: 0.668
##### RUN 2 #####
Epoch: 020, Train Loss: 2.001, Val f1_micro: 0.104
Epoch: 040, Train Loss: 1.881, Val f1_micro: 0.175
Epoch: 060, Train Loss: 1.741, Val f1_micro: 0.144
Epoch: 080, Train Loss: 1.627, Val f1_micro: 0.155
Epoch: 100, Train Loss: 1.509, Val f1_micro: 0.183
Epoch: 120, Train Loss: 1.395, Val f1_micro: 0.202
Epoch: 140, Train Loss: 1.288, Val f1_micro: 0.214
Epoch: 160, Train Loss: 1.150, Val f1_micro: 0.239
Epoch: 180, Train Loss: 1.062, Val f1_micro: 0.246
Epoch: 200, Train Loss: 0.973, Val f1_micro: 0.265
Epoch: 220, Train Loss: 0.901, Val f1_micro: 0.275
Epoch: 240, Train Loss: 0.833, Val f1_micro: 0.276
Epoch: 260, Train Loss: 0.774, Val f1_micro: 0.277
Epoch: 280, Train Loss: 0.774, Val f1_micro: 0.287
Epoch: 300, Train Loss: 0.683, Val f1_micro: 0.287
Epoch: 320, Train Loss: 0.654, Val f1_micro: 0.290
Epoch: 340, Train Loss: 0.635, Val f1_micro: 0.293
Epoch: 360, Train Loss: 0.583, Val f1_micro: 0.295
Epoch: 380, Train Loss: 0.543, Val f1_micro: 0.299
Epoch: 400, Train Loss: 0.531, Val f1_micro: 0.296
Epoch: 420, Train Loss: 0.539, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.491, Val f1_micro: 0.305
Epoch: 460, Train Loss: 0.488, Val f1_micro: 0.306
Epoch: 480, Train Loss: 0.435, Val f1_micro: 0.308
Epoch: 500, Train Loss: 0.426, Val f1_micro: 0.310
f1-micro: 0.310, f1-macro: 0.303, f1-weighted: 0.309, , roc-auc: 0.666
##### RUN 3 #####
Epoch: 020, Train Loss: 2.022, Val f1_micro: 0.101
Epoch: 040, Train Loss: 1.867, Val f1_micro: 0.178
Epoch: 060, Train Loss: 1.761, Val f1_micro: 0.140
Epoch: 080, Train Loss: 1.640, Val f1_micro: 0.153
Epoch: 100, Train Loss: 1.530, Val f1_micro: 0.184
Epoch: 120, Train Loss: 1.427, Val f1_micro: 0.200
Epoch: 140, Train Loss: 1.331, Val f1_micro: 0.216
Epoch: 160, Train Loss: 1.183, Val f1_micro: 0.221
Epoch: 180, Train Loss: 1.085, Val f1_micro: 0.240
Epoch: 200, Train Loss: 1.009, Val f1_micro: 0.250
Epoch: 220, Train Loss: 0.904, Val f1_micro: 0.265
Epoch: 240, Train Loss: 0.823, Val f1_micro: 0.268
Epoch: 260, Train Loss: 0.747, Val f1_micro: 0.276
Epoch: 280, Train Loss: 0.716, Val f1_micro: 0.275
Epoch: 300, Train Loss: 0.666, Val f1_micro: 0.274
Epoch: 320, Train Loss: 0.615, Val f1_micro: 0.287
Epoch: 340, Train Loss: 0.590, Val f1_micro: 0.287
Epoch: 360, Train Loss: 0.528, Val f1_micro: 0.290
Epoch: 380, Train Loss: 0.541, Val f1_micro: 0.286
Epoch: 400, Train Loss: 0.494, Val f1_micro: 0.293
Epoch: 420, Train Loss: 0.486, Val f1_micro: 0.295
Epoch: 440, Train Loss: 0.485, Val f1_micro: 0.296
Epoch: 460, Train Loss: 0.474, Val f1_micro: 0.293
Epoch: 480, Train Loss: 0.450, Val f1_micro: 0.296
Epoch: 500, Train Loss: 0.451, Val f1_micro: 0.298
f1-micro: 0.298, f1-macro: 0.292, f1-weighted: 0.298, , roc-auc: 0.669
##### RUN 4 #####
Epoch: 020, Train Loss: 2.013, Val f1_micro: 0.099
Epoch: 040, Train Loss: 1.895, Val f1_micro: 0.178
Epoch: 060, Train Loss: 1.782, Val f1_micro: 0.144
Epoch: 080, Train Loss: 1.673, Val f1_micro: 0.160
Epoch: 100, Train Loss: 1.510, Val f1_micro: 0.205
Epoch: 120, Train Loss: 1.370, Val f1_micro: 0.217
Epoch: 140, Train Loss: 1.282, Val f1_micro: 0.226
Epoch: 160, Train Loss: 1.219, Val f1_micro: 0.227
Epoch: 180, Train Loss: 1.078, Val f1_micro: 0.243
Epoch: 200, Train Loss: 1.011, Val f1_micro: 0.250
Epoch: 220, Train Loss: 0.961, Val f1_micro: 0.254
Epoch: 240, Train Loss: 0.861, Val f1_micro: 0.265
Epoch: 260, Train Loss: 0.809, Val f1_micro: 0.265
Epoch: 280, Train Loss: 0.767, Val f1_micro: 0.278
Epoch: 300, Train Loss: 0.698, Val f1_micro: 0.282
Epoch: 320, Train Loss: 0.665, Val f1_micro: 0.286
Epoch: 340, Train Loss: 0.610, Val f1_micro: 0.284
Epoch: 360, Train Loss: 0.590, Val f1_micro: 0.290
Epoch: 380, Train Loss: 0.565, Val f1_micro: 0.287
Epoch: 400, Train Loss: 0.571, Val f1_micro: 0.295
Epoch: 420, Train Loss: 0.528, Val f1_micro: 0.290
Epoch: 440, Train Loss: 0.511, Val f1_micro: 0.290
Epoch: 460, Train Loss: 0.517, Val f1_micro: 0.294
Epoch: 480, Train Loss: 0.495, Val f1_micro: 0.293
Epoch: 500, Train Loss: 0.467, Val f1_micro: 0.294
f1-micro: 0.294, f1-macro: 0.291, f1-weighted: 0.298, , roc-auc: 0.667
##### RUN 5 #####
Epoch: 020, Train Loss: 1.994, Val f1_micro: 0.106
Epoch: 040, Train Loss: 1.849, Val f1_micro: 0.182
Epoch: 060, Train Loss: 1.724, Val f1_micro: 0.148
Epoch: 080, Train Loss: 1.569, Val f1_micro: 0.174
Epoch: 100, Train Loss: 1.454, Val f1_micro: 0.219
Epoch: 120, Train Loss: 1.329, Val f1_micro: 0.235
Epoch: 140, Train Loss: 1.197, Val f1_micro: 0.240
Epoch: 160, Train Loss: 1.066, Val f1_micro: 0.254
Epoch: 180, Train Loss: 0.956, Val f1_micro: 0.263
Epoch: 200, Train Loss: 0.937, Val f1_micro: 0.266
Epoch: 220, Train Loss: 0.839, Val f1_micro: 0.274
Epoch: 240, Train Loss: 0.819, Val f1_micro: 0.278
Epoch: 260, Train Loss: 0.742, Val f1_micro: 0.282
Epoch: 280, Train Loss: 0.699, Val f1_micro: 0.285
Epoch: 300, Train Loss: 0.612, Val f1_micro: 0.288
Epoch: 320, Train Loss: 0.619, Val f1_micro: 0.292
Epoch: 340, Train Loss: 0.563, Val f1_micro: 0.296
Epoch: 360, Train Loss: 0.536, Val f1_micro: 0.295
Epoch: 380, Train Loss: 0.543, Val f1_micro: 0.296
Epoch: 400, Train Loss: 0.506, Val f1_micro: 0.300
Epoch: 420, Train Loss: 0.482, Val f1_micro: 0.304
Epoch: 440, Train Loss: 0.470, Val f1_micro: 0.300
Epoch: 460, Train Loss: 0.444, Val f1_micro: 0.303
Epoch: 480, Train Loss: 0.440, Val f1_micro: 0.303
Epoch: 500, Train Loss: 0.433, Val f1_micro: 0.299
f1-micro: 0.299, f1-macro: 0.296, f1-weighted: 0.301, , roc-auc: 0.662
########## Hyperparameters combination ##########
(1024, 0.4, 0.05, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.025, Val f1_micro: 0.106
Epoch: 040, Train Loss: 1.927, Val f1_micro: 0.173
Epoch: 060, Train Loss: 1.823, Val f1_micro: 0.149
Epoch: 080, Train Loss: 1.721, Val f1_micro: 0.174
Epoch: 100, Train Loss: 1.615, Val f1_micro: 0.184
Epoch: 120, Train Loss: 1.488, Val f1_micro: 0.206
Epoch: 140, Train Loss: 1.372, Val f1_micro: 0.238
Epoch: 160, Train Loss: 1.302, Val f1_micro: 0.239
Epoch: 180, Train Loss: 1.225, Val f1_micro: 0.244
Epoch: 200, Train Loss: 1.164, Val f1_micro: 0.248
Epoch: 220, Train Loss: 1.109, Val f1_micro: 0.256
Epoch: 240, Train Loss: 1.108, Val f1_micro: 0.254
Epoch: 260, Train Loss: 1.062, Val f1_micro: 0.246
Epoch: 280, Train Loss: 1.017, Val f1_micro: 0.260
Epoch: 300, Train Loss: 0.958, Val f1_micro: 0.272
Epoch: 320, Train Loss: 0.983, Val f1_micro: 0.267
Epoch: 340, Train Loss: 0.949, Val f1_micro: 0.269
Epoch: 360, Train Loss: 0.924, Val f1_micro: 0.273
Epoch: 380, Train Loss: 0.927, Val f1_micro: 0.274
Epoch: 400, Train Loss: 0.906, Val f1_micro: 0.269
Epoch: 420, Train Loss: 0.897, Val f1_micro: 0.261
Epoch: 440, Train Loss: 0.941, Val f1_micro: 0.261
Epoch: 460, Train Loss: 0.874, Val f1_micro: 0.285
Epoch: 480, Train Loss: 0.847, Val f1_micro: 0.273
Epoch: 500, Train Loss: 0.839, Val f1_micro: 0.277
f1-micro: 0.277, f1-macro: 0.272, f1-weighted: 0.275, , roc-auc: 0.670
##### RUN 2 #####
Epoch: 020, Train Loss: 2.025, Val f1_micro: 0.100
Epoch: 040, Train Loss: 1.911, Val f1_micro: 0.177
Epoch: 060, Train Loss: 1.748, Val f1_micro: 0.193
Epoch: 080, Train Loss: 1.661, Val f1_micro: 0.194
Epoch: 100, Train Loss: 1.562, Val f1_micro: 0.198
Epoch: 120, Train Loss: 1.451, Val f1_micro: 0.209
Epoch: 140, Train Loss: 1.384, Val f1_micro: 0.209
Epoch: 160, Train Loss: 1.319, Val f1_micro: 0.237
Epoch: 180, Train Loss: 1.261, Val f1_micro: 0.232
Epoch: 200, Train Loss: 1.191, Val f1_micro: 0.244
Epoch: 220, Train Loss: 1.118, Val f1_micro: 0.245
Epoch: 240, Train Loss: 1.076, Val f1_micro: 0.256
Epoch: 260, Train Loss: 1.072, Val f1_micro: 0.256
Epoch: 280, Train Loss: 1.055, Val f1_micro: 0.258
Epoch: 300, Train Loss: 0.999, Val f1_micro: 0.261
Epoch: 320, Train Loss: 0.969, Val f1_micro: 0.264
Epoch: 340, Train Loss: 0.986, Val f1_micro: 0.256
Epoch: 360, Train Loss: 0.940, Val f1_micro: 0.272
Epoch: 380, Train Loss: 0.908, Val f1_micro: 0.277
Epoch: 400, Train Loss: 0.849, Val f1_micro: 0.274
Epoch: 420, Train Loss: 0.870, Val f1_micro: 0.269
Epoch: 440, Train Loss: 0.846, Val f1_micro: 0.271
Epoch: 460, Train Loss: 0.863, Val f1_micro: 0.271
Epoch: 480, Train Loss: 0.818, Val f1_micro: 0.277
Epoch: 500, Train Loss: 0.804, Val f1_micro: 0.279
f1-micro: 0.279, f1-macro: 0.274, f1-weighted: 0.277, , roc-auc: 0.664
##### RUN 3 #####
Epoch: 020, Train Loss: 2.020, Val f1_micro: 0.103
Epoch: 040, Train Loss: 1.903, Val f1_micro: 0.176
Epoch: 060, Train Loss: 1.835, Val f1_micro: 0.163
Epoch: 080, Train Loss: 1.736, Val f1_micro: 0.158
Epoch: 100, Train Loss: 1.684, Val f1_micro: 0.190
Epoch: 120, Train Loss: 1.584, Val f1_micro: 0.193
Epoch: 140, Train Loss: 1.492, Val f1_micro: 0.204
Epoch: 160, Train Loss: 1.428, Val f1_micro: 0.216
Epoch: 180, Train Loss: 1.338, Val f1_micro: 0.227
Epoch: 200, Train Loss: 1.259, Val f1_micro: 0.228
Epoch: 220, Train Loss: 1.245, Val f1_micro: 0.223
Epoch: 240, Train Loss: 1.171, Val f1_micro: 0.246
Epoch: 260, Train Loss: 1.186, Val f1_micro: 0.243
Epoch: 280, Train Loss: 1.111, Val f1_micro: 0.254
Epoch: 300, Train Loss: 1.059, Val f1_micro: 0.250
Epoch: 320, Train Loss: 1.030, Val f1_micro: 0.262
Epoch: 340, Train Loss: 0.984, Val f1_micro: 0.263
Epoch: 360, Train Loss: 0.993, Val f1_micro: 0.267
Epoch: 380, Train Loss: 0.951, Val f1_micro: 0.266
Epoch: 400, Train Loss: 0.921, Val f1_micro: 0.270
Epoch: 420, Train Loss: 0.889, Val f1_micro: 0.274
Epoch: 440, Train Loss: 0.885, Val f1_micro: 0.278
Epoch: 460, Train Loss: 0.895, Val f1_micro: 0.274
Epoch: 480, Train Loss: 0.842, Val f1_micro: 0.279
Epoch: 500, Train Loss: 0.826, Val f1_micro: 0.275
f1-micro: 0.275, f1-macro: 0.267, f1-weighted: 0.269, , roc-auc: 0.667
##### RUN 4 #####
Epoch: 020, Train Loss: 2.027, Val f1_micro: 0.104
Epoch: 040, Train Loss: 1.929, Val f1_micro: 0.175
Epoch: 060, Train Loss: 1.835, Val f1_micro: 0.140
Epoch: 080, Train Loss: 1.732, Val f1_micro: 0.155
Epoch: 100, Train Loss: 1.630, Val f1_micro: 0.168
Epoch: 120, Train Loss: 1.487, Val f1_micro: 0.205
Epoch: 140, Train Loss: 1.365, Val f1_micro: 0.223
Epoch: 160, Train Loss: 1.324, Val f1_micro: 0.233
Epoch: 180, Train Loss: 1.205, Val f1_micro: 0.239
Epoch: 200, Train Loss: 1.148, Val f1_micro: 0.243
Epoch: 220, Train Loss: 1.076, Val f1_micro: 0.251
Epoch: 240, Train Loss: 1.052, Val f1_micro: 0.247
Epoch: 260, Train Loss: 1.016, Val f1_micro: 0.261
Epoch: 280, Train Loss: 1.006, Val f1_micro: 0.261
Epoch: 300, Train Loss: 0.942, Val f1_micro: 0.274
Epoch: 320, Train Loss: 0.933, Val f1_micro: 0.274
Epoch: 340, Train Loss: 0.906, Val f1_micro: 0.265
Epoch: 360, Train Loss: 0.930, Val f1_micro: 0.259
Epoch: 380, Train Loss: 0.855, Val f1_micro: 0.279
Epoch: 400, Train Loss: 0.832, Val f1_micro: 0.276
Epoch: 420, Train Loss: 0.818, Val f1_micro: 0.285
Epoch: 440, Train Loss: 0.821, Val f1_micro: 0.270
Epoch: 460, Train Loss: 0.793, Val f1_micro: 0.283
Epoch: 480, Train Loss: 0.770, Val f1_micro: 0.284
Epoch: 500, Train Loss: 0.772, Val f1_micro: 0.289
f1-micro: 0.289, f1-macro: 0.284, f1-weighted: 0.287, , roc-auc: 0.668
##### RUN 5 #####
Epoch: 020, Train Loss: 2.021, Val f1_micro: 0.102
Epoch: 040, Train Loss: 1.912, Val f1_micro: 0.174
Epoch: 060, Train Loss: 1.790, Val f1_micro: 0.164
Epoch: 080, Train Loss: 1.636, Val f1_micro: 0.203
Epoch: 100, Train Loss: 1.507, Val f1_micro: 0.209
Epoch: 120, Train Loss: 1.440, Val f1_micro: 0.224
Epoch: 140, Train Loss: 1.346, Val f1_micro: 0.227
Epoch: 160, Train Loss: 1.269, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.240, Val f1_micro: 0.241
Epoch: 200, Train Loss: 1.175, Val f1_micro: 0.245
Epoch: 220, Train Loss: 1.125, Val f1_micro: 0.251
Epoch: 240, Train Loss: 1.065, Val f1_micro: 0.258
Epoch: 260, Train Loss: 1.047, Val f1_micro: 0.254
Epoch: 280, Train Loss: 0.987, Val f1_micro: 0.255
Epoch: 300, Train Loss: 0.954, Val f1_micro: 0.268
Epoch: 320, Train Loss: 0.927, Val f1_micro: 0.267
Epoch: 340, Train Loss: 0.975, Val f1_micro: 0.267
Epoch: 360, Train Loss: 0.896, Val f1_micro: 0.274
Epoch: 380, Train Loss: 0.849, Val f1_micro: 0.276
Epoch: 400, Train Loss: 0.874, Val f1_micro: 0.270
Epoch: 420, Train Loss: 0.850, Val f1_micro: 0.266
Epoch: 440, Train Loss: 0.805, Val f1_micro: 0.277
Epoch: 460, Train Loss: 0.812, Val f1_micro: 0.278
Epoch: 480, Train Loss: 0.783, Val f1_micro: 0.281
Epoch: 500, Train Loss: 0.767, Val f1_micro: 0.283
f1-micro: 0.283, f1-macro: 0.280, f1-weighted: 0.283, , roc-auc: 0.666
########## Hyperparameters combination ##########
(1024, 0.4, 0.05, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.047, Val f1_micro: 0.147
Epoch: 040, Train Loss: 1.956, Val f1_micro: 0.169
Epoch: 060, Train Loss: 1.898, Val f1_micro: 0.128
Epoch: 080, Train Loss: 1.840, Val f1_micro: 0.186
Epoch: 100, Train Loss: 1.736, Val f1_micro: 0.199
Epoch: 120, Train Loss: 1.669, Val f1_micro: 0.204
Epoch: 140, Train Loss: 1.616, Val f1_micro: 0.208
Epoch: 160, Train Loss: 1.546, Val f1_micro: 0.213
Epoch: 180, Train Loss: 1.497, Val f1_micro: 0.215
Epoch: 200, Train Loss: 1.441, Val f1_micro: 0.215
Epoch: 220, Train Loss: 1.388, Val f1_micro: 0.232
Epoch: 240, Train Loss: 1.347, Val f1_micro: 0.222
Epoch: 260, Train Loss: 1.379, Val f1_micro: 0.249
Epoch: 280, Train Loss: 1.281, Val f1_micro: 0.254
Epoch: 300, Train Loss: 1.259, Val f1_micro: 0.244
Epoch: 320, Train Loss: 1.240, Val f1_micro: 0.256
Epoch: 340, Train Loss: 1.216, Val f1_micro: 0.239
Epoch: 360, Train Loss: 1.194, Val f1_micro: 0.243
Epoch: 380, Train Loss: 1.264, Val f1_micro: 0.241
Epoch: 400, Train Loss: 1.159, Val f1_micro: 0.251
Epoch: 420, Train Loss: 1.155, Val f1_micro: 0.251
Epoch: 440, Train Loss: 1.206, Val f1_micro: 0.254
Epoch: 460, Train Loss: 1.135, Val f1_micro: 0.255
Epoch: 480, Train Loss: 1.112, Val f1_micro: 0.266
Epoch: 500, Train Loss: 1.115, Val f1_micro: 0.249
f1-micro: 0.249, f1-macro: 0.234, f1-weighted: 0.233, , roc-auc: 0.663
##### RUN 2 #####
Epoch: 020, Train Loss: 2.063, Val f1_micro: 0.144
Epoch: 040, Train Loss: 1.963, Val f1_micro: 0.169
Epoch: 060, Train Loss: 1.923, Val f1_micro: 0.131
Epoch: 080, Train Loss: 1.886, Val f1_micro: 0.185
Epoch: 100, Train Loss: 1.813, Val f1_micro: 0.187
Epoch: 120, Train Loss: 1.731, Val f1_micro: 0.188
Epoch: 140, Train Loss: 1.676, Val f1_micro: 0.201
Epoch: 160, Train Loss: 1.603, Val f1_micro: 0.208
Epoch: 180, Train Loss: 1.555, Val f1_micro: 0.217
Epoch: 200, Train Loss: 1.534, Val f1_micro: 0.222
Epoch: 220, Train Loss: 1.406, Val f1_micro: 0.223
Epoch: 240, Train Loss: 1.399, Val f1_micro: 0.223
Epoch: 260, Train Loss: 1.342, Val f1_micro: 0.233
Epoch: 280, Train Loss: 1.323, Val f1_micro: 0.238
Epoch: 300, Train Loss: 1.357, Val f1_micro: 0.239
Epoch: 320, Train Loss: 1.264, Val f1_micro: 0.241
Epoch: 340, Train Loss: 1.248, Val f1_micro: 0.251
Epoch: 360, Train Loss: 1.185, Val f1_micro: 0.248
Epoch: 380, Train Loss: 1.202, Val f1_micro: 0.245
Epoch: 400, Train Loss: 1.176, Val f1_micro: 0.250
Epoch: 420, Train Loss: 1.189, Val f1_micro: 0.249
Epoch: 440, Train Loss: 1.150, Val f1_micro: 0.267
Epoch: 460, Train Loss: 1.135, Val f1_micro: 0.269
Epoch: 480, Train Loss: 1.100, Val f1_micro: 0.264
Epoch: 500, Train Loss: 1.093, Val f1_micro: 0.270
f1-micro: 0.270, f1-macro: 0.257, f1-weighted: 0.262, , roc-auc: 0.661
##### RUN 3 #####
Epoch: 020, Train Loss: 2.050, Val f1_micro: 0.144
Epoch: 040, Train Loss: 1.975, Val f1_micro: 0.170
Epoch: 060, Train Loss: 1.899, Val f1_micro: 0.129
Epoch: 080, Train Loss: 1.832, Val f1_micro: 0.159
Epoch: 100, Train Loss: 1.725, Val f1_micro: 0.206
Epoch: 120, Train Loss: 1.621, Val f1_micro: 0.196
Epoch: 140, Train Loss: 1.547, Val f1_micro: 0.218
Epoch: 160, Train Loss: 1.508, Val f1_micro: 0.208
Epoch: 180, Train Loss: 1.433, Val f1_micro: 0.228
Epoch: 200, Train Loss: 1.395, Val f1_micro: 0.232
Epoch: 220, Train Loss: 1.336, Val f1_micro: 0.241
Epoch: 240, Train Loss: 1.326, Val f1_micro: 0.224
Epoch: 260, Train Loss: 1.298, Val f1_micro: 0.245
Epoch: 280, Train Loss: 1.253, Val f1_micro: 0.251
Epoch: 300, Train Loss: 1.224, Val f1_micro: 0.251
Epoch: 320, Train Loss: 1.248, Val f1_micro: 0.250
Epoch: 340, Train Loss: 1.195, Val f1_micro: 0.254
Epoch: 360, Train Loss: 1.164, Val f1_micro: 0.255
Epoch: 380, Train Loss: 1.179, Val f1_micro: 0.254
Epoch: 400, Train Loss: 1.143, Val f1_micro: 0.255
Epoch: 420, Train Loss: 1.137, Val f1_micro: 0.261
Epoch: 440, Train Loss: 1.116, Val f1_micro: 0.259
Epoch: 460, Train Loss: 1.094, Val f1_micro: 0.269
Epoch: 480, Train Loss: 1.115, Val f1_micro: 0.263
Epoch: 500, Train Loss: 1.081, Val f1_micro: 0.253
f1-micro: 0.253, f1-macro: 0.243, f1-weighted: 0.244, , roc-auc: 0.661
##### RUN 4 #####
Epoch: 020, Train Loss: 2.059, Val f1_micro: 0.142
Epoch: 040, Train Loss: 1.979, Val f1_micro: 0.169
Epoch: 060, Train Loss: 1.850, Val f1_micro: 0.180
Epoch: 080, Train Loss: 1.759, Val f1_micro: 0.194
Epoch: 100, Train Loss: 1.701, Val f1_micro: 0.188
Epoch: 120, Train Loss: 1.636, Val f1_micro: 0.192
Epoch: 140, Train Loss: 1.567, Val f1_micro: 0.215
Epoch: 160, Train Loss: 1.517, Val f1_micro: 0.218
Epoch: 180, Train Loss: 1.453, Val f1_micro: 0.221
Epoch: 200, Train Loss: 1.404, Val f1_micro: 0.228
Epoch: 220, Train Loss: 1.350, Val f1_micro: 0.231
Epoch: 240, Train Loss: 1.358, Val f1_micro: 0.222
Epoch: 260, Train Loss: 1.327, Val f1_micro: 0.235
Epoch: 280, Train Loss: 1.324, Val f1_micro: 0.229
Epoch: 300, Train Loss: 1.233, Val f1_micro: 0.250
Epoch: 320, Train Loss: 1.227, Val f1_micro: 0.256
Epoch: 340, Train Loss: 1.177, Val f1_micro: 0.253
Epoch: 360, Train Loss: 1.213, Val f1_micro: 0.244
Epoch: 380, Train Loss: 1.168, Val f1_micro: 0.253
Epoch: 400, Train Loss: 1.156, Val f1_micro: 0.264
Epoch: 420, Train Loss: 1.242, Val f1_micro: 0.245
Epoch: 440, Train Loss: 1.120, Val f1_micro: 0.260
Epoch: 460, Train Loss: 1.096, Val f1_micro: 0.267
Epoch: 480, Train Loss: 1.080, Val f1_micro: 0.270
Epoch: 500, Train Loss: 1.173, Val f1_micro: 0.247
f1-micro: 0.247, f1-macro: 0.229, f1-weighted: 0.226, , roc-auc: 0.664
##### RUN 5 #####
Epoch: 020, Train Loss: 2.029, Val f1_micro: 0.145
Epoch: 040, Train Loss: 1.941, Val f1_micro: 0.175
Epoch: 060, Train Loss: 1.843, Val f1_micro: 0.184
Epoch: 080, Train Loss: 1.744, Val f1_micro: 0.178
Epoch: 100, Train Loss: 1.623, Val f1_micro: 0.204
Epoch: 120, Train Loss: 1.512, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.494, Val f1_micro: 0.218
Epoch: 160, Train Loss: 1.407, Val f1_micro: 0.223
Epoch: 180, Train Loss: 1.409, Val f1_micro: 0.229
Epoch: 200, Train Loss: 1.300, Val f1_micro: 0.240
Epoch: 220, Train Loss: 1.274, Val f1_micro: 0.244
Epoch: 240, Train Loss: 1.240, Val f1_micro: 0.244
Epoch: 260, Train Loss: 1.228, Val f1_micro: 0.236
Epoch: 280, Train Loss: 1.239, Val f1_micro: 0.250
Epoch: 300, Train Loss: 1.184, Val f1_micro: 0.245
Epoch: 320, Train Loss: 1.163, Val f1_micro: 0.256
Epoch: 340, Train Loss: 1.105, Val f1_micro: 0.265
Epoch: 360, Train Loss: 1.109, Val f1_micro: 0.266
Epoch: 380, Train Loss: 1.118, Val f1_micro: 0.245
Epoch: 400, Train Loss: 1.085, Val f1_micro: 0.264
Epoch: 420, Train Loss: 1.056, Val f1_micro: 0.265
Epoch: 440, Train Loss: 1.141, Val f1_micro: 0.247
Epoch: 460, Train Loss: 1.071, Val f1_micro: 0.267
Epoch: 480, Train Loss: 1.038, Val f1_micro: 0.270
Epoch: 500, Train Loss: 1.024, Val f1_micro: 0.275
f1-micro: 0.275, f1-macro: 0.267, f1-weighted: 0.270, , roc-auc: 0.665
########## Hyperparameters combination ##########
(1024, 0.4, 0.05, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.073, Val f1_micro: 0.097
Epoch: 040, Train Loss: 2.024, Val f1_micro: 0.159
Epoch: 060, Train Loss: 1.975, Val f1_micro: 0.173
Epoch: 080, Train Loss: 1.915, Val f1_micro: 0.163
Epoch: 100, Train Loss: 1.867, Val f1_micro: 0.182
Epoch: 120, Train Loss: 1.818, Val f1_micro: 0.181
Epoch: 140, Train Loss: 1.809, Val f1_micro: 0.183
Epoch: 160, Train Loss: 1.798, Val f1_micro: 0.194
Epoch: 180, Train Loss: 1.768, Val f1_micro: 0.178
Epoch: 200, Train Loss: 1.788, Val f1_micro: 0.196
Epoch: 220, Train Loss: 1.777, Val f1_micro: 0.204
Epoch: 240, Train Loss: 1.769, Val f1_micro: 0.203
Epoch: 260, Train Loss: 1.741, Val f1_micro: 0.202
Epoch: 280, Train Loss: 1.755, Val f1_micro: 0.205
Epoch: 300, Train Loss: 1.768, Val f1_micro: 0.194
Epoch: 320, Train Loss: 1.783, Val f1_micro: 0.189
Epoch: 340, Train Loss: 1.766, Val f1_micro: 0.202
Epoch: 360, Train Loss: 1.762, Val f1_micro: 0.164
Epoch: 380, Train Loss: 1.747, Val f1_micro: 0.195
Epoch: 400, Train Loss: 1.741, Val f1_micro: 0.198
Epoch: 420, Train Loss: 1.768, Val f1_micro: 0.191
Epoch: 440, Train Loss: 1.745, Val f1_micro: 0.204
Epoch: 460, Train Loss: 1.745, Val f1_micro: 0.209
Epoch: 480, Train Loss: 1.756, Val f1_micro: 0.197
Epoch: 500, Train Loss: 1.762, Val f1_micro: 0.202
f1-micro: 0.202, f1-macro: 0.170, f1-weighted: 0.164, , roc-auc: 0.638
##### RUN 2 #####
Epoch: 020, Train Loss: 2.069, Val f1_micro: 0.095
Epoch: 040, Train Loss: 2.032, Val f1_micro: 0.152
Epoch: 060, Train Loss: 1.973, Val f1_micro: 0.168
Epoch: 080, Train Loss: 1.930, Val f1_micro: 0.172
Epoch: 100, Train Loss: 1.874, Val f1_micro: 0.173
Epoch: 120, Train Loss: 1.857, Val f1_micro: 0.173
Epoch: 140, Train Loss: 1.836, Val f1_micro: 0.185
Epoch: 160, Train Loss: 1.826, Val f1_micro: 0.188
Epoch: 180, Train Loss: 1.801, Val f1_micro: 0.174
Epoch: 200, Train Loss: 1.777, Val f1_micro: 0.188
Epoch: 220, Train Loss: 1.784, Val f1_micro: 0.188
Epoch: 240, Train Loss: 1.768, Val f1_micro: 0.193
Epoch: 260, Train Loss: 1.801, Val f1_micro: 0.195
Epoch: 280, Train Loss: 1.795, Val f1_micro: 0.189
Epoch: 300, Train Loss: 1.766, Val f1_micro: 0.209
Epoch: 320, Train Loss: 1.749, Val f1_micro: 0.193
Epoch: 340, Train Loss: 1.763, Val f1_micro: 0.199
Epoch: 360, Train Loss: 1.772, Val f1_micro: 0.208
Epoch: 380, Train Loss: 1.738, Val f1_micro: 0.206
Epoch: 400, Train Loss: 1.750, Val f1_micro: 0.196
Epoch: 420, Train Loss: 1.755, Val f1_micro: 0.200
Epoch: 440, Train Loss: 1.747, Val f1_micro: 0.199
Epoch: 460, Train Loss: 1.742, Val f1_micro: 0.196
Epoch: 480, Train Loss: 1.781, Val f1_micro: 0.201
Epoch: 500, Train Loss: 1.760, Val f1_micro: 0.215
f1-micro: 0.215, f1-macro: 0.179, f1-weighted: 0.176, , roc-auc: 0.633
##### RUN 3 #####
Epoch: 020, Train Loss: 2.051, Val f1_micro: 0.102
Epoch: 040, Train Loss: 2.022, Val f1_micro: 0.117
Epoch: 060, Train Loss: 1.962, Val f1_micro: 0.174
Epoch: 080, Train Loss: 1.922, Val f1_micro: 0.172
Epoch: 100, Train Loss: 1.874, Val f1_micro: 0.171
Epoch: 120, Train Loss: 1.833, Val f1_micro: 0.178
Epoch: 140, Train Loss: 1.846, Val f1_micro: 0.184
Epoch: 160, Train Loss: 1.812, Val f1_micro: 0.182
Epoch: 180, Train Loss: 1.792, Val f1_micro: 0.191
Epoch: 200, Train Loss: 1.798, Val f1_micro: 0.195
Epoch: 220, Train Loss: 1.766, Val f1_micro: 0.198
Epoch: 240, Train Loss: 1.778, Val f1_micro: 0.196
Epoch: 260, Train Loss: 1.777, Val f1_micro: 0.202
Epoch: 280, Train Loss: 1.758, Val f1_micro: 0.201
Epoch: 300, Train Loss: 1.760, Val f1_micro: 0.201
Epoch: 320, Train Loss: 1.751, Val f1_micro: 0.193
Epoch: 340, Train Loss: 1.749, Val f1_micro: 0.197
Epoch: 360, Train Loss: 1.834, Val f1_micro: 0.147
Epoch: 380, Train Loss: 1.774, Val f1_micro: 0.193
Epoch: 400, Train Loss: 1.736, Val f1_micro: 0.200
Epoch: 420, Train Loss: 1.750, Val f1_micro: 0.196
Epoch: 440, Train Loss: 1.749, Val f1_micro: 0.205
Epoch: 460, Train Loss: 1.723, Val f1_micro: 0.202
Epoch: 480, Train Loss: 1.770, Val f1_micro: 0.197
Epoch: 500, Train Loss: 1.761, Val f1_micro: 0.195
f1-micro: 0.195, f1-macro: 0.170, f1-weighted: 0.164, , roc-auc: 0.636
##### RUN 4 #####
Epoch: 020, Train Loss: 2.065, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.023, Val f1_micro: 0.117
Epoch: 060, Train Loss: 1.979, Val f1_micro: 0.163
Epoch: 080, Train Loss: 1.934, Val f1_micro: 0.143
Epoch: 100, Train Loss: 1.869, Val f1_micro: 0.181
Epoch: 120, Train Loss: 1.864, Val f1_micro: 0.190
Epoch: 140, Train Loss: 1.817, Val f1_micro: 0.189
Epoch: 160, Train Loss: 1.811, Val f1_micro: 0.173
Epoch: 180, Train Loss: 1.792, Val f1_micro: 0.185
Epoch: 200, Train Loss: 1.788, Val f1_micro: 0.185
Epoch: 220, Train Loss: 1.782, Val f1_micro: 0.189
Epoch: 240, Train Loss: 1.793, Val f1_micro: 0.183
Epoch: 260, Train Loss: 1.759, Val f1_micro: 0.209
Epoch: 280, Train Loss: 1.774, Val f1_micro: 0.184
Epoch: 300, Train Loss: 1.744, Val f1_micro: 0.199
Epoch: 320, Train Loss: 1.745, Val f1_micro: 0.201
Epoch: 340, Train Loss: 1.762, Val f1_micro: 0.200
Epoch: 360, Train Loss: 1.762, Val f1_micro: 0.197
Epoch: 380, Train Loss: 1.761, Val f1_micro: 0.197
Epoch: 400, Train Loss: 1.778, Val f1_micro: 0.196
Epoch: 420, Train Loss: 1.764, Val f1_micro: 0.192
Epoch: 440, Train Loss: 1.739, Val f1_micro: 0.200
Epoch: 460, Train Loss: 1.734, Val f1_micro: 0.198
Epoch: 480, Train Loss: 1.745, Val f1_micro: 0.209
Epoch: 500, Train Loss: 1.727, Val f1_micro: 0.196
f1-micro: 0.196, f1-macro: 0.165, f1-weighted: 0.159, , roc-auc: 0.637
##### RUN 5 #####
Epoch: 020, Train Loss: 2.062, Val f1_micro: 0.099
Epoch: 040, Train Loss: 2.032, Val f1_micro: 0.124
Epoch: 060, Train Loss: 1.989, Val f1_micro: 0.158
Epoch: 080, Train Loss: 1.945, Val f1_micro: 0.166
Epoch: 100, Train Loss: 1.889, Val f1_micro: 0.156
Epoch: 120, Train Loss: 1.855, Val f1_micro: 0.176
Epoch: 140, Train Loss: 1.817, Val f1_micro: 0.167
Epoch: 160, Train Loss: 1.812, Val f1_micro: 0.181
Epoch: 180, Train Loss: 1.793, Val f1_micro: 0.194
Epoch: 200, Train Loss: 1.806, Val f1_micro: 0.196
Epoch: 220, Train Loss: 1.779, Val f1_micro: 0.200
Epoch: 240, Train Loss: 1.774, Val f1_micro: 0.191
Epoch: 260, Train Loss: 1.773, Val f1_micro: 0.190
Epoch: 280, Train Loss: 1.755, Val f1_micro: 0.191
Epoch: 300, Train Loss: 1.766, Val f1_micro: 0.192
Epoch: 320, Train Loss: 1.747, Val f1_micro: 0.190
Epoch: 340, Train Loss: 1.759, Val f1_micro: 0.199
Epoch: 360, Train Loss: 1.752, Val f1_micro: 0.199
Epoch: 380, Train Loss: 1.763, Val f1_micro: 0.196
Epoch: 400, Train Loss: 1.742, Val f1_micro: 0.205
Epoch: 420, Train Loss: 1.736, Val f1_micro: 0.185
Epoch: 440, Train Loss: 1.737, Val f1_micro: 0.210
Epoch: 460, Train Loss: 1.737, Val f1_micro: 0.173
Epoch: 480, Train Loss: 1.747, Val f1_micro: 0.210
Epoch: 500, Train Loss: 1.744, Val f1_micro: 0.197
f1-micro: 0.197, f1-macro: 0.166, f1-weighted: 0.164, , roc-auc: 0.636
########## Hyperparameters combination ##########
(1024, 0.5, 0.001, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.226, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.962, Val f1_micro: 0.210
Epoch: 060, Train Loss: 1.814, Val f1_micro: 0.216
Epoch: 080, Train Loss: 1.694, Val f1_micro: 0.225
Epoch: 100, Train Loss: 1.612, Val f1_micro: 0.230
Epoch: 120, Train Loss: 1.554, Val f1_micro: 0.239
Epoch: 140, Train Loss: 1.481, Val f1_micro: 0.239
Epoch: 160, Train Loss: 1.422, Val f1_micro: 0.248
Epoch: 180, Train Loss: 1.402, Val f1_micro: 0.253
Epoch: 200, Train Loss: 1.365, Val f1_micro: 0.257
Epoch: 220, Train Loss: 1.320, Val f1_micro: 0.258
Epoch: 240, Train Loss: 1.293, Val f1_micro: 0.259
Epoch: 260, Train Loss: 1.253, Val f1_micro: 0.260
Epoch: 280, Train Loss: 1.227, Val f1_micro: 0.262
Epoch: 300, Train Loss: 1.179, Val f1_micro: 0.261
Epoch: 320, Train Loss: 1.158, Val f1_micro: 0.263
Epoch: 340, Train Loss: 1.144, Val f1_micro: 0.266
Epoch: 360, Train Loss: 1.087, Val f1_micro: 0.267
Epoch: 380, Train Loss: 1.085, Val f1_micro: 0.270
Epoch: 400, Train Loss: 1.059, Val f1_micro: 0.269
Epoch: 420, Train Loss: 1.065, Val f1_micro: 0.270
Epoch: 440, Train Loss: 1.015, Val f1_micro: 0.272
Epoch: 460, Train Loss: 1.000, Val f1_micro: 0.274
Epoch: 480, Train Loss: 0.978, Val f1_micro: 0.276
Epoch: 500, Train Loss: 0.955, Val f1_micro: 0.277
f1-micro: 0.277, f1-macro: 0.271, f1-weighted: 0.273, , roc-auc: 0.678
##### RUN 2 #####
Epoch: 020, Train Loss: 2.215, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.969, Val f1_micro: 0.209
Epoch: 060, Train Loss: 1.829, Val f1_micro: 0.215
Epoch: 080, Train Loss: 1.698, Val f1_micro: 0.225
Epoch: 100, Train Loss: 1.621, Val f1_micro: 0.231
Epoch: 120, Train Loss: 1.556, Val f1_micro: 0.238
Epoch: 140, Train Loss: 1.499, Val f1_micro: 0.243
Epoch: 160, Train Loss: 1.430, Val f1_micro: 0.247
Epoch: 180, Train Loss: 1.391, Val f1_micro: 0.251
Epoch: 200, Train Loss: 1.336, Val f1_micro: 0.253
Epoch: 220, Train Loss: 1.313, Val f1_micro: 0.259
Epoch: 240, Train Loss: 1.264, Val f1_micro: 0.263
Epoch: 260, Train Loss: 1.240, Val f1_micro: 0.264
Epoch: 280, Train Loss: 1.210, Val f1_micro: 0.262
Epoch: 300, Train Loss: 1.181, Val f1_micro: 0.262
Epoch: 320, Train Loss: 1.164, Val f1_micro: 0.265
Epoch: 340, Train Loss: 1.126, Val f1_micro: 0.267
Epoch: 360, Train Loss: 1.114, Val f1_micro: 0.267
Epoch: 380, Train Loss: 1.085, Val f1_micro: 0.270
Epoch: 400, Train Loss: 1.066, Val f1_micro: 0.271
Epoch: 420, Train Loss: 1.048, Val f1_micro: 0.276
Epoch: 440, Train Loss: 1.017, Val f1_micro: 0.273
Epoch: 460, Train Loss: 1.004, Val f1_micro: 0.277
Epoch: 480, Train Loss: 0.982, Val f1_micro: 0.276
Epoch: 500, Train Loss: 0.970, Val f1_micro: 0.278
f1-micro: 0.278, f1-macro: 0.271, f1-weighted: 0.273, , roc-auc: 0.679
##### RUN 3 #####
Epoch: 020, Train Loss: 2.230, Val f1_micro: 0.190
Epoch: 040, Train Loss: 1.950, Val f1_micro: 0.208
Epoch: 060, Train Loss: 1.806, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.707, Val f1_micro: 0.227
Epoch: 100, Train Loss: 1.632, Val f1_micro: 0.230
Epoch: 120, Train Loss: 1.571, Val f1_micro: 0.240
Epoch: 140, Train Loss: 1.490, Val f1_micro: 0.243
Epoch: 160, Train Loss: 1.451, Val f1_micro: 0.251
Epoch: 180, Train Loss: 1.399, Val f1_micro: 0.253
Epoch: 200, Train Loss: 1.354, Val f1_micro: 0.256
Epoch: 220, Train Loss: 1.325, Val f1_micro: 0.256
Epoch: 240, Train Loss: 1.281, Val f1_micro: 0.260
Epoch: 260, Train Loss: 1.256, Val f1_micro: 0.262
Epoch: 280, Train Loss: 1.220, Val f1_micro: 0.265
Epoch: 300, Train Loss: 1.194, Val f1_micro: 0.264
Epoch: 320, Train Loss: 1.157, Val f1_micro: 0.267
Epoch: 340, Train Loss: 1.140, Val f1_micro: 0.268
Epoch: 360, Train Loss: 1.115, Val f1_micro: 0.266
Epoch: 380, Train Loss: 1.088, Val f1_micro: 0.267
Epoch: 400, Train Loss: 1.060, Val f1_micro: 0.270
Epoch: 420, Train Loss: 1.042, Val f1_micro: 0.271
Epoch: 440, Train Loss: 1.013, Val f1_micro: 0.272
Epoch: 460, Train Loss: 1.012, Val f1_micro: 0.274
Epoch: 480, Train Loss: 0.993, Val f1_micro: 0.276
Epoch: 500, Train Loss: 0.983, Val f1_micro: 0.273
f1-micro: 0.273, f1-macro: 0.266, f1-weighted: 0.268, , roc-auc: 0.679
##### RUN 4 #####
Epoch: 020, Train Loss: 2.214, Val f1_micro: 0.187
Epoch: 040, Train Loss: 1.959, Val f1_micro: 0.209
Epoch: 060, Train Loss: 1.812, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.693, Val f1_micro: 0.226
Epoch: 100, Train Loss: 1.630, Val f1_micro: 0.231
Epoch: 120, Train Loss: 1.552, Val f1_micro: 0.238
Epoch: 140, Train Loss: 1.484, Val f1_micro: 0.243
Epoch: 160, Train Loss: 1.442, Val f1_micro: 0.247
Epoch: 180, Train Loss: 1.384, Val f1_micro: 0.250
Epoch: 200, Train Loss: 1.342, Val f1_micro: 0.254
Epoch: 220, Train Loss: 1.319, Val f1_micro: 0.257
Epoch: 240, Train Loss: 1.262, Val f1_micro: 0.259
Epoch: 260, Train Loss: 1.225, Val f1_micro: 0.264
Epoch: 280, Train Loss: 1.212, Val f1_micro: 0.262
Epoch: 300, Train Loss: 1.204, Val f1_micro: 0.263
Epoch: 320, Train Loss: 1.162, Val f1_micro: 0.264
Epoch: 340, Train Loss: 1.139, Val f1_micro: 0.266
Epoch: 360, Train Loss: 1.108, Val f1_micro: 0.270
Epoch: 380, Train Loss: 1.085, Val f1_micro: 0.270
Epoch: 400, Train Loss: 1.067, Val f1_micro: 0.267
Epoch: 420, Train Loss: 1.044, Val f1_micro: 0.271
Epoch: 440, Train Loss: 1.027, Val f1_micro: 0.271
Epoch: 460, Train Loss: 0.991, Val f1_micro: 0.272
Epoch: 480, Train Loss: 0.975, Val f1_micro: 0.275
Epoch: 500, Train Loss: 0.949, Val f1_micro: 0.276
f1-micro: 0.276, f1-macro: 0.269, f1-weighted: 0.271, , roc-auc: 0.680
##### RUN 5 #####
Epoch: 020, Train Loss: 2.259, Val f1_micro: 0.186
Epoch: 040, Train Loss: 1.968, Val f1_micro: 0.208
Epoch: 060, Train Loss: 1.810, Val f1_micro: 0.217
Epoch: 080, Train Loss: 1.708, Val f1_micro: 0.226
Epoch: 100, Train Loss: 1.620, Val f1_micro: 0.234
Epoch: 120, Train Loss: 1.550, Val f1_micro: 0.240
Epoch: 140, Train Loss: 1.491, Val f1_micro: 0.241
Epoch: 160, Train Loss: 1.448, Val f1_micro: 0.249
Epoch: 180, Train Loss: 1.420, Val f1_micro: 0.253
Epoch: 200, Train Loss: 1.344, Val f1_micro: 0.253
Epoch: 220, Train Loss: 1.314, Val f1_micro: 0.258
Epoch: 240, Train Loss: 1.281, Val f1_micro: 0.260
Epoch: 260, Train Loss: 1.251, Val f1_micro: 0.259
Epoch: 280, Train Loss: 1.218, Val f1_micro: 0.262
Epoch: 300, Train Loss: 1.169, Val f1_micro: 0.263
Epoch: 320, Train Loss: 1.158, Val f1_micro: 0.265
Epoch: 340, Train Loss: 1.113, Val f1_micro: 0.266
Epoch: 360, Train Loss: 1.118, Val f1_micro: 0.268
Epoch: 380, Train Loss: 1.084, Val f1_micro: 0.269
Epoch: 400, Train Loss: 1.072, Val f1_micro: 0.272
Epoch: 420, Train Loss: 1.038, Val f1_micro: 0.271
Epoch: 440, Train Loss: 1.009, Val f1_micro: 0.273
Epoch: 460, Train Loss: 0.995, Val f1_micro: 0.273
Epoch: 480, Train Loss: 0.988, Val f1_micro: 0.276
Epoch: 500, Train Loss: 0.962, Val f1_micro: 0.277
f1-micro: 0.277, f1-macro: 0.270, f1-weighted: 0.273, , roc-auc: 0.679
########## Hyperparameters combination ##########
(1024, 0.5, 0.001, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.225, Val f1_micro: 0.186
Epoch: 040, Train Loss: 1.941, Val f1_micro: 0.207
Epoch: 060, Train Loss: 1.846, Val f1_micro: 0.216
Epoch: 080, Train Loss: 1.740, Val f1_micro: 0.224
Epoch: 100, Train Loss: 1.635, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.566, Val f1_micro: 0.236
Epoch: 140, Train Loss: 1.513, Val f1_micro: 0.235
Epoch: 160, Train Loss: 1.473, Val f1_micro: 0.246
Epoch: 180, Train Loss: 1.445, Val f1_micro: 0.246
Epoch: 200, Train Loss: 1.391, Val f1_micro: 0.249
Epoch: 220, Train Loss: 1.369, Val f1_micro: 0.250
Epoch: 240, Train Loss: 1.334, Val f1_micro: 0.252
Epoch: 260, Train Loss: 1.302, Val f1_micro: 0.257
Epoch: 280, Train Loss: 1.270, Val f1_micro: 0.256
Epoch: 300, Train Loss: 1.233, Val f1_micro: 0.262
Epoch: 320, Train Loss: 1.219, Val f1_micro: 0.265
Epoch: 340, Train Loss: 1.205, Val f1_micro: 0.265
Epoch: 360, Train Loss: 1.177, Val f1_micro: 0.266
Epoch: 380, Train Loss: 1.166, Val f1_micro: 0.268
Epoch: 400, Train Loss: 1.133, Val f1_micro: 0.269
Epoch: 420, Train Loss: 1.130, Val f1_micro: 0.271
Epoch: 440, Train Loss: 1.100, Val f1_micro: 0.270
Epoch: 460, Train Loss: 1.098, Val f1_micro: 0.273
Epoch: 480, Train Loss: 1.072, Val f1_micro: 0.275
Epoch: 500, Train Loss: 1.067, Val f1_micro: 0.274
f1-micro: 0.274, f1-macro: 0.265, f1-weighted: 0.266, , roc-auc: 0.678
##### RUN 2 #####
Epoch: 020, Train Loss: 2.256, Val f1_micro: 0.188
Epoch: 040, Train Loss: 1.968, Val f1_micro: 0.210
Epoch: 060, Train Loss: 1.815, Val f1_micro: 0.215
Epoch: 080, Train Loss: 1.730, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.640, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.579, Val f1_micro: 0.237
Epoch: 140, Train Loss: 1.521, Val f1_micro: 0.238
Epoch: 160, Train Loss: 1.465, Val f1_micro: 0.238
Epoch: 180, Train Loss: 1.439, Val f1_micro: 0.246
Epoch: 200, Train Loss: 1.385, Val f1_micro: 0.250
Epoch: 220, Train Loss: 1.363, Val f1_micro: 0.248
Epoch: 240, Train Loss: 1.326, Val f1_micro: 0.255
Epoch: 260, Train Loss: 1.284, Val f1_micro: 0.259
Epoch: 280, Train Loss: 1.269, Val f1_micro: 0.258
Epoch: 300, Train Loss: 1.267, Val f1_micro: 0.261
Epoch: 320, Train Loss: 1.224, Val f1_micro: 0.263
Epoch: 340, Train Loss: 1.207, Val f1_micro: 0.265
Epoch: 360, Train Loss: 1.190, Val f1_micro: 0.265
Epoch: 380, Train Loss: 1.163, Val f1_micro: 0.266
Epoch: 400, Train Loss: 1.155, Val f1_micro: 0.268
Epoch: 420, Train Loss: 1.132, Val f1_micro: 0.269
Epoch: 440, Train Loss: 1.097, Val f1_micro: 0.271
Epoch: 460, Train Loss: 1.109, Val f1_micro: 0.272
Epoch: 480, Train Loss: 1.075, Val f1_micro: 0.272
Epoch: 500, Train Loss: 1.067, Val f1_micro: 0.275
f1-micro: 0.275, f1-macro: 0.265, f1-weighted: 0.266, , roc-auc: 0.679
##### RUN 3 #####
Epoch: 020, Train Loss: 2.230, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.953, Val f1_micro: 0.206
Epoch: 060, Train Loss: 1.802, Val f1_micro: 0.215
Epoch: 080, Train Loss: 1.708, Val f1_micro: 0.228
Epoch: 100, Train Loss: 1.646, Val f1_micro: 0.226
Epoch: 120, Train Loss: 1.573, Val f1_micro: 0.233
Epoch: 140, Train Loss: 1.511, Val f1_micro: 0.235
Epoch: 160, Train Loss: 1.480, Val f1_micro: 0.239
Epoch: 180, Train Loss: 1.419, Val f1_micro: 0.247
Epoch: 200, Train Loss: 1.405, Val f1_micro: 0.248
Epoch: 220, Train Loss: 1.360, Val f1_micro: 0.253
Epoch: 240, Train Loss: 1.331, Val f1_micro: 0.257
Epoch: 260, Train Loss: 1.309, Val f1_micro: 0.257
Epoch: 280, Train Loss: 1.274, Val f1_micro: 0.262
Epoch: 300, Train Loss: 1.233, Val f1_micro: 0.264
Epoch: 320, Train Loss: 1.213, Val f1_micro: 0.267
Epoch: 340, Train Loss: 1.200, Val f1_micro: 0.267
Epoch: 360, Train Loss: 1.179, Val f1_micro: 0.270
Epoch: 380, Train Loss: 1.150, Val f1_micro: 0.268
Epoch: 400, Train Loss: 1.149, Val f1_micro: 0.271
Epoch: 420, Train Loss: 1.101, Val f1_micro: 0.273
Epoch: 440, Train Loss: 1.117, Val f1_micro: 0.275
Epoch: 460, Train Loss: 1.082, Val f1_micro: 0.274
Epoch: 480, Train Loss: 1.080, Val f1_micro: 0.275
Epoch: 500, Train Loss: 1.048, Val f1_micro: 0.272
f1-micro: 0.272, f1-macro: 0.263, f1-weighted: 0.264, , roc-auc: 0.680
##### RUN 4 #####
Epoch: 020, Train Loss: 2.227, Val f1_micro: 0.185
Epoch: 040, Train Loss: 1.953, Val f1_micro: 0.207
Epoch: 060, Train Loss: 1.826, Val f1_micro: 0.218
Epoch: 080, Train Loss: 1.725, Val f1_micro: 0.225
Epoch: 100, Train Loss: 1.654, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.573, Val f1_micro: 0.234
Epoch: 140, Train Loss: 1.522, Val f1_micro: 0.240
Epoch: 160, Train Loss: 1.480, Val f1_micro: 0.241
Epoch: 180, Train Loss: 1.448, Val f1_micro: 0.244
Epoch: 200, Train Loss: 1.392, Val f1_micro: 0.247
Epoch: 220, Train Loss: 1.353, Val f1_micro: 0.252
Epoch: 240, Train Loss: 1.316, Val f1_micro: 0.256
Epoch: 260, Train Loss: 1.303, Val f1_micro: 0.255
Epoch: 280, Train Loss: 1.254, Val f1_micro: 0.259
Epoch: 300, Train Loss: 1.239, Val f1_micro: 0.259
Epoch: 320, Train Loss: 1.232, Val f1_micro: 0.262
Epoch: 340, Train Loss: 1.206, Val f1_micro: 0.263
Epoch: 360, Train Loss: 1.185, Val f1_micro: 0.264
Epoch: 380, Train Loss: 1.172, Val f1_micro: 0.266
Epoch: 400, Train Loss: 1.141, Val f1_micro: 0.267
Epoch: 420, Train Loss: 1.124, Val f1_micro: 0.271
Epoch: 440, Train Loss: 1.093, Val f1_micro: 0.273
Epoch: 460, Train Loss: 1.109, Val f1_micro: 0.272
Epoch: 480, Train Loss: 1.077, Val f1_micro: 0.273
Epoch: 500, Train Loss: 1.059, Val f1_micro: 0.273
f1-micro: 0.273, f1-macro: 0.264, f1-weighted: 0.265, , roc-auc: 0.678
##### RUN 5 #####
Epoch: 020, Train Loss: 2.246, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.942, Val f1_micro: 0.205
Epoch: 060, Train Loss: 1.811, Val f1_micro: 0.215
Epoch: 080, Train Loss: 1.718, Val f1_micro: 0.221
Epoch: 100, Train Loss: 1.642, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.585, Val f1_micro: 0.234
Epoch: 140, Train Loss: 1.504, Val f1_micro: 0.238
Epoch: 160, Train Loss: 1.480, Val f1_micro: 0.239
Epoch: 180, Train Loss: 1.444, Val f1_micro: 0.244
Epoch: 200, Train Loss: 1.381, Val f1_micro: 0.249
Epoch: 220, Train Loss: 1.370, Val f1_micro: 0.250
Epoch: 240, Train Loss: 1.335, Val f1_micro: 0.255
Epoch: 260, Train Loss: 1.296, Val f1_micro: 0.257
Epoch: 280, Train Loss: 1.268, Val f1_micro: 0.260
Epoch: 300, Train Loss: 1.256, Val f1_micro: 0.262
Epoch: 320, Train Loss: 1.219, Val f1_micro: 0.263
Epoch: 340, Train Loss: 1.207, Val f1_micro: 0.264
Epoch: 360, Train Loss: 1.193, Val f1_micro: 0.267
Epoch: 380, Train Loss: 1.181, Val f1_micro: 0.268
Epoch: 400, Train Loss: 1.146, Val f1_micro: 0.267
Epoch: 420, Train Loss: 1.128, Val f1_micro: 0.269
Epoch: 440, Train Loss: 1.092, Val f1_micro: 0.274
Epoch: 460, Train Loss: 1.091, Val f1_micro: 0.270
Epoch: 480, Train Loss: 1.070, Val f1_micro: 0.274
Epoch: 500, Train Loss: 1.054, Val f1_micro: 0.275
f1-micro: 0.275, f1-macro: 0.266, f1-weighted: 0.268, , roc-auc: 0.678
########## Hyperparameters combination ##########
(1024, 0.5, 0.001, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.225, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.946, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.802, Val f1_micro: 0.216
Epoch: 080, Train Loss: 1.738, Val f1_micro: 0.221
Epoch: 100, Train Loss: 1.643, Val f1_micro: 0.227
Epoch: 120, Train Loss: 1.594, Val f1_micro: 0.230
Epoch: 140, Train Loss: 1.536, Val f1_micro: 0.237
Epoch: 160, Train Loss: 1.477, Val f1_micro: 0.239
Epoch: 180, Train Loss: 1.453, Val f1_micro: 0.242
Epoch: 200, Train Loss: 1.421, Val f1_micro: 0.243
Epoch: 220, Train Loss: 1.400, Val f1_micro: 0.248
Epoch: 240, Train Loss: 1.373, Val f1_micro: 0.248
Epoch: 260, Train Loss: 1.339, Val f1_micro: 0.250
Epoch: 280, Train Loss: 1.344, Val f1_micro: 0.254
Epoch: 300, Train Loss: 1.306, Val f1_micro: 0.252
Epoch: 320, Train Loss: 1.287, Val f1_micro: 0.254
Epoch: 340, Train Loss: 1.253, Val f1_micro: 0.256
Epoch: 360, Train Loss: 1.268, Val f1_micro: 0.256
Epoch: 380, Train Loss: 1.240, Val f1_micro: 0.258
Epoch: 400, Train Loss: 1.216, Val f1_micro: 0.261
Epoch: 420, Train Loss: 1.208, Val f1_micro: 0.261
Epoch: 440, Train Loss: 1.185, Val f1_micro: 0.262
Epoch: 460, Train Loss: 1.163, Val f1_micro: 0.264
Epoch: 480, Train Loss: 1.177, Val f1_micro: 0.262
Epoch: 500, Train Loss: 1.158, Val f1_micro: 0.265
f1-micro: 0.265, f1-macro: 0.255, f1-weighted: 0.256, , roc-auc: 0.672
##### RUN 2 #####
Epoch: 020, Train Loss: 2.261, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.965, Val f1_micro: 0.209
Epoch: 060, Train Loss: 1.812, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.723, Val f1_micro: 0.225
Epoch: 100, Train Loss: 1.634, Val f1_micro: 0.224
Epoch: 120, Train Loss: 1.584, Val f1_micro: 0.231
Epoch: 140, Train Loss: 1.551, Val f1_micro: 0.236
Epoch: 160, Train Loss: 1.459, Val f1_micro: 0.240
Epoch: 180, Train Loss: 1.459, Val f1_micro: 0.238
Epoch: 200, Train Loss: 1.415, Val f1_micro: 0.243
Epoch: 220, Train Loss: 1.371, Val f1_micro: 0.246
Epoch: 240, Train Loss: 1.347, Val f1_micro: 0.250
Epoch: 260, Train Loss: 1.346, Val f1_micro: 0.252
Epoch: 280, Train Loss: 1.319, Val f1_micro: 0.251
Epoch: 300, Train Loss: 1.309, Val f1_micro: 0.255
Epoch: 320, Train Loss: 1.276, Val f1_micro: 0.255
Epoch: 340, Train Loss: 1.246, Val f1_micro: 0.257
Epoch: 360, Train Loss: 1.257, Val f1_micro: 0.258
Epoch: 380, Train Loss: 1.242, Val f1_micro: 0.255
Epoch: 400, Train Loss: 1.209, Val f1_micro: 0.260
Epoch: 420, Train Loss: 1.209, Val f1_micro: 0.261
Epoch: 440, Train Loss: 1.178, Val f1_micro: 0.261
Epoch: 460, Train Loss: 1.197, Val f1_micro: 0.261
Epoch: 480, Train Loss: 1.177, Val f1_micro: 0.263
Epoch: 500, Train Loss: 1.162, Val f1_micro: 0.261
f1-micro: 0.261, f1-macro: 0.251, f1-weighted: 0.252, , roc-auc: 0.672
##### RUN 3 #####
Epoch: 020, Train Loss: 2.239, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.969, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.810, Val f1_micro: 0.218
Epoch: 080, Train Loss: 1.698, Val f1_micro: 0.219
Epoch: 100, Train Loss: 1.642, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.574, Val f1_micro: 0.229
Epoch: 140, Train Loss: 1.534, Val f1_micro: 0.234
Epoch: 160, Train Loss: 1.479, Val f1_micro: 0.239
Epoch: 180, Train Loss: 1.438, Val f1_micro: 0.241
Epoch: 200, Train Loss: 1.414, Val f1_micro: 0.242
Epoch: 220, Train Loss: 1.390, Val f1_micro: 0.245
Epoch: 240, Train Loss: 1.357, Val f1_micro: 0.249
Epoch: 260, Train Loss: 1.336, Val f1_micro: 0.248
Epoch: 280, Train Loss: 1.319, Val f1_micro: 0.253
Epoch: 300, Train Loss: 1.284, Val f1_micro: 0.253
Epoch: 320, Train Loss: 1.267, Val f1_micro: 0.256
Epoch: 340, Train Loss: 1.256, Val f1_micro: 0.257
Epoch: 360, Train Loss: 1.247, Val f1_micro: 0.257
Epoch: 380, Train Loss: 1.234, Val f1_micro: 0.260
Epoch: 400, Train Loss: 1.215, Val f1_micro: 0.260
Epoch: 420, Train Loss: 1.199, Val f1_micro: 0.262
Epoch: 440, Train Loss: 1.195, Val f1_micro: 0.262
Epoch: 460, Train Loss: 1.176, Val f1_micro: 0.264
Epoch: 480, Train Loss: 1.180, Val f1_micro: 0.264
Epoch: 500, Train Loss: 1.152, Val f1_micro: 0.266
f1-micro: 0.266, f1-macro: 0.255, f1-weighted: 0.257, , roc-auc: 0.672
##### RUN 4 #####
Epoch: 020, Train Loss: 2.232, Val f1_micro: 0.196
Epoch: 040, Train Loss: 1.984, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.820, Val f1_micro: 0.218
Epoch: 080, Train Loss: 1.712, Val f1_micro: 0.222
Epoch: 100, Train Loss: 1.651, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.585, Val f1_micro: 0.230
Epoch: 140, Train Loss: 1.532, Val f1_micro: 0.230
Epoch: 160, Train Loss: 1.479, Val f1_micro: 0.234
Epoch: 180, Train Loss: 1.458, Val f1_micro: 0.243
Epoch: 200, Train Loss: 1.426, Val f1_micro: 0.249
Epoch: 220, Train Loss: 1.399, Val f1_micro: 0.245
Epoch: 240, Train Loss: 1.364, Val f1_micro: 0.249
Epoch: 260, Train Loss: 1.338, Val f1_micro: 0.250
Epoch: 280, Train Loss: 1.318, Val f1_micro: 0.254
Epoch: 300, Train Loss: 1.292, Val f1_micro: 0.254
Epoch: 320, Train Loss: 1.282, Val f1_micro: 0.257
Epoch: 340, Train Loss: 1.250, Val f1_micro: 0.259
Epoch: 360, Train Loss: 1.253, Val f1_micro: 0.259
Epoch: 380, Train Loss: 1.222, Val f1_micro: 0.258
Epoch: 400, Train Loss: 1.222, Val f1_micro: 0.260
Epoch: 420, Train Loss: 1.195, Val f1_micro: 0.263
Epoch: 440, Train Loss: 1.187, Val f1_micro: 0.262
Epoch: 460, Train Loss: 1.185, Val f1_micro: 0.263
Epoch: 480, Train Loss: 1.175, Val f1_micro: 0.264
Epoch: 500, Train Loss: 1.163, Val f1_micro: 0.264
f1-micro: 0.264, f1-macro: 0.253, f1-weighted: 0.254, , roc-auc: 0.672
##### RUN 5 #####
Epoch: 020, Train Loss: 2.246, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.976, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.811, Val f1_micro: 0.218
Epoch: 080, Train Loss: 1.710, Val f1_micro: 0.221
Epoch: 100, Train Loss: 1.648, Val f1_micro: 0.227
Epoch: 120, Train Loss: 1.576, Val f1_micro: 0.231
Epoch: 140, Train Loss: 1.510, Val f1_micro: 0.236
Epoch: 160, Train Loss: 1.474, Val f1_micro: 0.239
Epoch: 180, Train Loss: 1.439, Val f1_micro: 0.243
Epoch: 200, Train Loss: 1.422, Val f1_micro: 0.246
Epoch: 220, Train Loss: 1.409, Val f1_micro: 0.247
Epoch: 240, Train Loss: 1.363, Val f1_micro: 0.248
Epoch: 260, Train Loss: 1.339, Val f1_micro: 0.249
Epoch: 280, Train Loss: 1.312, Val f1_micro: 0.251
Epoch: 300, Train Loss: 1.308, Val f1_micro: 0.251
Epoch: 320, Train Loss: 1.287, Val f1_micro: 0.256
Epoch: 340, Train Loss: 1.267, Val f1_micro: 0.255
Epoch: 360, Train Loss: 1.249, Val f1_micro: 0.259
Epoch: 380, Train Loss: 1.239, Val f1_micro: 0.260
Epoch: 400, Train Loss: 1.210, Val f1_micro: 0.261
Epoch: 420, Train Loss: 1.227, Val f1_micro: 0.260
Epoch: 440, Train Loss: 1.194, Val f1_micro: 0.261
Epoch: 460, Train Loss: 1.180, Val f1_micro: 0.265
Epoch: 480, Train Loss: 1.161, Val f1_micro: 0.266
Epoch: 500, Train Loss: 1.155, Val f1_micro: 0.265
f1-micro: 0.265, f1-macro: 0.256, f1-weighted: 0.257, , roc-auc: 0.672
########## Hyperparameters combination ##########
(1024, 0.5, 0.001, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.253, Val f1_micro: 0.196
Epoch: 040, Train Loss: 1.963, Val f1_micro: 0.217
Epoch: 060, Train Loss: 1.866, Val f1_micro: 0.222
Epoch: 080, Train Loss: 1.762, Val f1_micro: 0.224
Epoch: 100, Train Loss: 1.708, Val f1_micro: 0.226
Epoch: 120, Train Loss: 1.670, Val f1_micro: 0.233
Epoch: 140, Train Loss: 1.660, Val f1_micro: 0.227
Epoch: 160, Train Loss: 1.628, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.607, Val f1_micro: 0.233
Epoch: 200, Train Loss: 1.607, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.601, Val f1_micro: 0.238
Epoch: 240, Train Loss: 1.583, Val f1_micro: 0.235
Epoch: 260, Train Loss: 1.578, Val f1_micro: 0.237
Epoch: 280, Train Loss: 1.584, Val f1_micro: 0.238
Epoch: 300, Train Loss: 1.580, Val f1_micro: 0.238
Epoch: 320, Train Loss: 1.588, Val f1_micro: 0.233
Epoch: 340, Train Loss: 1.579, Val f1_micro: 0.235
Epoch: 360, Train Loss: 1.573, Val f1_micro: 0.236
Epoch: 380, Train Loss: 1.579, Val f1_micro: 0.238
Epoch: 400, Train Loss: 1.584, Val f1_micro: 0.233
Epoch: 420, Train Loss: 1.595, Val f1_micro: 0.231
Epoch: 440, Train Loss: 1.588, Val f1_micro: 0.235
Epoch: 460, Train Loss: 1.599, Val f1_micro: 0.236
Epoch: 480, Train Loss: 1.587, Val f1_micro: 0.233
Epoch: 500, Train Loss: 1.588, Val f1_micro: 0.233
f1-micro: 0.233, f1-macro: 0.207, f1-weighted: 0.206, , roc-auc: 0.662
##### RUN 2 #####
Epoch: 020, Train Loss: 2.226, Val f1_micro: 0.193
Epoch: 040, Train Loss: 1.981, Val f1_micro: 0.220
Epoch: 060, Train Loss: 1.850, Val f1_micro: 0.222
Epoch: 080, Train Loss: 1.765, Val f1_micro: 0.224
Epoch: 100, Train Loss: 1.704, Val f1_micro: 0.229
Epoch: 120, Train Loss: 1.679, Val f1_micro: 0.227
Epoch: 140, Train Loss: 1.643, Val f1_micro: 0.230
Epoch: 160, Train Loss: 1.636, Val f1_micro: 0.232
Epoch: 180, Train Loss: 1.606, Val f1_micro: 0.232
Epoch: 200, Train Loss: 1.596, Val f1_micro: 0.233
Epoch: 220, Train Loss: 1.599, Val f1_micro: 0.234
Epoch: 240, Train Loss: 1.582, Val f1_micro: 0.233
Epoch: 260, Train Loss: 1.587, Val f1_micro: 0.230
Epoch: 280, Train Loss: 1.581, Val f1_micro: 0.233
Epoch: 300, Train Loss: 1.570, Val f1_micro: 0.236
Epoch: 320, Train Loss: 1.580, Val f1_micro: 0.235
Epoch: 340, Train Loss: 1.585, Val f1_micro: 0.234
Epoch: 360, Train Loss: 1.592, Val f1_micro: 0.234
Epoch: 380, Train Loss: 1.582, Val f1_micro: 0.231
Epoch: 400, Train Loss: 1.584, Val f1_micro: 0.235
Epoch: 420, Train Loss: 1.578, Val f1_micro: 0.232
Epoch: 440, Train Loss: 1.593, Val f1_micro: 0.232
Epoch: 460, Train Loss: 1.592, Val f1_micro: 0.229
Epoch: 480, Train Loss: 1.595, Val f1_micro: 0.233
Epoch: 500, Train Loss: 1.601, Val f1_micro: 0.233
f1-micro: 0.233, f1-macro: 0.208, f1-weighted: 0.205, , roc-auc: 0.661
##### RUN 3 #####
Epoch: 020, Train Loss: 2.252, Val f1_micro: 0.197
Epoch: 040, Train Loss: 1.978, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.847, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.766, Val f1_micro: 0.221
Epoch: 100, Train Loss: 1.723, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.667, Val f1_micro: 0.229
Epoch: 140, Train Loss: 1.650, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.629, Val f1_micro: 0.235
Epoch: 180, Train Loss: 1.600, Val f1_micro: 0.232
Epoch: 200, Train Loss: 1.605, Val f1_micro: 0.231
Epoch: 220, Train Loss: 1.598, Val f1_micro: 0.238
Epoch: 240, Train Loss: 1.595, Val f1_micro: 0.237
Epoch: 260, Train Loss: 1.585, Val f1_micro: 0.233
Epoch: 280, Train Loss: 1.568, Val f1_micro: 0.236
Epoch: 300, Train Loss: 1.571, Val f1_micro: 0.235
Epoch: 320, Train Loss: 1.583, Val f1_micro: 0.234
Epoch: 340, Train Loss: 1.577, Val f1_micro: 0.235
Epoch: 360, Train Loss: 1.591, Val f1_micro: 0.235
Epoch: 380, Train Loss: 1.577, Val f1_micro: 0.233
Epoch: 400, Train Loss: 1.591, Val f1_micro: 0.231
Epoch: 420, Train Loss: 1.580, Val f1_micro: 0.232
Epoch: 440, Train Loss: 1.590, Val f1_micro: 0.235
Epoch: 460, Train Loss: 1.579, Val f1_micro: 0.231
Epoch: 480, Train Loss: 1.587, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.598, Val f1_micro: 0.234
f1-micro: 0.234, f1-macro: 0.210, f1-weighted: 0.209, , roc-auc: 0.661
##### RUN 4 #####
Epoch: 020, Train Loss: 2.249, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.980, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.829, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.770, Val f1_micro: 0.226
Epoch: 100, Train Loss: 1.702, Val f1_micro: 0.227
Epoch: 120, Train Loss: 1.678, Val f1_micro: 0.228
Epoch: 140, Train Loss: 1.655, Val f1_micro: 0.227
Epoch: 160, Train Loss: 1.617, Val f1_micro: 0.235
Epoch: 180, Train Loss: 1.599, Val f1_micro: 0.234
Epoch: 200, Train Loss: 1.600, Val f1_micro: 0.233
Epoch: 220, Train Loss: 1.589, Val f1_micro: 0.233
Epoch: 240, Train Loss: 1.584, Val f1_micro: 0.234
Epoch: 260, Train Loss: 1.591, Val f1_micro: 0.234
Epoch: 280, Train Loss: 1.578, Val f1_micro: 0.234
Epoch: 300, Train Loss: 1.586, Val f1_micro: 0.234
Epoch: 320, Train Loss: 1.575, Val f1_micro: 0.236
Epoch: 340, Train Loss: 1.568, Val f1_micro: 0.231
Epoch: 360, Train Loss: 1.573, Val f1_micro: 0.231
Epoch: 380, Train Loss: 1.592, Val f1_micro: 0.237
Epoch: 400, Train Loss: 1.584, Val f1_micro: 0.236
Epoch: 420, Train Loss: 1.588, Val f1_micro: 0.232
Epoch: 440, Train Loss: 1.574, Val f1_micro: 0.234
Epoch: 460, Train Loss: 1.595, Val f1_micro: 0.234
Epoch: 480, Train Loss: 1.600, Val f1_micro: 0.233
Epoch: 500, Train Loss: 1.596, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.206, f1-weighted: 0.204, , roc-auc: 0.661
##### RUN 5 #####
Epoch: 020, Train Loss: 2.257, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.980, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.849, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.759, Val f1_micro: 0.226
Epoch: 100, Train Loss: 1.717, Val f1_micro: 0.226
Epoch: 120, Train Loss: 1.683, Val f1_micro: 0.229
Epoch: 140, Train Loss: 1.652, Val f1_micro: 0.235
Epoch: 160, Train Loss: 1.623, Val f1_micro: 0.229
Epoch: 180, Train Loss: 1.613, Val f1_micro: 0.232
Epoch: 200, Train Loss: 1.605, Val f1_micro: 0.233
Epoch: 220, Train Loss: 1.592, Val f1_micro: 0.233
Epoch: 240, Train Loss: 1.587, Val f1_micro: 0.233
Epoch: 260, Train Loss: 1.585, Val f1_micro: 0.234
Epoch: 280, Train Loss: 1.593, Val f1_micro: 0.235
Epoch: 300, Train Loss: 1.582, Val f1_micro: 0.234
Epoch: 320, Train Loss: 1.591, Val f1_micro: 0.237
Epoch: 340, Train Loss: 1.574, Val f1_micro: 0.231
Epoch: 360, Train Loss: 1.576, Val f1_micro: 0.234
Epoch: 380, Train Loss: 1.582, Val f1_micro: 0.233
Epoch: 400, Train Loss: 1.590, Val f1_micro: 0.235
Epoch: 420, Train Loss: 1.585, Val f1_micro: 0.233
Epoch: 440, Train Loss: 1.579, Val f1_micro: 0.234
Epoch: 460, Train Loss: 1.584, Val f1_micro: 0.235
Epoch: 480, Train Loss: 1.591, Val f1_micro: 0.232
Epoch: 500, Train Loss: 1.595, Val f1_micro: 0.232
f1-micro: 0.232, f1-macro: 0.208, f1-weighted: 0.206, , roc-auc: 0.662
########## Hyperparameters combination ##########
(1024, 0.5, 0.005, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.754, Val f1_micro: 0.228
Epoch: 040, Train Loss: 1.477, Val f1_micro: 0.245
Epoch: 060, Train Loss: 1.299, Val f1_micro: 0.264
Epoch: 080, Train Loss: 1.203, Val f1_micro: 0.268
Epoch: 100, Train Loss: 1.092, Val f1_micro: 0.275
Epoch: 120, Train Loss: 1.005, Val f1_micro: 0.282
Epoch: 140, Train Loss: 0.942, Val f1_micro: 0.284
Epoch: 160, Train Loss: 0.870, Val f1_micro: 0.286
Epoch: 180, Train Loss: 0.820, Val f1_micro: 0.289
Epoch: 200, Train Loss: 0.752, Val f1_micro: 0.292
Epoch: 220, Train Loss: 0.732, Val f1_micro: 0.296
Epoch: 240, Train Loss: 0.675, Val f1_micro: 0.301
Epoch: 260, Train Loss: 0.627, Val f1_micro: 0.304
Epoch: 280, Train Loss: 0.592, Val f1_micro: 0.305
Epoch: 300, Train Loss: 0.541, Val f1_micro: 0.307
Epoch: 320, Train Loss: 0.540, Val f1_micro: 0.308
Epoch: 340, Train Loss: 0.511, Val f1_micro: 0.307
Epoch: 360, Train Loss: 0.494, Val f1_micro: 0.308
Epoch: 380, Train Loss: 0.476, Val f1_micro: 0.312
Epoch: 400, Train Loss: 0.431, Val f1_micro: 0.312
Epoch: 420, Train Loss: 0.424, Val f1_micro: 0.314
Epoch: 440, Train Loss: 0.410, Val f1_micro: 0.315
Epoch: 460, Train Loss: 0.382, Val f1_micro: 0.316
Epoch: 480, Train Loss: 0.376, Val f1_micro: 0.314
Epoch: 500, Train Loss: 0.353, Val f1_micro: 0.317
f1-micro: 0.317, f1-macro: 0.311, f1-weighted: 0.318, , roc-auc: 0.686
##### RUN 2 #####
Epoch: 020, Train Loss: 1.730, Val f1_micro: 0.226
Epoch: 040, Train Loss: 1.457, Val f1_micro: 0.250
Epoch: 060, Train Loss: 1.292, Val f1_micro: 0.259
Epoch: 080, Train Loss: 1.192, Val f1_micro: 0.266
Epoch: 100, Train Loss: 1.086, Val f1_micro: 0.273
Epoch: 120, Train Loss: 1.002, Val f1_micro: 0.282
Epoch: 140, Train Loss: 0.909, Val f1_micro: 0.283
Epoch: 160, Train Loss: 0.877, Val f1_micro: 0.286
Epoch: 180, Train Loss: 0.818, Val f1_micro: 0.291
Epoch: 200, Train Loss: 0.760, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.712, Val f1_micro: 0.298
Epoch: 240, Train Loss: 0.679, Val f1_micro: 0.296
Epoch: 260, Train Loss: 0.608, Val f1_micro: 0.301
Epoch: 280, Train Loss: 0.587, Val f1_micro: 0.303
Epoch: 300, Train Loss: 0.570, Val f1_micro: 0.305
Epoch: 320, Train Loss: 0.525, Val f1_micro: 0.309
Epoch: 340, Train Loss: 0.500, Val f1_micro: 0.309
Epoch: 360, Train Loss: 0.466, Val f1_micro: 0.311
Epoch: 380, Train Loss: 0.468, Val f1_micro: 0.310
Epoch: 400, Train Loss: 0.438, Val f1_micro: 0.313
Epoch: 420, Train Loss: 0.420, Val f1_micro: 0.313
Epoch: 440, Train Loss: 0.420, Val f1_micro: 0.312
Epoch: 460, Train Loss: 0.384, Val f1_micro: 0.316
Epoch: 480, Train Loss: 0.380, Val f1_micro: 0.312
Epoch: 500, Train Loss: 0.378, Val f1_micro: 0.316
f1-micro: 0.316, f1-macro: 0.311, f1-weighted: 0.317, , roc-auc: 0.685
##### RUN 3 #####
Epoch: 020, Train Loss: 1.750, Val f1_micro: 0.227
Epoch: 040, Train Loss: 1.469, Val f1_micro: 0.247
Epoch: 060, Train Loss: 1.309, Val f1_micro: 0.259
Epoch: 080, Train Loss: 1.199, Val f1_micro: 0.266
Epoch: 100, Train Loss: 1.068, Val f1_micro: 0.277
Epoch: 120, Train Loss: 1.001, Val f1_micro: 0.278
Epoch: 140, Train Loss: 0.978, Val f1_micro: 0.282
Epoch: 160, Train Loss: 0.868, Val f1_micro: 0.285
Epoch: 180, Train Loss: 0.812, Val f1_micro: 0.292
Epoch: 200, Train Loss: 0.787, Val f1_micro: 0.291
Epoch: 220, Train Loss: 0.727, Val f1_micro: 0.297
Epoch: 240, Train Loss: 0.686, Val f1_micro: 0.296
Epoch: 260, Train Loss: 0.651, Val f1_micro: 0.303
Epoch: 280, Train Loss: 0.591, Val f1_micro: 0.302
Epoch: 300, Train Loss: 0.577, Val f1_micro: 0.304
Epoch: 320, Train Loss: 0.545, Val f1_micro: 0.307
Epoch: 340, Train Loss: 0.499, Val f1_micro: 0.309
Epoch: 360, Train Loss: 0.490, Val f1_micro: 0.307
Epoch: 380, Train Loss: 0.459, Val f1_micro: 0.311
Epoch: 400, Train Loss: 0.435, Val f1_micro: 0.314
Epoch: 420, Train Loss: 0.422, Val f1_micro: 0.310
Epoch: 440, Train Loss: 0.397, Val f1_micro: 0.315
Epoch: 460, Train Loss: 0.388, Val f1_micro: 0.313
Epoch: 480, Train Loss: 0.369, Val f1_micro: 0.317
Epoch: 500, Train Loss: 0.352, Val f1_micro: 0.313
f1-micro: 0.313, f1-macro: 0.308, f1-weighted: 0.314, , roc-auc: 0.685
##### RUN 4 #####
Epoch: 020, Train Loss: 1.743, Val f1_micro: 0.229
Epoch: 040, Train Loss: 1.473, Val f1_micro: 0.246
Epoch: 060, Train Loss: 1.308, Val f1_micro: 0.264
Epoch: 080, Train Loss: 1.198, Val f1_micro: 0.267
Epoch: 100, Train Loss: 1.081, Val f1_micro: 0.274
Epoch: 120, Train Loss: 1.005, Val f1_micro: 0.281
Epoch: 140, Train Loss: 0.946, Val f1_micro: 0.284
Epoch: 160, Train Loss: 0.861, Val f1_micro: 0.290
Epoch: 180, Train Loss: 0.834, Val f1_micro: 0.285
Epoch: 200, Train Loss: 0.766, Val f1_micro: 0.293
Epoch: 220, Train Loss: 0.730, Val f1_micro: 0.295
Epoch: 240, Train Loss: 0.675, Val f1_micro: 0.297
Epoch: 260, Train Loss: 0.619, Val f1_micro: 0.301
Epoch: 280, Train Loss: 0.592, Val f1_micro: 0.304
Epoch: 300, Train Loss: 0.570, Val f1_micro: 0.304
Epoch: 320, Train Loss: 0.550, Val f1_micro: 0.308
Epoch: 340, Train Loss: 0.512, Val f1_micro: 0.311
Epoch: 360, Train Loss: 0.491, Val f1_micro: 0.305
Epoch: 380, Train Loss: 0.450, Val f1_micro: 0.314
Epoch: 400, Train Loss: 0.441, Val f1_micro: 0.316
Epoch: 420, Train Loss: 0.416, Val f1_micro: 0.314
Epoch: 440, Train Loss: 0.393, Val f1_micro: 0.315
Epoch: 460, Train Loss: 0.386, Val f1_micro: 0.315
Epoch: 480, Train Loss: 0.370, Val f1_micro: 0.312
Epoch: 500, Train Loss: 0.355, Val f1_micro: 0.316
f1-micro: 0.316, f1-macro: 0.310, f1-weighted: 0.316, , roc-auc: 0.687
##### RUN 5 #####
Epoch: 020, Train Loss: 1.758, Val f1_micro: 0.227
Epoch: 040, Train Loss: 1.467, Val f1_micro: 0.247
Epoch: 060, Train Loss: 1.317, Val f1_micro: 0.264
Epoch: 080, Train Loss: 1.189, Val f1_micro: 0.270
Epoch: 100, Train Loss: 1.071, Val f1_micro: 0.268
Epoch: 120, Train Loss: 1.006, Val f1_micro: 0.277
Epoch: 140, Train Loss: 0.939, Val f1_micro: 0.280
Epoch: 160, Train Loss: 0.892, Val f1_micro: 0.286
Epoch: 180, Train Loss: 0.833, Val f1_micro: 0.287
Epoch: 200, Train Loss: 0.775, Val f1_micro: 0.294
Epoch: 220, Train Loss: 0.715, Val f1_micro: 0.300
Epoch: 240, Train Loss: 0.690, Val f1_micro: 0.297
Epoch: 260, Train Loss: 0.618, Val f1_micro: 0.300
Epoch: 280, Train Loss: 0.594, Val f1_micro: 0.301
Epoch: 300, Train Loss: 0.587, Val f1_micro: 0.309
Epoch: 320, Train Loss: 0.541, Val f1_micro: 0.309
Epoch: 340, Train Loss: 0.525, Val f1_micro: 0.313
Epoch: 360, Train Loss: 0.485, Val f1_micro: 0.313
Epoch: 380, Train Loss: 0.466, Val f1_micro: 0.314
Epoch: 400, Train Loss: 0.432, Val f1_micro: 0.314
Epoch: 420, Train Loss: 0.415, Val f1_micro: 0.314
Epoch: 440, Train Loss: 0.397, Val f1_micro: 0.315
Epoch: 460, Train Loss: 0.375, Val f1_micro: 0.317
Epoch: 480, Train Loss: 0.375, Val f1_micro: 0.316
Epoch: 500, Train Loss: 0.351, Val f1_micro: 0.318
f1-micro: 0.318, f1-macro: 0.311, f1-weighted: 0.317, , roc-auc: 0.686
########## Hyperparameters combination ##########
(1024, 0.5, 0.005, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.748, Val f1_micro: 0.216
Epoch: 040, Train Loss: 1.484, Val f1_micro: 0.239
Epoch: 060, Train Loss: 1.352, Val f1_micro: 0.252
Epoch: 080, Train Loss: 1.257, Val f1_micro: 0.257
Epoch: 100, Train Loss: 1.173, Val f1_micro: 0.266
Epoch: 120, Train Loss: 1.105, Val f1_micro: 0.269
Epoch: 140, Train Loss: 1.055, Val f1_micro: 0.273
Epoch: 160, Train Loss: 1.007, Val f1_micro: 0.275
Epoch: 180, Train Loss: 0.969, Val f1_micro: 0.276
Epoch: 200, Train Loss: 0.923, Val f1_micro: 0.285
Epoch: 220, Train Loss: 0.909, Val f1_micro: 0.282
Epoch: 240, Train Loss: 0.859, Val f1_micro: 0.286
Epoch: 260, Train Loss: 0.855, Val f1_micro: 0.287
Epoch: 280, Train Loss: 0.834, Val f1_micro: 0.289
Epoch: 300, Train Loss: 0.785, Val f1_micro: 0.291
Epoch: 320, Train Loss: 0.785, Val f1_micro: 0.295
Epoch: 340, Train Loss: 0.745, Val f1_micro: 0.299
Epoch: 360, Train Loss: 0.723, Val f1_micro: 0.296
Epoch: 380, Train Loss: 0.699, Val f1_micro: 0.296
Epoch: 400, Train Loss: 0.713, Val f1_micro: 0.302
Epoch: 420, Train Loss: 0.685, Val f1_micro: 0.304
Epoch: 440, Train Loss: 0.657, Val f1_micro: 0.304
Epoch: 460, Train Loss: 0.658, Val f1_micro: 0.301
Epoch: 480, Train Loss: 0.676, Val f1_micro: 0.305
Epoch: 500, Train Loss: 0.653, Val f1_micro: 0.304
f1-micro: 0.304, f1-macro: 0.297, f1-weighted: 0.302, , roc-auc: 0.683
##### RUN 2 #####
Epoch: 020, Train Loss: 1.766, Val f1_micro: 0.224
Epoch: 040, Train Loss: 1.513, Val f1_micro: 0.242
Epoch: 060, Train Loss: 1.359, Val f1_micro: 0.247
Epoch: 080, Train Loss: 1.235, Val f1_micro: 0.254
Epoch: 100, Train Loss: 1.167, Val f1_micro: 0.262
Epoch: 120, Train Loss: 1.104, Val f1_micro: 0.271
Epoch: 140, Train Loss: 1.032, Val f1_micro: 0.273
Epoch: 160, Train Loss: 1.000, Val f1_micro: 0.275
Epoch: 180, Train Loss: 0.960, Val f1_micro: 0.280
Epoch: 200, Train Loss: 0.934, Val f1_micro: 0.287
Epoch: 220, Train Loss: 0.879, Val f1_micro: 0.286
Epoch: 240, Train Loss: 0.861, Val f1_micro: 0.287
Epoch: 260, Train Loss: 0.844, Val f1_micro: 0.289
Epoch: 280, Train Loss: 0.799, Val f1_micro: 0.296
Epoch: 300, Train Loss: 0.777, Val f1_micro: 0.299
Epoch: 320, Train Loss: 0.775, Val f1_micro: 0.297
Epoch: 340, Train Loss: 0.739, Val f1_micro: 0.302
Epoch: 360, Train Loss: 0.739, Val f1_micro: 0.303
Epoch: 380, Train Loss: 0.719, Val f1_micro: 0.302
Epoch: 400, Train Loss: 0.704, Val f1_micro: 0.305
Epoch: 420, Train Loss: 0.670, Val f1_micro: 0.305
Epoch: 440, Train Loss: 0.676, Val f1_micro: 0.307
Epoch: 460, Train Loss: 0.647, Val f1_micro: 0.305
Epoch: 480, Train Loss: 0.638, Val f1_micro: 0.307
Epoch: 500, Train Loss: 0.637, Val f1_micro: 0.311
f1-micro: 0.311, f1-macro: 0.303, f1-weighted: 0.309, , roc-auc: 0.683
##### RUN 3 #####
Epoch: 020, Train Loss: 1.761, Val f1_micro: 0.226
Epoch: 040, Train Loss: 1.487, Val f1_micro: 0.239
Epoch: 060, Train Loss: 1.348, Val f1_micro: 0.250
Epoch: 080, Train Loss: 1.250, Val f1_micro: 0.260
Epoch: 100, Train Loss: 1.164, Val f1_micro: 0.264
Epoch: 120, Train Loss: 1.116, Val f1_micro: 0.267
Epoch: 140, Train Loss: 1.059, Val f1_micro: 0.269
Epoch: 160, Train Loss: 1.007, Val f1_micro: 0.277
Epoch: 180, Train Loss: 0.949, Val f1_micro: 0.274
Epoch: 200, Train Loss: 0.919, Val f1_micro: 0.282
Epoch: 220, Train Loss: 0.884, Val f1_micro: 0.285
Epoch: 240, Train Loss: 0.856, Val f1_micro: 0.290
Epoch: 260, Train Loss: 0.819, Val f1_micro: 0.288
Epoch: 280, Train Loss: 0.799, Val f1_micro: 0.292
Epoch: 300, Train Loss: 0.795, Val f1_micro: 0.292
Epoch: 320, Train Loss: 0.766, Val f1_micro: 0.292
Epoch: 340, Train Loss: 0.753, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.742, Val f1_micro: 0.296
Epoch: 380, Train Loss: 0.712, Val f1_micro: 0.303
Epoch: 400, Train Loss: 0.695, Val f1_micro: 0.301
Epoch: 420, Train Loss: 0.685, Val f1_micro: 0.302
Epoch: 440, Train Loss: 0.688, Val f1_micro: 0.303
Epoch: 460, Train Loss: 0.647, Val f1_micro: 0.307
Epoch: 480, Train Loss: 0.653, Val f1_micro: 0.302
Epoch: 500, Train Loss: 0.643, Val f1_micro: 0.308
f1-micro: 0.308, f1-macro: 0.301, f1-weighted: 0.306, , roc-auc: 0.684
##### RUN 4 #####
Epoch: 020, Train Loss: 1.750, Val f1_micro: 0.222
Epoch: 040, Train Loss: 1.492, Val f1_micro: 0.237
Epoch: 060, Train Loss: 1.334, Val f1_micro: 0.252
Epoch: 080, Train Loss: 1.224, Val f1_micro: 0.260
Epoch: 100, Train Loss: 1.175, Val f1_micro: 0.268
Epoch: 120, Train Loss: 1.102, Val f1_micro: 0.270
Epoch: 140, Train Loss: 1.051, Val f1_micro: 0.273
Epoch: 160, Train Loss: 1.010, Val f1_micro: 0.276
Epoch: 180, Train Loss: 0.951, Val f1_micro: 0.279
Epoch: 200, Train Loss: 0.925, Val f1_micro: 0.282
Epoch: 220, Train Loss: 0.883, Val f1_micro: 0.286
Epoch: 240, Train Loss: 0.862, Val f1_micro: 0.290
Epoch: 260, Train Loss: 0.846, Val f1_micro: 0.289
Epoch: 280, Train Loss: 0.812, Val f1_micro: 0.297
Epoch: 300, Train Loss: 0.795, Val f1_micro: 0.298
Epoch: 320, Train Loss: 0.769, Val f1_micro: 0.299
Epoch: 340, Train Loss: 0.747, Val f1_micro: 0.298
Epoch: 360, Train Loss: 0.713, Val f1_micro: 0.301
Epoch: 380, Train Loss: 0.718, Val f1_micro: 0.302
Epoch: 400, Train Loss: 0.697, Val f1_micro: 0.303
Epoch: 420, Train Loss: 0.680, Val f1_micro: 0.303
Epoch: 440, Train Loss: 0.679, Val f1_micro: 0.309
Epoch: 460, Train Loss: 0.676, Val f1_micro: 0.305
Epoch: 480, Train Loss: 0.644, Val f1_micro: 0.309
Epoch: 500, Train Loss: 0.645, Val f1_micro: 0.308
f1-micro: 0.308, f1-macro: 0.301, f1-weighted: 0.307, , roc-auc: 0.683
##### RUN 5 #####
Epoch: 020, Train Loss: 1.774, Val f1_micro: 0.223
Epoch: 040, Train Loss: 1.504, Val f1_micro: 0.237
Epoch: 060, Train Loss: 1.357, Val f1_micro: 0.253
Epoch: 080, Train Loss: 1.266, Val f1_micro: 0.260
Epoch: 100, Train Loss: 1.174, Val f1_micro: 0.265
Epoch: 120, Train Loss: 1.105, Val f1_micro: 0.268
Epoch: 140, Train Loss: 1.052, Val f1_micro: 0.271
Epoch: 160, Train Loss: 1.013, Val f1_micro: 0.273
Epoch: 180, Train Loss: 0.971, Val f1_micro: 0.280
Epoch: 200, Train Loss: 0.898, Val f1_micro: 0.282
Epoch: 220, Train Loss: 0.899, Val f1_micro: 0.288
Epoch: 240, Train Loss: 0.878, Val f1_micro: 0.286
Epoch: 260, Train Loss: 0.845, Val f1_micro: 0.289
Epoch: 280, Train Loss: 0.812, Val f1_micro: 0.291
Epoch: 300, Train Loss: 0.799, Val f1_micro: 0.292
Epoch: 320, Train Loss: 0.773, Val f1_micro: 0.297
Epoch: 340, Train Loss: 0.736, Val f1_micro: 0.299
Epoch: 360, Train Loss: 0.729, Val f1_micro: 0.296
Epoch: 380, Train Loss: 0.727, Val f1_micro: 0.300
Epoch: 400, Train Loss: 0.690, Val f1_micro: 0.305
Epoch: 420, Train Loss: 0.686, Val f1_micro: 0.304
Epoch: 440, Train Loss: 0.671, Val f1_micro: 0.304
Epoch: 460, Train Loss: 0.653, Val f1_micro: 0.307
Epoch: 480, Train Loss: 0.657, Val f1_micro: 0.310
Epoch: 500, Train Loss: 0.656, Val f1_micro: 0.307
f1-micro: 0.307, f1-macro: 0.301, f1-weighted: 0.307, , roc-auc: 0.685
########## Hyperparameters combination ##########
(1024, 0.5, 0.005, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.747, Val f1_micro: 0.220
Epoch: 040, Train Loss: 1.513, Val f1_micro: 0.236
Epoch: 060, Train Loss: 1.391, Val f1_micro: 0.244
Epoch: 080, Train Loss: 1.315, Val f1_micro: 0.257
Epoch: 100, Train Loss: 1.254, Val f1_micro: 0.268
Epoch: 120, Train Loss: 1.221, Val f1_micro: 0.268
Epoch: 140, Train Loss: 1.165, Val f1_micro: 0.267
Epoch: 160, Train Loss: 1.139, Val f1_micro: 0.272
Epoch: 180, Train Loss: 1.099, Val f1_micro: 0.271
Epoch: 200, Train Loss: 1.076, Val f1_micro: 0.269
Epoch: 220, Train Loss: 1.044, Val f1_micro: 0.275
Epoch: 240, Train Loss: 1.050, Val f1_micro: 0.275
Epoch: 260, Train Loss: 1.009, Val f1_micro: 0.275
Epoch: 280, Train Loss: 1.023, Val f1_micro: 0.280
Epoch: 300, Train Loss: 0.990, Val f1_micro: 0.281
Epoch: 320, Train Loss: 0.977, Val f1_micro: 0.280
Epoch: 340, Train Loss: 0.960, Val f1_micro: 0.282
Epoch: 360, Train Loss: 0.946, Val f1_micro: 0.284
Epoch: 380, Train Loss: 0.944, Val f1_micro: 0.285
Epoch: 400, Train Loss: 0.915, Val f1_micro: 0.286
Epoch: 420, Train Loss: 0.916, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.924, Val f1_micro: 0.285
Epoch: 460, Train Loss: 0.890, Val f1_micro: 0.288
Epoch: 480, Train Loss: 0.891, Val f1_micro: 0.288
Epoch: 500, Train Loss: 0.878, Val f1_micro: 0.290
f1-micro: 0.290, f1-macro: 0.283, f1-weighted: 0.287, , roc-auc: 0.677
##### RUN 2 #####
Epoch: 020, Train Loss: 1.767, Val f1_micro: 0.225
Epoch: 040, Train Loss: 1.515, Val f1_micro: 0.237
Epoch: 060, Train Loss: 1.393, Val f1_micro: 0.254
Epoch: 080, Train Loss: 1.326, Val f1_micro: 0.257
Epoch: 100, Train Loss: 1.247, Val f1_micro: 0.264
Epoch: 120, Train Loss: 1.210, Val f1_micro: 0.264
Epoch: 140, Train Loss: 1.156, Val f1_micro: 0.266
Epoch: 160, Train Loss: 1.121, Val f1_micro: 0.266
Epoch: 180, Train Loss: 1.100, Val f1_micro: 0.271
Epoch: 200, Train Loss: 1.071, Val f1_micro: 0.273
Epoch: 220, Train Loss: 1.047, Val f1_micro: 0.273
Epoch: 240, Train Loss: 1.018, Val f1_micro: 0.273
Epoch: 260, Train Loss: 1.017, Val f1_micro: 0.276
Epoch: 280, Train Loss: 1.017, Val f1_micro: 0.279
Epoch: 300, Train Loss: 0.981, Val f1_micro: 0.281
Epoch: 320, Train Loss: 0.966, Val f1_micro: 0.281
Epoch: 340, Train Loss: 0.974, Val f1_micro: 0.286
Epoch: 360, Train Loss: 0.943, Val f1_micro: 0.282
Epoch: 380, Train Loss: 0.962, Val f1_micro: 0.286
Epoch: 400, Train Loss: 0.925, Val f1_micro: 0.283
Epoch: 420, Train Loss: 0.918, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.908, Val f1_micro: 0.286
Epoch: 460, Train Loss: 0.892, Val f1_micro: 0.289
Epoch: 480, Train Loss: 0.897, Val f1_micro: 0.287
Epoch: 500, Train Loss: 0.893, Val f1_micro: 0.289
f1-micro: 0.289, f1-macro: 0.282, f1-weighted: 0.286, , roc-auc: 0.677
##### RUN 3 #####
Epoch: 020, Train Loss: 1.761, Val f1_micro: 0.217
Epoch: 040, Train Loss: 1.517, Val f1_micro: 0.238
Epoch: 060, Train Loss: 1.403, Val f1_micro: 0.248
Epoch: 080, Train Loss: 1.344, Val f1_micro: 0.259
Epoch: 100, Train Loss: 1.242, Val f1_micro: 0.261
Epoch: 120, Train Loss: 1.207, Val f1_micro: 0.261
Epoch: 140, Train Loss: 1.164, Val f1_micro: 0.268
Epoch: 160, Train Loss: 1.131, Val f1_micro: 0.269
Epoch: 180, Train Loss: 1.125, Val f1_micro: 0.269
Epoch: 200, Train Loss: 1.087, Val f1_micro: 0.271
Epoch: 220, Train Loss: 1.063, Val f1_micro: 0.275
Epoch: 240, Train Loss: 1.042, Val f1_micro: 0.276
Epoch: 260, Train Loss: 1.019, Val f1_micro: 0.276
Epoch: 280, Train Loss: 1.010, Val f1_micro: 0.279
Epoch: 300, Train Loss: 0.997, Val f1_micro: 0.283
Epoch: 320, Train Loss: 0.971, Val f1_micro: 0.277
Epoch: 340, Train Loss: 0.955, Val f1_micro: 0.283
Epoch: 360, Train Loss: 0.952, Val f1_micro: 0.285
Epoch: 380, Train Loss: 0.940, Val f1_micro: 0.282
Epoch: 400, Train Loss: 0.943, Val f1_micro: 0.286
Epoch: 420, Train Loss: 0.923, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.894, Val f1_micro: 0.285
Epoch: 460, Train Loss: 0.899, Val f1_micro: 0.288
Epoch: 480, Train Loss: 0.899, Val f1_micro: 0.287
Epoch: 500, Train Loss: 0.879, Val f1_micro: 0.288
f1-micro: 0.288, f1-macro: 0.281, f1-weighted: 0.285, , roc-auc: 0.677
##### RUN 4 #####
Epoch: 020, Train Loss: 1.762, Val f1_micro: 0.223
Epoch: 040, Train Loss: 1.522, Val f1_micro: 0.241
Epoch: 060, Train Loss: 1.385, Val f1_micro: 0.252
Epoch: 080, Train Loss: 1.312, Val f1_micro: 0.257
Epoch: 100, Train Loss: 1.236, Val f1_micro: 0.257
Epoch: 120, Train Loss: 1.196, Val f1_micro: 0.267
Epoch: 140, Train Loss: 1.167, Val f1_micro: 0.267
Epoch: 160, Train Loss: 1.126, Val f1_micro: 0.268
Epoch: 180, Train Loss: 1.098, Val f1_micro: 0.266
Epoch: 200, Train Loss: 1.071, Val f1_micro: 0.272
Epoch: 220, Train Loss: 1.034, Val f1_micro: 0.276
Epoch: 240, Train Loss: 1.042, Val f1_micro: 0.274
Epoch: 260, Train Loss: 1.027, Val f1_micro: 0.279
Epoch: 280, Train Loss: 1.021, Val f1_micro: 0.279
Epoch: 300, Train Loss: 0.977, Val f1_micro: 0.280
Epoch: 320, Train Loss: 0.970, Val f1_micro: 0.281
Epoch: 340, Train Loss: 0.959, Val f1_micro: 0.287
Epoch: 360, Train Loss: 0.961, Val f1_micro: 0.284
Epoch: 380, Train Loss: 0.941, Val f1_micro: 0.288
Epoch: 400, Train Loss: 0.930, Val f1_micro: 0.285
Epoch: 420, Train Loss: 0.935, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.912, Val f1_micro: 0.288
Epoch: 460, Train Loss: 0.910, Val f1_micro: 0.289
Epoch: 480, Train Loss: 0.896, Val f1_micro: 0.291
Epoch: 500, Train Loss: 0.873, Val f1_micro: 0.288
f1-micro: 0.288, f1-macro: 0.282, f1-weighted: 0.286, , roc-auc: 0.678
##### RUN 5 #####
Epoch: 020, Train Loss: 1.768, Val f1_micro: 0.222
Epoch: 040, Train Loss: 1.510, Val f1_micro: 0.240
Epoch: 060, Train Loss: 1.390, Val f1_micro: 0.252
Epoch: 080, Train Loss: 1.315, Val f1_micro: 0.257
Epoch: 100, Train Loss: 1.239, Val f1_micro: 0.265
Epoch: 120, Train Loss: 1.186, Val f1_micro: 0.266
Epoch: 140, Train Loss: 1.172, Val f1_micro: 0.268
Epoch: 160, Train Loss: 1.134, Val f1_micro: 0.270
Epoch: 180, Train Loss: 1.112, Val f1_micro: 0.268
Epoch: 200, Train Loss: 1.080, Val f1_micro: 0.273
Epoch: 220, Train Loss: 1.068, Val f1_micro: 0.273
Epoch: 240, Train Loss: 1.045, Val f1_micro: 0.272
Epoch: 260, Train Loss: 1.025, Val f1_micro: 0.277
Epoch: 280, Train Loss: 0.999, Val f1_micro: 0.278
Epoch: 300, Train Loss: 0.977, Val f1_micro: 0.281
Epoch: 320, Train Loss: 0.956, Val f1_micro: 0.280
Epoch: 340, Train Loss: 0.971, Val f1_micro: 0.281
Epoch: 360, Train Loss: 0.962, Val f1_micro: 0.284
Epoch: 380, Train Loss: 0.952, Val f1_micro: 0.281
Epoch: 400, Train Loss: 0.925, Val f1_micro: 0.282
Epoch: 420, Train Loss: 0.894, Val f1_micro: 0.289
Epoch: 440, Train Loss: 0.912, Val f1_micro: 0.286
Epoch: 460, Train Loss: 0.909, Val f1_micro: 0.285
Epoch: 480, Train Loss: 0.898, Val f1_micro: 0.286
Epoch: 500, Train Loss: 0.881, Val f1_micro: 0.285
f1-micro: 0.285, f1-macro: 0.279, f1-weighted: 0.282, , roc-auc: 0.677
########## Hyperparameters combination ##########
(1024, 0.5, 0.005, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.783, Val f1_micro: 0.221
Epoch: 040, Train Loss: 1.626, Val f1_micro: 0.227
Epoch: 060, Train Loss: 1.593, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.593, Val f1_micro: 0.231
Epoch: 100, Train Loss: 1.589, Val f1_micro: 0.233
Epoch: 120, Train Loss: 1.600, Val f1_micro: 0.240
Epoch: 140, Train Loss: 1.618, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.629, Val f1_micro: 0.233
Epoch: 180, Train Loss: 1.613, Val f1_micro: 0.228
Epoch: 200, Train Loss: 1.636, Val f1_micro: 0.231
Epoch: 220, Train Loss: 1.637, Val f1_micro: 0.224
Epoch: 240, Train Loss: 1.642, Val f1_micro: 0.226
Epoch: 260, Train Loss: 1.651, Val f1_micro: 0.230
Epoch: 280, Train Loss: 1.643, Val f1_micro: 0.232
Epoch: 300, Train Loss: 1.632, Val f1_micro: 0.225
Epoch: 320, Train Loss: 1.633, Val f1_micro: 0.221
Epoch: 340, Train Loss: 1.635, Val f1_micro: 0.228
Epoch: 360, Train Loss: 1.637, Val f1_micro: 0.230
Epoch: 380, Train Loss: 1.639, Val f1_micro: 0.232
Epoch: 400, Train Loss: 1.642, Val f1_micro: 0.227
Epoch: 420, Train Loss: 1.633, Val f1_micro: 0.225
Epoch: 440, Train Loss: 1.640, Val f1_micro: 0.226
Epoch: 460, Train Loss: 1.640, Val f1_micro: 0.225
Epoch: 480, Train Loss: 1.634, Val f1_micro: 0.225
Epoch: 500, Train Loss: 1.624, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.200, f1-weighted: 0.198, , roc-auc: 0.649
##### RUN 2 #####
Epoch: 020, Train Loss: 1.773, Val f1_micro: 0.224
Epoch: 040, Train Loss: 1.625, Val f1_micro: 0.225
Epoch: 060, Train Loss: 1.607, Val f1_micro: 0.233
Epoch: 080, Train Loss: 1.609, Val f1_micro: 0.236
Epoch: 100, Train Loss: 1.604, Val f1_micro: 0.228
Epoch: 120, Train Loss: 1.610, Val f1_micro: 0.233
Epoch: 140, Train Loss: 1.618, Val f1_micro: 0.237
Epoch: 160, Train Loss: 1.616, Val f1_micro: 0.231
Epoch: 180, Train Loss: 1.626, Val f1_micro: 0.234
Epoch: 200, Train Loss: 1.631, Val f1_micro: 0.231
Epoch: 220, Train Loss: 1.636, Val f1_micro: 0.236
Epoch: 240, Train Loss: 1.628, Val f1_micro: 0.231
Epoch: 260, Train Loss: 1.641, Val f1_micro: 0.227
Epoch: 280, Train Loss: 1.639, Val f1_micro: 0.228
Epoch: 300, Train Loss: 1.633, Val f1_micro: 0.226
Epoch: 320, Train Loss: 1.633, Val f1_micro: 0.223
Epoch: 340, Train Loss: 1.646, Val f1_micro: 0.229
Epoch: 360, Train Loss: 1.640, Val f1_micro: 0.219
Epoch: 380, Train Loss: 1.641, Val f1_micro: 0.222
Epoch: 400, Train Loss: 1.641, Val f1_micro: 0.230
Epoch: 420, Train Loss: 1.629, Val f1_micro: 0.229
Epoch: 440, Train Loss: 1.632, Val f1_micro: 0.229
Epoch: 460, Train Loss: 1.646, Val f1_micro: 0.226
Epoch: 480, Train Loss: 1.626, Val f1_micro: 0.225
Epoch: 500, Train Loss: 1.630, Val f1_micro: 0.231
f1-micro: 0.231, f1-macro: 0.201, f1-weighted: 0.198, , roc-auc: 0.648
##### RUN 3 #####
Epoch: 020, Train Loss: 1.792, Val f1_micro: 0.227
Epoch: 040, Train Loss: 1.628, Val f1_micro: 0.231
Epoch: 060, Train Loss: 1.595, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.582, Val f1_micro: 0.230
Epoch: 100, Train Loss: 1.597, Val f1_micro: 0.231
Epoch: 120, Train Loss: 1.595, Val f1_micro: 0.236
Epoch: 140, Train Loss: 1.606, Val f1_micro: 0.236
Epoch: 160, Train Loss: 1.620, Val f1_micro: 0.232
Epoch: 180, Train Loss: 1.635, Val f1_micro: 0.225
Epoch: 200, Train Loss: 1.637, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.638, Val f1_micro: 0.229
Epoch: 240, Train Loss: 1.637, Val f1_micro: 0.232
Epoch: 260, Train Loss: 1.636, Val f1_micro: 0.231
Epoch: 280, Train Loss: 1.632, Val f1_micro: 0.228
Epoch: 300, Train Loss: 1.642, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.642, Val f1_micro: 0.225
Epoch: 340, Train Loss: 1.642, Val f1_micro: 0.234
Epoch: 360, Train Loss: 1.641, Val f1_micro: 0.225
Epoch: 380, Train Loss: 1.633, Val f1_micro: 0.220
Epoch: 400, Train Loss: 1.643, Val f1_micro: 0.231
Epoch: 420, Train Loss: 1.634, Val f1_micro: 0.217
Epoch: 440, Train Loss: 1.628, Val f1_micro: 0.227
Epoch: 460, Train Loss: 1.641, Val f1_micro: 0.230
Epoch: 480, Train Loss: 1.633, Val f1_micro: 0.230
Epoch: 500, Train Loss: 1.640, Val f1_micro: 0.223
f1-micro: 0.223, f1-macro: 0.189, f1-weighted: 0.186, , roc-auc: 0.649
##### RUN 4 #####
Epoch: 020, Train Loss: 1.781, Val f1_micro: 0.226
Epoch: 040, Train Loss: 1.619, Val f1_micro: 0.228
Epoch: 060, Train Loss: 1.595, Val f1_micro: 0.233
Epoch: 080, Train Loss: 1.588, Val f1_micro: 0.232
Epoch: 100, Train Loss: 1.608, Val f1_micro: 0.236
Epoch: 120, Train Loss: 1.601, Val f1_micro: 0.230
Epoch: 140, Train Loss: 1.620, Val f1_micro: 0.230
Epoch: 160, Train Loss: 1.618, Val f1_micro: 0.227
Epoch: 180, Train Loss: 1.614, Val f1_micro: 0.229
Epoch: 200, Train Loss: 1.624, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.631, Val f1_micro: 0.230
Epoch: 240, Train Loss: 1.619, Val f1_micro: 0.226
Epoch: 260, Train Loss: 1.634, Val f1_micro: 0.223
Epoch: 280, Train Loss: 1.636, Val f1_micro: 0.226
Epoch: 300, Train Loss: 1.634, Val f1_micro: 0.227
Epoch: 320, Train Loss: 1.642, Val f1_micro: 0.229
Epoch: 340, Train Loss: 1.636, Val f1_micro: 0.231
Epoch: 360, Train Loss: 1.641, Val f1_micro: 0.228
Epoch: 380, Train Loss: 1.646, Val f1_micro: 0.226
Epoch: 400, Train Loss: 1.643, Val f1_micro: 0.227
Epoch: 420, Train Loss: 1.631, Val f1_micro: 0.226
Epoch: 440, Train Loss: 1.631, Val f1_micro: 0.227
Epoch: 460, Train Loss: 1.650, Val f1_micro: 0.227
Epoch: 480, Train Loss: 1.641, Val f1_micro: 0.229
Epoch: 500, Train Loss: 1.631, Val f1_micro: 0.228
f1-micro: 0.228, f1-macro: 0.197, f1-weighted: 0.193, , roc-auc: 0.649
##### RUN 5 #####
Epoch: 020, Train Loss: 1.789, Val f1_micro: 0.228
Epoch: 040, Train Loss: 1.629, Val f1_micro: 0.229
Epoch: 060, Train Loss: 1.595, Val f1_micro: 0.235
Epoch: 080, Train Loss: 1.616, Val f1_micro: 0.233
Epoch: 100, Train Loss: 1.607, Val f1_micro: 0.236
Epoch: 120, Train Loss: 1.605, Val f1_micro: 0.229
Epoch: 140, Train Loss: 1.617, Val f1_micro: 0.232
Epoch: 160, Train Loss: 1.603, Val f1_micro: 0.232
Epoch: 180, Train Loss: 1.632, Val f1_micro: 0.233
Epoch: 200, Train Loss: 1.622, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.630, Val f1_micro: 0.224
Epoch: 240, Train Loss: 1.634, Val f1_micro: 0.231
Epoch: 260, Train Loss: 1.642, Val f1_micro: 0.228
Epoch: 280, Train Loss: 1.636, Val f1_micro: 0.229
Epoch: 300, Train Loss: 1.644, Val f1_micro: 0.229
Epoch: 320, Train Loss: 1.646, Val f1_micro: 0.232
Epoch: 340, Train Loss: 1.637, Val f1_micro: 0.227
Epoch: 360, Train Loss: 1.642, Val f1_micro: 0.226
Epoch: 380, Train Loss: 1.643, Val f1_micro: 0.219
Epoch: 400, Train Loss: 1.647, Val f1_micro: 0.225
Epoch: 420, Train Loss: 1.636, Val f1_micro: 0.228
Epoch: 440, Train Loss: 1.633, Val f1_micro: 0.232
Epoch: 460, Train Loss: 1.638, Val f1_micro: 0.229
Epoch: 480, Train Loss: 1.633, Val f1_micro: 0.226
Epoch: 500, Train Loss: 1.650, Val f1_micro: 0.226
f1-micro: 0.226, f1-macro: 0.201, f1-weighted: 0.198, , roc-auc: 0.649
########## Hyperparameters combination ##########
(1024, 0.5, 0.01, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.663, Val f1_micro: 0.227
Epoch: 040, Train Loss: 1.391, Val f1_micro: 0.252
Epoch: 060, Train Loss: 1.204, Val f1_micro: 0.267
Epoch: 080, Train Loss: 1.066, Val f1_micro: 0.268
Epoch: 100, Train Loss: 0.967, Val f1_micro: 0.277
Epoch: 120, Train Loss: 0.912, Val f1_micro: 0.281
Epoch: 140, Train Loss: 0.779, Val f1_micro: 0.288
Epoch: 160, Train Loss: 0.737, Val f1_micro: 0.288
Epoch: 180, Train Loss: 0.649, Val f1_micro: 0.298
Epoch: 200, Train Loss: 0.596, Val f1_micro: 0.300
Epoch: 220, Train Loss: 0.557, Val f1_micro: 0.311
Epoch: 240, Train Loss: 0.521, Val f1_micro: 0.305
Epoch: 260, Train Loss: 0.478, Val f1_micro: 0.311
Epoch: 280, Train Loss: 0.451, Val f1_micro: 0.316
Epoch: 300, Train Loss: 0.423, Val f1_micro: 0.314
Epoch: 320, Train Loss: 0.406, Val f1_micro: 0.314
Epoch: 340, Train Loss: 0.369, Val f1_micro: 0.314
Epoch: 360, Train Loss: 0.354, Val f1_micro: 0.317
Epoch: 380, Train Loss: 0.338, Val f1_micro: 0.318
Epoch: 400, Train Loss: 0.333, Val f1_micro: 0.322
Epoch: 420, Train Loss: 0.312, Val f1_micro: 0.320
Epoch: 440, Train Loss: 0.295, Val f1_micro: 0.319
Epoch: 460, Train Loss: 0.285, Val f1_micro: 0.319
Epoch: 480, Train Loss: 0.301, Val f1_micro: 0.320
Epoch: 500, Train Loss: 0.277, Val f1_micro: 0.320
f1-micro: 0.320, f1-macro: 0.314, f1-weighted: 0.321, , roc-auc: 0.690
##### RUN 2 #####
Epoch: 020, Train Loss: 1.677, Val f1_micro: 0.220
Epoch: 040, Train Loss: 1.386, Val f1_micro: 0.255
Epoch: 060, Train Loss: 1.203, Val f1_micro: 0.270
Epoch: 080, Train Loss: 1.066, Val f1_micro: 0.277
Epoch: 100, Train Loss: 0.973, Val f1_micro: 0.281
Epoch: 120, Train Loss: 0.878, Val f1_micro: 0.285
Epoch: 140, Train Loss: 0.779, Val f1_micro: 0.288
Epoch: 160, Train Loss: 0.704, Val f1_micro: 0.292
Epoch: 180, Train Loss: 0.658, Val f1_micro: 0.300
Epoch: 200, Train Loss: 0.598, Val f1_micro: 0.306
Epoch: 220, Train Loss: 0.541, Val f1_micro: 0.306
Epoch: 240, Train Loss: 0.487, Val f1_micro: 0.309
Epoch: 260, Train Loss: 0.465, Val f1_micro: 0.308
Epoch: 280, Train Loss: 0.447, Val f1_micro: 0.314
Epoch: 300, Train Loss: 0.406, Val f1_micro: 0.315
Epoch: 320, Train Loss: 0.403, Val f1_micro: 0.318
Epoch: 340, Train Loss: 0.367, Val f1_micro: 0.318
Epoch: 360, Train Loss: 0.356, Val f1_micro: 0.320
Epoch: 380, Train Loss: 0.347, Val f1_micro: 0.320
Epoch: 400, Train Loss: 0.319, Val f1_micro: 0.322
Epoch: 420, Train Loss: 0.320, Val f1_micro: 0.319
Epoch: 440, Train Loss: 0.293, Val f1_micro: 0.320
Epoch: 460, Train Loss: 0.298, Val f1_micro: 0.319
Epoch: 480, Train Loss: 0.273, Val f1_micro: 0.320
Epoch: 500, Train Loss: 0.254, Val f1_micro: 0.320
f1-micro: 0.320, f1-macro: 0.314, f1-weighted: 0.321, , roc-auc: 0.688
##### RUN 3 #####
Epoch: 020, Train Loss: 1.710, Val f1_micro: 0.224
Epoch: 040, Train Loss: 1.414, Val f1_micro: 0.256
Epoch: 060, Train Loss: 1.235, Val f1_micro: 0.258
Epoch: 080, Train Loss: 1.083, Val f1_micro: 0.271
Epoch: 100, Train Loss: 0.987, Val f1_micro: 0.281
Epoch: 120, Train Loss: 0.873, Val f1_micro: 0.283
Epoch: 140, Train Loss: 0.801, Val f1_micro: 0.286
Epoch: 160, Train Loss: 0.745, Val f1_micro: 0.289
Epoch: 180, Train Loss: 0.677, Val f1_micro: 0.298
Epoch: 200, Train Loss: 0.620, Val f1_micro: 0.301
Epoch: 220, Train Loss: 0.562, Val f1_micro: 0.306
Epoch: 240, Train Loss: 0.535, Val f1_micro: 0.309
Epoch: 260, Train Loss: 0.492, Val f1_micro: 0.308
Epoch: 280, Train Loss: 0.444, Val f1_micro: 0.311
Epoch: 300, Train Loss: 0.424, Val f1_micro: 0.311
Epoch: 320, Train Loss: 0.412, Val f1_micro: 0.314
Epoch: 340, Train Loss: 0.383, Val f1_micro: 0.319
Epoch: 360, Train Loss: 0.383, Val f1_micro: 0.314
Epoch: 380, Train Loss: 0.341, Val f1_micro: 0.319
Epoch: 400, Train Loss: 0.322, Val f1_micro: 0.315
Epoch: 420, Train Loss: 0.303, Val f1_micro: 0.317
Epoch: 440, Train Loss: 0.310, Val f1_micro: 0.312
Epoch: 460, Train Loss: 0.308, Val f1_micro: 0.317
Epoch: 480, Train Loss: 0.274, Val f1_micro: 0.317
Epoch: 500, Train Loss: 0.280, Val f1_micro: 0.320
f1-micro: 0.320, f1-macro: 0.314, f1-weighted: 0.320, , roc-auc: 0.688
##### RUN 4 #####
Epoch: 020, Train Loss: 1.692, Val f1_micro: 0.232
Epoch: 040, Train Loss: 1.385, Val f1_micro: 0.249
Epoch: 060, Train Loss: 1.219, Val f1_micro: 0.265
Epoch: 080, Train Loss: 1.078, Val f1_micro: 0.277
Epoch: 100, Train Loss: 0.968, Val f1_micro: 0.279
Epoch: 120, Train Loss: 0.873, Val f1_micro: 0.287
Epoch: 140, Train Loss: 0.790, Val f1_micro: 0.289
Epoch: 160, Train Loss: 0.718, Val f1_micro: 0.296
Epoch: 180, Train Loss: 0.676, Val f1_micro: 0.302
Epoch: 200, Train Loss: 0.595, Val f1_micro: 0.305
Epoch: 220, Train Loss: 0.571, Val f1_micro: 0.307
Epoch: 240, Train Loss: 0.519, Val f1_micro: 0.307
Epoch: 260, Train Loss: 0.476, Val f1_micro: 0.311
Epoch: 280, Train Loss: 0.444, Val f1_micro: 0.314
Epoch: 300, Train Loss: 0.433, Val f1_micro: 0.316
Epoch: 320, Train Loss: 0.412, Val f1_micro: 0.316
Epoch: 340, Train Loss: 0.399, Val f1_micro: 0.318
Epoch: 360, Train Loss: 0.381, Val f1_micro: 0.317
Epoch: 380, Train Loss: 0.357, Val f1_micro: 0.317
Epoch: 400, Train Loss: 0.331, Val f1_micro: 0.318
Epoch: 420, Train Loss: 0.330, Val f1_micro: 0.320
Epoch: 440, Train Loss: 0.301, Val f1_micro: 0.320
Epoch: 460, Train Loss: 0.309, Val f1_micro: 0.318
Epoch: 480, Train Loss: 0.282, Val f1_micro: 0.319
Epoch: 500, Train Loss: 0.266, Val f1_micro: 0.319
f1-micro: 0.319, f1-macro: 0.314, f1-weighted: 0.320, , roc-auc: 0.688
##### RUN 5 #####
Epoch: 020, Train Loss: 1.663, Val f1_micro: 0.223
Epoch: 040, Train Loss: 1.370, Val f1_micro: 0.255
Epoch: 060, Train Loss: 1.222, Val f1_micro: 0.264
Epoch: 080, Train Loss: 1.088, Val f1_micro: 0.271
Epoch: 100, Train Loss: 0.977, Val f1_micro: 0.282
Epoch: 120, Train Loss: 0.870, Val f1_micro: 0.281
Epoch: 140, Train Loss: 0.790, Val f1_micro: 0.287
Epoch: 160, Train Loss: 0.729, Val f1_micro: 0.292
Epoch: 180, Train Loss: 0.668, Val f1_micro: 0.300
Epoch: 200, Train Loss: 0.626, Val f1_micro: 0.304
Epoch: 220, Train Loss: 0.529, Val f1_micro: 0.305
Epoch: 240, Train Loss: 0.530, Val f1_micro: 0.309
Epoch: 260, Train Loss: 0.486, Val f1_micro: 0.310
Epoch: 280, Train Loss: 0.447, Val f1_micro: 0.315
Epoch: 300, Train Loss: 0.429, Val f1_micro: 0.314
Epoch: 320, Train Loss: 0.389, Val f1_micro: 0.316
Epoch: 340, Train Loss: 0.385, Val f1_micro: 0.315
Epoch: 360, Train Loss: 0.366, Val f1_micro: 0.313
Epoch: 380, Train Loss: 0.337, Val f1_micro: 0.320
Epoch: 400, Train Loss: 0.336, Val f1_micro: 0.318
Epoch: 420, Train Loss: 0.321, Val f1_micro: 0.319
Epoch: 440, Train Loss: 0.301, Val f1_micro: 0.317
Epoch: 460, Train Loss: 0.276, Val f1_micro: 0.321
Epoch: 480, Train Loss: 0.268, Val f1_micro: 0.320
Epoch: 500, Train Loss: 0.257, Val f1_micro: 0.319
f1-micro: 0.319, f1-macro: 0.314, f1-weighted: 0.320, , roc-auc: 0.688
########## Hyperparameters combination ##########
(1024, 0.5, 0.01, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.703, Val f1_micro: 0.218
Epoch: 040, Train Loss: 1.420, Val f1_micro: 0.252
Epoch: 060, Train Loss: 1.272, Val f1_micro: 0.266
Epoch: 080, Train Loss: 1.167, Val f1_micro: 0.268
Epoch: 100, Train Loss: 1.086, Val f1_micro: 0.274
Epoch: 120, Train Loss: 1.001, Val f1_micro: 0.277
Epoch: 140, Train Loss: 0.965, Val f1_micro: 0.279
Epoch: 160, Train Loss: 0.932, Val f1_micro: 0.279
Epoch: 180, Train Loss: 0.897, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.859, Val f1_micro: 0.286
Epoch: 220, Train Loss: 0.813, Val f1_micro: 0.287
Epoch: 240, Train Loss: 0.794, Val f1_micro: 0.291
Epoch: 260, Train Loss: 0.738, Val f1_micro: 0.290
Epoch: 280, Train Loss: 0.726, Val f1_micro: 0.294
Epoch: 300, Train Loss: 0.711, Val f1_micro: 0.294
Epoch: 320, Train Loss: 0.679, Val f1_micro: 0.299
Epoch: 340, Train Loss: 0.685, Val f1_micro: 0.302
Epoch: 360, Train Loss: 0.658, Val f1_micro: 0.305
Epoch: 380, Train Loss: 0.651, Val f1_micro: 0.303
Epoch: 400, Train Loss: 0.635, Val f1_micro: 0.303
Epoch: 420, Train Loss: 0.606, Val f1_micro: 0.308
Epoch: 440, Train Loss: 0.596, Val f1_micro: 0.309
Epoch: 460, Train Loss: 0.589, Val f1_micro: 0.306
Epoch: 480, Train Loss: 0.597, Val f1_micro: 0.309
Epoch: 500, Train Loss: 0.590, Val f1_micro: 0.308
f1-micro: 0.308, f1-macro: 0.303, f1-weighted: 0.308, , roc-auc: 0.681
##### RUN 2 #####
Epoch: 020, Train Loss: 1.678, Val f1_micro: 0.219
Epoch: 040, Train Loss: 1.423, Val f1_micro: 0.253
Epoch: 060, Train Loss: 1.250, Val f1_micro: 0.258
Epoch: 080, Train Loss: 1.147, Val f1_micro: 0.268
Epoch: 100, Train Loss: 1.097, Val f1_micro: 0.271
Epoch: 120, Train Loss: 1.053, Val f1_micro: 0.275
Epoch: 140, Train Loss: 0.977, Val f1_micro: 0.279
Epoch: 160, Train Loss: 0.934, Val f1_micro: 0.281
Epoch: 180, Train Loss: 0.888, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.827, Val f1_micro: 0.289
Epoch: 220, Train Loss: 0.811, Val f1_micro: 0.288
Epoch: 240, Train Loss: 0.781, Val f1_micro: 0.288
Epoch: 260, Train Loss: 0.763, Val f1_micro: 0.294
Epoch: 280, Train Loss: 0.734, Val f1_micro: 0.293
Epoch: 300, Train Loss: 0.718, Val f1_micro: 0.297
Epoch: 320, Train Loss: 0.697, Val f1_micro: 0.302
Epoch: 340, Train Loss: 0.676, Val f1_micro: 0.301
Epoch: 360, Train Loss: 0.657, Val f1_micro: 0.303
Epoch: 380, Train Loss: 0.661, Val f1_micro: 0.305
Epoch: 400, Train Loss: 0.646, Val f1_micro: 0.307
Epoch: 420, Train Loss: 0.630, Val f1_micro: 0.303
Epoch: 440, Train Loss: 0.608, Val f1_micro: 0.303
Epoch: 460, Train Loss: 0.592, Val f1_micro: 0.306
Epoch: 480, Train Loss: 0.598, Val f1_micro: 0.306
Epoch: 500, Train Loss: 0.583, Val f1_micro: 0.306
f1-micro: 0.306, f1-macro: 0.301, f1-weighted: 0.306, , roc-auc: 0.684
##### RUN 3 #####
Epoch: 020, Train Loss: 1.682, Val f1_micro: 0.220
Epoch: 040, Train Loss: 1.408, Val f1_micro: 0.259
Epoch: 060, Train Loss: 1.265, Val f1_micro: 0.269
Epoch: 080, Train Loss: 1.169, Val f1_micro: 0.268
Epoch: 100, Train Loss: 1.092, Val f1_micro: 0.273
Epoch: 120, Train Loss: 1.008, Val f1_micro: 0.276
Epoch: 140, Train Loss: 0.980, Val f1_micro: 0.278
Epoch: 160, Train Loss: 0.906, Val f1_micro: 0.286
Epoch: 180, Train Loss: 0.895, Val f1_micro: 0.288
Epoch: 200, Train Loss: 0.845, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.791, Val f1_micro: 0.295
Epoch: 240, Train Loss: 0.756, Val f1_micro: 0.293
Epoch: 260, Train Loss: 0.727, Val f1_micro: 0.298
Epoch: 280, Train Loss: 0.716, Val f1_micro: 0.295
Epoch: 300, Train Loss: 0.712, Val f1_micro: 0.299
Epoch: 320, Train Loss: 0.701, Val f1_micro: 0.304
Epoch: 340, Train Loss: 0.657, Val f1_micro: 0.301
Epoch: 360, Train Loss: 0.666, Val f1_micro: 0.305
Epoch: 380, Train Loss: 0.617, Val f1_micro: 0.302
Epoch: 400, Train Loss: 0.619, Val f1_micro: 0.308
Epoch: 420, Train Loss: 0.606, Val f1_micro: 0.310
Epoch: 440, Train Loss: 0.585, Val f1_micro: 0.308
Epoch: 460, Train Loss: 0.583, Val f1_micro: 0.312
Epoch: 480, Train Loss: 0.563, Val f1_micro: 0.306
Epoch: 500, Train Loss: 0.568, Val f1_micro: 0.312
f1-micro: 0.312, f1-macro: 0.306, f1-weighted: 0.312, , roc-auc: 0.684
##### RUN 4 #####
Epoch: 020, Train Loss: 1.695, Val f1_micro: 0.223
Epoch: 040, Train Loss: 1.404, Val f1_micro: 0.252
Epoch: 060, Train Loss: 1.259, Val f1_micro: 0.267
Epoch: 080, Train Loss: 1.180, Val f1_micro: 0.270
Epoch: 100, Train Loss: 1.083, Val f1_micro: 0.272
Epoch: 120, Train Loss: 1.013, Val f1_micro: 0.274
Epoch: 140, Train Loss: 0.976, Val f1_micro: 0.284
Epoch: 160, Train Loss: 0.926, Val f1_micro: 0.285
Epoch: 180, Train Loss: 0.865, Val f1_micro: 0.284
Epoch: 200, Train Loss: 0.840, Val f1_micro: 0.286
Epoch: 220, Train Loss: 0.824, Val f1_micro: 0.288
Epoch: 240, Train Loss: 0.807, Val f1_micro: 0.296
Epoch: 260, Train Loss: 0.765, Val f1_micro: 0.290
Epoch: 280, Train Loss: 0.760, Val f1_micro: 0.297
Epoch: 300, Train Loss: 0.707, Val f1_micro: 0.297
Epoch: 320, Train Loss: 0.691, Val f1_micro: 0.299
Epoch: 340, Train Loss: 0.688, Val f1_micro: 0.302
Epoch: 360, Train Loss: 0.637, Val f1_micro: 0.304
Epoch: 380, Train Loss: 0.652, Val f1_micro: 0.301
Epoch: 400, Train Loss: 0.629, Val f1_micro: 0.302
Epoch: 420, Train Loss: 0.604, Val f1_micro: 0.307
Epoch: 440, Train Loss: 0.619, Val f1_micro: 0.301
Epoch: 460, Train Loss: 0.587, Val f1_micro: 0.303
Epoch: 480, Train Loss: 0.597, Val f1_micro: 0.308
Epoch: 500, Train Loss: 0.583, Val f1_micro: 0.309
f1-micro: 0.309, f1-macro: 0.301, f1-weighted: 0.307, , roc-auc: 0.680
##### RUN 5 #####
Epoch: 020, Train Loss: 1.669, Val f1_micro: 0.208
Epoch: 040, Train Loss: 1.421, Val f1_micro: 0.254
Epoch: 060, Train Loss: 1.261, Val f1_micro: 0.266
Epoch: 080, Train Loss: 1.174, Val f1_micro: 0.268
Epoch: 100, Train Loss: 1.085, Val f1_micro: 0.275
Epoch: 120, Train Loss: 1.034, Val f1_micro: 0.275
Epoch: 140, Train Loss: 0.972, Val f1_micro: 0.279
Epoch: 160, Train Loss: 0.922, Val f1_micro: 0.281
Epoch: 180, Train Loss: 0.893, Val f1_micro: 0.287
Epoch: 200, Train Loss: 0.861, Val f1_micro: 0.291
Epoch: 220, Train Loss: 0.831, Val f1_micro: 0.290
Epoch: 240, Train Loss: 0.782, Val f1_micro: 0.293
Epoch: 260, Train Loss: 0.762, Val f1_micro: 0.298
Epoch: 280, Train Loss: 0.749, Val f1_micro: 0.296
Epoch: 300, Train Loss: 0.693, Val f1_micro: 0.302
Epoch: 320, Train Loss: 0.682, Val f1_micro: 0.302
Epoch: 340, Train Loss: 0.681, Val f1_micro: 0.302
Epoch: 360, Train Loss: 0.635, Val f1_micro: 0.299
Epoch: 380, Train Loss: 0.643, Val f1_micro: 0.304
Epoch: 400, Train Loss: 0.626, Val f1_micro: 0.303
Epoch: 420, Train Loss: 0.628, Val f1_micro: 0.304
Epoch: 440, Train Loss: 0.607, Val f1_micro: 0.309
Epoch: 460, Train Loss: 0.601, Val f1_micro: 0.308
Epoch: 480, Train Loss: 0.587, Val f1_micro: 0.306
Epoch: 500, Train Loss: 0.574, Val f1_micro: 0.306
f1-micro: 0.306, f1-macro: 0.301, f1-weighted: 0.307, , roc-auc: 0.681
########## Hyperparameters combination ##########
(1024, 0.5, 0.01, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.696, Val f1_micro: 0.220
Epoch: 040, Train Loss: 1.459, Val f1_micro: 0.248
Epoch: 060, Train Loss: 1.327, Val f1_micro: 0.264
Epoch: 080, Train Loss: 1.257, Val f1_micro: 0.265
Epoch: 100, Train Loss: 1.182, Val f1_micro: 0.266
Epoch: 120, Train Loss: 1.150, Val f1_micro: 0.271
Epoch: 140, Train Loss: 1.120, Val f1_micro: 0.276
Epoch: 160, Train Loss: 1.070, Val f1_micro: 0.275
Epoch: 180, Train Loss: 1.027, Val f1_micro: 0.279
Epoch: 200, Train Loss: 1.027, Val f1_micro: 0.281
Epoch: 220, Train Loss: 1.007, Val f1_micro: 0.287
Epoch: 240, Train Loss: 0.984, Val f1_micro: 0.281
Epoch: 260, Train Loss: 0.970, Val f1_micro: 0.283
Epoch: 280, Train Loss: 0.968, Val f1_micro: 0.284
Epoch: 300, Train Loss: 0.946, Val f1_micro: 0.288
Epoch: 320, Train Loss: 0.918, Val f1_micro: 0.286
Epoch: 340, Train Loss: 0.903, Val f1_micro: 0.291
Epoch: 360, Train Loss: 0.904, Val f1_micro: 0.294
Epoch: 380, Train Loss: 0.898, Val f1_micro: 0.290
Epoch: 400, Train Loss: 0.890, Val f1_micro: 0.292
Epoch: 420, Train Loss: 0.867, Val f1_micro: 0.292
Epoch: 440, Train Loss: 0.882, Val f1_micro: 0.289
Epoch: 460, Train Loss: 0.856, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.857, Val f1_micro: 0.299
Epoch: 500, Train Loss: 0.852, Val f1_micro: 0.295
f1-micro: 0.295, f1-macro: 0.289, f1-weighted: 0.293, , roc-auc: 0.679
##### RUN 2 #####
Epoch: 020, Train Loss: 1.718, Val f1_micro: 0.221
Epoch: 040, Train Loss: 1.472, Val f1_micro: 0.242
Epoch: 060, Train Loss: 1.345, Val f1_micro: 0.260
Epoch: 080, Train Loss: 1.263, Val f1_micro: 0.265
Epoch: 100, Train Loss: 1.198, Val f1_micro: 0.268
Epoch: 120, Train Loss: 1.149, Val f1_micro: 0.268
Epoch: 140, Train Loss: 1.102, Val f1_micro: 0.269
Epoch: 160, Train Loss: 1.080, Val f1_micro: 0.274
Epoch: 180, Train Loss: 1.036, Val f1_micro: 0.273
Epoch: 200, Train Loss: 1.031, Val f1_micro: 0.283
Epoch: 220, Train Loss: 0.988, Val f1_micro: 0.283
Epoch: 240, Train Loss: 0.983, Val f1_micro: 0.284
Epoch: 260, Train Loss: 0.956, Val f1_micro: 0.286
Epoch: 280, Train Loss: 0.949, Val f1_micro: 0.289
Epoch: 300, Train Loss: 0.927, Val f1_micro: 0.286
Epoch: 320, Train Loss: 0.932, Val f1_micro: 0.292
Epoch: 340, Train Loss: 0.914, Val f1_micro: 0.296
Epoch: 360, Train Loss: 0.906, Val f1_micro: 0.289
Epoch: 380, Train Loss: 0.886, Val f1_micro: 0.292
Epoch: 400, Train Loss: 0.877, Val f1_micro: 0.295
Epoch: 420, Train Loss: 0.871, Val f1_micro: 0.295
Epoch: 440, Train Loss: 0.878, Val f1_micro: 0.297
Epoch: 460, Train Loss: 0.857, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.856, Val f1_micro: 0.297
Epoch: 500, Train Loss: 0.859, Val f1_micro: 0.294
f1-micro: 0.294, f1-macro: 0.283, f1-weighted: 0.288, , roc-auc: 0.678
##### RUN 3 #####
Epoch: 020, Train Loss: 1.709, Val f1_micro: 0.217
Epoch: 040, Train Loss: 1.476, Val f1_micro: 0.247
Epoch: 060, Train Loss: 1.333, Val f1_micro: 0.262
Epoch: 080, Train Loss: 1.250, Val f1_micro: 0.270
Epoch: 100, Train Loss: 1.198, Val f1_micro: 0.263
Epoch: 120, Train Loss: 1.139, Val f1_micro: 0.273
Epoch: 140, Train Loss: 1.134, Val f1_micro: 0.269
Epoch: 160, Train Loss: 1.062, Val f1_micro: 0.275
Epoch: 180, Train Loss: 1.057, Val f1_micro: 0.275
Epoch: 200, Train Loss: 1.020, Val f1_micro: 0.280
Epoch: 220, Train Loss: 1.021, Val f1_micro: 0.283
Epoch: 240, Train Loss: 1.002, Val f1_micro: 0.281
Epoch: 260, Train Loss: 0.962, Val f1_micro: 0.285
Epoch: 280, Train Loss: 0.969, Val f1_micro: 0.288
Epoch: 300, Train Loss: 0.950, Val f1_micro: 0.298
Epoch: 320, Train Loss: 0.939, Val f1_micro: 0.291
Epoch: 340, Train Loss: 0.910, Val f1_micro: 0.292
Epoch: 360, Train Loss: 0.905, Val f1_micro: 0.292
Epoch: 380, Train Loss: 0.888, Val f1_micro: 0.292
Epoch: 400, Train Loss: 0.878, Val f1_micro: 0.293
Epoch: 420, Train Loss: 0.870, Val f1_micro: 0.301
Epoch: 440, Train Loss: 0.895, Val f1_micro: 0.294
Epoch: 460, Train Loss: 0.856, Val f1_micro: 0.296
Epoch: 480, Train Loss: 0.874, Val f1_micro: 0.300
Epoch: 500, Train Loss: 0.851, Val f1_micro: 0.299
f1-micro: 0.299, f1-macro: 0.291, f1-weighted: 0.297, , roc-auc: 0.677
##### RUN 4 #####
Epoch: 020, Train Loss: 1.709, Val f1_micro: 0.218
Epoch: 040, Train Loss: 1.455, Val f1_micro: 0.246
Epoch: 060, Train Loss: 1.339, Val f1_micro: 0.265
Epoch: 080, Train Loss: 1.251, Val f1_micro: 0.266
Epoch: 100, Train Loss: 1.184, Val f1_micro: 0.271
Epoch: 120, Train Loss: 1.150, Val f1_micro: 0.269
Epoch: 140, Train Loss: 1.121, Val f1_micro: 0.272
Epoch: 160, Train Loss: 1.087, Val f1_micro: 0.276
Epoch: 180, Train Loss: 1.040, Val f1_micro: 0.275
Epoch: 200, Train Loss: 1.032, Val f1_micro: 0.278
Epoch: 220, Train Loss: 0.998, Val f1_micro: 0.282
Epoch: 240, Train Loss: 0.965, Val f1_micro: 0.286
Epoch: 260, Train Loss: 0.951, Val f1_micro: 0.281
Epoch: 280, Train Loss: 0.942, Val f1_micro: 0.288
Epoch: 300, Train Loss: 0.935, Val f1_micro: 0.291
Epoch: 320, Train Loss: 0.940, Val f1_micro: 0.289
Epoch: 340, Train Loss: 0.910, Val f1_micro: 0.293
Epoch: 360, Train Loss: 0.888, Val f1_micro: 0.292
Epoch: 380, Train Loss: 0.876, Val f1_micro: 0.296
Epoch: 400, Train Loss: 0.893, Val f1_micro: 0.293
Epoch: 420, Train Loss: 0.900, Val f1_micro: 0.292
Epoch: 440, Train Loss: 0.874, Val f1_micro: 0.293
Epoch: 460, Train Loss: 0.861, Val f1_micro: 0.298
Epoch: 480, Train Loss: 0.832, Val f1_micro: 0.299
Epoch: 500, Train Loss: 0.852, Val f1_micro: 0.294
f1-micro: 0.294, f1-macro: 0.285, f1-weighted: 0.291, , roc-auc: 0.677
##### RUN 5 #####
Epoch: 020, Train Loss: 1.710, Val f1_micro: 0.220
Epoch: 040, Train Loss: 1.481, Val f1_micro: 0.248
Epoch: 060, Train Loss: 1.329, Val f1_micro: 0.261
Epoch: 080, Train Loss: 1.271, Val f1_micro: 0.269
Epoch: 100, Train Loss: 1.205, Val f1_micro: 0.271
Epoch: 120, Train Loss: 1.156, Val f1_micro: 0.274
Epoch: 140, Train Loss: 1.123, Val f1_micro: 0.271
Epoch: 160, Train Loss: 1.077, Val f1_micro: 0.279
Epoch: 180, Train Loss: 1.026, Val f1_micro: 0.281
Epoch: 200, Train Loss: 1.020, Val f1_micro: 0.278
Epoch: 220, Train Loss: 1.001, Val f1_micro: 0.282
Epoch: 240, Train Loss: 0.989, Val f1_micro: 0.284
Epoch: 260, Train Loss: 0.962, Val f1_micro: 0.289
Epoch: 280, Train Loss: 0.934, Val f1_micro: 0.290
Epoch: 300, Train Loss: 0.928, Val f1_micro: 0.286
Epoch: 320, Train Loss: 0.922, Val f1_micro: 0.289
Epoch: 340, Train Loss: 0.905, Val f1_micro: 0.291
Epoch: 360, Train Loss: 0.902, Val f1_micro: 0.294
Epoch: 380, Train Loss: 0.888, Val f1_micro: 0.295
Epoch: 400, Train Loss: 0.881, Val f1_micro: 0.295
Epoch: 420, Train Loss: 0.887, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.892, Val f1_micro: 0.297
Epoch: 460, Train Loss: 0.847, Val f1_micro: 0.299
Epoch: 480, Train Loss: 0.835, Val f1_micro: 0.301
Epoch: 500, Train Loss: 0.839, Val f1_micro: 0.300
f1-micro: 0.300, f1-macro: 0.291, f1-weighted: 0.297, , roc-auc: 0.676
########## Hyperparameters combination ##########
(1024, 0.5, 0.01, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.749, Val f1_micro: 0.211
Epoch: 040, Train Loss: 1.643, Val f1_micro: 0.222
Epoch: 060, Train Loss: 1.634, Val f1_micro: 0.221
Epoch: 080, Train Loss: 1.642, Val f1_micro: 0.220
Epoch: 100, Train Loss: 1.632, Val f1_micro: 0.217
Epoch: 120, Train Loss: 1.646, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.665, Val f1_micro: 0.212
Epoch: 160, Train Loss: 1.663, Val f1_micro: 0.218
Epoch: 180, Train Loss: 1.658, Val f1_micro: 0.215
Epoch: 200, Train Loss: 1.661, Val f1_micro: 0.218
Epoch: 220, Train Loss: 1.661, Val f1_micro: 0.217
Epoch: 240, Train Loss: 1.663, Val f1_micro: 0.214
Epoch: 260, Train Loss: 1.659, Val f1_micro: 0.219
Epoch: 280, Train Loss: 1.651, Val f1_micro: 0.214
Epoch: 300, Train Loss: 1.650, Val f1_micro: 0.214
Epoch: 320, Train Loss: 1.651, Val f1_micro: 0.213
Epoch: 340, Train Loss: 1.664, Val f1_micro: 0.210
Epoch: 360, Train Loss: 1.651, Val f1_micro: 0.223
Epoch: 380, Train Loss: 1.647, Val f1_micro: 0.219
Epoch: 400, Train Loss: 1.660, Val f1_micro: 0.215
Epoch: 420, Train Loss: 1.652, Val f1_micro: 0.207
Epoch: 440, Train Loss: 1.639, Val f1_micro: 0.219
Epoch: 460, Train Loss: 1.653, Val f1_micro: 0.214
Epoch: 480, Train Loss: 1.644, Val f1_micro: 0.217
Epoch: 500, Train Loss: 1.648, Val f1_micro: 0.218
f1-micro: 0.218, f1-macro: 0.191, f1-weighted: 0.187, , roc-auc: 0.645
##### RUN 2 #####
Epoch: 020, Train Loss: 1.789, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.659, Val f1_micro: 0.217
Epoch: 060, Train Loss: 1.642, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.643, Val f1_micro: 0.219
Epoch: 100, Train Loss: 1.661, Val f1_micro: 0.219
Epoch: 120, Train Loss: 1.649, Val f1_micro: 0.217
Epoch: 140, Train Loss: 1.655, Val f1_micro: 0.219
Epoch: 160, Train Loss: 1.661, Val f1_micro: 0.210
Epoch: 180, Train Loss: 1.668, Val f1_micro: 0.215
Epoch: 200, Train Loss: 1.656, Val f1_micro: 0.213
Epoch: 220, Train Loss: 1.648, Val f1_micro: 0.208
Epoch: 240, Train Loss: 1.663, Val f1_micro: 0.216
Epoch: 260, Train Loss: 1.665, Val f1_micro: 0.212
Epoch: 280, Train Loss: 1.650, Val f1_micro: 0.216
Epoch: 300, Train Loss: 1.662, Val f1_micro: 0.214
Epoch: 320, Train Loss: 1.647, Val f1_micro: 0.218
Epoch: 340, Train Loss: 1.651, Val f1_micro: 0.211
Epoch: 360, Train Loss: 1.655, Val f1_micro: 0.217
Epoch: 380, Train Loss: 1.653, Val f1_micro: 0.215
Epoch: 400, Train Loss: 1.658, Val f1_micro: 0.210
Epoch: 420, Train Loss: 1.652, Val f1_micro: 0.218
Epoch: 440, Train Loss: 1.656, Val f1_micro: 0.210
Epoch: 460, Train Loss: 1.645, Val f1_micro: 0.216
Epoch: 480, Train Loss: 1.651, Val f1_micro: 0.216
Epoch: 500, Train Loss: 1.649, Val f1_micro: 0.215
f1-micro: 0.215, f1-macro: 0.189, f1-weighted: 0.186, , roc-auc: 0.641
##### RUN 3 #####
Epoch: 020, Train Loss: 1.758, Val f1_micro: 0.224
Epoch: 040, Train Loss: 1.646, Val f1_micro: 0.217
Epoch: 060, Train Loss: 1.629, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.634, Val f1_micro: 0.218
Epoch: 100, Train Loss: 1.640, Val f1_micro: 0.219
Epoch: 120, Train Loss: 1.650, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.647, Val f1_micro: 0.212
Epoch: 160, Train Loss: 1.650, Val f1_micro: 0.213
Epoch: 180, Train Loss: 1.662, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.666, Val f1_micro: 0.219
Epoch: 220, Train Loss: 1.666, Val f1_micro: 0.212
Epoch: 240, Train Loss: 1.668, Val f1_micro: 0.218
Epoch: 260, Train Loss: 1.660, Val f1_micro: 0.214
Epoch: 280, Train Loss: 1.647, Val f1_micro: 0.218
Epoch: 300, Train Loss: 1.647, Val f1_micro: 0.214
Epoch: 320, Train Loss: 1.656, Val f1_micro: 0.217
Epoch: 340, Train Loss: 1.650, Val f1_micro: 0.220
Epoch: 360, Train Loss: 1.670, Val f1_micro: 0.214
Epoch: 380, Train Loss: 1.655, Val f1_micro: 0.214
Epoch: 400, Train Loss: 1.667, Val f1_micro: 0.213
Epoch: 420, Train Loss: 1.651, Val f1_micro: 0.217
Epoch: 440, Train Loss: 1.650, Val f1_micro: 0.211
Epoch: 460, Train Loss: 1.647, Val f1_micro: 0.215
Epoch: 480, Train Loss: 1.639, Val f1_micro: 0.212
Epoch: 500, Train Loss: 1.654, Val f1_micro: 0.213
f1-micro: 0.213, f1-macro: 0.190, f1-weighted: 0.184, , roc-auc: 0.644
##### RUN 4 #####
Epoch: 020, Train Loss: 1.776, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.658, Val f1_micro: 0.222
Epoch: 060, Train Loss: 1.650, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.637, Val f1_micro: 0.217
Epoch: 100, Train Loss: 1.651, Val f1_micro: 0.218
Epoch: 120, Train Loss: 1.644, Val f1_micro: 0.216
Epoch: 140, Train Loss: 1.661, Val f1_micro: 0.214
Epoch: 160, Train Loss: 1.663, Val f1_micro: 0.213
Epoch: 180, Train Loss: 1.659, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.663, Val f1_micro: 0.216
Epoch: 220, Train Loss: 1.655, Val f1_micro: 0.218
Epoch: 240, Train Loss: 1.664, Val f1_micro: 0.217
Epoch: 260, Train Loss: 1.667, Val f1_micro: 0.216
Epoch: 280, Train Loss: 1.650, Val f1_micro: 0.213
Epoch: 300, Train Loss: 1.658, Val f1_micro: 0.211
Epoch: 320, Train Loss: 1.659, Val f1_micro: 0.219
Epoch: 340, Train Loss: 1.653, Val f1_micro: 0.214
Epoch: 360, Train Loss: 1.662, Val f1_micro: 0.216
Epoch: 380, Train Loss: 1.662, Val f1_micro: 0.220
Epoch: 400, Train Loss: 1.654, Val f1_micro: 0.216
Epoch: 420, Train Loss: 1.663, Val f1_micro: 0.211
Epoch: 440, Train Loss: 1.648, Val f1_micro: 0.219
Epoch: 460, Train Loss: 1.656, Val f1_micro: 0.215
Epoch: 480, Train Loss: 1.658, Val f1_micro: 0.214
Epoch: 500, Train Loss: 1.649, Val f1_micro: 0.208
f1-micro: 0.208, f1-macro: 0.182, f1-weighted: 0.176, , roc-auc: 0.642
##### RUN 5 #####
Epoch: 020, Train Loss: 1.753, Val f1_micro: 0.211
Epoch: 040, Train Loss: 1.643, Val f1_micro: 0.222
Epoch: 060, Train Loss: 1.636, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.639, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.659, Val f1_micro: 0.216
Epoch: 120, Train Loss: 1.659, Val f1_micro: 0.217
Epoch: 140, Train Loss: 1.668, Val f1_micro: 0.214
Epoch: 160, Train Loss: 1.665, Val f1_micro: 0.213
Epoch: 180, Train Loss: 1.659, Val f1_micro: 0.211
Epoch: 200, Train Loss: 1.652, Val f1_micro: 0.216
Epoch: 220, Train Loss: 1.657, Val f1_micro: 0.221
Epoch: 240, Train Loss: 1.663, Val f1_micro: 0.210
Epoch: 260, Train Loss: 1.654, Val f1_micro: 0.216
Epoch: 280, Train Loss: 1.660, Val f1_micro: 0.213
Epoch: 300, Train Loss: 1.646, Val f1_micro: 0.216
Epoch: 320, Train Loss: 1.658, Val f1_micro: 0.220
Epoch: 340, Train Loss: 1.652, Val f1_micro: 0.212
Epoch: 360, Train Loss: 1.652, Val f1_micro: 0.217
Epoch: 380, Train Loss: 1.648, Val f1_micro: 0.219
Epoch: 400, Train Loss: 1.642, Val f1_micro: 0.214
Epoch: 420, Train Loss: 1.631, Val f1_micro: 0.219
Epoch: 440, Train Loss: 1.643, Val f1_micro: 0.209
Epoch: 460, Train Loss: 1.655, Val f1_micro: 0.221
Epoch: 480, Train Loss: 1.652, Val f1_micro: 0.216
Epoch: 500, Train Loss: 1.641, Val f1_micro: 0.214
f1-micro: 0.214, f1-macro: 0.188, f1-weighted: 0.183, , roc-auc: 0.643
########## Hyperparameters combination ##########
(1024, 0.5, 0.05, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.032, Val f1_micro: 0.144
Epoch: 040, Train Loss: 1.933, Val f1_micro: 0.168
Epoch: 060, Train Loss: 1.819, Val f1_micro: 0.134
Epoch: 080, Train Loss: 1.730, Val f1_micro: 0.153
Epoch: 100, Train Loss: 1.615, Val f1_micro: 0.188
Epoch: 120, Train Loss: 1.518, Val f1_micro: 0.185
Epoch: 140, Train Loss: 1.429, Val f1_micro: 0.205
Epoch: 160, Train Loss: 1.326, Val f1_micro: 0.209
Epoch: 180, Train Loss: 1.223, Val f1_micro: 0.230
Epoch: 200, Train Loss: 1.129, Val f1_micro: 0.241
Epoch: 220, Train Loss: 1.081, Val f1_micro: 0.246
Epoch: 240, Train Loss: 1.011, Val f1_micro: 0.256
Epoch: 260, Train Loss: 0.936, Val f1_micro: 0.252
Epoch: 280, Train Loss: 0.909, Val f1_micro: 0.258
Epoch: 300, Train Loss: 0.840, Val f1_micro: 0.265
Epoch: 320, Train Loss: 0.816, Val f1_micro: 0.263
Epoch: 340, Train Loss: 0.789, Val f1_micro: 0.271
Epoch: 360, Train Loss: 0.760, Val f1_micro: 0.272
Epoch: 380, Train Loss: 0.748, Val f1_micro: 0.277
Epoch: 400, Train Loss: 0.709, Val f1_micro: 0.270
Epoch: 420, Train Loss: 0.690, Val f1_micro: 0.280
Epoch: 440, Train Loss: 0.641, Val f1_micro: 0.285
Epoch: 460, Train Loss: 0.627, Val f1_micro: 0.284
Epoch: 480, Train Loss: 0.597, Val f1_micro: 0.285
Epoch: 500, Train Loss: 0.561, Val f1_micro: 0.284
f1-micro: 0.284, f1-macro: 0.280, f1-weighted: 0.285, , roc-auc: 0.657
##### RUN 2 #####
Epoch: 020, Train Loss: 2.045, Val f1_micro: 0.101
Epoch: 040, Train Loss: 1.935, Val f1_micro: 0.173
Epoch: 060, Train Loss: 1.847, Val f1_micro: 0.133
Epoch: 080, Train Loss: 1.755, Val f1_micro: 0.146
Epoch: 100, Train Loss: 1.673, Val f1_micro: 0.202
Epoch: 120, Train Loss: 1.630, Val f1_micro: 0.180
Epoch: 140, Train Loss: 1.515, Val f1_micro: 0.197
Epoch: 160, Train Loss: 1.394, Val f1_micro: 0.211
Epoch: 180, Train Loss: 1.323, Val f1_micro: 0.217
Epoch: 200, Train Loss: 1.245, Val f1_micro: 0.234
Epoch: 220, Train Loss: 1.156, Val f1_micro: 0.234
Epoch: 240, Train Loss: 1.132, Val f1_micro: 0.242
Epoch: 260, Train Loss: 1.048, Val f1_micro: 0.245
Epoch: 280, Train Loss: 0.990, Val f1_micro: 0.257
Epoch: 300, Train Loss: 0.956, Val f1_micro: 0.260
Epoch: 320, Train Loss: 0.864, Val f1_micro: 0.267
Epoch: 340, Train Loss: 0.844, Val f1_micro: 0.268
Epoch: 360, Train Loss: 0.816, Val f1_micro: 0.273
Epoch: 380, Train Loss: 0.780, Val f1_micro: 0.278
Epoch: 400, Train Loss: 0.741, Val f1_micro: 0.277
Epoch: 420, Train Loss: 0.725, Val f1_micro: 0.280
Epoch: 440, Train Loss: 0.722, Val f1_micro: 0.277
Epoch: 460, Train Loss: 0.683, Val f1_micro: 0.282
Epoch: 480, Train Loss: 0.641, Val f1_micro: 0.283
Epoch: 500, Train Loss: 0.591, Val f1_micro: 0.289
f1-micro: 0.289, f1-macro: 0.284, f1-weighted: 0.288, , roc-auc: 0.662
##### RUN 3 #####
Epoch: 020, Train Loss: 2.059, Val f1_micro: 0.141
Epoch: 040, Train Loss: 1.933, Val f1_micro: 0.166
Epoch: 060, Train Loss: 1.847, Val f1_micro: 0.128
Epoch: 080, Train Loss: 1.769, Val f1_micro: 0.137
Epoch: 100, Train Loss: 1.681, Val f1_micro: 0.146
Epoch: 120, Train Loss: 1.596, Val f1_micro: 0.177
Epoch: 140, Train Loss: 1.453, Val f1_micro: 0.189
Epoch: 160, Train Loss: 1.407, Val f1_micro: 0.206
Epoch: 180, Train Loss: 1.299, Val f1_micro: 0.213
Epoch: 200, Train Loss: 1.209, Val f1_micro: 0.218
Epoch: 220, Train Loss: 1.173, Val f1_micro: 0.234
Epoch: 240, Train Loss: 1.061, Val f1_micro: 0.247
Epoch: 260, Train Loss: 0.995, Val f1_micro: 0.248
Epoch: 280, Train Loss: 0.924, Val f1_micro: 0.259
Epoch: 300, Train Loss: 0.865, Val f1_micro: 0.267
Epoch: 320, Train Loss: 0.864, Val f1_micro: 0.270
Epoch: 340, Train Loss: 0.794, Val f1_micro: 0.266
Epoch: 360, Train Loss: 0.779, Val f1_micro: 0.271
Epoch: 380, Train Loss: 0.729, Val f1_micro: 0.279
Epoch: 400, Train Loss: 0.705, Val f1_micro: 0.284
Epoch: 420, Train Loss: 0.656, Val f1_micro: 0.280
Epoch: 440, Train Loss: 0.656, Val f1_micro: 0.289
Epoch: 460, Train Loss: 0.602, Val f1_micro: 0.281
Epoch: 480, Train Loss: 0.608, Val f1_micro: 0.287
Epoch: 500, Train Loss: 0.607, Val f1_micro: 0.294
f1-micro: 0.294, f1-macro: 0.290, f1-weighted: 0.295, , roc-auc: 0.664
##### RUN 4 #####
Epoch: 020, Train Loss: 2.051, Val f1_micro: 0.099
Epoch: 040, Train Loss: 1.950, Val f1_micro: 0.165
Epoch: 060, Train Loss: 1.854, Val f1_micro: 0.125
Epoch: 080, Train Loss: 1.771, Val f1_micro: 0.137
Epoch: 100, Train Loss: 1.680, Val f1_micro: 0.155
Epoch: 120, Train Loss: 1.600, Val f1_micro: 0.176
Epoch: 140, Train Loss: 1.475, Val f1_micro: 0.199
Epoch: 160, Train Loss: 1.400, Val f1_micro: 0.204
Epoch: 180, Train Loss: 1.300, Val f1_micro: 0.220
Epoch: 200, Train Loss: 1.240, Val f1_micro: 0.226
Epoch: 220, Train Loss: 1.166, Val f1_micro: 0.233
Epoch: 240, Train Loss: 1.107, Val f1_micro: 0.234
Epoch: 260, Train Loss: 1.064, Val f1_micro: 0.248
Epoch: 280, Train Loss: 1.024, Val f1_micro: 0.253
Epoch: 300, Train Loss: 0.968, Val f1_micro: 0.252
Epoch: 320, Train Loss: 0.944, Val f1_micro: 0.256
Epoch: 340, Train Loss: 0.866, Val f1_micro: 0.265
Epoch: 360, Train Loss: 0.841, Val f1_micro: 0.266
Epoch: 380, Train Loss: 0.796, Val f1_micro: 0.273
Epoch: 400, Train Loss: 0.741, Val f1_micro: 0.272
Epoch: 420, Train Loss: 0.726, Val f1_micro: 0.278
Epoch: 440, Train Loss: 0.712, Val f1_micro: 0.282
Epoch: 460, Train Loss: 0.667, Val f1_micro: 0.283
Epoch: 480, Train Loss: 0.679, Val f1_micro: 0.278
Epoch: 500, Train Loss: 0.617, Val f1_micro: 0.286
f1-micro: 0.286, f1-macro: 0.282, f1-weighted: 0.287, , roc-auc: 0.660
##### RUN 5 #####
Epoch: 020, Train Loss: 2.046, Val f1_micro: 0.145
Epoch: 040, Train Loss: 1.940, Val f1_micro: 0.160
Epoch: 060, Train Loss: 1.843, Val f1_micro: 0.130
Epoch: 080, Train Loss: 1.756, Val f1_micro: 0.141
Epoch: 100, Train Loss: 1.650, Val f1_micro: 0.165
Epoch: 120, Train Loss: 1.560, Val f1_micro: 0.179
Epoch: 140, Train Loss: 1.467, Val f1_micro: 0.186
Epoch: 160, Train Loss: 1.387, Val f1_micro: 0.195
Epoch: 180, Train Loss: 1.323, Val f1_micro: 0.213
Epoch: 200, Train Loss: 1.215, Val f1_micro: 0.224
Epoch: 220, Train Loss: 1.160, Val f1_micro: 0.224
Epoch: 240, Train Loss: 1.099, Val f1_micro: 0.236
Epoch: 260, Train Loss: 1.030, Val f1_micro: 0.245
Epoch: 280, Train Loss: 0.981, Val f1_micro: 0.251
Epoch: 300, Train Loss: 0.939, Val f1_micro: 0.256
Epoch: 320, Train Loss: 0.861, Val f1_micro: 0.262
Epoch: 340, Train Loss: 0.837, Val f1_micro: 0.267
Epoch: 360, Train Loss: 0.796, Val f1_micro: 0.269
Epoch: 380, Train Loss: 0.776, Val f1_micro: 0.274
Epoch: 400, Train Loss: 0.726, Val f1_micro: 0.274
Epoch: 420, Train Loss: 0.686, Val f1_micro: 0.282
Epoch: 440, Train Loss: 0.630, Val f1_micro: 0.280
Epoch: 460, Train Loss: 0.635, Val f1_micro: 0.280
Epoch: 480, Train Loss: 0.606, Val f1_micro: 0.282
Epoch: 500, Train Loss: 0.593, Val f1_micro: 0.285
f1-micro: 0.285, f1-macro: 0.281, f1-weighted: 0.285, , roc-auc: 0.663
########## Hyperparameters combination ##########
(1024, 0.5, 0.05, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.060, Val f1_micro: 0.145
Epoch: 040, Train Loss: 1.975, Val f1_micro: 0.171
Epoch: 060, Train Loss: 1.899, Val f1_micro: 0.132
Epoch: 080, Train Loss: 1.857, Val f1_micro: 0.170
Epoch: 100, Train Loss: 1.796, Val f1_micro: 0.183
Epoch: 120, Train Loss: 1.697, Val f1_micro: 0.187
Epoch: 140, Train Loss: 1.624, Val f1_micro: 0.201
Epoch: 160, Train Loss: 1.554, Val f1_micro: 0.205
Epoch: 180, Train Loss: 1.510, Val f1_micro: 0.198
Epoch: 200, Train Loss: 1.458, Val f1_micro: 0.221
Epoch: 220, Train Loss: 1.395, Val f1_micro: 0.227
Epoch: 240, Train Loss: 1.376, Val f1_micro: 0.229
Epoch: 260, Train Loss: 1.293, Val f1_micro: 0.240
Epoch: 280, Train Loss: 1.291, Val f1_micro: 0.237
Epoch: 300, Train Loss: 1.221, Val f1_micro: 0.243
Epoch: 320, Train Loss: 1.204, Val f1_micro: 0.249
Epoch: 340, Train Loss: 1.193, Val f1_micro: 0.252
Epoch: 360, Train Loss: 1.134, Val f1_micro: 0.257
Epoch: 380, Train Loss: 1.109, Val f1_micro: 0.258
Epoch: 400, Train Loss: 1.119, Val f1_micro: 0.256
Epoch: 420, Train Loss: 1.012, Val f1_micro: 0.261
Epoch: 440, Train Loss: 1.043, Val f1_micro: 0.269
Epoch: 460, Train Loss: 0.990, Val f1_micro: 0.263
Epoch: 480, Train Loss: 0.992, Val f1_micro: 0.270
Epoch: 500, Train Loss: 1.045, Val f1_micro: 0.264
f1-micro: 0.264, f1-macro: 0.257, f1-weighted: 0.258, , roc-auc: 0.656
##### RUN 2 #####
Epoch: 020, Train Loss: 2.035, Val f1_micro: 0.100
Epoch: 040, Train Loss: 1.973, Val f1_micro: 0.169
Epoch: 060, Train Loss: 1.897, Val f1_micro: 0.137
Epoch: 080, Train Loss: 1.824, Val f1_micro: 0.185
Epoch: 100, Train Loss: 1.734, Val f1_micro: 0.190
Epoch: 120, Train Loss: 1.682, Val f1_micro: 0.198
Epoch: 140, Train Loss: 1.594, Val f1_micro: 0.204
Epoch: 160, Train Loss: 1.495, Val f1_micro: 0.211
Epoch: 180, Train Loss: 1.479, Val f1_micro: 0.216
Epoch: 200, Train Loss: 1.401, Val f1_micro: 0.212
Epoch: 220, Train Loss: 1.338, Val f1_micro: 0.227
Epoch: 240, Train Loss: 1.301, Val f1_micro: 0.233
Epoch: 260, Train Loss: 1.275, Val f1_micro: 0.231
Epoch: 280, Train Loss: 1.211, Val f1_micro: 0.243
Epoch: 300, Train Loss: 1.177, Val f1_micro: 0.252
Epoch: 320, Train Loss: 1.128, Val f1_micro: 0.245
Epoch: 340, Train Loss: 1.129, Val f1_micro: 0.259
Epoch: 360, Train Loss: 1.139, Val f1_micro: 0.254
Epoch: 380, Train Loss: 1.117, Val f1_micro: 0.253
Epoch: 400, Train Loss: 1.072, Val f1_micro: 0.260
Epoch: 420, Train Loss: 1.100, Val f1_micro: 0.258
Epoch: 440, Train Loss: 1.020, Val f1_micro: 0.264
Epoch: 460, Train Loss: 1.003, Val f1_micro: 0.256
Epoch: 480, Train Loss: 0.996, Val f1_micro: 0.273
Epoch: 500, Train Loss: 1.006, Val f1_micro: 0.259
f1-micro: 0.259, f1-macro: 0.255, f1-weighted: 0.256, , roc-auc: 0.660
##### RUN 3 #####
Epoch: 020, Train Loss: 2.044, Val f1_micro: 0.141
Epoch: 040, Train Loss: 1.962, Val f1_micro: 0.171
Epoch: 060, Train Loss: 1.890, Val f1_micro: 0.124
Epoch: 080, Train Loss: 1.817, Val f1_micro: 0.182
Epoch: 100, Train Loss: 1.675, Val f1_micro: 0.193
Epoch: 120, Train Loss: 1.588, Val f1_micro: 0.196
Epoch: 140, Train Loss: 1.517, Val f1_micro: 0.207
Epoch: 160, Train Loss: 1.448, Val f1_micro: 0.218
Epoch: 180, Train Loss: 1.428, Val f1_micro: 0.226
Epoch: 200, Train Loss: 1.356, Val f1_micro: 0.219
Epoch: 220, Train Loss: 1.280, Val f1_micro: 0.228
Epoch: 240, Train Loss: 1.268, Val f1_micro: 0.241
Epoch: 260, Train Loss: 1.234, Val f1_micro: 0.247
Epoch: 280, Train Loss: 1.176, Val f1_micro: 0.252
Epoch: 300, Train Loss: 1.150, Val f1_micro: 0.249
Epoch: 320, Train Loss: 1.105, Val f1_micro: 0.248
Epoch: 340, Train Loss: 1.169, Val f1_micro: 0.244
Epoch: 360, Train Loss: 1.084, Val f1_micro: 0.261
Epoch: 380, Train Loss: 1.057, Val f1_micro: 0.255
Epoch: 400, Train Loss: 1.039, Val f1_micro: 0.265
Epoch: 420, Train Loss: 1.091, Val f1_micro: 0.241
Epoch: 440, Train Loss: 1.038, Val f1_micro: 0.270
Epoch: 460, Train Loss: 1.000, Val f1_micro: 0.268
Epoch: 480, Train Loss: 0.987, Val f1_micro: 0.260
Epoch: 500, Train Loss: 0.984, Val f1_micro: 0.272
f1-micro: 0.272, f1-macro: 0.266, f1-weighted: 0.269, , roc-auc: 0.661
##### RUN 4 #####
Epoch: 020, Train Loss: 2.052, Val f1_micro: 0.143
Epoch: 040, Train Loss: 1.956, Val f1_micro: 0.168
Epoch: 060, Train Loss: 1.884, Val f1_micro: 0.130
Epoch: 080, Train Loss: 1.801, Val f1_micro: 0.143
Epoch: 100, Train Loss: 1.725, Val f1_micro: 0.185
Epoch: 120, Train Loss: 1.652, Val f1_micro: 0.202
Epoch: 140, Train Loss: 1.557, Val f1_micro: 0.212
Epoch: 160, Train Loss: 1.488, Val f1_micro: 0.215
Epoch: 180, Train Loss: 1.428, Val f1_micro: 0.221
Epoch: 200, Train Loss: 1.374, Val f1_micro: 0.221
Epoch: 220, Train Loss: 1.334, Val f1_micro: 0.232
Epoch: 240, Train Loss: 1.295, Val f1_micro: 0.238
Epoch: 260, Train Loss: 1.288, Val f1_micro: 0.238
Epoch: 280, Train Loss: 1.234, Val f1_micro: 0.243
Epoch: 300, Train Loss: 1.173, Val f1_micro: 0.252
Epoch: 320, Train Loss: 1.118, Val f1_micro: 0.260
Epoch: 340, Train Loss: 1.120, Val f1_micro: 0.260
Epoch: 360, Train Loss: 1.114, Val f1_micro: 0.245
Epoch: 380, Train Loss: 1.064, Val f1_micro: 0.263
Epoch: 400, Train Loss: 1.039, Val f1_micro: 0.264
Epoch: 420, Train Loss: 1.026, Val f1_micro: 0.269
Epoch: 440, Train Loss: 0.997, Val f1_micro: 0.272
Epoch: 460, Train Loss: 0.995, Val f1_micro: 0.265
Epoch: 480, Train Loss: 0.960, Val f1_micro: 0.268
Epoch: 500, Train Loss: 0.947, Val f1_micro: 0.279
f1-micro: 0.279, f1-macro: 0.269, f1-weighted: 0.272, , roc-auc: 0.658
##### RUN 5 #####
Epoch: 020, Train Loss: 2.053, Val f1_micro: 0.142
Epoch: 040, Train Loss: 1.944, Val f1_micro: 0.176
Epoch: 060, Train Loss: 1.906, Val f1_micro: 0.137
Epoch: 080, Train Loss: 1.847, Val f1_micro: 0.170
Epoch: 100, Train Loss: 1.775, Val f1_micro: 0.185
Epoch: 120, Train Loss: 1.700, Val f1_micro: 0.194
Epoch: 140, Train Loss: 1.611, Val f1_micro: 0.207
Epoch: 160, Train Loss: 1.521, Val f1_micro: 0.211
Epoch: 180, Train Loss: 1.496, Val f1_micro: 0.215
Epoch: 200, Train Loss: 1.437, Val f1_micro: 0.216
Epoch: 220, Train Loss: 1.385, Val f1_micro: 0.221
Epoch: 240, Train Loss: 1.338, Val f1_micro: 0.229
Epoch: 260, Train Loss: 1.331, Val f1_micro: 0.218
Epoch: 280, Train Loss: 1.265, Val f1_micro: 0.244
Epoch: 300, Train Loss: 1.222, Val f1_micro: 0.240
Epoch: 320, Train Loss: 1.224, Val f1_micro: 0.241
Epoch: 340, Train Loss: 1.203, Val f1_micro: 0.243
Epoch: 360, Train Loss: 1.175, Val f1_micro: 0.244
Epoch: 380, Train Loss: 1.124, Val f1_micro: 0.250
Epoch: 400, Train Loss: 1.104, Val f1_micro: 0.254
Epoch: 420, Train Loss: 1.079, Val f1_micro: 0.251
Epoch: 440, Train Loss: 1.068, Val f1_micro: 0.251
Epoch: 460, Train Loss: 1.035, Val f1_micro: 0.263
Epoch: 480, Train Loss: 1.050, Val f1_micro: 0.256
Epoch: 500, Train Loss: 1.022, Val f1_micro: 0.262
f1-micro: 0.262, f1-macro: 0.251, f1-weighted: 0.253, , roc-auc: 0.653
########## Hyperparameters combination ##########
(1024, 0.5, 0.05, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.068, Val f1_micro: 0.099
Epoch: 040, Train Loss: 2.005, Val f1_micro: 0.161
Epoch: 060, Train Loss: 1.962, Val f1_micro: 0.124
Epoch: 080, Train Loss: 1.913, Val f1_micro: 0.176
Epoch: 100, Train Loss: 1.852, Val f1_micro: 0.178
Epoch: 120, Train Loss: 1.795, Val f1_micro: 0.170
Epoch: 140, Train Loss: 1.719, Val f1_micro: 0.183
Epoch: 160, Train Loss: 1.666, Val f1_micro: 0.181
Epoch: 180, Train Loss: 1.616, Val f1_micro: 0.206
Epoch: 200, Train Loss: 1.569, Val f1_micro: 0.206
Epoch: 220, Train Loss: 1.534, Val f1_micro: 0.208
Epoch: 240, Train Loss: 1.482, Val f1_micro: 0.223
Epoch: 260, Train Loss: 1.457, Val f1_micro: 0.221
Epoch: 280, Train Loss: 1.453, Val f1_micro: 0.219
Epoch: 300, Train Loss: 1.426, Val f1_micro: 0.225
Epoch: 320, Train Loss: 1.408, Val f1_micro: 0.230
Epoch: 340, Train Loss: 1.352, Val f1_micro: 0.237
Epoch: 360, Train Loss: 1.359, Val f1_micro: 0.225
Epoch: 380, Train Loss: 1.344, Val f1_micro: 0.229
Epoch: 400, Train Loss: 1.319, Val f1_micro: 0.237
Epoch: 420, Train Loss: 1.320, Val f1_micro: 0.238
Epoch: 440, Train Loss: 1.290, Val f1_micro: 0.226
Epoch: 460, Train Loss: 1.298, Val f1_micro: 0.237
Epoch: 480, Train Loss: 1.273, Val f1_micro: 0.245
Epoch: 500, Train Loss: 1.312, Val f1_micro: 0.231
f1-micro: 0.231, f1-macro: 0.209, f1-weighted: 0.207, , roc-auc: 0.647
##### RUN 2 #####
Epoch: 020, Train Loss: 2.048, Val f1_micro: 0.097
Epoch: 040, Train Loss: 1.980, Val f1_micro: 0.120
Epoch: 060, Train Loss: 1.929, Val f1_micro: 0.138
Epoch: 080, Train Loss: 1.843, Val f1_micro: 0.165
Epoch: 100, Train Loss: 1.809, Val f1_micro: 0.172
Epoch: 120, Train Loss: 1.732, Val f1_micro: 0.182
Epoch: 140, Train Loss: 1.683, Val f1_micro: 0.182
Epoch: 160, Train Loss: 1.636, Val f1_micro: 0.182
Epoch: 180, Train Loss: 1.584, Val f1_micro: 0.191
Epoch: 200, Train Loss: 1.533, Val f1_micro: 0.210
Epoch: 220, Train Loss: 1.510, Val f1_micro: 0.191
Epoch: 240, Train Loss: 1.458, Val f1_micro: 0.225
Epoch: 260, Train Loss: 1.428, Val f1_micro: 0.225
Epoch: 280, Train Loss: 1.450, Val f1_micro: 0.223
Epoch: 300, Train Loss: 1.389, Val f1_micro: 0.239
Epoch: 320, Train Loss: 1.351, Val f1_micro: 0.251
Epoch: 340, Train Loss: 1.328, Val f1_micro: 0.227
Epoch: 360, Train Loss: 1.312, Val f1_micro: 0.255
Epoch: 380, Train Loss: 1.293, Val f1_micro: 0.241
Epoch: 400, Train Loss: 1.305, Val f1_micro: 0.242
Epoch: 420, Train Loss: 1.296, Val f1_micro: 0.247
Epoch: 440, Train Loss: 1.242, Val f1_micro: 0.249
Epoch: 460, Train Loss: 1.228, Val f1_micro: 0.248
Epoch: 480, Train Loss: 1.224, Val f1_micro: 0.246
Epoch: 500, Train Loss: 1.232, Val f1_micro: 0.228
f1-micro: 0.228, f1-macro: 0.218, f1-weighted: 0.215, , roc-auc: 0.652
##### RUN 3 #####
Epoch: 020, Train Loss: 2.058, Val f1_micro: 0.099
Epoch: 040, Train Loss: 1.983, Val f1_micro: 0.165
Epoch: 060, Train Loss: 1.913, Val f1_micro: 0.137
Epoch: 080, Train Loss: 1.853, Val f1_micro: 0.182
Epoch: 100, Train Loss: 1.784, Val f1_micro: 0.188
Epoch: 120, Train Loss: 1.758, Val f1_micro: 0.187
Epoch: 140, Train Loss: 1.692, Val f1_micro: 0.206
Epoch: 160, Train Loss: 1.655, Val f1_micro: 0.210
Epoch: 180, Train Loss: 1.612, Val f1_micro: 0.195
Epoch: 200, Train Loss: 1.597, Val f1_micro: 0.207
Epoch: 220, Train Loss: 1.549, Val f1_micro: 0.228
Epoch: 240, Train Loss: 1.529, Val f1_micro: 0.198
Epoch: 260, Train Loss: 1.503, Val f1_micro: 0.219
Epoch: 280, Train Loss: 1.471, Val f1_micro: 0.231
Epoch: 300, Train Loss: 1.460, Val f1_micro: 0.228
Epoch: 320, Train Loss: 1.432, Val f1_micro: 0.229
Epoch: 340, Train Loss: 1.427, Val f1_micro: 0.225
Epoch: 360, Train Loss: 1.362, Val f1_micro: 0.239
Epoch: 380, Train Loss: 1.326, Val f1_micro: 0.240
Epoch: 400, Train Loss: 1.319, Val f1_micro: 0.234
Epoch: 420, Train Loss: 1.373, Val f1_micro: 0.229
Epoch: 440, Train Loss: 1.331, Val f1_micro: 0.243
Epoch: 460, Train Loss: 1.296, Val f1_micro: 0.237
Epoch: 480, Train Loss: 1.329, Val f1_micro: 0.224
Epoch: 500, Train Loss: 1.264, Val f1_micro: 0.252
f1-micro: 0.252, f1-macro: 0.238, f1-weighted: 0.238, , roc-auc: 0.654
##### RUN 4 #####
Epoch: 020, Train Loss: 2.058, Val f1_micro: 0.099
Epoch: 040, Train Loss: 1.992, Val f1_micro: 0.163
Epoch: 060, Train Loss: 1.947, Val f1_micro: 0.127
Epoch: 080, Train Loss: 1.877, Val f1_micro: 0.154
Epoch: 100, Train Loss: 1.809, Val f1_micro: 0.162
Epoch: 120, Train Loss: 1.775, Val f1_micro: 0.187
Epoch: 140, Train Loss: 1.681, Val f1_micro: 0.197
Epoch: 160, Train Loss: 1.626, Val f1_micro: 0.206
Epoch: 180, Train Loss: 1.574, Val f1_micro: 0.214
Epoch: 200, Train Loss: 1.506, Val f1_micro: 0.212
Epoch: 220, Train Loss: 1.463, Val f1_micro: 0.217
Epoch: 240, Train Loss: 1.455, Val f1_micro: 0.221
Epoch: 260, Train Loss: 1.446, Val f1_micro: 0.230
Epoch: 280, Train Loss: 1.377, Val f1_micro: 0.235
Epoch: 300, Train Loss: 1.390, Val f1_micro: 0.241
Epoch: 320, Train Loss: 1.337, Val f1_micro: 0.240
Epoch: 340, Train Loss: 1.305, Val f1_micro: 0.236
Epoch: 360, Train Loss: 1.314, Val f1_micro: 0.238
Epoch: 380, Train Loss: 1.283, Val f1_micro: 0.231
Epoch: 400, Train Loss: 1.287, Val f1_micro: 0.245
Epoch: 420, Train Loss: 1.278, Val f1_micro: 0.242
Epoch: 440, Train Loss: 1.265, Val f1_micro: 0.236
Epoch: 460, Train Loss: 1.239, Val f1_micro: 0.248
Epoch: 480, Train Loss: 1.233, Val f1_micro: 0.248
Epoch: 500, Train Loss: 1.226, Val f1_micro: 0.251
f1-micro: 0.251, f1-macro: 0.241, f1-weighted: 0.243, , roc-auc: 0.655
##### RUN 5 #####
Epoch: 020, Train Loss: 2.051, Val f1_micro: 0.144
Epoch: 040, Train Loss: 1.978, Val f1_micro: 0.121
Epoch: 060, Train Loss: 1.923, Val f1_micro: 0.126
Epoch: 080, Train Loss: 1.866, Val f1_micro: 0.147
Epoch: 100, Train Loss: 1.791, Val f1_micro: 0.185
Epoch: 120, Train Loss: 1.725, Val f1_micro: 0.182
Epoch: 140, Train Loss: 1.670, Val f1_micro: 0.185
Epoch: 160, Train Loss: 1.630, Val f1_micro: 0.190
Epoch: 180, Train Loss: 1.619, Val f1_micro: 0.193
Epoch: 200, Train Loss: 1.527, Val f1_micro: 0.202
Epoch: 220, Train Loss: 1.480, Val f1_micro: 0.222
Epoch: 240, Train Loss: 1.469, Val f1_micro: 0.227
Epoch: 260, Train Loss: 1.409, Val f1_micro: 0.228
Epoch: 280, Train Loss: 1.369, Val f1_micro: 0.240
Epoch: 300, Train Loss: 1.373, Val f1_micro: 0.223
Epoch: 320, Train Loss: 1.294, Val f1_micro: 0.242
Epoch: 340, Train Loss: 1.307, Val f1_micro: 0.238
Epoch: 360, Train Loss: 1.352, Val f1_micro: 0.231
Epoch: 380, Train Loss: 1.237, Val f1_micro: 0.249
Epoch: 400, Train Loss: 1.247, Val f1_micro: 0.245
Epoch: 420, Train Loss: 1.212, Val f1_micro: 0.248
Epoch: 440, Train Loss: 1.208, Val f1_micro: 0.259
Epoch: 460, Train Loss: 1.224, Val f1_micro: 0.262
Epoch: 480, Train Loss: 1.193, Val f1_micro: 0.261
Epoch: 500, Train Loss: 1.165, Val f1_micro: 0.263
f1-micro: 0.263, f1-macro: 0.251, f1-weighted: 0.252, , roc-auc: 0.665
########## Hyperparameters combination ##########
(1024, 0.5, 0.05, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.079, Val f1_micro: 0.143
Epoch: 040, Train Loss: 2.033, Val f1_micro: 0.161
Epoch: 060, Train Loss: 2.017, Val f1_micro: 0.155
Epoch: 080, Train Loss: 1.959, Val f1_micro: 0.160
Epoch: 100, Train Loss: 1.899, Val f1_micro: 0.173
Epoch: 120, Train Loss: 1.878, Val f1_micro: 0.187
Epoch: 140, Train Loss: 1.859, Val f1_micro: 0.188
Epoch: 160, Train Loss: 1.846, Val f1_micro: 0.196
Epoch: 180, Train Loss: 1.859, Val f1_micro: 0.199
Epoch: 200, Train Loss: 1.848, Val f1_micro: 0.198
Epoch: 220, Train Loss: 1.821, Val f1_micro: 0.199
Epoch: 240, Train Loss: 1.840, Val f1_micro: 0.199
Epoch: 260, Train Loss: 1.815, Val f1_micro: 0.196
Epoch: 280, Train Loss: 1.818, Val f1_micro: 0.201
Epoch: 300, Train Loss: 1.816, Val f1_micro: 0.195
Epoch: 320, Train Loss: 1.828, Val f1_micro: 0.197
Epoch: 340, Train Loss: 1.806, Val f1_micro: 0.194
Epoch: 360, Train Loss: 1.802, Val f1_micro: 0.206
Epoch: 380, Train Loss: 1.809, Val f1_micro: 0.202
Epoch: 400, Train Loss: 1.822, Val f1_micro: 0.194
Epoch: 420, Train Loss: 1.815, Val f1_micro: 0.197
Epoch: 440, Train Loss: 1.795, Val f1_micro: 0.202
Epoch: 460, Train Loss: 1.798, Val f1_micro: 0.201
Epoch: 480, Train Loss: 1.793, Val f1_micro: 0.211
Epoch: 500, Train Loss: 1.799, Val f1_micro: 0.195
f1-micro: 0.195, f1-macro: 0.138, f1-weighted: 0.134, , roc-auc: 0.629
##### RUN 2 #####
Epoch: 020, Train Loss: 2.064, Val f1_micro: 0.100
Epoch: 040, Train Loss: 2.031, Val f1_micro: 0.173
Epoch: 060, Train Loss: 2.004, Val f1_micro: 0.155
Epoch: 080, Train Loss: 1.953, Val f1_micro: 0.162
Epoch: 100, Train Loss: 1.913, Val f1_micro: 0.185
Epoch: 120, Train Loss: 1.878, Val f1_micro: 0.191
Epoch: 140, Train Loss: 1.852, Val f1_micro: 0.183
Epoch: 160, Train Loss: 1.839, Val f1_micro: 0.193
Epoch: 180, Train Loss: 1.834, Val f1_micro: 0.192
Epoch: 200, Train Loss: 1.835, Val f1_micro: 0.187
Epoch: 220, Train Loss: 1.830, Val f1_micro: 0.193
Epoch: 240, Train Loss: 1.808, Val f1_micro: 0.194
Epoch: 260, Train Loss: 1.816, Val f1_micro: 0.195
Epoch: 280, Train Loss: 1.819, Val f1_micro: 0.191
Epoch: 300, Train Loss: 1.826, Val f1_micro: 0.208
Epoch: 320, Train Loss: 1.795, Val f1_micro: 0.196
Epoch: 340, Train Loss: 1.807, Val f1_micro: 0.186
Epoch: 360, Train Loss: 1.801, Val f1_micro: 0.195
Epoch: 380, Train Loss: 1.796, Val f1_micro: 0.197
Epoch: 400, Train Loss: 1.807, Val f1_micro: 0.199
Epoch: 420, Train Loss: 1.804, Val f1_micro: 0.201
Epoch: 440, Train Loss: 1.811, Val f1_micro: 0.199
Epoch: 460, Train Loss: 1.779, Val f1_micro: 0.197
Epoch: 480, Train Loss: 1.783, Val f1_micro: 0.195
Epoch: 500, Train Loss: 1.803, Val f1_micro: 0.192
f1-micro: 0.192, f1-macro: 0.160, f1-weighted: 0.159, , roc-auc: 0.627
##### RUN 3 #####
Epoch: 020, Train Loss: 2.075, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.032, Val f1_micro: 0.161
Epoch: 060, Train Loss: 1.984, Val f1_micro: 0.156
Epoch: 080, Train Loss: 1.920, Val f1_micro: 0.173
Epoch: 100, Train Loss: 1.889, Val f1_micro: 0.176
Epoch: 120, Train Loss: 1.882, Val f1_micro: 0.165
Epoch: 140, Train Loss: 1.885, Val f1_micro: 0.186
Epoch: 160, Train Loss: 1.857, Val f1_micro: 0.197
Epoch: 180, Train Loss: 1.840, Val f1_micro: 0.193
Epoch: 200, Train Loss: 1.844, Val f1_micro: 0.183
Epoch: 220, Train Loss: 1.836, Val f1_micro: 0.195
Epoch: 240, Train Loss: 1.824, Val f1_micro: 0.202
Epoch: 260, Train Loss: 1.819, Val f1_micro: 0.198
Epoch: 280, Train Loss: 1.817, Val f1_micro: 0.196
Epoch: 300, Train Loss: 1.810, Val f1_micro: 0.196
Epoch: 320, Train Loss: 1.800, Val f1_micro: 0.184
Epoch: 340, Train Loss: 1.803, Val f1_micro: 0.197
Epoch: 360, Train Loss: 1.791, Val f1_micro: 0.210
Epoch: 380, Train Loss: 1.814, Val f1_micro: 0.195
Epoch: 400, Train Loss: 1.804, Val f1_micro: 0.196
Epoch: 420, Train Loss: 1.797, Val f1_micro: 0.210
Epoch: 440, Train Loss: 1.800, Val f1_micro: 0.200
Epoch: 460, Train Loss: 1.801, Val f1_micro: 0.206
Epoch: 480, Train Loss: 1.797, Val f1_micro: 0.197
Epoch: 500, Train Loss: 1.785, Val f1_micro: 0.203
f1-micro: 0.203, f1-macro: 0.165, f1-weighted: 0.162, , roc-auc: 0.625
##### RUN 4 #####
Epoch: 020, Train Loss: 2.082, Val f1_micro: 0.140
Epoch: 040, Train Loss: 2.041, Val f1_micro: 0.162
Epoch: 060, Train Loss: 2.005, Val f1_micro: 0.166
Epoch: 080, Train Loss: 1.954, Val f1_micro: 0.173
Epoch: 100, Train Loss: 1.900, Val f1_micro: 0.183
Epoch: 120, Train Loss: 1.892, Val f1_micro: 0.189
Epoch: 140, Train Loss: 1.846, Val f1_micro: 0.179
Epoch: 160, Train Loss: 1.848, Val f1_micro: 0.186
Epoch: 180, Train Loss: 1.843, Val f1_micro: 0.195
Epoch: 200, Train Loss: 1.823, Val f1_micro: 0.179
Epoch: 220, Train Loss: 1.814, Val f1_micro: 0.194
Epoch: 240, Train Loss: 1.822, Val f1_micro: 0.199
Epoch: 260, Train Loss: 1.826, Val f1_micro: 0.194
Epoch: 280, Train Loss: 1.813, Val f1_micro: 0.199
Epoch: 300, Train Loss: 1.821, Val f1_micro: 0.204
Epoch: 320, Train Loss: 1.799, Val f1_micro: 0.189
Epoch: 340, Train Loss: 1.801, Val f1_micro: 0.204
Epoch: 360, Train Loss: 1.822, Val f1_micro: 0.184
Epoch: 380, Train Loss: 1.808, Val f1_micro: 0.193
Epoch: 400, Train Loss: 1.820, Val f1_micro: 0.209
Epoch: 420, Train Loss: 1.809, Val f1_micro: 0.203
Epoch: 440, Train Loss: 1.793, Val f1_micro: 0.206
Epoch: 460, Train Loss: 1.797, Val f1_micro: 0.206
Epoch: 480, Train Loss: 1.786, Val f1_micro: 0.202
Epoch: 500, Train Loss: 1.794, Val f1_micro: 0.204
f1-micro: 0.204, f1-macro: 0.169, f1-weighted: 0.168, , roc-auc: 0.624
##### RUN 5 #####
Epoch: 020, Train Loss: 2.078, Val f1_micro: 0.140
Epoch: 040, Train Loss: 2.034, Val f1_micro: 0.161
Epoch: 060, Train Loss: 1.997, Val f1_micro: 0.164
Epoch: 080, Train Loss: 1.962, Val f1_micro: 0.156
Epoch: 100, Train Loss: 1.915, Val f1_micro: 0.179
Epoch: 120, Train Loss: 1.886, Val f1_micro: 0.188
Epoch: 140, Train Loss: 1.856, Val f1_micro: 0.188
Epoch: 160, Train Loss: 1.864, Val f1_micro: 0.182
Epoch: 180, Train Loss: 1.842, Val f1_micro: 0.192
Epoch: 200, Train Loss: 1.822, Val f1_micro: 0.199
Epoch: 220, Train Loss: 1.832, Val f1_micro: 0.189
Epoch: 240, Train Loss: 1.823, Val f1_micro: 0.192
Epoch: 260, Train Loss: 1.815, Val f1_micro: 0.202
Epoch: 280, Train Loss: 1.823, Val f1_micro: 0.191
Epoch: 300, Train Loss: 1.815, Val f1_micro: 0.206
Epoch: 320, Train Loss: 1.819, Val f1_micro: 0.206
Epoch: 340, Train Loss: 1.811, Val f1_micro: 0.197
Epoch: 360, Train Loss: 1.798, Val f1_micro: 0.205
Epoch: 380, Train Loss: 1.805, Val f1_micro: 0.187
Epoch: 400, Train Loss: 1.813, Val f1_micro: 0.195
Epoch: 420, Train Loss: 1.805, Val f1_micro: 0.204
Epoch: 440, Train Loss: 1.790, Val f1_micro: 0.194
Epoch: 460, Train Loss: 1.808, Val f1_micro: 0.180
Epoch: 480, Train Loss: 1.811, Val f1_micro: 0.187
Epoch: 500, Train Loss: 1.800, Val f1_micro: 0.189
f1-micro: 0.189, f1-macro: 0.161, f1-weighted: 0.156, , roc-auc: 0.626
########## Hyperparameters combination ##########
(1024, 0.6, 0.001, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.351, Val f1_micro: 0.194
Epoch: 040, Train Loss: 2.045, Val f1_micro: 0.204
Epoch: 060, Train Loss: 1.885, Val f1_micro: 0.210
Epoch: 080, Train Loss: 1.826, Val f1_micro: 0.215
Epoch: 100, Train Loss: 1.727, Val f1_micro: 0.223
Epoch: 120, Train Loss: 1.673, Val f1_micro: 0.225
Epoch: 140, Train Loss: 1.609, Val f1_micro: 0.229
Epoch: 160, Train Loss: 1.553, Val f1_micro: 0.233
Epoch: 180, Train Loss: 1.511, Val f1_micro: 0.239
Epoch: 200, Train Loss: 1.485, Val f1_micro: 0.236
Epoch: 220, Train Loss: 1.442, Val f1_micro: 0.243
Epoch: 240, Train Loss: 1.400, Val f1_micro: 0.244
Epoch: 260, Train Loss: 1.354, Val f1_micro: 0.250
Epoch: 280, Train Loss: 1.337, Val f1_micro: 0.247
Epoch: 300, Train Loss: 1.332, Val f1_micro: 0.251
Epoch: 320, Train Loss: 1.288, Val f1_micro: 0.253
Epoch: 340, Train Loss: 1.272, Val f1_micro: 0.255
Epoch: 360, Train Loss: 1.239, Val f1_micro: 0.255
Epoch: 380, Train Loss: 1.230, Val f1_micro: 0.259
Epoch: 400, Train Loss: 1.199, Val f1_micro: 0.259
Epoch: 420, Train Loss: 1.190, Val f1_micro: 0.261
Epoch: 440, Train Loss: 1.170, Val f1_micro: 0.265
Epoch: 460, Train Loss: 1.134, Val f1_micro: 0.267
Epoch: 480, Train Loss: 1.118, Val f1_micro: 0.263
Epoch: 500, Train Loss: 1.117, Val f1_micro: 0.269
f1-micro: 0.269, f1-macro: 0.262, f1-weighted: 0.264, , roc-auc: 0.674
##### RUN 2 #####
Epoch: 020, Train Loss: 2.318, Val f1_micro: 0.192
Epoch: 040, Train Loss: 2.062, Val f1_micro: 0.206
Epoch: 060, Train Loss: 1.928, Val f1_micro: 0.211
Epoch: 080, Train Loss: 1.826, Val f1_micro: 0.218
Epoch: 100, Train Loss: 1.734, Val f1_micro: 0.221
Epoch: 120, Train Loss: 1.657, Val f1_micro: 0.223
Epoch: 140, Train Loss: 1.597, Val f1_micro: 0.229
Epoch: 160, Train Loss: 1.557, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.522, Val f1_micro: 0.238
Epoch: 200, Train Loss: 1.468, Val f1_micro: 0.235
Epoch: 220, Train Loss: 1.449, Val f1_micro: 0.243
Epoch: 240, Train Loss: 1.384, Val f1_micro: 0.244
Epoch: 260, Train Loss: 1.381, Val f1_micro: 0.247
Epoch: 280, Train Loss: 1.356, Val f1_micro: 0.247
Epoch: 300, Train Loss: 1.315, Val f1_micro: 0.249
Epoch: 320, Train Loss: 1.289, Val f1_micro: 0.252
Epoch: 340, Train Loss: 1.292, Val f1_micro: 0.252
Epoch: 360, Train Loss: 1.243, Val f1_micro: 0.254
Epoch: 380, Train Loss: 1.241, Val f1_micro: 0.258
Epoch: 400, Train Loss: 1.198, Val f1_micro: 0.260
Epoch: 420, Train Loss: 1.186, Val f1_micro: 0.261
Epoch: 440, Train Loss: 1.192, Val f1_micro: 0.264
Epoch: 460, Train Loss: 1.140, Val f1_micro: 0.264
Epoch: 480, Train Loss: 1.113, Val f1_micro: 0.263
Epoch: 500, Train Loss: 1.102, Val f1_micro: 0.268
f1-micro: 0.268, f1-macro: 0.260, f1-weighted: 0.262, , roc-auc: 0.674
##### RUN 3 #####
Epoch: 020, Train Loss: 2.392, Val f1_micro: 0.193
Epoch: 040, Train Loss: 2.077, Val f1_micro: 0.205
Epoch: 060, Train Loss: 1.921, Val f1_micro: 0.213
Epoch: 080, Train Loss: 1.823, Val f1_micro: 0.218
Epoch: 100, Train Loss: 1.734, Val f1_micro: 0.219
Epoch: 120, Train Loss: 1.670, Val f1_micro: 0.228
Epoch: 140, Train Loss: 1.616, Val f1_micro: 0.228
Epoch: 160, Train Loss: 1.564, Val f1_micro: 0.235
Epoch: 180, Train Loss: 1.511, Val f1_micro: 0.234
Epoch: 200, Train Loss: 1.479, Val f1_micro: 0.239
Epoch: 220, Train Loss: 1.440, Val f1_micro: 0.244
Epoch: 240, Train Loss: 1.388, Val f1_micro: 0.245
Epoch: 260, Train Loss: 1.370, Val f1_micro: 0.246
Epoch: 280, Train Loss: 1.331, Val f1_micro: 0.250
Epoch: 300, Train Loss: 1.311, Val f1_micro: 0.251
Epoch: 320, Train Loss: 1.288, Val f1_micro: 0.252
Epoch: 340, Train Loss: 1.267, Val f1_micro: 0.254
Epoch: 360, Train Loss: 1.244, Val f1_micro: 0.258
Epoch: 380, Train Loss: 1.225, Val f1_micro: 0.260
Epoch: 400, Train Loss: 1.187, Val f1_micro: 0.261
Epoch: 420, Train Loss: 1.196, Val f1_micro: 0.260
Epoch: 440, Train Loss: 1.157, Val f1_micro: 0.260
Epoch: 460, Train Loss: 1.148, Val f1_micro: 0.266
Epoch: 480, Train Loss: 1.133, Val f1_micro: 0.265
Epoch: 500, Train Loss: 1.115, Val f1_micro: 0.267
f1-micro: 0.267, f1-macro: 0.260, f1-weighted: 0.261, , roc-auc: 0.674
##### RUN 4 #####
Epoch: 020, Train Loss: 2.347, Val f1_micro: 0.191
Epoch: 040, Train Loss: 2.068, Val f1_micro: 0.205
Epoch: 060, Train Loss: 1.929, Val f1_micro: 0.215
Epoch: 080, Train Loss: 1.809, Val f1_micro: 0.216
Epoch: 100, Train Loss: 1.734, Val f1_micro: 0.220
Epoch: 120, Train Loss: 1.667, Val f1_micro: 0.226
Epoch: 140, Train Loss: 1.610, Val f1_micro: 0.233
Epoch: 160, Train Loss: 1.579, Val f1_micro: 0.232
Epoch: 180, Train Loss: 1.535, Val f1_micro: 0.238
Epoch: 200, Train Loss: 1.498, Val f1_micro: 0.240
Epoch: 220, Train Loss: 1.450, Val f1_micro: 0.245
Epoch: 240, Train Loss: 1.405, Val f1_micro: 0.244
Epoch: 260, Train Loss: 1.387, Val f1_micro: 0.249
Epoch: 280, Train Loss: 1.353, Val f1_micro: 0.247
Epoch: 300, Train Loss: 1.311, Val f1_micro: 0.250
Epoch: 320, Train Loss: 1.295, Val f1_micro: 0.250
Epoch: 340, Train Loss: 1.274, Val f1_micro: 0.253
Epoch: 360, Train Loss: 1.241, Val f1_micro: 0.257
Epoch: 380, Train Loss: 1.246, Val f1_micro: 0.259
Epoch: 400, Train Loss: 1.191, Val f1_micro: 0.260
Epoch: 420, Train Loss: 1.180, Val f1_micro: 0.261
Epoch: 440, Train Loss: 1.153, Val f1_micro: 0.262
Epoch: 460, Train Loss: 1.166, Val f1_micro: 0.265
Epoch: 480, Train Loss: 1.127, Val f1_micro: 0.265
Epoch: 500, Train Loss: 1.109, Val f1_micro: 0.267
f1-micro: 0.267, f1-macro: 0.260, f1-weighted: 0.262, , roc-auc: 0.674
##### RUN 5 #####
Epoch: 020, Train Loss: 2.349, Val f1_micro: 0.191
Epoch: 040, Train Loss: 2.068, Val f1_micro: 0.207
Epoch: 060, Train Loss: 1.910, Val f1_micro: 0.212
Epoch: 080, Train Loss: 1.814, Val f1_micro: 0.216
Epoch: 100, Train Loss: 1.708, Val f1_micro: 0.219
Epoch: 120, Train Loss: 1.658, Val f1_micro: 0.226
Epoch: 140, Train Loss: 1.605, Val f1_micro: 0.232
Epoch: 160, Train Loss: 1.582, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.522, Val f1_micro: 0.238
Epoch: 200, Train Loss: 1.484, Val f1_micro: 0.238
Epoch: 220, Train Loss: 1.417, Val f1_micro: 0.242
Epoch: 240, Train Loss: 1.423, Val f1_micro: 0.242
Epoch: 260, Train Loss: 1.365, Val f1_micro: 0.246
Epoch: 280, Train Loss: 1.338, Val f1_micro: 0.249
Epoch: 300, Train Loss: 1.314, Val f1_micro: 0.249
Epoch: 320, Train Loss: 1.294, Val f1_micro: 0.256
Epoch: 340, Train Loss: 1.259, Val f1_micro: 0.256
Epoch: 360, Train Loss: 1.265, Val f1_micro: 0.255
Epoch: 380, Train Loss: 1.240, Val f1_micro: 0.259
Epoch: 400, Train Loss: 1.207, Val f1_micro: 0.260
Epoch: 420, Train Loss: 1.189, Val f1_micro: 0.263
Epoch: 440, Train Loss: 1.154, Val f1_micro: 0.260
Epoch: 460, Train Loss: 1.133, Val f1_micro: 0.264
Epoch: 480, Train Loss: 1.145, Val f1_micro: 0.266
Epoch: 500, Train Loss: 1.100, Val f1_micro: 0.267
f1-micro: 0.267, f1-macro: 0.259, f1-weighted: 0.261, , roc-auc: 0.673
########## Hyperparameters combination ##########
(1024, 0.6, 0.001, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.386, Val f1_micro: 0.193
Epoch: 040, Train Loss: 2.079, Val f1_micro: 0.205
Epoch: 060, Train Loss: 1.930, Val f1_micro: 0.213
Epoch: 080, Train Loss: 1.803, Val f1_micro: 0.220
Epoch: 100, Train Loss: 1.744, Val f1_micro: 0.221
Epoch: 120, Train Loss: 1.669, Val f1_micro: 0.225
Epoch: 140, Train Loss: 1.607, Val f1_micro: 0.228
Epoch: 160, Train Loss: 1.572, Val f1_micro: 0.235
Epoch: 180, Train Loss: 1.521, Val f1_micro: 0.236
Epoch: 200, Train Loss: 1.520, Val f1_micro: 0.240
Epoch: 220, Train Loss: 1.461, Val f1_micro: 0.242
Epoch: 240, Train Loss: 1.445, Val f1_micro: 0.245
Epoch: 260, Train Loss: 1.438, Val f1_micro: 0.246
Epoch: 280, Train Loss: 1.387, Val f1_micro: 0.249
Epoch: 300, Train Loss: 1.345, Val f1_micro: 0.246
Epoch: 320, Train Loss: 1.318, Val f1_micro: 0.251
Epoch: 340, Train Loss: 1.316, Val f1_micro: 0.254
Epoch: 360, Train Loss: 1.304, Val f1_micro: 0.255
Epoch: 380, Train Loss: 1.276, Val f1_micro: 0.257
Epoch: 400, Train Loss: 1.287, Val f1_micro: 0.257
Epoch: 420, Train Loss: 1.248, Val f1_micro: 0.257
Epoch: 440, Train Loss: 1.220, Val f1_micro: 0.258
Epoch: 460, Train Loss: 1.236, Val f1_micro: 0.260
Epoch: 480, Train Loss: 1.217, Val f1_micro: 0.262
Epoch: 500, Train Loss: 1.177, Val f1_micro: 0.262
f1-micro: 0.262, f1-macro: 0.253, f1-weighted: 0.253, , roc-auc: 0.671
##### RUN 2 #####
Epoch: 020, Train Loss: 2.370, Val f1_micro: 0.194
Epoch: 040, Train Loss: 2.054, Val f1_micro: 0.205
Epoch: 060, Train Loss: 1.922, Val f1_micro: 0.211
Epoch: 080, Train Loss: 1.812, Val f1_micro: 0.221
Epoch: 100, Train Loss: 1.738, Val f1_micro: 0.223
Epoch: 120, Train Loss: 1.670, Val f1_micro: 0.225
Epoch: 140, Train Loss: 1.615, Val f1_micro: 0.227
Epoch: 160, Train Loss: 1.584, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.531, Val f1_micro: 0.235
Epoch: 200, Train Loss: 1.492, Val f1_micro: 0.243
Epoch: 220, Train Loss: 1.464, Val f1_micro: 0.241
Epoch: 240, Train Loss: 1.446, Val f1_micro: 0.245
Epoch: 260, Train Loss: 1.415, Val f1_micro: 0.245
Epoch: 280, Train Loss: 1.375, Val f1_micro: 0.248
Epoch: 300, Train Loss: 1.360, Val f1_micro: 0.250
Epoch: 320, Train Loss: 1.326, Val f1_micro: 0.252
Epoch: 340, Train Loss: 1.337, Val f1_micro: 0.255
Epoch: 360, Train Loss: 1.283, Val f1_micro: 0.252
Epoch: 380, Train Loss: 1.293, Val f1_micro: 0.255
Epoch: 400, Train Loss: 1.274, Val f1_micro: 0.256
Epoch: 420, Train Loss: 1.250, Val f1_micro: 0.257
Epoch: 440, Train Loss: 1.238, Val f1_micro: 0.260
Epoch: 460, Train Loss: 1.211, Val f1_micro: 0.263
Epoch: 480, Train Loss: 1.208, Val f1_micro: 0.263
Epoch: 500, Train Loss: 1.201, Val f1_micro: 0.260
f1-micro: 0.260, f1-macro: 0.251, f1-weighted: 0.252, , roc-auc: 0.671
##### RUN 3 #####
Epoch: 020, Train Loss: 2.401, Val f1_micro: 0.191
Epoch: 040, Train Loss: 2.063, Val f1_micro: 0.203
Epoch: 060, Train Loss: 1.897, Val f1_micro: 0.211
Epoch: 080, Train Loss: 1.818, Val f1_micro: 0.218
Epoch: 100, Train Loss: 1.712, Val f1_micro: 0.220
Epoch: 120, Train Loss: 1.665, Val f1_micro: 0.228
Epoch: 140, Train Loss: 1.624, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.580, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.545, Val f1_micro: 0.233
Epoch: 200, Train Loss: 1.508, Val f1_micro: 0.242
Epoch: 220, Train Loss: 1.469, Val f1_micro: 0.242
Epoch: 240, Train Loss: 1.434, Val f1_micro: 0.242
Epoch: 260, Train Loss: 1.422, Val f1_micro: 0.245
Epoch: 280, Train Loss: 1.398, Val f1_micro: 0.245
Epoch: 300, Train Loss: 1.364, Val f1_micro: 0.248
Epoch: 320, Train Loss: 1.330, Val f1_micro: 0.250
Epoch: 340, Train Loss: 1.330, Val f1_micro: 0.252
Epoch: 360, Train Loss: 1.300, Val f1_micro: 0.253
Epoch: 380, Train Loss: 1.274, Val f1_micro: 0.255
Epoch: 400, Train Loss: 1.284, Val f1_micro: 0.256
Epoch: 420, Train Loss: 1.254, Val f1_micro: 0.257
Epoch: 440, Train Loss: 1.242, Val f1_micro: 0.257
Epoch: 460, Train Loss: 1.237, Val f1_micro: 0.261
Epoch: 480, Train Loss: 1.189, Val f1_micro: 0.260
Epoch: 500, Train Loss: 1.173, Val f1_micro: 0.261
f1-micro: 0.261, f1-macro: 0.252, f1-weighted: 0.252, , roc-auc: 0.670
##### RUN 4 #####
Epoch: 020, Train Loss: 2.332, Val f1_micro: 0.189
Epoch: 040, Train Loss: 2.078, Val f1_micro: 0.205
Epoch: 060, Train Loss: 1.914, Val f1_micro: 0.214
Epoch: 080, Train Loss: 1.820, Val f1_micro: 0.218
Epoch: 100, Train Loss: 1.749, Val f1_micro: 0.220
Epoch: 120, Train Loss: 1.675, Val f1_micro: 0.224
Epoch: 140, Train Loss: 1.614, Val f1_micro: 0.232
Epoch: 160, Train Loss: 1.583, Val f1_micro: 0.235
Epoch: 180, Train Loss: 1.538, Val f1_micro: 0.240
Epoch: 200, Train Loss: 1.489, Val f1_micro: 0.237
Epoch: 220, Train Loss: 1.447, Val f1_micro: 0.241
Epoch: 240, Train Loss: 1.446, Val f1_micro: 0.246
Epoch: 260, Train Loss: 1.425, Val f1_micro: 0.243
Epoch: 280, Train Loss: 1.394, Val f1_micro: 0.253
Epoch: 300, Train Loss: 1.362, Val f1_micro: 0.249
Epoch: 320, Train Loss: 1.328, Val f1_micro: 0.246
Epoch: 340, Train Loss: 1.328, Val f1_micro: 0.253
Epoch: 360, Train Loss: 1.318, Val f1_micro: 0.254
Epoch: 380, Train Loss: 1.274, Val f1_micro: 0.252
Epoch: 400, Train Loss: 1.263, Val f1_micro: 0.254
Epoch: 420, Train Loss: 1.236, Val f1_micro: 0.255
Epoch: 440, Train Loss: 1.234, Val f1_micro: 0.259
Epoch: 460, Train Loss: 1.220, Val f1_micro: 0.258
Epoch: 480, Train Loss: 1.189, Val f1_micro: 0.260
Epoch: 500, Train Loss: 1.178, Val f1_micro: 0.262
f1-micro: 0.262, f1-macro: 0.254, f1-weighted: 0.254, , roc-auc: 0.671
##### RUN 5 #####
Epoch: 020, Train Loss: 2.335, Val f1_micro: 0.189
Epoch: 040, Train Loss: 2.055, Val f1_micro: 0.205
Epoch: 060, Train Loss: 1.929, Val f1_micro: 0.213
Epoch: 080, Train Loss: 1.827, Val f1_micro: 0.218
Epoch: 100, Train Loss: 1.734, Val f1_micro: 0.223
Epoch: 120, Train Loss: 1.679, Val f1_micro: 0.227
Epoch: 140, Train Loss: 1.620, Val f1_micro: 0.230
Epoch: 160, Train Loss: 1.560, Val f1_micro: 0.232
Epoch: 180, Train Loss: 1.532, Val f1_micro: 0.239
Epoch: 200, Train Loss: 1.482, Val f1_micro: 0.238
Epoch: 220, Train Loss: 1.445, Val f1_micro: 0.240
Epoch: 240, Train Loss: 1.431, Val f1_micro: 0.245
Epoch: 260, Train Loss: 1.388, Val f1_micro: 0.245
Epoch: 280, Train Loss: 1.414, Val f1_micro: 0.249
Epoch: 300, Train Loss: 1.387, Val f1_micro: 0.252
Epoch: 320, Train Loss: 1.332, Val f1_micro: 0.251
Epoch: 340, Train Loss: 1.321, Val f1_micro: 0.255
Epoch: 360, Train Loss: 1.321, Val f1_micro: 0.254
Epoch: 380, Train Loss: 1.292, Val f1_micro: 0.255
Epoch: 400, Train Loss: 1.266, Val f1_micro: 0.252
Epoch: 420, Train Loss: 1.242, Val f1_micro: 0.258
Epoch: 440, Train Loss: 1.237, Val f1_micro: 0.258
Epoch: 460, Train Loss: 1.214, Val f1_micro: 0.259
Epoch: 480, Train Loss: 1.220, Val f1_micro: 0.261
Epoch: 500, Train Loss: 1.187, Val f1_micro: 0.262
f1-micro: 0.262, f1-macro: 0.253, f1-weighted: 0.253, , roc-auc: 0.671
########## Hyperparameters combination ##########
(1024, 0.6, 0.001, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.347, Val f1_micro: 0.196
Epoch: 040, Train Loss: 2.066, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.897, Val f1_micro: 0.215
Epoch: 080, Train Loss: 1.830, Val f1_micro: 0.222
Epoch: 100, Train Loss: 1.749, Val f1_micro: 0.221
Epoch: 120, Train Loss: 1.692, Val f1_micro: 0.231
Epoch: 140, Train Loss: 1.622, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.587, Val f1_micro: 0.235
Epoch: 180, Train Loss: 1.562, Val f1_micro: 0.235
Epoch: 200, Train Loss: 1.495, Val f1_micro: 0.243
Epoch: 220, Train Loss: 1.481, Val f1_micro: 0.240
Epoch: 240, Train Loss: 1.470, Val f1_micro: 0.244
Epoch: 260, Train Loss: 1.436, Val f1_micro: 0.246
Epoch: 280, Train Loss: 1.431, Val f1_micro: 0.247
Epoch: 300, Train Loss: 1.425, Val f1_micro: 0.247
Epoch: 320, Train Loss: 1.398, Val f1_micro: 0.248
Epoch: 340, Train Loss: 1.363, Val f1_micro: 0.250
Epoch: 360, Train Loss: 1.364, Val f1_micro: 0.251
Epoch: 380, Train Loss: 1.322, Val f1_micro: 0.251
Epoch: 400, Train Loss: 1.331, Val f1_micro: 0.252
Epoch: 420, Train Loss: 1.320, Val f1_micro: 0.254
Epoch: 440, Train Loss: 1.308, Val f1_micro: 0.253
Epoch: 460, Train Loss: 1.311, Val f1_micro: 0.255
Epoch: 480, Train Loss: 1.291, Val f1_micro: 0.255
Epoch: 500, Train Loss: 1.276, Val f1_micro: 0.257
f1-micro: 0.257, f1-macro: 0.246, f1-weighted: 0.247, , roc-auc: 0.670
##### RUN 2 #####
Epoch: 020, Train Loss: 2.398, Val f1_micro: 0.196
Epoch: 040, Train Loss: 2.048, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.923, Val f1_micro: 0.218
Epoch: 080, Train Loss: 1.818, Val f1_micro: 0.224
Epoch: 100, Train Loss: 1.720, Val f1_micro: 0.224
Epoch: 120, Train Loss: 1.697, Val f1_micro: 0.228
Epoch: 140, Train Loss: 1.625, Val f1_micro: 0.234
Epoch: 160, Train Loss: 1.565, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.549, Val f1_micro: 0.238
Epoch: 200, Train Loss: 1.516, Val f1_micro: 0.241
Epoch: 220, Train Loss: 1.498, Val f1_micro: 0.241
Epoch: 240, Train Loss: 1.471, Val f1_micro: 0.244
Epoch: 260, Train Loss: 1.451, Val f1_micro: 0.247
Epoch: 280, Train Loss: 1.422, Val f1_micro: 0.247
Epoch: 300, Train Loss: 1.414, Val f1_micro: 0.250
Epoch: 320, Train Loss: 1.403, Val f1_micro: 0.249
Epoch: 340, Train Loss: 1.372, Val f1_micro: 0.249
Epoch: 360, Train Loss: 1.354, Val f1_micro: 0.251
Epoch: 380, Train Loss: 1.360, Val f1_micro: 0.253
Epoch: 400, Train Loss: 1.336, Val f1_micro: 0.252
Epoch: 420, Train Loss: 1.325, Val f1_micro: 0.253
Epoch: 440, Train Loss: 1.311, Val f1_micro: 0.254
Epoch: 460, Train Loss: 1.305, Val f1_micro: 0.255
Epoch: 480, Train Loss: 1.276, Val f1_micro: 0.258
Epoch: 500, Train Loss: 1.286, Val f1_micro: 0.255
f1-micro: 0.255, f1-macro: 0.244, f1-weighted: 0.245, , roc-auc: 0.670
##### RUN 3 #####
Epoch: 020, Train Loss: 2.343, Val f1_micro: 0.196
Epoch: 040, Train Loss: 2.055, Val f1_micro: 0.208
Epoch: 060, Train Loss: 1.927, Val f1_micro: 0.218
Epoch: 080, Train Loss: 1.801, Val f1_micro: 0.219
Epoch: 100, Train Loss: 1.738, Val f1_micro: 0.223
Epoch: 120, Train Loss: 1.688, Val f1_micro: 0.229
Epoch: 140, Train Loss: 1.629, Val f1_micro: 0.231
Epoch: 160, Train Loss: 1.589, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.564, Val f1_micro: 0.237
Epoch: 200, Train Loss: 1.522, Val f1_micro: 0.241
Epoch: 220, Train Loss: 1.489, Val f1_micro: 0.243
Epoch: 240, Train Loss: 1.481, Val f1_micro: 0.243
Epoch: 260, Train Loss: 1.470, Val f1_micro: 0.242
Epoch: 280, Train Loss: 1.433, Val f1_micro: 0.245
Epoch: 300, Train Loss: 1.408, Val f1_micro: 0.248
Epoch: 320, Train Loss: 1.405, Val f1_micro: 0.246
Epoch: 340, Train Loss: 1.385, Val f1_micro: 0.249
Epoch: 360, Train Loss: 1.356, Val f1_micro: 0.251
Epoch: 380, Train Loss: 1.342, Val f1_micro: 0.250
Epoch: 400, Train Loss: 1.341, Val f1_micro: 0.251
Epoch: 420, Train Loss: 1.322, Val f1_micro: 0.252
Epoch: 440, Train Loss: 1.325, Val f1_micro: 0.254
Epoch: 460, Train Loss: 1.301, Val f1_micro: 0.256
Epoch: 480, Train Loss: 1.287, Val f1_micro: 0.256
Epoch: 500, Train Loss: 1.272, Val f1_micro: 0.257
f1-micro: 0.257, f1-macro: 0.247, f1-weighted: 0.248, , roc-auc: 0.671
##### RUN 4 #####
Epoch: 020, Train Loss: 2.350, Val f1_micro: 0.196
Epoch: 040, Train Loss: 2.041, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.924, Val f1_micro: 0.216
Epoch: 080, Train Loss: 1.817, Val f1_micro: 0.219
Epoch: 100, Train Loss: 1.723, Val f1_micro: 0.222
Epoch: 120, Train Loss: 1.671, Val f1_micro: 0.230
Epoch: 140, Train Loss: 1.633, Val f1_micro: 0.232
Epoch: 160, Train Loss: 1.579, Val f1_micro: 0.236
Epoch: 180, Train Loss: 1.549, Val f1_micro: 0.238
Epoch: 200, Train Loss: 1.511, Val f1_micro: 0.242
Epoch: 220, Train Loss: 1.506, Val f1_micro: 0.242
Epoch: 240, Train Loss: 1.474, Val f1_micro: 0.246
Epoch: 260, Train Loss: 1.450, Val f1_micro: 0.246
Epoch: 280, Train Loss: 1.438, Val f1_micro: 0.246
Epoch: 300, Train Loss: 1.401, Val f1_micro: 0.250
Epoch: 320, Train Loss: 1.400, Val f1_micro: 0.251
Epoch: 340, Train Loss: 1.378, Val f1_micro: 0.249
Epoch: 360, Train Loss: 1.353, Val f1_micro: 0.250
Epoch: 380, Train Loss: 1.347, Val f1_micro: 0.250
Epoch: 400, Train Loss: 1.335, Val f1_micro: 0.253
Epoch: 420, Train Loss: 1.323, Val f1_micro: 0.253
Epoch: 440, Train Loss: 1.327, Val f1_micro: 0.251
Epoch: 460, Train Loss: 1.281, Val f1_micro: 0.256
Epoch: 480, Train Loss: 1.277, Val f1_micro: 0.257
Epoch: 500, Train Loss: 1.288, Val f1_micro: 0.255
f1-micro: 0.255, f1-macro: 0.244, f1-weighted: 0.244, , roc-auc: 0.670
##### RUN 5 #####
Epoch: 020, Train Loss: 2.382, Val f1_micro: 0.194
Epoch: 040, Train Loss: 2.053, Val f1_micro: 0.209
Epoch: 060, Train Loss: 1.902, Val f1_micro: 0.217
Epoch: 080, Train Loss: 1.827, Val f1_micro: 0.221
Epoch: 100, Train Loss: 1.734, Val f1_micro: 0.226
Epoch: 120, Train Loss: 1.661, Val f1_micro: 0.227
Epoch: 140, Train Loss: 1.630, Val f1_micro: 0.234
Epoch: 160, Train Loss: 1.585, Val f1_micro: 0.233
Epoch: 180, Train Loss: 1.547, Val f1_micro: 0.239
Epoch: 200, Train Loss: 1.517, Val f1_micro: 0.241
Epoch: 220, Train Loss: 1.514, Val f1_micro: 0.242
Epoch: 240, Train Loss: 1.463, Val f1_micro: 0.242
Epoch: 260, Train Loss: 1.453, Val f1_micro: 0.248
Epoch: 280, Train Loss: 1.436, Val f1_micro: 0.246
Epoch: 300, Train Loss: 1.405, Val f1_micro: 0.248
Epoch: 320, Train Loss: 1.408, Val f1_micro: 0.251
Epoch: 340, Train Loss: 1.402, Val f1_micro: 0.250
Epoch: 360, Train Loss: 1.384, Val f1_micro: 0.253
Epoch: 380, Train Loss: 1.329, Val f1_micro: 0.254
Epoch: 400, Train Loss: 1.350, Val f1_micro: 0.254
Epoch: 420, Train Loss: 1.324, Val f1_micro: 0.253
Epoch: 440, Train Loss: 1.327, Val f1_micro: 0.254
Epoch: 460, Train Loss: 1.320, Val f1_micro: 0.253
Epoch: 480, Train Loss: 1.289, Val f1_micro: 0.255
Epoch: 500, Train Loss: 1.275, Val f1_micro: 0.255
f1-micro: 0.255, f1-macro: 0.244, f1-weighted: 0.245, , roc-auc: 0.670
########## Hyperparameters combination ##########
(1024, 0.6, 0.001, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.370, Val f1_micro: 0.188
Epoch: 040, Train Loss: 2.081, Val f1_micro: 0.202
Epoch: 060, Train Loss: 1.926, Val f1_micro: 0.204
Epoch: 080, Train Loss: 1.831, Val f1_micro: 0.206
Epoch: 100, Train Loss: 1.796, Val f1_micro: 0.207
Epoch: 120, Train Loss: 1.736, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.708, Val f1_micro: 0.221
Epoch: 160, Train Loss: 1.682, Val f1_micro: 0.219
Epoch: 180, Train Loss: 1.674, Val f1_micro: 0.215
Epoch: 200, Train Loss: 1.659, Val f1_micro: 0.221
Epoch: 220, Train Loss: 1.657, Val f1_micro: 0.215
Epoch: 240, Train Loss: 1.640, Val f1_micro: 0.224
Epoch: 260, Train Loss: 1.641, Val f1_micro: 0.222
Epoch: 280, Train Loss: 1.629, Val f1_micro: 0.216
Epoch: 300, Train Loss: 1.614, Val f1_micro: 0.219
Epoch: 320, Train Loss: 1.626, Val f1_micro: 0.220
Epoch: 340, Train Loss: 1.637, Val f1_micro: 0.222
Epoch: 360, Train Loss: 1.630, Val f1_micro: 0.218
Epoch: 380, Train Loss: 1.643, Val f1_micro: 0.220
Epoch: 400, Train Loss: 1.635, Val f1_micro: 0.225
Epoch: 420, Train Loss: 1.637, Val f1_micro: 0.215
Epoch: 440, Train Loss: 1.630, Val f1_micro: 0.219
Epoch: 460, Train Loss: 1.634, Val f1_micro: 0.220
Epoch: 480, Train Loss: 1.615, Val f1_micro: 0.219
Epoch: 500, Train Loss: 1.640, Val f1_micro: 0.218
f1-micro: 0.218, f1-macro: 0.195, f1-weighted: 0.191, , roc-auc: 0.658
##### RUN 2 #####
Epoch: 020, Train Loss: 2.357, Val f1_micro: 0.190
Epoch: 040, Train Loss: 2.070, Val f1_micro: 0.200
Epoch: 060, Train Loss: 1.903, Val f1_micro: 0.207
Epoch: 080, Train Loss: 1.841, Val f1_micro: 0.210
Epoch: 100, Train Loss: 1.786, Val f1_micro: 0.210
Epoch: 120, Train Loss: 1.746, Val f1_micro: 0.213
Epoch: 140, Train Loss: 1.714, Val f1_micro: 0.215
Epoch: 160, Train Loss: 1.695, Val f1_micro: 0.216
Epoch: 180, Train Loss: 1.678, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.665, Val f1_micro: 0.218
Epoch: 220, Train Loss: 1.639, Val f1_micro: 0.217
Epoch: 240, Train Loss: 1.650, Val f1_micro: 0.221
Epoch: 260, Train Loss: 1.630, Val f1_micro: 0.217
Epoch: 280, Train Loss: 1.631, Val f1_micro: 0.219
Epoch: 300, Train Loss: 1.631, Val f1_micro: 0.218
Epoch: 320, Train Loss: 1.637, Val f1_micro: 0.221
Epoch: 340, Train Loss: 1.631, Val f1_micro: 0.218
Epoch: 360, Train Loss: 1.632, Val f1_micro: 0.221
Epoch: 380, Train Loss: 1.633, Val f1_micro: 0.220
Epoch: 400, Train Loss: 1.630, Val f1_micro: 0.222
Epoch: 420, Train Loss: 1.633, Val f1_micro: 0.221
Epoch: 440, Train Loss: 1.635, Val f1_micro: 0.221
Epoch: 460, Train Loss: 1.646, Val f1_micro: 0.217
Epoch: 480, Train Loss: 1.644, Val f1_micro: 0.222
Epoch: 500, Train Loss: 1.634, Val f1_micro: 0.222
f1-micro: 0.222, f1-macro: 0.200, f1-weighted: 0.197, , roc-auc: 0.658
##### RUN 3 #####
Epoch: 020, Train Loss: 2.338, Val f1_micro: 0.186
Epoch: 040, Train Loss: 2.069, Val f1_micro: 0.202
Epoch: 060, Train Loss: 1.921, Val f1_micro: 0.205
Epoch: 080, Train Loss: 1.847, Val f1_micro: 0.207
Epoch: 100, Train Loss: 1.783, Val f1_micro: 0.213
Epoch: 120, Train Loss: 1.733, Val f1_micro: 0.210
Epoch: 140, Train Loss: 1.709, Val f1_micro: 0.216
Epoch: 160, Train Loss: 1.697, Val f1_micro: 0.216
Epoch: 180, Train Loss: 1.665, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.668, Val f1_micro: 0.218
Epoch: 220, Train Loss: 1.650, Val f1_micro: 0.218
Epoch: 240, Train Loss: 1.666, Val f1_micro: 0.217
Epoch: 260, Train Loss: 1.644, Val f1_micro: 0.218
Epoch: 280, Train Loss: 1.624, Val f1_micro: 0.224
Epoch: 300, Train Loss: 1.642, Val f1_micro: 0.219
Epoch: 320, Train Loss: 1.638, Val f1_micro: 0.221
Epoch: 340, Train Loss: 1.627, Val f1_micro: 0.220
Epoch: 360, Train Loss: 1.627, Val f1_micro: 0.217
Epoch: 380, Train Loss: 1.640, Val f1_micro: 0.219
Epoch: 400, Train Loss: 1.630, Val f1_micro: 0.221
Epoch: 420, Train Loss: 1.627, Val f1_micro: 0.220
Epoch: 440, Train Loss: 1.628, Val f1_micro: 0.219
Epoch: 460, Train Loss: 1.627, Val f1_micro: 0.221
Epoch: 480, Train Loss: 1.638, Val f1_micro: 0.219
Epoch: 500, Train Loss: 1.635, Val f1_micro: 0.217
f1-micro: 0.217, f1-macro: 0.195, f1-weighted: 0.190, , roc-auc: 0.658
##### RUN 4 #####
Epoch: 020, Train Loss: 2.345, Val f1_micro: 0.192
Epoch: 040, Train Loss: 2.049, Val f1_micro: 0.207
Epoch: 060, Train Loss: 1.923, Val f1_micro: 0.206
Epoch: 080, Train Loss: 1.841, Val f1_micro: 0.209
Epoch: 100, Train Loss: 1.785, Val f1_micro: 0.213
Epoch: 120, Train Loss: 1.752, Val f1_micro: 0.214
Epoch: 140, Train Loss: 1.721, Val f1_micro: 0.212
Epoch: 160, Train Loss: 1.688, Val f1_micro: 0.216
Epoch: 180, Train Loss: 1.674, Val f1_micro: 0.219
Epoch: 200, Train Loss: 1.660, Val f1_micro: 0.222
Epoch: 220, Train Loss: 1.657, Val f1_micro: 0.224
Epoch: 240, Train Loss: 1.634, Val f1_micro: 0.220
Epoch: 260, Train Loss: 1.636, Val f1_micro: 0.223
Epoch: 280, Train Loss: 1.629, Val f1_micro: 0.220
Epoch: 300, Train Loss: 1.624, Val f1_micro: 0.219
Epoch: 320, Train Loss: 1.629, Val f1_micro: 0.219
Epoch: 340, Train Loss: 1.633, Val f1_micro: 0.221
Epoch: 360, Train Loss: 1.634, Val f1_micro: 0.220
Epoch: 380, Train Loss: 1.629, Val f1_micro: 0.216
Epoch: 400, Train Loss: 1.634, Val f1_micro: 0.222
Epoch: 420, Train Loss: 1.636, Val f1_micro: 0.220
Epoch: 440, Train Loss: 1.631, Val f1_micro: 0.219
Epoch: 460, Train Loss: 1.638, Val f1_micro: 0.220
Epoch: 480, Train Loss: 1.630, Val f1_micro: 0.218
Epoch: 500, Train Loss: 1.627, Val f1_micro: 0.219
f1-micro: 0.219, f1-macro: 0.197, f1-weighted: 0.194, , roc-auc: 0.658
##### RUN 5 #####
Epoch: 020, Train Loss: 2.363, Val f1_micro: 0.192
Epoch: 040, Train Loss: 2.085, Val f1_micro: 0.204
Epoch: 060, Train Loss: 1.922, Val f1_micro: 0.206
Epoch: 080, Train Loss: 1.829, Val f1_micro: 0.208
Epoch: 100, Train Loss: 1.782, Val f1_micro: 0.215
Epoch: 120, Train Loss: 1.742, Val f1_micro: 0.211
Epoch: 140, Train Loss: 1.716, Val f1_micro: 0.218
Epoch: 160, Train Loss: 1.704, Val f1_micro: 0.218
Epoch: 180, Train Loss: 1.676, Val f1_micro: 0.219
Epoch: 200, Train Loss: 1.663, Val f1_micro: 0.223
Epoch: 220, Train Loss: 1.650, Val f1_micro: 0.218
Epoch: 240, Train Loss: 1.633, Val f1_micro: 0.218
Epoch: 260, Train Loss: 1.632, Val f1_micro: 0.223
Epoch: 280, Train Loss: 1.626, Val f1_micro: 0.220
Epoch: 300, Train Loss: 1.635, Val f1_micro: 0.220
Epoch: 320, Train Loss: 1.628, Val f1_micro: 0.220
Epoch: 340, Train Loss: 1.631, Val f1_micro: 0.225
Epoch: 360, Train Loss: 1.627, Val f1_micro: 0.217
Epoch: 380, Train Loss: 1.635, Val f1_micro: 0.219
Epoch: 400, Train Loss: 1.632, Val f1_micro: 0.223
Epoch: 420, Train Loss: 1.632, Val f1_micro: 0.220
Epoch: 440, Train Loss: 1.635, Val f1_micro: 0.220
Epoch: 460, Train Loss: 1.639, Val f1_micro: 0.221
Epoch: 480, Train Loss: 1.621, Val f1_micro: 0.218
Epoch: 500, Train Loss: 1.650, Val f1_micro: 0.214
f1-micro: 0.214, f1-macro: 0.195, f1-weighted: 0.190, , roc-auc: 0.659
########## Hyperparameters combination ##########
(1024, 0.6, 0.005, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.865, Val f1_micro: 0.216
Epoch: 040, Train Loss: 1.596, Val f1_micro: 0.236
Epoch: 060, Train Loss: 1.456, Val f1_micro: 0.252
Epoch: 080, Train Loss: 1.331, Val f1_micro: 0.257
Epoch: 100, Train Loss: 1.258, Val f1_micro: 0.263
Epoch: 120, Train Loss: 1.170, Val f1_micro: 0.267
Epoch: 140, Train Loss: 1.099, Val f1_micro: 0.270
Epoch: 160, Train Loss: 1.045, Val f1_micro: 0.274
Epoch: 180, Train Loss: 0.981, Val f1_micro: 0.280
Epoch: 200, Train Loss: 0.935, Val f1_micro: 0.276
Epoch: 220, Train Loss: 0.899, Val f1_micro: 0.287
Epoch: 240, Train Loss: 0.834, Val f1_micro: 0.288
Epoch: 260, Train Loss: 0.806, Val f1_micro: 0.288
Epoch: 280, Train Loss: 0.759, Val f1_micro: 0.292
Epoch: 300, Train Loss: 0.713, Val f1_micro: 0.296
Epoch: 320, Train Loss: 0.705, Val f1_micro: 0.299
Epoch: 340, Train Loss: 0.655, Val f1_micro: 0.300
Epoch: 360, Train Loss: 0.592, Val f1_micro: 0.304
Epoch: 380, Train Loss: 0.593, Val f1_micro: 0.306
Epoch: 400, Train Loss: 0.563, Val f1_micro: 0.307
Epoch: 420, Train Loss: 0.546, Val f1_micro: 0.304
Epoch: 440, Train Loss: 0.527, Val f1_micro: 0.308
Epoch: 460, Train Loss: 0.502, Val f1_micro: 0.308
Epoch: 480, Train Loss: 0.472, Val f1_micro: 0.308
Epoch: 500, Train Loss: 0.444, Val f1_micro: 0.310
f1-micro: 0.310, f1-macro: 0.302, f1-weighted: 0.309, , roc-auc: 0.679
##### RUN 2 #####
Epoch: 020, Train Loss: 1.872, Val f1_micro: 0.212
Epoch: 040, Train Loss: 1.610, Val f1_micro: 0.230
Epoch: 060, Train Loss: 1.435, Val f1_micro: 0.248
Epoch: 080, Train Loss: 1.334, Val f1_micro: 0.259
Epoch: 100, Train Loss: 1.264, Val f1_micro: 0.263
Epoch: 120, Train Loss: 1.163, Val f1_micro: 0.271
Epoch: 140, Train Loss: 1.104, Val f1_micro: 0.276
Epoch: 160, Train Loss: 1.036, Val f1_micro: 0.275
Epoch: 180, Train Loss: 0.993, Val f1_micro: 0.276
Epoch: 200, Train Loss: 0.942, Val f1_micro: 0.285
Epoch: 220, Train Loss: 0.897, Val f1_micro: 0.283
Epoch: 240, Train Loss: 0.844, Val f1_micro: 0.289
Epoch: 260, Train Loss: 0.793, Val f1_micro: 0.289
Epoch: 280, Train Loss: 0.762, Val f1_micro: 0.293
Epoch: 300, Train Loss: 0.752, Val f1_micro: 0.298
Epoch: 320, Train Loss: 0.688, Val f1_micro: 0.302
Epoch: 340, Train Loss: 0.649, Val f1_micro: 0.304
Epoch: 360, Train Loss: 0.634, Val f1_micro: 0.303
Epoch: 380, Train Loss: 0.590, Val f1_micro: 0.307
Epoch: 400, Train Loss: 0.548, Val f1_micro: 0.307
Epoch: 420, Train Loss: 0.537, Val f1_micro: 0.308
Epoch: 440, Train Loss: 0.514, Val f1_micro: 0.311
Epoch: 460, Train Loss: 0.497, Val f1_micro: 0.310
Epoch: 480, Train Loss: 0.468, Val f1_micro: 0.312
Epoch: 500, Train Loss: 0.474, Val f1_micro: 0.313
f1-micro: 0.313, f1-macro: 0.307, f1-weighted: 0.314, , roc-auc: 0.680
##### RUN 3 #####
Epoch: 020, Train Loss: 1.856, Val f1_micro: 0.213
Epoch: 040, Train Loss: 1.593, Val f1_micro: 0.232
Epoch: 060, Train Loss: 1.450, Val f1_micro: 0.249
Epoch: 080, Train Loss: 1.335, Val f1_micro: 0.260
Epoch: 100, Train Loss: 1.262, Val f1_micro: 0.261
Epoch: 120, Train Loss: 1.182, Val f1_micro: 0.266
Epoch: 140, Train Loss: 1.129, Val f1_micro: 0.270
Epoch: 160, Train Loss: 1.019, Val f1_micro: 0.277
Epoch: 180, Train Loss: 0.981, Val f1_micro: 0.277
Epoch: 200, Train Loss: 0.929, Val f1_micro: 0.283
Epoch: 220, Train Loss: 0.880, Val f1_micro: 0.288
Epoch: 240, Train Loss: 0.849, Val f1_micro: 0.290
Epoch: 260, Train Loss: 0.777, Val f1_micro: 0.293
Epoch: 280, Train Loss: 0.743, Val f1_micro: 0.296
Epoch: 300, Train Loss: 0.722, Val f1_micro: 0.298
Epoch: 320, Train Loss: 0.666, Val f1_micro: 0.303
Epoch: 340, Train Loss: 0.649, Val f1_micro: 0.299
Epoch: 360, Train Loss: 0.620, Val f1_micro: 0.301
Epoch: 380, Train Loss: 0.602, Val f1_micro: 0.304
Epoch: 400, Train Loss: 0.579, Val f1_micro: 0.304
Epoch: 420, Train Loss: 0.543, Val f1_micro: 0.307
Epoch: 440, Train Loss: 0.540, Val f1_micro: 0.308
Epoch: 460, Train Loss: 0.497, Val f1_micro: 0.307
Epoch: 480, Train Loss: 0.505, Val f1_micro: 0.308
Epoch: 500, Train Loss: 0.463, Val f1_micro: 0.308
f1-micro: 0.308, f1-macro: 0.301, f1-weighted: 0.309, , roc-auc: 0.679
##### RUN 4 #####
Epoch: 020, Train Loss: 1.866, Val f1_micro: 0.219
Epoch: 040, Train Loss: 1.599, Val f1_micro: 0.236
Epoch: 060, Train Loss: 1.481, Val f1_micro: 0.248
Epoch: 080, Train Loss: 1.335, Val f1_micro: 0.254
Epoch: 100, Train Loss: 1.278, Val f1_micro: 0.261
Epoch: 120, Train Loss: 1.199, Val f1_micro: 0.264
Epoch: 140, Train Loss: 1.093, Val f1_micro: 0.267
Epoch: 160, Train Loss: 1.035, Val f1_micro: 0.275
Epoch: 180, Train Loss: 0.993, Val f1_micro: 0.280
Epoch: 200, Train Loss: 0.941, Val f1_micro: 0.286
Epoch: 220, Train Loss: 0.880, Val f1_micro: 0.284
Epoch: 240, Train Loss: 0.851, Val f1_micro: 0.284
Epoch: 260, Train Loss: 0.806, Val f1_micro: 0.290
Epoch: 280, Train Loss: 0.770, Val f1_micro: 0.292
Epoch: 300, Train Loss: 0.726, Val f1_micro: 0.300
Epoch: 320, Train Loss: 0.685, Val f1_micro: 0.296
Epoch: 340, Train Loss: 0.663, Val f1_micro: 0.299
Epoch: 360, Train Loss: 0.631, Val f1_micro: 0.299
Epoch: 380, Train Loss: 0.607, Val f1_micro: 0.303
Epoch: 400, Train Loss: 0.578, Val f1_micro: 0.302
Epoch: 420, Train Loss: 0.553, Val f1_micro: 0.303
Epoch: 440, Train Loss: 0.514, Val f1_micro: 0.303
Epoch: 460, Train Loss: 0.521, Val f1_micro: 0.305
Epoch: 480, Train Loss: 0.481, Val f1_micro: 0.306
Epoch: 500, Train Loss: 0.477, Val f1_micro: 0.311
f1-micro: 0.311, f1-macro: 0.303, f1-weighted: 0.310, , roc-auc: 0.680
##### RUN 5 #####
Epoch: 020, Train Loss: 1.854, Val f1_micro: 0.208
Epoch: 040, Train Loss: 1.589, Val f1_micro: 0.227
Epoch: 060, Train Loss: 1.443, Val f1_micro: 0.248
Epoch: 080, Train Loss: 1.341, Val f1_micro: 0.259
Epoch: 100, Train Loss: 1.257, Val f1_micro: 0.262
Epoch: 120, Train Loss: 1.177, Val f1_micro: 0.269
Epoch: 140, Train Loss: 1.096, Val f1_micro: 0.274
Epoch: 160, Train Loss: 1.057, Val f1_micro: 0.273
Epoch: 180, Train Loss: 0.989, Val f1_micro: 0.279
Epoch: 200, Train Loss: 0.926, Val f1_micro: 0.277
Epoch: 220, Train Loss: 0.895, Val f1_micro: 0.284
Epoch: 240, Train Loss: 0.823, Val f1_micro: 0.289
Epoch: 260, Train Loss: 0.799, Val f1_micro: 0.289
Epoch: 280, Train Loss: 0.759, Val f1_micro: 0.294
Epoch: 300, Train Loss: 0.715, Val f1_micro: 0.295
Epoch: 320, Train Loss: 0.694, Val f1_micro: 0.297
Epoch: 340, Train Loss: 0.651, Val f1_micro: 0.301
Epoch: 360, Train Loss: 0.605, Val f1_micro: 0.308
Epoch: 380, Train Loss: 0.597, Val f1_micro: 0.307
Epoch: 400, Train Loss: 0.593, Val f1_micro: 0.307
Epoch: 420, Train Loss: 0.537, Val f1_micro: 0.308
Epoch: 440, Train Loss: 0.521, Val f1_micro: 0.312
Epoch: 460, Train Loss: 0.516, Val f1_micro: 0.311
Epoch: 480, Train Loss: 0.470, Val f1_micro: 0.314
Epoch: 500, Train Loss: 0.453, Val f1_micro: 0.313
f1-micro: 0.313, f1-macro: 0.307, f1-weighted: 0.314, , roc-auc: 0.681
########## Hyperparameters combination ##########
(1024, 0.6, 0.005, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.870, Val f1_micro: 0.213
Epoch: 040, Train Loss: 1.612, Val f1_micro: 0.221
Epoch: 060, Train Loss: 1.472, Val f1_micro: 0.245
Epoch: 080, Train Loss: 1.380, Val f1_micro: 0.249
Epoch: 100, Train Loss: 1.294, Val f1_micro: 0.249
Epoch: 120, Train Loss: 1.243, Val f1_micro: 0.259
Epoch: 140, Train Loss: 1.203, Val f1_micro: 0.257
Epoch: 160, Train Loss: 1.134, Val f1_micro: 0.261
Epoch: 180, Train Loss: 1.094, Val f1_micro: 0.267
Epoch: 200, Train Loss: 1.067, Val f1_micro: 0.270
Epoch: 220, Train Loss: 1.038, Val f1_micro: 0.269
Epoch: 240, Train Loss: 1.012, Val f1_micro: 0.272
Epoch: 260, Train Loss: 0.950, Val f1_micro: 0.274
Epoch: 280, Train Loss: 0.927, Val f1_micro: 0.283
Epoch: 300, Train Loss: 0.917, Val f1_micro: 0.277
Epoch: 320, Train Loss: 0.912, Val f1_micro: 0.286
Epoch: 340, Train Loss: 0.871, Val f1_micro: 0.284
Epoch: 360, Train Loss: 0.847, Val f1_micro: 0.284
Epoch: 380, Train Loss: 0.838, Val f1_micro: 0.289
Epoch: 400, Train Loss: 0.829, Val f1_micro: 0.290
Epoch: 420, Train Loss: 0.802, Val f1_micro: 0.290
Epoch: 440, Train Loss: 0.797, Val f1_micro: 0.291
Epoch: 460, Train Loss: 0.775, Val f1_micro: 0.290
Epoch: 480, Train Loss: 0.775, Val f1_micro: 0.293
Epoch: 500, Train Loss: 0.752, Val f1_micro: 0.293
f1-micro: 0.293, f1-macro: 0.286, f1-weighted: 0.292, , roc-auc: 0.673
##### RUN 2 #####
Epoch: 020, Train Loss: 1.852, Val f1_micro: 0.216
Epoch: 040, Train Loss: 1.615, Val f1_micro: 0.225
Epoch: 060, Train Loss: 1.484, Val f1_micro: 0.251
Epoch: 080, Train Loss: 1.394, Val f1_micro: 0.250
Epoch: 100, Train Loss: 1.307, Val f1_micro: 0.254
Epoch: 120, Train Loss: 1.245, Val f1_micro: 0.255
Epoch: 140, Train Loss: 1.184, Val f1_micro: 0.260
Epoch: 160, Train Loss: 1.132, Val f1_micro: 0.266
Epoch: 180, Train Loss: 1.088, Val f1_micro: 0.268
Epoch: 200, Train Loss: 1.054, Val f1_micro: 0.271
Epoch: 220, Train Loss: 1.029, Val f1_micro: 0.271
Epoch: 240, Train Loss: 0.994, Val f1_micro: 0.276
Epoch: 260, Train Loss: 0.945, Val f1_micro: 0.279
Epoch: 280, Train Loss: 0.945, Val f1_micro: 0.279
Epoch: 300, Train Loss: 0.915, Val f1_micro: 0.279
Epoch: 320, Train Loss: 0.907, Val f1_micro: 0.283
Epoch: 340, Train Loss: 0.867, Val f1_micro: 0.283
Epoch: 360, Train Loss: 0.835, Val f1_micro: 0.285
Epoch: 380, Train Loss: 0.842, Val f1_micro: 0.285
Epoch: 400, Train Loss: 0.815, Val f1_micro: 0.288
Epoch: 420, Train Loss: 0.798, Val f1_micro: 0.291
Epoch: 440, Train Loss: 0.792, Val f1_micro: 0.294
Epoch: 460, Train Loss: 0.759, Val f1_micro: 0.295
Epoch: 480, Train Loss: 0.775, Val f1_micro: 0.297
Epoch: 500, Train Loss: 0.721, Val f1_micro: 0.297
f1-micro: 0.297, f1-macro: 0.291, f1-weighted: 0.295, , roc-auc: 0.674
##### RUN 3 #####
Epoch: 020, Train Loss: 1.867, Val f1_micro: 0.219
Epoch: 040, Train Loss: 1.618, Val f1_micro: 0.226
Epoch: 060, Train Loss: 1.464, Val f1_micro: 0.249
Epoch: 080, Train Loss: 1.383, Val f1_micro: 0.252
Epoch: 100, Train Loss: 1.314, Val f1_micro: 0.253
Epoch: 120, Train Loss: 1.248, Val f1_micro: 0.256
Epoch: 140, Train Loss: 1.171, Val f1_micro: 0.263
Epoch: 160, Train Loss: 1.139, Val f1_micro: 0.263
Epoch: 180, Train Loss: 1.082, Val f1_micro: 0.270
Epoch: 200, Train Loss: 1.056, Val f1_micro: 0.273
Epoch: 220, Train Loss: 1.025, Val f1_micro: 0.268
Epoch: 240, Train Loss: 0.993, Val f1_micro: 0.278
Epoch: 260, Train Loss: 0.965, Val f1_micro: 0.278
Epoch: 280, Train Loss: 0.943, Val f1_micro: 0.283
Epoch: 300, Train Loss: 0.911, Val f1_micro: 0.284
Epoch: 320, Train Loss: 0.907, Val f1_micro: 0.281
Epoch: 340, Train Loss: 0.865, Val f1_micro: 0.287
Epoch: 360, Train Loss: 0.856, Val f1_micro: 0.289
Epoch: 380, Train Loss: 0.833, Val f1_micro: 0.290
Epoch: 400, Train Loss: 0.818, Val f1_micro: 0.288
Epoch: 420, Train Loss: 0.822, Val f1_micro: 0.291
Epoch: 440, Train Loss: 0.793, Val f1_micro: 0.293
Epoch: 460, Train Loss: 0.795, Val f1_micro: 0.292
Epoch: 480, Train Loss: 0.763, Val f1_micro: 0.299
Epoch: 500, Train Loss: 0.746, Val f1_micro: 0.297
f1-micro: 0.297, f1-macro: 0.291, f1-weighted: 0.296, , roc-auc: 0.674
##### RUN 4 #####
Epoch: 020, Train Loss: 1.842, Val f1_micro: 0.204
Epoch: 040, Train Loss: 1.586, Val f1_micro: 0.218
Epoch: 060, Train Loss: 1.465, Val f1_micro: 0.245
Epoch: 080, Train Loss: 1.389, Val f1_micro: 0.243
Epoch: 100, Train Loss: 1.294, Val f1_micro: 0.260
Epoch: 120, Train Loss: 1.218, Val f1_micro: 0.263
Epoch: 140, Train Loss: 1.215, Val f1_micro: 0.262
Epoch: 160, Train Loss: 1.140, Val f1_micro: 0.269
Epoch: 180, Train Loss: 1.119, Val f1_micro: 0.264
Epoch: 200, Train Loss: 1.054, Val f1_micro: 0.272
Epoch: 220, Train Loss: 1.025, Val f1_micro: 0.277
Epoch: 240, Train Loss: 0.978, Val f1_micro: 0.276
Epoch: 260, Train Loss: 0.968, Val f1_micro: 0.281
Epoch: 280, Train Loss: 0.944, Val f1_micro: 0.278
Epoch: 300, Train Loss: 0.919, Val f1_micro: 0.282
Epoch: 320, Train Loss: 0.912, Val f1_micro: 0.284
Epoch: 340, Train Loss: 0.860, Val f1_micro: 0.282
Epoch: 360, Train Loss: 0.880, Val f1_micro: 0.289
Epoch: 380, Train Loss: 0.855, Val f1_micro: 0.289
Epoch: 400, Train Loss: 0.815, Val f1_micro: 0.287
Epoch: 420, Train Loss: 0.812, Val f1_micro: 0.289
Epoch: 440, Train Loss: 0.797, Val f1_micro: 0.293
Epoch: 460, Train Loss: 0.778, Val f1_micro: 0.292
Epoch: 480, Train Loss: 0.766, Val f1_micro: 0.292
Epoch: 500, Train Loss: 0.736, Val f1_micro: 0.296
f1-micro: 0.296, f1-macro: 0.292, f1-weighted: 0.296, , roc-auc: 0.674
##### RUN 5 #####
Epoch: 020, Train Loss: 1.836, Val f1_micro: 0.211
Epoch: 040, Train Loss: 1.597, Val f1_micro: 0.220
Epoch: 060, Train Loss: 1.467, Val f1_micro: 0.253
Epoch: 080, Train Loss: 1.374, Val f1_micro: 0.251
Epoch: 100, Train Loss: 1.283, Val f1_micro: 0.248
Epoch: 120, Train Loss: 1.239, Val f1_micro: 0.256
Epoch: 140, Train Loss: 1.185, Val f1_micro: 0.258
Epoch: 160, Train Loss: 1.135, Val f1_micro: 0.267
Epoch: 180, Train Loss: 1.099, Val f1_micro: 0.273
Epoch: 200, Train Loss: 1.049, Val f1_micro: 0.271
Epoch: 220, Train Loss: 1.023, Val f1_micro: 0.271
Epoch: 240, Train Loss: 0.990, Val f1_micro: 0.271
Epoch: 260, Train Loss: 0.954, Val f1_micro: 0.279
Epoch: 280, Train Loss: 0.936, Val f1_micro: 0.278
Epoch: 300, Train Loss: 0.922, Val f1_micro: 0.279
Epoch: 320, Train Loss: 0.890, Val f1_micro: 0.281
Epoch: 340, Train Loss: 0.898, Val f1_micro: 0.286
Epoch: 360, Train Loss: 0.859, Val f1_micro: 0.288
Epoch: 380, Train Loss: 0.833, Val f1_micro: 0.288
Epoch: 400, Train Loss: 0.797, Val f1_micro: 0.292
Epoch: 420, Train Loss: 0.796, Val f1_micro: 0.290
Epoch: 440, Train Loss: 0.794, Val f1_micro: 0.296
Epoch: 460, Train Loss: 0.776, Val f1_micro: 0.290
Epoch: 480, Train Loss: 0.752, Val f1_micro: 0.296
Epoch: 500, Train Loss: 0.735, Val f1_micro: 0.292
f1-micro: 0.292, f1-macro: 0.287, f1-weighted: 0.292, , roc-auc: 0.673
########## Hyperparameters combination ##########
(1024, 0.6, 0.005, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.859, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.635, Val f1_micro: 0.220
Epoch: 060, Train Loss: 1.502, Val f1_micro: 0.240
Epoch: 080, Train Loss: 1.436, Val f1_micro: 0.242
Epoch: 100, Train Loss: 1.358, Val f1_micro: 0.252
Epoch: 120, Train Loss: 1.322, Val f1_micro: 0.251
Epoch: 140, Train Loss: 1.280, Val f1_micro: 0.251
Epoch: 160, Train Loss: 1.269, Val f1_micro: 0.259
Epoch: 180, Train Loss: 1.230, Val f1_micro: 0.261
Epoch: 200, Train Loss: 1.201, Val f1_micro: 0.260
Epoch: 220, Train Loss: 1.172, Val f1_micro: 0.264
Epoch: 240, Train Loss: 1.166, Val f1_micro: 0.261
Epoch: 260, Train Loss: 1.145, Val f1_micro: 0.265
Epoch: 280, Train Loss: 1.113, Val f1_micro: 0.263
Epoch: 300, Train Loss: 1.095, Val f1_micro: 0.264
Epoch: 320, Train Loss: 1.092, Val f1_micro: 0.271
Epoch: 340, Train Loss: 1.074, Val f1_micro: 0.270
Epoch: 360, Train Loss: 1.063, Val f1_micro: 0.271
Epoch: 380, Train Loss: 1.054, Val f1_micro: 0.274
Epoch: 400, Train Loss: 1.046, Val f1_micro: 0.274
Epoch: 420, Train Loss: 1.063, Val f1_micro: 0.274
Epoch: 440, Train Loss: 1.012, Val f1_micro: 0.277
Epoch: 460, Train Loss: 1.010, Val f1_micro: 0.275
Epoch: 480, Train Loss: 1.019, Val f1_micro: 0.274
Epoch: 500, Train Loss: 1.002, Val f1_micro: 0.274
f1-micro: 0.274, f1-macro: 0.269, f1-weighted: 0.272, , roc-auc: 0.673
##### RUN 2 #####
Epoch: 020, Train Loss: 1.848, Val f1_micro: 0.216
Epoch: 040, Train Loss: 1.630, Val f1_micro: 0.233
Epoch: 060, Train Loss: 1.530, Val f1_micro: 0.239
Epoch: 080, Train Loss: 1.437, Val f1_micro: 0.247
Epoch: 100, Train Loss: 1.379, Val f1_micro: 0.247
Epoch: 120, Train Loss: 1.339, Val f1_micro: 0.251
Epoch: 140, Train Loss: 1.288, Val f1_micro: 0.254
Epoch: 160, Train Loss: 1.256, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.229, Val f1_micro: 0.260
Epoch: 200, Train Loss: 1.202, Val f1_micro: 0.259
Epoch: 220, Train Loss: 1.189, Val f1_micro: 0.262
Epoch: 240, Train Loss: 1.172, Val f1_micro: 0.263
Epoch: 260, Train Loss: 1.134, Val f1_micro: 0.263
Epoch: 280, Train Loss: 1.141, Val f1_micro: 0.264
Epoch: 300, Train Loss: 1.096, Val f1_micro: 0.273
Epoch: 320, Train Loss: 1.102, Val f1_micro: 0.269
Epoch: 340, Train Loss: 1.070, Val f1_micro: 0.268
Epoch: 360, Train Loss: 1.080, Val f1_micro: 0.271
Epoch: 380, Train Loss: 1.024, Val f1_micro: 0.268
Epoch: 400, Train Loss: 1.027, Val f1_micro: 0.272
Epoch: 420, Train Loss: 1.027, Val f1_micro: 0.274
Epoch: 440, Train Loss: 1.029, Val f1_micro: 0.276
Epoch: 460, Train Loss: 1.008, Val f1_micro: 0.278
Epoch: 480, Train Loss: 1.017, Val f1_micro: 0.277
Epoch: 500, Train Loss: 1.007, Val f1_micro: 0.275
f1-micro: 0.275, f1-macro: 0.268, f1-weighted: 0.270, , roc-auc: 0.671
##### RUN 3 #####
Epoch: 020, Train Loss: 1.882, Val f1_micro: 0.210
Epoch: 040, Train Loss: 1.613, Val f1_micro: 0.225
Epoch: 060, Train Loss: 1.520, Val f1_micro: 0.240
Epoch: 080, Train Loss: 1.414, Val f1_micro: 0.246
Epoch: 100, Train Loss: 1.367, Val f1_micro: 0.249
Epoch: 120, Train Loss: 1.330, Val f1_micro: 0.249
Epoch: 140, Train Loss: 1.284, Val f1_micro: 0.259
Epoch: 160, Train Loss: 1.249, Val f1_micro: 0.256
Epoch: 180, Train Loss: 1.244, Val f1_micro: 0.255
Epoch: 200, Train Loss: 1.199, Val f1_micro: 0.262
Epoch: 220, Train Loss: 1.167, Val f1_micro: 0.262
Epoch: 240, Train Loss: 1.164, Val f1_micro: 0.269
Epoch: 260, Train Loss: 1.136, Val f1_micro: 0.264
Epoch: 280, Train Loss: 1.101, Val f1_micro: 0.269
Epoch: 300, Train Loss: 1.119, Val f1_micro: 0.269
Epoch: 320, Train Loss: 1.090, Val f1_micro: 0.268
Epoch: 340, Train Loss: 1.078, Val f1_micro: 0.271
Epoch: 360, Train Loss: 1.058, Val f1_micro: 0.274
Epoch: 380, Train Loss: 1.049, Val f1_micro: 0.276
Epoch: 400, Train Loss: 1.045, Val f1_micro: 0.277
Epoch: 420, Train Loss: 1.025, Val f1_micro: 0.278
Epoch: 440, Train Loss: 1.033, Val f1_micro: 0.281
Epoch: 460, Train Loss: 1.010, Val f1_micro: 0.281
Epoch: 480, Train Loss: 1.000, Val f1_micro: 0.278
Epoch: 500, Train Loss: 1.018, Val f1_micro: 0.278
f1-micro: 0.278, f1-macro: 0.270, f1-weighted: 0.273, , roc-auc: 0.673
##### RUN 4 #####
Epoch: 020, Train Loss: 1.863, Val f1_micro: 0.214
Epoch: 040, Train Loss: 1.626, Val f1_micro: 0.238
Epoch: 060, Train Loss: 1.498, Val f1_micro: 0.248
Epoch: 080, Train Loss: 1.431, Val f1_micro: 0.249
Epoch: 100, Train Loss: 1.373, Val f1_micro: 0.251
Epoch: 120, Train Loss: 1.326, Val f1_micro: 0.252
Epoch: 140, Train Loss: 1.294, Val f1_micro: 0.259
Epoch: 160, Train Loss: 1.256, Val f1_micro: 0.261
Epoch: 180, Train Loss: 1.213, Val f1_micro: 0.257
Epoch: 200, Train Loss: 1.193, Val f1_micro: 0.260
Epoch: 220, Train Loss: 1.162, Val f1_micro: 0.259
Epoch: 240, Train Loss: 1.146, Val f1_micro: 0.265
Epoch: 260, Train Loss: 1.120, Val f1_micro: 0.268
Epoch: 280, Train Loss: 1.115, Val f1_micro: 0.267
Epoch: 300, Train Loss: 1.097, Val f1_micro: 0.267
Epoch: 320, Train Loss: 1.078, Val f1_micro: 0.271
Epoch: 340, Train Loss: 1.086, Val f1_micro: 0.272
Epoch: 360, Train Loss: 1.073, Val f1_micro: 0.275
Epoch: 380, Train Loss: 1.065, Val f1_micro: 0.271
Epoch: 400, Train Loss: 1.027, Val f1_micro: 0.272
Epoch: 420, Train Loss: 1.018, Val f1_micro: 0.275
Epoch: 440, Train Loss: 1.017, Val f1_micro: 0.275
Epoch: 460, Train Loss: 1.011, Val f1_micro: 0.273
Epoch: 480, Train Loss: 0.987, Val f1_micro: 0.277
Epoch: 500, Train Loss: 0.991, Val f1_micro: 0.277
f1-micro: 0.277, f1-macro: 0.270, f1-weighted: 0.273, , roc-auc: 0.673
##### RUN 5 #####
Epoch: 020, Train Loss: 1.865, Val f1_micro: 0.219
Epoch: 040, Train Loss: 1.622, Val f1_micro: 0.224
Epoch: 060, Train Loss: 1.501, Val f1_micro: 0.245
Epoch: 080, Train Loss: 1.417, Val f1_micro: 0.250
Epoch: 100, Train Loss: 1.374, Val f1_micro: 0.245
Epoch: 120, Train Loss: 1.328, Val f1_micro: 0.253
Epoch: 140, Train Loss: 1.301, Val f1_micro: 0.258
Epoch: 160, Train Loss: 1.236, Val f1_micro: 0.259
Epoch: 180, Train Loss: 1.209, Val f1_micro: 0.262
Epoch: 200, Train Loss: 1.192, Val f1_micro: 0.265
Epoch: 220, Train Loss: 1.170, Val f1_micro: 0.265
Epoch: 240, Train Loss: 1.153, Val f1_micro: 0.263
Epoch: 260, Train Loss: 1.129, Val f1_micro: 0.267
Epoch: 280, Train Loss: 1.107, Val f1_micro: 0.269
Epoch: 300, Train Loss: 1.097, Val f1_micro: 0.271
Epoch: 320, Train Loss: 1.088, Val f1_micro: 0.273
Epoch: 340, Train Loss: 1.076, Val f1_micro: 0.270
Epoch: 360, Train Loss: 1.042, Val f1_micro: 0.277
Epoch: 380, Train Loss: 1.077, Val f1_micro: 0.270
Epoch: 400, Train Loss: 1.041, Val f1_micro: 0.279
Epoch: 420, Train Loss: 1.019, Val f1_micro: 0.277
Epoch: 440, Train Loss: 1.027, Val f1_micro: 0.276
Epoch: 460, Train Loss: 0.995, Val f1_micro: 0.281
Epoch: 480, Train Loss: 0.989, Val f1_micro: 0.281
Epoch: 500, Train Loss: 1.005, Val f1_micro: 0.279
f1-micro: 0.279, f1-macro: 0.271, f1-weighted: 0.275, , roc-auc: 0.672
########## Hyperparameters combination ##########
(1024, 0.6, 0.005, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.873, Val f1_micro: 0.211
Epoch: 040, Train Loss: 1.710, Val f1_micro: 0.217
Epoch: 060, Train Loss: 1.665, Val f1_micro: 0.226
Epoch: 080, Train Loss: 1.667, Val f1_micro: 0.215
Epoch: 100, Train Loss: 1.659, Val f1_micro: 0.223
Epoch: 120, Train Loss: 1.670, Val f1_micro: 0.219
Epoch: 140, Train Loss: 1.687, Val f1_micro: 0.221
Epoch: 160, Train Loss: 1.676, Val f1_micro: 0.215
Epoch: 180, Train Loss: 1.685, Val f1_micro: 0.215
Epoch: 200, Train Loss: 1.707, Val f1_micro: 0.210
Epoch: 220, Train Loss: 1.697, Val f1_micro: 0.207
Epoch: 240, Train Loss: 1.700, Val f1_micro: 0.210
Epoch: 260, Train Loss: 1.686, Val f1_micro: 0.209
Epoch: 280, Train Loss: 1.705, Val f1_micro: 0.217
Epoch: 300, Train Loss: 1.709, Val f1_micro: 0.212
Epoch: 320, Train Loss: 1.698, Val f1_micro: 0.208
Epoch: 340, Train Loss: 1.713, Val f1_micro: 0.211
Epoch: 360, Train Loss: 1.704, Val f1_micro: 0.215
Epoch: 380, Train Loss: 1.705, Val f1_micro: 0.215
Epoch: 400, Train Loss: 1.713, Val f1_micro: 0.208
Epoch: 420, Train Loss: 1.706, Val f1_micro: 0.216
Epoch: 440, Train Loss: 1.699, Val f1_micro: 0.208
Epoch: 460, Train Loss: 1.710, Val f1_micro: 0.216
Epoch: 480, Train Loss: 1.698, Val f1_micro: 0.207
Epoch: 500, Train Loss: 1.694, Val f1_micro: 0.215
f1-micro: 0.215, f1-macro: 0.189, f1-weighted: 0.187, , roc-auc: 0.639
##### RUN 2 #####
Epoch: 020, Train Loss: 1.872, Val f1_micro: 0.198
Epoch: 040, Train Loss: 1.713, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.665, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.655, Val f1_micro: 0.214
Epoch: 100, Train Loss: 1.658, Val f1_micro: 0.219
Epoch: 120, Train Loss: 1.678, Val f1_micro: 0.214
Epoch: 140, Train Loss: 1.671, Val f1_micro: 0.218
Epoch: 160, Train Loss: 1.677, Val f1_micro: 0.220
Epoch: 180, Train Loss: 1.693, Val f1_micro: 0.213
Epoch: 200, Train Loss: 1.700, Val f1_micro: 0.216
Epoch: 220, Train Loss: 1.694, Val f1_micro: 0.216
Epoch: 240, Train Loss: 1.707, Val f1_micro: 0.219
Epoch: 260, Train Loss: 1.699, Val f1_micro: 0.208
Epoch: 280, Train Loss: 1.703, Val f1_micro: 0.214
Epoch: 300, Train Loss: 1.699, Val f1_micro: 0.216
Epoch: 320, Train Loss: 1.701, Val f1_micro: 0.219
Epoch: 340, Train Loss: 1.709, Val f1_micro: 0.210
Epoch: 360, Train Loss: 1.701, Val f1_micro: 0.214
Epoch: 380, Train Loss: 1.699, Val f1_micro: 0.212
Epoch: 400, Train Loss: 1.708, Val f1_micro: 0.211
Epoch: 420, Train Loss: 1.707, Val f1_micro: 0.211
Epoch: 440, Train Loss: 1.698, Val f1_micro: 0.217
Epoch: 460, Train Loss: 1.703, Val f1_micro: 0.213
Epoch: 480, Train Loss: 1.704, Val f1_micro: 0.215
Epoch: 500, Train Loss: 1.704, Val f1_micro: 0.215
f1-micro: 0.215, f1-macro: 0.183, f1-weighted: 0.182, , roc-auc: 0.639
##### RUN 3 #####
Epoch: 020, Train Loss: 1.888, Val f1_micro: 0.200
Epoch: 040, Train Loss: 1.713, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.670, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.657, Val f1_micro: 0.216
Epoch: 100, Train Loss: 1.664, Val f1_micro: 0.218
Epoch: 120, Train Loss: 1.670, Val f1_micro: 0.219
Epoch: 140, Train Loss: 1.687, Val f1_micro: 0.213
Epoch: 160, Train Loss: 1.688, Val f1_micro: 0.215
Epoch: 180, Train Loss: 1.685, Val f1_micro: 0.211
Epoch: 200, Train Loss: 1.688, Val f1_micro: 0.213
Epoch: 220, Train Loss: 1.703, Val f1_micro: 0.216
Epoch: 240, Train Loss: 1.688, Val f1_micro: 0.219
Epoch: 260, Train Loss: 1.700, Val f1_micro: 0.207
Epoch: 280, Train Loss: 1.700, Val f1_micro: 0.211
Epoch: 300, Train Loss: 1.725, Val f1_micro: 0.214
Epoch: 320, Train Loss: 1.702, Val f1_micro: 0.208
Epoch: 340, Train Loss: 1.714, Val f1_micro: 0.209
Epoch: 360, Train Loss: 1.719, Val f1_micro: 0.208
Epoch: 380, Train Loss: 1.698, Val f1_micro: 0.206
Epoch: 400, Train Loss: 1.706, Val f1_micro: 0.209
Epoch: 420, Train Loss: 1.711, Val f1_micro: 0.206
Epoch: 440, Train Loss: 1.700, Val f1_micro: 0.210
Epoch: 460, Train Loss: 1.712, Val f1_micro: 0.205
Epoch: 480, Train Loss: 1.699, Val f1_micro: 0.211
Epoch: 500, Train Loss: 1.703, Val f1_micro: 0.209
f1-micro: 0.209, f1-macro: 0.184, f1-weighted: 0.179, , roc-auc: 0.639
##### RUN 4 #####
Epoch: 020, Train Loss: 1.863, Val f1_micro: 0.206
Epoch: 040, Train Loss: 1.713, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.671, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.665, Val f1_micro: 0.223
Epoch: 100, Train Loss: 1.670, Val f1_micro: 0.222
Epoch: 120, Train Loss: 1.666, Val f1_micro: 0.216
Epoch: 140, Train Loss: 1.659, Val f1_micro: 0.212
Epoch: 160, Train Loss: 1.688, Val f1_micro: 0.217
Epoch: 180, Train Loss: 1.673, Val f1_micro: 0.211
Epoch: 200, Train Loss: 1.691, Val f1_micro: 0.214
Epoch: 220, Train Loss: 1.694, Val f1_micro: 0.218
Epoch: 240, Train Loss: 1.708, Val f1_micro: 0.211
Epoch: 260, Train Loss: 1.708, Val f1_micro: 0.209
Epoch: 280, Train Loss: 1.684, Val f1_micro: 0.208
Epoch: 300, Train Loss: 1.705, Val f1_micro: 0.210
Epoch: 320, Train Loss: 1.701, Val f1_micro: 0.209
Epoch: 340, Train Loss: 1.701, Val f1_micro: 0.211
Epoch: 360, Train Loss: 1.711, Val f1_micro: 0.210
Epoch: 380, Train Loss: 1.708, Val f1_micro: 0.207
Epoch: 400, Train Loss: 1.709, Val f1_micro: 0.212
Epoch: 420, Train Loss: 1.697, Val f1_micro: 0.208
Epoch: 440, Train Loss: 1.696, Val f1_micro: 0.211
Epoch: 460, Train Loss: 1.703, Val f1_micro: 0.211
Epoch: 480, Train Loss: 1.693, Val f1_micro: 0.214
Epoch: 500, Train Loss: 1.695, Val f1_micro: 0.210
f1-micro: 0.210, f1-macro: 0.184, f1-weighted: 0.180, , roc-auc: 0.637
##### RUN 5 #####
Epoch: 020, Train Loss: 1.888, Val f1_micro: 0.207
Epoch: 040, Train Loss: 1.710, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.668, Val f1_micro: 0.223
Epoch: 080, Train Loss: 1.656, Val f1_micro: 0.217
Epoch: 100, Train Loss: 1.676, Val f1_micro: 0.217
Epoch: 120, Train Loss: 1.676, Val f1_micro: 0.224
Epoch: 140, Train Loss: 1.686, Val f1_micro: 0.223
Epoch: 160, Train Loss: 1.689, Val f1_micro: 0.219
Epoch: 180, Train Loss: 1.679, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.687, Val f1_micro: 0.210
Epoch: 220, Train Loss: 1.689, Val f1_micro: 0.216
Epoch: 240, Train Loss: 1.703, Val f1_micro: 0.208
Epoch: 260, Train Loss: 1.697, Val f1_micro: 0.213
Epoch: 280, Train Loss: 1.707, Val f1_micro: 0.212
Epoch: 300, Train Loss: 1.702, Val f1_micro: 0.215
Epoch: 320, Train Loss: 1.700, Val f1_micro: 0.209
Epoch: 340, Train Loss: 1.709, Val f1_micro: 0.211
Epoch: 360, Train Loss: 1.712, Val f1_micro: 0.216
Epoch: 380, Train Loss: 1.701, Val f1_micro: 0.209
Epoch: 400, Train Loss: 1.703, Val f1_micro: 0.215
Epoch: 420, Train Loss: 1.709, Val f1_micro: 0.218
Epoch: 440, Train Loss: 1.708, Val f1_micro: 0.210
Epoch: 460, Train Loss: 1.705, Val f1_micro: 0.216
Epoch: 480, Train Loss: 1.701, Val f1_micro: 0.210
Epoch: 500, Train Loss: 1.700, Val f1_micro: 0.210
f1-micro: 0.210, f1-macro: 0.187, f1-weighted: 0.183, , roc-auc: 0.638
########## Hyperparameters combination ##########
(1024, 0.6, 0.01, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.810, Val f1_micro: 0.184
Epoch: 040, Train Loss: 1.520, Val f1_micro: 0.226
Epoch: 060, Train Loss: 1.348, Val f1_micro: 0.248
Epoch: 080, Train Loss: 1.249, Val f1_micro: 0.259
Epoch: 100, Train Loss: 1.153, Val f1_micro: 0.264
Epoch: 120, Train Loss: 1.042, Val f1_micro: 0.275
Epoch: 140, Train Loss: 0.945, Val f1_micro: 0.275
Epoch: 160, Train Loss: 0.899, Val f1_micro: 0.281
Epoch: 180, Train Loss: 0.816, Val f1_micro: 0.286
Epoch: 200, Train Loss: 0.760, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.718, Val f1_micro: 0.292
Epoch: 240, Train Loss: 0.668, Val f1_micro: 0.295
Epoch: 260, Train Loss: 0.655, Val f1_micro: 0.298
Epoch: 280, Train Loss: 0.584, Val f1_micro: 0.306
Epoch: 300, Train Loss: 0.544, Val f1_micro: 0.304
Epoch: 320, Train Loss: 0.522, Val f1_micro: 0.300
Epoch: 340, Train Loss: 0.496, Val f1_micro: 0.310
Epoch: 360, Train Loss: 0.457, Val f1_micro: 0.308
Epoch: 380, Train Loss: 0.439, Val f1_micro: 0.309
Epoch: 400, Train Loss: 0.419, Val f1_micro: 0.312
Epoch: 420, Train Loss: 0.405, Val f1_micro: 0.312
Epoch: 440, Train Loss: 0.379, Val f1_micro: 0.313
Epoch: 460, Train Loss: 0.369, Val f1_micro: 0.311
Epoch: 480, Train Loss: 0.348, Val f1_micro: 0.312
Epoch: 500, Train Loss: 0.345, Val f1_micro: 0.313
f1-micro: 0.313, f1-macro: 0.308, f1-weighted: 0.314, , roc-auc: 0.680
##### RUN 2 #####
Epoch: 020, Train Loss: 1.791, Val f1_micro: 0.200
Epoch: 040, Train Loss: 1.535, Val f1_micro: 0.237
Epoch: 060, Train Loss: 1.362, Val f1_micro: 0.255
Epoch: 080, Train Loss: 1.238, Val f1_micro: 0.257
Epoch: 100, Train Loss: 1.133, Val f1_micro: 0.266
Epoch: 120, Train Loss: 1.059, Val f1_micro: 0.272
Epoch: 140, Train Loss: 0.959, Val f1_micro: 0.276
Epoch: 160, Train Loss: 0.877, Val f1_micro: 0.284
Epoch: 180, Train Loss: 0.816, Val f1_micro: 0.288
Epoch: 200, Train Loss: 0.751, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.707, Val f1_micro: 0.295
Epoch: 240, Train Loss: 0.679, Val f1_micro: 0.298
Epoch: 260, Train Loss: 0.599, Val f1_micro: 0.299
Epoch: 280, Train Loss: 0.589, Val f1_micro: 0.300
Epoch: 300, Train Loss: 0.533, Val f1_micro: 0.301
Epoch: 320, Train Loss: 0.528, Val f1_micro: 0.304
Epoch: 340, Train Loss: 0.481, Val f1_micro: 0.306
Epoch: 360, Train Loss: 0.445, Val f1_micro: 0.309
Epoch: 380, Train Loss: 0.438, Val f1_micro: 0.307
Epoch: 400, Train Loss: 0.423, Val f1_micro: 0.306
Epoch: 420, Train Loss: 0.401, Val f1_micro: 0.308
Epoch: 440, Train Loss: 0.396, Val f1_micro: 0.309
Epoch: 460, Train Loss: 0.382, Val f1_micro: 0.311
Epoch: 480, Train Loss: 0.359, Val f1_micro: 0.310
Epoch: 500, Train Loss: 0.342, Val f1_micro: 0.310
f1-micro: 0.310, f1-macro: 0.305, f1-weighted: 0.311, , roc-auc: 0.681
##### RUN 3 #####
Epoch: 020, Train Loss: 1.770, Val f1_micro: 0.196
Epoch: 040, Train Loss: 1.559, Val f1_micro: 0.237
Epoch: 060, Train Loss: 1.377, Val f1_micro: 0.254
Epoch: 080, Train Loss: 1.234, Val f1_micro: 0.261
Epoch: 100, Train Loss: 1.149, Val f1_micro: 0.263
Epoch: 120, Train Loss: 1.052, Val f1_micro: 0.273
Epoch: 140, Train Loss: 0.968, Val f1_micro: 0.277
Epoch: 160, Train Loss: 0.898, Val f1_micro: 0.281
Epoch: 180, Train Loss: 0.849, Val f1_micro: 0.287
Epoch: 200, Train Loss: 0.764, Val f1_micro: 0.292
Epoch: 220, Train Loss: 0.710, Val f1_micro: 0.298
Epoch: 240, Train Loss: 0.691, Val f1_micro: 0.298
Epoch: 260, Train Loss: 0.640, Val f1_micro: 0.300
Epoch: 280, Train Loss: 0.581, Val f1_micro: 0.304
Epoch: 300, Train Loss: 0.535, Val f1_micro: 0.307
Epoch: 320, Train Loss: 0.528, Val f1_micro: 0.308
Epoch: 340, Train Loss: 0.480, Val f1_micro: 0.310
Epoch: 360, Train Loss: 0.474, Val f1_micro: 0.310
Epoch: 380, Train Loss: 0.450, Val f1_micro: 0.309
Epoch: 400, Train Loss: 0.432, Val f1_micro: 0.311
Epoch: 420, Train Loss: 0.413, Val f1_micro: 0.312
Epoch: 440, Train Loss: 0.398, Val f1_micro: 0.311
Epoch: 460, Train Loss: 0.348, Val f1_micro: 0.310
Epoch: 480, Train Loss: 0.367, Val f1_micro: 0.313
Epoch: 500, Train Loss: 0.356, Val f1_micro: 0.309
f1-micro: 0.309, f1-macro: 0.305, f1-weighted: 0.310, , roc-auc: 0.678
##### RUN 4 #####
Epoch: 020, Train Loss: 1.796, Val f1_micro: 0.196
Epoch: 040, Train Loss: 1.548, Val f1_micro: 0.228
Epoch: 060, Train Loss: 1.361, Val f1_micro: 0.244
Epoch: 080, Train Loss: 1.230, Val f1_micro: 0.255
Epoch: 100, Train Loss: 1.145, Val f1_micro: 0.263
Epoch: 120, Train Loss: 1.048, Val f1_micro: 0.274
Epoch: 140, Train Loss: 0.972, Val f1_micro: 0.279
Epoch: 160, Train Loss: 0.924, Val f1_micro: 0.280
Epoch: 180, Train Loss: 0.833, Val f1_micro: 0.289
Epoch: 200, Train Loss: 0.797, Val f1_micro: 0.292
Epoch: 220, Train Loss: 0.742, Val f1_micro: 0.293
Epoch: 240, Train Loss: 0.709, Val f1_micro: 0.299
Epoch: 260, Train Loss: 0.644, Val f1_micro: 0.302
Epoch: 280, Train Loss: 0.593, Val f1_micro: 0.306
Epoch: 300, Train Loss: 0.532, Val f1_micro: 0.307
Epoch: 320, Train Loss: 0.512, Val f1_micro: 0.310
Epoch: 340, Train Loss: 0.499, Val f1_micro: 0.308
Epoch: 360, Train Loss: 0.472, Val f1_micro: 0.313
Epoch: 380, Train Loss: 0.448, Val f1_micro: 0.313
Epoch: 400, Train Loss: 0.426, Val f1_micro: 0.310
Epoch: 420, Train Loss: 0.387, Val f1_micro: 0.313
Epoch: 440, Train Loss: 0.394, Val f1_micro: 0.310
Epoch: 460, Train Loss: 0.397, Val f1_micro: 0.310
Epoch: 480, Train Loss: 0.361, Val f1_micro: 0.314
Epoch: 500, Train Loss: 0.343, Val f1_micro: 0.313
f1-micro: 0.313, f1-macro: 0.308, f1-weighted: 0.313, , roc-auc: 0.682
##### RUN 5 #####
Epoch: 020, Train Loss: 1.796, Val f1_micro: 0.195
Epoch: 040, Train Loss: 1.506, Val f1_micro: 0.235
Epoch: 060, Train Loss: 1.374, Val f1_micro: 0.251
Epoch: 080, Train Loss: 1.262, Val f1_micro: 0.257
Epoch: 100, Train Loss: 1.139, Val f1_micro: 0.262
Epoch: 120, Train Loss: 1.040, Val f1_micro: 0.268
Epoch: 140, Train Loss: 0.978, Val f1_micro: 0.281
Epoch: 160, Train Loss: 0.898, Val f1_micro: 0.285
Epoch: 180, Train Loss: 0.834, Val f1_micro: 0.288
Epoch: 200, Train Loss: 0.762, Val f1_micro: 0.290
Epoch: 220, Train Loss: 0.711, Val f1_micro: 0.295
Epoch: 240, Train Loss: 0.673, Val f1_micro: 0.296
Epoch: 260, Train Loss: 0.611, Val f1_micro: 0.301
Epoch: 280, Train Loss: 0.552, Val f1_micro: 0.307
Epoch: 300, Train Loss: 0.553, Val f1_micro: 0.305
Epoch: 320, Train Loss: 0.500, Val f1_micro: 0.308
Epoch: 340, Train Loss: 0.488, Val f1_micro: 0.310
Epoch: 360, Train Loss: 0.462, Val f1_micro: 0.313
Epoch: 380, Train Loss: 0.428, Val f1_micro: 0.313
Epoch: 400, Train Loss: 0.421, Val f1_micro: 0.312
Epoch: 420, Train Loss: 0.390, Val f1_micro: 0.311
Epoch: 440, Train Loss: 0.388, Val f1_micro: 0.310
Epoch: 460, Train Loss: 0.370, Val f1_micro: 0.311
Epoch: 480, Train Loss: 0.355, Val f1_micro: 0.315
Epoch: 500, Train Loss: 0.342, Val f1_micro: 0.310
f1-micro: 0.310, f1-macro: 0.306, f1-weighted: 0.311, , roc-auc: 0.678
########## Hyperparameters combination ##########
(1024, 0.6, 0.01, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.805, Val f1_micro: 0.211
Epoch: 040, Train Loss: 1.554, Val f1_micro: 0.234
Epoch: 060, Train Loss: 1.440, Val f1_micro: 0.245
Epoch: 080, Train Loss: 1.335, Val f1_micro: 0.255
Epoch: 100, Train Loss: 1.244, Val f1_micro: 0.260
Epoch: 120, Train Loss: 1.183, Val f1_micro: 0.264
Epoch: 140, Train Loss: 1.128, Val f1_micro: 0.263
Epoch: 160, Train Loss: 1.066, Val f1_micro: 0.270
Epoch: 180, Train Loss: 1.013, Val f1_micro: 0.273
Epoch: 200, Train Loss: 0.966, Val f1_micro: 0.278
Epoch: 220, Train Loss: 0.920, Val f1_micro: 0.282
Epoch: 240, Train Loss: 0.924, Val f1_micro: 0.283
Epoch: 260, Train Loss: 0.886, Val f1_micro: 0.285
Epoch: 280, Train Loss: 0.838, Val f1_micro: 0.287
Epoch: 300, Train Loss: 0.826, Val f1_micro: 0.293
Epoch: 320, Train Loss: 0.774, Val f1_micro: 0.293
Epoch: 340, Train Loss: 0.783, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.756, Val f1_micro: 0.298
Epoch: 380, Train Loss: 0.723, Val f1_micro: 0.298
Epoch: 400, Train Loss: 0.717, Val f1_micro: 0.293
Epoch: 420, Train Loss: 0.723, Val f1_micro: 0.300
Epoch: 440, Train Loss: 0.709, Val f1_micro: 0.303
Epoch: 460, Train Loss: 0.687, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.682, Val f1_micro: 0.300
Epoch: 500, Train Loss: 0.645, Val f1_micro: 0.301
f1-micro: 0.301, f1-macro: 0.295, f1-weighted: 0.300, , roc-auc: 0.673
##### RUN 2 #####
Epoch: 020, Train Loss: 1.816, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.571, Val f1_micro: 0.237
Epoch: 060, Train Loss: 1.440, Val f1_micro: 0.257
Epoch: 080, Train Loss: 1.324, Val f1_micro: 0.253
Epoch: 100, Train Loss: 1.250, Val f1_micro: 0.256
Epoch: 120, Train Loss: 1.176, Val f1_micro: 0.261
Epoch: 140, Train Loss: 1.131, Val f1_micro: 0.268
Epoch: 160, Train Loss: 1.085, Val f1_micro: 0.269
Epoch: 180, Train Loss: 1.053, Val f1_micro: 0.269
Epoch: 200, Train Loss: 0.988, Val f1_micro: 0.279
Epoch: 220, Train Loss: 0.935, Val f1_micro: 0.273
Epoch: 240, Train Loss: 0.913, Val f1_micro: 0.280
Epoch: 260, Train Loss: 0.903, Val f1_micro: 0.282
Epoch: 280, Train Loss: 0.869, Val f1_micro: 0.285
Epoch: 300, Train Loss: 0.827, Val f1_micro: 0.288
Epoch: 320, Train Loss: 0.831, Val f1_micro: 0.286
Epoch: 340, Train Loss: 0.782, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.782, Val f1_micro: 0.292
Epoch: 380, Train Loss: 0.748, Val f1_micro: 0.294
Epoch: 400, Train Loss: 0.724, Val f1_micro: 0.289
Epoch: 420, Train Loss: 0.708, Val f1_micro: 0.293
Epoch: 440, Train Loss: 0.710, Val f1_micro: 0.296
Epoch: 460, Train Loss: 0.701, Val f1_micro: 0.296
Epoch: 480, Train Loss: 0.677, Val f1_micro: 0.299
Epoch: 500, Train Loss: 0.673, Val f1_micro: 0.296
f1-micro: 0.296, f1-macro: 0.292, f1-weighted: 0.298, , roc-auc: 0.673
##### RUN 3 #####
Epoch: 020, Train Loss: 1.809, Val f1_micro: 0.190
Epoch: 040, Train Loss: 1.573, Val f1_micro: 0.234
Epoch: 060, Train Loss: 1.440, Val f1_micro: 0.249
Epoch: 080, Train Loss: 1.325, Val f1_micro: 0.254
Epoch: 100, Train Loss: 1.245, Val f1_micro: 0.256
Epoch: 120, Train Loss: 1.180, Val f1_micro: 0.263
Epoch: 140, Train Loss: 1.130, Val f1_micro: 0.264
Epoch: 160, Train Loss: 1.068, Val f1_micro: 0.265
Epoch: 180, Train Loss: 1.028, Val f1_micro: 0.273
Epoch: 200, Train Loss: 0.990, Val f1_micro: 0.282
Epoch: 220, Train Loss: 0.941, Val f1_micro: 0.284
Epoch: 240, Train Loss: 0.882, Val f1_micro: 0.282
Epoch: 260, Train Loss: 0.893, Val f1_micro: 0.283
Epoch: 280, Train Loss: 0.849, Val f1_micro: 0.291
Epoch: 300, Train Loss: 0.824, Val f1_micro: 0.288
Epoch: 320, Train Loss: 0.788, Val f1_micro: 0.292
Epoch: 340, Train Loss: 0.779, Val f1_micro: 0.290
Epoch: 360, Train Loss: 0.743, Val f1_micro: 0.298
Epoch: 380, Train Loss: 0.746, Val f1_micro: 0.298
Epoch: 400, Train Loss: 0.715, Val f1_micro: 0.301
Epoch: 420, Train Loss: 0.695, Val f1_micro: 0.298
Epoch: 440, Train Loss: 0.694, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.682, Val f1_micro: 0.303
Epoch: 480, Train Loss: 0.652, Val f1_micro: 0.300
Epoch: 500, Train Loss: 0.661, Val f1_micro: 0.293
f1-micro: 0.293, f1-macro: 0.289, f1-weighted: 0.294, , roc-auc: 0.671
##### RUN 4 #####
Epoch: 020, Train Loss: 1.800, Val f1_micro: 0.208
Epoch: 040, Train Loss: 1.569, Val f1_micro: 0.229
Epoch: 060, Train Loss: 1.427, Val f1_micro: 0.243
Epoch: 080, Train Loss: 1.314, Val f1_micro: 0.259
Epoch: 100, Train Loss: 1.221, Val f1_micro: 0.256
Epoch: 120, Train Loss: 1.165, Val f1_micro: 0.262
Epoch: 140, Train Loss: 1.116, Val f1_micro: 0.270
Epoch: 160, Train Loss: 1.071, Val f1_micro: 0.270
Epoch: 180, Train Loss: 1.024, Val f1_micro: 0.276
Epoch: 200, Train Loss: 0.981, Val f1_micro: 0.278
Epoch: 220, Train Loss: 0.933, Val f1_micro: 0.285
Epoch: 240, Train Loss: 0.910, Val f1_micro: 0.286
Epoch: 260, Train Loss: 0.893, Val f1_micro: 0.287
Epoch: 280, Train Loss: 0.845, Val f1_micro: 0.286
Epoch: 300, Train Loss: 0.819, Val f1_micro: 0.297
Epoch: 320, Train Loss: 0.803, Val f1_micro: 0.293
Epoch: 340, Train Loss: 0.780, Val f1_micro: 0.294
Epoch: 360, Train Loss: 0.748, Val f1_micro: 0.296
Epoch: 380, Train Loss: 0.766, Val f1_micro: 0.297
Epoch: 400, Train Loss: 0.726, Val f1_micro: 0.302
Epoch: 420, Train Loss: 0.725, Val f1_micro: 0.297
Epoch: 440, Train Loss: 0.704, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.709, Val f1_micro: 0.302
Epoch: 480, Train Loss: 0.658, Val f1_micro: 0.303
Epoch: 500, Train Loss: 0.666, Val f1_micro: 0.303
f1-micro: 0.303, f1-macro: 0.297, f1-weighted: 0.303, , roc-auc: 0.675
##### RUN 5 #####
Epoch: 020, Train Loss: 1.800, Val f1_micro: 0.204
Epoch: 040, Train Loss: 1.539, Val f1_micro: 0.235
Epoch: 060, Train Loss: 1.414, Val f1_micro: 0.255
Epoch: 080, Train Loss: 1.309, Val f1_micro: 0.256
Epoch: 100, Train Loss: 1.240, Val f1_micro: 0.262
Epoch: 120, Train Loss: 1.142, Val f1_micro: 0.263
Epoch: 140, Train Loss: 1.086, Val f1_micro: 0.268
Epoch: 160, Train Loss: 1.067, Val f1_micro: 0.271
Epoch: 180, Train Loss: 1.004, Val f1_micro: 0.271
Epoch: 200, Train Loss: 0.956, Val f1_micro: 0.277
Epoch: 220, Train Loss: 0.936, Val f1_micro: 0.279
Epoch: 240, Train Loss: 0.908, Val f1_micro: 0.285
Epoch: 260, Train Loss: 0.866, Val f1_micro: 0.286
Epoch: 280, Train Loss: 0.831, Val f1_micro: 0.285
Epoch: 300, Train Loss: 0.818, Val f1_micro: 0.293
Epoch: 320, Train Loss: 0.791, Val f1_micro: 0.293
Epoch: 340, Train Loss: 0.775, Val f1_micro: 0.295
Epoch: 360, Train Loss: 0.765, Val f1_micro: 0.293
Epoch: 380, Train Loss: 0.728, Val f1_micro: 0.298
Epoch: 400, Train Loss: 0.732, Val f1_micro: 0.299
Epoch: 420, Train Loss: 0.701, Val f1_micro: 0.300
Epoch: 440, Train Loss: 0.690, Val f1_micro: 0.301
Epoch: 460, Train Loss: 0.681, Val f1_micro: 0.301
Epoch: 480, Train Loss: 0.676, Val f1_micro: 0.295
Epoch: 500, Train Loss: 0.682, Val f1_micro: 0.303
f1-micro: 0.303, f1-macro: 0.297, f1-weighted: 0.302, , roc-auc: 0.677
########## Hyperparameters combination ##########
(1024, 0.6, 0.01, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.810, Val f1_micro: 0.208
Epoch: 040, Train Loss: 1.571, Val f1_micro: 0.233
Epoch: 060, Train Loss: 1.471, Val f1_micro: 0.252
Epoch: 080, Train Loss: 1.384, Val f1_micro: 0.255
Epoch: 100, Train Loss: 1.334, Val f1_micro: 0.257
Epoch: 120, Train Loss: 1.286, Val f1_micro: 0.259
Epoch: 140, Train Loss: 1.234, Val f1_micro: 0.257
Epoch: 160, Train Loss: 1.214, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.185, Val f1_micro: 0.265
Epoch: 200, Train Loss: 1.144, Val f1_micro: 0.268
Epoch: 220, Train Loss: 1.133, Val f1_micro: 0.270
Epoch: 240, Train Loss: 1.109, Val f1_micro: 0.271
Epoch: 260, Train Loss: 1.103, Val f1_micro: 0.269
Epoch: 280, Train Loss: 1.067, Val f1_micro: 0.278
Epoch: 300, Train Loss: 1.062, Val f1_micro: 0.276
Epoch: 320, Train Loss: 1.044, Val f1_micro: 0.281
Epoch: 340, Train Loss: 1.035, Val f1_micro: 0.283
Epoch: 360, Train Loss: 1.033, Val f1_micro: 0.277
Epoch: 380, Train Loss: 1.027, Val f1_micro: 0.283
Epoch: 400, Train Loss: 1.004, Val f1_micro: 0.282
Epoch: 420, Train Loss: 1.003, Val f1_micro: 0.286
Epoch: 440, Train Loss: 0.979, Val f1_micro: 0.284
Epoch: 460, Train Loss: 1.000, Val f1_micro: 0.281
Epoch: 480, Train Loss: 0.975, Val f1_micro: 0.287
Epoch: 500, Train Loss: 0.959, Val f1_micro: 0.286
f1-micro: 0.286, f1-macro: 0.276, f1-weighted: 0.280, , roc-auc: 0.667
##### RUN 2 #####
Epoch: 020, Train Loss: 1.831, Val f1_micro: 0.215
Epoch: 040, Train Loss: 1.580, Val f1_micro: 0.238
Epoch: 060, Train Loss: 1.484, Val f1_micro: 0.249
Epoch: 080, Train Loss: 1.403, Val f1_micro: 0.258
Epoch: 100, Train Loss: 1.335, Val f1_micro: 0.256
Epoch: 120, Train Loss: 1.293, Val f1_micro: 0.258
Epoch: 140, Train Loss: 1.253, Val f1_micro: 0.260
Epoch: 160, Train Loss: 1.206, Val f1_micro: 0.261
Epoch: 180, Train Loss: 1.187, Val f1_micro: 0.262
Epoch: 200, Train Loss: 1.182, Val f1_micro: 0.266
Epoch: 220, Train Loss: 1.138, Val f1_micro: 0.266
Epoch: 240, Train Loss: 1.112, Val f1_micro: 0.267
Epoch: 260, Train Loss: 1.093, Val f1_micro: 0.266
Epoch: 280, Train Loss: 1.083, Val f1_micro: 0.274
Epoch: 300, Train Loss: 1.051, Val f1_micro: 0.269
Epoch: 320, Train Loss: 1.074, Val f1_micro: 0.276
Epoch: 340, Train Loss: 1.040, Val f1_micro: 0.279
Epoch: 360, Train Loss: 1.015, Val f1_micro: 0.271
Epoch: 380, Train Loss: 1.021, Val f1_micro: 0.277
Epoch: 400, Train Loss: 1.000, Val f1_micro: 0.284
Epoch: 420, Train Loss: 1.009, Val f1_micro: 0.280
Epoch: 440, Train Loss: 0.991, Val f1_micro: 0.286
Epoch: 460, Train Loss: 0.962, Val f1_micro: 0.285
Epoch: 480, Train Loss: 0.965, Val f1_micro: 0.283
Epoch: 500, Train Loss: 0.981, Val f1_micro: 0.286
f1-micro: 0.286, f1-macro: 0.278, f1-weighted: 0.282, , roc-auc: 0.670
##### RUN 3 #####
Epoch: 020, Train Loss: 1.810, Val f1_micro: 0.211
Epoch: 040, Train Loss: 1.585, Val f1_micro: 0.237
Epoch: 060, Train Loss: 1.456, Val f1_micro: 0.250
Epoch: 080, Train Loss: 1.371, Val f1_micro: 0.254
Epoch: 100, Train Loss: 1.342, Val f1_micro: 0.254
Epoch: 120, Train Loss: 1.279, Val f1_micro: 0.265
Epoch: 140, Train Loss: 1.249, Val f1_micro: 0.261
Epoch: 160, Train Loss: 1.189, Val f1_micro: 0.261
Epoch: 180, Train Loss: 1.170, Val f1_micro: 0.263
Epoch: 200, Train Loss: 1.155, Val f1_micro: 0.265
Epoch: 220, Train Loss: 1.121, Val f1_micro: 0.270
Epoch: 240, Train Loss: 1.100, Val f1_micro: 0.268
Epoch: 260, Train Loss: 1.095, Val f1_micro: 0.271
Epoch: 280, Train Loss: 1.078, Val f1_micro: 0.274
Epoch: 300, Train Loss: 1.042, Val f1_micro: 0.274
Epoch: 320, Train Loss: 1.048, Val f1_micro: 0.277
Epoch: 340, Train Loss: 1.028, Val f1_micro: 0.275
Epoch: 360, Train Loss: 1.035, Val f1_micro: 0.285
Epoch: 380, Train Loss: 1.008, Val f1_micro: 0.279
Epoch: 400, Train Loss: 1.001, Val f1_micro: 0.284
Epoch: 420, Train Loss: 0.984, Val f1_micro: 0.280
Epoch: 440, Train Loss: 0.988, Val f1_micro: 0.287
Epoch: 460, Train Loss: 0.959, Val f1_micro: 0.288
Epoch: 480, Train Loss: 0.954, Val f1_micro: 0.288
Epoch: 500, Train Loss: 0.949, Val f1_micro: 0.285
f1-micro: 0.285, f1-macro: 0.278, f1-weighted: 0.282, , roc-auc: 0.668
##### RUN 4 #####
Epoch: 020, Train Loss: 1.802, Val f1_micro: 0.207
Epoch: 040, Train Loss: 1.540, Val f1_micro: 0.239
Epoch: 060, Train Loss: 1.475, Val f1_micro: 0.243
Epoch: 080, Train Loss: 1.377, Val f1_micro: 0.252
Epoch: 100, Train Loss: 1.348, Val f1_micro: 0.256
Epoch: 120, Train Loss: 1.279, Val f1_micro: 0.261
Epoch: 140, Train Loss: 1.246, Val f1_micro: 0.257
Epoch: 160, Train Loss: 1.203, Val f1_micro: 0.262
Epoch: 180, Train Loss: 1.172, Val f1_micro: 0.263
Epoch: 200, Train Loss: 1.162, Val f1_micro: 0.263
Epoch: 220, Train Loss: 1.119, Val f1_micro: 0.266
Epoch: 240, Train Loss: 1.105, Val f1_micro: 0.274
Epoch: 260, Train Loss: 1.099, Val f1_micro: 0.271
Epoch: 280, Train Loss: 1.092, Val f1_micro: 0.272
Epoch: 300, Train Loss: 1.058, Val f1_micro: 0.274
Epoch: 320, Train Loss: 1.051, Val f1_micro: 0.279
Epoch: 340, Train Loss: 1.047, Val f1_micro: 0.280
Epoch: 360, Train Loss: 1.009, Val f1_micro: 0.285
Epoch: 380, Train Loss: 1.018, Val f1_micro: 0.281
Epoch: 400, Train Loss: 0.996, Val f1_micro: 0.280
Epoch: 420, Train Loss: 0.993, Val f1_micro: 0.279
Epoch: 440, Train Loss: 0.985, Val f1_micro: 0.282
Epoch: 460, Train Loss: 0.968, Val f1_micro: 0.283
Epoch: 480, Train Loss: 0.972, Val f1_micro: 0.283
Epoch: 500, Train Loss: 0.959, Val f1_micro: 0.286
f1-micro: 0.286, f1-macro: 0.278, f1-weighted: 0.281, , roc-auc: 0.668
##### RUN 5 #####
Epoch: 020, Train Loss: 1.805, Val f1_micro: 0.211
Epoch: 040, Train Loss: 1.584, Val f1_micro: 0.238
Epoch: 060, Train Loss: 1.449, Val f1_micro: 0.252
Epoch: 080, Train Loss: 1.405, Val f1_micro: 0.254
Epoch: 100, Train Loss: 1.327, Val f1_micro: 0.254
Epoch: 120, Train Loss: 1.267, Val f1_micro: 0.258
Epoch: 140, Train Loss: 1.259, Val f1_micro: 0.259
Epoch: 160, Train Loss: 1.210, Val f1_micro: 0.264
Epoch: 180, Train Loss: 1.183, Val f1_micro: 0.265
Epoch: 200, Train Loss: 1.143, Val f1_micro: 0.265
Epoch: 220, Train Loss: 1.121, Val f1_micro: 0.268
Epoch: 240, Train Loss: 1.099, Val f1_micro: 0.269
Epoch: 260, Train Loss: 1.080, Val f1_micro: 0.275
Epoch: 280, Train Loss: 1.064, Val f1_micro: 0.276
Epoch: 300, Train Loss: 1.051, Val f1_micro: 0.271
Epoch: 320, Train Loss: 1.032, Val f1_micro: 0.287
Epoch: 340, Train Loss: 1.046, Val f1_micro: 0.287
Epoch: 360, Train Loss: 1.037, Val f1_micro: 0.285
Epoch: 380, Train Loss: 0.993, Val f1_micro: 0.283
Epoch: 400, Train Loss: 1.013, Val f1_micro: 0.285
Epoch: 420, Train Loss: 0.989, Val f1_micro: 0.287
Epoch: 440, Train Loss: 0.999, Val f1_micro: 0.280
Epoch: 460, Train Loss: 0.983, Val f1_micro: 0.286
Epoch: 480, Train Loss: 0.955, Val f1_micro: 0.291
Epoch: 500, Train Loss: 0.957, Val f1_micro: 0.287
f1-micro: 0.287, f1-macro: 0.279, f1-weighted: 0.283, , roc-auc: 0.669
########## Hyperparameters combination ##########
(1024, 0.6, 0.01, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.852, Val f1_micro: 0.197
Epoch: 040, Train Loss: 1.723, Val f1_micro: 0.210
Epoch: 060, Train Loss: 1.723, Val f1_micro: 0.214
Epoch: 080, Train Loss: 1.710, Val f1_micro: 0.220
Epoch: 100, Train Loss: 1.706, Val f1_micro: 0.215
Epoch: 120, Train Loss: 1.719, Val f1_micro: 0.217
Epoch: 140, Train Loss: 1.704, Val f1_micro: 0.218
Epoch: 160, Train Loss: 1.734, Val f1_micro: 0.214
Epoch: 180, Train Loss: 1.722, Val f1_micro: 0.216
Epoch: 200, Train Loss: 1.727, Val f1_micro: 0.217
Epoch: 220, Train Loss: 1.726, Val f1_micro: 0.210
Epoch: 240, Train Loss: 1.728, Val f1_micro: 0.209
Epoch: 260, Train Loss: 1.727, Val f1_micro: 0.213
Epoch: 280, Train Loss: 1.722, Val f1_micro: 0.213
Epoch: 300, Train Loss: 1.715, Val f1_micro: 0.217
Epoch: 320, Train Loss: 1.725, Val f1_micro: 0.209
Epoch: 340, Train Loss: 1.722, Val f1_micro: 0.215
Epoch: 360, Train Loss: 1.719, Val f1_micro: 0.218
Epoch: 380, Train Loss: 1.719, Val f1_micro: 0.216
Epoch: 400, Train Loss: 1.740, Val f1_micro: 0.206
Epoch: 420, Train Loss: 1.732, Val f1_micro: 0.207
Epoch: 440, Train Loss: 1.718, Val f1_micro: 0.218
Epoch: 460, Train Loss: 1.718, Val f1_micro: 0.207
Epoch: 480, Train Loss: 1.708, Val f1_micro: 0.214
Epoch: 500, Train Loss: 1.715, Val f1_micro: 0.211
f1-micro: 0.211, f1-macro: 0.186, f1-weighted: 0.183, , roc-auc: 0.643
##### RUN 2 #####
Epoch: 020, Train Loss: 1.823, Val f1_micro: 0.200
Epoch: 040, Train Loss: 1.731, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.694, Val f1_micro: 0.218
Epoch: 080, Train Loss: 1.700, Val f1_micro: 0.214
Epoch: 100, Train Loss: 1.700, Val f1_micro: 0.217
Epoch: 120, Train Loss: 1.709, Val f1_micro: 0.220
Epoch: 140, Train Loss: 1.727, Val f1_micro: 0.214
Epoch: 160, Train Loss: 1.717, Val f1_micro: 0.216
Epoch: 180, Train Loss: 1.717, Val f1_micro: 0.210
Epoch: 200, Train Loss: 1.721, Val f1_micro: 0.216
Epoch: 220, Train Loss: 1.717, Val f1_micro: 0.217
Epoch: 240, Train Loss: 1.715, Val f1_micro: 0.213
Epoch: 260, Train Loss: 1.731, Val f1_micro: 0.211
Epoch: 280, Train Loss: 1.731, Val f1_micro: 0.214
Epoch: 300, Train Loss: 1.719, Val f1_micro: 0.213
Epoch: 320, Train Loss: 1.728, Val f1_micro: 0.215
Epoch: 340, Train Loss: 1.724, Val f1_micro: 0.213
Epoch: 360, Train Loss: 1.710, Val f1_micro: 0.217
Epoch: 380, Train Loss: 1.706, Val f1_micro: 0.212
Epoch: 400, Train Loss: 1.709, Val f1_micro: 0.212
Epoch: 420, Train Loss: 1.709, Val f1_micro: 0.214
Epoch: 440, Train Loss: 1.710, Val f1_micro: 0.214
Epoch: 460, Train Loss: 1.714, Val f1_micro: 0.215
Epoch: 480, Train Loss: 1.717, Val f1_micro: 0.211
Epoch: 500, Train Loss: 1.720, Val f1_micro: 0.212
f1-micro: 0.212, f1-macro: 0.182, f1-weighted: 0.177, , roc-auc: 0.639
##### RUN 3 #####
Epoch: 020, Train Loss: 1.854, Val f1_micro: 0.208
Epoch: 040, Train Loss: 1.746, Val f1_micro: 0.218
Epoch: 060, Train Loss: 1.704, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.703, Val f1_micro: 0.215
Epoch: 100, Train Loss: 1.712, Val f1_micro: 0.217
Epoch: 120, Train Loss: 1.713, Val f1_micro: 0.214
Epoch: 140, Train Loss: 1.711, Val f1_micro: 0.220
Epoch: 160, Train Loss: 1.723, Val f1_micro: 0.224
Epoch: 180, Train Loss: 1.715, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.727, Val f1_micro: 0.216
Epoch: 220, Train Loss: 1.715, Val f1_micro: 0.213
Epoch: 240, Train Loss: 1.721, Val f1_micro: 0.218
Epoch: 260, Train Loss: 1.720, Val f1_micro: 0.216
Epoch: 280, Train Loss: 1.730, Val f1_micro: 0.221
Epoch: 300, Train Loss: 1.729, Val f1_micro: 0.214
Epoch: 320, Train Loss: 1.713, Val f1_micro: 0.216
Epoch: 340, Train Loss: 1.720, Val f1_micro: 0.216
Epoch: 360, Train Loss: 1.730, Val f1_micro: 0.209
Epoch: 380, Train Loss: 1.710, Val f1_micro: 0.210
Epoch: 400, Train Loss: 1.724, Val f1_micro: 0.213
Epoch: 420, Train Loss: 1.698, Val f1_micro: 0.214
Epoch: 440, Train Loss: 1.722, Val f1_micro: 0.209
Epoch: 460, Train Loss: 1.718, Val f1_micro: 0.208
Epoch: 480, Train Loss: 1.719, Val f1_micro: 0.216
Epoch: 500, Train Loss: 1.711, Val f1_micro: 0.210
f1-micro: 0.210, f1-macro: 0.170, f1-weighted: 0.167, , roc-auc: 0.639
##### RUN 4 #####
Epoch: 020, Train Loss: 1.845, Val f1_micro: 0.203
Epoch: 040, Train Loss: 1.725, Val f1_micro: 0.218
Epoch: 060, Train Loss: 1.702, Val f1_micro: 0.217
Epoch: 080, Train Loss: 1.700, Val f1_micro: 0.221
Epoch: 100, Train Loss: 1.703, Val f1_micro: 0.224
Epoch: 120, Train Loss: 1.703, Val f1_micro: 0.218
Epoch: 140, Train Loss: 1.721, Val f1_micro: 0.221
Epoch: 160, Train Loss: 1.725, Val f1_micro: 0.222
Epoch: 180, Train Loss: 1.730, Val f1_micro: 0.215
Epoch: 200, Train Loss: 1.718, Val f1_micro: 0.216
Epoch: 220, Train Loss: 1.731, Val f1_micro: 0.217
Epoch: 240, Train Loss: 1.714, Val f1_micro: 0.220
Epoch: 260, Train Loss: 1.721, Val f1_micro: 0.218
Epoch: 280, Train Loss: 1.732, Val f1_micro: 0.217
Epoch: 300, Train Loss: 1.733, Val f1_micro: 0.219
Epoch: 320, Train Loss: 1.723, Val f1_micro: 0.207
Epoch: 340, Train Loss: 1.715, Val f1_micro: 0.214
Epoch: 360, Train Loss: 1.732, Val f1_micro: 0.216
Epoch: 380, Train Loss: 1.722, Val f1_micro: 0.214
Epoch: 400, Train Loss: 1.727, Val f1_micro: 0.213
Epoch: 420, Train Loss: 1.727, Val f1_micro: 0.214
Epoch: 440, Train Loss: 1.730, Val f1_micro: 0.216
Epoch: 460, Train Loss: 1.713, Val f1_micro: 0.211
Epoch: 480, Train Loss: 1.724, Val f1_micro: 0.213
Epoch: 500, Train Loss: 1.713, Val f1_micro: 0.209
f1-micro: 0.209, f1-macro: 0.166, f1-weighted: 0.162, , roc-auc: 0.640
##### RUN 5 #####
Epoch: 020, Train Loss: 1.829, Val f1_micro: 0.204
Epoch: 040, Train Loss: 1.741, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.710, Val f1_micro: 0.211
Epoch: 080, Train Loss: 1.695, Val f1_micro: 0.222
Epoch: 100, Train Loss: 1.705, Val f1_micro: 0.223
Epoch: 120, Train Loss: 1.708, Val f1_micro: 0.218
Epoch: 140, Train Loss: 1.721, Val f1_micro: 0.216
Epoch: 160, Train Loss: 1.709, Val f1_micro: 0.221
Epoch: 180, Train Loss: 1.721, Val f1_micro: 0.211
Epoch: 200, Train Loss: 1.725, Val f1_micro: 0.207
Epoch: 220, Train Loss: 1.715, Val f1_micro: 0.210
Epoch: 240, Train Loss: 1.726, Val f1_micro: 0.212
Epoch: 260, Train Loss: 1.730, Val f1_micro: 0.211
Epoch: 280, Train Loss: 1.714, Val f1_micro: 0.210
Epoch: 300, Train Loss: 1.723, Val f1_micro: 0.216
Epoch: 320, Train Loss: 1.726, Val f1_micro: 0.216
Epoch: 340, Train Loss: 1.712, Val f1_micro: 0.217
Epoch: 360, Train Loss: 1.731, Val f1_micro: 0.212
Epoch: 380, Train Loss: 1.727, Val f1_micro: 0.215
Epoch: 400, Train Loss: 1.723, Val f1_micro: 0.212
Epoch: 420, Train Loss: 1.710, Val f1_micro: 0.218
Epoch: 440, Train Loss: 1.712, Val f1_micro: 0.217
Epoch: 460, Train Loss: 1.717, Val f1_micro: 0.219
Epoch: 480, Train Loss: 1.712, Val f1_micro: 0.212
Epoch: 500, Train Loss: 1.712, Val f1_micro: 0.215
f1-micro: 0.215, f1-macro: 0.184, f1-weighted: 0.181, , roc-auc: 0.639
########## Hyperparameters combination ##########
(1024, 0.6, 0.05, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.050, Val f1_micro: 0.142
Epoch: 040, Train Loss: 1.979, Val f1_micro: 0.163
Epoch: 060, Train Loss: 1.904, Val f1_micro: 0.123
Epoch: 080, Train Loss: 1.841, Val f1_micro: 0.129
Epoch: 100, Train Loss: 1.770, Val f1_micro: 0.140
Epoch: 120, Train Loss: 1.704, Val f1_micro: 0.155
Epoch: 140, Train Loss: 1.625, Val f1_micro: 0.176
Epoch: 160, Train Loss: 1.538, Val f1_micro: 0.190
Epoch: 180, Train Loss: 1.486, Val f1_micro: 0.191
Epoch: 200, Train Loss: 1.446, Val f1_micro: 0.193
Epoch: 220, Train Loss: 1.400, Val f1_micro: 0.200
Epoch: 240, Train Loss: 1.306, Val f1_micro: 0.208
Epoch: 260, Train Loss: 1.270, Val f1_micro: 0.213
Epoch: 280, Train Loss: 1.215, Val f1_micro: 0.216
Epoch: 300, Train Loss: 1.169, Val f1_micro: 0.221
Epoch: 320, Train Loss: 1.119, Val f1_micro: 0.232
Epoch: 340, Train Loss: 1.035, Val f1_micro: 0.233
Epoch: 360, Train Loss: 1.051, Val f1_micro: 0.240
Epoch: 380, Train Loss: 1.003, Val f1_micro: 0.240
Epoch: 400, Train Loss: 0.951, Val f1_micro: 0.248
Epoch: 420, Train Loss: 0.942, Val f1_micro: 0.253
Epoch: 440, Train Loss: 0.924, Val f1_micro: 0.252
Epoch: 460, Train Loss: 0.896, Val f1_micro: 0.247
Epoch: 480, Train Loss: 0.869, Val f1_micro: 0.257
Epoch: 500, Train Loss: 0.848, Val f1_micro: 0.256
f1-micro: 0.256, f1-macro: 0.250, f1-weighted: 0.252, , roc-auc: 0.641
##### RUN 2 #####
Epoch: 020, Train Loss: 2.067, Val f1_micro: 0.096
Epoch: 040, Train Loss: 1.986, Val f1_micro: 0.150
Epoch: 060, Train Loss: 1.925, Val f1_micro: 0.117
Epoch: 080, Train Loss: 1.844, Val f1_micro: 0.149
Epoch: 100, Train Loss: 1.771, Val f1_micro: 0.160
Epoch: 120, Train Loss: 1.697, Val f1_micro: 0.164
Epoch: 140, Train Loss: 1.641, Val f1_micro: 0.172
Epoch: 160, Train Loss: 1.561, Val f1_micro: 0.181
Epoch: 180, Train Loss: 1.504, Val f1_micro: 0.190
Epoch: 200, Train Loss: 1.442, Val f1_micro: 0.192
Epoch: 220, Train Loss: 1.357, Val f1_micro: 0.203
Epoch: 240, Train Loss: 1.340, Val f1_micro: 0.212
Epoch: 260, Train Loss: 1.258, Val f1_micro: 0.220
Epoch: 280, Train Loss: 1.228, Val f1_micro: 0.218
Epoch: 300, Train Loss: 1.202, Val f1_micro: 0.227
Epoch: 320, Train Loss: 1.170, Val f1_micro: 0.232
Epoch: 340, Train Loss: 1.108, Val f1_micro: 0.231
Epoch: 360, Train Loss: 1.100, Val f1_micro: 0.232
Epoch: 380, Train Loss: 1.078, Val f1_micro: 0.239
Epoch: 400, Train Loss: 1.049, Val f1_micro: 0.242
Epoch: 420, Train Loss: 1.005, Val f1_micro: 0.248
Epoch: 440, Train Loss: 0.983, Val f1_micro: 0.246
Epoch: 460, Train Loss: 0.935, Val f1_micro: 0.245
Epoch: 480, Train Loss: 0.927, Val f1_micro: 0.254
Epoch: 500, Train Loss: 0.854, Val f1_micro: 0.256
f1-micro: 0.256, f1-macro: 0.252, f1-weighted: 0.253, , roc-auc: 0.641
##### RUN 3 #####
Epoch: 020, Train Loss: 2.053, Val f1_micro: 0.097
Epoch: 040, Train Loss: 1.973, Val f1_micro: 0.162
Epoch: 060, Train Loss: 1.921, Val f1_micro: 0.119
Epoch: 080, Train Loss: 1.849, Val f1_micro: 0.125
Epoch: 100, Train Loss: 1.765, Val f1_micro: 0.134
Epoch: 120, Train Loss: 1.716, Val f1_micro: 0.152
Epoch: 140, Train Loss: 1.610, Val f1_micro: 0.173
Epoch: 160, Train Loss: 1.543, Val f1_micro: 0.183
Epoch: 180, Train Loss: 1.456, Val f1_micro: 0.194
Epoch: 200, Train Loss: 1.363, Val f1_micro: 0.199
Epoch: 220, Train Loss: 1.335, Val f1_micro: 0.210
Epoch: 240, Train Loss: 1.247, Val f1_micro: 0.211
Epoch: 260, Train Loss: 1.192, Val f1_micro: 0.224
Epoch: 280, Train Loss: 1.118, Val f1_micro: 0.228
Epoch: 300, Train Loss: 1.098, Val f1_micro: 0.229
Epoch: 320, Train Loss: 1.018, Val f1_micro: 0.240
Epoch: 340, Train Loss: 1.034, Val f1_micro: 0.231
Epoch: 360, Train Loss: 0.972, Val f1_micro: 0.238
Epoch: 380, Train Loss: 0.943, Val f1_micro: 0.249
Epoch: 400, Train Loss: 0.883, Val f1_micro: 0.245
Epoch: 420, Train Loss: 0.844, Val f1_micro: 0.255
Epoch: 440, Train Loss: 0.856, Val f1_micro: 0.255
Epoch: 460, Train Loss: 0.839, Val f1_micro: 0.253
Epoch: 480, Train Loss: 0.779, Val f1_micro: 0.259
Epoch: 500, Train Loss: 0.785, Val f1_micro: 0.258
f1-micro: 0.258, f1-macro: 0.252, f1-weighted: 0.254, , roc-auc: 0.645
##### RUN 4 #####
Epoch: 020, Train Loss: 2.039, Val f1_micro: 0.097
Epoch: 040, Train Loss: 1.961, Val f1_micro: 0.165
Epoch: 060, Train Loss: 1.895, Val f1_micro: 0.121
Epoch: 080, Train Loss: 1.853, Val f1_micro: 0.130
Epoch: 100, Train Loss: 1.785, Val f1_micro: 0.134
Epoch: 120, Train Loss: 1.716, Val f1_micro: 0.148
Epoch: 140, Train Loss: 1.644, Val f1_micro: 0.180
Epoch: 160, Train Loss: 1.588, Val f1_micro: 0.196
Epoch: 180, Train Loss: 1.480, Val f1_micro: 0.201
Epoch: 200, Train Loss: 1.410, Val f1_micro: 0.205
Epoch: 220, Train Loss: 1.373, Val f1_micro: 0.206
Epoch: 240, Train Loss: 1.297, Val f1_micro: 0.215
Epoch: 260, Train Loss: 1.288, Val f1_micro: 0.215
Epoch: 280, Train Loss: 1.238, Val f1_micro: 0.223
Epoch: 300, Train Loss: 1.156, Val f1_micro: 0.229
Epoch: 320, Train Loss: 1.147, Val f1_micro: 0.236
Epoch: 340, Train Loss: 1.108, Val f1_micro: 0.239
Epoch: 360, Train Loss: 1.033, Val f1_micro: 0.239
Epoch: 380, Train Loss: 0.990, Val f1_micro: 0.247
Epoch: 400, Train Loss: 0.993, Val f1_micro: 0.252
Epoch: 420, Train Loss: 0.981, Val f1_micro: 0.250
Epoch: 440, Train Loss: 0.889, Val f1_micro: 0.255
Epoch: 460, Train Loss: 0.935, Val f1_micro: 0.256
Epoch: 480, Train Loss: 0.872, Val f1_micro: 0.258
Epoch: 500, Train Loss: 0.887, Val f1_micro: 0.258
f1-micro: 0.258, f1-macro: 0.250, f1-weighted: 0.253, , roc-auc: 0.637
##### RUN 5 #####
Epoch: 020, Train Loss: 2.062, Val f1_micro: 0.139
Epoch: 040, Train Loss: 1.970, Val f1_micro: 0.161
Epoch: 060, Train Loss: 1.899, Val f1_micro: 0.117
Epoch: 080, Train Loss: 1.842, Val f1_micro: 0.131
Epoch: 100, Train Loss: 1.744, Val f1_micro: 0.165
Epoch: 120, Train Loss: 1.670, Val f1_micro: 0.168
Epoch: 140, Train Loss: 1.605, Val f1_micro: 0.187
Epoch: 160, Train Loss: 1.527, Val f1_micro: 0.182
Epoch: 180, Train Loss: 1.458, Val f1_micro: 0.195
Epoch: 200, Train Loss: 1.370, Val f1_micro: 0.195
Epoch: 220, Train Loss: 1.322, Val f1_micro: 0.204
Epoch: 240, Train Loss: 1.253, Val f1_micro: 0.211
Epoch: 260, Train Loss: 1.210, Val f1_micro: 0.218
Epoch: 280, Train Loss: 1.156, Val f1_micro: 0.213
Epoch: 300, Train Loss: 1.096, Val f1_micro: 0.232
Epoch: 320, Train Loss: 1.033, Val f1_micro: 0.226
Epoch: 340, Train Loss: 1.016, Val f1_micro: 0.239
Epoch: 360, Train Loss: 0.973, Val f1_micro: 0.243
Epoch: 380, Train Loss: 0.936, Val f1_micro: 0.243
Epoch: 400, Train Loss: 0.901, Val f1_micro: 0.248
Epoch: 420, Train Loss: 0.871, Val f1_micro: 0.245
Epoch: 440, Train Loss: 0.852, Val f1_micro: 0.255
Epoch: 460, Train Loss: 0.814, Val f1_micro: 0.257
Epoch: 480, Train Loss: 0.797, Val f1_micro: 0.259
Epoch: 500, Train Loss: 0.790, Val f1_micro: 0.257
f1-micro: 0.257, f1-macro: 0.250, f1-weighted: 0.252, , roc-auc: 0.640
########## Hyperparameters combination ##########
(1024, 0.6, 0.05, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.078, Val f1_micro: 0.098
Epoch: 040, Train Loss: 1.998, Val f1_micro: 0.168
Epoch: 060, Train Loss: 1.956, Val f1_micro: 0.121
Epoch: 080, Train Loss: 1.909, Val f1_micro: 0.124
Epoch: 100, Train Loss: 1.834, Val f1_micro: 0.179
Epoch: 120, Train Loss: 1.760, Val f1_micro: 0.183
Epoch: 140, Train Loss: 1.704, Val f1_micro: 0.188
Epoch: 160, Train Loss: 1.683, Val f1_micro: 0.190
Epoch: 180, Train Loss: 1.629, Val f1_micro: 0.192
Epoch: 200, Train Loss: 1.572, Val f1_micro: 0.203
Epoch: 220, Train Loss: 1.516, Val f1_micro: 0.195
Epoch: 240, Train Loss: 1.512, Val f1_micro: 0.213
Epoch: 260, Train Loss: 1.446, Val f1_micro: 0.219
Epoch: 280, Train Loss: 1.437, Val f1_micro: 0.219
Epoch: 300, Train Loss: 1.388, Val f1_micro: 0.224
Epoch: 320, Train Loss: 1.365, Val f1_micro: 0.235
Epoch: 340, Train Loss: 1.354, Val f1_micro: 0.233
Epoch: 360, Train Loss: 1.287, Val f1_micro: 0.233
Epoch: 380, Train Loss: 1.335, Val f1_micro: 0.223
Epoch: 400, Train Loss: 1.289, Val f1_micro: 0.243
Epoch: 420, Train Loss: 1.220, Val f1_micro: 0.244
Epoch: 440, Train Loss: 1.228, Val f1_micro: 0.240
Epoch: 460, Train Loss: 1.191, Val f1_micro: 0.248
Epoch: 480, Train Loss: 1.180, Val f1_micro: 0.252
Epoch: 500, Train Loss: 1.165, Val f1_micro: 0.250
f1-micro: 0.250, f1-macro: 0.241, f1-weighted: 0.241, , roc-auc: 0.644
##### RUN 2 #####
Epoch: 020, Train Loss: 2.078, Val f1_micro: 0.096
Epoch: 040, Train Loss: 1.995, Val f1_micro: 0.162
Epoch: 060, Train Loss: 1.949, Val f1_micro: 0.119
Epoch: 080, Train Loss: 1.929, Val f1_micro: 0.127
Epoch: 100, Train Loss: 1.845, Val f1_micro: 0.152
Epoch: 120, Train Loss: 1.775, Val f1_micro: 0.183
Epoch: 140, Train Loss: 1.722, Val f1_micro: 0.182
Epoch: 160, Train Loss: 1.654, Val f1_micro: 0.188
Epoch: 180, Train Loss: 1.582, Val f1_micro: 0.196
Epoch: 200, Train Loss: 1.575, Val f1_micro: 0.203
Epoch: 220, Train Loss: 1.526, Val f1_micro: 0.216
Epoch: 240, Train Loss: 1.458, Val f1_micro: 0.204
Epoch: 260, Train Loss: 1.418, Val f1_micro: 0.220
Epoch: 280, Train Loss: 1.387, Val f1_micro: 0.207
Epoch: 300, Train Loss: 1.371, Val f1_micro: 0.229
Epoch: 320, Train Loss: 1.363, Val f1_micro: 0.215
Epoch: 340, Train Loss: 1.307, Val f1_micro: 0.225
Epoch: 360, Train Loss: 1.301, Val f1_micro: 0.223
Epoch: 380, Train Loss: 1.277, Val f1_micro: 0.236
Epoch: 400, Train Loss: 1.222, Val f1_micro: 0.238
Epoch: 420, Train Loss: 1.210, Val f1_micro: 0.242
Epoch: 440, Train Loss: 1.200, Val f1_micro: 0.241
Epoch: 460, Train Loss: 1.185, Val f1_micro: 0.252
Epoch: 480, Train Loss: 1.140, Val f1_micro: 0.259
Epoch: 500, Train Loss: 1.128, Val f1_micro: 0.256
f1-micro: 0.256, f1-macro: 0.246, f1-weighted: 0.248, , roc-auc: 0.649
##### RUN 3 #####
Epoch: 020, Train Loss: 2.059, Val f1_micro: 0.142
Epoch: 040, Train Loss: 1.993, Val f1_micro: 0.165
Epoch: 060, Train Loss: 1.942, Val f1_micro: 0.121
Epoch: 080, Train Loss: 1.904, Val f1_micro: 0.123
Epoch: 100, Train Loss: 1.848, Val f1_micro: 0.172
Epoch: 120, Train Loss: 1.784, Val f1_micro: 0.170
Epoch: 140, Train Loss: 1.708, Val f1_micro: 0.192
Epoch: 160, Train Loss: 1.683, Val f1_micro: 0.196
Epoch: 180, Train Loss: 1.631, Val f1_micro: 0.198
Epoch: 200, Train Loss: 1.557, Val f1_micro: 0.210
Epoch: 220, Train Loss: 1.504, Val f1_micro: 0.218
Epoch: 240, Train Loss: 1.445, Val f1_micro: 0.228
Epoch: 260, Train Loss: 1.413, Val f1_micro: 0.227
Epoch: 280, Train Loss: 1.405, Val f1_micro: 0.233
Epoch: 300, Train Loss: 1.355, Val f1_micro: 0.224
Epoch: 320, Train Loss: 1.344, Val f1_micro: 0.238
Epoch: 340, Train Loss: 1.292, Val f1_micro: 0.238
Epoch: 360, Train Loss: 1.330, Val f1_micro: 0.248
Epoch: 380, Train Loss: 1.276, Val f1_micro: 0.250
Epoch: 400, Train Loss: 1.241, Val f1_micro: 0.243
Epoch: 420, Train Loss: 1.231, Val f1_micro: 0.240
Epoch: 440, Train Loss: 1.196, Val f1_micro: 0.248
Epoch: 460, Train Loss: 1.182, Val f1_micro: 0.257
Epoch: 480, Train Loss: 1.160, Val f1_micro: 0.251
Epoch: 500, Train Loss: 1.169, Val f1_micro: 0.251
f1-micro: 0.251, f1-macro: 0.242, f1-weighted: 0.243, , roc-auc: 0.649
##### RUN 4 #####
Epoch: 020, Train Loss: 2.064, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.022, Val f1_micro: 0.163
Epoch: 060, Train Loss: 1.978, Val f1_micro: 0.116
Epoch: 080, Train Loss: 1.932, Val f1_micro: 0.122
Epoch: 100, Train Loss: 1.868, Val f1_micro: 0.161
Epoch: 120, Train Loss: 1.791, Val f1_micro: 0.179
Epoch: 140, Train Loss: 1.728, Val f1_micro: 0.184
Epoch: 160, Train Loss: 1.685, Val f1_micro: 0.188
Epoch: 180, Train Loss: 1.630, Val f1_micro: 0.196
Epoch: 200, Train Loss: 1.586, Val f1_micro: 0.205
Epoch: 220, Train Loss: 1.569, Val f1_micro: 0.207
Epoch: 240, Train Loss: 1.539, Val f1_micro: 0.211
Epoch: 260, Train Loss: 1.500, Val f1_micro: 0.212
Epoch: 280, Train Loss: 1.468, Val f1_micro: 0.219
Epoch: 300, Train Loss: 1.427, Val f1_micro: 0.222
Epoch: 320, Train Loss: 1.430, Val f1_micro: 0.216
Epoch: 340, Train Loss: 1.376, Val f1_micro: 0.222
Epoch: 360, Train Loss: 1.351, Val f1_micro: 0.238
Epoch: 380, Train Loss: 1.336, Val f1_micro: 0.238
Epoch: 400, Train Loss: 1.280, Val f1_micro: 0.249
Epoch: 420, Train Loss: 1.289, Val f1_micro: 0.240
Epoch: 440, Train Loss: 1.254, Val f1_micro: 0.245
Epoch: 460, Train Loss: 1.229, Val f1_micro: 0.245
Epoch: 480, Train Loss: 1.178, Val f1_micro: 0.250
Epoch: 500, Train Loss: 1.201, Val f1_micro: 0.258
f1-micro: 0.258, f1-macro: 0.244, f1-weighted: 0.246, , roc-auc: 0.649
##### RUN 5 #####
Epoch: 020, Train Loss: 2.057, Val f1_micro: 0.099
Epoch: 040, Train Loss: 1.994, Val f1_micro: 0.161
Epoch: 060, Train Loss: 1.949, Val f1_micro: 0.116
Epoch: 080, Train Loss: 1.899, Val f1_micro: 0.138
Epoch: 100, Train Loss: 1.838, Val f1_micro: 0.177
Epoch: 120, Train Loss: 1.790, Val f1_micro: 0.179
Epoch: 140, Train Loss: 1.730, Val f1_micro: 0.171
Epoch: 160, Train Loss: 1.684, Val f1_micro: 0.188
Epoch: 180, Train Loss: 1.632, Val f1_micro: 0.194
Epoch: 200, Train Loss: 1.594, Val f1_micro: 0.202
Epoch: 220, Train Loss: 1.562, Val f1_micro: 0.207
Epoch: 240, Train Loss: 1.505, Val f1_micro: 0.211
Epoch: 260, Train Loss: 1.479, Val f1_micro: 0.220
Epoch: 280, Train Loss: 1.415, Val f1_micro: 0.226
Epoch: 300, Train Loss: 1.393, Val f1_micro: 0.225
Epoch: 320, Train Loss: 1.393, Val f1_micro: 0.229
Epoch: 340, Train Loss: 1.346, Val f1_micro: 0.230
Epoch: 360, Train Loss: 1.282, Val f1_micro: 0.234
Epoch: 380, Train Loss: 1.270, Val f1_micro: 0.237
Epoch: 400, Train Loss: 1.280, Val f1_micro: 0.237
Epoch: 420, Train Loss: 1.226, Val f1_micro: 0.246
Epoch: 440, Train Loss: 1.268, Val f1_micro: 0.243
Epoch: 460, Train Loss: 1.174, Val f1_micro: 0.244
Epoch: 480, Train Loss: 1.169, Val f1_micro: 0.244
Epoch: 500, Train Loss: 1.180, Val f1_micro: 0.257
f1-micro: 0.257, f1-macro: 0.247, f1-weighted: 0.249, , roc-auc: 0.650
########## Hyperparameters combination ##########
(1024, 0.6, 0.05, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.084, Val f1_micro: 0.097
Epoch: 040, Train Loss: 2.011, Val f1_micro: 0.165
Epoch: 060, Train Loss: 1.987, Val f1_micro: 0.115
Epoch: 080, Train Loss: 1.935, Val f1_micro: 0.154
Epoch: 100, Train Loss: 1.901, Val f1_micro: 0.159
Epoch: 120, Train Loss: 1.856, Val f1_micro: 0.174
Epoch: 140, Train Loss: 1.827, Val f1_micro: 0.182
Epoch: 160, Train Loss: 1.807, Val f1_micro: 0.179
Epoch: 180, Train Loss: 1.786, Val f1_micro: 0.178
Epoch: 200, Train Loss: 1.755, Val f1_micro: 0.175
Epoch: 220, Train Loss: 1.727, Val f1_micro: 0.186
Epoch: 240, Train Loss: 1.707, Val f1_micro: 0.199
Epoch: 260, Train Loss: 1.666, Val f1_micro: 0.190
Epoch: 280, Train Loss: 1.640, Val f1_micro: 0.209
Epoch: 300, Train Loss: 1.616, Val f1_micro: 0.205
Epoch: 320, Train Loss: 1.578, Val f1_micro: 0.207
Epoch: 340, Train Loss: 1.564, Val f1_micro: 0.213
Epoch: 360, Train Loss: 1.570, Val f1_micro: 0.213
Epoch: 380, Train Loss: 1.560, Val f1_micro: 0.208
Epoch: 400, Train Loss: 1.540, Val f1_micro: 0.212
Epoch: 420, Train Loss: 1.529, Val f1_micro: 0.214
Epoch: 440, Train Loss: 1.516, Val f1_micro: 0.226
Epoch: 460, Train Loss: 1.471, Val f1_micro: 0.221
Epoch: 480, Train Loss: 1.486, Val f1_micro: 0.215
Epoch: 500, Train Loss: 1.460, Val f1_micro: 0.218
f1-micro: 0.218, f1-macro: 0.201, f1-weighted: 0.197, , roc-auc: 0.646
##### RUN 2 #####
Epoch: 020, Train Loss: 2.078, Val f1_micro: 0.097
Epoch: 040, Train Loss: 2.022, Val f1_micro: 0.166
Epoch: 060, Train Loss: 1.995, Val f1_micro: 0.117
Epoch: 080, Train Loss: 1.964, Val f1_micro: 0.121
Epoch: 100, Train Loss: 1.928, Val f1_micro: 0.160
Epoch: 120, Train Loss: 1.878, Val f1_micro: 0.185
Epoch: 140, Train Loss: 1.850, Val f1_micro: 0.173
Epoch: 160, Train Loss: 1.814, Val f1_micro: 0.168
Epoch: 180, Train Loss: 1.768, Val f1_micro: 0.180
Epoch: 200, Train Loss: 1.729, Val f1_micro: 0.184
Epoch: 220, Train Loss: 1.693, Val f1_micro: 0.198
Epoch: 240, Train Loss: 1.685, Val f1_micro: 0.183
Epoch: 260, Train Loss: 1.617, Val f1_micro: 0.204
Epoch: 280, Train Loss: 1.596, Val f1_micro: 0.203
Epoch: 300, Train Loss: 1.627, Val f1_micro: 0.205
Epoch: 320, Train Loss: 1.569, Val f1_micro: 0.215
Epoch: 340, Train Loss: 1.552, Val f1_micro: 0.214
Epoch: 360, Train Loss: 1.506, Val f1_micro: 0.215
Epoch: 380, Train Loss: 1.466, Val f1_micro: 0.217
Epoch: 400, Train Loss: 1.467, Val f1_micro: 0.234
Epoch: 420, Train Loss: 1.466, Val f1_micro: 0.221
Epoch: 440, Train Loss: 1.439, Val f1_micro: 0.227
Epoch: 460, Train Loss: 1.460, Val f1_micro: 0.234
Epoch: 480, Train Loss: 1.425, Val f1_micro: 0.225
Epoch: 500, Train Loss: 1.413, Val f1_micro: 0.239
f1-micro: 0.239, f1-macro: 0.221, f1-weighted: 0.224, , roc-auc: 0.647
##### RUN 3 #####
Epoch: 020, Train Loss: 2.067, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.005, Val f1_micro: 0.118
Epoch: 060, Train Loss: 1.972, Val f1_micro: 0.116
Epoch: 080, Train Loss: 1.944, Val f1_micro: 0.121
Epoch: 100, Train Loss: 1.833, Val f1_micro: 0.165
Epoch: 120, Train Loss: 1.784, Val f1_micro: 0.188
Epoch: 140, Train Loss: 1.756, Val f1_micro: 0.181
Epoch: 160, Train Loss: 1.736, Val f1_micro: 0.186
Epoch: 180, Train Loss: 1.734, Val f1_micro: 0.190
Epoch: 200, Train Loss: 1.689, Val f1_micro: 0.192
Epoch: 220, Train Loss: 1.655, Val f1_micro: 0.190
Epoch: 240, Train Loss: 1.641, Val f1_micro: 0.202
Epoch: 260, Train Loss: 1.621, Val f1_micro: 0.198
Epoch: 280, Train Loss: 1.627, Val f1_micro: 0.210
Epoch: 300, Train Loss: 1.576, Val f1_micro: 0.217
Epoch: 320, Train Loss: 1.583, Val f1_micro: 0.208
Epoch: 340, Train Loss: 1.574, Val f1_micro: 0.211
Epoch: 360, Train Loss: 1.531, Val f1_micro: 0.216
Epoch: 380, Train Loss: 1.537, Val f1_micro: 0.219
Epoch: 400, Train Loss: 1.517, Val f1_micro: 0.216
Epoch: 420, Train Loss: 1.475, Val f1_micro: 0.215
Epoch: 440, Train Loss: 1.476, Val f1_micro: 0.221
Epoch: 460, Train Loss: 1.489, Val f1_micro: 0.225
Epoch: 480, Train Loss: 1.456, Val f1_micro: 0.223
Epoch: 500, Train Loss: 1.435, Val f1_micro: 0.230
f1-micro: 0.230, f1-macro: 0.213, f1-weighted: 0.215, , roc-auc: 0.641
##### RUN 4 #####
Epoch: 020, Train Loss: 2.057, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.020, Val f1_micro: 0.161
Epoch: 060, Train Loss: 1.993, Val f1_micro: 0.117
Epoch: 080, Train Loss: 1.960, Val f1_micro: 0.120
Epoch: 100, Train Loss: 1.893, Val f1_micro: 0.151
Epoch: 120, Train Loss: 1.863, Val f1_micro: 0.186
Epoch: 140, Train Loss: 1.846, Val f1_micro: 0.182
Epoch: 160, Train Loss: 1.814, Val f1_micro: 0.182
Epoch: 180, Train Loss: 1.752, Val f1_micro: 0.179
Epoch: 200, Train Loss: 1.684, Val f1_micro: 0.199
Epoch: 220, Train Loss: 1.645, Val f1_micro: 0.210
Epoch: 240, Train Loss: 1.615, Val f1_micro: 0.192
Epoch: 260, Train Loss: 1.586, Val f1_micro: 0.216
Epoch: 280, Train Loss: 1.594, Val f1_micro: 0.216
Epoch: 300, Train Loss: 1.588, Val f1_micro: 0.210
Epoch: 320, Train Loss: 1.513, Val f1_micro: 0.224
Epoch: 340, Train Loss: 1.514, Val f1_micro: 0.220
Epoch: 360, Train Loss: 1.520, Val f1_micro: 0.223
Epoch: 380, Train Loss: 1.474, Val f1_micro: 0.223
Epoch: 400, Train Loss: 1.468, Val f1_micro: 0.223
Epoch: 420, Train Loss: 1.454, Val f1_micro: 0.232
Epoch: 440, Train Loss: 1.460, Val f1_micro: 0.235
Epoch: 460, Train Loss: 1.430, Val f1_micro: 0.228
Epoch: 480, Train Loss: 1.419, Val f1_micro: 0.226
Epoch: 500, Train Loss: 1.437, Val f1_micro: 0.234
f1-micro: 0.234, f1-macro: 0.218, f1-weighted: 0.218, , roc-auc: 0.646
##### RUN 5 #####
Epoch: 020, Train Loss: 2.080, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.011, Val f1_micro: 0.117
Epoch: 060, Train Loss: 1.983, Val f1_micro: 0.146
Epoch: 080, Train Loss: 1.932, Val f1_micro: 0.164
Epoch: 100, Train Loss: 1.913, Val f1_micro: 0.165
Epoch: 120, Train Loss: 1.857, Val f1_micro: 0.171
Epoch: 140, Train Loss: 1.820, Val f1_micro: 0.175
Epoch: 160, Train Loss: 1.781, Val f1_micro: 0.186
Epoch: 180, Train Loss: 1.774, Val f1_micro: 0.197
Epoch: 200, Train Loss: 1.708, Val f1_micro: 0.194
Epoch: 220, Train Loss: 1.699, Val f1_micro: 0.183
Epoch: 240, Train Loss: 1.687, Val f1_micro: 0.195
Epoch: 260, Train Loss: 1.650, Val f1_micro: 0.193
Epoch: 280, Train Loss: 1.648, Val f1_micro: 0.200
Epoch: 300, Train Loss: 1.623, Val f1_micro: 0.199
Epoch: 320, Train Loss: 1.601, Val f1_micro: 0.213
Epoch: 340, Train Loss: 1.572, Val f1_micro: 0.214
Epoch: 360, Train Loss: 1.561, Val f1_micro: 0.219
Epoch: 380, Train Loss: 1.566, Val f1_micro: 0.214
Epoch: 400, Train Loss: 1.535, Val f1_micro: 0.214
Epoch: 420, Train Loss: 1.486, Val f1_micro: 0.223
Epoch: 440, Train Loss: 1.528, Val f1_micro: 0.205
Epoch: 460, Train Loss: 1.514, Val f1_micro: 0.216
Epoch: 480, Train Loss: 1.481, Val f1_micro: 0.222
Epoch: 500, Train Loss: 1.482, Val f1_micro: 0.222
f1-micro: 0.222, f1-macro: 0.205, f1-weighted: 0.202, , roc-auc: 0.638
########## Hyperparameters combination ##########
(1024, 0.6, 0.05, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.080, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.044, Val f1_micro: 0.155
Epoch: 060, Train Loss: 2.021, Val f1_micro: 0.108
Epoch: 080, Train Loss: 1.980, Val f1_micro: 0.139
Epoch: 100, Train Loss: 1.964, Val f1_micro: 0.174
Epoch: 120, Train Loss: 1.947, Val f1_micro: 0.176
Epoch: 140, Train Loss: 1.935, Val f1_micro: 0.166
Epoch: 160, Train Loss: 1.911, Val f1_micro: 0.192
Epoch: 180, Train Loss: 1.898, Val f1_micro: 0.175
Epoch: 200, Train Loss: 1.888, Val f1_micro: 0.161
Epoch: 220, Train Loss: 1.896, Val f1_micro: 0.188
Epoch: 240, Train Loss: 1.906, Val f1_micro: 0.170
Epoch: 260, Train Loss: 1.882, Val f1_micro: 0.188
Epoch: 280, Train Loss: 1.891, Val f1_micro: 0.175
Epoch: 300, Train Loss: 1.880, Val f1_micro: 0.173
Epoch: 320, Train Loss: 1.877, Val f1_micro: 0.191
Epoch: 340, Train Loss: 1.871, Val f1_micro: 0.190
Epoch: 360, Train Loss: 1.880, Val f1_micro: 0.199
Epoch: 380, Train Loss: 1.882, Val f1_micro: 0.181
Epoch: 400, Train Loss: 1.866, Val f1_micro: 0.190
Epoch: 420, Train Loss: 1.860, Val f1_micro: 0.193
Epoch: 440, Train Loss: 1.858, Val f1_micro: 0.178
Epoch: 460, Train Loss: 1.864, Val f1_micro: 0.185
Epoch: 480, Train Loss: 1.847, Val f1_micro: 0.186
Epoch: 500, Train Loss: 1.865, Val f1_micro: 0.173
f1-micro: 0.173, f1-macro: 0.127, f1-weighted: 0.127, , roc-auc: 0.620
##### RUN 2 #####
Epoch: 020, Train Loss: 2.062, Val f1_micro: 0.097
Epoch: 040, Train Loss: 2.041, Val f1_micro: 0.112
Epoch: 060, Train Loss: 2.020, Val f1_micro: 0.120
Epoch: 080, Train Loss: 1.992, Val f1_micro: 0.167
Epoch: 100, Train Loss: 1.967, Val f1_micro: 0.174
Epoch: 120, Train Loss: 1.939, Val f1_micro: 0.175
Epoch: 140, Train Loss: 1.908, Val f1_micro: 0.177
Epoch: 160, Train Loss: 1.920, Val f1_micro: 0.169
Epoch: 180, Train Loss: 1.907, Val f1_micro: 0.173
Epoch: 200, Train Loss: 1.872, Val f1_micro: 0.186
Epoch: 220, Train Loss: 1.890, Val f1_micro: 0.183
Epoch: 240, Train Loss: 1.874, Val f1_micro: 0.179
Epoch: 260, Train Loss: 1.869, Val f1_micro: 0.158
Epoch: 280, Train Loss: 1.864, Val f1_micro: 0.192
Epoch: 300, Train Loss: 1.872, Val f1_micro: 0.196
Epoch: 320, Train Loss: 1.871, Val f1_micro: 0.187
Epoch: 340, Train Loss: 1.866, Val f1_micro: 0.192
Epoch: 360, Train Loss: 1.845, Val f1_micro: 0.183
Epoch: 380, Train Loss: 1.864, Val f1_micro: 0.190
Epoch: 400, Train Loss: 1.865, Val f1_micro: 0.194
Epoch: 420, Train Loss: 1.855, Val f1_micro: 0.190
Epoch: 440, Train Loss: 1.858, Val f1_micro: 0.185
Epoch: 460, Train Loss: 1.874, Val f1_micro: 0.174
Epoch: 480, Train Loss: 1.877, Val f1_micro: 0.172
Epoch: 500, Train Loss: 1.877, Val f1_micro: 0.207
f1-micro: 0.207, f1-macro: 0.157, f1-weighted: 0.160, , roc-auc: 0.622
##### RUN 3 #####
Epoch: 020, Train Loss: 2.085, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.040, Val f1_micro: 0.163
Epoch: 060, Train Loss: 2.028, Val f1_micro: 0.143
Epoch: 080, Train Loss: 1.995, Val f1_micro: 0.154
Epoch: 100, Train Loss: 1.958, Val f1_micro: 0.161
Epoch: 120, Train Loss: 1.924, Val f1_micro: 0.170
Epoch: 140, Train Loss: 1.917, Val f1_micro: 0.184
Epoch: 160, Train Loss: 1.898, Val f1_micro: 0.146
Epoch: 180, Train Loss: 1.886, Val f1_micro: 0.185
Epoch: 200, Train Loss: 1.888, Val f1_micro: 0.185
Epoch: 220, Train Loss: 1.890, Val f1_micro: 0.197
Epoch: 240, Train Loss: 1.883, Val f1_micro: 0.202
Epoch: 260, Train Loss: 1.893, Val f1_micro: 0.177
Epoch: 280, Train Loss: 1.878, Val f1_micro: 0.185
Epoch: 300, Train Loss: 1.865, Val f1_micro: 0.202
Epoch: 320, Train Loss: 1.881, Val f1_micro: 0.192
Epoch: 340, Train Loss: 1.874, Val f1_micro: 0.178
Epoch: 360, Train Loss: 1.863, Val f1_micro: 0.187
Epoch: 380, Train Loss: 1.865, Val f1_micro: 0.194
Epoch: 400, Train Loss: 1.866, Val f1_micro: 0.196
Epoch: 420, Train Loss: 1.859, Val f1_micro: 0.185
Epoch: 440, Train Loss: 1.868, Val f1_micro: 0.151
Epoch: 460, Train Loss: 1.869, Val f1_micro: 0.192
Epoch: 480, Train Loss: 1.860, Val f1_micro: 0.174
Epoch: 500, Train Loss: 1.852, Val f1_micro: 0.179
f1-micro: 0.179, f1-macro: 0.146, f1-weighted: 0.138, , roc-auc: 0.623
##### RUN 4 #####
Epoch: 020, Train Loss: 2.088, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.046, Val f1_micro: 0.157
Epoch: 060, Train Loss: 2.030, Val f1_micro: 0.113
Epoch: 080, Train Loss: 1.979, Val f1_micro: 0.174
Epoch: 100, Train Loss: 1.947, Val f1_micro: 0.162
Epoch: 120, Train Loss: 1.925, Val f1_micro: 0.170
Epoch: 140, Train Loss: 1.942, Val f1_micro: 0.183
Epoch: 160, Train Loss: 1.906, Val f1_micro: 0.188
Epoch: 180, Train Loss: 1.904, Val f1_micro: 0.190
Epoch: 200, Train Loss: 1.900, Val f1_micro: 0.188
Epoch: 220, Train Loss: 1.910, Val f1_micro: 0.198
Epoch: 240, Train Loss: 1.887, Val f1_micro: 0.180
Epoch: 260, Train Loss: 1.892, Val f1_micro: 0.191
Epoch: 280, Train Loss: 1.884, Val f1_micro: 0.188
Epoch: 300, Train Loss: 1.879, Val f1_micro: 0.192
Epoch: 320, Train Loss: 1.887, Val f1_micro: 0.197
Epoch: 340, Train Loss: 1.881, Val f1_micro: 0.184
Epoch: 360, Train Loss: 1.874, Val f1_micro: 0.182
Epoch: 380, Train Loss: 1.863, Val f1_micro: 0.186
Epoch: 400, Train Loss: 1.868, Val f1_micro: 0.182
Epoch: 420, Train Loss: 1.865, Val f1_micro: 0.182
Epoch: 440, Train Loss: 1.864, Val f1_micro: 0.190
Epoch: 460, Train Loss: 1.876, Val f1_micro: 0.161
Epoch: 480, Train Loss: 1.868, Val f1_micro: 0.187
Epoch: 500, Train Loss: 1.883, Val f1_micro: 0.190
f1-micro: 0.190, f1-macro: 0.163, f1-weighted: 0.155, , roc-auc: 0.623
##### RUN 5 #####
Epoch: 020, Train Loss: 2.100, Val f1_micro: 0.096
Epoch: 040, Train Loss: 2.046, Val f1_micro: 0.154
Epoch: 060, Train Loss: 2.024, Val f1_micro: 0.131
Epoch: 080, Train Loss: 1.976, Val f1_micro: 0.172
Epoch: 100, Train Loss: 1.961, Val f1_micro: 0.162
Epoch: 120, Train Loss: 1.938, Val f1_micro: 0.177
Epoch: 140, Train Loss: 1.921, Val f1_micro: 0.182
Epoch: 160, Train Loss: 1.915, Val f1_micro: 0.188
Epoch: 180, Train Loss: 1.893, Val f1_micro: 0.188
Epoch: 200, Train Loss: 1.901, Val f1_micro: 0.187
Epoch: 220, Train Loss: 1.897, Val f1_micro: 0.172
Epoch: 240, Train Loss: 1.873, Val f1_micro: 0.187
Epoch: 260, Train Loss: 1.878, Val f1_micro: 0.170
Epoch: 280, Train Loss: 1.871, Val f1_micro: 0.179
Epoch: 300, Train Loss: 1.872, Val f1_micro: 0.186
Epoch: 320, Train Loss: 1.869, Val f1_micro: 0.196
Epoch: 340, Train Loss: 1.869, Val f1_micro: 0.191
Epoch: 360, Train Loss: 1.867, Val f1_micro: 0.192
Epoch: 380, Train Loss: 1.882, Val f1_micro: 0.200
Epoch: 400, Train Loss: 1.857, Val f1_micro: 0.213
Epoch: 420, Train Loss: 1.875, Val f1_micro: 0.152
Epoch: 440, Train Loss: 1.864, Val f1_micro: 0.194
Epoch: 460, Train Loss: 1.868, Val f1_micro: 0.186
Epoch: 480, Train Loss: 1.863, Val f1_micro: 0.172
Epoch: 500, Train Loss: 1.874, Val f1_micro: 0.181
f1-micro: 0.181, f1-macro: 0.157, f1-weighted: 0.151, , roc-auc: 0.624
########## Hyperparameters combination ##########
(1024, 0.7, 0.001, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.543, Val f1_micro: 0.193
Epoch: 040, Train Loss: 2.203, Val f1_micro: 0.195
Epoch: 060, Train Loss: 2.075, Val f1_micro: 0.202
Epoch: 080, Train Loss: 1.936, Val f1_micro: 0.203
Epoch: 100, Train Loss: 1.846, Val f1_micro: 0.210
Epoch: 120, Train Loss: 1.765, Val f1_micro: 0.216
Epoch: 140, Train Loss: 1.731, Val f1_micro: 0.218
Epoch: 160, Train Loss: 1.673, Val f1_micro: 0.225
Epoch: 180, Train Loss: 1.627, Val f1_micro: 0.227
Epoch: 200, Train Loss: 1.608, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.568, Val f1_micro: 0.232
Epoch: 240, Train Loss: 1.545, Val f1_micro: 0.235
Epoch: 260, Train Loss: 1.529, Val f1_micro: 0.238
Epoch: 280, Train Loss: 1.473, Val f1_micro: 0.240
Epoch: 300, Train Loss: 1.465, Val f1_micro: 0.242
Epoch: 320, Train Loss: 1.450, Val f1_micro: 0.242
Epoch: 340, Train Loss: 1.431, Val f1_micro: 0.244
Epoch: 360, Train Loss: 1.386, Val f1_micro: 0.247
Epoch: 380, Train Loss: 1.379, Val f1_micro: 0.245
Epoch: 400, Train Loss: 1.363, Val f1_micro: 0.247
Epoch: 420, Train Loss: 1.354, Val f1_micro: 0.248
Epoch: 440, Train Loss: 1.334, Val f1_micro: 0.246
Epoch: 460, Train Loss: 1.313, Val f1_micro: 0.247
Epoch: 480, Train Loss: 1.279, Val f1_micro: 0.248
Epoch: 500, Train Loss: 1.275, Val f1_micro: 0.253
f1-micro: 0.253, f1-macro: 0.245, f1-weighted: 0.246, , roc-auc: 0.666
##### RUN 2 #####
Epoch: 020, Train Loss: 2.615, Val f1_micro: 0.197
Epoch: 040, Train Loss: 2.232, Val f1_micro: 0.200
Epoch: 060, Train Loss: 2.052, Val f1_micro: 0.205
Epoch: 080, Train Loss: 1.936, Val f1_micro: 0.203
Epoch: 100, Train Loss: 1.852, Val f1_micro: 0.210
Epoch: 120, Train Loss: 1.800, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.732, Val f1_micro: 0.221
Epoch: 160, Train Loss: 1.679, Val f1_micro: 0.225
Epoch: 180, Train Loss: 1.633, Val f1_micro: 0.225
Epoch: 200, Train Loss: 1.592, Val f1_micro: 0.230
Epoch: 220, Train Loss: 1.575, Val f1_micro: 0.229
Epoch: 240, Train Loss: 1.561, Val f1_micro: 0.232
Epoch: 260, Train Loss: 1.516, Val f1_micro: 0.237
Epoch: 280, Train Loss: 1.474, Val f1_micro: 0.242
Epoch: 300, Train Loss: 1.482, Val f1_micro: 0.239
Epoch: 320, Train Loss: 1.441, Val f1_micro: 0.241
Epoch: 340, Train Loss: 1.408, Val f1_micro: 0.247
Epoch: 360, Train Loss: 1.402, Val f1_micro: 0.244
Epoch: 380, Train Loss: 1.382, Val f1_micro: 0.244
Epoch: 400, Train Loss: 1.349, Val f1_micro: 0.247
Epoch: 420, Train Loss: 1.372, Val f1_micro: 0.247
Epoch: 440, Train Loss: 1.328, Val f1_micro: 0.249
Epoch: 460, Train Loss: 1.307, Val f1_micro: 0.251
Epoch: 480, Train Loss: 1.282, Val f1_micro: 0.248
Epoch: 500, Train Loss: 1.279, Val f1_micro: 0.251
f1-micro: 0.251, f1-macro: 0.242, f1-weighted: 0.243, , roc-auc: 0.666
##### RUN 3 #####
Epoch: 020, Train Loss: 2.516, Val f1_micro: 0.193
Epoch: 040, Train Loss: 2.161, Val f1_micro: 0.197
Epoch: 060, Train Loss: 2.047, Val f1_micro: 0.205
Epoch: 080, Train Loss: 1.920, Val f1_micro: 0.207
Epoch: 100, Train Loss: 1.865, Val f1_micro: 0.205
Epoch: 120, Train Loss: 1.794, Val f1_micro: 0.216
Epoch: 140, Train Loss: 1.741, Val f1_micro: 0.221
Epoch: 160, Train Loss: 1.711, Val f1_micro: 0.224
Epoch: 180, Train Loss: 1.639, Val f1_micro: 0.225
Epoch: 200, Train Loss: 1.623, Val f1_micro: 0.235
Epoch: 220, Train Loss: 1.562, Val f1_micro: 0.237
Epoch: 240, Train Loss: 1.557, Val f1_micro: 0.233
Epoch: 260, Train Loss: 1.525, Val f1_micro: 0.237
Epoch: 280, Train Loss: 1.487, Val f1_micro: 0.237
Epoch: 300, Train Loss: 1.484, Val f1_micro: 0.241
Epoch: 320, Train Loss: 1.448, Val f1_micro: 0.241
Epoch: 340, Train Loss: 1.409, Val f1_micro: 0.247
Epoch: 360, Train Loss: 1.405, Val f1_micro: 0.243
Epoch: 380, Train Loss: 1.384, Val f1_micro: 0.248
Epoch: 400, Train Loss: 1.366, Val f1_micro: 0.247
Epoch: 420, Train Loss: 1.339, Val f1_micro: 0.250
Epoch: 440, Train Loss: 1.326, Val f1_micro: 0.249
Epoch: 460, Train Loss: 1.307, Val f1_micro: 0.249
Epoch: 480, Train Loss: 1.284, Val f1_micro: 0.254
Epoch: 500, Train Loss: 1.277, Val f1_micro: 0.254
f1-micro: 0.254, f1-macro: 0.245, f1-weighted: 0.246, , roc-auc: 0.667
##### RUN 4 #####
Epoch: 020, Train Loss: 2.552, Val f1_micro: 0.194
Epoch: 040, Train Loss: 2.196, Val f1_micro: 0.200
Epoch: 060, Train Loss: 2.039, Val f1_micro: 0.203
Epoch: 080, Train Loss: 1.930, Val f1_micro: 0.204
Epoch: 100, Train Loss: 1.850, Val f1_micro: 0.216
Epoch: 120, Train Loss: 1.792, Val f1_micro: 0.219
Epoch: 140, Train Loss: 1.749, Val f1_micro: 0.224
Epoch: 160, Train Loss: 1.702, Val f1_micro: 0.221
Epoch: 180, Train Loss: 1.649, Val f1_micro: 0.226
Epoch: 200, Train Loss: 1.620, Val f1_micro: 0.229
Epoch: 220, Train Loss: 1.577, Val f1_micro: 0.236
Epoch: 240, Train Loss: 1.569, Val f1_micro: 0.233
Epoch: 260, Train Loss: 1.525, Val f1_micro: 0.236
Epoch: 280, Train Loss: 1.483, Val f1_micro: 0.238
Epoch: 300, Train Loss: 1.453, Val f1_micro: 0.242
Epoch: 320, Train Loss: 1.450, Val f1_micro: 0.245
Epoch: 340, Train Loss: 1.429, Val f1_micro: 0.243
Epoch: 360, Train Loss: 1.383, Val f1_micro: 0.245
Epoch: 380, Train Loss: 1.381, Val f1_micro: 0.243
Epoch: 400, Train Loss: 1.365, Val f1_micro: 0.247
Epoch: 420, Train Loss: 1.347, Val f1_micro: 0.248
Epoch: 440, Train Loss: 1.343, Val f1_micro: 0.250
Epoch: 460, Train Loss: 1.288, Val f1_micro: 0.248
Epoch: 480, Train Loss: 1.283, Val f1_micro: 0.252
Epoch: 500, Train Loss: 1.284, Val f1_micro: 0.252
f1-micro: 0.252, f1-macro: 0.243, f1-weighted: 0.244, , roc-auc: 0.666
##### RUN 5 #####
Epoch: 020, Train Loss: 2.575, Val f1_micro: 0.192
Epoch: 040, Train Loss: 2.220, Val f1_micro: 0.197
Epoch: 060, Train Loss: 2.045, Val f1_micro: 0.205
Epoch: 080, Train Loss: 1.975, Val f1_micro: 0.205
Epoch: 100, Train Loss: 1.871, Val f1_micro: 0.212
Epoch: 120, Train Loss: 1.802, Val f1_micro: 0.219
Epoch: 140, Train Loss: 1.750, Val f1_micro: 0.219
Epoch: 160, Train Loss: 1.691, Val f1_micro: 0.225
Epoch: 180, Train Loss: 1.659, Val f1_micro: 0.231
Epoch: 200, Train Loss: 1.596, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.580, Val f1_micro: 0.236
Epoch: 240, Train Loss: 1.550, Val f1_micro: 0.234
Epoch: 260, Train Loss: 1.516, Val f1_micro: 0.234
Epoch: 280, Train Loss: 1.485, Val f1_micro: 0.239
Epoch: 300, Train Loss: 1.479, Val f1_micro: 0.241
Epoch: 320, Train Loss: 1.460, Val f1_micro: 0.240
Epoch: 340, Train Loss: 1.413, Val f1_micro: 0.247
Epoch: 360, Train Loss: 1.419, Val f1_micro: 0.245
Epoch: 380, Train Loss: 1.407, Val f1_micro: 0.243
Epoch: 400, Train Loss: 1.369, Val f1_micro: 0.247
Epoch: 420, Train Loss: 1.347, Val f1_micro: 0.247
Epoch: 440, Train Loss: 1.305, Val f1_micro: 0.248
Epoch: 460, Train Loss: 1.313, Val f1_micro: 0.251
Epoch: 480, Train Loss: 1.298, Val f1_micro: 0.251
Epoch: 500, Train Loss: 1.271, Val f1_micro: 0.253
f1-micro: 0.253, f1-macro: 0.244, f1-weighted: 0.244, , roc-auc: 0.666
########## Hyperparameters combination ##########
(1024, 0.7, 0.001, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.550, Val f1_micro: 0.200
Epoch: 040, Train Loss: 2.211, Val f1_micro: 0.209
Epoch: 060, Train Loss: 2.037, Val f1_micro: 0.209
Epoch: 080, Train Loss: 1.923, Val f1_micro: 0.207
Epoch: 100, Train Loss: 1.854, Val f1_micro: 0.220
Epoch: 120, Train Loss: 1.819, Val f1_micro: 0.219
Epoch: 140, Train Loss: 1.765, Val f1_micro: 0.223
Epoch: 160, Train Loss: 1.707, Val f1_micro: 0.225
Epoch: 180, Train Loss: 1.660, Val f1_micro: 0.224
Epoch: 200, Train Loss: 1.634, Val f1_micro: 0.228
Epoch: 220, Train Loss: 1.597, Val f1_micro: 0.231
Epoch: 240, Train Loss: 1.572, Val f1_micro: 0.233
Epoch: 260, Train Loss: 1.563, Val f1_micro: 0.233
Epoch: 280, Train Loss: 1.527, Val f1_micro: 0.236
Epoch: 300, Train Loss: 1.515, Val f1_micro: 0.238
Epoch: 320, Train Loss: 1.485, Val f1_micro: 0.241
Epoch: 340, Train Loss: 1.459, Val f1_micro: 0.239
Epoch: 360, Train Loss: 1.468, Val f1_micro: 0.241
Epoch: 380, Train Loss: 1.428, Val f1_micro: 0.240
Epoch: 400, Train Loss: 1.412, Val f1_micro: 0.248
Epoch: 420, Train Loss: 1.412, Val f1_micro: 0.244
Epoch: 440, Train Loss: 1.376, Val f1_micro: 0.244
Epoch: 460, Train Loss: 1.370, Val f1_micro: 0.246
Epoch: 480, Train Loss: 1.344, Val f1_micro: 0.247
Epoch: 500, Train Loss: 1.334, Val f1_micro: 0.247
f1-micro: 0.247, f1-macro: 0.237, f1-weighted: 0.236, , roc-auc: 0.665
##### RUN 2 #####
Epoch: 020, Train Loss: 2.501, Val f1_micro: 0.199
Epoch: 040, Train Loss: 2.235, Val f1_micro: 0.201
Epoch: 060, Train Loss: 2.048, Val f1_micro: 0.213
Epoch: 080, Train Loss: 1.953, Val f1_micro: 0.216
Epoch: 100, Train Loss: 1.861, Val f1_micro: 0.219
Epoch: 120, Train Loss: 1.785, Val f1_micro: 0.223
Epoch: 140, Train Loss: 1.758, Val f1_micro: 0.224
Epoch: 160, Train Loss: 1.704, Val f1_micro: 0.224
Epoch: 180, Train Loss: 1.654, Val f1_micro: 0.228
Epoch: 200, Train Loss: 1.633, Val f1_micro: 0.229
Epoch: 220, Train Loss: 1.592, Val f1_micro: 0.228
Epoch: 240, Train Loss: 1.570, Val f1_micro: 0.229
Epoch: 260, Train Loss: 1.555, Val f1_micro: 0.237
Epoch: 280, Train Loss: 1.504, Val f1_micro: 0.237
Epoch: 300, Train Loss: 1.504, Val f1_micro: 0.236
Epoch: 320, Train Loss: 1.489, Val f1_micro: 0.236
Epoch: 340, Train Loss: 1.473, Val f1_micro: 0.240
Epoch: 360, Train Loss: 1.438, Val f1_micro: 0.242
Epoch: 380, Train Loss: 1.429, Val f1_micro: 0.241
Epoch: 400, Train Loss: 1.429, Val f1_micro: 0.243
Epoch: 420, Train Loss: 1.415, Val f1_micro: 0.243
Epoch: 440, Train Loss: 1.394, Val f1_micro: 0.245
Epoch: 460, Train Loss: 1.365, Val f1_micro: 0.248
Epoch: 480, Train Loss: 1.369, Val f1_micro: 0.249
Epoch: 500, Train Loss: 1.352, Val f1_micro: 0.248
f1-micro: 0.248, f1-macro: 0.238, f1-weighted: 0.238, , roc-auc: 0.664
##### RUN 3 #####
Epoch: 020, Train Loss: 2.580, Val f1_micro: 0.197
Epoch: 040, Train Loss: 2.171, Val f1_micro: 0.201
Epoch: 060, Train Loss: 2.066, Val f1_micro: 0.209
Epoch: 080, Train Loss: 1.947, Val f1_micro: 0.213
Epoch: 100, Train Loss: 1.878, Val f1_micro: 0.216
Epoch: 120, Train Loss: 1.793, Val f1_micro: 0.218
Epoch: 140, Train Loss: 1.740, Val f1_micro: 0.223
Epoch: 160, Train Loss: 1.700, Val f1_micro: 0.221
Epoch: 180, Train Loss: 1.656, Val f1_micro: 0.223
Epoch: 200, Train Loss: 1.613, Val f1_micro: 0.227
Epoch: 220, Train Loss: 1.613, Val f1_micro: 0.230
Epoch: 240, Train Loss: 1.569, Val f1_micro: 0.234
Epoch: 260, Train Loss: 1.538, Val f1_micro: 0.236
Epoch: 280, Train Loss: 1.522, Val f1_micro: 0.234
Epoch: 300, Train Loss: 1.507, Val f1_micro: 0.237
Epoch: 320, Train Loss: 1.477, Val f1_micro: 0.237
Epoch: 340, Train Loss: 1.451, Val f1_micro: 0.239
Epoch: 360, Train Loss: 1.423, Val f1_micro: 0.243
Epoch: 380, Train Loss: 1.441, Val f1_micro: 0.241
Epoch: 400, Train Loss: 1.398, Val f1_micro: 0.242
Epoch: 420, Train Loss: 1.397, Val f1_micro: 0.242
Epoch: 440, Train Loss: 1.374, Val f1_micro: 0.245
Epoch: 460, Train Loss: 1.377, Val f1_micro: 0.248
Epoch: 480, Train Loss: 1.353, Val f1_micro: 0.248
Epoch: 500, Train Loss: 1.323, Val f1_micro: 0.248
f1-micro: 0.248, f1-macro: 0.239, f1-weighted: 0.239, , roc-auc: 0.664
##### RUN 4 #####
Epoch: 020, Train Loss: 2.517, Val f1_micro: 0.194
Epoch: 040, Train Loss: 2.193, Val f1_micro: 0.200
Epoch: 060, Train Loss: 2.050, Val f1_micro: 0.208
Epoch: 080, Train Loss: 1.922, Val f1_micro: 0.215
Epoch: 100, Train Loss: 1.874, Val f1_micro: 0.221
Epoch: 120, Train Loss: 1.810, Val f1_micro: 0.224
Epoch: 140, Train Loss: 1.746, Val f1_micro: 0.222
Epoch: 160, Train Loss: 1.692, Val f1_micro: 0.227
Epoch: 180, Train Loss: 1.665, Val f1_micro: 0.227
Epoch: 200, Train Loss: 1.636, Val f1_micro: 0.229
Epoch: 220, Train Loss: 1.589, Val f1_micro: 0.226
Epoch: 240, Train Loss: 1.578, Val f1_micro: 0.233
Epoch: 260, Train Loss: 1.554, Val f1_micro: 0.232
Epoch: 280, Train Loss: 1.524, Val f1_micro: 0.239
Epoch: 300, Train Loss: 1.499, Val f1_micro: 0.237
Epoch: 320, Train Loss: 1.472, Val f1_micro: 0.236
Epoch: 340, Train Loss: 1.455, Val f1_micro: 0.240
Epoch: 360, Train Loss: 1.474, Val f1_micro: 0.243
Epoch: 380, Train Loss: 1.442, Val f1_micro: 0.241
Epoch: 400, Train Loss: 1.415, Val f1_micro: 0.246
Epoch: 420, Train Loss: 1.421, Val f1_micro: 0.247
Epoch: 440, Train Loss: 1.375, Val f1_micro: 0.243
Epoch: 460, Train Loss: 1.365, Val f1_micro: 0.247
Epoch: 480, Train Loss: 1.351, Val f1_micro: 0.247
Epoch: 500, Train Loss: 1.352, Val f1_micro: 0.248
f1-micro: 0.248, f1-macro: 0.238, f1-weighted: 0.238, , roc-auc: 0.665
##### RUN 5 #####
Epoch: 020, Train Loss: 2.530, Val f1_micro: 0.198
Epoch: 040, Train Loss: 2.226, Val f1_micro: 0.203
Epoch: 060, Train Loss: 2.046, Val f1_micro: 0.207
Epoch: 080, Train Loss: 1.935, Val f1_micro: 0.209
Epoch: 100, Train Loss: 1.873, Val f1_micro: 0.217
Epoch: 120, Train Loss: 1.806, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.741, Val f1_micro: 0.220
Epoch: 160, Train Loss: 1.698, Val f1_micro: 0.225
Epoch: 180, Train Loss: 1.655, Val f1_micro: 0.225
Epoch: 200, Train Loss: 1.635, Val f1_micro: 0.229
Epoch: 220, Train Loss: 1.605, Val f1_micro: 0.227
Epoch: 240, Train Loss: 1.561, Val f1_micro: 0.230
Epoch: 260, Train Loss: 1.549, Val f1_micro: 0.234
Epoch: 280, Train Loss: 1.512, Val f1_micro: 0.234
Epoch: 300, Train Loss: 1.475, Val f1_micro: 0.234
Epoch: 320, Train Loss: 1.495, Val f1_micro: 0.238
Epoch: 340, Train Loss: 1.469, Val f1_micro: 0.239
Epoch: 360, Train Loss: 1.447, Val f1_micro: 0.239
Epoch: 380, Train Loss: 1.421, Val f1_micro: 0.241
Epoch: 400, Train Loss: 1.396, Val f1_micro: 0.243
Epoch: 420, Train Loss: 1.394, Val f1_micro: 0.246
Epoch: 440, Train Loss: 1.382, Val f1_micro: 0.247
Epoch: 460, Train Loss: 1.361, Val f1_micro: 0.244
Epoch: 480, Train Loss: 1.351, Val f1_micro: 0.243
Epoch: 500, Train Loss: 1.329, Val f1_micro: 0.245
f1-micro: 0.245, f1-macro: 0.235, f1-weighted: 0.235, , roc-auc: 0.664
########## Hyperparameters combination ##########
(1024, 0.7, 0.001, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.557, Val f1_micro: 0.195
Epoch: 040, Train Loss: 2.234, Val f1_micro: 0.195
Epoch: 060, Train Loss: 2.064, Val f1_micro: 0.201
Epoch: 080, Train Loss: 1.960, Val f1_micro: 0.202
Epoch: 100, Train Loss: 1.854, Val f1_micro: 0.211
Epoch: 120, Train Loss: 1.821, Val f1_micro: 0.212
Epoch: 140, Train Loss: 1.768, Val f1_micro: 0.210
Epoch: 160, Train Loss: 1.728, Val f1_micro: 0.216
Epoch: 180, Train Loss: 1.688, Val f1_micro: 0.219
Epoch: 200, Train Loss: 1.655, Val f1_micro: 0.220
Epoch: 220, Train Loss: 1.598, Val f1_micro: 0.226
Epoch: 240, Train Loss: 1.613, Val f1_micro: 0.228
Epoch: 260, Train Loss: 1.586, Val f1_micro: 0.227
Epoch: 280, Train Loss: 1.567, Val f1_micro: 0.233
Epoch: 300, Train Loss: 1.544, Val f1_micro: 0.230
Epoch: 320, Train Loss: 1.516, Val f1_micro: 0.238
Epoch: 340, Train Loss: 1.509, Val f1_micro: 0.236
Epoch: 360, Train Loss: 1.512, Val f1_micro: 0.237
Epoch: 380, Train Loss: 1.482, Val f1_micro: 0.238
Epoch: 400, Train Loss: 1.472, Val f1_micro: 0.240
Epoch: 420, Train Loss: 1.455, Val f1_micro: 0.237
Epoch: 440, Train Loss: 1.455, Val f1_micro: 0.243
Epoch: 460, Train Loss: 1.438, Val f1_micro: 0.240
Epoch: 480, Train Loss: 1.417, Val f1_micro: 0.243
Epoch: 500, Train Loss: 1.422, Val f1_micro: 0.241
f1-micro: 0.241, f1-macro: 0.231, f1-weighted: 0.231, , roc-auc: 0.665
##### RUN 2 #####
Epoch: 020, Train Loss: 2.553, Val f1_micro: 0.193
Epoch: 040, Train Loss: 2.174, Val f1_micro: 0.197
Epoch: 060, Train Loss: 2.052, Val f1_micro: 0.198
Epoch: 080, Train Loss: 1.960, Val f1_micro: 0.200
Epoch: 100, Train Loss: 1.878, Val f1_micro: 0.203
Epoch: 120, Train Loss: 1.817, Val f1_micro: 0.213
Epoch: 140, Train Loss: 1.744, Val f1_micro: 0.211
Epoch: 160, Train Loss: 1.725, Val f1_micro: 0.217
Epoch: 180, Train Loss: 1.680, Val f1_micro: 0.222
Epoch: 200, Train Loss: 1.658, Val f1_micro: 0.224
Epoch: 220, Train Loss: 1.617, Val f1_micro: 0.226
Epoch: 240, Train Loss: 1.590, Val f1_micro: 0.229
Epoch: 260, Train Loss: 1.577, Val f1_micro: 0.230
Epoch: 280, Train Loss: 1.543, Val f1_micro: 0.232
Epoch: 300, Train Loss: 1.562, Val f1_micro: 0.237
Epoch: 320, Train Loss: 1.516, Val f1_micro: 0.232
Epoch: 340, Train Loss: 1.507, Val f1_micro: 0.236
Epoch: 360, Train Loss: 1.483, Val f1_micro: 0.235
Epoch: 380, Train Loss: 1.493, Val f1_micro: 0.238
Epoch: 400, Train Loss: 1.475, Val f1_micro: 0.239
Epoch: 420, Train Loss: 1.464, Val f1_micro: 0.241
Epoch: 440, Train Loss: 1.426, Val f1_micro: 0.239
Epoch: 460, Train Loss: 1.437, Val f1_micro: 0.242
Epoch: 480, Train Loss: 1.433, Val f1_micro: 0.241
Epoch: 500, Train Loss: 1.423, Val f1_micro: 0.243
f1-micro: 0.243, f1-macro: 0.232, f1-weighted: 0.231, , roc-auc: 0.665
##### RUN 3 #####
Epoch: 020, Train Loss: 2.531, Val f1_micro: 0.189
Epoch: 040, Train Loss: 2.211, Val f1_micro: 0.200
Epoch: 060, Train Loss: 2.064, Val f1_micro: 0.204
Epoch: 080, Train Loss: 1.973, Val f1_micro: 0.205
Epoch: 100, Train Loss: 1.876, Val f1_micro: 0.202
Epoch: 120, Train Loss: 1.815, Val f1_micro: 0.209
Epoch: 140, Train Loss: 1.769, Val f1_micro: 0.216
Epoch: 160, Train Loss: 1.729, Val f1_micro: 0.220
Epoch: 180, Train Loss: 1.694, Val f1_micro: 0.221
Epoch: 200, Train Loss: 1.645, Val f1_micro: 0.225
Epoch: 220, Train Loss: 1.627, Val f1_micro: 0.222
Epoch: 240, Train Loss: 1.594, Val f1_micro: 0.225
Epoch: 260, Train Loss: 1.594, Val f1_micro: 0.231
Epoch: 280, Train Loss: 1.571, Val f1_micro: 0.232
Epoch: 300, Train Loss: 1.533, Val f1_micro: 0.233
Epoch: 320, Train Loss: 1.530, Val f1_micro: 0.234
Epoch: 340, Train Loss: 1.507, Val f1_micro: 0.235
Epoch: 360, Train Loss: 1.496, Val f1_micro: 0.236
Epoch: 380, Train Loss: 1.476, Val f1_micro: 0.240
Epoch: 400, Train Loss: 1.465, Val f1_micro: 0.239
Epoch: 420, Train Loss: 1.461, Val f1_micro: 0.241
Epoch: 440, Train Loss: 1.446, Val f1_micro: 0.238
Epoch: 460, Train Loss: 1.428, Val f1_micro: 0.240
Epoch: 480, Train Loss: 1.430, Val f1_micro: 0.241
Epoch: 500, Train Loss: 1.423, Val f1_micro: 0.243
f1-micro: 0.243, f1-macro: 0.231, f1-weighted: 0.231, , roc-auc: 0.664
##### RUN 4 #####
Epoch: 020, Train Loss: 2.555, Val f1_micro: 0.191
Epoch: 040, Train Loss: 2.219, Val f1_micro: 0.196
Epoch: 060, Train Loss: 2.035, Val f1_micro: 0.198
Epoch: 080, Train Loss: 1.948, Val f1_micro: 0.204
Epoch: 100, Train Loss: 1.874, Val f1_micro: 0.206
Epoch: 120, Train Loss: 1.820, Val f1_micro: 0.210
Epoch: 140, Train Loss: 1.738, Val f1_micro: 0.219
Epoch: 160, Train Loss: 1.724, Val f1_micro: 0.213
Epoch: 180, Train Loss: 1.678, Val f1_micro: 0.222
Epoch: 200, Train Loss: 1.670, Val f1_micro: 0.219
Epoch: 220, Train Loss: 1.623, Val f1_micro: 0.226
Epoch: 240, Train Loss: 1.606, Val f1_micro: 0.226
Epoch: 260, Train Loss: 1.600, Val f1_micro: 0.230
Epoch: 280, Train Loss: 1.583, Val f1_micro: 0.237
Epoch: 300, Train Loss: 1.533, Val f1_micro: 0.232
Epoch: 320, Train Loss: 1.522, Val f1_micro: 0.236
Epoch: 340, Train Loss: 1.503, Val f1_micro: 0.236
Epoch: 360, Train Loss: 1.505, Val f1_micro: 0.239
Epoch: 380, Train Loss: 1.481, Val f1_micro: 0.237
Epoch: 400, Train Loss: 1.475, Val f1_micro: 0.238
Epoch: 420, Train Loss: 1.469, Val f1_micro: 0.238
Epoch: 440, Train Loss: 1.443, Val f1_micro: 0.241
Epoch: 460, Train Loss: 1.443, Val f1_micro: 0.238
Epoch: 480, Train Loss: 1.427, Val f1_micro: 0.243
Epoch: 500, Train Loss: 1.420, Val f1_micro: 0.243
f1-micro: 0.243, f1-macro: 0.233, f1-weighted: 0.233, , roc-auc: 0.664
##### RUN 5 #####
Epoch: 020, Train Loss: 2.567, Val f1_micro: 0.195
Epoch: 040, Train Loss: 2.206, Val f1_micro: 0.196
Epoch: 060, Train Loss: 2.018, Val f1_micro: 0.204
Epoch: 080, Train Loss: 1.949, Val f1_micro: 0.198
Epoch: 100, Train Loss: 1.878, Val f1_micro: 0.206
Epoch: 120, Train Loss: 1.810, Val f1_micro: 0.211
Epoch: 140, Train Loss: 1.755, Val f1_micro: 0.210
Epoch: 160, Train Loss: 1.712, Val f1_micro: 0.218
Epoch: 180, Train Loss: 1.661, Val f1_micro: 0.221
Epoch: 200, Train Loss: 1.660, Val f1_micro: 0.223
Epoch: 220, Train Loss: 1.614, Val f1_micro: 0.228
Epoch: 240, Train Loss: 1.588, Val f1_micro: 0.229
Epoch: 260, Train Loss: 1.575, Val f1_micro: 0.230
Epoch: 280, Train Loss: 1.547, Val f1_micro: 0.231
Epoch: 300, Train Loss: 1.537, Val f1_micro: 0.232
Epoch: 320, Train Loss: 1.540, Val f1_micro: 0.233
Epoch: 340, Train Loss: 1.491, Val f1_micro: 0.233
Epoch: 360, Train Loss: 1.492, Val f1_micro: 0.236
Epoch: 380, Train Loss: 1.479, Val f1_micro: 0.236
Epoch: 400, Train Loss: 1.451, Val f1_micro: 0.240
Epoch: 420, Train Loss: 1.439, Val f1_micro: 0.238
Epoch: 440, Train Loss: 1.431, Val f1_micro: 0.240
Epoch: 460, Train Loss: 1.431, Val f1_micro: 0.243
Epoch: 480, Train Loss: 1.413, Val f1_micro: 0.239
Epoch: 500, Train Loss: 1.411, Val f1_micro: 0.241
f1-micro: 0.241, f1-macro: 0.229, f1-weighted: 0.229, , roc-auc: 0.664
########## Hyperparameters combination ##########
(1024, 0.7, 0.001, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.551, Val f1_micro: 0.194
Epoch: 040, Train Loss: 2.199, Val f1_micro: 0.199
Epoch: 060, Train Loss: 2.069, Val f1_micro: 0.201
Epoch: 080, Train Loss: 1.953, Val f1_micro: 0.206
Epoch: 100, Train Loss: 1.917, Val f1_micro: 0.207
Epoch: 120, Train Loss: 1.846, Val f1_micro: 0.207
Epoch: 140, Train Loss: 1.826, Val f1_micro: 0.212
Epoch: 160, Train Loss: 1.806, Val f1_micro: 0.208
Epoch: 180, Train Loss: 1.760, Val f1_micro: 0.215
Epoch: 200, Train Loss: 1.735, Val f1_micro: 0.214
Epoch: 220, Train Loss: 1.741, Val f1_micro: 0.214
Epoch: 240, Train Loss: 1.727, Val f1_micro: 0.214
Epoch: 260, Train Loss: 1.725, Val f1_micro: 0.213
Epoch: 280, Train Loss: 1.718, Val f1_micro: 0.217
Epoch: 300, Train Loss: 1.718, Val f1_micro: 0.217
Epoch: 320, Train Loss: 1.712, Val f1_micro: 0.222
Epoch: 340, Train Loss: 1.728, Val f1_micro: 0.220
Epoch: 360, Train Loss: 1.715, Val f1_micro: 0.222
Epoch: 380, Train Loss: 1.713, Val f1_micro: 0.217
Epoch: 400, Train Loss: 1.700, Val f1_micro: 0.221
Epoch: 420, Train Loss: 1.696, Val f1_micro: 0.218
Epoch: 440, Train Loss: 1.707, Val f1_micro: 0.216
Epoch: 460, Train Loss: 1.718, Val f1_micro: 0.220
Epoch: 480, Train Loss: 1.705, Val f1_micro: 0.219
Epoch: 500, Train Loss: 1.709, Val f1_micro: 0.219
f1-micro: 0.219, f1-macro: 0.194, f1-weighted: 0.191, , roc-auc: 0.656
##### RUN 2 #####
Epoch: 020, Train Loss: 2.575, Val f1_micro: 0.195
Epoch: 040, Train Loss: 2.215, Val f1_micro: 0.203
Epoch: 060, Train Loss: 2.042, Val f1_micro: 0.204
Epoch: 080, Train Loss: 1.974, Val f1_micro: 0.208
Epoch: 100, Train Loss: 1.874, Val f1_micro: 0.210
Epoch: 120, Train Loss: 1.827, Val f1_micro: 0.206
Epoch: 140, Train Loss: 1.796, Val f1_micro: 0.208
Epoch: 160, Train Loss: 1.777, Val f1_micro: 0.211
Epoch: 180, Train Loss: 1.755, Val f1_micro: 0.210
Epoch: 200, Train Loss: 1.766, Val f1_micro: 0.216
Epoch: 220, Train Loss: 1.746, Val f1_micro: 0.213
Epoch: 240, Train Loss: 1.720, Val f1_micro: 0.218
Epoch: 260, Train Loss: 1.723, Val f1_micro: 0.216
Epoch: 280, Train Loss: 1.712, Val f1_micro: 0.220
Epoch: 300, Train Loss: 1.706, Val f1_micro: 0.215
Epoch: 320, Train Loss: 1.714, Val f1_micro: 0.216
Epoch: 340, Train Loss: 1.707, Val f1_micro: 0.215
Epoch: 360, Train Loss: 1.717, Val f1_micro: 0.220
Epoch: 380, Train Loss: 1.712, Val f1_micro: 0.223
Epoch: 400, Train Loss: 1.690, Val f1_micro: 0.216
Epoch: 420, Train Loss: 1.721, Val f1_micro: 0.216
Epoch: 440, Train Loss: 1.717, Val f1_micro: 0.221
Epoch: 460, Train Loss: 1.697, Val f1_micro: 0.214
Epoch: 480, Train Loss: 1.708, Val f1_micro: 0.222
Epoch: 500, Train Loss: 1.697, Val f1_micro: 0.216
f1-micro: 0.216, f1-macro: 0.191, f1-weighted: 0.188, , roc-auc: 0.656
##### RUN 3 #####
Epoch: 020, Train Loss: 2.517, Val f1_micro: 0.198
Epoch: 040, Train Loss: 2.214, Val f1_micro: 0.200
Epoch: 060, Train Loss: 2.063, Val f1_micro: 0.206
Epoch: 080, Train Loss: 1.946, Val f1_micro: 0.202
Epoch: 100, Train Loss: 1.885, Val f1_micro: 0.206
Epoch: 120, Train Loss: 1.838, Val f1_micro: 0.210
Epoch: 140, Train Loss: 1.815, Val f1_micro: 0.207
Epoch: 160, Train Loss: 1.786, Val f1_micro: 0.208
Epoch: 180, Train Loss: 1.772, Val f1_micro: 0.207
Epoch: 200, Train Loss: 1.734, Val f1_micro: 0.213
Epoch: 220, Train Loss: 1.730, Val f1_micro: 0.221
Epoch: 240, Train Loss: 1.735, Val f1_micro: 0.216
Epoch: 260, Train Loss: 1.719, Val f1_micro: 0.213
Epoch: 280, Train Loss: 1.707, Val f1_micro: 0.220
Epoch: 300, Train Loss: 1.731, Val f1_micro: 0.222
Epoch: 320, Train Loss: 1.720, Val f1_micro: 0.217
Epoch: 340, Train Loss: 1.714, Val f1_micro: 0.211
Epoch: 360, Train Loss: 1.713, Val f1_micro: 0.225
Epoch: 380, Train Loss: 1.711, Val f1_micro: 0.215
Epoch: 400, Train Loss: 1.712, Val f1_micro: 0.216
Epoch: 420, Train Loss: 1.712, Val f1_micro: 0.208
Epoch: 440, Train Loss: 1.713, Val f1_micro: 0.222
Epoch: 460, Train Loss: 1.711, Val f1_micro: 0.218
Epoch: 480, Train Loss: 1.713, Val f1_micro: 0.218
Epoch: 500, Train Loss: 1.708, Val f1_micro: 0.219
f1-micro: 0.219, f1-macro: 0.196, f1-weighted: 0.194, , roc-auc: 0.657
##### RUN 4 #####
Epoch: 020, Train Loss: 2.589, Val f1_micro: 0.197
Epoch: 040, Train Loss: 2.218, Val f1_micro: 0.198
Epoch: 060, Train Loss: 2.079, Val f1_micro: 0.207
Epoch: 080, Train Loss: 1.946, Val f1_micro: 0.205
Epoch: 100, Train Loss: 1.906, Val f1_micro: 0.204
Epoch: 120, Train Loss: 1.840, Val f1_micro: 0.211
Epoch: 140, Train Loss: 1.823, Val f1_micro: 0.210
Epoch: 160, Train Loss: 1.788, Val f1_micro: 0.210
Epoch: 180, Train Loss: 1.758, Val f1_micro: 0.214
Epoch: 200, Train Loss: 1.743, Val f1_micro: 0.210
Epoch: 220, Train Loss: 1.737, Val f1_micro: 0.213
Epoch: 240, Train Loss: 1.732, Val f1_micro: 0.215
Epoch: 260, Train Loss: 1.724, Val f1_micro: 0.212
Epoch: 280, Train Loss: 1.720, Val f1_micro: 0.220
Epoch: 300, Train Loss: 1.732, Val f1_micro: 0.216
Epoch: 320, Train Loss: 1.691, Val f1_micro: 0.214
Epoch: 340, Train Loss: 1.705, Val f1_micro: 0.216
Epoch: 360, Train Loss: 1.712, Val f1_micro: 0.220
Epoch: 380, Train Loss: 1.702, Val f1_micro: 0.218
Epoch: 400, Train Loss: 1.712, Val f1_micro: 0.219
Epoch: 420, Train Loss: 1.698, Val f1_micro: 0.221
Epoch: 440, Train Loss: 1.703, Val f1_micro: 0.217
Epoch: 460, Train Loss: 1.713, Val f1_micro: 0.217
Epoch: 480, Train Loss: 1.712, Val f1_micro: 0.215
Epoch: 500, Train Loss: 1.715, Val f1_micro: 0.216
f1-micro: 0.216, f1-macro: 0.193, f1-weighted: 0.189, , roc-auc: 0.657
##### RUN 5 #####
Epoch: 020, Train Loss: 2.498, Val f1_micro: 0.196
Epoch: 040, Train Loss: 2.223, Val f1_micro: 0.201
Epoch: 060, Train Loss: 2.073, Val f1_micro: 0.206
Epoch: 080, Train Loss: 1.952, Val f1_micro: 0.208
Epoch: 100, Train Loss: 1.899, Val f1_micro: 0.207
Epoch: 120, Train Loss: 1.838, Val f1_micro: 0.204
Epoch: 140, Train Loss: 1.811, Val f1_micro: 0.210
Epoch: 160, Train Loss: 1.777, Val f1_micro: 0.211
Epoch: 180, Train Loss: 1.768, Val f1_micro: 0.216
Epoch: 200, Train Loss: 1.739, Val f1_micro: 0.214
Epoch: 220, Train Loss: 1.734, Val f1_micro: 0.212
Epoch: 240, Train Loss: 1.733, Val f1_micro: 0.213
Epoch: 260, Train Loss: 1.730, Val f1_micro: 0.220
Epoch: 280, Train Loss: 1.701, Val f1_micro: 0.217
Epoch: 300, Train Loss: 1.717, Val f1_micro: 0.213
Epoch: 320, Train Loss: 1.719, Val f1_micro: 0.213
Epoch: 340, Train Loss: 1.711, Val f1_micro: 0.217
Epoch: 360, Train Loss: 1.709, Val f1_micro: 0.216
Epoch: 380, Train Loss: 1.702, Val f1_micro: 0.218
Epoch: 400, Train Loss: 1.713, Val f1_micro: 0.218
Epoch: 420, Train Loss: 1.705, Val f1_micro: 0.216
Epoch: 440, Train Loss: 1.693, Val f1_micro: 0.215
Epoch: 460, Train Loss: 1.710, Val f1_micro: 0.216
Epoch: 480, Train Loss: 1.706, Val f1_micro: 0.222
Epoch: 500, Train Loss: 1.713, Val f1_micro: 0.219
f1-micro: 0.219, f1-macro: 0.194, f1-weighted: 0.191, , roc-auc: 0.656
########## Hyperparameters combination ##########
(1024, 0.7, 0.005, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.006, Val f1_micro: 0.183
Epoch: 040, Train Loss: 1.753, Val f1_micro: 0.214
Epoch: 060, Train Loss: 1.624, Val f1_micro: 0.228
Epoch: 080, Train Loss: 1.504, Val f1_micro: 0.240
Epoch: 100, Train Loss: 1.432, Val f1_micro: 0.246
Epoch: 120, Train Loss: 1.344, Val f1_micro: 0.251
Epoch: 140, Train Loss: 1.280, Val f1_micro: 0.255
Epoch: 160, Train Loss: 1.242, Val f1_micro: 0.263
Epoch: 180, Train Loss: 1.184, Val f1_micro: 0.261
Epoch: 200, Train Loss: 1.106, Val f1_micro: 0.264
Epoch: 220, Train Loss: 1.051, Val f1_micro: 0.267
Epoch: 240, Train Loss: 1.041, Val f1_micro: 0.274
Epoch: 260, Train Loss: 1.017, Val f1_micro: 0.277
Epoch: 280, Train Loss: 0.934, Val f1_micro: 0.277
Epoch: 300, Train Loss: 0.913, Val f1_micro: 0.283
Epoch: 320, Train Loss: 0.869, Val f1_micro: 0.284
Epoch: 340, Train Loss: 0.817, Val f1_micro: 0.288
Epoch: 360, Train Loss: 0.808, Val f1_micro: 0.286
Epoch: 380, Train Loss: 0.765, Val f1_micro: 0.287
Epoch: 400, Train Loss: 0.732, Val f1_micro: 0.291
Epoch: 420, Train Loss: 0.687, Val f1_micro: 0.293
Epoch: 440, Train Loss: 0.694, Val f1_micro: 0.294
Epoch: 460, Train Loss: 0.643, Val f1_micro: 0.296
Epoch: 480, Train Loss: 0.619, Val f1_micro: 0.294
Epoch: 500, Train Loss: 0.600, Val f1_micro: 0.297
f1-micro: 0.297, f1-macro: 0.292, f1-weighted: 0.298, , roc-auc: 0.676
##### RUN 2 #####
Epoch: 020, Train Loss: 2.001, Val f1_micro: 0.198
Epoch: 040, Train Loss: 1.756, Val f1_micro: 0.209
Epoch: 060, Train Loss: 1.599, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.488, Val f1_micro: 0.235
Epoch: 100, Train Loss: 1.442, Val f1_micro: 0.241
Epoch: 120, Train Loss: 1.345, Val f1_micro: 0.245
Epoch: 140, Train Loss: 1.280, Val f1_micro: 0.253
Epoch: 160, Train Loss: 1.223, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.157, Val f1_micro: 0.262
Epoch: 200, Train Loss: 1.110, Val f1_micro: 0.267
Epoch: 220, Train Loss: 1.074, Val f1_micro: 0.268
Epoch: 240, Train Loss: 1.024, Val f1_micro: 0.270
Epoch: 260, Train Loss: 0.969, Val f1_micro: 0.274
Epoch: 280, Train Loss: 0.937, Val f1_micro: 0.277
Epoch: 300, Train Loss: 0.884, Val f1_micro: 0.283
Epoch: 320, Train Loss: 0.832, Val f1_micro: 0.283
Epoch: 340, Train Loss: 0.783, Val f1_micro: 0.287
Epoch: 360, Train Loss: 0.778, Val f1_micro: 0.286
Epoch: 380, Train Loss: 0.728, Val f1_micro: 0.289
Epoch: 400, Train Loss: 0.706, Val f1_micro: 0.293
Epoch: 420, Train Loss: 0.698, Val f1_micro: 0.295
Epoch: 440, Train Loss: 0.663, Val f1_micro: 0.295
Epoch: 460, Train Loss: 0.635, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.632, Val f1_micro: 0.299
Epoch: 500, Train Loss: 0.585, Val f1_micro: 0.302
f1-micro: 0.302, f1-macro: 0.296, f1-weighted: 0.302, , roc-auc: 0.674
##### RUN 3 #####
Epoch: 020, Train Loss: 2.021, Val f1_micro: 0.194
Epoch: 040, Train Loss: 1.774, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.635, Val f1_micro: 0.224
Epoch: 080, Train Loss: 1.502, Val f1_micro: 0.234
Epoch: 100, Train Loss: 1.434, Val f1_micro: 0.247
Epoch: 120, Train Loss: 1.359, Val f1_micro: 0.249
Epoch: 140, Train Loss: 1.295, Val f1_micro: 0.259
Epoch: 160, Train Loss: 1.258, Val f1_micro: 0.258
Epoch: 180, Train Loss: 1.169, Val f1_micro: 0.260
Epoch: 200, Train Loss: 1.097, Val f1_micro: 0.265
Epoch: 220, Train Loss: 1.088, Val f1_micro: 0.268
Epoch: 240, Train Loss: 1.018, Val f1_micro: 0.267
Epoch: 260, Train Loss: 0.987, Val f1_micro: 0.276
Epoch: 280, Train Loss: 0.955, Val f1_micro: 0.276
Epoch: 300, Train Loss: 0.902, Val f1_micro: 0.281
Epoch: 320, Train Loss: 0.854, Val f1_micro: 0.281
Epoch: 340, Train Loss: 0.826, Val f1_micro: 0.285
Epoch: 360, Train Loss: 0.799, Val f1_micro: 0.289
Epoch: 380, Train Loss: 0.773, Val f1_micro: 0.293
Epoch: 400, Train Loss: 0.732, Val f1_micro: 0.292
Epoch: 420, Train Loss: 0.688, Val f1_micro: 0.294
Epoch: 440, Train Loss: 0.678, Val f1_micro: 0.293
Epoch: 460, Train Loss: 0.654, Val f1_micro: 0.296
Epoch: 480, Train Loss: 0.633, Val f1_micro: 0.295
Epoch: 500, Train Loss: 0.596, Val f1_micro: 0.300
f1-micro: 0.300, f1-macro: 0.294, f1-weighted: 0.300, , roc-auc: 0.675
##### RUN 4 #####
Epoch: 020, Train Loss: 2.017, Val f1_micro: 0.201
Epoch: 040, Train Loss: 1.752, Val f1_micro: 0.216
Epoch: 060, Train Loss: 1.615, Val f1_micro: 0.233
Epoch: 080, Train Loss: 1.503, Val f1_micro: 0.247
Epoch: 100, Train Loss: 1.414, Val f1_micro: 0.244
Epoch: 120, Train Loss: 1.348, Val f1_micro: 0.251
Epoch: 140, Train Loss: 1.285, Val f1_micro: 0.255
Epoch: 160, Train Loss: 1.243, Val f1_micro: 0.260
Epoch: 180, Train Loss: 1.159, Val f1_micro: 0.263
Epoch: 200, Train Loss: 1.093, Val f1_micro: 0.266
Epoch: 220, Train Loss: 1.079, Val f1_micro: 0.266
Epoch: 240, Train Loss: 1.040, Val f1_micro: 0.273
Epoch: 260, Train Loss: 0.971, Val f1_micro: 0.277
Epoch: 280, Train Loss: 0.957, Val f1_micro: 0.279
Epoch: 300, Train Loss: 0.898, Val f1_micro: 0.282
Epoch: 320, Train Loss: 0.841, Val f1_micro: 0.287
Epoch: 340, Train Loss: 0.832, Val f1_micro: 0.289
Epoch: 360, Train Loss: 0.781, Val f1_micro: 0.288
Epoch: 380, Train Loss: 0.756, Val f1_micro: 0.293
Epoch: 400, Train Loss: 0.727, Val f1_micro: 0.291
Epoch: 420, Train Loss: 0.687, Val f1_micro: 0.293
Epoch: 440, Train Loss: 0.658, Val f1_micro: 0.295
Epoch: 460, Train Loss: 0.634, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.604, Val f1_micro: 0.297
Epoch: 500, Train Loss: 0.593, Val f1_micro: 0.299
f1-micro: 0.299, f1-macro: 0.295, f1-weighted: 0.300, , roc-auc: 0.675
##### RUN 5 #####
Epoch: 020, Train Loss: 2.024, Val f1_micro: 0.198
Epoch: 040, Train Loss: 1.763, Val f1_micro: 0.214
Epoch: 060, Train Loss: 1.617, Val f1_micro: 0.225
Epoch: 080, Train Loss: 1.514, Val f1_micro: 0.242
Epoch: 100, Train Loss: 1.425, Val f1_micro: 0.244
Epoch: 120, Train Loss: 1.381, Val f1_micro: 0.252
Epoch: 140, Train Loss: 1.290, Val f1_micro: 0.252
Epoch: 160, Train Loss: 1.244, Val f1_micro: 0.260
Epoch: 180, Train Loss: 1.176, Val f1_micro: 0.263
Epoch: 200, Train Loss: 1.130, Val f1_micro: 0.263
Epoch: 220, Train Loss: 1.061, Val f1_micro: 0.270
Epoch: 240, Train Loss: 1.037, Val f1_micro: 0.275
Epoch: 260, Train Loss: 0.993, Val f1_micro: 0.274
Epoch: 280, Train Loss: 0.939, Val f1_micro: 0.278
Epoch: 300, Train Loss: 0.917, Val f1_micro: 0.282
Epoch: 320, Train Loss: 0.882, Val f1_micro: 0.283
Epoch: 340, Train Loss: 0.842, Val f1_micro: 0.285
Epoch: 360, Train Loss: 0.798, Val f1_micro: 0.289
Epoch: 380, Train Loss: 0.774, Val f1_micro: 0.290
Epoch: 400, Train Loss: 0.744, Val f1_micro: 0.291
Epoch: 420, Train Loss: 0.718, Val f1_micro: 0.295
Epoch: 440, Train Loss: 0.669, Val f1_micro: 0.297
Epoch: 460, Train Loss: 0.642, Val f1_micro: 0.297
Epoch: 480, Train Loss: 0.612, Val f1_micro: 0.299
Epoch: 500, Train Loss: 0.595, Val f1_micro: 0.301
f1-micro: 0.301, f1-macro: 0.295, f1-weighted: 0.301, , roc-auc: 0.675
########## Hyperparameters combination ##########
(1024, 0.7, 0.005, 0.0005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.004, Val f1_micro: 0.187
Epoch: 040, Train Loss: 1.750, Val f1_micro: 0.203
Epoch: 060, Train Loss: 1.610, Val f1_micro: 0.221
Epoch: 080, Train Loss: 1.542, Val f1_micro: 0.232
Epoch: 100, Train Loss: 1.474, Val f1_micro: 0.240
Epoch: 120, Train Loss: 1.404, Val f1_micro: 0.238
Epoch: 140, Train Loss: 1.354, Val f1_micro: 0.243
Epoch: 160, Train Loss: 1.308, Val f1_micro: 0.246
Epoch: 180, Train Loss: 1.262, Val f1_micro: 0.251
Epoch: 200, Train Loss: 1.252, Val f1_micro: 0.256
Epoch: 220, Train Loss: 1.196, Val f1_micro: 0.248
Epoch: 240, Train Loss: 1.165, Val f1_micro: 0.257
Epoch: 260, Train Loss: 1.134, Val f1_micro: 0.260
Epoch: 280, Train Loss: 1.093, Val f1_micro: 0.266
Epoch: 300, Train Loss: 1.093, Val f1_micro: 0.270
Epoch: 320, Train Loss: 1.055, Val f1_micro: 0.271
Epoch: 340, Train Loss: 1.027, Val f1_micro: 0.268
Epoch: 360, Train Loss: 1.029, Val f1_micro: 0.274
Epoch: 380, Train Loss: 0.977, Val f1_micro: 0.279
Epoch: 400, Train Loss: 0.984, Val f1_micro: 0.274
Epoch: 420, Train Loss: 0.944, Val f1_micro: 0.279
Epoch: 440, Train Loss: 0.926, Val f1_micro: 0.273
Epoch: 460, Train Loss: 0.918, Val f1_micro: 0.276
Epoch: 480, Train Loss: 0.904, Val f1_micro: 0.282
Epoch: 500, Train Loss: 0.878, Val f1_micro: 0.284
f1-micro: 0.284, f1-macro: 0.277, f1-weighted: 0.281, , roc-auc: 0.664
##### RUN 2 #####
Epoch: 020, Train Loss: 2.016, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.768, Val f1_micro: 0.210
Epoch: 060, Train Loss: 1.613, Val f1_micro: 0.221
Epoch: 080, Train Loss: 1.520, Val f1_micro: 0.230
Epoch: 100, Train Loss: 1.454, Val f1_micro: 0.241
Epoch: 120, Train Loss: 1.429, Val f1_micro: 0.239
Epoch: 140, Train Loss: 1.338, Val f1_micro: 0.241
Epoch: 160, Train Loss: 1.330, Val f1_micro: 0.246
Epoch: 180, Train Loss: 1.266, Val f1_micro: 0.249
Epoch: 200, Train Loss: 1.235, Val f1_micro: 0.254
Epoch: 220, Train Loss: 1.182, Val f1_micro: 0.253
Epoch: 240, Train Loss: 1.170, Val f1_micro: 0.259
Epoch: 260, Train Loss: 1.134, Val f1_micro: 0.263
Epoch: 280, Train Loss: 1.114, Val f1_micro: 0.262
Epoch: 300, Train Loss: 1.088, Val f1_micro: 0.262
Epoch: 320, Train Loss: 1.057, Val f1_micro: 0.270
Epoch: 340, Train Loss: 1.014, Val f1_micro: 0.265
Epoch: 360, Train Loss: 1.026, Val f1_micro: 0.272
Epoch: 380, Train Loss: 0.979, Val f1_micro: 0.276
Epoch: 400, Train Loss: 0.982, Val f1_micro: 0.271
Epoch: 420, Train Loss: 0.952, Val f1_micro: 0.275
Epoch: 440, Train Loss: 0.946, Val f1_micro: 0.279
Epoch: 460, Train Loss: 0.921, Val f1_micro: 0.280
Epoch: 480, Train Loss: 0.894, Val f1_micro: 0.286
Epoch: 500, Train Loss: 0.869, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.275, f1-weighted: 0.279, , roc-auc: 0.666
##### RUN 3 #####
Epoch: 020, Train Loss: 1.986, Val f1_micro: 0.187
Epoch: 040, Train Loss: 1.758, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.615, Val f1_micro: 0.214
Epoch: 080, Train Loss: 1.530, Val f1_micro: 0.228
Epoch: 100, Train Loss: 1.478, Val f1_micro: 0.231
Epoch: 120, Train Loss: 1.414, Val f1_micro: 0.237
Epoch: 140, Train Loss: 1.353, Val f1_micro: 0.241
Epoch: 160, Train Loss: 1.279, Val f1_micro: 0.248
Epoch: 180, Train Loss: 1.257, Val f1_micro: 0.251
Epoch: 200, Train Loss: 1.223, Val f1_micro: 0.256
Epoch: 220, Train Loss: 1.196, Val f1_micro: 0.264
Epoch: 240, Train Loss: 1.138, Val f1_micro: 0.261
Epoch: 260, Train Loss: 1.129, Val f1_micro: 0.265
Epoch: 280, Train Loss: 1.082, Val f1_micro: 0.271
Epoch: 300, Train Loss: 1.073, Val f1_micro: 0.270
Epoch: 320, Train Loss: 1.043, Val f1_micro: 0.272
Epoch: 340, Train Loss: 1.027, Val f1_micro: 0.272
Epoch: 360, Train Loss: 1.029, Val f1_micro: 0.274
Epoch: 380, Train Loss: 0.981, Val f1_micro: 0.273
Epoch: 400, Train Loss: 0.976, Val f1_micro: 0.280
Epoch: 420, Train Loss: 0.938, Val f1_micro: 0.280
Epoch: 440, Train Loss: 0.935, Val f1_micro: 0.282
Epoch: 460, Train Loss: 0.933, Val f1_micro: 0.279
Epoch: 480, Train Loss: 0.918, Val f1_micro: 0.283
Epoch: 500, Train Loss: 0.910, Val f1_micro: 0.281
f1-micro: 0.281, f1-macro: 0.275, f1-weighted: 0.279, , roc-auc: 0.664
##### RUN 4 #####
Epoch: 020, Train Loss: 2.000, Val f1_micro: 0.185
Epoch: 040, Train Loss: 1.738, Val f1_micro: 0.211
Epoch: 060, Train Loss: 1.618, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.532, Val f1_micro: 0.230
Epoch: 100, Train Loss: 1.450, Val f1_micro: 0.239
Epoch: 120, Train Loss: 1.378, Val f1_micro: 0.241
Epoch: 140, Train Loss: 1.351, Val f1_micro: 0.238
Epoch: 160, Train Loss: 1.326, Val f1_micro: 0.249
Epoch: 180, Train Loss: 1.262, Val f1_micro: 0.249
Epoch: 200, Train Loss: 1.208, Val f1_micro: 0.255
Epoch: 220, Train Loss: 1.192, Val f1_micro: 0.256
Epoch: 240, Train Loss: 1.147, Val f1_micro: 0.262
Epoch: 260, Train Loss: 1.142, Val f1_micro: 0.262
Epoch: 280, Train Loss: 1.120, Val f1_micro: 0.261
Epoch: 300, Train Loss: 1.101, Val f1_micro: 0.266
Epoch: 320, Train Loss: 1.061, Val f1_micro: 0.269
Epoch: 340, Train Loss: 1.052, Val f1_micro: 0.271
Epoch: 360, Train Loss: 1.052, Val f1_micro: 0.270
Epoch: 380, Train Loss: 0.982, Val f1_micro: 0.274
Epoch: 400, Train Loss: 0.967, Val f1_micro: 0.282
Epoch: 420, Train Loss: 0.952, Val f1_micro: 0.281
Epoch: 440, Train Loss: 0.931, Val f1_micro: 0.277
Epoch: 460, Train Loss: 0.925, Val f1_micro: 0.278
Epoch: 480, Train Loss: 0.891, Val f1_micro: 0.283
Epoch: 500, Train Loss: 0.911, Val f1_micro: 0.285
f1-micro: 0.285, f1-macro: 0.280, f1-weighted: 0.284, , roc-auc: 0.665
##### RUN 5 #####
Epoch: 020, Train Loss: 1.981, Val f1_micro: 0.194
Epoch: 040, Train Loss: 1.769, Val f1_micro: 0.216
Epoch: 060, Train Loss: 1.616, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.539, Val f1_micro: 0.231
Epoch: 100, Train Loss: 1.457, Val f1_micro: 0.237
Epoch: 120, Train Loss: 1.401, Val f1_micro: 0.234
Epoch: 140, Train Loss: 1.352, Val f1_micro: 0.243
Epoch: 160, Train Loss: 1.308, Val f1_micro: 0.245
Epoch: 180, Train Loss: 1.254, Val f1_micro: 0.251
Epoch: 200, Train Loss: 1.230, Val f1_micro: 0.252
Epoch: 220, Train Loss: 1.189, Val f1_micro: 0.258
Epoch: 240, Train Loss: 1.165, Val f1_micro: 0.258
Epoch: 260, Train Loss: 1.131, Val f1_micro: 0.263
Epoch: 280, Train Loss: 1.110, Val f1_micro: 0.267
Epoch: 300, Train Loss: 1.081, Val f1_micro: 0.269
Epoch: 320, Train Loss: 1.056, Val f1_micro: 0.267
Epoch: 340, Train Loss: 1.039, Val f1_micro: 0.272
Epoch: 360, Train Loss: 1.022, Val f1_micro: 0.273
Epoch: 380, Train Loss: 0.993, Val f1_micro: 0.278
Epoch: 400, Train Loss: 0.975, Val f1_micro: 0.279
Epoch: 420, Train Loss: 0.957, Val f1_micro: 0.284
Epoch: 440, Train Loss: 0.941, Val f1_micro: 0.277
Epoch: 460, Train Loss: 0.943, Val f1_micro: 0.280
Epoch: 480, Train Loss: 0.901, Val f1_micro: 0.287
Epoch: 500, Train Loss: 0.889, Val f1_micro: 0.286
f1-micro: 0.286, f1-macro: 0.278, f1-weighted: 0.282, , roc-auc: 0.666
########## Hyperparameters combination ##########
(1024, 0.7, 0.005, 0.001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 2.004, Val f1_micro: 0.191
Epoch: 040, Train Loss: 1.778, Val f1_micro: 0.215
Epoch: 060, Train Loss: 1.637, Val f1_micro: 0.224
Epoch: 080, Train Loss: 1.579, Val f1_micro: 0.230
Epoch: 100, Train Loss: 1.512, Val f1_micro: 0.236
Epoch: 120, Train Loss: 1.476, Val f1_micro: 0.239
Epoch: 140, Train Loss: 1.409, Val f1_micro: 0.240
Epoch: 160, Train Loss: 1.395, Val f1_micro: 0.234
Epoch: 180, Train Loss: 1.370, Val f1_micro: 0.241
Epoch: 200, Train Loss: 1.347, Val f1_micro: 0.247
Epoch: 220, Train Loss: 1.319, Val f1_micro: 0.245
Epoch: 240, Train Loss: 1.307, Val f1_micro: 0.254
Epoch: 260, Train Loss: 1.273, Val f1_micro: 0.249
Epoch: 280, Train Loss: 1.278, Val f1_micro: 0.249
Epoch: 300, Train Loss: 1.257, Val f1_micro: 0.256
Epoch: 320, Train Loss: 1.232, Val f1_micro: 0.260
Epoch: 340, Train Loss: 1.192, Val f1_micro: 0.255
Epoch: 360, Train Loss: 1.219, Val f1_micro: 0.259
Epoch: 380, Train Loss: 1.202, Val f1_micro: 0.259
Epoch: 400, Train Loss: 1.196, Val f1_micro: 0.262
Epoch: 420, Train Loss: 1.164, Val f1_micro: 0.264
Epoch: 440, Train Loss: 1.152, Val f1_micro: 0.267
Epoch: 460, Train Loss: 1.118, Val f1_micro: 0.262
Epoch: 480, Train Loss: 1.124, Val f1_micro: 0.261
Epoch: 500, Train Loss: 1.133, Val f1_micro: 0.268
f1-micro: 0.268, f1-macro: 0.256, f1-weighted: 0.259, , roc-auc: 0.661
##### RUN 2 #####
Epoch: 020, Train Loss: 2.027, Val f1_micro: 0.196
Epoch: 040, Train Loss: 1.777, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.648, Val f1_micro: 0.217
Epoch: 080, Train Loss: 1.568, Val f1_micro: 0.228
Epoch: 100, Train Loss: 1.510, Val f1_micro: 0.232
Epoch: 120, Train Loss: 1.478, Val f1_micro: 0.239
Epoch: 140, Train Loss: 1.436, Val f1_micro: 0.241
Epoch: 160, Train Loss: 1.414, Val f1_micro: 0.244
Epoch: 180, Train Loss: 1.370, Val f1_micro: 0.250
Epoch: 200, Train Loss: 1.352, Val f1_micro: 0.249
Epoch: 220, Train Loss: 1.318, Val f1_micro: 0.251
Epoch: 240, Train Loss: 1.285, Val f1_micro: 0.249
Epoch: 260, Train Loss: 1.294, Val f1_micro: 0.251
Epoch: 280, Train Loss: 1.260, Val f1_micro: 0.253
Epoch: 300, Train Loss: 1.245, Val f1_micro: 0.251
Epoch: 320, Train Loss: 1.233, Val f1_micro: 0.257
Epoch: 340, Train Loss: 1.208, Val f1_micro: 0.259
Epoch: 360, Train Loss: 1.184, Val f1_micro: 0.260
Epoch: 380, Train Loss: 1.186, Val f1_micro: 0.265
Epoch: 400, Train Loss: 1.159, Val f1_micro: 0.265
Epoch: 420, Train Loss: 1.152, Val f1_micro: 0.265
Epoch: 440, Train Loss: 1.136, Val f1_micro: 0.267
Epoch: 460, Train Loss: 1.143, Val f1_micro: 0.264
Epoch: 480, Train Loss: 1.156, Val f1_micro: 0.269
Epoch: 500, Train Loss: 1.145, Val f1_micro: 0.264
f1-micro: 0.264, f1-macro: 0.255, f1-weighted: 0.258, , roc-auc: 0.663
##### RUN 3 #####
Epoch: 020, Train Loss: 2.002, Val f1_micro: 0.199
Epoch: 040, Train Loss: 1.755, Val f1_micro: 0.209
Epoch: 060, Train Loss: 1.648, Val f1_micro: 0.224
Epoch: 080, Train Loss: 1.570, Val f1_micro: 0.234
Epoch: 100, Train Loss: 1.505, Val f1_micro: 0.238
Epoch: 120, Train Loss: 1.434, Val f1_micro: 0.237
Epoch: 140, Train Loss: 1.416, Val f1_micro: 0.243
Epoch: 160, Train Loss: 1.422, Val f1_micro: 0.242
Epoch: 180, Train Loss: 1.379, Val f1_micro: 0.243
Epoch: 200, Train Loss: 1.364, Val f1_micro: 0.242
Epoch: 220, Train Loss: 1.323, Val f1_micro: 0.242
Epoch: 240, Train Loss: 1.297, Val f1_micro: 0.255
Epoch: 260, Train Loss: 1.293, Val f1_micro: 0.253
Epoch: 280, Train Loss: 1.300, Val f1_micro: 0.254
Epoch: 300, Train Loss: 1.252, Val f1_micro: 0.254
Epoch: 320, Train Loss: 1.252, Val f1_micro: 0.253
Epoch: 340, Train Loss: 1.242, Val f1_micro: 0.263
Epoch: 360, Train Loss: 1.199, Val f1_micro: 0.263
Epoch: 380, Train Loss: 1.190, Val f1_micro: 0.260
Epoch: 400, Train Loss: 1.185, Val f1_micro: 0.257
Epoch: 420, Train Loss: 1.165, Val f1_micro: 0.263
Epoch: 440, Train Loss: 1.168, Val f1_micro: 0.262
Epoch: 460, Train Loss: 1.156, Val f1_micro: 0.264
Epoch: 480, Train Loss: 1.138, Val f1_micro: 0.263
Epoch: 500, Train Loss: 1.127, Val f1_micro: 0.268
f1-micro: 0.268, f1-macro: 0.257, f1-weighted: 0.261, , roc-auc: 0.660
##### RUN 4 #####
Epoch: 020, Train Loss: 1.993, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.760, Val f1_micro: 0.213
Epoch: 060, Train Loss: 1.638, Val f1_micro: 0.224
Epoch: 080, Train Loss: 1.551, Val f1_micro: 0.231
Epoch: 100, Train Loss: 1.503, Val f1_micro: 0.236
Epoch: 120, Train Loss: 1.461, Val f1_micro: 0.242
Epoch: 140, Train Loss: 1.437, Val f1_micro: 0.245
Epoch: 160, Train Loss: 1.411, Val f1_micro: 0.241
Epoch: 180, Train Loss: 1.372, Val f1_micro: 0.245
Epoch: 200, Train Loss: 1.356, Val f1_micro: 0.248
Epoch: 220, Train Loss: 1.322, Val f1_micro: 0.244
Epoch: 240, Train Loss: 1.308, Val f1_micro: 0.249
Epoch: 260, Train Loss: 1.280, Val f1_micro: 0.253
Epoch: 280, Train Loss: 1.256, Val f1_micro: 0.254
Epoch: 300, Train Loss: 1.234, Val f1_micro: 0.257
Epoch: 320, Train Loss: 1.217, Val f1_micro: 0.257
Epoch: 340, Train Loss: 1.224, Val f1_micro: 0.261
Epoch: 360, Train Loss: 1.209, Val f1_micro: 0.258
Epoch: 380, Train Loss: 1.196, Val f1_micro: 0.259
Epoch: 400, Train Loss: 1.161, Val f1_micro: 0.263
Epoch: 420, Train Loss: 1.164, Val f1_micro: 0.265
Epoch: 440, Train Loss: 1.158, Val f1_micro: 0.263
Epoch: 460, Train Loss: 1.144, Val f1_micro: 0.267
Epoch: 480, Train Loss: 1.158, Val f1_micro: 0.266
Epoch: 500, Train Loss: 1.115, Val f1_micro: 0.269
f1-micro: 0.269, f1-macro: 0.260, f1-weighted: 0.262, , roc-auc: 0.663
##### RUN 5 #####
Epoch: 020, Train Loss: 2.036, Val f1_micro: 0.192
Epoch: 040, Train Loss: 1.733, Val f1_micro: 0.209
Epoch: 060, Train Loss: 1.646, Val f1_micro: 0.220
Epoch: 080, Train Loss: 1.573, Val f1_micro: 0.233
Epoch: 100, Train Loss: 1.522, Val f1_micro: 0.230
Epoch: 120, Train Loss: 1.472, Val f1_micro: 0.237
Epoch: 140, Train Loss: 1.423, Val f1_micro: 0.245
Epoch: 160, Train Loss: 1.404, Val f1_micro: 0.240
Epoch: 180, Train Loss: 1.371, Val f1_micro: 0.242
Epoch: 200, Train Loss: 1.352, Val f1_micro: 0.242
Epoch: 220, Train Loss: 1.326, Val f1_micro: 0.251
Epoch: 240, Train Loss: 1.312, Val f1_micro: 0.245
Epoch: 260, Train Loss: 1.277, Val f1_micro: 0.249
Epoch: 280, Train Loss: 1.261, Val f1_micro: 0.256
Epoch: 300, Train Loss: 1.243, Val f1_micro: 0.254
Epoch: 320, Train Loss: 1.228, Val f1_micro: 0.257
Epoch: 340, Train Loss: 1.218, Val f1_micro: 0.256
Epoch: 360, Train Loss: 1.188, Val f1_micro: 0.258
Epoch: 380, Train Loss: 1.193, Val f1_micro: 0.259
Epoch: 400, Train Loss: 1.160, Val f1_micro: 0.262
Epoch: 420, Train Loss: 1.184, Val f1_micro: 0.264
Epoch: 440, Train Loss: 1.165, Val f1_micro: 0.267
Epoch: 460, Train Loss: 1.133, Val f1_micro: 0.260
Epoch: 480, Train Loss: 1.141, Val f1_micro: 0.265
Epoch: 500, Train Loss: 1.140, Val f1_micro: 0.264
f1-micro: 0.264, f1-macro: 0.256, f1-weighted: 0.259, , roc-auc: 0.663
########## Hyperparameters combination ##########
(1024, 0.7, 0.005, 0.005)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.966, Val f1_micro: 0.202
Epoch: 040, Train Loss: 1.787, Val f1_micro: 0.204
Epoch: 060, Train Loss: 1.745, Val f1_micro: 0.211
Epoch: 080, Train Loss: 1.723, Val f1_micro: 0.220
Epoch: 100, Train Loss: 1.733, Val f1_micro: 0.211
Epoch: 120, Train Loss: 1.723, Val f1_micro: 0.218
Epoch: 140, Train Loss: 1.741, Val f1_micro: 0.213
Epoch: 160, Train Loss: 1.741, Val f1_micro: 0.209
Epoch: 180, Train Loss: 1.743, Val f1_micro: 0.217
Epoch: 200, Train Loss: 1.743, Val f1_micro: 0.222
Epoch: 220, Train Loss: 1.766, Val f1_micro: 0.222
Epoch: 240, Train Loss: 1.749, Val f1_micro: 0.213
Epoch: 260, Train Loss: 1.769, Val f1_micro: 0.215
Epoch: 280, Train Loss: 1.761, Val f1_micro: 0.213
Epoch: 300, Train Loss: 1.758, Val f1_micro: 0.211
Epoch: 320, Train Loss: 1.768, Val f1_micro: 0.202
Epoch: 340, Train Loss: 1.765, Val f1_micro: 0.209
Epoch: 360, Train Loss: 1.770, Val f1_micro: 0.205
Epoch: 380, Train Loss: 1.759, Val f1_micro: 0.207
Epoch: 400, Train Loss: 1.758, Val f1_micro: 0.209
Epoch: 420, Train Loss: 1.773, Val f1_micro: 0.210
Epoch: 440, Train Loss: 1.776, Val f1_micro: 0.205
Epoch: 460, Train Loss: 1.778, Val f1_micro: 0.200
Epoch: 480, Train Loss: 1.764, Val f1_micro: 0.211
Epoch: 500, Train Loss: 1.754, Val f1_micro: 0.211
f1-micro: 0.211, f1-macro: 0.181, f1-weighted: 0.178, , roc-auc: 0.637
##### RUN 2 #####
Epoch: 020, Train Loss: 1.990, Val f1_micro: 0.189
Epoch: 040, Train Loss: 1.804, Val f1_micro: 0.209
Epoch: 060, Train Loss: 1.746, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.743, Val f1_micro: 0.225
Epoch: 100, Train Loss: 1.743, Val f1_micro: 0.216
Epoch: 120, Train Loss: 1.735, Val f1_micro: 0.215
Epoch: 140, Train Loss: 1.734, Val f1_micro: 0.200
Epoch: 160, Train Loss: 1.735, Val f1_micro: 0.221
Epoch: 180, Train Loss: 1.731, Val f1_micro: 0.216
Epoch: 200, Train Loss: 1.740, Val f1_micro: 0.214
Epoch: 220, Train Loss: 1.752, Val f1_micro: 0.213
Epoch: 240, Train Loss: 1.750, Val f1_micro: 0.214
Epoch: 260, Train Loss: 1.775, Val f1_micro: 0.220
Epoch: 280, Train Loss: 1.758, Val f1_micro: 0.218
Epoch: 300, Train Loss: 1.761, Val f1_micro: 0.215
Epoch: 320, Train Loss: 1.753, Val f1_micro: 0.214
Epoch: 340, Train Loss: 1.763, Val f1_micro: 0.218
Epoch: 360, Train Loss: 1.760, Val f1_micro: 0.216
Epoch: 380, Train Loss: 1.765, Val f1_micro: 0.208
Epoch: 400, Train Loss: 1.760, Val f1_micro: 0.211
Epoch: 420, Train Loss: 1.775, Val f1_micro: 0.210
Epoch: 440, Train Loss: 1.773, Val f1_micro: 0.207
Epoch: 460, Train Loss: 1.766, Val f1_micro: 0.214
Epoch: 480, Train Loss: 1.753, Val f1_micro: 0.210
Epoch: 500, Train Loss: 1.772, Val f1_micro: 0.214
f1-micro: 0.214, f1-macro: 0.176, f1-weighted: 0.173, , roc-auc: 0.636
##### RUN 3 #####
Epoch: 020, Train Loss: 1.965, Val f1_micro: 0.201
Epoch: 040, Train Loss: 1.801, Val f1_micro: 0.217
Epoch: 060, Train Loss: 1.762, Val f1_micro: 0.213
Epoch: 080, Train Loss: 1.725, Val f1_micro: 0.213
Epoch: 100, Train Loss: 1.720, Val f1_micro: 0.218
Epoch: 120, Train Loss: 1.745, Val f1_micro: 0.221
Epoch: 140, Train Loss: 1.734, Val f1_micro: 0.216
Epoch: 160, Train Loss: 1.731, Val f1_micro: 0.216
Epoch: 180, Train Loss: 1.743, Val f1_micro: 0.218
Epoch: 200, Train Loss: 1.748, Val f1_micro: 0.218
Epoch: 220, Train Loss: 1.740, Val f1_micro: 0.215
Epoch: 240, Train Loss: 1.775, Val f1_micro: 0.212
Epoch: 260, Train Loss: 1.752, Val f1_micro: 0.212
Epoch: 280, Train Loss: 1.754, Val f1_micro: 0.215
Epoch: 300, Train Loss: 1.760, Val f1_micro: 0.216
Epoch: 320, Train Loss: 1.769, Val f1_micro: 0.215
Epoch: 340, Train Loss: 1.761, Val f1_micro: 0.207
Epoch: 360, Train Loss: 1.767, Val f1_micro: 0.199
Epoch: 380, Train Loss: 1.776, Val f1_micro: 0.213
Epoch: 400, Train Loss: 1.778, Val f1_micro: 0.218
Epoch: 420, Train Loss: 1.764, Val f1_micro: 0.210
Epoch: 440, Train Loss: 1.760, Val f1_micro: 0.209
Epoch: 460, Train Loss: 1.772, Val f1_micro: 0.211
Epoch: 480, Train Loss: 1.770, Val f1_micro: 0.210
Epoch: 500, Train Loss: 1.774, Val f1_micro: 0.211
f1-micro: 0.211, f1-macro: 0.176, f1-weighted: 0.175, , roc-auc: 0.636
##### RUN 4 #####
Epoch: 020, Train Loss: 2.019, Val f1_micro: 0.195
Epoch: 040, Train Loss: 1.800, Val f1_micro: 0.210
Epoch: 060, Train Loss: 1.745, Val f1_micro: 0.213
Epoch: 080, Train Loss: 1.736, Val f1_micro: 0.220
Epoch: 100, Train Loss: 1.739, Val f1_micro: 0.218
Epoch: 120, Train Loss: 1.728, Val f1_micro: 0.222
Epoch: 140, Train Loss: 1.746, Val f1_micro: 0.217
Epoch: 160, Train Loss: 1.726, Val f1_micro: 0.218
Epoch: 180, Train Loss: 1.745, Val f1_micro: 0.208
Epoch: 200, Train Loss: 1.753, Val f1_micro: 0.220
Epoch: 220, Train Loss: 1.761, Val f1_micro: 0.218
Epoch: 240, Train Loss: 1.762, Val f1_micro: 0.212
Epoch: 260, Train Loss: 1.762, Val f1_micro: 0.216
Epoch: 280, Train Loss: 1.774, Val f1_micro: 0.213
Epoch: 300, Train Loss: 1.770, Val f1_micro: 0.209
Epoch: 320, Train Loss: 1.764, Val f1_micro: 0.208
Epoch: 340, Train Loss: 1.767, Val f1_micro: 0.206
Epoch: 360, Train Loss: 1.772, Val f1_micro: 0.204
Epoch: 380, Train Loss: 1.773, Val f1_micro: 0.209
Epoch: 400, Train Loss: 1.773, Val f1_micro: 0.205
Epoch: 420, Train Loss: 1.778, Val f1_micro: 0.212
Epoch: 440, Train Loss: 1.776, Val f1_micro: 0.209
Epoch: 460, Train Loss: 1.768, Val f1_micro: 0.204
Epoch: 480, Train Loss: 1.765, Val f1_micro: 0.211
Epoch: 500, Train Loss: 1.779, Val f1_micro: 0.205
f1-micro: 0.205, f1-macro: 0.162, f1-weighted: 0.157, , roc-auc: 0.637
##### RUN 5 #####
Epoch: 020, Train Loss: 2.002, Val f1_micro: 0.202
Epoch: 040, Train Loss: 1.799, Val f1_micro: 0.209
Epoch: 060, Train Loss: 1.749, Val f1_micro: 0.219
Epoch: 080, Train Loss: 1.737, Val f1_micro: 0.224
Epoch: 100, Train Loss: 1.718, Val f1_micro: 0.222
Epoch: 120, Train Loss: 1.732, Val f1_micro: 0.218
Epoch: 140, Train Loss: 1.729, Val f1_micro: 0.218
Epoch: 160, Train Loss: 1.741, Val f1_micro: 0.220
Epoch: 180, Train Loss: 1.748, Val f1_micro: 0.219
Epoch: 200, Train Loss: 1.754, Val f1_micro: 0.218
Epoch: 220, Train Loss: 1.736, Val f1_micro: 0.215
Epoch: 240, Train Loss: 1.759, Val f1_micro: 0.213
Epoch: 260, Train Loss: 1.758, Val f1_micro: 0.210
Epoch: 280, Train Loss: 1.766, Val f1_micro: 0.207
Epoch: 300, Train Loss: 1.762, Val f1_micro: 0.213
Epoch: 320, Train Loss: 1.763, Val f1_micro: 0.214
Epoch: 340, Train Loss: 1.761, Val f1_micro: 0.214
Epoch: 360, Train Loss: 1.775, Val f1_micro: 0.214
Epoch: 380, Train Loss: 1.760, Val f1_micro: 0.213
Epoch: 400, Train Loss: 1.767, Val f1_micro: 0.207
Epoch: 420, Train Loss: 1.775, Val f1_micro: 0.208
Epoch: 440, Train Loss: 1.769, Val f1_micro: 0.215
Epoch: 460, Train Loss: 1.769, Val f1_micro: 0.211
Epoch: 480, Train Loss: 1.763, Val f1_micro: 0.212
Epoch: 500, Train Loss: 1.766, Val f1_micro: 0.207
f1-micro: 0.207, f1-macro: 0.181, f1-weighted: 0.178, , roc-auc: 0.637
########## Hyperparameters combination ##########
(1024, 0.7, 0.01, 0.0001)
##########

/tmp/ipykernel_4879/1398315810.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author', 'id_j':'paper'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'author_id', 'id_j':'institution_id'}, inplace=True)
/tmp/ipykernel_4879/1398315810.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_r.rename(columns={'id_i': 'citing', 'id_j':'cited'}, inplace=True)

online shape torch.Size([189])
unchanged shape torch.Size([189])
final shape torch.Size([378])
##### RUN 1 #####
Epoch: 020, Train Loss: 1.924, Val f1_micro: 0.179
Epoch: 040, Train Loss: 1.684, Val f1_micro: 0.212
Epoch: 060, Train Loss: 1.563, Val f1_micro: 0.236
Epoch: 080, Train Loss: 1.413, Val f1_micro: 0.243
Epoch: 100, Train Loss: 1.315, Val f1_micro: 0.249
Epoch: 120, Train Loss: 1.246, Val f1_micro: 0.251
Epoch: 140, Train Loss: 1.162, Val f1_micro: 0.254
Epoch: 160, Train Loss: 1.084, Val f1_micro: 0.260
Epoch: 180, Train Loss: 1.015, Val f1_micro: 0.267
Epoch: 200, Train Loss: 0.964, Val f1_micro: 0.273
Epoch: 220, Train Loss: 0.897, Val f1_micro: 0.279
Epoch: 240, Train Loss: 0.845, Val f1_micro: 0.283
Epoch: 260, Train Loss: 0.781, Val f1_micro: 0.285
Epoch: 280, Train Loss: 0.770, Val f1_micro: 0.287
Epoch: 300, Train Loss: 0.719, Val f1_micro: 0.292
Epoch: 320, Train Loss: 0.679, Val f1_micro: 0.292
Epoch: 340, Train Loss: 0.610, Val f1_micro: 0.296
Epoch: 360, Train Loss: 0.585, Val f1_micro: 0.296
Epoch: 380, Train Loss: 0.553, Val f1_micro: 0.297
Epoch: 400, Train Loss: 0.513, Val f1_micro: 0.296
Epoch: 420, Train Loss: 0.504, Val f1_micro: 0.301
Epoch: 440, Train Loss: 0.517, Val f1_micro: 0.298
Epoch: 460, Train Loss: 0.457, Val f1_micro: 0.299
Epoch: 480, Train Loss: 0.453, Val f1_micro: 0.302
Epoch: 500, Train Loss: 0.438, Val f1_micro: 0.301
f1-micro: 0.301, f1-macro: 0.296, f1-weighted: 0.301, , roc-auc: 0.669
##### RUN 2 #####
Epoch: 020, Train Loss: 1.917, Val f1_micro: 0.171
Epoch: 040, Train Loss: 1.684, Val f1_micro: 0.214
Epoch: 060, Train Loss: 1.530, Val f1_micro: 0.234
Epoch: 080, Train Loss: 1.425, Val f1_micro: 0.239
Epoch: 100, Train Loss: 1.324, Val f1_micro: 0.243
Epoch: 120, Train Loss: 1.241, Val f1_micro: 0.251
Epoch: 140, Train Loss: 1.168, Val f1_micro: 0.258
Epoch: 160, Train Loss: 1.072, Val f1_micro: 0.262
Epoch: 180, Train Loss: 1.031, Val f1_micro: 0.269

In [8]:
import pandas as pd
from itertools import product

#salva in DATA tutte le possibili combinazioni di parametri come df 
#(per ogni row una colonna con tupla combinazione)

hyperparameters = {
    'B_size':[768, 2048, 256], #512 tutti e 80, 1024 ne mancano 7
    'dropout':[0.3, 0.4, 0.5, 0.6, 0.7],
    'lr': [0.001, 0.005, 0.01, 0.05],
    'L2': [0.0001, 0.0005, 0.001, 0.005]
}

param_combinations = product(*hyperparameters.values())
param_conbinations_list = [params for params in param_combinations]
df = pd.DataFrame(columns=['Params'])
df['Params'] = param_conbinations_list
df.to_csv(fname_base+new+'params.csv', index=False)
df.head(5)

                      Params
0  (768, 0.3, 0.001, 0.0001)
1  (768, 0.3, 0.001, 0.0005)
2   (768, 0.3, 0.001, 0.001)
3   (768, 0.3, 0.001, 0.005)
4  (768, 0.3, 0.005, 0.0001)

In [41]:
#estract combinations not processed
from itertools import product
import pandas as pd
fname_base = 'DyHANE/'

df1 = pd.read_csv(fname_base+'params_scores.csv')
print('Processed 1:', df1.shape[0])
df2 = pd.read_csv(fname_base+'params_scores_old.csv')
print('Processed 2:', df2.shape[0])
df2.rename(columns={'F1-micro':'F1_micro', 'F1-macro':'F1_macro', 'F1-weighted':'F1_weighted'}, inplace=True)
df = pd.concat([df1, df2], axis=0)#ignore_index=True
params_ok = df['Params'].tolist()
print('Already processed:',len(params_ok))
#print(params_ok[:10])


hyperparameters = {
    'B_size':[512, 2024], #768, 2048, 256
    'dropout':[0.3, 0.4, 0.5, 0.6, 0.7],
    'lr': [0.001, 0.005, 0.01, 0.05],
    'L2': [0.0001, 0.0005, 0.001, 0.005]
}

param_combinations = product(*hyperparameters.values())
param_combinations_list = [str(params) for params in param_combinations]
print('To check:',len(param_combinations_list))
print(param_combinations_list[:10])

#devono essere 7
params_to_process = [params for params in param_combinations_list if params not in params_ok]
print('To process',len(params_to_process))
print(params_to_process[:10])

To check: 160
['(512, 0.3, 0.001, 0.0001)', '(512, 0.3, 0.001, 0.0005)', '(512, 0.3, 0.001, 0.001)', '(512, 0.3, 0.001, 0.005)', '(512, 0.3, 0.005, 0.0001)', '(512, 0.3, 0.005, 0.0005)', '(512, 0.3, 0.005, 0.001)', '(512, 0.3, 0.005, 0.005)', '(512, 0.3, 0.01, 0.0001)', '(512, 0.3, 0.01, 0.0005)']
To process 80
['(2024, 0.3, 0.001, 0.0001)', '(2024, 0.3, 0.001, 0.0005)', '(2024, 0.3, 0.001, 0.001)', '(2024, 0.3, 0.001, 0.005)', '(2024, 0.3, 0.005, 0.0001)', '(2024, 0.3, 0.005, 0.0005)', '(2024, 0.3, 0.005, 0.001)', '(2024, 0.3, 0.005, 0.005)', '(2024, 0.3, 0.01, 0.0001)', '(2024, 0.3, 0.01, 0.0005)']

In [42]:
#check
import pandas as pd

def split_params(params):
    params = params[1:-1]
    params_list = params.split(', ')
    return params_list[0], params_list[1], params_list[2], params_list[3]

df1 = pd.read_csv(fname_base+'params_scores.csv')
#print('Processed 1:', df1.shape[0])
df2 = pd.read_csv(fname_base+'params_scores_old.csv')
#print('Processed 2:', df2.shape[0])
df2.rename(columns={'F1-micro':'F1_micro', 'F1-macro':'F1_macro', 'F1-weighted':'F1_weighted'}, inplace=True)
df = pd.concat([df1, df2], axis=0)#ignore_index=True

new_columns = df2['Params'].apply(split_params)
new_column_names = ['B_size', 'dropout', 'lr', 'L2']

for i, col_name in enumerate(new_column_names):
    df[col_name] = [res[i] for res in new_columns]

B_size = '1024' #153, '512' invece 0

# Count the number of rows matching the specified value for the specified column
count = (df2['B_size'] == B_size).sum()
print(count)

ValueError: Length of values (152) does not match length of index (392)

In [25]:
#RUN QUESTO (8)

from tqdm import tqdm
import pandas as pd


PATH_SAVE=fname_base+'params_scores_others.csv' #params_scores.csv


path=fname_base+new+'params_others.csv' #params.csv
DATA=pd.read_csv(path) 

DATA=DATA.to_dict(orient="records")

In [26]:
#RUN QUESTO (9)

from itertools import product

# Example usage:
# Assuming you have a model called 'model' and hyperparameters defined as a dictionary
# hyperparameters = {'param1': [value1, value2, ...], 'param2': [value1, value2, ...], ...}

def train_node_classifier(model, data, optimizer, criterion, n_epochs=200): 

    for epoch in range(1, n_epochs + 1):
        model.train()
        optimizer.zero_grad()
        out = model(data.x_dict, data.edge_index_dict)
        mask = data['author'].train_mask
        loss = criterion(out['author'][mask], data['author'].y[mask]) 
        loss.backward()
        optimizer.step()
        pred = out['author'].argmax(dim=1) ## Use the class with highest probability
        f1_micro, f1_macro, f1_weigh, auc = eval_node_classifier(model, data) 
        '''if epoch % 20 == 0:
            print(f'Epoch: {epoch:03d}, Train Loss: {loss:.3f}, Val f1_micro: {f1_micro:.3f}')'''
    return model


def eval_node_classifier(model, data):

    model.eval()
    with torch.no_grad(): 
        pred = model(data.x_dict, data.edge_index_dict)['author'].argmax(dim=-1)
        pred_prob = torch.nn.functional.softmax(model(data.x_dict, data.edge_index_dict)['author'], -1)
        mask = data['author'].val_mask
        correct = (pred[mask] == data['author'].y[mask]).sum()
        f1_micro = f1_score(data['author'].y.cpu(), pred.cpu(), average='micro')
        f1_macro = f1_score(data['author'].y.cpu(), pred.cpu(), average='macro')
        f1_weigh = f1_score(data['author'].y.cpu(), pred.cpu(), average='weighted')
        #servono predicted probabilities, 8 classes
        auc = roc_auc_score(data['author'].y.cpu(), pred_prob.cpu().detach().numpy(), average='macro', multi_class='ovo')
        return f1_micro, f1_macro, f1_weigh, auc
    

def grid_search(params):
    
    print('########## Hyperparameters combination ##########')
    print(params)
    print('##########')
    params = params[1:-1]
    I = pickle.load(open(fname_base+new+'I.pkl', 'rb'))
    B = pickle.load(open(fname_base+base+'B_'+str(params.split(', ')[0])+'.pkl', 'rb')) #params[0] --> 'B_size'
    df_events = pd.read_csv(fname_base+new+'events_edges.csv') #openalex_id_i, openalex_id_j, id_i, id_j, r_type
    scenario = 'C+U' #'C'
    new_data = generate_new_heterodata(I, B, df_events, scenario)

    num_run = 5
    l_micro = []
    l_macro = []
    l_weigh = []
    l_auc = []
    for run in range(num_run):
        #print('##### RUN '+str((run+1))+' #####')

        model = None
        model = GAT(hidden_channels=64, out_channels=8, dropout=float(params.split(', ')[1])) #params[1] --> 'dropout'
        model = to_hetero(model, new_data.metadata(), aggr='sum')

        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        new_data, model = new_data.to(device), model.to(device)

        model = load_model(64,8,float(params.split(', ')[1]), new_data,fname_base+base+'base_model.pth') #params[1] --> 'dropout'

        optimizer = torch.optim.Adam(model.parameters(), lr=float(params.split(', ')[2]), weight_decay=float(params.split(', ')[3])) #params[2] --> lr, params[3] --> L2
        weights = torch.tensor([2, 2, 1, 1.5, 1.5, 1, 2, 1]).float().to(device)
        criterion = nn.CrossEntropyLoss(weights) 

        model = train_node_classifier(model, new_data, optimizer, criterion, n_epochs=500) 

        torch.save(model.state_dict(), fname_base+new+'model_dyhane_B'+str(params.split(', ')[0])+'_run'+str(run+1)+'_old_new.pth') #params[0] --> 'B_size'

        f1_micro, f1_macro, f1_weigh, auc = eval_node_classifier(model, new_data) 
        #print(f'f1-micro: {f1_micro:.3f}, f1-macro: {f1_macro:.3f}, f1-weighted: {f1_weigh:.3f}, , roc-auc: {auc:.3f}')

        l_micro.append(f1_micro)
        l_macro.append(f1_macro)
        l_weigh.append(f1_weigh)
        l_auc.append(auc)

    df = pd.DataFrame(columns=['F1_micro', 'F1_macro', 'F1_weighted', 'ROC-AUC'])
    df['F1_micro'] = l_micro
    df['F1_macro'] = l_macro
    df['F1_weighted'] = l_weigh
    df['ROC-AUC'] = l_auc
    df_ok = processing_results(df)
    #df_ok.to_excel(fname_base+new+'results_dyhane_B'+str(params[0])+'_old_new.xlsx', index=False) #params[0] --> 'B_size'

    #score = df_ok['F1_micro'].mean() #F1 micro
    f1_micro_tot = df_ok['F1_micro'].iloc[-1] #float(df_ok['F1_micro'].iloc[-1].split('±')[0])
    f1_macro_tot = df_ok['F1_macro'].iloc[-1]
    f1_weigh_tot = df_ok['F1_weighted'].iloc[-1]
    roc_auc_tot = df_ok['ROC-AUC'].iloc[-1]

    #print(f'f1-micro: {f1_micro_tot:.3f}, f1-macro: {f1_macro_tot:.3f}, f1-weighted: {f1_weigh_tot:.3f}, , roc-auc: {roc_auc_tot:.3f}')
    print('f1-micro:', f1_micro_tot, 'f1-macro:', f1_macro_tot, 'f1-weighted:', f1_weigh_tot, 'roc-auc:', roc_auc_tot)

    return [f1_micro_tot, f1_macro_tot, f1_weigh_tot, roc_auc_tot]

In [27]:
#RUN QUESTO (10)

pd.set_option('mode.chained_assignment', None)

if os.path.exists(PATH_SAVE):
    NEW_DATA=pd.read_csv(PATH_SAVE).to_dict(orient="records")
else:
    NEW_DATA=[]

for row in tqdm(DATA[len(NEW_DATA):]):

    params = row['Params']
    scores = grid_search(params)

    record={
        "Params":params,
        "F1_micro":scores[0],
        "F1_macro":scores[1],
        "F1_weighted":scores[2],
        "ROC-AUC":scores[3]
    }
    NEW_DATA.append(record)
    if len(NEW_DATA)%5==0:
        pd.DataFrame().from_records(NEW_DATA).to_csv(PATH_SAVE,index=False)

pd.DataFrame().from_records(NEW_DATA).to_csv(PATH_SAVE,index=False)

  0%|          | 0/8 [00:00<?, ?it/s]

########## Hyperparameters combination ##########
(1024, 0.7, 0.01, 0.0001)
##########

 12%|█▎        | 1/8 [05:57<41:43, 357.61s/it]

f1-micro: 0.3031±0.0013 f1-macro: 0.2977±0.0015 f1-weighted: 0.3027±0.0013 roc-auc: 0.6691±0.0015
########## Hyperparameters combination ##########
(1024, 0.7, 0.01, 0.0005)
##########

 25%|██▌       | 2/8 [11:59<35:59, 359.99s/it]

f1-micro: 0.2908±0.0014 f1-macro: 0.2848±0.0018 f1-weighted: 0.2896±0.0016 roc-auc: 0.6680±0.0009
########## Hyperparameters combination ##########
(1024, 0.7, 0.01, 0.001)
##########

 38%|███▊      | 3/8 [17:57<29:55, 359.16s/it]

f1-micro: 0.2727±0.0025 f1-macro: 0.2654±0.0022 f1-weighted: 0.2684±0.0022 roc-auc: 0.6613±0.0017
########## Hyperparameters combination ##########
(1024, 0.7, 0.01, 0.005)
##########

 50%|█████     | 4/8 [23:58<24:00, 360.11s/it]

f1-micro: 0.2049±0.0028 f1-macro: 0.1753±0.0047 f1-weighted: 0.1721±0.0051 roc-auc: 0.6371±0.0010
########## Hyperparameters combination ##########
(1024, 0.7, 0.05, 0.0001)
##########

 62%|██████▎   | 5/8 [29:59<18:01, 360.41s/it]

f1-micro: 0.2102±0.0076 f1-macro: 0.2007±0.0101 f1-weighted: 0.1984±0.0123 roc-auc: 0.6121±0.0039
########## Hyperparameters combination ##########
(1024, 0.7, 0.05, 0.0005)
##########

 75%|███████▌  | 6/8 [36:00<12:00, 360.39s/it]

f1-micro: 0.2182±0.0070 f1-macro: 0.2054±0.0076 f1-weighted: 0.2029±0.0083 roc-auc: 0.6309±0.0020
########## Hyperparameters combination ##########
(1024, 0.7, 0.05, 0.001)
##########

 88%|████████▊ | 7/8 [42:00<06:00, 360.45s/it]

f1-micro: 0.2078±0.0033 f1-macro: 0.1925±0.0050 f1-weighted: 0.1901±0.0059 roc-auc: 0.6281±0.0026
########## Hyperparameters combination ##########
(1024, 0.7, 0.05, 0.005)
##########

100%|██████████| 8/8 [48:11<00:00, 361.44s/it]

f1-micro: 0.1797±0.0065 f1-macro: 0.1352±0.0119 f1-weighted: 0.1309±0.0113 roc-auc: 0.6202±0.0018

In [7]:
#Stupid test to check masking

import random

mask_A = torch.zeros(10, dtype=torch.bool)
indices_A = [0, 3, 4, 5, 8]
mask_A[indices_A] = 1
print('mask A:', mask_A)
   
indices_test = torch.tensor([0, 1, 2, 3])
mask_test = torch.zeros(10, dtype=torch.bool)
mask_test[indices_test] = 1
print('mask test:', mask_test)
mask_test_opp = ~mask_test
print('opposite of mask test:', mask_test_opp)

init_test_mask = torch.logical_and(mask_A, mask_test)
print('final test mask:', init_test_mask)
init_train_mask = torch.logical_and(mask_A, mask_test_opp)
print('init train mask:', init_train_mask)
init_val_mask = torch.logical_and(mask_A, mask_test_opp)
print('init val mask:', init_val_mask)

true_indices_val = torch.masked_select(torch.arange(10), init_val_mask) #tutti indici true di val
sampled_indices = true_indices_val[torch.randperm(true_indices_val.shape[0])[:2]] #prendo 500 valori a caso (sono gli indici che rimarrano True qui e diventeranno False in train_mask)
mask_val = torch.zeros(10, dtype=torch.bool)
mask_val[sampled_indices] = 1
val_mask = torch.logical_and(init_val_mask, mask_val)
print('final val mask:', val_mask)
mask_train = ~mask_val
train_mask = torch.logical_and(init_train_mask, mask_train)
print('final train mask:', train_mask)

mask A: tensor([ True, False, False,  True,  True,  True, False, False,  True, False])
mask test: tensor([ True,  True,  True,  True, False, False, False, False, False, False])
opposite of mask test: tensor([False, False, False, False,  True,  True,  True,  True,  True,  True])
final test mask: tensor([ True, False, False,  True, False, False, False, False, False, False])
init train mask: tensor([False, False, False, False,  True,  True, False, False,  True, False])
init val mask: tensor([False, False, False, False,  True,  True, False, False,  True, False])
final val mask: tensor([False, False, False, False, False,  True, False, False,  True, False])
final train mask: tensor([False, False, False, False,  True, False, False, False, False, False])

In [31]:
#CASO ONLINE: solo edges in new e risp. nodes


#loading X and Y tensors
AX = torch.load(fname_base+new+'features/AX_tensor_2019-2022.pt') 
AY = torch.load(fname_base+new+'features/AY_tensor_2019-2022.pt')
PX = torch.load(fname_base+new+'features/PX_tensor_2019-2022.pt')
IX = torch.load(fname_base+new+'features/IX_tensor_2019-2022.pt')

#PCA
dim=128
pca_author=PCA(n_components=dim).fit(AX)
pca_paper=PCA(n_components=dim).fit(PX)
pca_institution=PCA(n_components=dim).fit(IX)

#create edge list
AP = pd.read_csv(fname_base+new+'AP_map.csv')[['author', 'paper']] 
AP_tensor = torch.tensor(AP.values.T)
PA = pd.read_csv(fname_base+new+'AP_map.csv')[['paper', 'author']]
PA_tensor = torch.tensor(PA.values.T)
PP = pd.read_csv(fname_base+new+'PP_map.csv')[['citing', 'cited']]
PP_tensor = torch.tensor(PP.values.T)
PP_rev = pd.read_csv(fname_base+new+'PP_map.csv')[['cited', 'citing']]
PP_rev_tensor = torch.tensor(PP_rev.values.T)
AI = pd.read_csv(fname_base+new+'AI_map.csv')
AI_tensor = torch.tensor(AI.values.T)
IA = AI[['institution_id', 'author_id']]
IA_tensor = torch.tensor(IA.values.T)

new_data = HeteroData()

filter_nan=lambda x:x[:,torch.logical_not(x.isnan().long().sum(axis=0).bool())]

new_data['author'].x = torch.tensor(pca_author.transform(AX)).float()# qui
new_data['author'].y = AY.long()
new_data['paper'].x = torch.tensor(pca_paper.transform(PX)).float()
new_data['institution'].x = torch.tensor(pca_institution.transform(IX)).float()
new_data['author', 'writes', 'paper'].edge_index = AP_tensor.long()
new_data['paper', 'is_written_by', 'author'].edge_index = PA_tensor.long()
new_data['paper', 'cites', 'paper'].edge_index = PP_tensor.long()
new_data['paper', 'is_cited_by', 'paper'].edge_index = PP_rev_tensor.long()
new_data['author', 'is_affiliated_with', 'institution'].edge_index = filter_nan(AI_tensor).long()
new_data['institution', 'has_affiliated', 'author'].edge_index = filter_nan(IA_tensor).long()

#add meta-paths
metapaths = [[('author', 'paper'), ('paper', 'author')], #APA
        [('author', 'paper'), ('paper', 'is_cited_by', 'paper'), ('paper', 'author')], #APPA
        [('author', 'institution'), ('institution', 'author')]] #AIA
new_data = AddMetaPaths(metapaths, weighted=True)(new_data)

# transform: train-test split + index to mask
transform = T.RandomNodeSplit()
new_data = transform(new_data)

mask_A = torch.zeros(AX.shape[0], dtype=torch.bool)
#sono gli indici degli A nei nuovi AP + nei nuovi AI. Che poi sarebbe solo la differenza degli AX
indices_A = list(set(AP['author'].tolist()+AI['author_id'].tolist())) #indices_to_keep(I, B, 'authors') 
mask_A[indices_A] = 1
new_data['author'].train_mask = torch.logical_and(new_data['author'].train_mask, mask_A) #T.IndexToMask(indices_A)
new_data['author'].val_mask = torch.logical_and(new_data['author'].val_mask, mask_A)
new_data['author'].test_mask = torch.logical_and(new_data['author'].test_mask, mask_A)

mask_I = torch.zeros(IX.shape[0], dtype=torch.bool)
#sono gli indici degli I nei nuovi AI
indices_I = AI['institution_id'].drop_duplicates().tolist()#indices_to_keep(I, B, 'institutions') 
mask_I[indices_I] = 1
new_data['institution'].train_mask = mask_I

mask_P = torch.zeros(PX.shape[0], dtype=torch.bool)
#sono gli indici dei P nei nuovi AP + nei nuovi PP
indices_P = list(set(AP['paper'].tolist()+PP['citing'].tolist()+PP['cited'].tolist()))#indices_to_keep(I, B, 'papers') 
mask_P[indices_P] = 1
new_data['paper'].train_mask = mask_P

print(new_data)

HeteroData(
  metapath_dict={
    (author, metapath_0, author)=[2],
    (author, metapath_1, author)=[3],
    (author, metapath_2, author)=[2],
  },
  author={
    x=[15397, 128],
    y=[15397],
    train_mask=[15397],
    val_mask=[15397],
    test_mask=[15397],
  },
  paper={
    x=[10173, 128],
    train_mask=[10173],
  },
  institution={
    x=[1830, 128],
    train_mask=[1830],
  },
  (author, writes, paper)={ edge_index=[2, 2748] },
  (paper, is_written_by, author)={ edge_index=[2, 2748] },
  (paper, cites, paper)={ edge_index=[2, 79] },
  (paper, is_cited_by, paper)={ edge_index=[2, 79] },
  (author, is_affiliated_with, institution)={ edge_index=[2, 712] },
  (institution, has_affiliated, author)={ edge_index=[2, 712] },
  (author, metapath_0, author)={
    edge_index=[2, 8472],
    edge_weight=[8472],
  },
  (author, metapath_1, author)={
    edge_index=[2, 122],
    edge_weight=[122],
  },
  (author, metapath_2, author)={
    edge_index=[2, 1594],
    edge_weight=[1594],
  }
)

In [35]:
#keep indices of nodes used in test set by online model (mask values=False)

print(AX.shape[0])
new_data['author'].test_mask.count_nonzero() #mask tutti tranni 186 
#prendi gli indici in corrispondenza di false
training_online = torch.masked_select(torch.arange(AX.shape[0]), new_data['author'].test_mask)
print(training_online.shape)
torch.save(training_online, fname_base+'testing_online.pt')

15397
torch.Size([189])

In [67]:
#test set con nodi del test set dell'online model + un numero uguale di nodi unchanged non presenti né in I né in B
#se non presenti in I+B a maggior ragione non presenti nel test set di online

#prendiamo online
indices_online = torch.load(fname_base+'testing_online.pt')
mask_online = torch.zeros(AX.shape[0], dtype=torch.bool)
mask_online[indices_online] = 1
mask_online_opp = ~mask_online
tx = torch.masked_select(torch.arange(AX.shape[0]), mask_online)
print(tx.shape)
   

I = pickle.load(open(fname_base+new+'I.pkl', 'rb'))
B = pickle.load(open(fname_base+base+'B_512.pkl', 'rb'))

#Gli indici True di A sono quelli che si possono prendere, tra cui selezionare i random.
#Quindi vanno messi a true gli indici non presenti in A e in B e non presenti in online.
mask = torch.zeros(AX.shape[0], dtype=torch.bool)
indices_no = list(set(I['authors']+B['authors']))
indices_si = [a for a in range(AX.shape[0]) if a not in indices_no] 
mask[indices_si] = 1
mask = torch.logical_and(mask, mask_online_opp)

#prendiamo random 189 indici tra quelli true di A. 
true_indices_val = torch.masked_select(torch.arange(AX.shape[0]), mask) #tutti indici true di val
sampled_indices = true_indices_val[torch.randperm(true_indices_val.shape[0])[:189]] #prendo 189 valori a caso (sono gli indici che rimarrano True qui)

mask_test_2 = torch.zeros(AX.shape[0], dtype=torch.bool)
mask_test_2[sampled_indices] = 1
testing_2 = torch.masked_select(torch.arange(AX.shape[0]), mask_test_2)
print(testing_2.shape)

mask_test_2 = torch.logical_or(mask_test_2, mask_online) #metto a True indici che posso prendere & indici test online
testing_2 = torch.masked_select(torch.arange(AX.shape[0]), mask_test_2)
print(testing_2.shape)
torch.save(testing_2, fname_base+'testing_online_and_unchanged.pt')

torch.Size([189])
torch.Size([189])
torch.Size([378])

In [39]:
#ONLINE CON SUO TEST

res = pd.read_excel(fname_base+new+'results_online.xlsx')
res

        F1_micro       F1_macro    F1_weighted        ROC-AUC
0       0.280184       0.274059       0.277085       0.672901
1       0.283367       0.275166       0.279129       0.672345
2       0.286095       0.278059         0.2814       0.675729
3       0.288693       0.279408       0.283072       0.673634
4       0.288303       0.279634       0.283667       0.678202
5  0.2853±0.0036  0.2773±0.0025  0.2809±0.0028  0.6746±0.0024

In [64]:
print('Autori eff. training:', new_data['author'].train_mask.count_nonzero())
print('Papers eff. training:', new_data['paper'].train_mask.count_nonzero())
print('Institutions eff. training:', new_data['institution'].train_mask.count_nonzero())

Autori eff. training: tensor(3164, device='cuda:0')
Papers eff. training: tensor(2552, device='cuda:0')
Institutions eff. training: tensor(596, device='cuda:0')

In [61]:
print(new_data['author'].train_mask.count_nonzero())
print(new_data['author'].num_nodes)

print(new_data['paper'].train_mask.count_nonzero())
print(new_data['paper'].num_nodes)

tensor(4357, device='cuda:0')
15397
tensor(2940, device='cuda:0')
10173

In [ ]:
#check num nodi

AP_base = pd.read_csv(fname_base+base+'AP_map.csv')
print('A 2019-2021:', AP_base['author'].drop_duplicates().shape[0])

AP_new = pd.read_csv(fname_base+new+'AP_map.csv')
print('A 2022:', AP_new['author'].drop_duplicates().shape[0])

authors_base = AP_base['author'].drop_duplicates().tolist()
AP_x = AP_new[~AP_new['author'].isin(authors_base)]
print('A 2022 not in 2019-2021:', AP_x['author'].drop_duplicates().shape[0])

In [ ]:
I = pickle.load(open(fname_base+new+'I.pkl', 'rb'))
authors_I = I['authors']

print(len(authors_I))

x = [a for a in authors_I if a not in AP_x['author'].tolist()]
print(len(x))

x2 = [a for a in authors_I if a in AP_x['author'].tolist()]
print(len(x2))

In [1]:
#estract combinations not processed
from itertools import product
import pandas as pd
fname_base = 'DyHANE/'

df1 = pd.read_csv(fname_base+'params_scores.csv')
df2 = pd.read_csv(fname_base+'params_scores_old.csv')
df2.rename(columns={'F1-micro':'F1_micro', 'F1-macro':'F1_macro', 'F1-weighted':'F1_weighted'}, inplace=True)
df = pd.concat([df1, df2], ignore_index=True)
params_ok = df['Params'].tolist()

hyperparameters = {
    'B_size':[512, 2024], #768, 2048, 256
    'dropout':[0.3, 0.4, 0.5, 0.6, 0.7],
    'lr': [0.001, 0.005, 0.01, 0.05],
    'L2': [0.0001, 0.0005, 0.001, 0.005]
}

param_combinations = product(*hyperparameters.values())

params_to_process = [params for params in param_combinations if params not in params_ok]
print(len(params_to_process))

160

In [10]:
import pandas as pd
fname_base='DyHANE/'

df = pd.read_csv(fname_base+'params_scores_all.csv')

#mi serve il df ordinato per valori decrescenti di una metrica

def extract_score(value):
    return float(value.split('±')[0])

df['score'] = df.apply(lambda x: extract_score(x['ROC-AUC']), axis=1)
df_sorted = df.sort_values(by='score', ascending=False)
df_sorted.to_csv(fname_base+'params_scores_all.csv', index=False)
df_sorted.head(20)

,Params,F1_micro,F1_macro,F1_weighted,ROC-AUC,score
248,"(2048, 0.3, 0.01, 0.0001)",0.6818±0.0021,0.6766±0.0018,0.6823±0.0017,0.9561±0.0009,0.9561
244,"(2048, 0.3, 0.005, 0.0001)",0.6792±0.0016,0.6739±0.0014,0.6793±0.0015,0.9525±0.0010,0.9525
264,"(2048, 0.4, 0.01, 0.0001)",0.6809±0.0020,0.6756±0.0021,0.6813±0.0019,0.9512±0.0020,0.9512
260,"(2048, 0.4, 0.005, 0.0001)",0.6770±0.0014,0.6715±0.0012,0.6775±0.0011,0.9510±0.0005,0.9510
245,"(2048, 0.3, 0.005, 0.0005)",0.6678±0.0008,0.6624±0.0008,0.6672±0.0010,0.9509±0.0008,0.9509
84,"(1024, 0.3, 0.005, 0.0001)",0.6734±0.0024,0.6680±0.0023,0.6732±0.0020,0.9484±0.0011,0.9484
240,"(2048, 0.3, 0.001, 0.0001)",0.6460±0.0014,0.6401±0.0014,0.6432±0.0015,0.9477±0.0004,0.9477
276,"(2048, 0.5, 0.005, 0.0001)",0.6722±0.0012,0.6680±0.0011,0.6732±0.0009,0.9468±0.0004,0.9468
249,"(2048, 0.3, 0.01, 0.0005)",0.6738±0.0042,0.6678±0.0033,0.6736±0.0033,0.9465±0.0010,0.9465
168,"(768, 0.3, 0.01, 0.0001)",0.6739±0.0014,0.6684±0.0009,0.6746±0.0011,0.9462±0.0003,0.9462
88,"(1024, 0.3, 0.01, 0.0001)",0.6740±0.0025,0.6678±0.0025,0.6740±0.0025,0.9462±0.0013,0.9462
280,"(2048, 0.5, 0.01, 0.0001)",0.6749±0.0037,0.6704±0.0031,0.6760±0.0031,0.9462±0.0012,0.9462
261,"(2048, 0.4, 0.005, 0.0005)",0.6665±0.0014,0.6600±0.0014,0.6646±0.0014,0.9457±0.0011,0.9457
104,"(1024, 0.4, 0.01, 0.0001)",0.6750±0.0016,0.6696±0.0018,0.6760±0.0020,0.9456±0.0011,0.9456
250,"(2048, 0.3, 0.01, 0.001)",0.6549±0.0013,0.6476±0.0015,0.6512±0.0015,0.9449±0.0007,0.9449
164,"(768, 0.3, 0.005, 0.0001)",0.6727±0.0017,0.6668±0.0014,0.6727±0.0014,0.9446±0.0007,0.9446
246,"(2048, 0.3, 0.005, 0.001)",0.6614±0.0022,0.6543±0.0016,0.6585±0.0017,0.9444±0.0003,0.9444
292,"(2048, 0.6, 0.005, 0.0001)",0.6717±0.0035,0.6669±0.0034,0.6722±0.0035,0.9439±0.0010,0.9439
265,"(2048, 0.4, 0.01, 0.0005)",0.6727±0.0028,0.6657±0.0026,0.6705±0.0029,0.9439±0.0005,0.9439
8,"(512, 0.3, 0.01, 0.0001)",0.6746±0.0015,0.6684±0.0011,0.6740±0.0012,0.9430±0.0010,0.9430

In [11]:
#Analisi dei primi 30
df = pd.read_csv(fname_base+'params_scores_all.csv')
df = df[df['score'] >= 0.94] #32 combinazioni
df

,Params,F1_micro,F1_macro,F1_weighted,ROC-AUC,score
0,"(2048, 0.3, 0.01, 0.0001)",0.6818±0.0021,0.6766±0.0018,0.6823±0.0017,0.9561±0.0009,0.9561
1,"(2048, 0.3, 0.005, 0.0001)",0.6792±0.0016,0.6739±0.0014,0.6793±0.0015,0.9525±0.0010,0.9525
2,"(2048, 0.4, 0.01, 0.0001)",0.6809±0.0020,0.6756±0.0021,0.6813±0.0019,0.9512±0.0020,0.9512
3,"(2048, 0.4, 0.005, 0.0001)",0.6770±0.0014,0.6715±0.0012,0.6775±0.0011,0.9510±0.0005,0.9510
4,"(2048, 0.3, 0.005, 0.0005)",0.6678±0.0008,0.6624±0.0008,0.6672±0.0010,0.9509±0.0008,0.9509
5,"(1024, 0.3, 0.005, 0.0001)",0.6734±0.0024,0.6680±0.0023,0.6732±0.0020,0.9484±0.0011,0.9484
6,"(2048, 0.3, 0.001, 0.0001)",0.6460±0.0014,0.6401±0.0014,0.6432±0.0015,0.9477±0.0004,0.9477
7,"(2048, 0.5, 0.005, 0.0001)",0.6722±0.0012,0.6680±0.0011,0.6732±0.0009,0.9468±0.0004,0.9468
8,"(2048, 0.3, 0.01, 0.0005)",0.6738±0.0042,0.6678±0.0033,0.6736±0.0033,0.9465±0.0010,0.9465
9,"(768, 0.3, 0.01, 0.0001)",0.6739±0.0014,0.6684±0.0009,0.6746±0.0011,0.9462±0.0003,0.9462
10,"(1024, 0.3, 0.01, 0.0001)",0.6740±0.0025,0.6678±0.0025,0.6740±0.0025,0.9462±0.0013,0.9462
11,"(2048, 0.5, 0.01, 0.0001)",0.6749±0.0037,0.6704±0.0031,0.6760±0.0031,0.9462±0.0012,0.9462
12,"(2048, 0.4, 0.005, 0.0005)",0.6665±0.0014,0.6600±0.0014,0.6646±0.0014,0.9457±0.0011,0.9457
13,"(1024, 0.4, 0.01, 0.0001)",0.6750±0.0016,0.6696±0.0018,0.6760±0.0020,0.9456±0.0011,0.9456
14,"(2048, 0.3, 0.01, 0.001)",0.6549±0.0013,0.6476±0.0015,0.6512±0.0015,0.9449±0.0007,0.9449
15,"(768, 0.3, 0.005, 0.0001)",0.6727±0.0017,0.6668±0.0014,0.6727±0.0014,0.9446±0.0007,0.9446
16,"(2048, 0.3, 0.005, 0.001)",0.6614±0.0022,0.6543±0.0016,0.6585±0.0017,0.9444±0.0003,0.9444
17,"(2048, 0.6, 0.005, 0.0001)",0.6717±0.0035,0.6669±0.0034,0.6722±0.0035,0.9439±0.0010,0.9439
18,"(2048, 0.4, 0.01, 0.0005)",0.6727±0.0028,0.6657±0.0026,0.6705±0.0029,0.9439±0.0005,0.9439
19,"(512, 0.3, 0.01, 0.0001)",0.6746±0.0015,0.6684±0.0011,0.6740±0.0012,0.9430±0.0010,0.9430
20,"(1024, 0.3, 0.01, 0.0005)",0.6678±0.0018,0.6620±0.0014,0.6684±0.0015,0.9428±0.0015,0.9428
21,"(2048, 0.3, 0.001, 0.0005)",0.6446±0.0008,0.6355±0.0008,0.6378±0.0009,0.9425±0.0001,0.9425
22,"(2048, 0.4, 0.01, 0.001)",0.6566±0.0019,0.6484±0.0026,0.6521±0.0032,0.9423±0.0010,0.9423
23,"(2048, 0.4, 0.001, 0.0001)",0.6372±0.0008,0.6303±0.0008,0.6329±0.0011,0.9422±0.0003,0.9422
24,"(2048, 0.5, 0.005, 0.0005)",0.6626±0.0034,0.6562±0.0030,0.6617±0.0036,0.9417±0.0009,0.9417
25,"(2048, 0.6, 0.01, 0.0001)",0.6710±0.0016,0.6659±0.0010,0.6717±0.0008,0.9416±0.0019,0.9416
26,"(768, 0.4, 0.005, 0.0001)",0.6682±0.0009,0.6622±0.0013,0.6682±0.0011,0.9414±0.0011,0.9414
27,"(2048, 0.5, 0.01, 0.0005)",0.6637±0.0034,0.6589±0.0026,0.6635±0.0029,0.9412±0.0009,0.9412
28,"(1024, 0.4, 0.005, 0.0001)",0.6700±0.0010,0.6644±0.0009,0.6706±0.0005,0.9404±0.0005,0.9404
29,"(2048, 0.3, 0.001, 0.001)",0.6324±0.0008,0.6230±0.0009,0.6238±0.0010,0.9403±0.0005,0.9403
30,"(2048, 0.5, 0.001, 0.0001)",0.6355±0.0013,0.6276±0.0012,0.6296±0.0014,0.9402±0.0004,0.9402
31,"(2048, 0.4, 0.005, 0.001)",0.6497±0.0009,0.6424±0.0012,0.6456±0.0014,0.9401±0.0008,0.9401

In [13]:
import pickle
I = pickle.load(open('DyHANE/2022/I.pkl', 'rb'))
print(len(I['authors']))
print(len(I['papers']))
print(len(I['institutions']))

3409
1817
525

In [5]:
import pickle
B = pickle.load(open('DyHANE/2019-2021/B_1024.pkl', 'rb'))
print(len(B['authors']))
print(len(B['papers']))
print(len(B['institutions']))

74
377
61